### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by dandv** [asbru-cm/asbru-cm#1]
Adding screenshots to the README and the website would be super helpful!

Then we can add the project to [AlternativeTo.net](https://alternativeto.net/software/pac-manager/).

**Comment by gfrenoy** [comment]
Indeed :)  Any suggestion on the screenshot that would be describe the software ?  Thanks!

**Comment by gfrenoy** [comment]
Screenshots added to https://www.asbru-cm.net/
(see 785927154ac2b6ad0a3f707e31682c5bb50bd837)
