### ISSUE TITLE
 Canceling user input dialogs for expect produces an error message

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#10]
When I have an expect entry for a SSH connection which asks for user input and I cancel it, it writes the following error messages to the terminal:
```
Use of uninitialized value $cmd_str in substitution (s///) at /opt/asbru/lib/pac_conn line 1532.
Use of uninitialized value $cmd_str in concatenation (.) or string at /opt/asbru/lib/pac_conn line 1533.
```

For me it's a bit unclear what's expected to happen if you cancel or just [X] the dialog? Should asbru-cm just stop there and leave the user on a half initialized shell in an unknown state? Should the whole SSH connection be dropped?

Maybe it doesn't make sense to cancel the dialog and the user should be forced to enter something, or have a button labeled "disconnect" instead of "cancel".

**Comment by gfrenoy** [comment]
No sure either :-/  Actually I'm not sure to understand your example correctly ; can you give more details about the expect script your are using ?

**Comment by gfrenoy** [comment]
@nomike Any more comment to clarify this issue ?  Can we consider it closed ?

**Comment by nomike** [comment]
Steps to reproduce:
1. Create a new entry and call it "Issue#10"
1.1. Configure it as "SSH" and connect to a host you are able to connect to
1.2. Add an entry to "expect" with the following parameters:
    Expect: <command prompt>
    Send: echo "<ASK:number>"
2. Double click the connection entry to connect to the server.
3. When you are prompted for the input, cancel the dialog ("Cancel", "X", or <esc>)

Then you get an error message in the terminal which I believe shouldn't be there.

But I also have no Idea what should happen if you cancel? Maybe the connection should be terminated.

**Comment by gfrenoy** [comment]
Thanks for the additional explanations !  The issue is now very clear :)

I also think the connection should fail if user cancels one of the data entry.  I'll make the change in the code.
