### ISSUE TITLE
make the "Info" tab always visible.

### ISSUE THREAD

**Issue by Charlietje** [asbru-cm/asbru-cm#100]
This is a feature request:

Make the "Info" tab always visible.
When I have many connections open, the info tab disappears.
On the info tab, I keep relevant information of the connection, but when I need to look for the info tab, the focus is not on the connection I need, so the information is not relevant.
If the info tab would be persistent, I could click on it, and have all the relevant information.

If the tab can not be made persistent, maybe a short cut to jump to the info tab would also be helpfull.

**Comment by gfrenoy** [comment]
Interesting.  Not sure this is an option of the [Gtk2 Notebook object](https://developer.gnome.org/gtk2/stable/GtkNotebook.html) though so I don't know how we could do this.

Maybe an alternative option would be to add an "Info" button in the bottom bar ?

**Comment by Charlietje** [comment]
The alternative "Info" button in the bottom bar option would also be
interesting!


Op zo 29 jul. 2018 om 12:21 schreef Gaëtan Frenoy <notifications@github.com

**Comment by gfrenoy** [comment]
I'll commit a change that will had an icon in the bottom bar.  I also added the shortcut key "Ctrl+Shift+I" so you don't even need an icon :)

![image](https://user-images.githubusercontent.com/981546/43369201-0b375684-936a-11e8-8314-485f24723489.png)

Will you give it a try and give a feedback using our snapshot build ?

**Comment by Charlietje** [comment]
That looks good!
The short cut (ctrl-shift-i) with ctrl-tab (last focused option) works great.
Thanks
