### ISSUE TITLE
Flatpak support maybe?

### ISSUE THREAD

**Issue by JurijOrlow** [asbru-cm/asbru-cm#1000]
I (and I am sure a lot of people too) are pleased with idea of Flatpaks - fast, secure, distro-agnostic, easier to install than normal applications. Why not add the best (in my opinion) connection manager to Flathub? For now it's the only thing that stops me from going to immutable distro, like Fedora Silverblue - I need Asbru for my work.
I would do it myself, but sadly, I'm lacking skills and knowledge on how to do that :(

**Comment by gfrenoy** [comment]
Thanks for your suggestion, see #83.

And why our standard [Fedora repository](https://github.com/asbru-cm/asbru-cm/wiki/installation-on-fedora) or our new [AppImage](https://www.appimagehub.com/p/1796061) would not work for you ?
