### ISSUE TITLE
Asbru 6.4 *buntu 22: Expect not working?

### ISSUE THREAD

**Issue by Aerya** [asbru-cm/asbru-cm#1001]
Hi,

Seems it can't catch any macthing expression at SSH login. It worked weel on previous build, didn't change anything.
Thanks for help.

**Screenshots**
![ ](https://i.imgur.com/Eeukt5H.png)
![ ](https://i.imgur.com/AwrPz9X.png)
![ ](https://i.imgur.com/tfu1XMR.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Ásbrú 6.4.0

**Additional context**
Complete logs: https://pastebin.com/RCVFR5HB

**Comment by gfrenoy** [comment]
The "Welcome" message is processed before the Expect begins.  It may have worked before but that's not the way to go.

Try to use `<command prompt>` as first expect.  It's probably what you are looking for and we will work more reliably.

**Comment by Aerya** [comment]
Thanks, that works.
