### ISSUE TITLE
motd and expect trouble

### ISSUE THREAD

**Issue by barthoosh** [asbru-cm/asbru-cm#1003]
**Describe the bug**
After succesful login I try to change account via expect. When the "PrintMotd yes" directive is set in sshd_config and motd is not empty, first expect clause preform "su - name" command, and second expect clause does not catch password prompt. Without motd set expect is working.

**To Reproduce**
1. Set /etc/motd with few lines of text on remote system
2. Set /etc/ssh/sshd_config dirctive "PrintMotd yes" on remote system and restart sshd
3. Set 1st expect clause with Expect pattern: "$"  and Send pattern "su -" 
4. Set 2nd expect clause  with Expect pattern: ":"  and Send pattern "topsecretrootpass"
5. Execute connection. 2nd expect clause hangs on password prompt

**Expected behavior**
Account changed to root after connection.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS (Focal Fossa) 
 - Ásbrú Version 6.3.3-1

**Comment by gfrenoy** [comment]
Did you to use <command prompt> as first expect. It's probably what you are looking for and we will work more reliably.
