### ISSUE TITLE
Non working Dark mode with Ubuntu 22.10

### ISSUE THREAD

**Issue by M3sSi4z** [asbru-cm/asbru-cm#1005]
**Describe the bug**
I upgraded to Ubuntu 22.10 and since that, asbru cm use always light-theme even though my ubuntu appearance is set to dark and even i change asbru cm icons theme to asbru-dark it remains with white background etc. I did a restart after the change. 

**To Reproduce**
1. Start Asbru cm
2. Go to "Settings"
3. Go to "Main Options"
4. Go to "Behaviour"
5. select "asbru-dark"
6. select "save and close"
7. exit asbru cm
8. start asbru cm

**Expected behavior**
asbru cm use dark theme and background etc. is dark 

**Screenshots**
![Bildschirmfoto vom 2022-12-10 08-49-41](https://user-images.githubusercontent.com/12097104/206839447-af3a2437-bc0d-46b6-99f0-b205ccb1779f.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.10
 - Ásbrú Version 6.4.0

**Additional context**

**Comment by syco** [comment]
![Screenshot from 2023-01-19 16-49-35](https://user-images.githubusercontent.com/54575/213512501-4dbc15c9-8e3a-4c9e-9103-3a911bd3a26e.png)
I don't know about ubuntu specifically, but in gnome you need to open `gnome-tweaks`, got to `Appearance` and change the `Legacy Applications` theme.

**Comment by M3sSi4z** [comment]
Hi, yeah, that's it! Didn't know that "gnome-tweaks". I wonder, why is this options not integrated in Ubuntu Settings app. 
Thanks syco!
