### ISSUE TITLE
Unable to negotiate with XXX.XXX.XXX.XXX port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss

### ISSUE THREAD

**Issue by gianpy** [asbru-cm/asbru-cm#1008]
Hi
Im tryng to connect to a  server with ssh-dss algorithm using command line I normally use "-oHostKeyAlgorithms=+ssh-dss" between ssh command and host name but I cant find a way to put this options in Asbru.

Environment:
Linux mint 21

**Comment by popxunga** [comment]
Hi ...
Edit Connection -> SSH Option (on the left menu) -> Advanced Options

![image](https://user-images.githubusercontent.com/37672088/211096200-1a27aa70-b074-444c-85c2-85a9c95968ca.png)

**Comment by gianpy** [comment]
Great, thank you
