### ISSUE TITLE
abru doesn't start from Cinnamon menu

### ISSUE THREAD

**Issue by toni-az** [asbru-cm/asbru-cm#101]
Manjaro Cinnamon:

- installation via aur - no problem
- I can start the application from CLI
- when I try to start from the Menu,  panel launcher, autostart after login, nothing happens.

Is there any way  to troubleshoot? Does it write to a log file? Or can I start a debug mode?

**Comment by gfrenoy** [comment]
I'd start by looking at the .desktop file.

That being said, you may want to first contact the AUR packager though (https://aur.archlinux.org/packages/asbru-cm-git/) ; they would probably better support the way Ásbrú has been packaged on their platform.

**Comment by toni-az** [comment]
thanks for the tip

actually the issue was in bad environment setup during installation which put perl libraries to my home dir, after fixing variables and reinstallation of asbru and all dependencies all started working ok

So it wasn't an issue of your software but the issue of arch architecture combined with my bad configuration
