### ISSUE TITLE
script executes, repo not suitable for Rocky Linux 9

### ISSUE THREAD

**Issue by commandline-be** [asbru-cm/asbru-cm#1010]
**Is your feature request related to a problem? Please describe.**

Using the Fedora install script from https://www.asbru-cm.net/ the script executes fine but does not load with Rocky Linux 9(.1) which is similar to Fedora 35. The fail is because of the below where .../el/9/ is not suitable to load Fedora 35

    [asbru-cm-release]
    name=asbru-cm-release
    baseurl=https://dl.cloudsmith.io/public/asbru-cm/release/rpm/el/9/$basearch
    repo_gpgcheck=1
    enabled=1
    gpgkey=https://dl.cloudsmith.io/public/asbru-cm/release/gpg.7684B0670B1C65E8.key
    gpgcheck=1
    sslverify=1
    sslcacert=/etc/pki/tls/certs/ca-bundle.crt
    metadata_expire=300
    pkg_gpgcheck=1
    autorefresh=1
    type=rpm-md
.....

**Describe the solution you'd like**

> Modify the script to alert on RPM but not supported such as for Fedora with the option to use the Fedora settings anyway. 
> Support Rocky Linux 

**Describe alternatives you've considered**

none, curious to try asbru-cm when looking for a commercial/supported linux ssh connection manager

**Additional context**

**Comment by gfrenoy** [comment]
See #894
