### ISSUE TITLE
High CPU usage, makes whole system slow on Kubuntu

### ISSUE THREAD

**Issue by dakorpar** [asbru-cm/asbru-cm#1018]
**Describe the bug**
X11 becomes super slow as soon as I start asbru

**To Reproduce**
As soon as I start asbru whole system becomes a but unresponsive...
![image](https://user-images.githubusercontent.com/9303856/221195020-1cff8ae7-5211-40b6-8cb6-b5d1c7e5f311.png)
as soon as I close everything works fine... Even when I type this bug report I get delay of 1 second and I have pretty strong Ryzen 7 pro laptop 

**Expected behavior**
it shouldn't slowdown whole system

**Screenshots**

**Environment (please complete the following information):**
 - OS: Kubuntu 22.04.1 LTS
 - Ásbrú Version: 6.4.0

**Additional context**
Here is terminal output:
asbru-cm 
```
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 31052
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : other
INFO: Config directory is '/home/dalibor/.config/asbru'
INFO: Used config file '/home/dalibor/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.68
GLib-GObject-WARNING **: invalid (NULL) pointer instance at /opt/asbru/lib/PACMain.pm line 4924.
GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed at /opt/asbru/lib/PACMain.pm line 4924.
INFO: Theme directory is '/opt/asbru/res/themes/default'
INFO: Trying to loading Unity specific tray icon package...
WARNING: AppIndicator is missing --> there might be no icon showing up in the status bar when running Unity!
INFO: Using Gnome tray icon

```

**Comment by gfrenoy** [comment]
Obviously, this is not the standard and desired behaviour.  There must be something special in your installation.

You may want to start from a "clean" profile and then troubleshoot the differences to understand what is causing this.
