### ISSUE TITLE
TAB COLORS / HOST COLORS

### ISSUE THREAD

**Issue by bsdrazor** [asbru-cm/asbru-cm#1023]
**HEY There**
I'm using ACM for a lot of years. My question is  it possible to mark the hosts/tabs with different colors somehow in connection settings. If that option already exists please take me an advice where to find it. Thank you all for your great work!
Glory to Ukraine!

**Comment by gfrenoy** [comment]
Yes, in "Termain Options", there is already an option "Use this tab backgrournd color":

![image](https://github.com/asbru-cm/asbru-cm/assets/981546/90415e39-6d92-4c58-91fb-1a4b7a5b7a95)
