### ISSUE TITLE
Crash on start after upgrade 6.3.3 to 6.4.0

### ISSUE THREAD

**Issue by necarnot** [asbru-cm/asbru-cm#1026]
**Describe the bug**
asbru-cm is crashing on start after having upgraded from 6.3.3 to 6.4.0

**To Reproduce**
1. Use asbru-cm since years, without a single issue. Using around 100+ connections sorted in a nice folders tree.
2. Upgrade to 6.4.0
3. Launching asbru-cm (either with icon click or via CLI "asbru-cm --verbose") is launching asbru-cm which is appearing and immediately shutting down

**Expected behavior**
Get the same asbru-cm as before, with my previous connections settings

**Screenshots**
```bash
$ asbru-cm 
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 12191
INFO: Language detected : fr_FR.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : xfce
INFO: Config directory is '/home/xxx/.config/asbru'
INFO: Used config file '/home/xxx/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.68
GLib-GObject-WARNING **: invalid (NULL) pointer instance at /opt/asbru/lib/PACMain.pm line 4924.
GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed at /opt/asbru/lib/PACMain.pm line 4924.
INFO: Theme directory is '/opt/asbru/res/themes/system'
INFO: Trying to loading Unity specific tray icon package...
INFO: Using Unity tray icon
INFO: Finishing (asbru-cm) with pid 12191
INFO: Finished Ásbrú Connection Manager 6.4.0 (asbru-cm) (PID:12191)...
```

**Environment (please complete the following information):**
 - OS: XUbuntu 22.04.2 LTS
 - Ásbrú Version : 6.4.0

**Additional context**
Completely removing the ~/.config/asbru folder and re-launching asbru leads to a working state, but obviously with an empty folders tree, which would be painful.

I also tried to vimdiff/compare the asbru.yml file of the 6.3.3 and 6.4.0 versions, trying to focus on what would lead to a crash, to no avail.

**Comment by apanasis** [comment]
Same behavior asbru-cm 6.4.0
OS Arch linux

**Comment by liprox** [comment]
HI,

we have workaround with this downgrade:
https://github.com/asbru-cm/asbru-cm/issues/1035#issuecomment-1553200535
this works for us,
thank you

**Comment by liprox** [comment]
perhaps the newest version also works again, have a look at:
https://github.com/asbru-cm/asbru-cm/issues/1035#issuecomment-1583828581
 regards

**Comment by apanasis** [comment]
Yes! it works.
Thanks)

**Comment by malavolti** [comment]
Distribution:
- Ubuntu 22.04.3 LTS (jammy)

APT packages:
- asbru-cm (version 6.4.0-1)
- libglib-object-introspection-perl (version 0.049-1+build2 amd64)

Error:

```bash
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 7105
INFO: Language detected : it_IT.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : gnome-shell:ubuntu
INFO: Config directory is '/home/mala/.config/asbru'
INFO: Used config file '/home/mala/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.68
GLib-GObject-WARNING **: invalid (NULL) pointer instance at /opt/asbru/lib/PACMain.pm line 4924.
GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed at /opt/asbru/lib/PACMain.pm line 4924.
INFO: Theme directory is '/opt/asbru/res/themes/default'
INFO: Trying to loading Unity specific tray icon package...
INFO: Using Unity tray icon

(asbru-cm:7105): GVFS-WARNING **: 11:11:11.332: The peer-to-peer connection failed: Timeout was reached. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
```

Asbru-CM doesn't work. :(

Can you help me, please?

**Comment by malavolti** [comment]
I have restored the v6.3.3-1 and it works. I'll wait to upgrade to the 6.4.0 until the problem it will be fixed.

**Comment by gfrenoy** [comment]
Looks like a dependency issue ; if needed please re-open a new issue with details about your configuration.
