### ISSUE TITLE
Error maping keyboard Ctrl left on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by nguyentthai96** [asbru-cm/asbru-cm#1028]
**Describe the bug**
When I remote to windows and Ctrl+C to copy or anny task using Ctrl not work, similar Ctrl maping Alt, 
button Alt working normal

But Ctrl right then okay.

I using version last and have try update.
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
sudo apt-get install asbru-cm

**Comment by gfrenoy** [comment]
Which rdp client are you using ?
