### ISSUE TITLE
Fedora 38 build 

### ISSUE THREAD

**Issue by TimmiORG** [asbru-cm/asbru-cm#1029]
Hi,

please provide a build for Fedora 38 in future.

THX

**Comment by gfrenoy** [comment]
If someone wants to help on this:

Check this --> https://github.com/asbru-cm/asbru-cm/blob/master/.travis.yml

As the pack pack project is not publishing an image for F38, you may need to provide your own.

This can help --> https://github.com/asbru-cm/packpack-docker-images

**Comment by gfrenoy** [comment]
And don't forget this is the same package for all distributions ... You can just override the automatic detection of the installer.  See https://github.com/asbru-cm/asbru-cm/issues/861#issuecomment-1001556672 for an example.

**Comment by Bert-H** [comment]
@gfrenoy, I have successfully created an RPM package for Fedora39.
Tested this on a dedicated FC39 VM and it worked just fine.
Happy to contribute this to the project. Let me know how.

Thanks for all the work you do in keeping this project alive.

**Comment by klemenkobetic** [comment]
Anything new here? F39 is also out!

**Comment by KlaasT** [comment]
I just added the matrix entries for the F38 and F39 as packpack is now delivering docker images to build.

However the build jobs are not running through the pipeline right now. I created a support ticket for that and hope it will run as soon as possible.

**Comment by KlaasT** [comment]
@klemenkobetic Good news. The build was successful and Fedora 38 and 39 packages are now available in the snapshots repository.

**Comment by klemendlabs** [comment]
Will there be a new official version? 6.4.0 was release...in 2022.
