### ISSUE TITLE
FreeBSD login

### ISSUE THREAD

**Issue by baka44** [asbru-cm/asbru-cm#104]
There is error while freebsd autologin/login processing.
Go **Preferences** -> **Advanced** -> **PASSWORD prompt:**
Edit regex:
 `([p|P]ass|[p|P]ass[w|W]or[d|t](\s+for\s+)*|[c|C]ontrase.a|Enter passphrase for key '.+')\s*:\s*$`
to
 `([p|P]ass|[p|P]ass[w|W]or[d|t](\s+for\s+|\w+@\w+)*|[c|C]ontrase.a|Enter passphrase for key '.+')\s*:\s*$`
now its works fine.
Your project is awesome, thanks.

**Comment by gfrenoy** [comment]
Thanks for your suggestion !

Any idea if this may have some impact on other systems ?  Or this is fully compatible with what we have now (I mean: is this "regression free") ?

**Comment by baka44** [comment]
Not pretty sure, we aretesting it with my employees, seems well for now.

**Comment by gfrenoy** [comment]
Ok let me change it on my environment and test it for a while ; then I'll change the default value for the next version.

Thanks again for your contribution, these are making the project great :)

**Comment by gfrenoy** [comment]
This change is not available in the latest release.

**Comment by gfrenoy** [comment]
Please check if the `Password Prompt` regular expression is matching yours.
(and open a new case with details of your issue, please ; this one is closed)
