### ISSUE TITLE
when i open a connection the app closes

### ISSUE THREAD

**Issue by Vincenzoferrara** [asbru-cm/asbru-cm#1044]
as the title suggests when I double click both an ssh and rdp connection the app closes

**Environment (please complete the following information):**
 - OS: [manjaro linux kde (arch)]
 - Ásbrú Version [6.4.0.r5   aur name: asbru-cm-git]

**Comment by ikabod** [comment]
Same here with asbru-cm version 6.4.0-1 and Manjaro XFCE.

Right click on connection also close the app.

**Comment by ikabod** [comment]
Could fix it with the help of this site:
https://aur.archlinux.org/packages/asbru-cm

1. install "downgrade"
2. run in a terminal the command "sudo DOWNGRADE_FROM_ALA=1 downgrade perl-glib-object-introspection"
3. choose the latest version with number "12"

If this is not working, try a older version.
