### ISSUE TITLE
INFO: Language detected : de_DE.UTF-8, forcing to en_US.UTF-8

### ISSUE THREAD

**Issue by liprox** [asbru-cm/asbru-cm#1046]
HI,
this is not a Bug and it is not a feature thing .... ???

the last time I connect to Windows server with asbru-cm, always with RDP, **xfreerdp**, windows show the language switch beside the sys-tray clock and is set to EN for English. This is a german installation. We need the german (DE) keyboard layout.
If I start asbru on command line, I get this output:
`INFO: Language detected : de_DE.UTF-8, forcing to en_US.UTF-8`
How and where is the setting for ?:
`forcing to  "de_DE.UTF-8"` 

And:
I know the `Keyboard Layout setting: 0x00000407` and alternatively the "other Option:" parameter ` /kbd-lang:0x0407`  
But this settings you have to deal with every single connection ....
I'm looking for "one size fits all" 

Thanks and regards
from germany

**Comment by gfrenoy** [comment]
See https://github.com/asbru-cm/asbru-cm/blob/7a3e8839e9fab2ae881ddfc32ee06eaa7f6962cb/asbru-cm#L144
(and line 123 above)

`de_DE.UTF-8` comes from the environment variable "LANG" and it is forced to `en_US.UTF-8` today because other locales are not always properly supported (see #748).

**Comment by liprox** [comment]
Hi Gaëtan,

thank you for the answer, then we can close this question,

regards,
 gerd
