### ISSUE TITLE
edit name 

### ISSUE THREAD

**Issue by Vincenzoferrara** [asbru-cm/asbru-cm#1047]
when i search for apps i look for "asbru" without accents

also add the protocols used in the name e.g. (rdp, ssh, etc.)

example: Asbru Connection Manager (ssh, rdp)

this name is used to facilitate the search for the app.
so have the search name one way and the app name another (should be possible)

that being said great project :)

my system language is Italian

nome = name
programma = program

![Screenshot_20230703_182333](https://github.com/asbru-cm/asbru-cm/assets/64591523/bea9c109-e047-42b0-808e-4816479f9324)

**Comment by gfrenoy** [comment]
The correct spelling for Ásbrú is ... Ásbrú :)
A search tool can ignore the accents while searching but there is no reason to ignore the accents, they mean something.

That being said, feel free to propose any PR to improve [the desktop file](https://github.com/asbru-cm/asbru-cm/blob/master/res/asbru-cm.desktop).

And thanks a lot for the compliments and the suggestions !
