### ISSUE TITLE
SSH CONNECTION REQUIRES COMBINED KEY INTERACTION (CTRL+Y) after auth.

### ISSUE THREAD

**Issue by HmiloH** [asbru-cm/asbru-cm#1049]
Hi friends,
After the authentication is done my device (switch) shows a welcome message, that's where I have to press CTRL+Y to show the prompt. My question is where can I perform this interaction from asbru?
Its possible?
Thanks for helps.
Milo
![image](https://github.com/asbru-cm/asbru-cm/assets/139565542/bca17d5d-9448-4906-a72e-42784f262bca)

**Comment by gfrenoy** [comment]
I would first try with the "Expect" feature.  See https://docs.asbru-cm.net/Managing/Expect/.  Not sure how to simulate Ctrl+Y in the sent text, though.
