### ISSUE TITLE
Retrieve terminal method inside scripts

### ISSUE THREAD

**Issue by syco** [asbru-cm/asbru-cm#105]
Hi,
I'm using the script functionality in Connection -> Advanced parameters.
I had a look at the examples and this is what I've got:
```
our ( %COMMON, %PAC, %TERMINAL, %SHARED );
sub CONNECTION {
  $TERMINAL{send}("unset HISTFILE; echo 'good morning'\n");
  return 1;
}
return 1;
```
my problem now is that this script runs also when I right click on the terminal and open a sftp window.
Is there a variable I can check to know the type of connection?
Thanks

**Comment by gfrenoy** [comment]
As far as I can see, there is no way to retrieve the terminal method inside the script.

So I've added it to the ```%TERMINAL``` map, you can retrieve it with the ```method``` key, here's an example on how to use it:

```
our ( %COMMON, %PAC, %TERMINAL, %SHARED );
sub CONNECTION {
  if ( $TERMINAL{method} eq 'ssh' ) {
    $TERMINAL{send}("unset HISTFILE; echo 'good morning'\n");
  }
  if ( $TERMINAL{method} eq 'sftp' ) {
    // Do something else
  }
  return 1;
}
return 1;
```

To test this, you'll need to get the latest snapshot...
