### ISSUE TITLE
Fail to setup the repo: 'does not have a Release file'

### ISSUE THREAD

**Issue by Candide7** [asbru-cm/asbru-cm#1053]
Hello I'm trying to run your 2 CLI installer but fail at first.
Any help please? (note that the appimage maunch fails on Could not locate symbol app_indicator_new at /tmp/.mount_asbru-mXC53S/opt/asbru-cm/lib/PACTrayUnity.pm line 151.) 

curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=22.04  codename=jammy  arch=x86_64  
 >>>>:
 NOPE: Checking for apt dependency 'apt-transport-https' ...
 NOPE: Updating apt repository metadata cache ...
Failed to update via apt-get update
Hit:1 https://apt.releases.hashicorp.com jammy InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:3 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:4 https://updates.signal.org/desktop/apt xenial InRelease
Hit:5 https://ppa.launchpadcontent.net/cappelikan/ppa/ubuntu jammy InRelease
Get:6 https://packages.microsoft.com/repos/ms-teams stable InRelease [5 931 B]
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:8 https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Err:10 https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy Release
  404  Not Found [IP: 2620:2d:4000:1::3e 443]
Hit:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:12 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists...
E: The repository 'https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy Release' does not have a Release file.
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact asbru-cm for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/asbru-cm/asbru-cm
 !!!!:

Environment: Ubuntu 22.04.3

Thank you.

**Comment by gfrenoy** [comment]
> E: The repository 'https://ppa.launchpadcontent.net/oguzhaninan/stacer/ubuntu jammy Release' does not have a Release file.

During the install process, an apt update is done and your local installation causes errors to the upate.

Please fix your system and try again.
