### ISSUE TITLE
modify connect timeout variable to >100s

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#1055]
Hi!  

Connect timeout can be set max to 100s.
My desired value is 600s.

Since I use script (aka prepend command) to check connection availability (on target host) before connecting.. I would be able to run my script for longer than 100s ;)

**Comment by gfrenoy** [comment]
Which timeout are you referring to ... Can you please be more specific ?

**Comment by vibo69** [comment]
Hello! In global preferences,  terminal options, time to connect

**Comment by gfrenoy** [comment]
Ok I found the place where to change this ; will push the change to the loki branch in a minute.
