### ISSUE TITLE
How to open VNC session in tab?

### ISSUE THREAD

**Issue by Hi-Timofey** [asbru-cm/asbru-cm#1058]
When I open VNC session it's always open another window for it.

Is there any way to make VNC connection apper in tab like any other connection? 

P.S.: If it's not supposed to be like that, I'm ready to send logs.

**Comment by gfrenoy** [comment]
First, this will likely depend on the VNC cllent you are using.  Don't believe they all offer all the necessary options to do so (I did not check, to be verified).

Then, probably the "clean" solution is stop using several different clients but to have the integration with gtk-vnc, see #297.

So well, the short answer is no, I do fear.
