### ISSUE TITLE
Installing on fedora not working

### ISSUE THREAD

**Issue by binnih** [asbru-cm/asbru-cm#106]
I run the install command you show on your webpage for Fedora and the result is this.

"Dependencies resolved.
Nothing to do.
Complete!
Generating yum cache for asbru-cm_asbru-cm...

The repository is setup! You can now install packages.
[user@computer ~]$ sudo dnf install asbru-cm 
Last metadata expiration check: 0:00:17 ago on Fri 17 Aug 2018 00:39:26 GMT.
No match for argument: asbru-cm
Error: Unable to find a match
"

If I try searching for it this is all i get

"[user@computer ~]$ sudo dnf search asbru
Last metadata expiration check: 0:01:50 ago on Fri 17 Aug 2018 00:39:26 GMT.
No matches found.
"

**Comment by binnih** [comment]
This is on F28

**Comment by gfrenoy** [comment]
Project [packpack](https://github.com/packpack/packpack) looks to be on hold and I don't see fedora-28 in the list of available images on https://hub.docker.com/r/packpack/packpack/tags/ ...

Not sure how to build Ásbrú for the newest operating systems, if anyone has a clue...Help will be greatly appreciated.

**Comment by gfrenoy** [comment]
Thanks @KlaasT ; just tried and it now works fine from the snapshot repository :)

To give it a try, use:

    curl -s https://packagecloud.io/install/repositories/asbru-cm/snapshots/script.rpm.sh | sudo bash
    sudo dnf install asbru-cm

Whenever we release the next version, it will be included in the main repository.

**Comment by Frankstar** [comment]
just to clarify - it works great from the snapshot.

**Comment by wixaw** [comment]
Hi
Thanks for the fork !
I will post my problem here (https://github.com/perseo22/pacmanager/issues/72) here when ASBRU will work on my workstation

PAC Manager 4.5.5.7-2 work for Centos 7 but 5.1.0-1 have dependency issues

```
[root@host ~]# yum localinstall asbru-cm-5.1.0-1.fc27.noarch.rpm 
Modules complémentaires chargés : fastestmirror, langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Examen de asbru-cm-5.1.0-1.fc27.noarch.rpm : asbru-cm-5.1.0-1.fc27.noarch
Sélection de asbru-cm-5.1.0-1.fc27.noarch.rpm pour installation 
Résolution des dépendances
--> Lancement de la transaction de test
---> Le paquet asbru-cm.noarch 0:5.1.0-1.fc27 sera installé
--> Traitement de la dépendance : perl(Gtk2::AppIndicator) pour le paquet : asbru-cm-5.1.0-1.fc27.noarch
Loading mirror speeds from cached hostfile
 * base: miroir.univ-paris13.fr
 * epel: fr2.rpmfind.net
 * extras: fr2.rpmfind.net
 * nux-dextop: mirror.li.nux.ro
 * remi-safe: fr2.rpmfind.net
 * updates: fr2.rpmfind.net
--> Traitement de la dépendance : perl(Gtk2::SourceView2) pour le paquet : asbru-cm-5.1.0-1.fc27.noarch
--> Traitement de la dépendance : perl(HTTP::Proxy) pour le paquet : asbru-cm-5.1.0-1.fc27.noarch
--> Traitement de la dépendance : perl-Gnome2-Vte pour le paquet : asbru-cm-5.1.0-1.fc27.noarch
--> Lancement de la transaction de test
---> Le paquet asbru-cm.noarch 0:5.1.0-1.fc27 sera installé
--> Traitement de la dépendance : perl(Gtk2::AppIndicator) pour le paquet : asbru-cm-5.1.0-1.fc27.noarch
--> Traitement de la dépendance : perl(Gtk2::SourceView2) pour le paquet : asbru-cm-5.1.0-1.fc27.noarch
--> Traitement de la dépendance : perl(HTTP::Proxy) pour le paquet : asbru-cm-5.1.0-1.fc27.noarch
---> Le paquet perl-Gnome2-Vte.x86_64 0:0.11-3.el7.nux sera installé
--> Résolution des dépendances terminée
Erreur : Paquet : asbru-cm-5.1.0-1.fc27.noarch (/asbru-cm-5.1.0-1.fc27.noarch)
             Requiert : perl(Gtk2::SourceView2)
Erreur : Paquet : asbru-cm-5.1.0-1.fc27.noarch (/asbru-cm-5.1.0-1.fc27.noarch)
             Requiert : perl(Gtk2::AppIndicator)
Erreur : Paquet : asbru-cm-5.1.0-1.fc27.noarch (/asbru-cm-5.1.0-1.fc27.noarch)
             Requiert : perl(HTTP::Proxy)
 Vous pouvez essayer d'utiliser --skip-broken pour contourner le problème
 Vous pouvez essayer d'exécuter : rpm -Va --nofiles --nodiges
```

Thank's

**Comment by gfrenoy** [comment]
@wixaw Please stay on topic ; this issue is related to Fedora.

**Comment by BeZazz** [comment]
Same issue on Fedora 29 but the snapshot above did not work.

**Comment by gfrenoy** [comment]
Build for Fedora 29 is now available in the snapshot repository.

**Comment by gfrenoy** [comment]
The latest release [(5.2)](https://github.com/asbru-cm/asbru-cm/releases/tag/5.2.0) can now be installed on Fedora 29, see [specific instructions](https://github.com/asbru-cm/asbru-cm/wiki/installation-on-fedora).

**Comment by x-wolverine-x** [comment]
Try with https://li.nux.ro/repos.html there should be all needed packages so far.

**Comment by gablex** [comment]
I can't start pac on fedora 35 running Gnome 41 and Xorg , the error is

INFO: Ásbrú Connection Manager 6.3.3 (asbru-cm) started with PID 209381
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : gnome-shell:gnome-xorg
INFO: Config file lost or corrupted, trying to recover a previous configuration file...
ERROR: You have no valid configuration file to load!
ERROR: Please inspect /home/martinkarari/.config/asbru/asbru.yml manually. at /usr/bin/asbru-cm line 296.
