### ISSUE TITLE
[Feature Request] Popup search box with drop-down list of matching connections

### ISSUE THREAD

**Issue by YahiaJr** [asbru-cm/asbru-cm#1060]
Sometimes the connections list side-panel needs to be hidden in order to make better room for content of the current session to be shown.

My request here since I find my self always hiding it and only getting back to it whenever I need to open another session from the list, is for a shortcut to be available that when triggered a popup search box appears in the center of the screen, and when you start typing in it a text that matches part of names of some connections, they appear below the search box as a drop-down list that can be navigated with keyboard or clicked with a mouse.

**Comment by gfrenoy** [comment]
Would be "nicer" yes but really a lot of things to change to achieve this.

Moreover, there is fair workaround, I think: Alt+N and the Ctrl+F and then Alt+N again.

(alt+N = hiden/show the list ; Ctrl+F = search for connection in the list)
