### ISSUE TITLE
Zoom In/Out text do not seem to work

### ISSUE THREAD

**Issue by guidozualdi** [asbru-cm/asbru-cm#1061]
**Describe the bug**
Zoom In/Out text do not seem to work

**To Reproduce**
1) Check key bindings **Zoom in text** and **Zoom out text**, in my configuration are:
```
Terminal    Zoom in text       Ctrl+plus
Terminal    Zoom out text      Ctrl+minus
```
2) Open a local shell
3) Try to use one of these key combinations.

**Expected behavior**
Text should change dimension, but these commands seems to be ignored.

**Environment **
 - OS: Garuda Linux fully updated + KDE + Kernel 6.5.7-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sun, 15 Oct 2023 22:10:35 +0000 x86_64 GNU/Linux
 - Ásbrú Version 6.4.0 (aur/asbru-cm)

**Additional context**
I don't know exactly when these bindings stopped working. Some months ago, on a Debian 11 with Mate, these bindings were working, I don't remember if they ever worked on Garuda. These bindings do not work even on a clean asbru-cm configuration. By launching asbru with --verbose there is little output
```
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 48566
INFO: Language detected : it_IT.UTF-8, forcing to en_US.UTF-8
INFO: Path for temporary socket files: /tmp/asbru-cm-Wlu7
INFO: Desktop environment detected : other
INFO: Config directory is '/home/user/.config/asbru'
INFO: Crypt::CBC version is 3.04
INFO: Used config file '/home/user/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.74
       - has_bright = 1
       - major_version = 0
       - minor_version = 74
       - vte_feed_binary = 1
       - vte_feed_child = 1
GLib-GObject-CRITICAL **: invalid (NULL) pointer instance at /opt/asbru/lib/PACMain.pm line 4924.
GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed at /opt/asbru/lib/PACMain.pm line 4924.
INFO: Theme directory is '/opt/asbru/res/themes/default'
INFO: Trying to loading Unity specific tray icon package...
INFO: Using Unity tray icon
DEBUG: Starting window position = (maximized, maximized} ; window size (maximized, maximized)
DEBUG:KEEPASS: Update usage

```
but no messages when using Zoom in/out sequences.

**Comment by guidozualdi** [comment]
On a Debian 11 + Mate, Asbru 6.4.0 with same configuration files, zoom in/out works correctly.

**Comment by gfrenoy** [comment]
Strange since those keys are indeed working fine on my environment as well.

I would suspect the keystroke is "eaten" by another application and do not reach Ásbrú that is thus not able to process it.

What you can do to investigate a bit more on your environment is to edit file `/opt/asbru/lib/PACTerminal.pm` and look for the "_zoomHandler" function ; and put some messages there to see if the code is reached or not.

```perl
sub _zoomHandler {
    my $self = shift;
    my $action = shift;

    my $zoom = 0;
    my $scale = $$self{_GUI}{_VTE}->get_font_scale();

    if ($action eq 'zoomin') {
        print("ZOOM IN");   # <---- ADD THIS LINE
        $zoom = 1;
        $scale += 0.1;
    } elsif ($action eq 'zoomout') {
        print("ZOOM OUT");   # <---- AND ADD THIS LINE
        $zoom = 1;
        $scale -= 0.1;
    } elsif ($action eq 'zoomreset') {
        $zoom = 1;
        $scale = 1;
    }
    if ($zoom) {
        $$self{_GUI}{_VTE}->set_font_scale($scale);
        return 1;
    }

    return 0;
}
```

Then restart Ásbrú and see if you can see "ZOOM IN" and "ZOOM OUT" on the console.
