### ISSUE TITLE
E: Unable to locate package asbru-cm

### ISSUE THREAD

**Issue by gpahlevanzadeh** [asbru-cm/asbru-cm#1062]
I downloaded asbru, and According to md file I run the following command and get error:
*****************************************************************************************************************************
mohsen@debian:~/src-compiled$ curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
[sudo] password for mohsen: 
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=debian  version=<empty>  codename=trixie  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
  RUN: Importing 'asbru-cm/release' repository GPG keys ...gpg: WARNING: unsafe ownership on homedir '/home/mohsen/.gnupg'
   OK: Checking for apt signed-by key support ...
   OK: Importing 'asbru-cm/release' repository GPG keys ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

mohsen@debian:~/src-compiled$ sudo apt-get install asbru-cm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package asbru-cm
*****************************************************************************************************************************

OS: Debian trixie/sid ,

**Comment by stilgarwolf** [comment]
Also on Debian Trixie sid:
Package asbru-cm is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by KlaasT** [comment]
Yeah we currently don't have newer OS versions included in the build process. We need to check if a docker container for the build process is available and include it into the build matrix.

**Comment by stilgarwolf** [comment]
I found something: libcanberra-gtk-module has no installation candidate after last perl update.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by alkinoy** [comment]
have the same issue as topic starer.

```$ curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
sudo apt-get install asbru-cm
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=23.10  codename=mantic  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
  RUN: Importing 'asbru-cm/release' repository GPG keys ...gpg: WARNING: unsafe ownership on homedir '/home/ot/.gnupg'
   OK: Checking for apt signed-by key support ...
   OK: Importing 'asbru-cm/release' repository GPG keys ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package asbru-cm
```

**Comment by alkinoy** [comment]
have the same issue as topic starter

```sudo apt-get install asbru-cm
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=23.10  codename=mantic  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
  RUN: Importing 'asbru-cm/release' repository GPG keys ...gpg: WARNING: unsafe ownership on homedir '/home/xxx/.gnupg'
   OK: Checking for apt signed-by key support ...
   OK: Importing 'asbru-cm/release' repository GPG keys ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package asbru-cm```

**Comment by StormTrooper** [comment]
Having the same issue on Ubuntu 23.10

**Comment by stilgarwolf** [comment]
I still have errors errors in apt-get update:

$sudo apt-get update
...
Err:17 https://packagecloud.io/asbru-cm/asbru-cm/debian trixie Release
404  Not Found [IP: 54.183.93.75 443]

**Comment by gfrenoy** [comment]
Alternatively you can:

1) Override the automatic detection of the distribution, see https://github.com/asbru-cm/asbru-cm/issues/861#issuecomment-1001556672

2) Help providing the new package, see https://github.com/asbru-cm/asbru-cm/issues/1029#issuecomment-1595253193
