### ISSUE TITLE
how to import sites from mobaXterm into asbru?

### ISSUE THREAD

**Issue by tbswork1** [asbru-cm/asbru-cm#1063]
**Is your feature request related to a problem? Please describe.**
how to import sites from mobaXterm into asbru? Only need to import the site name, host address, port and username.

**Comment by gfrenoy** [comment]
As far as I know, there is nothing that has been made to import connections from mobaXterm.

If the configuration files of mobaXterm is documented, you can get inspired by this script https://github.com/asbru-cm/asbru-cm/blob/master/utils/asbru_from_superputty.py to write your own.
