### ISSUE TITLE
Doesn't connecto on Hilllstone NGFW

### ISSUE THREAD

**Issue by josebogo** [asbru-cm/asbru-cm#1066]
I created a connection SSH to an Hillstone NGFW, but during connection I have the message on button bar:
"Stauts: PASSWORD:Sent (not shown)"

After a few seconds, the connection is closed.

This occours only with Hillstone BGFW, on Asbru-CM.

**Comment by gfrenoy** [comment]
Your device has likely a special prompt for password that is not recognized by the default password prompt.

Please check the documentation for additional information on how to change the default password prompt --> https://docs.asbru-cm.net/Manual/Preferences/MOAdvanced/#prompts-password-username-etc
