### ISSUE TITLE
No package for Fedora 39

### ISSUE THREAD

**Issue by Gr33nR10t** [asbru-cm/asbru-cm#1067]
**Describe the bug**
During the installation of Asbru on Fedora 39 I get an error of missing package asbru-cm.

**To Reproduce**
1. Asbru-cm website
2. Follow the instructions to install the software
3. sudo dnf install asbru-cm # Give an error of missing package

**Expected behavior**
The package should be present in the repository for Fedora 39.

**Screenshots**
No screens

**Environment (please complete the following information):**
 - OS: Fedora 39
 - Ásbrú Version: N/A

**Additional context**
Thanks for your work!

**Comment by Bert-H** [comment]
I got Asbru-cm to work in a round-a-bout way on Fedora39.
I'd been a long-time user of PACManager, only to find that it was removed when upgrading from FC38 to FC39. Re-install does not seem possible anymore (it still was with FC38).
The developers will probably shoot me for how I got it working (the bit about the migration), but here is what I did.
Note that this is specifically for my system (with KDE), your's may be different and the below may not work.

1. Download the Asbru FC37 package with: wget --content-disposition "https://packagecloud.io/asbru-cm/asbru-cm/packages/fedora/37/asbru-cm-6.4.0-1.fc37.noarch.rpm/download.rpm?distro_version_id=260"
2. sudo dnf install perl-Gtk3-SimpleList (also installs perl-Gtk3). These are dependencies for the Asbru RPM install
3. sudo rpm -ivv asbru-cm-6.4.0-1.fc37.noarch.rpm. This installs the RPM package without issues

After install, run Asbru from the CLI with "./asbru-cm", it will throw the following error:

INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 22429
INFO: Language detected : en_NZ.UTF-8, forcing to en_US.UTF-8
Can't exec "'/usr/bin/perl' /usr/share/asbru-cm//utils/pac2asbru.pl": No such file or directory at /usr/bin/asbru-cm line 237.
INFO: Migration aborted or errors occured, execute with --verbose to see more information (-1)

In the error, note the "//" between 'asbru-cm' and 'utils'.
Before doing the following, make a backup copy of "/usr/bin/asbru-cm".

Removed one '/' in line 233 of /usr/bin/asbru-cm (asbru-cm itself is another perl script).
Path now correct, but still the same error.
Found that the error seems related to Asbru wanting to do a migration from PACManager. This isn't needed (in my case).
So, remarked out all lines of code that reference this migration. These lines were in between the following sections in /usr/bin/asbru-cm:
Line 164 - 180
Line 229 - 245

asbru-cm now runs.
Imported my saved connection information from the old PACManager and all connections came back.
The only issue was the dark theme that Asbru uses by default, this caused some of the fonts not to be displayed. This was just a matter of playing around with the preferences to fix it. See screenshot of the final outcome. So far, so good.
![Asbru_screenshot](https://github.com/asbru-cm/asbru-cm/assets/68218053/bee54eb0-07b9-445c-a33a-98c1965a11b4)

Hopefully this will be of help to someone.

**Comment by Bert-H** [comment]
Just found out why asbru-cm is throwing the error:

INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 22429
INFO: Language detected : en_NZ.UTF-8, forcing to en_US.UTF-8
Can't exec "'/usr/bin/perl' /usr/share/asbru-cm//utils/pac2asbru.pl": No such file or directory at /usr/bin/asbru-cm line 237.
INFO: Migration aborted or errors occured, execute with --verbose to see more information (-1)

This only happens when asbru-cm has never been run before and the 'asbru' config directory does not yet exist in the user's home directory. On my system the path is "/home/USER_ID/.config/" (.config is a hidden directory).

The same (in my case at least) happened when running the AppImage, it gave the exact same error.
Simply creating the "/home/USER_ID/.config/asbru/" directory fixes the issue.
So now I can run the AppImage on FC38 & FC39 which is my preferred solution.

**Comment by Gr33nR10t** [comment]
Dear @Bert-H, at first thanks to your instructions I have installed asbru-cm on my Fedora 39 with KDE Plasma!

I had previously used the AppImage so the "/home/USER_ID/.config/asbru/" was already existing.

Anyway I have encountered some other problem during the execution:

> INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 53140
> INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
> INFO: Desktop environment detected : other
> INFO: Config directory is '/home/giovdav/.config/asbru'
> INFO: Used config file '/home/giovdav/.config/asbru/asbru.nfreeze'
> INFO: Virtual terminal emulator (VTE) version is 0.74
> **GLib-GObject-CRITICAL: invalid (NULL) pointer instance at /usr/share/asbru-cm/lib/PACMain.pm line 4924.**
> **GLib-GObject-CRITICAL: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed at /usr/share/asbru-cm/lib/PACMain.pm line 4924.**
> INFO: Theme directory is '/usr/share/asbru-cm/res/themes/default'
> INFO: Ásbrú is already running.
> INFO: No more instances allowed!
> WARN: Ásbrú aborted.
> 
> (asbru-cm:53140): GLib-GIO-WARNING **: 17:46:00.965: Your application did not unregister from D-Bus before destruction. Consider using g_application_run().

The GUI seem have some problem and the terminal transparency is not working; anyway the connection is working without any problem.

![Screenshot_20240111_175910](https://github.com/asbru-cm/asbru-cm/assets/8977332/785fa30c-90f4-412c-97bd-4ec7ef7e6805)

**Comment by ValdikSS** [comment]
In `/etc/yum.repos.d/asbru-cm-release.repo`, replace `39` with `37` everywhere. It installs cleanly on Fedora 39.

**Comment by Gr33nR10t** [comment]
@ValdikSS Val I can't find the package, could you write the full repository URL?

Currently I'm using:

https://dl.cloudsmith.io/public/asbru-cm/release/rpm/fedora/39/$basearch

**Comment by ValdikSS** [comment]
Replace 39 with 37 in the url.

Jan 15, 2024 11:42:09 Green Riot ***@***.***>:

**Comment by Gr33nR10t** [comment]
Ok thanks! But it doesn't resolve the graphical glitch! :(

**Comment by Gr33nR10t** [comment]
I have tried to use Asbru-cm on XFCE and there are no issues.
The GUI has been load without any glitch; seem that the problem persist only with KDE Plasma.

**Comment by ValdikSS** [comment]
I use it on Plasma @ Fedora 39, no glitches. Which exactly are you referring to?

**Comment by ValdikSS** [comment]
Uh, so what's wrong with the screenshot? If you're talking about off-white background on the bottom element, that's just your theme.

**Comment by Gr33nR10t** [comment]
it don't happen with the other apps, here the messages starting asbru:

`INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 137976
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : xfce
INFO: Config directory is '/home/giovdav/.config/asbru'
INFO: Used config file '/home/giovdav/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.74
GLib-GObject-CRITICAL **: invalid (NULL) pointer instance at /usr/share/asbru-cm/lib/PACMain.pm line 4924.
GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed at /usr/share/asbru-cm/lib/PACMain.pm line 4924.
INFO: Theme directory is '/usr/share/asbru-cm/res/themes/default'
INFO: Ásbrú is already running.
INFO: No more instances allowed!
WARN: Ásbrú aborted.

(asbru-cm:137976): GLib-GIO-WARNING **: 11:35:38.123: Your application did not unregister from D-Bus before destruction. Consider using g_application_run().`

Seem that recognize xfce instead of kde

**Comment by ValdikSS** [comment]
You need to set proper theme for GTK3 applications in your DE. Try white theme, not black theme.
It looks fine for me in KDE.

**Comment by Gr33nR10t** [comment]
ahah! sorry I'm stupid!! XD

yes changing the theme in asbru solve the problem!!

**Comment by levireis1** [comment]
> I got Asbru-cm to work in a round-a-bout way on Fedora39. I'd been a long-time user of PACManager, only to find that it was removed when upgrading from FC38 to FC39. Re-install does not seem possible anymore (it still was with FC38). The developers will probably shoot me for how I got it working (the bit about the migration), but here is what I did. Note that this is specifically for my system (with KDE), your's may be different and the below may not work.
> 
>     1. Download the Asbru FC37 package with: wget --content-disposition "https://packagecloud.io/asbru-cm/asbru-cm/packages/fedora/37/asbru-cm-6.4.0-1.fc37.noarch.rpm/download.rpm?distro_version_id=260"
> 
>     2. sudo dnf install perl-Gtk3-SimpleList (also installs perl-Gtk3). These are dependencies for the Asbru RPM install
> 
>     3. sudo rpm -ivv asbru-cm-6.4.0-1.fc37.noarch.rpm. This installs the RPM package without issues
> 
> 
> After install, run Asbru from the CLI with "./asbru-cm", it will throw the following error:
> 
> INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 22429 INFO: Language detected : en_NZ.UTF-8, forcing to en_US.UTF-8 Can't exec "'/usr/bin/perl' /usr/share/asbru-cm//utils/pac2asbru.pl": No such file or directory at /usr/bin/asbru-cm line 237. INFO: Migration aborted or errors occured, execute with --verbose to see more information (-1)
> 
> In the error, note the "//" between 'asbru-cm' and 'utils'. Before doing the following, make a backup copy of "/usr/bin/asbru-cm".
> 
> Removed one '/' in line 233 of /usr/bin/asbru-cm (asbru-cm itself is another perl script). Path now correct, but still the same error. Found that the error seems related to Asbru wanting to do a migration from PACManager. This isn't needed (in my case). So, remarked out all lines of code that reference this migration. These lines were in between the following sections in /usr/bin/asbru-cm: Line 164 - 180 Line 229 - 245
> 
> asbru-cm now runs. Imported my saved connection information from the old PACManager and all connections came back. The only issue was the dark theme that Asbru uses by default, this caused some of the fonts not to be displayed. This was just a matter of playing around with the preferences to fix it. See screenshot of the final outcome. So far, so good. ![Asbru_screenshot](https://private-user-images.githubusercontent.com/68218053/294829344-bee54eb0-07b9-445c-a33a-98c1965a11b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMDAyNjAsIm5iZiI6MTcwNjA5OTk2MCwicGF0aCI6Ii82ODIxODA1My8yOTQ4MjkzNDQtYmVlNTRlYjAtMDdiOS00NDVjLWEzM2EtOThjMTk2NWExMWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEyMzkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MzhiNzQ3MzU5YTk2YjIzNWIxYjg3MWJkMDVkNGVkY2M4Y2YxZmFjZTgwNjdkYzdiYzQ1YzA4YjQ1MzI5ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9irALmi-2K90lLL9BP1rEm2h6xuBm-e_O6Ita9ZFYwQ)
> 
> Hopefully this will be of help to someone.

Hello,

It seems for my Fedora39 running Gnome, this did not work, despite having followed all of the above steps, it seems it is missing some other dependencies:

error: Failed dependencies:
	perl is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(Compress::Raw::Zlib) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(Crypt::Blowfish) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(Digest::SHA) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(Expect) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(File::Copy) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(FindBin) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(Net::ARP) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(Net::Ping) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(OSSP::uuid) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(Socket6) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(Sys::Hostname) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(Time::HiRes) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(XML::Parser) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl(YAML) is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl-Crypt-CBC is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl-Crypt-Rijndael is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl-IO-Stty is needed by asbru-cm-6.4.0-1.fc37.noarch
	perl-IO-Tty is needed by asbru-cm-6.4.0-1.fc37.noarch

Can you help?

Cheers,
Levi

**Comment by Gr33nR10t** [comment]
Hello @levireis1! to install the package use dnf instead of rpm!

**Comment by levireis1** [comment]
> Hello @levireis1! to install the package use dnf instead of rpm!

Hello thank you for the feedback. I tried sudo dnf install but I can't seem to find the appropriate argument of this version. Are you able to point me the right one?

Thanks again.

Levi
