### ISSUE TITLE
Opening a connection maximize the window 

### ISSUE THREAD

**Issue by teicors** [asbru-cm/asbru-cm#1076]
**Describe the bug**
Opening a connection if the program is in "window" mode, maximize the screen

**To Reproduce**
Asbru-cm is a windows, opening a connection, maximize asbru-cm

**Expected behavior**
if asbru-cm is windows, I expect to remain a window

**Environment (please complete the following information):**
Ubuntu 23.10
Ásbrú Version 6.4.1

**Comment by starmaex** [comment]
Same here since at least one or two years.

Currently I am using Asbru 6.5.0 on Debian 12/Bookworm.

Really annoying

**Comment by gfrenoy** [comment]
I tried to reproduce this one but could not find a way to see the same misbehaviour.
Can you elaborate a little bit more?  Give details about your configuration ?  Maybe some screenshot ?
Thanks.

**Comment by teicors** [comment]
Hi,
may be you changed the normal behavior or some default values, but I found (after you can't reproduce my error) a  settings under look and feel
"Start terminal maximized : If the new launched terminal window or tabbed window should be maximized."
So is not a asbru-cm issue, but normal if the the option is checked :)

Thanks for your time !!
Cheers,
Angelo
