### ISSUE TITLE
Hidden User Variable is shown in plaintext in right click menu

### ISSUE THREAD

**Issue by SirLagz** [asbru-cm/asbru-cm#1077]
Any user variables that are marked as hidden under the User Variables when editing the connection is then shown in plaintext when you go to the right click menu and hover over "Edit Local Variables"

**To Reproduce**
1. Create Connection
2. Add a hidden User Local Variable
3. Right click on the connection in the connection tree
4. Hover over "Edit Local Variables"

![Screenshot_20240117_103202](https://github.com/asbru-cm/asbru-cm/assets/4788268/611e30f1-a3a3-486c-a023-b717b32d3f11)

![Screenshot_20240117_103233](https://github.com/asbru-cm/asbru-cm/assets/4788268/41978b00-16ec-4173-939b-fb0b3232f5a2)

**Expected behavior**
Any hidden user local variables should be hidden / masked

**Environment:**
 - OS: Debian Bookwoom
 - Ásbrú Version v6.4.0 AppImage

**Comment by gfrenoy** [comment]
Thanks for the report and accurate description, the issue has been fixed and will be included in the next releases.
