### ISSUE TITLE
Focused element and clicks

### ISSUE THREAD

**Issue by syco** [asbru-cm/asbru-cm#1078]
Hi,

I'm on archlinux, using loki, and there's something that always bugged me, but never asked if it's a common issue.

In order to change focused element I sometimes have to click it twice.

Let's say I'm typing in a terminal and I want to edit a different connection just to copy the ip in the host.
I would click on the connection in the list and do Alt+e, but that at times edits the connection of the terminal, not the connection I just clicked on.

Another example is, I'm in a terminal, I click on anything in the connection list and start typing, sometimes that opens the search box as expected, sometimes it sends the input to the terminal. So I have to click the connection list twice to be sure.

Another example is with split terminals, if I'm typing on the right terminal and want to move to the left terminal I have to click the left panel twice or it doesn't get focused.

Does anyone else find this happens at times?

**Comment by gfrenoy** [comment]
I never noticed this in my environment.

To troubleshoot this further, you should try to add some debug messages in the relevant callbacks and analyse when exactly they are caught.  It mainly in [PACMain](https://github.com/asbru-cm/asbru-cm/blob/master/lib/PACMain.pm#L1157).
