### ISSUE TITLE
Can't connect to any servers

### ISSUE THREAD

**Issue by DennisSkov** [asbru-cm/asbru-cm#108]
Hi,
I've just installed asbru, but I'm having trouble getting any connection working.
I'm connecting using private key, and I'm prompted to input the password for the private key when I connect (and what I input is shown - any way to hide that?)
After waiting a few seconds, I always get the following error:
 <-= DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Sun Aug 26 11:22:55 2018)

If I copy and paste the connect command to a terminal, I connect just fine.

Any idea what could be causing this?

**Comment by DennisSkov** [comment]
Alrighty, pretty sure I'm missing something, or this might be a bug.
If I append -vvv to the connection hostname to enable verbose, I connect just fine. Input from entering the private key password is hidden as well.

What am I missing?

**Comment by gfrenoy** [comment]
Ásbrú relies on the system to ask the password of the private key ; it basically runs:

    ssh -i <your_private_key> <your_server>

And, on the first connection, this should trigger a popup asking you the password of your key.

This is typically handled by [gnome-keyring](https://wiki.gnome.org/Projects/GnomeKeyring).

If this fails (for some reason), you should indeed see a "DISCONNECTED" message...

Not sure why it does not work for you...

Can you give more details about your system ?  Didn't you disable the keyring for some reason ?

**Comment by DennisSkov** [comment]
I see no popup at all. I'm running KDE Plasma on Arch Linux. 

Gnome-keyring is running with the following parameters: /usr/bin/gnome-keyring-daemon --start --foreground --components=secrets

SSH is running on port 222 on the machine that I'm trying to connect to. 

Is it normal that Ásbrú shows the password input? As soon as I add -v to the hostname, it no longer shows the input, and I can login just fine.

**Comment by gfrenoy** [comment]
No, it's not normal.

Can you get the command line that is actually started by Ásbrú ?  (You can see it in "Advanced Parameters" of your connection).  Both with and without "-v" ?

**Comment by DennisSkov** [comment]
Sure.:
`ssh -p 222 -i "/home/dennis/.ssh/id_rsa"  -X -l root server10.example.com`
`ssh -p 222 -i "/home/dennis/.ssh/id_rsa"  -X -l root server10.example.com -v`

I can copy the commands to a terminal window and connect just fine (even in Ásbrú local terminal).

**Comment by gfrenoy** [comment]
Mmm, really strange, I don't see anything wrong with that...

Do you have "Use selected auth method ..." option checked ?

You may also try to activate the "Expect DEBUG" in Preferences > Terminal Options > Advanced to see if you can get some hints.

**Comment by DennisSkov** [comment]
Hi,

I've tried with an without that option. None of them works.
Here is the debug log when trying to connect:

>  CONNECTING WITH 'Server 10' (Mon Aug 27 21:54:37 2018) =->
> 
> Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
> Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
> [pac_conn(30616)][Server 10][Server 10]: !!_PAC_AUTH_[pac_PID30077_n3]!!
> [pac_conn(30616)][Server 10][Server 10]: SPAWNING:ssh -p 222 -i "/home/dennis/.ssh/id_rsa" -o "PreferredAuthentications=publickey"  -X -l root server10.example.com
> [pac_conn(30616)][Server 10][Server 10]: SPAWNED:'ssh -p 222 -i "/home/dennis/.ssh/id_rsa" -o "PreferredAuthentications=publickey"  -X -l root server10.example.com' (PID:30616)
> Starting EXPECT pattern matching...
>  at /usr/share/perl5/vendor_perl/Expect.pm line 597.
> 	Expect::expect(Expect=GLOB(0x560f20d27eb8), 40, ARRAY(0x560f21bc9708), ARRAY(0x560f21bc97b0), ARRAY(0x560f21bdb140), ARRAY(0x560f21bdb338), ARRAY(0x560f21bdb410), ARRAY(0x560f21bd3430), ...) called at /opt/asbru/lib/pac_conn line 1573
> spawn id(3): list of patterns:
>   #2: -eof `'
>   #3: -re `\\[__PAC__SUDO__PROMPT__\\]'
>   #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'
>   #5: -re `.*(any key to continue|tecla para continuar).*'
>   #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'
>   #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'
>   #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+|\\w+@\\w+)*|[c|C]ontrase.a|Enter passphrase for key )\\s*:\\s*$'
>   #9: -re `[#%\\$>]|\\:\\/\\s*$'
> 
> 
> spawn id(3): Does `'
> match:
>   pattern #2: -eof `'? No.
>   pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
>   pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
>   pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
>   pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
>   pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
>   pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+|\\w+@\\w+)*|[c|C]ontrase.a|Enter passphrase for key )\\s*:\\s*$'? No.
>   pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.
> 
> Enter passphrase for key '/home/dennis/.ssh/id_rsa': 
> spawn id(3): Does `Enter passphrase for key \'/home/dennis/.ssh/id_rsa\': '
> match:
>   pattern #2: -eof `'? No.
>   pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
>   pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
>   pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
>   pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
>   pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
>   pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+|\\w+@\\w+)*|[c|C]ontrase.a|Enter passphrase for key )\\s*:\\s*$'? No.
>   pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.
> 
> <PASSWORD INPUT>
> [pac_conn(30616)][Server 10][Server 10]: CLOSE:TIMEOUT:40 seconds trying to connect or get prompt!!
> [pac_conn(30616)][Server 10][Server 10]: DISCONNECTING
> [pac_conn(30616)][Server 10][Server 10]: DISCONNECTED
> 
>  <-= DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Mon Aug 27 21:55:18 2018)

**Comment by gfrenoy** [comment]
Ok so we have 2 things here:

1) Your system keyring does not work for some reason
2) You cannot enter your passphrase interactively inside Ásbrú

About 1, I'm really not comfortable enough with Arch to troubleshoot the problem further.

About 2, I got it working here by setting <<ASK_PASS>> in the private key definition:
![image](https://user-images.githubusercontent.com/981546/44684015-34807080-aa48-11e8-9aed-ad7b60357aa3.png)

Attention, you'll also have to make sure your Password prompt is correct, it should:

    ([p|P]ass|[p|P]ass[w|W]or[d|t](\s+for\s+|\w+@\w+)*|[c|C]ontrase.a|Enter passphrase for key '.+')\s*:\s*$

In the log your reported, it looks like the '.+' part after 'for key' is missing, please double check.

Hope this helps.

**Comment by DennisSkov** [comment]
That seems to have fixed it. 
They keyring should work - I've used it for other apps, such as MailSpring.

**Comment by gfrenoy** [comment]
Good :)  But what have fixed it ?  Using <<ASK_PASS>> or changing the password prompt ?

**Comment by DennisSkov** [comment]
I changed the password prompt first, but that did nothing. Setting <<ASK_PASS>> as the password prompted me for a password, and connection was successful.
