### ISSUE TITLE
file .rdp for freerdp

### ISSUE THREAD

**Issue by apanasis** [asbru-cm/asbru-cm#1081]
How can add name of .rdp file for freerdp? If add as first option in Other options on RDP(xfreerdp) options tab got error : 12:01:08:176] [307616:307616] [ERROR][com.winpr.commandline] - Failed at index 6 [filename.rdp]: Unexpected keyword
Thanks

**Comment by gfrenoy** [comment]
You cannot use a .rdp file to configure a RDP connection in Ásbrú.

You have to use the information that are defined into the .rdp file to configure Ásbrú properly.
