### ISSUE TITLE
Alternative for MAC OS

### ISSUE THREAD

**Issue by SorianoMarmol** [asbru-cm/asbru-cm#1083]
Firstly, I'd like to congratulate and thank the project maintainers for their hard work.

After many years of using Asbru-cm, I'm forced to switch to macOS. Can someone suggest a similar alternative?

My goal is to be able to run commands automatically, especially locally. I use the "Expect" tab of Asbru CM:

![image](https://github.com/asbru-cm/asbru-cm/assets/12081940/1dd22129-d989-4fcb-a5b7-9747e31aa6d5)

Thanks to the maintainers of this project, I'll always recommend it for Linux.

**Comment by KlaasT** [comment]
Thank you for the kind words. Sadly we would love to do more but real life kicked in hard. But we are always willing to accept help.

In regards of Mac OS, we had someone in the tickets trying to create a mac port. I honestly don't know off my mind how that one went.

**Comment by gfrenoy** [comment]
See #732
