### ISSUE TITLE
"Invalid sigil" error while trying to connect to a Windows 11 VM

### ISSUE THREAD

**Issue by maxdrake69** [asbru-cm/asbru-cm#1084]
**Describe the bug**
Having asbru-cm v.6.4.0 installed on kubuntu 22.04, after setting up a straightforward RDP connection when I try to connect I get this error (followed bya long xfreerdp usage-sintax-example list) :
[09:46:18:996] [18252:18252] [ERROR][com.winpr.commandline] - Failed at index 1 [/parent-window:98608597]: Invalid sigil

**To Reproduce**
Nothing special, just a plain new connection shows that.

**Expected behavior**
Please consider that I also tried to launch xfreerdp directly from a terminal 
xfreerdp /u:username /v:machineaddress:3389
and it just works fine giving a fully working session

**Screenshots**

**Environment (please complete the following information):**
 - OS: kubuntu 22.04 (plasma on x11) with latest updates
 - Ásbrú Version 6.4.0

**Additional context**

**Comment by gfrenoy** [comment]
Looks like your version of xfreerdp does not support the option ```/parent-window```, does it ?
