### ISSUE TITLE
please add the paste with a right mouse click

### ISSUE THREAD

**Issue by emoxam** [asbru-cm/asbru-cm#1089]
**Is your feature request related to a problem? Please describe.**
I'm getting sad because right mouse click shows menu when i need to select paste everytime.

**Describe the solution you'd like**
Let menu be on the middle click and paste on the right click, option to select the behaviour.

**Describe alternatives you've considered**
It working so in the securecrt

**Additional context**
And terminator shell)

**Comment by yennor** [comment]
it's standard on linux having paste on the middle click. If you really want to have paste on the right mouse button and the context menu on the middle one, I'm pretty sure you can change that in your desktop environment

**Comment by emoxam** [comment]
> it's standard on linux having paste on the middle click. If you really want to have paste on the right mouse button and the context menu on the middle one, I'm pretty sure you can change that in your desktop environment

And you know the way ?

**Comment by emoxam** [comment]
seems thats the way
```killall xbindkeys && echo -e '"xdotool key ctrl+shift+v"\nb:3' >> ~/.xbindkeysrc && xbindkeys```

**Comment by gfrenoy** [comment]
As mentionned by @yennor, it's more a default behaviour of the desktop environment.  Don't believe we HAVE to override it.  At least, as I don't use Windows at all since years and years, I would be confused, for sure.

**Comment by emoxam** [comment]
there is option in terminator you can select the way you like
https://github.com/search?q=repo%3Agnome-terminator%2Fterminator%20putty_paste_style&type=code

**Comment by tleasure** [comment]
It would be awesome to have a configurable option to do right-click paste
