### ISSUE TITLE
persistent irc channel at freenode

### ISSUE THREAD

**Issue by dpecka** [asbru-cm/asbru-cm#109]
Hello ppl,

thanks for continuing a pacmanager ... please consider establishing the persistent irc channel on freenode .. I think it will help greatly to work on gtk3 backend migration ...

regards, dan

**Comment by gfrenoy** [comment]
Well, there's already a persistent channel (#asbru-cm) on irc.st-city.net ; what's wrong with it ?

And also, Ásbrú is meant to be community driven so if one wants to create a channel on Freenode, just do it :)  And let us know so we can join and promote it...

**Comment by KlaasT** [comment]
Feel free to join us. At irc://irc.st-city.net/#asbru-cm or if you don't have access to an IRC client because you're at work or so you can use our web client: https://webchat.st-city.net/#asbru-cm

**Comment by beliys** [comment]
What do you think about telegram chat?

**Comment by dpecka** [comment]
Telegram is

1) controversial
2) banned in some countries

so I don't think that it is sane

**Comment by gfrenoy** [comment]
A [Matrix](https://matrix.org/) room ?

**Comment by gfrenoy** [comment]
Thanks to @KlaasT, we now have a bridge between our IRC channel and the [Matrix](https://matrix.org/) network.

Using any client supporting the [Matrix open standard](https://matrix.org/docs/spec), you can now discuss about Ásbrú on [#asbru-cm:scificenter.de](https://matrix.to/#/#asbru-cm:scificenter.de).

I did not try it myself but as Freenode is itself bridged with the Matrix network (see [here](https://matrix.org/blog/2015/06/22/the-matrix-org-irc-bridge-now-bridges-all-of-freenode)), that should fix this issue, I presume :)
