### ISSUE TITLE
Where connections are saved when asbru-cm installed via snap?

### ISSUE THREAD

**Issue by emoxam** [asbru-cm/asbru-cm#1090]
Where connections are saved when asbru-cm installed via snap?

**Comment by emoxam** [comment]
![image](https://github.com/asbru-cm/asbru-cm/assets/3593601/fe6e784e-bcdf-4359-ac37-bb5313e49667)

**Comment by gfrenoy** [comment]
You should ask this question to the team who made the snap package ; we have not been involved into this.

**Comment by emoxam** [comment]
While using secure crt i can select the path config will be saved to
it could be nextcloud folder
the same i do at home
so same configs i have on the work and at the home.
What to do with asbru ? Can i synchronize connections ?

**Comment by gfrenoy** [comment]
For specific questions about the snap package, please ask the team who made that packaging.

For synchronization between several computers, search the existing issues, it has already been discussed.
