### ISSUE TITLE
sync config settings between hosts and/or merge different configs together

### ISSUE THREAD

**Issue by grufocom** [asbru-cm/asbru-cm#1093]
Asbru is a great help at daily work - thank you for that wonderfull tool!

If you work with more than one computer (desktop, notebook) you often have the problem that the config has been changed on one system and this change is missing on the second system on the way.

It would be great if you could synchronise the config regularly, e.g. via a cloud (nextcloud). It would certainly be an advantage if the general settings and the connection settings were kept separately in configurations. In this way, only the connection-specific part could be synchronised.

Regards
Manfred

**Comment by emoxam** [comment]
Noone is care for a long time. So here's a link https://docs.asbru-cm.net/Manual/CommandLine/#-config-dir
