### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by klemenkobetic** [asbru-cm/asbru-cm#1095]
PR's are old, there's no new release...is the project dead?

**Comment by gfrenoy** [comment]
The project will remain alive if the community is active and proposes evolutions.

What do you propose @klemenkobetic ?

**Comment by klemenkobetic** [comment]
Hmm, I don't know - but I currently see 136 issues? What do we need to resolve them? Funding?

**Comment by gfrenoy** [comment]
> but I currently see 136 issues?

Ok, and ?

What is called an "issue" is maybe not an issue.  Some are already addressed, some are just suggestions, some are not useful.  What you mean, I guess, is that nobody is doing the "triage" job.

> What do we need to resolve them?

Not sure what needs to be resolved at this stage but the first step is for sure : someone that does the triage job.

> Funding?

If money can buy what is required, yes, that can help of course.  But money is not the only requirement to fulfil.  If you spend money on something, you need time to define the expected tasks, decide on which tasks the money will be allocated, follow-up the results, etc.  So it's another job that requires the time of skilled people.

Into my eyes, what we need is an active community and and small group of motivated and organized people who have time to organize it.

Who's in ?

**Comment by emoxam** [comment]
I proposed, i won't add an option .. 
I asked where config is located what did you do? 
Take of the crowd.

**Comment by gfrenoy** [comment]
> I asked where config is located what did you do?

I explained you should ask the maintainer of the snap packager.  I don't have the answer and I will not search for you.

Let's close this discussion, it is not helping.
