### ISSUE TITLE
Statistics button always shown on startup disregarding the checkbox

### ISSUE THREAD

**Issue by erezh16** [asbru-cm/asbru-cm#1098]
**Describe the bug**
Linux (Fedora 39 - using the F37 version of asbru-cm)
When asbru-cm is started, the statistics button and lower panel is always shown, even if the checkbox "Show Statistics" in Preferences is unchecked.

**To Reproduce**
1. Click on Preferences
2. In the "Main Options" category, select "Look and Feel" tab
3. Uncheck "Show Statistics"
4. Click "Save and Close"
5. Press "Quit" in the main window to completely close asbru-cm
6. Launch asbru-cm again
7. Statistics panel is showing again. By repeating the above process, you can see that the "Show Statistics" checkbox is still unchecked.

**Expected behavior**
When the "Show Statistics" checkbox is unchecked, the statistics panel should not show upon startup.

**Screenshots**
I think it's pretty straightforward to reproduce.

**Environment (please complete the following information):**
 - OS: Fedora 39
 - Ásbrú Version: 6.4.0

**Additional context**
N/A

**Comment by gfrenoy** [comment]
The "Show Statistics" is "just" showing/hiding this part of the "Info" tab:
![image](https://github.com/asbru-cm/asbru-cm/assets/981546/84f437ed-9866-4704-8768-53d23ae3aa36)

As far as I could test it, it works as expected.
