### ISSUE TITLE
Make the connections side panel hide by default, pop up when needed

### ISSUE THREAD

**Issue by erezh16** [asbru-cm/asbru-cm#1099]
**Is your feature request related to a problem? Please describe.**
I sometimes work in a window-dense environment wherethe size of the screen dedicated to asbru-cm window is quite limited. I maximize my utilization by hiding the connection side panel (alt-n). 

**Describe the solution you'd like**
I would like to be able to configure hiding the connection panel as default behavior so that it pops up only when needed, e.g., by pressing alt-n or by clicking on an icon. Maybe it would even be possible to auto-hide the panel again after the connection is chosen.

**Describe alternatives you've considered**
As written above, the only option I have right now is to manually hide the side panel when I open the asbru-cm main window.

**Additional context**
As a general vision, I think that in the age of cloud and distributed computing, asbru-cm can become a superior alternative to the common terminal applications because of all the smart remote connectivity choices it has in addition to the local terminal.

**Comment by gfrenoy** [comment]
Did you check this option:
![image](https://github.com/asbru-cm/asbru-cm/assets/981546/d39a3bb8-103a-4c6a-897f-d6ef4748e4d1)
?

**Comment by erezh16** [comment]
I just found about it, and checking all the boxes makes asbru-cm behave closely to they way I wanted it. Thank you! I'll be closing this item.
