### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by eprompc** [asbru-cm/asbru-cm#110]
Hello!!

I'm thinking to format drive and change of distro. How can I backup all the connection list for import in new installation??? I have more than 50 connections........ thanks!

**Comment by jkwedar** [comment]
Before i reformatted my desktop, i right clicked in Asbru "available connections" -> "export all connections" -> ok and then select destination (should be .yml file). You could load it on another computer just to verify it worked before formatting but that is what i did.
