### ISSUE TITLE
Warning messages because of missing dependencies

### ISSUE THREAD

**Issue by yennor** [asbru-cm/asbru-cm#1100]
**Describe the bug**
On Debian Testing following two warning messages appear with every ssh connection being made. 
It's kinda annoying but otherwise works.

```
Gtk-Message: 09:30:02.188: Failed to load module "xapp-gtk3-module"

(asbru_conn:615770): dbind-WARNING **: 09:30:02.194: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

```

This can be solved by installing the two following packages:
apt install libxapp-gtk3-module  at-spi2-core

Since those package aren't really needed to run asbru-cm it would be nice to catch those errors.
If they are needed for certain functionality maybe add them to suggested-packages and still catch the errors if those packages aren't installed ;-)

**To Reproduce**
1. start up absru-cm and open a ssh connection

**Environment (please complete the following information):**
 - OS: Debian Testing
 - Ásbrú Version 6.4.0-1

**Comment by yennor** [comment]
I uninstalled at-spi2-core at purpose on my system. Since from time to time the screen reader got automagically activated. It's been easier deinstalling it, than finding out why ;-).

> Got this warning as well but except adding the necessary dependency (xapp in my case - Ubuntu 22.04), I don't see how we can get rid of it.

So that message doesn't come from a library or something similar which asbru uses?
would it be possible to just filter it out? (No idea how messages get send to the terminal)

**Comment by gfrenoy** [comment]
> So that message doesn't come from a library or something similar which asbru uses?

That would be my wild guess as well.

> would it be possible to just filter it out? (No idea how messages get send to the terminal)

I don't know either.

One needs to dig into this and spend time on searching...
Any candidate ?

**Comment by gfrenoy** [comment]
I found out that the messages are shown when we do `use Gtk '-init'`.

This is for sure required when you first start the application but it's probably not necessary in all the packages.  I removed some of them in the "loki" version and I don't see the messages anymore when I start a terminal (only at Ásbú startup).

Will you give it a try and see if it has removed the messages for you as well ?  And if you don't notice any regression ?

Thanks.

**Comment by yennor** [comment]
Since right now, I've got nothing to do on a server, I can't test it productively. But I've run through the default stuff I usually need it for and it seems to work :-).
Since right now I'm halfway in holidays it could take a week or two until I'll need it productively again.

**Comment by yennor** [comment]
this week I used it quite a lot productively.
Seems to be working exactly the same way it worked before :-)

**Comment by gfrenoy** [comment]
Good that you could test it, thanks a lot for your help :-)

But do you mean there was no regression AND the message have disappeared ; or that it did not change anything (you still see the warning messages) ?  If the issue is fixed, just close the issue ... Thanks !

**Comment by yennor** [comment]
sorry for being ambiguous. everything worked the way it should, without having the messages anymore.

**Comment by gfrenoy** [comment]
> sorry for being ambiguous. everything worked the way it should, without having the messages anymore.

Cool !  Thanks for raising the issue ; that was actually bugging me as well ; happy that we found a workaround together :)
