### ISSUE TITLE
Password with £ char hangs Asbru

### ISSUE THREAD

**Issue by teicors** [asbru-cm/asbru-cm#1101]
The password stored in the conf cannot start an ssh session 

Create a connection and set the password with a £ char

The login stops at the request of password and the window of the password appears

 - OS: Ubuntu 24.04
 - Ásbrú Version 6.4.1

**Comment by gfrenoy** [comment]
Indeed if the password contains a special character that is encoded as a multibyte in UTF-8 will likely fail to be passed correctly.

I'll push a fix in a few minutes that will hopefully fix this, thanks for reporting ;)

That being said, it is not secure to store password in Ásbrú, you should really consider using a SSH key or use KeePass to store your passwords...
