### ISSUE TITLE
Incomplete line

### ISSUE THREAD

**Issue by nani81** [asbru-cm/asbru-cm#1102]
For a long time now when I try to display a long paragraph I always have to hit space to make it continue.
For example, when I enter a switch and I want to see the status of the interfaces, only the first line appears and I have to hit enter 40 times to get the whole thing.
If I do the same from a terminal outside of Asbrú I don't have this problem, in fact, I didn't have this problem before.
Attached screenshots
* Desde Asbrú
![1](https://github.com/user-attachments/assets/6d2b581b-54ac-4b0a-8c56-72e24194b013)
![2](https://github.com/user-attachments/assets/043c430c-dacf-47ec-93fb-5314d8e3c6fc)
* Desde un terminal
![3](https://github.com/user-attachments/assets/d5f79964-4b2a-4425-b5b0-aae680d5125d)

**Comment by gfrenoy** [comment]
Without having access to that particular appliance, it will be complicated to understand the root reason.

I would suspect the appliance is not detecting the screen size correctly and is consequently adding more pages than necessary.  Please not Ásbú relies on the [Vte project](https://gitlab.gnome.org/GNOME/vte), the problem might be there as well.

When you say "I didn't have this problem before" ; do you mean with a previous version of Ásbrú ?  Or maybe a previous version of your operating system ?

**Comment by nani81** [comment]
I refer to the previous OS version.
I used to have Fedora 37 and now I have 38.
I will try downloading the project you sent me.

**Comment by gfrenoy** [comment]
I don't see any change that we would have done that would change this behaviour, I'd first suspect a change in a dependency.  Do you have the opportunity to test this again with F37 (in a VM or something) to confirm ?
