### ISSUE TITLE
stale floating box after aborting drag and drop of a connection

### ISSUE THREAD

**Issue by efferre79** [asbru-cm/asbru-cm#1105]
**Describe the bug**
It is currently possible to arrange the connections in groups and use drag&drop to move them around. If I select a connection and move the mouse, a floating box is created which follows the mouse. Then if I don't move the box to a final destination (or I press ESC to terminate the operation), the box is not destroyed and stays in foreground on my desktop even if the application is hidden or below other windows.

The workaround is to select another connection and drag it on "My connections" (or the same group it belongs).

**To Reproduce**
1. click and select a connection
2. start moving the mouse
3. press ESC

**Expected behavior**
the floating box should disappear when the drag&drop operation is aborted

**Environment (please complete the following information):**
 - OS: Gentoo Linux
 - Desktop: XFCE 4.18
 - Ásbrú Version: 6.4.0

**Comment by gfrenoy** [comment]
Thanks for the detailed description and ... the workaround !!!    It did not happen often to me but I remember this and I just restarted Ásbrú to get rid of the annoying box.  Let me see if I can find how to properly abort the drag&drop operation...

**Comment by gfrenoy** [comment]
I believe I identified and fixed the issue.  You can this in our "snapshots" release and the fix will be included in our next release (likely 6.4.1).  Thanks again for your contribution.

**Comment by efferre79** [comment]
@gfrenoy thanks but the quick answer, I have tested the patch but it is not complete. The patch only covers the case when I cancel the drag operation with ESC. If instead there is no target when releasing the mouse button (when running with --verbose I get the message _drag failed no-target_), the problem is still visible.

**Comment by gfrenoy** [comment]
Good point :)  I made another change, it will be available in the snapshots release very soon and will also cover this case.

Thanks for your feedback :)
