### ISSUE TITLE
Reorganizing Connections - Unable to Drag and No Move Up/Down Options

### ISSUE THREAD

**Issue by siriusgithub** [asbru-cm/asbru-cm#1107]
**Describe the bug**
I've read online that it's possible to reorganize connections above or beneath each other. The only ability I have is dragging to different folders and at the bottom of the folder specifically.

**To Reproduce**
1. Open program.
2. Add more than two connections in a folder or the My Connections root diretory.
3. Try to put on connection above the other.
4. Connections stay in the same order as added chronologically.

**Expected behavior**
Newer connections can be put on top of others and visa versa.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Ásbrú Version Latest 6.4.0

**Comment by gfrenoy** [comment]
How it currently works is that the connections are sorted alphabetically into a folder.
When I want to control the order into a specific folder, I just prefix all entries with 01, 02, 03, ...
Wouldn't this work for you ?

**Comment by siriusgithub** [comment]
That's totally reasonable. I didn't realize it was alpha. Thank you!
