### ISSUE TITLE
Add support for Ubuntu 24.04

### ISSUE THREAD

**Issue by aqu1ntero** [asbru-cm/asbru-cm#1108]
**Is your feature request related to a problem? Please describe.**
I'm unable to install the software on Ubuntu 24.04. The version for Ubuntu 22.04 works, but the repository has no installation candidate for the new Ubuntu release.

**Describe the solution you'd like**
I'd like the repository to include an installation candidate for Ubuntu 24.04 to support users on the latest version of Ubuntu.

**Describe alternatives you've considered**
Alternatives include manually downloading and building the software from source or using a different version of Ubuntu (like 22.04) that is currently supported, but these are not ideal solutions.

**Comment by javierjcf** [comment]
The package for ubuntu 24.04 is not ready. I get the installation by editing file /etc/sourcest_list.d/asbru-cm-release.list and changing the word noble by jammy. This way we get Ubuntu 22.04 package.

**Comment by KlaasT** [comment]
Ubuntu noble is available within the snapshot repository. Will be ported over to the releases once a new release is tagged.
