### ISSUE TITLE
Package asbru-cm unavailable in the Debian Bookwork repository

### ISSUE THREAD

**Issue by megaknight** [asbru-cm/asbru-cm#1109]
I recently followed the instructions for installing on Debian:

curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
sudo apt update
sudo apt install asbru-cm 

However, the package is not available for installation. A workaround seems to be opening the repository info on /etc/apt/sources.list.d and changing from bookwork to bullseye, the previous Debian version. It's obviously not the ideal situation.

Running this on Debian 12.6 AMD64.

**Comment by KlaasT** [comment]
A bookworm build is available in the snapshot repository and will be available for the release versions with the next release tag.
