### ISSUE TITLE
It doesnt connect

### ISSUE THREAD

**Issue by Kryuko** [asbru-cm/asbru-cm#111]
Hello.
I have ubuntu 18.04 mate.
I installed the software, i already had pac installed and i see my ssh pac's connections.

The problem is (exactly like pac) when i click on an ssh connection the software freezes.
Everything is working fine if i open the program from terminal, exactly like PAC.

Thank you.

**Comment by gfrenoy** [comment]
@Kryuko I do fear there is not enough information in your message to investigate further.

Can you describe a bit more what you mean by "the software freezes" ?  Maybe with some screenshots and/or a screencast ?

Can you also elaborate a bit more on the other method you are using to start Ásbrú (as opposed to the one  from terminal) ?

Any log file or other information might also be helpful.  Or error message you see on the screen ?

Is this related to Ubuntu 18.04 Mate only ?  Did you try on any other environment ?

Is it happening for all SSH connections ?  Or only a few of them ?

**Comment by juliardi** [comment]
I don't know if this is the same problem as the first comment intended, but Asbru also freezing after I double click on a connection profile. The window just turn gray and I am unable to click any object inside the window. But, when I click the close button, the confirmation message does appear.
Here is the screenshot :
![screenshot_20181018_100022](https://user-images.githubusercontent.com/4223302/47128887-5f0adf00-d2bd-11e8-8a28-9ce1a39f0828.png)
Also this is the terminal message :
![screenshot_20181018_100346](https://user-images.githubusercontent.com/4223302/47128909-7fd33480-d2bd-11e8-9365-319fac756b89.png)

**Comment by gfrenoy** [comment]
@juliardi According to the error message on the terminal, it looks like the "Vte" package has not properly been installed on your machine.  I'm not very familiar with the Arch packaging, you should look here for support : https://aur.archlinux.org/packages/asbru-cm-git/

**Comment by dynamicmindset** [comment]
Hello, was using PAC manager for a long time, had some issues with it on 18.04.

asbru is working after installing:
sudo apt-get install libgnome2-vte-perl
