### ISSUE TITLE
No asbru-cm (asbru-cm-loki) for fedora 40

### ISSUE THREAD

**Issue by Frankstar** [asbru-cm/asbru-cm#1110]
Looks like there is no package for asbru-cm / absru-cm-loki in the cloudsmith.io repos.

---
EDIT:
looks like there is no package for fedora 38,39 and 40.

https://cloudsmith.io/~asbru-cm/repos/loki/packages/?q=distribution%3Afedora+AND+distribution%3A38
https://cloudsmith.io/~asbru-cm/repos/loki/packages/?q=distribution%3Afedora+AND+distribution%3A39
https://cloudsmith.io/~asbru-cm/repos/loki/packages/?q=distribution%3Afedora+AND+distribution%3A40

The last one is for 37.
https://cloudsmith.io/~asbru-cm/repos/loki/packages/?q=distribution%3Afedora+AND+distribution%3A37

**Comment by KlaasT** [comment]
Packages are now available, though I don't know if loki is currently up to date codewise. You might want to try the snapshot repository. Loki is more experimental anyway.
