### ISSUE TITLE
Missing dependencies on (k)ubuntu 18.10

### ISSUE THREAD

**Issue by mirlipili** [asbru-cm/asbru-cm#113]
Hello, I'm trying to install Ásbrú on Kubuntu 18.10.
Cosmic suttlefish is not yet supported by package cloud, so I ran:

wget https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh
chmod +x script.deb.sh
sudo os=ubuntu dist=bionic ./script.deb.sh

which starts fine.

But there are 2 missing dependencies:

libgnome2-gconf-perl
libgtk2-unique-perl

Both can't be found in the repository.

Any Idea what I could do?

Thanks

**Comment by gfrenoy** [comment]
Thanks for your feedback and the workaround @mirlipili

This is not yet done but we may indeed want to add support for 18.10 on packagecloud ...

**Comment by netroby** [comment]
+1 hope support ubuntu 18.10

**Comment by gfrenoy** [comment]
Actually, I added support for Cosmic a few weeks ago (see [here](https://github.com/asbru-cm/asbru-cm/commit/c9a073fa3045ff14022653b071121923fbde3688)) so it should work with the snapshot package that you can try with:

```
curl -s https://packagecloud.io/install/repositories/asbru-cm/snapshots/script.rpm.sh | sudo bash
sudo dnf install asbru-cm
```

**Comment by netroby** [comment]
```
下列软件包有未满足的依赖关系：
 asbru-cm : 依赖: libgnome2-gconf-perl 但无法安装它
            依赖: libgtk2-unique-perl 但无法安装它
            依赖: libgnome2-vte-perl 但无法安装它
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
huzhifeng@ubuntu ~ $ sudo apt install libgnome2-gconf-perl

```

**Comment by netroby** [comment]
libgnome2-gconf-perl libgtk2-unique-perl libgnome2-vte-perl missing

**Comment by gfrenoy** [comment]
I see.  This is actually the same issue as #114.  In that issue you'll find the necessary .deb.

**Comment by gfrenoy** [comment]
I just built and uploaded the missing packages on the main Ásbrú repository.  See https://github.com/asbru-cm/packages for details.

This should now work on Ubuntu Cosmic:

```
sudo apt-add-repository multiverse
curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash
curl -s https://packagecloud.io/install/repositories/asbru-cm/snapshots/script.deb.sh | sudo bash
sudo apt install asbru-cm
```

Whenever we release a new version, the "snapshots" will not be necessary anymore.

Let us know if it works for you.

**Comment by netroby** [comment]
It works, thanks a lot.
Hope the new release will be done soon.
Many thanks.

**Comment by ChrisN812** [comment]
> Let us know if it works for you.

Worked perfect for me as well.  Asbru is esential in my daily work managing 1000's of AIX and LINUX servers.  Thanks for the perfect tool!

**Comment by gfrenoy** [comment]
> Worked perfect for me as well

Thanks for the positive feedback !

**Comment by gfrenoy** [comment]
The latest release [(5.2)](https://github.com/asbru-cm/asbru-cm/releases/tag/5.2.0) can now be installed on (k)ubuntu 18.10, see [specific instructions](https://github.com/asbru-cm/asbru-cm/wiki/installation-on-ubuntu).
