### ISSUE TITLE
Debian experimental (buster) removed libgnome2...

### ISSUE THREAD

**Issue by panciom** [asbru-cm/asbru-cm#114]
Hello everyone.
First of all I would like to thank the old (PAC) and new (ASBRU) developers for the excellent tool.

Use PAC from a few years to today. After an apt-get dist-upgrade of my Debian experimental the libgnome2- * and consequently also PAC have been removed.
This thing is wanted by the Debian team.

I also tried ASBRU but I always have the same error:

```
root @ ciro: / home / hook / Download # dpkg -i asbru-cm_5.1.0-1.debian-stretch.amd64.deb
Selected asbru-cm package not previously selected.
(Read the database ... 315452 files and directories currently installed.)
Preparations for extracting asbru-cm_5.1.0-1.debian-stretch.amd64.deb ...
Extraction of asbru-cm (5.1.0-1) ...
dpkg: dependency problems prevent configuration of asbru-cm:
 asbru-cm depends on libgnome2-gconf-perl; however:
  The libgnome2-gconf-perl package is not installed.
 asbru-cm depends on libgtk2-unique-perl; however:
  The libgtk2-unique-perl package is not installed.


dpkg: error processing the package asbru-cm (--install):
 problems with dependencies - left unconfigured
Trigger processing for desktop-file-utils (0.23-4) ...
Trigger processing for mime-support (3.61) ...
Trigger processing for gnome-menus (3.13.3-11) ...
Trigger processing for hicolor-icon-theme (0.17-2) ...
Trigger processing for man-db (2.8.4-2 + b1) ...
There were errors in the processing:
 asbru-cm
```

```
root @ ciro: / home / pancio / Downloads # asbru-cm
Can not locate Gtk2 / Unique.pm in @INC (@INC contains: / opt / asbru / lib / opt / asbru / lib / ex / opt / asbru / lib / edit / etc / perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.0 /usr/local/share/perl/5.28.0 /usr/lib/x86_64-linux-gnu/perl5/5.28 / usr / share / perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 / usr / local / lib / site_perl / usr / lib / x86_64-linux-gnu / perl-base ) at /opt/asbru/lib/PACMain.pm line 48.
BEGIN failed - compilation aborted at /opt/asbru/lib/PACMain.pm line 48.
Compilation failed in require at / usr / bin / asbru-cm line 64.
BEGIN failed - aborted compilation at / usr / bin / asbru-cm line 64.


```

I think the solution is not simple ... or maybe yes?

I can not find alternatives to PAC / ASBRU and I am also willing to donate to see the development continue.

Thanks again to everyone.
Greetings
Mirko

**Comment by gfrenoy** [comment]
Thanks for your feedback and positive encouragements Mirko :)  Technically, I only see two options:

- Find an "unofficial" repository for the packages that are abandoned by Debian
- Migrate Ásbrú to GTK3

First option might be quicker to achieve but the "good" long term option is the second one.

Even if the migration activity started nearly one year ago, we are not very far !  As a matter of fact, I migrated all the "obvious" things but now we need to re-engineer some part of the code and I'm reaching the limit of my knowledge/time to learn...

So to make it short : the project is indeed lacking resources ... Money can be a good incentive to hire skilled people to make us progressing faster.  But the project has today no structure to receive money.

Not sure how to manage this.  Any idea, suggestion or contribution will be warmly welcome.

**Comment by panciom** [comment]
Thanks for the very quick response.

1) Do you know any repository for debian that is right for you? I'm looking for it but I can not find anything. Not being able to use PAC / Asbru is making me waste a lot of time ...

2) I'm a PHP developer ... I know programming but not PERL / GTK. But if you want I can lend a hand how I can. Definitely as a tester but also with the development ... Let me know.

A feature that I would like to have, and for which it can contribute, is the encryption with the "master" password access and the positioning of the configuration file in a folder chosen by the user ... or better still in webdav on nextcloud.

This is to allow a secure centralization of all connections with credentials.

Thank you so much again
Greetings
Mirko

**Comment by gfrenoy** [comment]
1. Sorry, I've no idea.  Maybe a quick workaround would be to find out the last version of the missing packages on https://snapshot.debian.org/ ?  Before they got removed ?

2. You are more than welcome !  Any kind of help will be very much appreciated.  Please contact us by any mean so we can discuss this further.

**Comment by gfrenoy** [comment]
1. I give it a try but the last version of the packages are built against perl 5.26 and buster now comes with perl 5.28.  I also searched a bit but did not find any repository that hosts a version of Gtk2::Unique ; I guess we'll need to rebuild this from the sources ; not sure how to do this though :-/

**Comment by gfrenoy** [comment]
Actually I know !  But I forget I knew :-)  This should be done the same way as https://github.com/asbru-cm/packages/tree/master/libgnome2-vte-perl ... I tried for libgtk2-unique-perl ; it looks to work fine.

**Comment by panciom** [comment]
Hello gfrenoy.
I'm searching and trying to follow your instruction... but i'm unable to compile anything.

I have downloaded this: https://github.com/GNOME/perl-Gtk2-Unique/archive/0.05.tar.gz
After untar:
```

root@ciro:/home/pancio/Scaricati/perl-Gtk2-Unique-0.05# perl Makefile.PL 
Package unique-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `unique-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'unique-1.0' found
 at Makefile.PL line 30.
FAIL: *** can not find package unique-1.0
*** check that it is properly installed and available in PKG_CONFIG_PATH
 at Makefile.PL line 30.
Use of uninitialized value in exit at Makefile.PL line 17.
```

These are the lib installed:
```
root@ciro:/home/pancio/Scaricati/perl-Gtk2-Unique-0.05# apt-get install libuni
libunibreak1               libunicode-utf8-perl       libunique-3.0-0            libunistring2
libunicode-linebreak-perl  libunique-1.0-0            libunistring0              

```

I know I'm asking a lot...but can you help me make asbru work on (my) debian experimental???

Thank you very much anyway.
Hello
Mirko

**Comment by gfrenoy** [comment]
Mirko, you're indeed on the wrong path.  You should look at https://github.com/asbru-cm/packages/blob/master/libgnome2-vte-perl/make_debian.sh (and the [README](https://github.com/asbru-cm/packages/blob/master/libgnome2-vte-perl/README.md) file); the idea is to re-use what the Debian project prepared to make the package.  (and not trying to build from sources...).

If you can, try to join on our IRC channel (https://webchat.st-city.net/#asbru-cm) and we'll try to sort that out together.

**Comment by giaur500** [comment]
I think you can't install libgtk2-unique-perl, because it depends from perl-base 5.24. So you will need to downgrade Perl. This is why package was removed on Perl upgrade.

It may be possible to compile libgtk2-unique-perl against Perl 5.28, but there may be modifications needed to compile, since package is deprecated and not maintained anymore. If somebody succedes, please share deb...

Indeed the best solution would be stop using deprecated libs and this forces you to upgrade to gtk3/gnome3 libs.

**Comment by giaur500** [comment]
@gfrenoy have you thought about flatpak/snap package? This way you can embed all neccesary libs, including any particular Perl or Gnome library versions. I think this is currently easiest way to keep Asbru compatible with all modern distros

**Comment by gfrenoy** [comment]
> I think you can't install libgtk2-unique-perl, because it depends from perl-base 5.24

You are correct.

> you will need to downgrade Perl

That's one option ; not a must.

> It may be possible to compile libgtk2-unique-perl against Perl 5.28

That's another option.

>  but there may be modifications needed to compile, since package is deprecated and not maintained anymore. If somebody succedes, 

Yes, I did ; just did the same as for [libgnome2](https://github.com/asbru-cm/packages/blob/master/libgnome2-vte-perl/README.md).

> please share deb...

Need to find time to finalize but I was planning to do it, yes.

> Indeed the best solution would be stop using deprecated libs 

Definitely.  Any kind of help to reach that goal will be greatly appreciated.

> have you thought about flatpak/snap package?

See https://github.com/asbru-cm/asbru-cm/issues/83

**Comment by giaur500** [comment]
> That's one option ; not a must.

Maybe I was not clear enough. Yes, it's a must as long as you are going to install archived libgtk2-unique-perl version, compiled with older Perl. There is no other solution unless you compile it by yourself for newer Perl version.

As gtk3 is not finished yet, I can see 3 solutions:
- flatpak/snap
- provide all packages compiled with latest Perl and latest libs. But they are deprecated, so this should be only temporary solution until gtk3 version ready
- link statically (probably not possible)

**Comment by giaur500** [comment]
> And actually, it works fine : by reusing the last version of the packages sources (see http://snapshot.debian.org/), I was able to rebuild the package for perl 5.28.

Can you please share?

**Comment by AdrianBan** [comment]
Hi all,

My solution was this:

1. apt source libgnome2-gconf-perl libgtk2-appindicator-perl libgtk2-gladexml-perl
2. Get the sources for libgtk2-unique-perl from https://packages.debian.org/stretch/libgtk2-unique-perl
http://http.debian.net/debian/pool/main/libg/libgtk2-unique-perl/libgtk2-unique-perl_0.05.orig.tar.gz
http://http.debian.net/debian/pool/main/libg/libgtk2-unique-perl/libgtk2-unique-perl_0.05-2.debian.tar.xz
3. Install dependency dev for those packages which are requesting for.
4. dpkg-buildpackage -us -uc -b for each one
5. Get sources for libgnome2-vte-perl and compile it
6. Build packages for ASBRU-CM and install it.

A little bit ugly but is working.. perhaps until next upgrade :))

```
$ dpkg -l | grep "libgnome2-vte-perl\|libgnome2-gconf-perl\|libgtk2-appindicator-perl\|libgtk2-gladexml-perl\|libgtk2-unique-perl\|asrbu"
ii  asbru-cm                                                    5.1.0-1                                 all          A free and open-source connection manager
ii  libgnome2-gconf-perl                                        1.044-6                                 amd64        Perl interface to the GNOME GConf library
ii  libgnome2-vte-perl                                          0.11-1                                  amd64        Perl interface to the Virtual Terminal Emulation library
ii  libgtk2-appindicator-perl                                   0.15-1                                  amd64        Perl bindings for libappindicator
ii  libgtk2-gladexml-perl                                       1.007-2                                 amd64        Perl interface to use user interfaces created with glade-2
ii  libgtk2-unique-perl                                         0.05-2                                  amd64        module for single instance applications

```

**Comment by gfrenoy** [comment]
> > And actually, it works fine : by reusing the last version of the packages sources (see http://snapshot.debian.org/), I was able to rebuild the package for perl 5.28.
> Can you please share?

Same question as [above](https://github.com/asbru-cm/asbru-cm/issues/114#issuecomment-437144753), same answer ;-)

**Comment by panciom** [comment]
Hello and very thanks to all of you guys...

I'm trying what @AdrianBan  write.
But on first command:
```
root@ciro:/etc/apt# apt source libgnome2-gconf-perl libgtk2-appindicator-perl libgtk2-gladexml-perl
Lettura elenco dei pacchetti... Fatto
E: Impossibile trovare un pacchetto sorgente per libgnome2-gconf-perl
```

I'm using PAC on laptop... blocking upgrade of packages.

@gfrenoy the gtk3 branch is totally broken a this time?
I'm interesting in try it.
I already work on eclipse (PDT) and SVN.
I have very little spare time but i can try it... I think the learning curve of perl/gtk3 is too slow for really help develop asbru...
What should i do?

Good weekend to all.
Hello
Mirko

**Comment by gfrenoy** [comment]
> Impossibile trovare un pacchetto sorgente per libgnome2-gconf-perl

Sorry don't have time to finalize or publish anything right now but let me recap the steps again (for libgtk2-unique-perl):

1) Download the latest source packages from http://snapshot.debian.org/ (ie: http://snapshot.debian.org/archive/debian-debug/20170206T205319Z/pool/main/libg/libgtk2-unique-perl/libgtk2-unique-perl_0.05-3.debian.tar.xz)
2) Make a copy of https://github.com/asbru-cm/packages/tree/master/libgnome2-vte-perl
3) Rename all libgnome2-vte-perl to libgtk2-unique-perl
4) Replace the "debian" directory with the one inside libgtk2-unique-perl_0.05-3.debian.tar.xz
5) Change https://github.com/asbru-cm/packages/blob/master/libgnome2-vte-perl/make_debian.sh : mainly replace libgnome2-vte-perl by libgtk2-unique-perl and replace the original source package by https://cpan.metacpan.org/authors/id/P/PO/POTYL/Gtk2-Unique-0.05.tar.gz (or you can also get the latest sources from the Debian project)
6) Submit PR to https://github.com/asbru-cm/packages :)

> gtk3 branch is totally broken a this time?

Well, the application is starting and you can see the splash screen and the welcome screen ... but that's about it :-p

> I have very little spare time but i can try it...
> I think the learning curve of perl/gtk3 is too slow for really help develop asbru...

Same here.  I guess being two times slow is still faster that only one time :)

> What should i do?

- clone the blanch and see if you can reach the point where I am today
- review the board (https://github.com/asbru-cm/asbru-cm/projects/1) and check that you can understand where we are so far
- try to get in touch on IRC so we can exchange our experience and learn together
- pick a card on the board and try to fix it
- create new cards that would describe the next actions/steps better

Thanks a lot :)

**Comment by panciom** [comment]
Hi gfrenoy.
I followed your instructions and successfully created the "libgtk2-unique-perl_0.05-3_amd64.deb" package.

I will try to do the submit completely.
But I still have not come to an end.
A package is still missing ...

```
root @ ciro: / home / hook / Download # dpkg -i asbru-cm_5.1.0-1.debian-stretch.amd64.deb
Selected asbru-cm package not previously selected.
(Read the database ... 312953 files and directories currently installed.)
Preparations for extracting asbru-cm_5.1.0-1.debian-stretch.amd64.deb ...
Extraction of asbru-cm (5.1.0-1) ...
dpkg: dependency problems prevent configuration of asbru-cm:
 asbru-cm depends on libgnome2-gconf-perl; however:
  The libgnome2-gconf-perl package is not installed.

dpkg: error processing the package asbru-cm (--install):
 problems with dependencies - left unconfigured
Trigger processing for desktop-file-utils (0.23-4) ...
Trigger processing for mime-support (3.61) ...
Trigger processing for gnome-menus (3.13.3-11) ...
Trigger processing for hicolor-icon-theme (0.17-2) ...
Trigger processing for man-db (2.8.4-3) ...
There were errors in the processing:
 asbru-cm
root @ ciro: / home / Pancho / Downloads #

```
If I run it:

```
pancio@ciro:~$ asbru-cm 
Can't locate Gnome2/GConf.pm in @INC (you may need to install the Gnome2::GConf module) (@INC contains: /opt/asbru/lib/edit /opt/asbru/lib /opt/asbru/lib/ex /opt/asbru/lib/ex/vte64 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.0 /usr/local/share/perl/5.28.0 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /opt/asbru/lib/PACEdit.pm line 39.
BEGIN failed--compilation aborted at /opt/asbru/lib/PACEdit.pm line 39.
Compilation failed in require at /opt/asbru/lib/PACMain.pm line 60.
BEGIN failed--compilation aborted at /opt/asbru/lib/PACMain.pm line 60.
Compilation failed in require at /usr/bin/asbru-cm line 64.
BEGIN failed--compilation aborted at /usr/bin/asbru-cm line 64.
pancio@ciro:~$ 

```

Do I have to recompile libgnome2-gconf-perl ???
Same procedure?

Thank you so much as always.
Mirko

**Comment by gfrenoy** [comment]
> I followed your instructions and successfully created the "libgtk2-unique-perl_0.05-3_amd64.deb" package.

Very good !

> A package is still missing ...
> Do I have to recompile libgnome2-gconf-perl ???

If it has been removed from Debian, I do fear so...

> Same procedure?

Yes.  Sources are here : https://metacpan.org/release/Gnome2-GConf

And there might be a few more ...

Hang in there, I'm sure we'll make it :)

**Comment by gfrenoy** [comment]
> Finally I managed to run asbru ...

Great !

> what i have to submit PR?

If you can submit sources to https://github.com/asbru-cm/packages ; that'd be fantastic !

So, at the same level as "libgnome2-vte-perl", the directory "debian" and script "make_debian.sh" you tweaked.

Then we can publish the output to packagecloud.io so that others can re-use what you did.

Thanks a lot !

**Comment by gfrenoy** [comment]
> libgnome2-vte-perl still missing, can you share deb?

You'll find it on our [repository](https://packagecloud.io/asbru-cm/asbru-cm).

**Comment by giaur500** [comment]
Just checked, all libgnome2-vte-perl in your repository are still compiled with perl 5.26, can you please share/upload version for Perl 5.28/Debian Sid?

**Comment by panciom** [comment]
Hello @giaur500 .

You are right. Also updating on the laptop is missing the package indicated by you.
I redid the zip with all 3 packages needed for Debian SID / Experimental and perl-5.28.
Ignore the zip in the post above.

[deb_sid_perl5.28_3_packages.zip](https://github.com/asbru-cm/asbru-cm/files/2577862/deb_sid_perl5.28_3_packages.zip)

SHA256:
```
1c136e50ecee8a2b98fa05ecbe45ff8f9cf80ee8b78e47bbb77ba95e38da8a23 libgnome2-gconf-perl_1.044-6_amd64.deb
c28959eb6d7b0229b6c219b37dbb9310f1cfe58fa7208f7e1c034bbb87aa696a libgtk2-unique-perl_0.05-3_amd64.deb
b1c383b2780f4d528ccbd380784692e85546a76c9337c6656caaf7d7abd04454  libgnome2-vte-perl_0.11-1_amd64.deb
```

As long as you manage to get on like this ...
Hello
Mirko

**Comment by panciom** [comment]
I confirm your bug/feature.
@gfrenoy bug or feature?

Thanks as always.

**Comment by giaur500** [comment]
If feature, goot to be able to disable that

**Comment by gfrenoy** [comment]
> bug or feature?

Yes, "feature" :)  See #99

**Comment by giaur500** [comment]
Good tutorials how to manage to build flatpak:
Getting started: http://docs.flatpak.org/en/latest/first-build.html
Real case - package wine: https://ramsdenj.com/2018/03/26/packaging-pathofexile-with-flatpak.html

**Comment by gfrenoy** [comment]
> Good tutorials how to manage to build flatpak

Very interesting, thanks !  But please stay on topic ; this info should be added to #83 ...

**Comment by gfrenoy** [comment]
The latest release [(5.2)](https://github.com/asbru-cm/asbru-cm/releases/tag/5.2.0) can now be installed on Debian 10 (Buster), see [specific instructions](https://github.com/asbru-cm/asbru-cm/wiki/installation-on-debian).

All gtk2 packages that are not delivered by the Debian project anymore are built using the "[packages](https://github.com/asbru-cm/packages)" repository.

Thanks to all who contributed to all of you who contributed to this thread :)
