### ISSUE TITLE
Changing shortcuts for COPY and PASTE commands

### ISSUE THREAD

**Issue by AdrianBan** [asbru-cm/asbru-cm#115]
Hi,

Sometimes is a little bit awkward to use CTRL+SHIFT+C or CTRL+SHIFT+V. There is a solution to change those shortcuts to normal behaviors like CTRL+C or CTRL+V?

Kind regards,
Adrian

**Comment by gfrenoy** [comment]
As of today, shortcuts cannot be changed inside Ásbrú.

PR are welcome :)

(and very personally, CTRL+C for copy will probably give you some headaches when you'll want to stop a command line process ... read [this](https://unix.stackexchange.com/questions/245421/ctrlc-copy-or-interrupt#245574) for more details)

**Comment by blessendor** [comment]
Linux Mint 19 -   SHIFT+CTRL+V  / SHIFT+CTRL+C seems not working. When I press SHIFT+CTRL+V - I get 'M' letter in a terminal shell instead past text from the buffer. With 'C' - getting nothing. Also, there is no reaction to Shift+* in the Midnight Commander (select dirs/fils with wildcard mask).

**Comment by gfrenoy** [comment]
@blessendor This is a different issue.  Please create a new one to discuss this.
