### ISSUE TITLE
Why not know which host is alive with a ping every x minutes that passes through each host in the list. That way we would know which one is on and which one we can not connect. Thanks

### ISSUE THREAD

**Issue by eprompc** [asbru-cm/asbru-cm#117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gfrenoy** [comment]
Ásbrú is not meant to become a monitoring tool.  I'd suggest dedicated solutions like zabbix.

And about the form of your question, please keep the topic short and use the template to better describe you request.
