### ISSUE TITLE
Executing whit sshrc method

### ISSUE THREAD

**Issue by Tamps** [asbru-cm/asbru-cm#118]
Hei

I wold like to request a new connection method whit sshrc, this wold make asbru-cm even more powerfull.
Whit sshrc you can ssh to server whit local .bashrc or .vimrc whit all the aliases and settings configured, it even allow user switching in session and still keep local bashrc settings.
I really wold love to have this future included in asbru-cm

more info:
https://github.com/Russell91/sshrc

--EDIT--
Got ti working, after editing the line 888 to sshrc
https://github.com/asbru-cm/asbru-cm/blob/master/lib/pac_conn#L888

**Comment by gfrenoy** [comment]
To make this generic, I guess we should have an option (per connection) to customize the ssh client to be used.

Not sure how to do this, any help will be greatly appreciated.
