### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by iron-udjin** [asbru-cm/asbru-cm#119]
Hello,

Is there any chance/plan to make port of asbru-cm for FreeBSD? Here is related topic: https://forums.freebsd.org/threads/installation-pac-on-freebsd.28771/

Thank you!

**Comment by gfrenoy** [comment]
Hi Evgeniy,

It would be really great if we can have a FreeBSD port of Ásbrú !

In the core team, there is nobody who can really help to make this happen but if one is willing to work on this, please ask any question here or get in touch on IRC and we'll be happy to assist you.

**Comment by 4mig4** [comment]
I am interested in knowing what is required to make such a port , as I understand Asbru is mostly PERL based ?

**Comment by 4mig4** [comment]
Anyone ported PAC to FreeBSD ?  I can't see to find a port or a package for it on the net either official or unofficial
