### ISSUE TITLE
bracketed paste mode

### ISSUE THREAD

**Issue by nerijus** [asbru-cm/asbru-cm#12]
The problem is described at https://sourceforge.net/p/pacmanager/discussion/1076055/thread/ac548112/ (see 4th and later messages).
I'd like not to paste EOL if line does not end with spaces.

**Comment by gfrenoy** [comment]
Sorry but not sure the get your point here ?

If you want someone to look at your problem, please provide as much details as possible... Maybe some screenshots or a screencast with an example ?

**Comment by nerijus** [comment]
The details are https://midnight-commander.org/ticket/3229
