### ISSUE TITLE
SHIFT+CTRL+V / SHIFT+CTRL+C seems not working

### ISSUE THREAD

**Issue by blessendor** [asbru-cm/asbru-cm#122]
**Describe the bug**
SHIFT+CTRL+V / SHIFT+CTRL+C seems not working. When I press SHIFT+CTRL+V - I get 'M' letter in a terminal shell instead past text from the buffer. With 'C' - getting nothing. Also, there is no reaction to Shift+* in the Midnight Commander (select dirs/files with wildcard mask).

**Desktop (please complete the following information):**
 - OS: Linux Mint 19 Cinnamon 64bit
 - Asbru CM 5.1.0

**Comment by gfrenoy** [comment]
Oleksandr, I tried on a VM running Linux Mint but could not reproduce the same error.

Does this only happen when you are inside Midnight Commander ?

Does this also happen when you are using the corresponding menu entries (in the context menu that is shown when you right click on the screen) ?

**Comment by blessendor** [comment]
I can use the context menu as expected. 
It possible that only problem with my laptop Jumper EZBOOK 3 PRO keyboard

**Comment by gfrenoy** [comment]
Ok let's assume this for now, let us know if you should find any new information about this.
