### ISSUE TITLE
Asbru-CM should save its main window position

### ISSUE THREAD

**Issue by Cris70** [asbru-cm/asbru-cm#123]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Asbru-CM main window appear on my second (left) monitor instead of appearing where it was when I closed it.

**Describe the solution you'd like**
I'd like for Asbru-CM to save it's main window screen coordinates on close, and reposition itself at the same coordinates on start.

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by gfrenoy** [comment]
As far as I can see, the position is already saved (see https://github.com/asbru-cm/asbru-cm/blob/6b70c88e6d0b8c9ad816571d8b7f5a86c1a3b365/lib/PACMain.pm#L3126) but it does not work for some obscure Gtk reasons (see https://developer.gnome.org/gtk2/stable/GtkWindow.html#gtk-window-get-position).

If anyone knows how to get the position of the window, help will be grealy appreciated.
