### ISSUE TITLE
No colors and long wait for shell when connecting to mikrotik routers

### ISSUE THREAD

**Issue by czyzo** [asbru-cm/asbru-cm#125]
When connecting to mikrotik devices - https://mikrotik.com - by ssh You need to wait long for sheel.
Also colors are not displayed correctly.
Here is a screen from KDE konsole - this how it should look like
![konsole](https://user-images.githubusercontent.com/9721628/50251434-2d5ce400-03e4-11e9-8304-1e80c401e03f.png)
And from asbru-cm
![asbru-cm](https://user-images.githubusercontent.com/9721628/50251457-364db580-03e4-11e9-9695-5717618eb768.png)

To reproduce please connect to mikrotik demo device available at admin@demo.mt.lv - no password required: ssh admin@demo.mt.lv

My OS is Kubuntu 18.04 LTS
```console
czyzo@phantom:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
czyzo@phantom:~$ dpkg -l | grep asbru
ii  asbru-cm                                        5.1.0-1                                      all          A free and open-source connection manager
czyzo@phantom:~$
```

**Comment by gfrenoy** [comment]
Issue confirmed but I've no clue about what could cause this.  I would assume it has something to some special code that is used by the target device but one would have to thoroughly analyse the exchanged information...

Can someone help activate the verbose mode and try to find which character is misunderstood by Ásbrú ?

**Comment by beliys** [comment]
^[[?62;9;c is a VT100 control sequence reporting the terminal's status (DA1). (https://stackoverflow.com/a/7653051)

**Comment by MrFishFinger** [comment]
hi @czyzo / @gfrenoy i experienced a similar issue (slow connection, weird control sequence in bottom left hand corner of screen, no colours in terminal).

the solution (workaround?) at least in my case, was to change my connection Authentication settings from using a `Private Key` to using `Manual` (and rely on my `.ssh/config` file for supplying auth settings)
