### ISSUE TITLE
Button for saythanks.io

### ISSUE THREAD

**Issue by lgg42** [asbru-cm/asbru-cm#126]
Creo que un botón de agradecimiento en el README.md vendría bien. Siempre que veo uno lo uso y a parte de las donaciones es otra forma de mostrar aprecio por el trabajo de muchos.

**Comment by KlaasT** [comment]
Thanks for the proposal. I could not create a general account for the project. As soon as that is possible I'll switch over from my personal to a general Saythanks account. In the meanwhile the button has been added.

**Comment by gfrenoy** [comment]
Fyi, https://saythanks.io looks to be offline so I removed the button.
