### ISSUE TITLE
How to manually input the username when launching a connection?

### ISSUE THREAD

**Issue by MiltonLai** [asbru-cm/asbru-cm#127]
**Is your feature request related to a problem? Please describe.**
For example, I have 5 users on the same host A, each stands for different permissions and purpose. For security reasons, I use the Authentication:Manual option so that I can input the password manually. In this case I have to create 5 connection for them, because I cannot find a way to input username for each login

**Describe the solution you'd like**
Is there any way to input the username when launching a connection

Thank you!

**Comment by gfrenoy** [comment]
Try <ASK:username> as the username and probably <<ASK_PASS>> for password unless you have the same for all users ;-p

![image](https://user-images.githubusercontent.com/981546/51412456-efcab280-1b6b-11e9-9e6a-547a3f2068e8.png)

Let us know if this helps.

**Comment by MiltonLai** [comment]
It works! Thank you very much!
