### ISSUE TITLE
Perl script when connection is launched executes multiple times

### ISSUE THREAD

**Issue by syco** [asbru-cm/asbru-cm#128]
Hi,
I'm on the latest git version and I noticed that when you can't login to a server, or the connection drops and then you finally connect, the perl script is executed for every connection attempt.
for example in this following situation the script is executed 3 times when the connection finally opens:
```
<-= DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Thu Feb 14 12:08:59 2019)
 CONNECTING WITH 'test server' (Thu Feb 14 12:09:43 2019) =->

 <-= DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Thu Feb 14 12:10:13 2019)
 CONNECTING WITH 'test server' (Thu Feb 14 12:10:15 2019) =->

 <-= DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Thu Feb 14 12:10:45 2019)
 CONNECTING WITH 'test server' (Thu Feb 14 12:10:46 2019) =->

Last login: Thu Feb 14 11:51:22 2019 from 84.39.232.98
```
I guess the script is queued for every attempt, while in my opinion it should replace the previous script if the connection can't be established.

**Comment by gfrenoy** [comment]
Thanks for the feedback, I found out that the script was indeed somehow queued every time the connection is started (even if not properly completed).

I made a change that I just pushed it so a new version will be available in the snapshot repository in a few minutes ; will you give it a try and let us know if it helps ?

**Comment by syco** [comment]
Thanks, it works great.
