### ISSUE TITLE
color

### ISSUE THREAD

**Issue by nerijus** [asbru-cm/asbru-cm#13]
Why there is a difference in colors? In both cases TERM=xterm.
asbru:
![asbru](https://user-images.githubusercontent.com/591932/32515575-46ba0a48-c409-11e7-889a-b62854f0bfc6.png)

PAC:
![pac](https://user-images.githubusercontent.com/591932/32515580-4c6a2630-c409-11e7-9e9b-5cb33db1c537.png)

**Comment by gfrenoy** [comment]
Interesting :-)

This has for sure not been changed intentionally.  Maybe some default color values are different ?

Are you using the exact same configuration files (in .config/pac) for both screenshots ?

**Comment by gfrenoy** [comment]
If you look at the preferences dialog, they are not exactly the same:

Ásbrú:
![image](https://user-images.githubusercontent.com/981546/32521781-28a5d15c-c415-11e7-8ed9-cf0eb039c3c9.png)

PAC:
![image](https://user-images.githubusercontent.com/981546/32521788-2e65368c-c415-11e7-80d2-3b83146a092e.png)

So it looks like new options were available in the latest sources but they were never published ?

If I commented out line 3304 of PACTerminal.pm it goes back to the same color as in PAC so this is certainly the guilty one...

Should we maybe remove those options for now ?

**Comment by nerijus** [comment]
Yes, the config is the same.
If there is a possibility to change color now, let's leave it.

**Comment by gfrenoy** [comment]
I made more experiments and you can now indeed change colors, it works fine :)  And by default it takes the colors that are defined in Gtk.

I guess we can close that issue, isn't it ?  If you don't agree, just let me know.
