### ISSUE TITLE
Fedora29 - yum-utils in conflict with dnf-utils

### ISSUE THREAD

**Issue by Hakun1n** [asbru-cm/asbru-cm#130]
**Describe the bug**
Installation script tries to install yum-utils which is in conflict with dnf-utils.

**Expected behavior**
Check if dnf-utils package exists in system if yes then skip. If no then better to install dnf-utils instead of yum-utils (as yum is deprecated)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 29

**Additional context**
Terminal log: https://pastebin.com/0sHthdDK

**Comment by gfrenoy** [comment]
Ásbrú does not require ```yum-utils```.

This is the [packagecloud.io setup script](https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.rpm.sh) that is installing it :-/

Can you [contact them](https://packagecloud.io/contact) directly to see if they can do something about it ?

**Comment by Stunherald** [comment]
Wow, thanks for quick response. Okay got the point. Will drop them an email :]
