### ISSUE TITLE
Wrong tooltip for Session log numbers

### ISSUE THREAD

**Issue by Hakun1n** [asbru-cm/asbru-cm#131]
**Describe the bug**
Tooltip for number of session logs provides wrong info. Suggests "A" for keeping all logs instead of "0". Cosmetic bug but confusing.

**To Reproduce**
- Go to Settings -> Terminal options -> Behaviour
- Mouse-over the "Files to save" text, you get tooltip "0 to keep ALL the session logs" // This is OK
- Mouse-over the actual text-field where you put the value. You get "**A** to keep ALL the session logs" // You can't put "A" in there

![image](https://user-images.githubusercontent.com/12685294/53289060-375ae480-3791-11e9-8cc1-1aca4360e067.png)

**Comment by gfrenoy** [comment]
Thanks for the feedback.  Apparently a typo in [pac.glade](https://github.com/asbru-cm/asbru-cm/blob/master/res/pac.glade).

I'll fix this now and will be available in the snapshot until we release a new version.
