### ISSUE TITLE
More compact server-list tree

### ISSUE THREAD

**Issue by Hakun1n** [asbru-cm/asbru-cm#133]
**Please describe.**
I have bunch of servers to manage separated to several (sub)groups so it is easy to quickly find and connect the needed one. Sadly due to the way how the tree graphic is build there is significant waste of space. See the attached screen bellow what i mean. The "red" markings.
![image](https://user-images.githubusercontent.com/12685294/53299691-ccb3b280-383d-11e9-8468-f0a571bdea33.png)

**Describe the solution you'd like**
Get rid of the unnecessary spaces. The indent for sub-tree objects is too width. Make the list more compact, just a small indent is enough. Spaces between icons and server names are too big. 

**Describe alternatives you've considered**
It seems like the whole tree is a table-based. So maybe allow user to change the column width. Or remove the folder icons completely. Or allow UI to be changed to alternative ASCII-based tree structure, like:
 \+ Collapsed Grp1
 \- Expanded Grp1
├ \+ Collabsed SubGrp1
├ \- Expanded SubGrp2
│├ [S] SSH server 1
│├ [C] SCP server 2
│└ [R] RDP server 2
└ \+ Collabled SubGrp3
 \+ Collapsed Grp3

**Additional context**
This is a screenshot from GCM. Sadly that software got abandoned and not functional on KDE Plasma. As you can see the server list is more compact so the extra space can be used for terminal width. This is beneficial especially in exploded/side-by-side terminal view.
![image](https://user-images.githubusercontent.com/12685294/53299815-d50ced00-383f-11e9-998b-f2f7ed380336.png)

**Comment by gfrenoy** [comment]
We should indeed remove that unnecessary padding.

I guess it must be in the [PACTree](https://github.com/asbru-cm/asbru-cm/blob/e5372718199cd4d8ecd11f33795564fb59b98503/lib/ex/PACTree.pm) definition but I cannot find where today...

Any help will be greatly appreciated.

**Comment by gfrenoy** [comment]
I investigated a bit more on this.

The space that we see is not really "padding".  The trick is that there are two columns ; the first one contains the icons and the second one contains the text.

When you have a hierarchy with many sub-levels, the width of the first column is larger and leads to large space...

To understand this better, you should collapse all levels and restart Ásbrú.  After you restart, the column width will be at its very minimum.  Then start collapsing some levels and the width of the first column will start to increase ... So will the space between the elements !

Except if we change completely the way the tree is built, I do fear there is not much we can do.

**Comment by gfrenoy** [comment]
Thanks for the autosize when collapsing @hanspr ; it helps :)

Is there a any way to remove the left padding of the arrow when expanding a node ?

**Comment by hanspr** [comment]
Having the current way to do it

1)
As you pointed out, is done with columns, it means that we would have to rearrange the columns in each expansion contraction, but because the tree is attached to PACTree.pm and this library adds a layer to interact with the tree, I can not see right now what side effects would create to re arrange columns.

2)
We remove the icons, the tree will be smaller, but I kind of like the icons.

3)
Is to have only 1 column. But the widget does not accept images or HTML tags in it. So, for that we would need to use UTF8 icons, and no image icons. Then the name would include character icons, like a: folder character, a file character, etc.

Something like this (this below are no images, are characters from utf8):

📁 Group
🗃 Cabinet

But they would show differently on each computer and the font that is active.

And recently apparently many fonts are under design and many icons that were available before are now missing from many fonts and the show up like this: 🗔

**Comment by hanspr** [comment]
I have played with all available options, and this is what I have managed to get

![imagen](https://user-images.githubusercontent.com/1572396/67738096-1824ee80-f9d3-11e9-9ef4-d538a4384cc5.png)

This way the icons and the text do not separate

But I can not find a way to squeeze the arrows on the left.

Do you want me to send a PR with this change?

**Comment by hanspr** [comment]
And this is what I can get using UTF8 icons.

![imagen](https://user-images.githubusercontent.com/1572396/67742720-6d1c3100-f9e2-11e9-9f02-2aad3d2701e5.png)

**Comment by gfrenoy** [comment]
> And this is what I can get using UTF8 icons.

Waw, this is much more compact !  It has certainly my preference.

**Comment by hanspr** [comment]
We could give it a try and see what is the response.

I would leave all the original code that is not used commented in case we have to go back.

My only concern is if it will render properly in other computers. UTF8 icons are becoming more common every day, and they are adding an improving there looks all the time.

**Comment by KlaasT** [comment]
I believe UTF8 icons should already be near standard for every modern operating system. At least I haven't heard of any Linux OS not supporting UTF8 icons. 

Therefore great job :-)

**Comment by KlaasT** [comment]
Closed #133

**Comment by gfrenoy** [comment]
The server list looks definitely more compact, thanks :)

But now, the icons that we see depend on the font that is selected in Main Options > Look and Feel > Connections Tree Font ; am I correct ?

The selected Unicode characters are maybe to be improved as well:

SSH --> https://unicode-table.com/en/1F4BB/
RDP --> https://unicode-table.com/en/1F308/
Others --> https://unicode-table.com/en/1F4A0/

That does not sound very "obvious" to me :-/

We might need to create a few more issues from here:
- to have an embed font (would [Font-Awesome](https://github.com/FortAwesome/Font-Awesome) work ?) to have more "branded" options (like https://fontawesome.com/icons/microsoft?style=brands)
- be able to select the font to be used for the icon
- be able to select the unicode character to use for each type of connection

**Comment by B1tl0rd** [comment]
I think the idea is good, to use an embedded font that can be selected and can select the icon from fontawesome.

**Comment by hanspr** [comment]
I would not know at the moment how to embed a font (gtk3 still not my strength)

I need to check how powerful is the rendering engine that is displaying the labels, I know that support the basic html, but I have not played with it to see at what extents it supports it.  Does it have support for css? how is it used?

If you have any knowledge on this, to point me in the right direction, would be appreciated.

**Comment by hanspr** [comment]
After some reading and testing, adding an image is not possible, the markup languange is a small subset of html, Pango text markup language. It does have the possibility to apply fonts to a tag using a style property.

I installed font awesome in my computer to see the effect. Well ?, they do not have colours and look very plain to me.

![imagen](https://user-images.githubusercontent.com/1572396/68090311-f3e46a00-fe37-11e9-9f6d-ff3d309b32f3.png)

This is the link where I have found existing utf8 icons.

https://apps.timwhitlock.info/emoji/tables/unicode

For sure, if we keep going in this direction we will not find very specific icons like : rdp, ssh, mosh (thou the icon looks like a pager and there is a pager utf8 code).

But the meaning could be improved by adding additional text like this

![imagen](https://user-images.githubusercontent.com/1572396/68090520-4c1c6b80-fe3a-11e9-9f90-0a6447ab063c.png)

---

To use images, we would have to go back as before, and take a deep dive into PACTree.pm

This is where the implementation would have to be changed. Add a new user defined type, and find how to send the icon and label using that user defined type, and then add each of them to a cell and then add the cells to the first column. And the code is still too obscure to me to know how to get it done.

**Comment by hanspr** [comment]
Looking at the actual icons images right now, in reality they are not even icons, must are the method  name inside a square

![imagen](https://user-images.githubusercontent.com/1572396/68090712-9c94c880-fe3c-11e9-8192-341c67dd7294.png)

Telnet, sftp, mosh and tty, I do not look very intuitive either.

The only icon that is relatable as an icon, is the rdp icon.

So adding small labels as suggested does not seem much different than a square image with a text inside.

![imagen](https://user-images.githubusercontent.com/1572396/68090766-4f652680-fe3d-11e9-94a8-03b82dc757f6.png)

And with this approach we just have to agree on icons that would be more pleasant.

**Comment by gfrenoy** [comment]
Thanks for the additional researches, comments and suggestions, they really help !

I think the bottom line is:

1) Unicode character does not define how it looks but what it is.  Said differently: how "pleasant" a Unicode character is depends on the font you are using.

2) There is no Unicode character for our concepts (like RDP/SSH connections).

So I'm really wondering if we should not revert back to icons where we have the flexibility to use any images (or preferably SVG files) that we would find "pleasan" :-/

**Comment by hanspr** [comment]
Yep,

So what I can do right now is take the code back to images having them aligned as this

![imagen](https://user-images.githubusercontent.com/1572396/68091128-85a4a500-fe41-11e9-8097-4422113b790d.png)

That was the best I could get with the actual implementation.

Tell me and I send the PR back to this option.

**Comment by gfrenoy** [comment]
My 2 cents:

- Not yet as compact as we wished
- But does not look bad at all
- We should look for new (hopefully better) images (v6 would deserve this...)
- Thanks a lot !

**Comment by B1tl0rd** [comment]
Mobaxterm icons, I personally like them. we could look for something similar, even you can select the preference icon. Obviously I know that there are programming issues that define this task and a great job ...
thanks for the contributions
