### ISSUE TITLE
Cluster Controller - Uninitialized value (Expect.pm)

### ISSUE THREAD

**Issue by Hakun1n** [asbru-cm/asbru-cm#134]
**Describe the bug**
Using the "Power Cluster Controller" with "Send on <INTRO>" enabled throws error(s)
_Use of uninitialized value in pattern match (m//) at /usr/share/perl5/vendor_perl/Expect.pm line 1077.
Use of uninitialized value in string eq at /usr/share/perl5/vendor_perl/Expect.pm line 1086.
Use of uninitialized value in string eq at /usr/share/perl5/vendor_perl/Expect.pm line 1093.
Use of uninitialized value in regexp compilation at /usr/share/perl5/vendor_perl/Expect.pm line 763._

![image](https://user-images.githubusercontent.com/12685294/53301426-0cd16000-3853-11e9-9958-66f1ff983b14.png)

![image](https://user-images.githubusercontent.com/12685294/53301439-4d30de00-3853-11e9-92ef-98b83817917f.png)

**To Reproduce**
1. Go to Power Cluster Controller
2. Enable "Send on <INTRO>"
3. Write command and hit ENTER. Command is sent to all terminals but error is thrown.

**Desktop (please complete the following information):**
 - Client OS: Fedora 29 Plasma
 - Server OS: AIX 7.2 PPC64

**Comment by gfrenoy** [comment]
Don't have this issue on Ubuntu 18.04.

And the error is actually reported by the "Expect" package in perl so I'm not sure we can do anything about this in Ásbrú.

**Comment by Hakun1n** [comment]
I've raised BUGreport on redhat bugzilla (https://bugzilla.redhat.com/show_bug.cgi?id=1688773) but i guess they will want to know more details about the issue. Sadly enabling the "Expect DEBUG" option does not add any extra errors when reproducing the issue so i have no idea what is being called on the background when using the PCC.

Maybe if you could add some extra logging for the PCC funcion so the DEBUG actually throws details WHAT was sent to expect it will provide more details what is wrong.

Thanks!

**Comment by gfrenoy** [comment]
Can't reproduce this here ; not even sure I've the same version.

Line 1077 of Expect.pm looks to be inside the "interact" function here ; and it looks like it's only called in [pac_conn line 1811](https://github.com/asbru-cm/asbru-cm/blob/cfa86036548d4a197f5abcadd35c84e8a93b5821/lib/pac_conn#L1811) ; can you try to add a ```print``` or ```ctrl``` there to see if you can grab more information ?

**Comment by Hakun1n** [comment]
Sorry but i am not a python Dev so not sure how/where to add "what".  But if you provide modified files/code i am happy to do the tests and provide output.

**Comment by gfrenoy** [comment]
Nor am I.  And, btw, it's written in Perl :)

This project is meant to be a community project ; I'm always happy to help but when it goes beyond what I can quickly reproduce on my environment, I'm not ready to invest more time and just label the issue as "help wanted" (and hoping that someone else will jump in and provide more information to find the root cause and fix the issue).

What I can do though is to share my very limited knowledge on how to add traces in Perl ...

**Comment by Hakun1n** [comment]
I understand the concept of "community project" but if there is no "community", there is no progress. Don't get me wrong here i appreciate your efforts of forking PAC and trying to resurrect its heavy potential. Sadly most of the issues are being auto-closed or marked as help-wanted while no help is coming. I have to put this aside and go back to old GCM mostly because the hard-coded expect integration scares the hell out of me with all of the recent issues. I don't want to end up in a situation when one day i sent some string to a productive shell and it parses it into console with destructive consequences.

I would really like to see this project to succeed so i wish you good luck and i hope one day some Perl-guru will stumble over this project and help with the open issues.

**Comment by gfrenoy** [comment]
What would be your suggestion(s) to motive a Perl-guru helping us ?

**Comment by gfrenoy** [comment]
@Hakun1n Just made a commit that should avoid the scary messages (see [f380ac2](https://github.com/asbru-cm/asbru-cm/commit/f380ac277ac8381de5548c554ff095b7444594ad)).

Please give it a try with the snapshot version (see [instructions](https://github.com/asbru-cm/asbru-cm/wiki/Installation-on-Fedora#snapshot-release)) and let us know it this helps.
