### ISSUE TITLE
App closes/crashes

### ISSUE THREAD

**Issue by Mjolinir** [asbru-cm/asbru-cm#135]
Environment:
Fedora 28 & 29
Asbru ver 5.1.0 (and previous)

Not sure if anyone else has noticed this, but it happens daily for me. When Asbru is open and running, it will randomly close/crash: whenever closing other windows on my system this happens. Most notably is Pidgin or Kopete. When I close a chat window with a co-worker, Asbru does this. It is not every time. 
More often than not, everything is fine. I have also noticed other applications closing to cause this. It also happens with PAC

**Comment by gfrenoy** [comment]
Can start Ásbrú from the command line interface and report us the error message you see when it crashes ?

**Comment by Mjolinir** [comment]
This is the error in the console when it happens

`Gdk-ERROR **: The program 'asbru-cm' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 6632380 error_code 3 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.) at /usr/share/asbru-cm/lib/PACUtils.pm line 3048.
[1]    9344 abort (core dumped)  asbru-cm
`

**Comment by gfrenoy** [comment]
Thanks for the additional information.

As far as I can see in the mentioned line ([3048 PACUtitls.pm](https://github.com/asbru-cm/asbru-cm/blob/e5372718199cd4d8ecd11f33795564fb59b98503/lib/PACUtils.pm#L3048)), it is a call that request information (to Gdk) about all Gdk windows ; if Ásbrú is asking information about a window that has just been destroyed, that could explain the crash.

It is requesting this information to find out which window contains the newly created RDP (or VNC) connection (see [here](https://github.com/asbru-cm/asbru-cm/blob/e5372718199cd4d8ecd11f33795564fb59b98503/lib/PACTerminal.pm#L1151)).  Strangely enough, it never finds it and try again and again, every 500ms.

So, eventually, every time you close a window, you can be inside this look that crashes !

I'll commit a change that will only do that operation 1 time and stop doing it if it fails.

This does not really fix the root issue but at least the chances that it crashes will be very low.

Please try the snapshot version (within 1 hour to let the system rebuild a new version) and let us know if it helps...

**Comment by Mjolinir** [comment]
This seems to have helped for sure, I have had only 1 crash since updating, where I normally would have had dozens!

**Comment by gfrenoy** [comment]
Thanks for your feedback.  Let's consider this fixed for now.
