### ISSUE TITLE
No packages for Ubuntu 17.04

### ISSUE THREAD

**Issue by clickwir** [asbru-cm/asbru-cm#14]
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

$ sudo apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu zesty InRelease
Hit:2 http://security.ubuntu.com/ubuntu zesty-security InRelease                                 
Hit:3 http://us.archive.ubuntu.com/ubuntu zesty-updates InRelease                                   
Hit:4 http://us.archive.ubuntu.com/ubuntu zesty-backports InRelease                                 
Ign:5 https://packagecloud.io/asbru-cm/asbru-cm/ubuntu zesty InRelease   
Err:7 https://packagecloud.io/asbru-cm/asbru-cm/ubuntu zesty Release
  404  Not Found
Hit:6 http://screenshots.getdeb.net zesty-getdeb InRelease
Reading package lists... Done                      
E: The repository 'https://packagecloud.io/asbru-cm/asbru-cm/ubuntu zesty Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Should there be?

**Comment by clickwir** [comment]
FWIW, I upgraded to 17.10 and it installs fine now.

Maybe we don't need 17.04 packages since it's only officially supported for a couple more months anyway.

**Comment by gfrenoy** [comment]
You are again very correct ;-)  We did not release a package for zesty.  We did not identify this as a very popular target since everybody should be on either Xenial (16.04 LTS) or Artful (17.10).

I'll close this for now but if one really needs the package for Zesty, this is something we can probably do.
