### ISSUE TITLE
Ubuntu 19.04 - uninstallable

### ISSUE THREAD

**Issue by monark88** [asbru-cm/asbru-cm#140]
**Describe the bug**
Unable to install asbru on Ubuntu 19.04

**To Reproduce**
1. Try to install from package cloud
2. It fails

**Expected behavior**
Should get all dependencies and install

**Desktop (please complete the following information):**
Ubuntu 19.04 (Mate amd64)

Unfortunately due to unresolved issues from 18.10, 18.04, 17.10 and so on and so forth, this is uninstallable on Ubuntu 19.04...

**Comment by gfrenoy** [comment]
Support for Ubuntu 19.04 is still to be done (and probably not before the official release...).

Not sure to understand you comment about earlier versions.  It should work fine up to 18.10 (but please consider this [comment](https://github.com/asbru-cm/asbru-cm/issues/113#issuecomment-464928575)).

**Comment by RogueScholar** [comment]
To illuminate the matter a bit more, there's a singular reason why the cosmic packages are wholly incompatible with 19.04 Disco, and that's the dependency on perlapi-5.26.2, as Disco advances the Ubuntu base up to perl 5.28.1. In fact the repos no longer have a package named perlapi-*, obviously a decision must've been made upstream to subsume those files into another package.

Does that suggest to you that it will be a quick fix when you are able to get around to it, or something more painstaking?

**Comment by gfrenoy** [comment]
At least, we need to rebuild the "vte" package.  You'll find instructions here https://github.com/asbru-cm/packages/tree/master/libgnome2-vte-perl.  This is fairly straightforward.

If more packages are missing, that's another story ... One will need to have a closer look.

**Comment by RogueScholar** [comment]
My compliments to your structuring the repository as you did to facilitate repackaging those dependencies, that was most helpful and the accompanying documentation was quite instructive for someone who'd never done a single bit of Debian packaging before.

All three packages build without issue, and [I've added them to my PPA](https://launchpad.net/~roguescholar/+archive/ubuntu/ppa) for the time being, for others who may be trying to hang onto Asbru CM during the transition to Disco Dingo.

**Comment by monark88** [comment]
I was about to report back and say building those packages got it up and running on Disco Dingo.  Thanks for the PPA.

**Comment by gfrenoy** [comment]
Thanks for setting up this PPA :)  I did try from a fresh 19.04 but I got the following error:

```
*** unhandled exception in callback:
***   Can't locate object method "new" via package "Gnome2::Vte::Terminal" (perhaps you forgot to load "Gnome2::Vte::Terminal"?) at /opt/asbru/lib/PACTerminal.pm line 506.
***  ignoring at /opt/asbru/lib/PACMain.pm line 368.
```

And when I look into the ```libgnome2-vte-perl``` package, there is nearly nothing (only some documentation file):

```
$ sudo dpkg -L libgnome2-vte-perl
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libgnome2-vte-perl
/usr/share/doc/libgnome2-vte-perl/NEWS.gz
/usr/share/doc/libgnome2-vte-perl/changelog.Debian.gz
/usr/share/doc/libgnome2-vte-perl/copyright
```

**Comment by RogueScholar** [comment]
That's entirely possible, I'm going to do some investigating right now. This is the very first time I've even glanced at the framework behind Debian packaging and quite frankly the minutiae are so dizzyingly intricate re: metadata that at some point I know I stopped even looking at the underlying build process itself.

I appreciate you testing it out for me and giving me a chance to improve at it. I'll report back with what I find.

**Comment by RogueScholar** [comment]
Alright, problem solved. Turned out the DEBIAN/control file didn't declare libvte-dev as a Build-Dependency, though I suspect that I'm still not grasping some nuance of the build process because if that were the real issue then the package would never have built successfully before. If you have any insights on that, I'd love to continue learning.

In any event, the `libgnome-vte-perl` packages in [my PPA](https://launchpad.net/~roguescholar/+archive/ubuntu/ppa) are complete and functional, available for Bionic, Cosmic and Disco to any and all who are interested.
![2019-04-15 08 53 07 launchpadlibrarian net c7cdb101f626](https://user-images.githubusercontent.com/15098724/56146881-f2b32480-5f5b-11e9-8f6d-f0e05821f6d4.png)

**Comment by gfrenoy** [comment]
It looks indeed much better :)

Don't hesitate to submit a pull request for the missing dependency.  When I build it, I always apply what is written in the [README](https://github.com/asbru-cm/packages/tree/master/libgnome2-vte-perl) of the packages repo.  There is an ```apt install libvte-dev``` there but it would be much better to have it in the control file !

**Comment by gfrenoy** [comment]
Fyi, I gave it another try and it just worked like a charm ; if you really start from scratch, here are the instructions:

```
sudo apt-add-repository multiverse
sudo add-apt-repository ppa:roguescholar/ppa
sudo apt-get update
sudo apt install asbru-cm
```

Thanks a lot !  If you want to join our efforts maintaining Ásbrú, you're very welcome :)

(ps: I'll push some changes to the packages repository according to what we discovered here)

**Comment by gfrenoy** [comment]
The latest release [(5.2)](https://github.com/asbru-cm/asbru-cm/releases/tag/5.2.0) can now be installed on (k)ubuntu 19.04, see [specific instructions](https://github.com/asbru-cm/asbru-cm/wiki/installation-on-ubuntu).
