### ISSUE TITLE
Common Router characters do not behave correctly (TAB, CTRL-a, CTRL-e, UP-Arrow)

### ISSUE THREAD

**Issue by coldiso** [asbru-cm/asbru-cm#141]
**Is your feature request related to a problem? Please describe.**
When I login to common Cisco routers and switches the TAB completion options among others (CTRL-a, CTRL-e, UP-Arrow) do not behave as expected in a normal xterm/terminal window.  I don't see where I can edit more ENV settings and I have tried multiple local Preferences.

**Describe the solution you'd like**
For the terminal in Asbru to behave like a standard terminal (xterm or otherwise)

**Describe alternatives you've considered**
xterm/terminal behave fine

**Additional context**

**Comment by coldiso** [comment]
I found that if I unchecked `Forward X` it resolved the issue - FYI

**Comment by gfrenoy** [comment]
Good that you found out the solution :)  Can we consider this as closed ?

**Comment by coldiso** [comment]
Hi Gaëtan Frenoy - you can consider this closed - i have opened a defect with the vendor i was testing against =) sorry for the noise.
