### ISSUE TITLE
New windows will not get focus

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#142]
**Distro**

This happens in Linux Mint 18.3 Cinnamon, can not confirm if it happens in other distros

**Bug**

- Main PAC Window Hidden
- Click on Tray Icon
- Dobleclick on a saved connection to open new session
- Main PAC Window hides to tray
- New window will open connects
    - window will be on top
    - focus will be on the new created window terminal ready to type

![Selección_001](https://user-images.githubusercontent.com/1572396/56471838-bdf01300-641c-11e9-9379-9d52118f9345.png)

- Main PAC Window Hidden
- Click on Tray Icon
- Dobleclick on same (previous) saved connection to open new session
- Main PAC Window hides to tray
- New window will open connects and
    - New Window will be on top
    - But focus will be on the previous window
    - if I type anything, it will be on the first opened window not visible under the new terminal window

![Selección_002](https://user-images.githubusercontent.com/1572396/56471905-7e75f680-641d-11e9-8316-fad255d91227.png)

**Expected behavior**

new widow to get focus for typing.

**Ugly Hack**

I do not find the code where Asbru sends focus to the previous window, so I had to add an ugly hack to it using wmctrl, changing this code.

```
PACMain.pm
Around line: 2786

    foreach my $t ( @new_terminals ) {
        $$self{_GUI}{_PACTABS} -> present if $$t{_TABBED};
        if ( ! $t -> start( $keys_buffer ) ) {
            _wMessage( $$self{_GUI}{main}, __( "ERROR: Could not start terminal '$$self{_CFG}{environments}{ $$t{_UUID} }{title}':\n$$t{ERROR}" ), 1 );
            next;
        }

       # ADDED TO SET FOCUS ON NEW WINDOW AFTER 300 MILLISECOND WAIT
        if (!$$t{_TABBED} ) {
            my $title = $$t{_WINDOWTERMINAL}->get_title;
            select(undef, undef, undef, 0.3);
            system "wmctrl -a '$title'";
#           $$t{_WINDOWTERMINAL}->present;
        }
        $$t{_GUI}{_VTE} -> grab_focus;

PACTerminal.pm
Around line: 57

# Define GLOBAL CLASS variables

my $APPNAME     = $PACUtils::APPNAME;
my $APPVERSION  = $PACUtils::APPVERSION;
my $APPICON     = $RealBin . '/res/asbru-logo-64.png';
my $CFG_DIR     = $ENV{'HOME'} . '/.config/pac';

my $PERL_BIN    = '/usr/bin/perl';
my $PAC_CONN    = $RealBin . '/lib/pac_conn';

my $SHELL_BIN   = -x '/bin/sh' ? '/bin/sh' : '/bin/bash';
my $SHELL_NAME  = -x '/bin/sh' ? 'sh' : 'bash';

my $_C          = 1;
my $EXEC_STORM_TIME = 0.2;

my @KPX;
my $TERM_COUNT = 0;  # ADDED NEW VARIABLE TO NUMBER EACH NEW TERMINAL

Around line: 711-712
    # New WINDOW:
    else
    {
        $TERM_COUNT++;  # INCREASE COUNT
        # Build a new window,
        $$self{_WINDOWTERMINAL} = Gtk2::Window -> new;
       # ADDED COUNT TO TERMINAL TITLE TO BE ABLE TO FIND IT LATER WITH wmctrl
        $$self{_WINDOWTERMINAL} -> set_title( $$self{_TITLE} . " : $APPNAME (v$APPVERSION) - ASBRU$TERM_COUNT" );
        $$self{_WINDOWTERMINAL} -> set_position( 'center' );
        $$self{_WINDOWTERMINAL} -> set_size_request( 200, 100 );

```

In PACMain.pm, I have have tried : 

- $$t{_WINDOWTERMINAL}->present;
- $$t{_WINDOWTERMINAL}->set_focus;
- $$t{_WINDOWTERMINAL}->activate_focus;

None has worked. Don't know how to accomplish this internally with Perl and GTK object.

**Comment by gfrenoy** [comment]
What kind of theme options do you have ?

I don't recognize the default Mint 18.3 Cinammon icons and layout.  It looks more like this here:
![image](https://user-images.githubusercontent.com/981546/56472886-7f7e4680-6464-11e9-9ced-d908e7d31c6f.png)

What I really don't understand is where is the "Ásbrú Connection Manager" title bar ?

**Comment by hanspr** [comment]
Hi,  I just wanted to save image space, but if you need it, here it is.
Is Linux Mint 18.3, Personal Skin (no window border title on maximized windows, flat, task manager without titles, title for active window at center), Numix-Folders, Icons Numix Circle.
Hope this is not the cause of the issue.
Can test with a normal theme if you like

![KbEoSaB4wJ](https://user-images.githubusercontent.com/1572396/56473262-357a6e00-642e-11e9-8cc7-c071b0f296d9.png)

**Comment by hanspr** [comment]
Perhaps I did not explain my self correctly, will try again:
- I do not use tabs, all sessions open in new maximized windows
- Asbru main window closes after opening the new session (minimized to taksbar)
- Add my Asbru preferences image
- And Terminal options

![Selección_001](https://user-images.githubusercontent.com/1572396/56473346-d6b5f400-642f-11e9-8ebd-f5cbddb8062a.png)

![Selección_002](https://user-images.githubusercontent.com/1572396/56473347-d9184e00-642f-11e9-88ec-d1c71f3492a4.png)

![Selección_003](https://user-images.githubusercontent.com/1572396/56473348-dc133e80-642f-11e9-8a5a-23e1446625d5.png)


 image

**Comment by hanspr** [comment]
I did a test with a normal theme to make sure is not a theme related bug (please, ignore menu icon is not a Mac), the result is the same, this is the full sequence:

Asbur is minimized to task bar.
![Selección_001](https://user-images.githubusercontent.com/1572396/56476269-d121d380-645a-11e9-8992-94524b4cf369.png)

Click on Tray Icon and Asbur, shows connections, I clic on Sanfandila
![Selección_002](https://user-images.githubusercontent.com/1572396/56476274-e72f9400-645a-11e9-8b10-ed6d503910ca.png)

Sanfandila Session opens, Asbur minimized to task bar, skiped this step on next image, sorry.
Click again on Tray Icon, Asbur main window shows, click again on Sanfandial
![Selección_003](https://user-images.githubusercontent.com/1572396/56476277-f878a080-645a-11e9-9fd9-2fcb46443b5b.png)

New window opens, but the first one has the focus.
![Captura de pantalla de 2019-04-21 17-21-28](https://user-images.githubusercontent.com/1572396/56476308-6cb34400-645b-11e9-9676-d36cf0f061a5.png)

**Comment by gfrenoy** [comment]
Hans, thanks for the additional information and very comprehensive explanations !  One additional option that needs to be changed to reproduce this : "Put Terminal TABS in Main Window" has to be unchecked otherwise the "hide on connection" is not working.

So I could reproduce the issue, even on Ubuntu and I think I found a trick to workaround this.  A variable ```$$self{_HAS_FOCUS}``` has to be set.  See commit [2aef43d](https://github.com/asbru-cm/asbru-cm/commit/2aef43d0e6ef721534b11653844092c36e3f7585).

Please try the patch or try the snapshot version (see [instructions on Mint](https://github.com/asbru-cm/asbru-cm/wiki/Installation-on-Mint#snapshot-release)) and let us know if it helped.

**Comment by hanspr** [comment]
Sorry, had a very busy day. I did not understand your request, but I can see you applied a new commit.

It works, has a minor side effect, but it works.

The side effect is that after the first session is opened, when you clic on the tray icon to show the main asbru-cm window, this time will show under the terminal session, this does not happen after the second session is opened or later.

I can live with that, thanks. Have 2 more bugs, one really nasty, but will give you a break.

Thanks again, don't see any donation button :100:

**Comment by gfrenoy** [comment]
Can you try the last commit (https://github.com/asbru-cm/asbru-cm/commit/9fa62c867e73c8b5f398bbad23a5fc422ffe4e2f) ; it should fix the little side effect.

**Comment by hanspr** [comment]
Perfect is working perfectly, this issue can be closed.
