### ISSUE TITLE
Store only fresh logs in log files.

### ISSUE THREAD

**Issue by porquinhopequenho** [asbru-cm/asbru-cm#144]
After checking the options and done some research, I haven't found the solution.
My apologies in advance in case it's already fixed/known.

When a new log file is opened to record logs, all the previous logs of the session are stored, despite those may have already been recorded in a default log file. Only fresh new logs are intented to be stored in the new log file, but that seems hard to manage.

Logging to a new log file should start from the moment the new log file is opened. Previous logs, recorded in other files, are flushed or, at least, not recorded in the new file. That would permit separate log files from different stages of a connection.

**Comment by gfrenoy** [comment]
Are you referring to the "Auto save Sessions logs" in "Terminal Options":
![image](https://user-images.githubusercontent.com/981546/56849406-2004b880-68f4-11e9-8cf8-64144d295cf3.png)

As far as I can see and if you set "<UUID>" or "<NAME>", it will recreate a new file for each new connection so I'm not sure to correctly understand your point... Can you elaborate a bit more ?

**Comment by gfrenoy** [comment]
Closed due to inactivity.  Feel free to re-open if you have new information to share.
