### ISSUE TITLE
SSH authenticity of host issue

### ISSUE THREAD

**Issue by Mjolinir** [asbru-cm/asbru-cm#145]
**Describe the bug**
When ssh connection is attempted to host for first time, you receive the normal warning about the authenticity of the host. You are prompted to enter "yes/no/fingerprint" at the prompt to accept the key, but nothing you enter makes any difference here. 

**To Reproduce**
1. SSH to new host
2. Wait for the warning with the prompt "Are you sure you want to continue connecting (yes/no/[fingerprint])? yes/no
Please type 'yes', 'no' or the fingerprint: "
3. Nothing happens

**Expected behavior**
If you type "yes", the SSH connection should continue

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version: Current

**Additional context**
If I SSH to the host in a separate terminal window first, the expected behavior will then occur. Its only when connecting to a new host via Asbru for the first time will this happen.

**Comment by gfrenoy** [comment]
Did you try the option "Auto-accept (...) SSH keys" ?

![image](https://user-images.githubusercontent.com/981546/57311725-7f30ad00-70ec-11e9-82ba-dd5dba2c8799.png)

**Comment by Mjolinir** [comment]
Yes sir, this option is indeed checked

**Comment by Mjolinir** [comment]
I just realized I did make a mistake in my bug report. The O/S is Arch Linux, not Fedora. Im not sure if it makes any real difference, but it does work fine on a Fedora box, but not on Arch Linux.

**Comment by B1tl0rd** [comment]
Hello everyone, I use Archlinux, and I have the same problem,

**Comment by gfrenoy** [comment]
Ok so my best bet at this point is that the string that is displayed has been slightly changed in Archlinux so you will need to change the regular expression accordingly:

![image](https://user-images.githubusercontent.com/981546/57336657-f71bc900-7126-11e9-9beb-104aa8fcf4e4.png)

The string you mention in your initial report is matching the default regexp ; can you double check:

- what is the exact message that is displayed ?
- what is the exact regexp that you have in your configuration ?

**Comment by B1tl0rd** [comment]
![pac](https://user-images.githubusercontent.com/12401985/57337585-fddf1780-70f7-11e9-8784-5be441f498f8.png)
![pac2](https://user-images.githubusercontent.com/12401985/57337592-059ebc00-70f8-11e9-9a92-81f7c8741cee.png)

**Comment by gfrenoy** [comment]
Thanks :)  But, mmm, what I see here is:

![image](https://user-images.githubusercontent.com/981546/57337706-c178df00-712a-11e9-84e1-b66f125fef94.png)

So there is a different in the displayed message but I don't understand why the regexp is not matching what you see.

Another thing I don't understand is the "yes/no" message that is written after the question.  Any idea from where it comes ?

The problem I have here is that I don't have a Archlinux machine to test :-/

**Comment by Mjolinir** [comment]
I am not sure what is causing the 2nd "yes/no" question, but I did find something that seems to match: https://github.com/openssh/openssh-portable/blob/master/sshconnect.c

Is that somehow incorporated?
I see the same output as B1tl0rd:

`The authenticity of host '[hostname.domain.com]:3822 ([10.xx.xx.xx]:3822)' can't be established.
ECDSA key fingerprint is SHA256:lyoKO81TCXQHaffMaIUWNR6ZJZFKJS6q0WnxM89dJV0.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes/no
Please type 'yes', 'no' or the fingerprint: 
 <-= DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Thu May  9 13:12:50 2019)
`

**Comment by gfrenoy** [comment]
Mmm, I really need a similar host to reproduce the issue :-/

Can someone give me some instructions on how to get Ásbrú working on Archlinux ?

I downloaded the image from the section "HTTP Direct Downloads" on https://www.archlinux.org/download/ but when I start the machine, I only get a command prompt and did not find instructions to install Gnome and Ásbrú ... 
[sorry, I'm a Ubuntu user...]

**Comment by Mjolinir** [comment]
Sure, it is available in the AUR. You just need an AUR helper (
https://wiki.archlinux.org/index.php/AUR_helpers), I recommend "yay", but
you can use any youd like. Then you install it with:

yay -S asbru-cm-git

That should do it!

**Comment by B1tl0rd** [comment]
> Mmm, I really need a similar host to reproduce the issue :-/
> 
> Can someone give me some instructions on how to get Ásbrú working on Archlinux ?
> 
> I downloaded the image from the section "HTTP Direct Downloads" on https://www.archlinux.org/download/ but when I start the machine, I only get a command prompt and did not find instructions to install Gnome and Ásbrú ...
> [sorry, I'm a Ubuntu user...]

Hi.. 
https://www.fosslinux.com/7117/how-to-install-arch-linux-complete-guide.htm

**Comment by gfrenoy** [comment]
What I typically do is downloading some "live CD" of a distribution and from there, execute a few instructions to get Ásbrú working on that distribution.  Said differently and even if this would be very interesting, I really don't want to spend time building a machine from scratch...

So I downloaded the Manjaro distrib ; I think it's the closer and more mature one.

After the live distrib has started, I did:

```
sudo pacman -Sy yay binutils make gcc pkg-config fakeroot patch gtk-engine-murrine openssh
yay -S asbru-cm-git
```

And now I can reproduce the issue :)

And I also now understand what is wrong with the regular expression !  It is trying to capture the yes or no options but is confused by the third option and picked "yes/no" as the first option and "[fingerprint]" as the second one.

Can you try to change it to the following:

```
^.+ontinue connecting \(([^/]+)\/([^/]+)(?:[^)])?\)\?\s*$
```

It is working for me ;-p

**Comment by B1tl0rd** [comment]
HI,
The authenticity of host 'ip (ip)' can't be established.
ECDSA key fingerprint is SHA256:##########################.
Are you sure you want to continue connecting (yes/no/[fingerprint])?

**Comment by gfrenoy** [comment]
Looks like I did not retyped it correctly ; sorry about that, the copy/paste from the VM did not work.  I forgot a "+", it should be:

```
^.+ontinue connecting \(([^/]+)\/([^/]+)(?:[^)]+)?\)\?\s*$
```

I saved the regular expression here so you can give it try on your own: https://regexr.com/4dq50

**Comment by B1tl0rd** [comment]
thank you, it worked

**Comment by Mjolinir** [comment]
This works for me as well, thank you an nice work :)

**Comment by gessel** [comment]
Just for anyone else on ubuntu 21.10 - I had the same issue with 6.3.2 and the same @gfrenoy's regexp cleared it right up. Thanks.
