### ISSUE TITLE
Is there a posibility to migrate the App to Mac/Windows ?

### ISSUE THREAD

**Issue by JairoAlonso25** [asbru-cm/asbru-cm#146]
Right now I use Asbru as my default connection manager. I work on Windows and Mac as well, I would like to know if there is a possibility to migrate the software to use in Mac or Windows since I use those OS in my daily work. I know is GTK based, but afaik, there are ports of many GTK apps in Windows and Mac...

**Comment by gfrenoy** [comment]
Well, there is probably a way but I doubt you can find someone that has a clue about how to do this...Especially for the legacy "VTE" component.

My suggestion would be to work on the Gtk3 version first ; then think about possible ports...

**Comment by gfrenoy** [comment]
Added a note in our [FAQ](https://github.com/asbru-cm/asbru-cm/wiki/Frequently-Asked-Questions).
