### ISSUE TITLE
Request - Link binary to something in $PATH

### ISSUE THREAD

**Issue by clickwir** [asbru-cm/asbru-cm#15]
Just installed Asbru (looks great so far!) but I had to go do a bit of searching to find it.

Once I found it I made a 'ln' (link) to it in one of the dirs in my $PATH. I think I used /usr/bin.

It would help people run it if this link (or a properly located one) would be made at install time.

**Comment by KlaasT** [comment]
I will have a look at that issue and debianize the package a bit more.

**Comment by gfrenoy** [comment]
With RC4, "asbru" is now in the standard $PATH.
