### ISSUE TITLE
gpg-agent or command prepend

### ISSUE THREAD

**Issue by EoleDev** [asbru-cm/asbru-cm#150]
Hi, 
Thanks for you work !
I am trying to use asbru-cm with a pkey loaded on a yubikey.
When I use a ssh client on command line, it loads the keys from the gpg-agent.
To find it, an exported variable is configured : SSH_AUTH_SOCK.

Is there a way to use the gpg-agent with asbru-cm, or is there a way to prepend a command
for all the ssh connections configured.
Right now it works if I prepend the line : "export SSH_AUTH_SOCK=..." on a connection,
but I would be glad if I could configure it once and not on each connection.

Thank you for your time,

**Comment by beliys** [comment]
`ssh` has an option of `IdentityAgent` for this - https://man.openbsd.org/ssh_config#IdentityAgent
You can add it to SSH Options - Advanced Options. But it also makes sense to add an option for the context menu in section `I`, when you click with the right mouse button on the option field, in the same way as for `IdentityFile`.
I have not yet looked at how we can correctly add this option to the context menu, but this does not prevent us from specifying this option manually.

**Comment by EoleDev** [comment]
Thank you for your quick answer.
I tried to use the IdentityAgent Option in the Advanced Options menu without success.
I wrote it in the option field, because as you said this option doesn't exists in the context menu, but it didn't work.

If I set this option in my ~/.ssh/config, it works when using a generic command like "ssh x.x.x.x" in asbru.
It seems my ssh config is not read when the connection is on SSH mode.

As I would prefer to configure it once and for all and not on each connection,
how may I use my ssh/config with asbru-cm ?

**Comment by gfrenoy** [comment]
beliys' suggestion should work...

But be careful, if you set "Authentication" to "User/Password" in "Connection", Ásbrú will add ```-o "PreferredAuthentications=password,keyboard-interactive"``` to the command and that will make ```IndetityAgent``` useless.  You have to specify "Private key".

It might be the same issue with ```~/.ssh/config```, if PreferredAuthentications is set, it overrides anything else.

You can check the actual command line that is started on "Connection" > "Advanced Parameters" > "Get Command line".

(note: and I'll add ```IdentityAgent``` to the available options)

**Comment by EoleDev** [comment]
Thank you for your precise answer.
All is working well now!

I used the IdentityAgent in my ssh config (to remove the need to configure it on each asbru connection).
When using the "Private Key" on each connection, it works well!
Thank you!
