### ISSUE TITLE
ssh always issue with setting local 

### ISSUE THREAD

**Issue by killmasta93** [asbru-cm/asbru-cm#151]
**Describe the bug**
Hi, I was wondering if someone could shed some light on the part of the ssh on asbru im always getting this 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_MEASUREMENT = "es_CO.UTF-8",
	LC_PAPER = "es_CO.UTF-8",
	LC_MONETARY = "es_CO.UTF-8",
	LC_NAME = "es_CO.UTF-8",
	LC_ADDRESS = "es_CO.UTF-8",
	LC_NUMERIC = "es_CO.UTF-8",
	LC_TELEPHONE = "es_CO.UTF-8",
	LC_IDENTIFICATION = "es_CO.UTF-8",
	LC_TIME = "es_CO.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").

**To Reproduce**
open ssh on asbru and run any command

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 
 - Version 18.04

**Additional context**

**Comment by gfrenoy** [comment]
What I typically do is to comment out the following line in ```/etc/ssh/sshd_config```
```
AcceptEnv LANG LC_*
```

See https://stackoverflow.com/a/2510548 for more details and other options (if you cannot change ssh configuration).

Hope this helps.

**Comment by killmasta93** [comment]
Thanks for the reply, the only issue is that i dont have sshd_config but only ssh_config
root@ubuntu-pc:~# ls /etc/ssh/
moduli  ssh_config

**Comment by gfrenoy** [comment]
@killmasta93 this is a setting on the server side.

**Comment by XANi** [comment]
Simplest fix is to install `locales-all` package (on Debian), then you will always have required one. Also that's mostly Perl issue, not asbru issue

**Comment by killmasta93** [comment]
@gfrenoy thanks for the reply, on the server side i dont have that either, this only happens on ubuntu as if ssh on putty on a windows machine no issue. 
@XANi i ran apt-get install locales-all
would i need to reboot or run something else?

**Comment by gfrenoy** [comment]
> on the server side i dont have that either

According to your actual server distribution, It might be located at a different place but there *must* be one otherwise it is not a SSH server...

Really, it's not a specific Ásbrú issue, read https://stackoverflow.com/a/2510548 again ; there are many options to fix or workaround the issue.
