### ISSUE TITLE
Paste current connection password button

### ISSUE THREAD

**Issue by doman18** [asbru-cm/asbru-cm#152]
Hi all
Ive just begun to use Asbru. I was looking for something similar to mobaXterm for linux.

The main thing which annoys me is copying and pasting password for SUDO commands. I would love to have button under right click (or some key shortcut) which would paste the current connection password. So far i made some custom commands but i would have to do such for every connection. Ive seen some scripts and looked for some current session variables to use but so far i didnt see any. Is there any workarround? If not i would love to have such feature.

**Comment by gfrenoy** [comment]
Interesting idea, thanks for your suggestion.  I just made a change that adds a menu entry "Paste Connection Password":

![image](https://user-images.githubusercontent.com/981546/61459804-d4e7c800-a96d-11e9-9596-510cd9125ed3.png)

This option will only be shown if there is actually a password that is defined.

**Comment by doman18** [comment]
Im sorry for such a late reply. Im very busy man :). Many thanks for taking this topic in such fast and serious manner :) As soon as have some tiny bit of spare time ill download snapshot version. So far im using asbruu very extensively :)

**Comment by gfrenoy** [comment]
Let's consider this closed for now.  Feel free to open it again later after you find time to test it.
