### ISSUE TITLE
Size of embedded xfreerdp

### ISSUE THREAD

**Issue by figue** [asbru-cm/asbru-cm#153]
**Describe the bug**
Size of embedded windows are not always equal

**To Reproduce**
1. Open a xfreerdp session
2. While your focus is xfreerdp session, open a second xfreerdp session
3. See error. This time embedded size seems bigger and you see vertical scroll or the desktop is trimmed

**Expected behavior**
Every new session should have the same virtual size

**Workaround**
Instead of open new session while your tab focused is a xfreerdp session, go back to info tab, then new tab will have the correct virtual size.

**Screenshots**
First tab:
![Selección_155](https://user-images.githubusercontent.com/3238330/61468473-a4a82580-a97d-11e9-9a5d-2db9c0802521.png)
Second tab:
![Selección_156](https://user-images.githubusercontent.com/3238330/61468481-a7a31600-a97d-11e9-97ba-b74d1ec893a4.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version: latest git

**Additional context**
I played adding _/dynamic-resolution_ before _/size:$$CFG{'tmp'}{'width'}x$$CFG{'tmp'}{'height'}_ in lib/pac_conn and that solves an old issue with bad size in Windows 2012. The old workaround was adding these lines:
https://github.com/asbru-cm/asbru-cm/blob/8ff2cac959484da6d8660f77cfe0a0b92f54183e/lib/pac_conn#L947-L948
Now a quick workaround with Windows 2012 is to change above with:
```
$$CFG{'tmp'}{'width'}-=3;
$$CFG{'tmp'}{'height'}-=21;
```
Those values could be different according to GTK theme. 3 and 21 works perfect in my current setup.

**Note 2**
The screenshots are with dynamic resolution enabled, so there isn't vertical scroll bar, you can see that bottom desktop area is hidden

**Comment by gfrenoy** [comment]
Thanks for your feedback Joan.  Do you think you can submit a PR for that ?

**Comment by figue** [comment]
I updated the last part of my comment, because I see a new workaround... If that's ok, I can submit a PR.

**Comment by gfrenoy** [comment]
Is it really the worth to change a hardcoded value by another one?  I mean: as you said, values could be different according to someone else's setup so we should either find a generic way to manage this or to give the opportunity to everyone to configure it.  Don't you think ?

**Comment by figue** [comment]
Yes, it is a bad idea. Adding /dynamic-resolution works partially, but it's clear that Asbru doesn't calculate the embedded area accurately. If that area was calculated correctly, hardcoded values could be removed.

**Comment by gfrenoy** [comment]
So we need to find a way to query the width / height of the inner window before calling xfreerdp ; do I get it correctly ?

I found out that there are more "hard coded values" in [PACTerminal.pm line 308-309](https://github.com/asbru-cm/asbru-cm/blob/8ff2cac959484da6d8660f77cfe0a0b92f54183e/lib/PACTerminal.pm#L308):
```
$$self{_CFG}{'tmp'}{'width'}	= $req -> width - 10;
$$self{_CFG}{'tmp'}{'height'}	= $req -> height - 85;
```

It's using "$$self{_NOTEBOOK}" (https://developer.gnome.org/gtk2/stable/GtkNotebook.html) ; we should probably get the current page and figure out what is the size of the inner window of that page.

Searched a bit but did not find anything really useful so far.

Any further help will be greatly appreciated.

**Comment by figue** [comment]
That's correct. If I get current size of xid with xwininfo (part of xorg-xwininfo) then hardcode those values in /size, the window is perfectly embedded. So the idea should be get width and height from parent window $$CFG{'tmp'}{'xid'} then insert in /size

**Comment by gfrenoy** [comment]
Interesting :)  Apparently, [xwininfo](https://github.com/idunham/xutils/blob/master/xwininfo.c#L408) uses XGetGeometry to find out this information.  But this looks to be a very low level X function ... I did not find anything similar in the perl packages we are currently using.

**Comment by figue** [comment]
Could we use X11::GuiTest as suggested here?

https://stackoverflow.com/questions/26085616/perl-getting-the-geometry-of-a-window-with-x11-windowid

**Comment by figue** [comment]
Maybe this patch can be used:

[fix-embedded-rdp-size.patch.gz](https://github.com/asbru-cm/asbru-cm/files/3416860/fix-embedded-rdp-size.patch.gz)

Two things:
- first I had to add a new "if" in case you select EMBED tab for freerdp, then I added /dynamic-resolution and the new calculated size using X11::GUITest.
- second I had to decrease 3 pixels for rdesktop width, because even with the right size, embed tab has scroll bars. Could be something related to rdesktop itself, but I don't know.

If this method is accepted, I can make a PR.

**Comment by gfrenoy** [comment]
Eeh, pretty cool !  It worked like a charm on my environment.  Thanks a lot.

Of course I needed to manually install the package ```libx11-guitest-perl``` so we'll need to add this to our dependencies (this is located in our other repo --> https://github.com/asbru-cm/packages/tree/master/asbru-cm).  We'll also need to check if this package is also available on RPM-based distros.  At least it looks to be available on Fedora --> https://rpms.remirepo.net/rpmphp/zoom.php?rpm=perl-X11-GUITest

Can we have a fallback if the package is not available on some distros ?

May I also suggest to use on tabs for indentation ?  In your code you have both tabs and spaces...

In any case, feel free to submit any PR ... Won't have much time to integrate everything this week but I will eventually do it !

Thanks.

**Comment by figue** [comment]
It's ok, make yourself the patch. I was editing with vim at work and maybe I don't have set tabs for indentation.

On Archllinux based distros package is named perl-x11-guitest and it's in AUR (the free user repository).

For fallback, what do you mean?

**Comment by gfrenoy** [comment]
> For fallback, what do you mean?

If the GuiTest package is not available for some reason ; can we still make it working as it is today ?

**Comment by figue** [comment]
Ok, this was a bit more difficult for me :)

But, maybe we can use something like this:
[fix-embedded-rdp-size2.patch.gz](https://github.com/asbru-cm/asbru-cm/files/3422562/fix-embedded-rdp-size2.patch.gz)

I had to understand first why Perl gives this error when you eval the module load:
"Too late to run INIT block at /usr/lib/perl5/5.30/vendor_perl/X11/GUITest.pm line 783."
So I had to insert eval inside a BEGIN... I don't know if it's the right way, but it seems to be working fine in my laptop.

I'm a "noob" in Perl programming, please be patient if I made a big "no sense"...

**Comment by gfrenoy** [comment]
Please, you're too humble !  This is really great job and you made my day : that "BEGIN" trick is something I was looking for ... (no I'm not a Perl programmer either).

If we want to go to the last bit of details of this, I guess we just need to expose the two arbitrary variables in the options of the RDP connection ; don't we ?

But as it is today, this is already a major improvement ; I made some tests with various sizes and it's always perfect !

Will you submit a PR ?  (so you can get the credits for that)

I'll need to change the build package accordingly so be patient.

**Comment by figue** [comment]
I can make the PR. Adding as options will be a really improvement, but I think don't have time and the knowledge to do that. Probably we have to patch more than 1 file... But with some help, it could be done.

**Comment by gfrenoy** [comment]
Sure, you're not alone :)

I would start by looking at PACMethod_xfreerdp.pm and the spWidth & spHeight parameters ; I would believe it will be very similar:
![image](https://user-images.githubusercontent.com/981546/61746675-876bc080-ad9c-11e9-8828-8b745362ccd6.png)

But if I get it correctly, all those options are command line options of xfreerdp ; not sure it is applicable in our case.

Another remark : we cannot ask someone to change the code to change the variable (since it will not survive an upgrade) but it's probably acceptable to change a configuration file "manually" if we cannot or don't want to expose these parameters in the GUI.

**Comment by figue** [comment]
Nice. About your remark: I see and I'm agree. I can make a PR without variables $embed_offset_width and $embed_offset_height. In the future we should add in GUI preferences in case someone doesn't have X11::GUITest and want to fit the tab.

**Comment by figue** [comment]
PR #155 opened with a little surprise

**Comment by gfrenoy** [comment]
Hi Joan.  Thanks a lot for the great patch !  Tested it on my environment and it works perfectly ; with or without X11::GUITest, really a great job :-)

Will you sign the CLA so that I can merge the PR ?

**Comment by figue** [comment]
CLA signed... I forgot :P

**Comment by gfrenoy** [comment]
Wonderful !  The commit is merged and will be available in the next builds...
