### ISSUE TITLE
Feature Request - Option to send Carriage Returns in Macros

### ISSUE THREAD

**Issue by leonard4** [asbru-cm/asbru-cm#154]
Would be nice if you could send carriage returns in macros to automate them. Older term programs used ^M or `<CR>` commands to do things like that. Using a serial connection on a VME bus using CU to do this.

**Comment by gfrenoy** [comment]
Great idea.

To make things easier for the one who may want to help on this, can you share an example and a few screenshots on how you see this ?

**Comment by leonard4** [comment]
I was thinking something real simple. Since you already have a format for <INTRO>, keep the same brackets and add in a handful of other options, like <CR> for Carriage Return, <LF> for Line Feed, <BELL> for a bell, things like that. Allow for multiple per macro as well, then you could run almost a script of commands from one macro.

![asbru_macro](https://user-images.githubusercontent.com/1154391/61885714-2b479000-aeb3-11e9-869d-76f25bf3044d.png)

![asbru_macro2](https://user-images.githubusercontent.com/1154391/61885722-2edb1700-aeb3-11e9-9d20-026cbbf5e227.png)

**Comment by gfrenoy** [comment]
Thanks for the additional information.  This looks clear to me :)

Did you notice the option "send <INTRO> at the end" ?  Did you try with this option checked ? 
 Actually, this will send a <CR> so maybe that it's good enough for what you want to do, isn't it ?

That being said, the request is still valid if you want to use <CR> in the middle of a command.

Another question: do we need to have an escape sequence, just in case we really want to have <CR> sent to the remote terminal ?

**Comment by gfrenoy** [comment]
@leonard4 Can you let us know if the "send INTRO at the end" option is not what you are looking for ?

**Comment by leonard4** [comment]
The send intro doesn't seem to send a CR, my terminal still wants a full " hit CR" to continue.

**Comment by gfrenoy** [comment]
What do you mean by a "full hit CR to continue" ?

When "send INTRO at the end" is checked, it appends a ```\n``` at the end of the given command.

What would expect instead of that character ?

**Comment by leonard4** [comment]
I'm not 100% on what it wants, but when I send a macro it says "HIT CR TO RUN AGAIN", so i assume its looking for a carriage return, when I click on the terminal and then press ENTER it runs like it should. When I use send  INTRO it returns down one line but doesn't simulate hitting ENTER so its acting like a newline which makes sense, \n is for newline, whereas \r is a carriage return so I think thats all we need?

**Comment by gfrenoy** [comment]
Ok so we do think it wants a "\r" instead of a "\n" ?

Just to validate this assumption l; can you try to change "\n" by "\r" or "\r\n" on the line that is sending the remote command ([L542 of pac_conn](https://github.com/asbru-cm/asbru-cm/blob/master/lib/pac_conn#L542) for the master) and see if it works for you ?
