### ISSUE TITLE
issue freezes computer

### ISSUE THREAD

**Issue by killmasta93** [asbru-cm/asbru-cm#156]
**Describe the bug**
sometimes if i close the RDP window or asbru freezes the computer

**To Reproduce**
1. Go to 'close the tab on xfreerdp'
2.freezes computer
3. have to reboot forcefully

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ubuntu ]
 - Version [18.04]

**Additional context**
asbru-cm.desktop[3570]: GLib-CRITICAL **: Source ID 9051 was not found when attempting to remove it at /opt/asbru/lib/PACTerminal.pm line 446.
 asbru-cm.desktop[3570]: GLib-CRITICAL **: Source ID 9051 was not found when attempting to remove it at /opt/asbru/lib/PACTerminal.pm line 1094.
 asbru-cm.desktop[3570]: *** unhandled exception in callback:
 asbru-cm.desktop[3570]: ***   Can't call method "get_active" on an undefined value at /opt/asbru/lib/PACTerminal.pm line 3215.
 asbru-cm.desktop[3570]: ***  ignoring at /opt/asbru/lib/PACMain.pm line 368.
 asbru-cm.desktop[3570]: Gdk-WARNING **: Couldn't match property type UTF8_STRING to STRING
 asbru-cm.desktop[3570]: Gdk-WARNING **: Couldn't match property type COMPOUND_TEXT to STRING

asbru-cm.desktop[3570]: GLib-CRITICAL **: Source ID 10301 was not found when attempting to remove it at /opt/asbru/lib/PACTerminal.pm line 1262.
 asbru-cm.desktop[3570]: GLib-CRITICAL **: Source ID 10301 was not found when attempting to remove it at /opt/asbru/lib/PACTerminal.pm line 1094.
 asbru-cm.desktop[3570]: Gdk-WARNING **: Couldn't match property type UTF8_STRING to STRING

**Comment by gfrenoy** [comment]
The current bug description does not give us enough details about the exact root cause of the computer freeze.  It is likely not related to Ásbrú.

**Comment by killmasta93** [comment]
Thank you for the reply, sorry for the being clear, this only happens on asbru on XFREERDP when i try to reconnect another tab to connect i start seeing the log
`asbru-cm.desktop[3570]: GLib-CRITICAL **: Source ID 9051 was not found when attempting to remove it at /opt/asbru/lib/PACTerminal.pm line 446.
asbru-cm.desktop[3570]: GLib-CRITICAL **: Source ID 9051 was not found when attempting to remove it at /opt/asbru/lib/PACTerminal.pm line 1094.
asbru-cm.desktop[3570]: *** unhandled exception in callback:
asbru-cm.desktop[3570]: *** Can't call method "get_active" on an undefined value at /opt/asbru/lib/PACTerminal.pm line 3215.
asbru-cm.desktop[3570]: *** ignoring at /opt/asbru/lib/PACMain.pm line 368.
asbru-cm.desktop[3570]: Gdk-WARNING **: Couldn't match property type UTF8_STRING to STRING
asbru-cm.desktop[3570]: Gdk-WARNING **: Couldn't match property type COMPOUND_TEXT to STRING

asbru-cm.desktop[3570]: GLib-CRITICAL **: Source ID 10301 was not found when attempting to remove it at /opt/asbru/lib/PACTerminal.pm line 1262.
asbru-cm.desktop[3570]: GLib-CRITICAL **: Source ID 10301 was not found when attempting to remove it at /opt/asbru/lib/PACTerminal.pm line 1094.
asbru-cm.desktop[3570]: Gdk-WARNING **: Couldn't match property type UTF8_STRING to STRING`
after that i have reboot the computer because it freezes completely
