### ISSUE TITLE
Add a free textbox to pass custom options in xfreerdp

### ISSUE THREAD

**Issue by figue** [asbru-cm/asbru-cm#158]
**Is your feature request related to a problem? Please describe.**
There are some options like /proxy, /gw etc that are necessary to some people but implement all xfreerdp options in Ásbrú is complicated. The idea is let the user do it with a free input text box.

**Describe the solution you'd like**
Add a free input text box in method xfreerdp.

**Describe alternatives you've considered**
Add more options to method, but window will be very large in the way that is implemented right now.

**Additional context**

![Selección_159](https://user-images.githubusercontent.com/3238330/62036251-beedc900-b1f1-11e9-8f9e-43b56fc8e33f.png)

I've already implemented that option, but I want to know first if it's an interesting feature for the project or not... I've spend several hours coding, had to rewrite some parts and I think is working fine, but before make a PR I want to discuss it here.

Also, I will need some testers because the rewrited section. Please comment if someone is interested and I'll share the patch here.

**Comment by gfrenoy** [comment]
I personally don't really use RDP connections (only for tests) so I cannot really validate the change thoroughfully but it certainly looks like a great addition !

Thanks a lot.

**Comment by figue** [comment]
It's OK Gaëtan, the idea comes from my need to connect to VDI through a gateway. In Remmina this is implemented:

![image](https://user-images.githubusercontent.com/3238330/62041045-12184980-b1fb-11e9-90b9-2def5e9af7e7.png)

In Ásbrú we can also add the parameters, but as it has a username/password fields maybe will be more complicated to code. In this case, you should to put credentials in clear text in "Other options" (which is not always a good idea or comfortable), but at least can be done:

![image](https://user-images.githubusercontent.com/3238330/62041590-50623880-b1fc-11e9-8ed3-da168e7738dc.png)

**Comment by figue** [comment]
PR #163

**Comment by gfrenoy** [comment]
Great !  Thanks a lot :)  So we can close this and #81 ? Do I get it correctly?

**Comment by figue** [comment]
Yes, you can close it
