### ISSUE TITLE
Relocate "Set keyboard focus" button to gain a piece of screen in embedded tabs

### ISSUE THREAD

**Issue by figue** [asbru-cm/asbru-cm#160]
**Is your feature request related to a problem? Please describe.**
Relocate "Set keyboard focus" button to gain a piece of screen in embedded tabs.

**Describe the solution you'd like**
Is already coded in this commit - GUI: down 'Set keyboard focus' button to bottombox to gain a piece of screen in embed tabs
https://github.com/figue/asbru-cm/commit/dbaff3e8b5ad4ed9d52ad6dcab9ef9a9bb2a9a97

**Describe alternatives you've considered**
Maybe all buttons could be placed in 1 bottom bar... With my relocate still would be 2

**Additional context**
![image](https://user-images.githubusercontent.com/3238330/62299805-efde3000-b475-11e9-8d75-a4ca7d09ec6d.png)

Please, give me your feedback. If it's ok you can merge my commit directly or I can make a PR.

Note: Can I can make a PR from 1 commit? Never tried...

Thanks!

**Comment by gfrenoy** [comment]
UI looks definitely better.

In your patch, I see you have added "if ( $$self{'EMBED'} ) {" so it means that the button will not be displayed at all in the non-embed mode ; is this intended ?

**Comment by figue** [comment]
Yes, I've followed the same logic like as before, in original code the button is inside an "else" that comes from "if ( ! $$self{'EMBED'}":

https://github.com/asbru-cm/asbru-cm/blob/master/lib/PACTerminal.pm#L541

**Comment by KlaasT** [comment]
> Note: Can I can make a PR from 1 commit? Never tried...

Sure you should be able to create a PR.

**Comment by figue** [comment]
> > Note: Can I can make a PR from 1 commit? Never tried...
> 
> Sure you should be able to create a PR.

Thanks. PR opened #162

**Comment by gfrenoy** [comment]
Merged with master branch.
