### ISSUE TITLE
How can I load a PuTTy (.ppk) private key into an ssh connection?

### ISSUE THREAD

**Issue by PyDataBlog** [asbru-cm/asbru-cm#161]
**Is your feature request related to a problem? Please describe.**
I have  a private key that was generated with PuTTy that I would like to load into connection manager. How can I set this up?

**Describe the solution you'd like**
A successful connection into a server using the PuTTy private key

**Comment by beliys** [comment]
Hi, you need to convert it.
https://superuser.com/a/232365

**Comment by KlaasT** [comment]
Thanks for the question and the answer already. I added this to our Tips & Tricks section for the future.

https://github.com/asbru-cm/asbru-cm/wiki/Tips-and-Tricks
