### ISSUE TITLE
Problem with ctrl key

### ISSUE THREAD

**Issue by mooky31** [asbru-cm/asbru-cm#164]
**Describe the bug**
I am using linux KVM console (virsh console) on debian 10.
It says "Escape character is ^]"
With putty, I used to leave the console with ctrl + $ (I have a french keyboard).
With Asbru, I can't find any key combination to leave the console.
Ctrl+$ just prints a $ sign.
I have to login another ssh and kill virsh, which is pretty annoying.
I tried to disable ctrl key binding, but that didn't help.

Is it a setting problem ? Or a bug ?
Or could anyone tell me the character sequence to leave the console ?

Thank you very much

**Desktop (please complete the following information):**
 - Ubuntu Bionic on windows 10 v1709
 - VcXsrv 1.20.1.4
 - Asbru 5.2.0

**Comment by gfrenoy** [comment]
Did you try ```CTRL+AltGr+$``` ?

**Comment by mooky31** [comment]
I just tried ctrl left+alt+$, ctrl left+altgr+$, ctrl right+alt+$, ctrl right+altgr+$.
None of them work :(

**Comment by mooky31** [comment]
I finally succeded exiting the console with ctrl+altgr+] (french keyboard always).
Thanks for the altgr suggestion, case closed.
