### ISSUE TITLE
Open duplicated connection just after current active tab

### ISSUE THREAD

**Issue by N-Mi** [asbru-cm/asbru-cm#165]
**Is your feature request related to a problem? Please describe.**

When working with many sessions opened, I very often use the "Duplicate connection" feature to open a new connection to the same server. The problem is the new connection tab is added at the end of the tab bar, and I need to manually move it so that it's placed right aside previous tabs from the same server.

Before duplicate :
![shot-2019-08-13_16-11-31](https://user-images.githubusercontent.com/3135085/62949559-b0ed9a00-bde6-11e9-909d-e84322378234.png)

After duplicate (red arrow shows new duplicated connection) :
![shot-2019-08-13_16-11-55](https://user-images.githubusercontent.com/3135085/62949566-b64ae480-bde6-11e9-9251-2744de88d252.png)

**Describe the solution you'd like**

I would like an option so that a new connection or a duplicate connection tab is opened just after current active tab.

In previous screenshot, here would be the new duplicated connection :
![shot-2019-08-13_16-12-18](https://user-images.githubusercontent.com/3135085/62949729-06c24200-bde7-11e9-8b6b-65626c734aff.png)

**Describe alternatives you've considered**
Another way would be an option to automatically group tabs opened for the same server.

**Additional context**
Nope.

**Comment by gfrenoy** [comment]
It is something I'm doing quite often myself !  I would indeed expect that the tab is created right after the one that is currently selected.

Not sure how to do this, I'll have a look.

Thanks for the suggestion.

**Comment by gfrenoy** [comment]
I think I found a way to do this and it is really helpful (at least for me) !

I'll make the commit in a minute.  It will be available within an hour in the snapshot build ... Let us know if it works for you.

Thanks again for the suggestion.

**Comment by N-Mi** [comment]
Thanks @gfrenoy , I just installed last git and it works exactly as expected !
