### ISSUE TITLE
Installation on Linux Mint 19.2 Tina does not work

### ISSUE THREAD

**Issue by HansPeterMauderer** [asbru-cm/asbru-cm#166]
**Describe the bug**
Trying the installation script stops with unknown OS Type.

**To Reproduce**
Follow Wiki how to install on Linux Mint

**Desktop (please complete the following information):**
 - OS: [e.g. LINUX MINT Tina
 - Version 19.2

**Additional context**

**Comment by HansPeterMauderer** [comment]
Trying the installation script stops with unknown OS Type.
Linux Mint 19.2 was released on 02.08.2019, it seems only older versions until 19.1 are supported.

Is there any option to get it working ?

**Comment by gfrenoy** [comment]
Mint 19.2 is not yet support by packagecloud.io (see https://packagecloud.io/docs#anchor-linuxmint).  I'll send them an email...

**Comment by gfrenoy** [comment]
The new tag has been added by [packagecloud.io](https://packagecloud.io/) (thanks for their prompt answer, btw!) and the packages have been built and available in the snapshot version (see https://github.com/asbru-cm/asbru-cm/wiki/installation-on-mint#snapshot-release).

Let us know if it works for you.
