### ISSUE TITLE
Be able to drag and drop connections into groups

### ISSUE THREAD

**Issue by clickwir** [asbru-cm/asbru-cm#167]
**Is your feature request related to a problem? Please describe.**
I already have many connections created, but the only way to get them into a Group seems to be to recreated them under a Group. Ones that are already made don't seem to be able to be moved to a Group.

**Describe the solution you'd like**
I'd like to be able to drag and drop them. Or, if renaming them put them in the group that would be ok also. Such as <CONNECTION> renamed to <GROUP> - <CONNECTION>.

**Describe alternatives you've considered**
Right now the only way I know how to get anything into a group is to create it after the group is already made.

**Additional context**

**Comment by merikz** [comment]
@clickwir , for info: It is possible to cut+paste a connection into an existing group, but it would of course be nice if drag+drop also worked.

**Comment by dpcinc** [comment]
+1 from me on this one

**Comment by mimmus** [comment]
First day of serious test, I'm adding +1 to most important features missing in my opinion.

**Comment by gfrenoy** [comment]
Just pushed a change is supposed to implement that request.

What basically happens behind the scene is a "cut / paste" between the drag source and drag destination.

It is now available on the [loki branch](https://docs.asbru-cm.net/General/Installation/) and here is how it looks:

![asbru-drag-and-drop-demo](https://user-images.githubusercontent.com/981546/83361727-837cd780-a38b-11ea-839a-6b09374bece0.gif)

Please consider this as experimental and keep a safe copy of your production configuration file before testing it.

Any comments or suggestions are welcome !
