### ISSUE TITLE
Cannot interact with multiple selections in Connection list

### ISSUE THREAD

**Issue by clickwir** [asbru-cm/asbru-cm#168]
**Describe the bug**
Multi selections in Connections list become deselected.

**To Reproduce**
1. Highlight multiple connections. Either via CTRL+click or SHIFT+click
2. Right click on any of the highlighted ones.
3. They all get deselected, except for the one you right clicked on.

**Expected behavior**
I'd expect to be able to highlight multiple connections and use some menu items that could apply to more than 1 connection at a time. Such as the "Export SELECTED Connections...", "Start", "Delete".

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04
 - Version: Asbru CM 5.0

**Comment by hanspr** [comment]
@KlaasT 

This should be closed

**Comment by KlaasT** [comment]
Close #168

**Comment by KlaasT** [comment]
Closed #168
