### ISSUE TITLE
Right mouse click on tab title stop working

### ISSUE THREAD

**Issue by figue** [asbru-cm/asbru-cm#169]
**Describe the bug**
Right click on embedded tab title stop working

**To Reproduce**
1. Open some tabs
2. Open a RDP tab but close it before connection is established
3. Then try to right click on any tab

**Expected behavior**
The menu should appear as always

**Additional context**
Perl errors:
```
*** unhandled exception in callback:
***   undef is not of type Gtk2::Widget at /DATA/apps/asbru-cm/lib/PACTerminal.pm line 2239.
***  ignoring at /DATA/apps/asbru-cm/lib/PACMain.pm line 368.
```

**Comment by gfrenoy** [comment]
Sorry....I cannot reproduce this on my side :-/

Can you confirm the exact version you're working with so that I can identify what is line 2239 ?
Or check if you still have the same issue with the latest snapshot (I'm using for testing...).

Thanks.

**Comment by hrmzaqa** [comment]
I've been having this issue for some time. It has to be connected to configuration. As it stoped working on my PAC manager. Then I got new laptop installed fresh Fedora 29. Installed Asbru Imported the configuration and no right click again. When I Reset to Default it start to show the right click menu again.

**Comment by gfrenoy** [comment]
Interesting.

Can you maybe isolate which connection entry in the configuration file is causing this issue ?

**Comment by figue** [comment]
Sorry for the late response. Involved line is this:
https://github.com/asbru-cm/asbru-cm/blob/fc27df658f8d8cc0d65f694859bb474ed78cd261/lib/PACTerminal.pm#L2240
It happens when you close a RDP tab. Then right click stop showing the popup.

**Comment by gfrenoy** [comment]
@figue Do you still have the same issue on the gtk3 branch ?  Can we consider this fixed ?

**Comment by figue** [comment]
Seems fixed now! Good job @hanspr
