### ISSUE TITLE
Change term emulation

### ISSUE THREAD

**Issue by digitecnodata** [asbru-cm/asbru-cm#170]
**Describe the bug**
I use asbru on ubuntu 18.04 LTE
If I change the term emulation in vt100 or vt220 strange characters appear on video and the session result hang like the image below.
![asbru-screenshot](https://user-images.githubusercontent.com/54400801/63693239-d41b3f00-c813-11e9-825c-c57412450d06.png)

My purpose is to have all text in black and not with directory in blue color or executable files in green.
Is there a way to do this?
Thanks

**To Reproduce**
1. Go to 'preferences'
2. Select 'Terminal Options'
3. Select 'Advanced'
3. In Term Emulation change the value from xterm to vt100
3. See error

**Expected behavior**
To have all character in black

**Screenshots**
![asbru-screenshot](https://user-images.githubusercontent.com/54400801/63694087-f0b87680-c815-11e9-8f8c-1858ac24dcd9.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.04 LTE]

**Additional context**

**Comment by gfrenoy** [comment]
Changing the term capability will indeed change the way characters are handled so what you describe seems to be as designed.

To turn off coloring, this has to be done on the remote server, I would believe.  Try ```ls --color=never``` as an example (and check this article maybe : https://unix.stackexchange.com/questions/107371/how-to-turn-off-color-with-ls).
