### ISSUE TITLE
Highlight search results in terminal

### ISSUE THREAD

**Issue by jurinva** [asbru-cm/asbru-cm#172]
kde konsole have that feature like in picture
![konsole](https://user-images.githubusercontent.com/11086186/64068992-5e670700-cc49-11e9-87c5-3a4e58d3df74.jpg)
standart "interactive search" in asbru not comfortable

**Comment by gfrenoy** [comment]
Would be nice indeed but way too complicated to do with the current Gtk2 (Vte) version we have now.

Let's close this for now ; I marked this entry with a new label "Gtk3" so that we can have another look at this if we ever have a Gtk3 in the future.
