### ISSUE TITLE
package not available for Fedora 30

### ISSUE THREAD

**Issue by bitchecker** [asbru-cm/asbru-cm#175]
**Describe the bug**
On Fedora 30, no `asbru-cm` package is available after repository installation procedure.

**To Reproduce**
1. follow the installation procedure
2. no packages was founds

**Expected behavior**
Install main package and related deps

**Screenshots**
[terminal output](https://ibb.co/VVLX5Mb)
[packagecloud search](https://ibb.co/6m8xzP8)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 30

**Additional context**
On packagecloud, packages are available on Fedora 29 and older.

Another tips, the repo file can be parameterized for better flexibility

**Comment by gfrenoy** [comment]
Well, it's probably time to make another "official" release.  5.2.0 is now 5 months old.

F30 should work with the snapshot packages (see https://github.com/asbru-cm/asbru-cm/wiki/installation-on-fedora#snapshot-release).

**Comment by bitchecker** [comment]
empty [page](https://packagecloud.io/asbru-cm/snapshots/fedora/30/x86_64)

**Comment by gfrenoy** [comment]
Check this --> https://packagecloud.io/app/asbru-cm/snapshots/search?dist=fedora%2F30

If I remember it correctly, I tested this on F30 with the snapshot version (as stated [here](https://github.com/asbru-cm/asbru-cm/wiki/installation-on-fedora#snapshot-release)) and it worked...

**Comment by bitchecker** [comment]
ok, thanks...i'll see repositories status

sorry for delay in reply...
