### ISSUE TITLE
VNC options empty: Can't call method "_buildGUI" on an undefined value

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#178]
1. Click on ⚡ ("Quick Connect").

2. Choose "Method: VNC"

3. A warning popup appears:
```
No 'vncviewer' binary found.
To use this option, please, install any of:
'xtightvncviewer' or 'tigervnc'
'tigervnc' is preferred, since it allows embedding it's window into PAC
```

4. Notice typo: "it's" should be "its".

5. Close this dialog

6. This is printed:
```
*** unhandled exception in callback:
***   Can't call method "_buildGUI" on an undefined value at .../asbru-cm/lib/edit/PACMethod.pm line 132.
***  ignoring at .../asbru-cm/lib/PACMain.pm line 368.
```

7. Switch to "'VNC' Options" on the left.

8. Notice that the main area says: "'VNC command line options:" and then it's empty, no config option is presented.

I'm not sure if it works as expected if I have VNC installed, but other connecion types that I don't have installed either (e.g. rdesktop) proceed without an error message, and present their GUI options.

This is with current master (gtk2).

**Comment by gfrenoy** [comment]
For all other methods, the option panel is indeed loaded ; even if the underlying tool is not installed.

For VNC, David did more tests to check which VNC viewer was installed and if none was available, did not load any.  I changed this to always load the default VNC panel.

Thanks for the report ;-)
