### ISSUE TITLE
Readonly mode doesn't work

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#181]
`asbru-cm --help` (and the man page) says `--readonly : start in read only mode (no config changes allowed)`

`asbru-cm --readonly` allows to create new connections and edit existing ones just like without this command line flag.

In `PACMain.pm` it seems that the `--readonly` command line flag is only checked if another instance is already running.

This is with current master (gtk2).

**Comment by gfrenoy** [comment]
The test was indeed strangely located.  I changed it in both versions.
