### ISSUE TITLE
Migrate config files

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#182]
I think the config files should be changed from `~/.config/pac/pac.*` to `~/.config/asbru/asbru.*` or similar.

Probably with a one-shot automatic migration at startup if `~/.config/pac` exists and `~/.config/asbru` does not exist.

**Comment by gfrenoy** [comment]
Looked like a quite risky one which does not really bring anything new.  But yes, why not.

**Comment by hanspr** [comment]
I will leave this note here for future reference when the migration takes place:

I created in asbru-cm a function "config_migration" and created a global access to the configuration directory.

As far as I can see, the migration process has to be as follows:

* set $ENV{"ASBRU_CFG"} = "$ENV{'HOME'}/.config/asbru";
* set our $CFG_DIR_OLD    = "$ENV{'HOME'}/.config/pac";
* sub config_migration
  * `if (!-d $old_dir) {return 0;}`
  * `mv .config/pac .config/asbru`
  * `rm -f .config/pac.nfreeze`
  * Open pac.yml
    * for each line =~ s|/pac|/asbru|g;
    * save new pac.yml
  * [optional ?] Open asbru-cm and change `$CFG_DIR_OLD="$ENV{'HOME'}/.config/pac";`
    to `$CFG_DIR_OLD = "";`

**Comment by gfrenoy** [comment]
Shouldn't we copy ```.config/pac``` to ```.config/asbru``` instead of renaming ?

I mean: this would be a kind of "backup" and fail-safe solution for anyone who would like to use a legacy version ?

Additionally, if we screw up in the migration script ; at least we can just delete ```.config/asbru```, upgrade Ásbrú and proceed with the migration again.

**Comment by hanspr** [comment]
Sure

**Comment by gfrenoy** [comment]
Ready in loki
