### ISSUE TITLE
Reports two more nodes

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#183]
Remove all the configs and then start up Ásbrú. The main page says "Total PAC Nodes: 2".

As I keep adding connections (toplevel or within group), and then click on "AVAILABLE CONNECTIONS", this number always seems to be 2 more than desired.

**Comment by gfrenoy** [comment]
It was counting the root node and the hidden "local shell"...

**Comment by egmontkob** [comment]
> and the hidden "local shell"

This possibility didn't occur to me.

Thinking further along this line:

With this change, local shell's usage no longer counts towards the statistics (e.g. total time connected). Interestingly, with the gtk2 version, it was counted as long as Ásbrú was open. After restarting the application, statistics of local shells were gone, no longer counted towards totals. It was apparently only the named connections that were saved and read back from the configs.

In this regard the new behavior is more consistent with itself; however, ideally even the local connection's usage would be saved and restored.

**Comment by gfrenoy** [comment]
Made a change to include local shell connections into the statistics (and save this information as well).
