### ISSUE TITLE
Launching a second Ásbrú crashes the first one

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#187]
Launch `./asbru-cm`. Then again (e.g. from another terminal) launch another `./asbru-cm`.

The new one fails with:

```
(asbru-cm:19083): Unique-DBus-WARNING **: 12:55:54.756: Error while sending message: Message recipient disconnected from message bus without replying
Ásbrú not started. Is Ásbrú already running?
```

And the older, existing one crashes with a brief message:
```
Segmentation fault
```

Same story if the second one wants to perform some action that requires connecting to the first, e.g. `--start-shell`, `--start-uuid=...`, `--edit-uuid=...`.

This is with current git master, a.k.a. 08fb877adf, using GTK2.

Ubuntu 19.10 beta, Ásbrú taken from git rather than a Debian/Ubuntu package. Most of the dependencies installed as Ubuntu package, some (that are no longer available in 19.10, such as Gtk2::Unique 0.05) manually from cpan, some less important ones might be missing.

**Comment by egmontkob** [comment]
No crash if I comment out the approximately 30 lines of `$$self{_APP} -> signal_connect( 'message-received' , sub { ... }`. The first Ásbrú simply doesn't care about incoming connections, then.

Whatever I add to the very first line of this `sub` (the `message-received` handler), e.g. a `print STDERR "foo\n";` or a `sleep 100;` isn't executed, the segfault occurs before reaching this point.

**Comment by egmontkob** [comment]
I guess it's okay to leave it buggy in the GTK2 branch if we find a working counterpart for GTK3.

**Comment by egmontkob** [comment]
Is it just a bug with my setup, or is it buggy for everyone?

If it's buggy for everyone then probably we can conclude that this is a feature no one is using. Then it's much easier to remove this feature entirely than to port to GApplicationCommandLine for GTK3.

**Comment by KlaasT** [comment]
I actually managed to launch three asbru-cm instances in parallel. However this is from the GTK3 branch.

With ./asbru-cm --start-shell I can start a second instance and the first one still stays. So the indeed the first one doesn't care about a second being started however it won't crash.

**Comment by egmontkob** [comment]
> I actually managed to launch three asbru-cm instances in parallel. However this is from the GTK3 branch.

Yes, because the libunique stuff (connecting to an already running instance) is not yet ported to GTK3.

> With ./asbru-cm --start-shell I can start a second instance and the first one still stays.

What does it do for you with GTK2? For me it crashes the existing instance.

**Comment by KlaasT** [comment]
Okay yes. From the master branch it is crashing the first instance with a memory allocation failure.

**Comment by egmontkob** [comment]
It's not just me then.

It's pretty unlikely to be an issue with Ásbrú per se, probably an issue with a perl module. And since porting to GTK3 would change the code significantly, there's probably not much use in trying to fix it for GTK2. Probably a proper GTK3 port, using GApplication instead of libunique, would just work as expected.

However, I'm temped to say that this is a sign that people don't use these features, and instead of porting to GApplication (which doesn't offer you to send an arbitrary message, but to send the not-yet-processed command line flags over), which seems doable but quite cumbersome, maybe we could just drop all these features.

**Comment by KlaasT** [comment]
I agree. If anyone was using it we would probably have a quite big amount of complaints and reports. 

@gfrenoy What is your opinion? Drop these buggy features or try to port them to GApplication?

**Comment by gfrenoy** [comment]
On Ubuntu 18.04 LTS / GTK2 version ; the option "Allow to run more than one instance at the same time" works for me (both if checked and unchecked).  No crash.

On GTK3 version ; the option is useless, an new option is always started (what makes sense since libunique is not there anymore).

I would say that this option is useful ... I do have it unchecked and would not like to see several versions of Ásbrú running.

**Comment by egmontkob** [comment]
Fair enough. Someone needs to port from libunique to GApplication then. Who shall that be?? :)

**Comment by gfrenoy** [comment]
Didn't I try already ?  Don't remember exactly.  Not today but I can continue. I guess it starts here:
  https://developer.gnome.org/gtk3/stable/gtk-migrating-unique-GtkApplication.html

**Comment by gfrenoy** [comment]
Got a bit confused by the article ; we only need to register the application and then use ```get_is_remote``` to go back to the previous behavior.

The next commit should have the "allow more instances" working again :)

**Comment by egmontkob** [comment]
Thanks! Indeed activating the already runninig instance seems quite simple (I haven't tried implementing it though :))

What seems a bit more complex is to pass "messages" (in the old version; unprocessed command line options in the new), i.e. when the second asbru is started with `--foobar` then make the already running instance execute the action corresponding to it.

But it's probably not that hard either, I just truly didn't have the motivation to do it.

**Comment by gfrenoy** [comment]
Well, that "message" thing is still not working ... "send_message" does not exist in ```Gtk3::Application```, apparently.  I don't what is the equivalent.

**Comment by egmontkob** [comment]
I can't find a direct equivalent. Looks to me – solely based on reading the docs, without having any experience here – that you need to go with GApplication's "command-line" signal and friends. E.g. from `g_application_run()`'s doc: "What happens next depends on the flags: if G_APPLICATION_HANDLES_COMMAND_LINE was specified then the remaining commandline arguments are sent to the primary instance, where a “command-line” signal is emitted." Also look around `local_command_line` how to make exceptions from this list that are handled locally.

The old system allowed you more freedom, the new one seems to give you one concrete architecture to use. That's why porting from asbru's old solution to the new system is going to be a bit more complicated than just a line-by-line replacement of code.

**Comment by egmontkob** [comment]
Or maybe you can `g_application_get_dbus_connection()` and then on that `g_dbus_connection_send_message()`.

**Comment by gfrenoy** [comment]
Thanks for the tip !  I found out [this article](https://developer.gnome.org/gtk3/stable/ch28s02.html) suggesting to use a group action but I'm lost so far.

**Comment by egmontkob** [comment]
> I found out this article

Looks promising!

> but I'm lost so far.

That's how it always starts, isn't it? :)

**Comment by gfrenoy** [comment]
> That's how it always starts, isn't it? :)

Of course :)

So I finally used ```g_application_open``` ; probably not the most beautiful code on Earth but it looks to work and is somehow similar to what we had.

Thanks again for your help and support !
