### ISSUE TITLE
[gtk3] Wrong label for Proxy Configuration

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#189]
gtk3 branch only:

Click on Preferences. The left-hand tab bar has an entry "Expect", which should be called "Proxy Configuration" instead.

Looks like it's simply faulty in the .glade file. If I open them in `glade`, it's faulty in the gtk3 version, while correct in gtk2 (after converting the file to the new format using `gtk-builder-convert`).

**Comment by KlaasT** [comment]
Thanks for reporting this. Corrected with the latest commit.
