### ISSUE TITLE
Duplicated options strings on SSH Advanced options tab

### ISSUE THREAD

**Issue by ltden** [asbru-cm/asbru-cm#19]
I use PAC and have some configured connections.
Asbru sees the connections and settings from PAC.
In PAC those connections have one string on Advanced options tab: "ProxyCommand  ssh -q -W %h:%p jumphost" in PAC
When I edit the connections using Asbru I see two the same strings on Advanced options tab:
ProxyCommand  ssh -q -W %h:%p jumphost"
ProxyCommand  ssh -q -W %h:%p jumphost"
However the connections work in Asbru, it actually use only one option string

**Comment by gfrenoy** [comment]
Interesting.  I'm not sure to get it exactly though.  Could you let me me know in which field you see the duplicated option ?  Or maybe do a screenshot ?

**Comment by ltden** [comment]
Hello!
Please see the screenshots, the connection was initially created in PAC.
PAC:
![pac](https://user-images.githubusercontent.com/20603656/32703087-5cbc46da-c80a-11e7-8191-e653dbdc426f.jpg)

Opened in Asbru:
![asbru](https://user-images.githubusercontent.com/20603656/32703088-617a2e3a-c80a-11e7-8df4-da9c0f58285c.jpg)

**Comment by gfrenoy** [comment]
Great :) I indeed see the same kind of problem here as well ... Really strange since no code has been (intentionally) change there but I'll have a look.  Thanks for the feedback !

**Comment by ltden** [comment]
FYI,
I have applied this patch on PAC to make ProxyCommand option works:
https://sourceforge.net/p/pacmanager/bugs/267/

**Comment by gfrenoy** [comment]
Ah ! This explains why we don't have the same behavior ;-)  Let me apply that patch to Ásbrú as well, I guess it'll help.  Thanks for the info.

**Comment by gfrenoy** [comment]
That was it !  After I applied Magnus' patch, it worked as expected on my environment.  We'll soon release a RC4 that includes it.  Thanks again for reporting the issue.

**Comment by ltden** [comment]
Thank you for your great support!

**Comment by merikz** [comment]
Hi,
good to see pac/asbru come to life again!
I also noticed this problem came back. Good that the same patch still works. I made a series of patches
around that time, for a few annoying problems. For example variable handling and right-click menus and keepass handling IIRC. I'll see if I can find time to port them to asbru.
regards
Magnus

**Comment by gfrenoy** [comment]
Hi Magnus.  Nice to have you on board :)  And thanks for the fix on this bug.

If you have other patch files that we can integrate to Ásbrú, it will of course be very much appreciated.

**Comment by ltden** [comment]
Guys, I don't see this problem in RC4.
I think we can close the issue.
Thank you!
