### ISSUE TITLE
[gtk3] Searching in the terminal doesn't work

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#192]
gtk3 branch

Start a terminal session. Right-click over the terminal itself and choose Find, or press its shortcut Ctrl+F3. The search dialog does not pop up.

The first time these two warnings/errors are printed:

```
*** Gtk3::Widget::has_focus: passed too many parameters (expected 1, got 2); ignoring excess at /home/egmont/src/asbru-cm/lib/PACTerminal.pm line 3565.
```

(Probably `has_focus` without parameter to query its actual value, or `grab_focus` to grab it.)

```
*** unhandled exception in callback:
***   Can't locate object method "can_default" via package "Gtk3::Button" at /home/egmont/src/asbru-cm/lib/PACTerminal.pm line 3584.
***  ignoring at /usr/share/perl5/Gtk3.pm line 572.
```

(Probably you need `set_can_default`.)

Do it again, this time this is printed:

```
*** unhandled exception in callback:
***   Can't call method "set_text" on an undefined value at /home/egmont/src/asbru-cm/lib/PACTerminal.pm line 3506.
***  ignoring at /usr/share/perl5/Gtk3.pm line 572.
```

(Probably needs a `// ''` as seen elsewhere during the gtk3 migration.)

(Sorry guys, I don't feel like coding now, just doing QA-ish work :))

**Comment by gfrenoy** [comment]
If you already give all the solution, it's too easy :-)  Ctrl+F3 now shows the dialog for me.  I'll push the fix in a minute.

**Comment by egmontkob** [comment]
I'm not giving you the solution, I'm giving you my first guess(es) on the solution, with no guarantee whatsoever. Big difference :)

**Comment by gfrenoy** [comment]
> I'm giving you my first guess

Your first *very educated* guess ; don't be so humble.  Thanks again for your help on this project!

**Comment by egmontkob** [comment]
You're very welcome! :)
