### ISSUE TITLE
[gtk3] feed_child: passed too many parameters

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#193]
gtk3 branch

Quit Ásbrú when it has a terminal open. This warning is printed:

```
*** Vte::Terminal::feed_child: passed too many parameters (expected 2, got 3); ignoring excess at /home/egmont/src/asbru-cm/lib/PACUtils.pm line 3500.
```

My bad, apparently there's no need to pass the array length, it's done automatically by the Perl binding.

**Comment by gfrenoy** [comment]
Mmm.  Don't see that message here.

And if I remove the length in PACUtils.pm line 3500, I see the opposite:

```
*** unhandled exception in callback:
***   Vte::Terminal::feed_child: passed too few parameters (expected 3, got 2) at /media/gaetan/Data/dvp/asbru/asbru-cm-gtk3/lib/PACUtils.pm line 3500.
***  ignoring at /usr/share/perl5/Gtk3.pm line 546.
```

Can it be that the perl binding changed this in 19.10 vs 18.04 ?

**Comment by egmontkob** [comment]
Yup, our annotations used to be incorrect.

`feed` was fixed [here](https://gitlab.gnome.org/GNOME/vte/commit/ef34977b6765be1036ea8cd016861199033e2231), for VTE version 0.30 or so, our previous API. Nothing to worry about here.

`feed_child_binary`'s fix was silently (or accidentally) sneaked in [here](https://gitlab.gnome.org/GNOME/vte/commit/00f252725c1eb1c5dc65fd9901221523418e18be), for VTE version 0.46.

Unfortunately the same went unnoticed for `feed_child` until [this commit](https://gitlab.gnome.org/GNOME/vte/commit/a1cd4a4e6e00022a6d874cef92980160973a9c01), released in VTE 0.52.

What I don't understand, though, is that Ubuntu 18.04 Bionic ships VTE 0.52.1, so it should already have this fix. Could you please confirm your VTE version? (E.g. `echo $VTE_VERSION` inside Ásbrú's terminal.)

You could branch based on the runtime VTE version, e.g. something like `if ( VTE::get_major_version() >= 1 or VTE::get_minor_version() >= 46/52 ) { one param } else { two params } `.

**Comment by egmontkob** [comment]
On a related note, I'm not even sure what's the difference between `feed_child` and `feed_child_binary` (something with encodings), and I'm absolutely not sure if there's any difference between them via the Perl binding. Maybe nothing. Or maybe you only call it with 7-bit data anyway. So perhaps you can unify them to just one of these methods (whichever turns out to be less problematic). I'm not entirely sure such a change would be okay, but probably it would.

**Comment by gfrenoy** [comment]
```
$ echo $VTE_VERSION                                                                                                                       
5202
```
(it's 18.04.3 btw)

Not sure to correctly understand the versioning scheme since https://packages.ubuntu.com/bionic/libvte9 shows 1:0.28.2 ?!

**Comment by egmontkob** [comment]
Indeed, 0.52.1 was shipped originally, but later 0.52.2 was released as an update to Bionic. So you have a fully updated Bionic, that's fine.

`libvte9` is the old, GTK2 based VTE. The new one is source package `vte2.91`, library package `libvte-2.91-0` and friends.

Just to stay on the safe side, please also check the introspection package `gir1.2-vte-2.91`. It should have the same version. (By the way, I think this is a necessary package, to be listed as a dependency in the control/spec files.)

Is there a way to suppress the warning message for this given line of Perl code? In that case you could just pass the length as second parameter, and everyone would be happy and silent.

**Comment by egmontkob** [comment]
Oh, I remember now. It's [Ubuntu patching back VTE to the previous, broken state](https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/1780501) for no sane reason that I could understand, rather than fixing the callers.

**Comment by egmontkob** [comment]
Ubuntu 18.10 Cosmic removed this freaking broken patch, and ships 0.54.

One thing that you can do is to check for `>= 54` rather than `>= 52`. It'll only warn on unpached 0.52 for an excess parameter.

**Comment by gfrenoy** [comment]
> libvte9 is the old, GTK2 based VTE. The new one is source package vte2.91

```
$ apt show libvte-2.91-0
Package: libvte-2.91-0
Version: 0.52.2-1ubuntu1~18.04.2
```

Oh I see.  Thanks for the explanations.

> Oh, I remember now. It's [Ubuntu patching back VTE to the previous, broken state](https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/1780501) for no sane reason that I could understand, rather than fixing the callers.

Waw, yes, that is so surprising and unpredictable ;-/  Anyway, we understand the root reason.  Thanks for digging into this.

> Is there a way to suppress the warning message for this given line of Perl code?

[Yes](https://stackoverflow.com/questions/19490351/how-can-i-suppress-warnings-from-a-perl-function).

(Did you really believe it could not be possible with such a language ;p)

> One thing that you can do is to check for >= 54 rather than >= 52. It'll only warn on unpached 0.52 for an excess parameter.

Ok I made a mix with all these information and try to cope with the various cases.

Thanks again for your help!

**Comment by egmontkob** [comment]
> (Did you really believe it could not be possible with such a language ;p)

LOL. It was 12+ years ago that I last did some Perl coding, apart from ths one now. Now that you link to an answer, it sounds familiar, but it didn't occur to me on my own. And yesterday was a QA day for me, not a googling-coding day :)

**Comment by egmontkob** [comment]
Could you please also do the same for `_vteFeedChildBinary` for VTE versions prior to 0.46,

**or**

decide on a minimum supported VTE version, at least 0.46 in this case, and place this requirement in the control/spec files?

If you're planning to add `set_bold_is_bright()`, mentioned somewhere in #176, then requiring 0.52 might be a reasonable choice. (And in that case you can remove the last branch of the `_vteFeedChild` version check, LOL.)

---

Ubuntu 16.04 Xenial -> 0.42
Ubuntu 18.04 Bionic -> 0.52 (patched)
Ubuntu 18.10 Cosmic -> 0.54

Debian 9 Stretch -> 0.46
Debian 10 Buster -> 0.54

RHEL 7 -> 0.52 as an update?? A bit unclear to me [here](https://bugzilla.redhat.com/show_bug.cgi?id=1569801) but there's a 0.52 [centos 7](http://mirror.centos.org/centos/7/os/x86_64/Packages/) package, so probably yes
Fedora 29 -> 0.54

Based on these, again, it might be reasonable to require 0.52 and not spend time on supporting (testing, workarounding etc.) older ones (e.g. checking whether `set_bold_is_bright()` is available before calling it, maybe even hiding the UI checkbox). Those with an older system can still use GTK2-based Ásbrú 5.2 :P

**Comment by gfrenoy** [comment]
I believe we'll indeed put some requirements in the dependencies but in the meantime, I just added the test in ```_vteFeedChildBinary```.

Thanks for the good suggestion.
