### ISSUE TITLE
PNG screenshots

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#194]
Screenshots are automatically created from terminals, and stored as JPG files.

This is fine as long as only a small thumbnail is shown. But clicking on the thumbnail opens the screenshot at its original size, and JPG is terribly blurry/noisy for these kinds of pictures.

May I recommend to store PNG screenshots instead?

**Comment by gfrenoy** [comment]
Should we have an option for this or just move to PNG for any new screenshot ?

**Comment by egmontkob** [comment]
It's your project to make such decisions not mine. :) But IMHO just move to PNG for all new screenshots.

**Comment by gfrenoy** [comment]
Thanks for giving your opinion.  Just made the change, should work that way from now on.
