### ISSUE TITLE
[gtk3] Set VTE's cwd via proper API

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#195]
Click on "Launch new local shell" (bottom middle).

A new terminal is started in whatever directory Ásbrú's working directory is, and then the command `cd /home/username` is fed to VTE using `feed_child[_binary]()`.

While it certainly works (*), it's quite ugly.

[(*) I'm blindly assuming that no one wants to shoot themselves in the foot by having special characters in their home directory, or that Ásbrú properly escapes them. I haven't checked the latter.]

VTE's `spawn_[a]sync()` methods have a dedicated parameter to specify the working directory. Using this field, instead of feeding, would be a much cleaner solution.

There's lot of stuff going around in Ásbrú with setting environment variables. I haven't checked out this part of the software. In case any environment variable is set by feeding to the child process, it would also be better to pass them to `spawn_[a]sync()`.

**Comment by gfrenoy** [comment]
Indeed, much better.
