### ISSUE TITLE
[gtk3] Local shell colors not remembered

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#196]
Preferences -> Local Shell Options -> Look and Feel -> Use these personal options

Pick four colors (need to toggle the checkbox above two of them).

Close and reopen this dialog.

Notice that the previously picked "Text color" is now moved to "Bold color like Text color", and the other three are reset to their defaults.

**Comment by egmontkob** [comment]
[asbru-196-local-colors-not-fix.patch.txt](https://github.com/asbru-cm/asbru-cm/files/3665953/asbru-196-local-colors-not-fix.patch.txt)

This definitely looks buggy. To my excuse, I took it from the feature-gtk3 branch :P

But this does not fix this bug.

We'll need to thoroughly look at the big gtk3 porting patch for other similar bugs...

**Comment by egmontkob** [comment]
In PACConfig.pm the old version used to say things like `$$cfg{'defaults'}{'text color'}` which got converted to `_updateWindowColor`'s 4th parameter `'text color'`.

In PACTermOpts.pm the old version used to say `$$cfg{'text color'}` instead, but is also converted to the same 4th parameter `'text color'` (or `'text black'` which I assume is a typo, as per the previous patch), upon which the implementation of `_updateWindowColor` still looks it up as if there was an indirection via `{'defaults'}`.

**Comment by egmontkob** [comment]
Just FYI:

My first work-in-progress version didn't use the wrapper method from feature-gtk3, but did everything inline. The changes looked like these:

    -	_( $self, 'colorText' )					-> set_color( _( $self, 'colorText' ) -> get_color -> parse( $$cfg{'defaults'}{'text color'} // _( $self, 'colorText' ) -> get_color -> to_string ) );
    +	_( $self, 'colorText' )					-> set_color( scalar Gtk3::Gdk::Color::parse( $$cfg{'defaults'}{'text color'} // _( $self, 'colorText' ) -> get_color -> to_string ) );

The trick was the addition of `scalar` to the right place. Also to call a class method on the class rather than an instance of it (as it's done correctly at other places in the code).

Also should probably say `set_rgba` and `Gtk3::Gdk::RGBA` for a non-deprecated solution, as I later changed that in the helper method.

You might want to revert to this one-liner approach, instead of somehow passing yet another parameter to the helper method (whether to access the field under `{'defaults'}` or not). Up to you, of course.

**Comment by gfrenoy** [comment]
I changed ```_updateWindowColor``` ; it now expect to have the configuration object and does not look into ```{'defaults'}``` anymore.

It looks to fix the issue for me.
