### ISSUE TITLE
Suspicious pipe chars in regexps

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#197]
There are six occurrences of a regular expression going something like

    ... [p|P]ass|[p|P]ass[w|W]or[d|t] ... [c|C]ontrase.a ...

(apparently "contraseña" is "password" in Spanish)

Inside parentheses the pipe symbols stands for "or", e.g. `(Password|Contrase.a)`.

Inside square brackets, however, it's a set of allowed characters to be listed. E.g. to match `p` or `P`, you should write `[pP]`.

`[p|P]` matches lowercase `p`, uppercase `P` as well as the pipe character itself `|`; presumably not what you want here.

**Comment by gfrenoy** [comment]
It looks so obvious when you read this ; can't believe it never saw it.  I fixed the regular expressions.
