### ISSUE TITLE
Easy settings syncronisation using cloud

### ISSUE THREAD

**Issue by doman18** [asbru-cm/asbru-cm#198]
KeepasXC has database in single file which can be syncronised with cloud services like gdrive, dropbox or nextcloud. This way i can have access to my passwords both at my work and home. I dont see (yet) such possiblity with Asbru

**Comment by gfrenoy** [comment]
There is nothing "native" but you can try to synchronize your ```.config/pac``` directory on your cloud service and use it on all your devices.

**Comment by doman18** [comment]
Ahh that is why "find" didnt return anything. But is it safe? I mean keepass database is encrypted and opened by password. I see that passwords in pac.yml are hashed some way and i also have password set for gui. What if someone get those data? Will he be able to use them?

**Comment by syco** [comment]
I do this between my desktop and laptop.
There's only one thing you have to keep in mind:
pac.yml is loaded when you open the application and is saved when you close it, so it's easy to create conflicts
```
e.g.
- open asbru-cm on pc1
- open asbru-cm on pc2
- make a change on pc1
- make a change on pc2
- close asbru-cm on pc1
-- now pac.yml changed on pc1 and gets synced to pc2 --
- close asbru-cm on pc2
-- pc2 has now generated a conflict
```

**Comment by doman18** [comment]
For me its not a problem since i never have situation of working with Keepas/Asbruu on two pcs at once. Only changes during offline time could cause this. 

But i more concerned about security. Afterall Asbruu keeps credentials to some important stuff.

**Comment by gfrenoy** [comment]
Thanks for your feedback @syco :)

@doman18  : about security, see #121
What we should do, I guess is to have a better KeePassXC support (see #65).

Contributions of any kind are welcome :)

**Comment by syco** [comment]
One more thing that forgot to mention, I sync only the pac.yml file and the scripts folder. All the tmp folders and freeze files are prone to conflicts.
On this, I don't know why the freeze files, but wouldn't be better to read and write the configuration directly, maybe monitoring the file for changes?
I might have a look at it and test if it's a viable solution.

Regarding the example above, it doesn't need to occur in that sequence. It mainly happens to me when I make changes at home, leave the computer on with asbru-cm open and some changes unsaved. And then go to the office and do the same.

**Comment by gfrenoy** [comment]
Not sure about the freeze file.  My assumption was that it was mainly useful when launching separate processes (pac_conn) but I did not investigate further.

What is sure is that it might be a good thing to simplify this...I believe that today everybody is expecting to have an "auto save" option, anyway.

See also this discussion #34 and maybe to do along with #182.

**Comment by gfrenoy** [comment]
Let's continue the discussion on the initial request #34
