### ISSUE TITLE
[gtk3] VNC connection (in embed mode) does not work properly

### ISSUE THREAD

**Issue by gfrenoy** [asbru-cm/asbru-cm#199]
Existing VNC connection fails to start in the new gtk3 branch.

When starting, the following error message is shown:

```
*** unhandled exception in callback:
***   Can't locate object method "get_xid" via package "Glib::Object::_Unregistered::GdkX11Window" at /dvp/asbru/asbru-cm-gtk3/lib/PACTerminal.pm line 301.
***  ignoring at /usr/lib/x86_64-linux-gnu/perl5/5.26/Glib/Object/Introspection.pm line 67.
```

**Comment by gfrenoy** [comment]
Don't understand why it complaints, that function looks to exist : https://developer.gnome.org/gdk3/stable/gdk3-X-Window-System-Interaction.html#gdk-x11-window-get-xid

**Comment by gfrenoy** [comment]
When in "embed" mode, Ásbrú is not able to "kidnap" the window anymore.

1) In ```PACTerminals.pm``` (line 301), ```$$self{_GUI}{_SOCKET} -> get_window -> get_xid``` does not work.  I *think* we can replace it with ```$$self{_GUI}{_SOCKET} -> get_id```

2) In ```PACUtils.pm``` (line 3029), helper function ```_getXWindowsList``` does not work anymore.  For some reason, the loop on ```$s -> get_window_stack``` does not work as expected.

Any help or tip will be appreciated :-/

**Comment by egmontkob** [comment]
Sorry for the lame question, but... how does it work with gtk**2**?

I've installed, configured, started up tightvncserver.

I've installed tigervnc-viewer, since Ásbrú told me:

> 'tigervnc' is preferred, since it allows embedding it's window into PAC

(notice the typo: should be "its", also no trailing dot)

I configured the connection in Ásbrú (Method: VNC; Host, Port, Password filled in). It works – within Ásbrú a terminal appears with about 10 lines of text, and a separate window connects successfully with VNC.

Now I enable the connection -> 'VNC' Options -> Embed in TAB. When I try to connect, the title in the tab bar becomes red, and at the bottom it says "Status: DISCONNECTED". Seems that the vnc viewer quits immediately, or so.

What am I missing?

**Comment by gfrenoy** [comment]
Mmm, indeed.  I'm actually not using that myself so I'm not even sure if it ever worked with gtk2.

Said differently: just tried with gtk2 and I indeed see the same behavior as you describe... Note that I use TightVNC.  And I see error messages on the console:

```
Gdk-WARNING **: Couldn't match property type UTF8_STRING to STRING
Gdk-WARNING **: Couldn't match property type UTF8_STRING to STRING
Gdk-WARNING **: Couldn't match property type UTF8_STRING to STRING
Gdk-WARNING **: Couldn't match property type UTF8_STRING to STRING
GLib-CRITICAL **: Source ID 2112 was not found when attempting to remove it at /media/gaetan/Data/dvp/asbru/asbru-cm/lib/PACTerminal.pm line 1271.
GLib-CRITICAL **: Source ID 2112 was not found when attempting to remove it at /media/gaetan/Data/dvp/asbru/asbru-cm/lib/PACTerminal.pm line 1103.
```

So at this stage ; either there is a way to embed an existing window, either I suppress that "embed" option for now...

ps: typo has been fixed on the gtk3 branch already.

**Comment by egmontkob** [comment]
Oh, I remember reporting an "it's" vs "its" typo, was it the same? :D

I'm trying to figure out `get_xid`, with no success yet. That "Glib::Object::_Unregistered::GdkX11Window" really doesn't look great to me.

Also the C method `gdk_x11_window_get_xid()` takes a `GdkWindow *` as first param, so the method name doesn't really match the object it's operating on. We've seen similar with `gdk_pixbuf_get_from_window()` which is mapped to the totally unguessable `Gtk3::Gdk::pixbuf_get_from_window()`. Maybe we need something like this here, something like `Gtk3::Gdk::x11_window_get_xid( $win )`, I just can't figure out what exactly.

**Comment by gfrenoy** [comment]
That GdkX11Window thing doesn't inspire me much either :-/

About the windows list, I may have found something interesting: https://stackoverflow.com/questions/37950679/how-to-list-all-x11-windows-using-gtk3gdk

**Comment by egmontkob** [comment]
Haha, that guy does a `Gtk3::Gdk::x11_get_default_root_xwindow()`, so my previous guess of `Gtk3::Gdk::x11_window_get_xid()` might have actually been a good one.

Looks like GdkX11Window stuff is not pulled in automatically, just like GIO isn't which I solved in `lib/ex/Glib/IO.pm`. The same needs to be done for GdkX11. This could be the key to making it work.

**Comment by gfrenoy** [comment]
```@{$s -> get_window_stack}``` works to get the list !  Not sure why but before, the ```@{...}``` was not required.

Now the last issue : finding the right way to get xid !

[This comment](http://gtk.10911.n7.nabble.com/GStreamer-and-Gtk3-td85766.html#a85831) on the mailing list is more or less what we are facing, isn't it:

> I should note though that the get_xid() call is part of GdkX11, which
> isn't wrapped as part of the Gtk3 perl modules as shipped in Debian; I
> had to use Glib::Object::Introspection to create my own perl wrapper
> (which works, but is slightly annoying).

Not yet sure how he did it.

**Comment by egmontkob** [comment]
I assume you cross-posted to my previous post :) You need to get the one-liner `Glib::Object::Introspection->setup(...)` from the stackoverflow post you linked, or whatever I did in `lib/ex/Glib/IO.pm` (or actually `lib/ex/Vte.pm`, too), it's the same. It's as simple as this to import the automatic bindings via introspection.

The `basename` and `version` parameters correspond to the `*.typelib` filename somewhere on the filesystem that will be loaded, `package` is whatever perl package you want it to be imported and accessed as.

**Comment by egmontkob** [comment]
(If you go with the one-liner inlined approach, you might want to convert the two tiny files that I created to inline, too, for consistency.)

**Comment by gfrenoy** [comment]
Oh !  Ok I see !  Well, at least, better ... I'll need to figure out the proper way but it looks to work better, indeed.

So I have now ```get_xid``` working :)  Great.

Now it's complaining about another one:
```
Can't locate object method "foreign_new_for_display" via package "Gtk3::Gdk::Window"
```

Time to sleep on this bit :)

Thanks again for your precious help !

**Comment by gfrenoy** [comment]
Didn't even notice the tooltip on that option:
![image](https://user-images.githubusercontent.com/981546/66276975-41e96a80-e898-11e9-97ca-152cc4bf1a94.png)

No kidding !

**Comment by egmontkob** [comment]
[here it says](https://developer.gnome.org/gdk2/stable/gdk2-X-Window-System-Interaction.html#gdk-window-foreign-new-for-display):

> gdk_window_foreign_new_for_display has been deprecated since version 2.24 and should not be used in newly-written code. Use gdk_x11_window_foreign_new_for_display() or equivalent backend-specific API instead

So probably it's again `Gtk3::Gdk::x11_blah()`.

---

I have different buttons there and different tooltip. Probably it depends on the detected vnc client.

**Comment by gfrenoy** [comment]
This was the correct syntax:

```Gtk3::Gdk::X11Window -> foreign_new_for_display( $display, $xid )```

Now the next lines:

```
my ( $type_atom_name, $format_name, $data_name ) = $win -> property_get ( Gtk3::Gdk::Atom -> intern('WM_NAME'), Gtk3::Gdk::Atom -> intern('STRING'), 0, 9999, 0 );
my ( $type_atom_pid, $format_pid, $data_pid ) = $win -> property_get ( Gtk3::Gdk::Atom -> intern('_NET_WM_PID'), Gtk3::Gdk::Atom -> intern('CARDINAL'), 0, 9999, 0 );
my ( $type_atom_command, $format_command, $data_command ) = $win -> property_get ( Gtk3::Gdk::Atom -> intern('WM_COMMAND'), Gtk3::Gdk::Atom -> intern('STRING'), 0, 9999, 0 );
```

```get_property``` is not known:

```
Can't locate object method "property_get" via package "Gtk3::Gdk::X11Window"
```

*sigh* so complicated...

**Comment by gfrenoy** [comment]
This syntaxically works:

```
my $a_name = Gtk3::Gdk::atom_intern( 'WM_NAME', 1);
my $s_name = Gtk3::Gdk::atom_intern( 'UTF8_STRING', 1);
my $data_name = Gtk3::Gdk::property_get ( $win, $a_name , $s_name, 0, 9999, 0 );
```

But it merely crashes:

```
ERROR:gperl-i11n-marshal-struct.c:43:struct_to_sv: assertion failed: (!own)
```

Trying to understand what [property_get](https://developer.gnome.org/gdk3/stable/gdk3-Properties-and-Atoms.html#gdk-property-get) means...

**Comment by egmontkob** [comment]
This (including the error) is the same as on the stackoverflow post that you linked. It's unclear to me how he solved this one.

> Trying to understand what property_get means...

Looks like some low level X11 programming to me, something I'm truly not familiar with.

**Comment by egmontkob** [comment]
This should be the API equivalent of the `xprop` command line tool. Launch that from a terminal, click on a window, and see what it prints for manual debugging of the desired values.

**Comment by gfrenoy** [comment]
Thanks Egmont :)  So I cleaned this up a bit and used Wnck to list the Windows.  As far as I can see we only only need the name of the window so that stackoverflow article is indeed all we need.

So at this stage, it looks to find out the correct window to embed and is doing

```
$$self{_GUI}{_SOCKET} -> add_id( $$list{'by_name'}{$title}{'xid'} )
```

to embed the window into the created [GtkSocket](https://developer.gnome.org/gtk3/3.24/GtkSocket.html).  On my machine, it just shows a gray window and does not work ... But I believe it is just as what the Gtk2 version was doing.

The RDP connection works fine.

Time to sleep now.  More investigations will be for another day.

**Comment by egmontkob** [comment]
Embedding using XID is probably sooner or later going to be a thing of the past. It's specific to X Window, and the new display server Wayland probably doesn't have such a concept.

Well, there's XWayland, the X compatibility layer for Wayland, transparently used whenever needed (when the client asks for X whereas the display server is Wayland). Probably embedding using XID works on XWayland, too.

Anyway, this approach _feels_ old fashioned to me. That being said, if easily doable, why not make it work.

---

In the mean time let me point you to [gtk-vnc](https://wiki.gnome.org/Projects/gtk-vnc), a VNC viewer widget for GTK. I haven't looked at it, but purely by its description it looks like the "proper" GTK-style embedding solution for VNC.

In that sense, it's to remote desktop as what VTE is to terminal emulation; whereas embedding a tight/tiger/whatevervnc window using XID would be analogous to let's say embedding an xterm using XID.

I'd leave it to you to explore how usable, convenient, nice etc. it is. I think it would be nice to add it as a possible option. (If things go really well then maybe you can even remove the other vnc solutions you offer.)

Being a GTK3 project, it provides language bindings via introspection. Ubuntu ships these files in its gir1.2-gtk-vnc-2.0 package.

**Comment by gfrenoy** [comment]
Very good point !  That would be a great achievement to use gtk-vnc instead of that tricky integration with legacy VNC clients.  Thanks a lot for the suggestion :)

I believe we should close that issue (it now works "as before") and create a new one for gtk-vnc integration (that might have a lower priority at this stage).

Thanks again for your very valuable contribution.

**Comment by gfrenoy** [comment]
By looking a bit more to the various VNC clients (TightVNC and TigerVNC), the "embedded window" is not an option that they support anymore.

So I removed the "embed" option for VNC and we can close this issue.

I will create a new issue to support [gtk-vnc](https://wiki.gnome.org/Projects/gtk-vnc).
