### ISSUE TITLE
No packages for Ubuntu

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#2]
I've tried to install asbru-cm according to the instructions in README.md and the following happend:

---SNIP---
 ✘  Fri 20 Oct - 15:40  ~ 
 @micpos  curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash
[sudo] password for micpos: 
Detected operating system as Ubuntu/artful.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/asbru-cm_asbru-cm.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.

 Fri 20 Oct - 15:41  ~ 
 @micpos  sudo apt install asbru-cm                                                                               
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package asbru-cm
---SNAP---

apt update get's a HTTP/404 when trying to fetch the repository list.
On packagecloud.io I saw there is only packages for debian stretch.

When I manually change /etc/apt/sources.list.d/asbru-cm_asbru-cm.list to point to debian stretch, it works and I can successfully "apt update".

Installing asbru-cm failes due to a dependency issue with libgnome2-vte-perl but I will file a separate issue for this.

**Comment by KlaasT** [comment]
Thanks for posting this issue. At the moment there are only Debian 9 packages. libgnome2-vte-perl should be resolvable. I will have a look at this.

**Comment by gfrenoy** [comment]
Ubuntu / Artful package has been uploaded on packagecloud.io so it should work for you now.

**Comment by nomike** [comment]
Unfortunately the package you uploaded doesn't work on Ubuntu Artful.
They switched to perl 5.26 and https://packagecloud.io/asbru-cm/asbru-cm/packages/ubuntu/artful/libgnome2-vte-perl_0.11-1_amd64.deb still installs stuff to /usr/lib/x86_64-linux-gnu/perl5/5.24/ and most likely is compiled towards perl 5.24.

Should I open a new bug for this or do you want to reopen this one?

Meanwhile I've sent a request for packaging to debian so that the Gnome2::Vte CPAN module is added to the official package index, this way the folks at debian and canonical will take care of it in the future. But I highly doubt this will be a quick process (never filed a request towards debian so far, so I don't know for sure).

**Comment by gfrenoy** [comment]
Ok thanks for the test.  Let's re-open this issue and see what we can do.

About adding Gnome2::Vte to Debian, see my message from Sep 19 on the Debian perl mailing list: https://lists.debian.org/debian-perl/2017/09/msg00033.html (and associated answers).  In short, this will not happen I do fear.

**Comment by KlaasT** [comment]
I will try to set up an Ubuntu Artful VM and maybe I will have any luck to compile the package correctly. However I'm at the RIPE Meeting at the moment I don't know if I manage to get this running this week.

**Comment by gfrenoy** [comment]
Ubuntu artful & xenial packages have been uploaded to packagecloud.io with correct dependencies to perl 5.22 and 5.26.

**Comment by dpecka** [comment]
I'd vote for NOT wasting effort to create per-distro packages ... community shall make packages for himself ... Moreover, if you git clone thing somewhere, it works without packages ... So for example, I just git cloning an asbru/pac to my $HOME/opt/pac with link $HOME/bin/asbru -> $HOME/opt/pac/asbru

regards, ddd
