### ISSUE TITLE
Segmentation fault when opening asbru-cm.

### ISSUE THREAD

**Issue by pabloricoy** [asbru-cm/asbru-cm#200]
**Describe the bug**

It's for some time since I last used it, it has always performed smoothly, so I can't figure out what has lead to this or under which circumstances.

I just try to run it, shows apparently correct, the connections seem to be listed, then vanishes. In dmesg I find a segmentation fault messages: 

[  373.915666] asbru-cm[5490]: segfault at 20 ip 00007f044c1ff474 sp 00007fff22276730 error 4 in libgdk-x11-2.0.so.0.2400.32[7f044c192000+b0000]
[  373.915671] Code: 48 89 84 24 98 00 00 00 31 c0 48 85 f6 0f 84 8b 02 00 00 48 b8 01 00 00 00 01 00 00 00 48 89 fd 49 89 f7 48 89 46 08 48 89 fb <48> 8b 47 20 eb 15 66 0f 1f 44 00 00 48 8b 50 20 48 85 d2 74 0b 48
pablo@Ubuntu-18:~$ 

I've tried to collect as much info as I can -but I'm a newbie, sorry-.

pablo@Ubuntu-18:~$ coredumpctl gdb
           PID: 5352 (asbru-cm)
           UID: 1000 (pablo)
           GID: 1000 (pablo)
        Signal: 11 (SEGV)
     Timestamp: Mon 2019-10-07 14:49:59 CEST (4s ago)
  Command Line: /usr/bin/perl /usr/bin/asbru-cm
    Executable: /usr/bin/perl
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (pablo)
       Boot ID: 56a78070d2ba4de49a5aa964ba18fcc4
    Machine ID: 1f3f6f87def4424bba7c2c7c72f398e5
      Hostname: Ubuntu-18.04
       Storage: /var/lib/systemd/coredump/core.asbru-cm.1000.56a78070d2ba4de49a5aa964ba18fcc4.5352.1570452599000000.lz4
       Message: Process 5352 (asbru-cm) of user 1000 dumped core.
                
                Stack trace of thread 5352:
                #0  0x00007feea1a68474 gdk_window_get_frame_extents (libgdk-x11-2.0.so.0)
                #1  0x00007fee9d63a1ae n/a (libgail.so)
                #2  0x00007feea17e038b atk_component_get_extents (libatk-1.0.so.0)
                #3  0x00007fee9cfdf8fe n/a (libatk-bridge-2.0.so.0)
                #4  0x00007fee9cfe6c6d n/a (libatk-bridge-2.0.so.0)
                #5  0x00007fee9ee87d90 n/a (libdbus-1.so.3)
                #6  0x00007fee9ee78b5a dbus_connection_dispatch (libdbus-1.so.3)
                #7  0x00007fee9cdac675 n/a (libatspi.so.0)
                #8  0x00007feea64ba417 g_main_context_dispatch (libglib-2.0.so.0)
                #9  0x00007feea64ba650 n/a (libglib-2.0.so.0)
                #10 0x00007feea64ba962 g_main_loop_run (libglib-2.0.so.0)
                #11 0x00007feea1ddfa37 gtk_main (libgtk-x11-2.0.so.0)
                #12 0x00007feea2399505 n/a (Gtk2.so)
                #13 0x0000561270329441 Perl_pp_entersub (perl)
                #14 0x0000561270321266 Perl_runops_standard (perl)
                #15 0x00005612702a217f perl_run (perl)
                #16 0x0000561270279492 main (perl)
                #17 0x00007feea92e1b97 __libc_start_main (libc.so.6)
                #18 0x00005612702794da _start (perl)
                
                Stack trace of thread 5385:
                #0  0x00007feea93d4bf9 __GI___poll (libc.so.6)
                #1  0x00007feea64ba5c9 n/a (libglib-2.0.so.0)
                #2  0x00007feea64ba6dc g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007feea64ba721 n/a (libglib-2.0.so.0)
                #4  0x00007feea64e2195 n/a (libglib-2.0.so.0)
                #5  0x00007feea96b86db start_thread (libpthread.so.0)
                #6  0x00007feea93e188f __clone (libc.so.6)
                
                Stack trace of thread 5386:
                #0  0x00007feea93d4bf9 __GI___poll (libc.so.6)
                #1  0x00007feea64ba5c9 n/a (libglib-2.0.so.0)
                #2  0x00007feea64ba962 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007feea0ed70e6 n/a (libgio-2.0.so.0)
                #4  0x00007feea64e2195 n/a (libglib-2.0.so.0)
                #5  0x00007feea96b86db start_thread (libpthread.so.0)
                #6  0x00007feea93e188f __clone (libc.so.6)
                
                Stack trace of thread 5387:
                #0  0x00007feea93db839 syscall (libc.so.6)
                #1  0x00007feea650089a g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007feea648d571 n/a (libglib-2.0.so.0)
                #3  0x00007feea648db2c g_async_queue_timeout_pop (libglib-2.0.so.0)
                #4  0x00007feea64e2c3e n/a (libglib-2.0.so.0)
                #5  0x00007feea64e2195 n/a (libglib-2.0.so.0)
                #6  0x00007feea96b86db start_thread (libpthread.so.0)
                #7  0x00007feea93e188f __clone (libc.so.6)

GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/perl...(no debugging symbols found)...rematado.

warning: core file may not match specified executable file.
[New LWP 5352]
[New LWP 5385]
[New LWP 5386]
[New LWP 5387]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/perl /usr/bin/asbru-cm'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007feea1a68474 in gdk_window_get_frame_extents ()
   from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
[Current thread is 1 (Thread 0x7feeaa07cfc0 (LWP 5352))]

**To Reproduce**
I'm just clicking the icon or start it within a shell.
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by gfrenoy** [comment]
Well, if it used to work and does not work anymore ; you'll need to find what has changed :-/

Any recent upgrade done on this machine ?

And, btw, what version of Ásbrú are using using ?

**Comment by gfrenoy** [comment]
Ok so this is the latest Ásbrú version.  Not sure what happened to your OS but you should probably make sure you have the proper packages to run Ásbrú... With a plain Ubuntu 18.04, it is working fine ; first make sure you have all the latest packages up to date...

**Comment by pabloricoy** [comment]
Yes, the Ubuntu is 18.04 and I have just updated to the latest packages, but no improvement.
Can't guess what happened.

**Comment by gfrenoy** [comment]
Did you try to start from a blank configuration directory ?

(attention, make sure to backup your ```.config/pac``` first)

(idea: it might be related to the content of your settings)

**Comment by pabloricoy** [comment]
Hi,

Yes I did. I tried to start without the session folders and connections, but crashes again.
I noticed while I still had the connections, that it taked longer to crash if I attempted to start a connection. 

BR,

**Comment by gfrenoy** [comment]
Sorry but I don't see why it's not working anymore on your machine.

I'm using Ásbrú on an up-to-date version of Ubuntu 18.04 and I also tried from a clean Ubuntu 18.04 system and cannot reproduce the problem :(

**Comment by beliys** [comment]
Try reinstalling all the Perl packages. If any of the modules was going to the old version of Perl, then you will get a Segmentation fault.
