### ISSUE TITLE
Not installable on Debian Sid

### ISSUE THREAD

**Issue by giaur500** [asbru-cm/asbru-cm#201]
Recent Perl update in Sid causes breaks Asbru, problem is outdated  Gnone2-vte-Perl libraries. Any workaround?

**Comment by KlaasT** [comment]
We are working on a GTK3 version to remove all the old dependencies. You can find install instructions in the GTK3 in the corresponding branch:

https://github.com/asbru-cm/asbru-cm/tree/gtk3

**Comment by giaur500** [comment]
Excellent. It works, thanks.
