### ISSUE TITLE
[gtk3]  Asbru crashes if you inactivate option "Put Terminals y Tabs"

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#203]
**Describe the bug**
In a fresh new installation.
Open Asbru, creates config dir

Open Preferences

Inactivate option : Put terminals in new tabs

![imagen](https://user-images.githubusercontent.com/1572396/66600683-a8f27200-eb6b-11e9-8f46-e9093802b450.png)

Save preferences, close, reopen and following message appeares

![imagen](https://user-images.githubusercontent.com/1572396/66600707-b871bb00-eb6b-11e9-8090-0578d7c44d11.png)

**Linux Mint:**
 - Linux
 - Version Xenial

**Comment by hanspr** [comment]
The consequence is that in PACMain.pm this next validation forbids hiding main PAC Windows after opening a connection on a new window

Line 2768

( $$self{_CFG}{'defaults'}{'hide on connect'} && ! $$self{_CFG}{'defaults'}{'tabs in main window'} ) and $self -> _hideConnectionsList;

**Comment by egmontkob** [comment]
Thanks for testing the GTK3 branch!

PACMain.pm line 835 should be `Gtk3::Window::set_default_icon_from_file( $APPICON );`. I fixed it somewhere else in the code, but not here.

(Not sure how line 2768 is relevant, I didn't run into a problem there.)

**Comment by hanspr** [comment]
Thanks for the fix egmontkob,

I can confirm that it does not crash any more.

The relevace of line 2768, is that if you can not uncheck this option (tabs in main tab, because produces the crash) then you are not able to use option "hide on connect", because they are connected by an "&&"

I use windows, not tabs and like to hide the Main Asbru window after I double click on the connection. I had to comment that if, and removed the and condition, to be able to do use hide on open, because I could not uncheck tabs in main tab option.

I had removed my commented line and returned line 2768 to its original validation and everything works fine.

Thanks again.

**Comment by hanspr** [comment]
Sorry

**Comment by gfrenoy** [comment]
Thanks both for your help !  The fix has been applied on branch gtk3.
