### ISSUE TITLE
[gtk3] Clusters sync input no longer works

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#205]
If I open 2 terminals that are in a cluster, and I type in one of them the other one does not receives a key but apparently a reference to a HASH. It used to work in Gtk2 version

![imagen](https://user-images.githubusercontent.com/1572396/66614696-a0ac2e00-eb8f-11e9-866e-97272c8e4158.png)

But if I use the  Power Cluster controler, the keys are sent correctly to both terminals

![imagen](https://user-images.githubusercontent.com/1572396/66614713-b3266780-eb8f-11e9-956d-50b2a1eda746.png)

May be I find the solution and send it later.

Linux Mint

**Comment by hanspr** [comment]
I found a some solutions to all my reported issues they are on a pull request. Hope it helps

**Comment by gfrenoy** [comment]
Thanks !  I cherry-picker your changes from your branch.
