### ISSUE TITLE
[gtk3] VTE: Remove or rework "Term Emulation"

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#206]
Old VTE tried to behave according to a given terminal description (in terminfo). That is, the value you set in Ásbrú as "Term Emulation" really changed its behavior.

New VTE doesn't do this, its emulation behavior is hardwired. Accordingly, the `set_emulation()` API was removed.

The remains of the "Term Emulation" UI entry and config file option should be removed

-- or --

should be reworked and rephrased into one that sets the value of `$TERM`, with the new default being VTE's default `xterm-256color`. Changing this field would not change how VTE itself behaves, but could still change how apps inside behave. Although I recommend not to do this and just go with VTE's choice.

**Comment by gfrenoy** [comment]
Option "Term Emulation" has been removed on the loki branch.
