### ISSUE TITLE
[gtk3] VTE transparency

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#207]
Terminal transparency doesn't work currently.

In new VTE it needs the following steps to make it work:
- give `set_color_background()` a background color with alpha;
- make the window app-paintable;
- do some magic around the `draw` signal;
- do further magic to make sure that other UI items (e.g. pane divider, unused area of notebook tab bar, etc.) don't become transparent.

I'm not sure about the exact details of the latter three. See VTE-based apps that support transparency for reference, e.g. Tilix, Terminator, Xfce4-terminal, Guake; and also a Fedora/Ubuntu patch for GNOME Terminal.

-- or --

Remove this feature (UI and config option).

**Comment by gfrenoy** [comment]
I guess we want to keep that feature, do we ?

**Comment by hanspr** [comment]
Yes, but I don't  know how to do it. I would suggest to hide the option while we study and find out how is done.

I think there are other issues and functionalities pending that are more important than this one.

**Comment by hanspr** [comment]
Close the other 2, check this one works and you would have your milestone completed
