### ISSUE TITLE
[gtk3] VTE visible bell

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#208]
VTE no longer supports a visible bell, and accordingly, the `set_visible_bell()` API was removed.

A terminal-based app might achieve a plain visual bell effect by setting reverse video for a short time. See e.g. `infocmp | grep flash` for the corresponding escape sequence, with a 100ms delay using terminfo's notation, or execute it using `tput flash`.

There's also the regular BEL character which emits the `bell` signal. You might catch it and decide to do whatever audio and/or visual effect you please, e.g. display an (animated) bell icon for some time, or until clicked on.

-- or --

You can just remove this feature (UI checkboxes and config options).

**Comment by gfrenoy** [comment]
I would vote for removing this feature.

Is there anybody really using this ?

**Comment by KlaasT** [comment]
Not me

**Comment by beliys** [comment]
Can we make a vote on this and similar issues?

**Comment by KlaasT** [comment]
Sure we could vote on this. I would say thumbs up on the initial post for "repair this feature" and thumbs down for "remove it entirely"

**Comment by KlaasT** [comment]
Will try to remove this to close the issue.

**Comment by hanspr** [comment]
@gfrenoy , @KlaasT 

If you give me a green light I can remove this functionality in a few minutes.

**Comment by KlaasT** [comment]
Sure go for it.

**Comment by KlaasT** [comment]
That should be done. Thanks @hanspr for the PR. Closed #208
