### ISSUE TITLE
Bad repository generated by asbru.sh on ubuntu

### ISSUE THREAD

**Issue by KaeroDot** [asbru-cm/asbru-cm#21]
If installation script asbru.sh is run on (k)ubuntu (14.04), it generates URI of repository https://packagecloud.io/asbru-cm/asbru-cm/ubuntu/ (this webpage does not exist!). Repository is updated correctly but no package asbru-cm is found by atp-get.

**Comment by gfrenoy** [comment]
With RC4, we have added support for Ubuntu 14.04 ; please give it another try and re-open the issue if required.

**Comment by gfrenoy** [comment]
My bad, there is still an issue on Ubuntu 14.04.  It should be fixed soon...

**Comment by gfrenoy** [comment]
Ok now it should work as expected ; let us know the outcome when you have a chance to give it a try.

**Comment by KaeroDot** [comment]
Works. Thanks!
