### ISSUE TITLE
[gtk3] VTE history of commands

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#211]
Remembering the history of terminal commands doesn't work (I've commented it out).

VTE's `get_text_range()` gives this error:

> gperl-i11n-invoke-c.c:582:_allocate_out_mem: assertion failed: (interface_info)

Looks like a nasty issue with VTE's annotation or the introspection framework. Might need help from introspection and Perl binding experts.

---

I played a bit with this one, and I think I give it up here.

The same method is used successfully in Terminator's logging plugin (Python).

If I alter the `(out caller-allocates)` annotation to simply `(out)` in VTE's source, the error message becomes a segfault instead.

If I remove `(out ...)` altogether (i.e. make it an `in` parameter), make it `(allow-none)` and pass it an `undef` (as we really don't care about this parameter) then it works like a charm.

Possibilities I see:

- Consult with VTE's main developer (he knows much more about these stuff than I do) whether our annotations are really good here, and whether we can (and should) change them to please the Perl binding. Mind you, I'm really not sure why it's an `out` parameter when its NULL-ness (undef-ness) actually carries information to the method (it saves work and memory if it's NULL/undef); shouldn't it be `in` or `inout` instead?

- Consult with Introspection's developers about this setup (`GArray`, which I believe is translated to native Perl array, as `(out ...)`) possibly not being supported and whether they're up to adding/fixing it.

- Write a small wrapper in C (and ship it as part of Ásbrú) that just skips this problematic parameter, and create a Perl binding for that that we could use.

- Drop this weird hack of Ásbrú of supporting command line history on its own.

**Comment by hanspr** [comment]
I searched and could not find a solution to this.

My suggestions would be

* Remove the functionality
    * We have sessions logs, command completions in the shell, etc.
* Reimplement (indirectly get new lines into the list by monitoring typing and paste), basic principle
    * On every character or paste, add the characters to a global $save_line
    * On every enter pass the $cmd_line to the list, and clean $save_line
    * Not sure if we would end up collecting bad information into the logs if we intercept everything typed, like when you are inside an application like an editor, because we do not have a reference of a prompt like the original code has.

Please vote, or add further suggestions

:+1:  REIMPLEMENT
:-1:  REMOVE

**Comment by hanspr** [comment]
This should be closed

**Comment by danielbgto** [comment]
I will miss it much. Not using it every day but sometimes is day-saving feature....

**Comment by popxunga** [comment]
Not sure what is this about, but if it removes the terminals session log facility, then I think something equivalent should be implemented.

**Comment by hanspr** [comment]
It does not remove any session logs, you still have them.

**Comment by popxunga** [comment]
Thanks @hanspr for the clarification.
