### ISSUE TITLE
[gtk3] Big GTK2 leftover cleanup

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#212]
Go through all the

- UI strings (error/info messages etc.)
- Documentation
- Perl package names used in the source
- Debian / Red Hat package names (dependencies)

and make sure that there are no GTK2 leftovers.

Make sure that the Debian control / Red Hat spec files mention all the required GTK3 packages, including the introspection ones (whichever packages ship the `.typelib` files corresponding to the `Glib::Object::Introspection->setup()` calls).

**Comment by gfrenoy** [comment]
It perfectly makes sense but very (too) general ... I do fear this kind of issue will remain forever open :-/  Can't we put it in https://github.com/asbru-cm/asbru-cm/projects/1 ?  Looks a better place to me.  What do you think ?

**Comment by egmontkob** [comment]
I split the way too generic #176 into multiple smaller ones for you, in the hope that it's useful. Feel free to further split it, or use other platforms than the issue tracker (e.g. projects/1), whatever is convenient for you to track progress, and to make sure it doesn't get missed before releasing a stable gtk3 version.

**Comment by gfrenoy** [comment]
> I split the way too generic #176 into multiple smaller ones for you

Yes, wonderful !  It really helps :)

> Feel free to further split it, or use other platforms than the issue tracker

Ok thanks, let me close this for now and have a reference in [projects/1](https://github.com/asbru-cm/asbru-cm/projects/1).
