### ISSUE TITLE
ubuntu 19.10 support please

### ISSUE THREAD

**Issue by netroby** [asbru-cm/asbru-cm#214]
```
Err:8 https://packagecloud.io/asbru-cm/asbru-cm/ubuntu eoan Release        
  404  Not Found [IP: 127.0.0.1 8123]

```
please support ubuntu 19.10

**Comment by KlaasT** [comment]
Ubuntu eoan packages are available for the gtk3 branch for now. You are welcome to test the gtk3 branch. Some installation instructions can be found here: https://github.com/asbru-cm/asbru-cm/tree/gtk3

However some things might not work as expected for the moment.

**Comment by RogueScholar** [comment]
Builds of the current GTK2 release (5.2.0) and all the needed backported packages for Eoan are available at the [Launchpad PPA](https://code.launchpad.net/~asbru-cm/+archive/ubuntu/releases) for anyone who's interested.

**Comment by gfrenoy** [comment]
@RogueScholar Why are you duplicating the work on launchpad and not contributing to this project ?

**Comment by gfrenoy** [comment]
And for those who really want to use the legacy version (5.2.1), check instructions on [our wiki](https://github.com/asbru-cm/asbru-cm/wiki/Installation-on-Ubuntu#snapshot-release).
