### ISSUE TITLE
[gtk3] Splash screen progress bar height

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#215]
In GTK2 the splash screen's progress bar is tall enough to display the progress as text (e.g. "Building GUI", "Loading Connections", "Finalizing").

In GTK3 the progress bar is much thinner and doesn't show these texts.

(I'm not sure whether the text is not visible because the progress bar is thin, or if the progress bar is thin because the text is not put there :))

**Comment by gfrenoy** [comment]
There is apparently a new property "[show-text](https://developer.gnome.org/gtk3/unstable/GtkProgressBar.html#GtkProgressBar--show-text)" and default is FALSE ; I set it to true.
