### ISSUE TITLE
[gtk3] Windows close on vertical resize

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#216]
Open a session local shell or ssh, on a window. You can resize the window horizontally or grow it vertically, but if you try to shrink it vertically the window closes (don't see any crash, it just closes)

Green arrows show valid resize actions, red arrows show direction in which it closes

![imagen](https://user-images.githubusercontent.com/1572396/66717525-a8dab800-ed9f-11e9-91b6-3c5ef86c7a06.png)

I have tried for several hours and can not find the code related to the resize event, I will not be able to help with this one.

Linux Mint 19.2

**Comment by gfrenoy** [comment]
Tried to reproduce that issue but without any success so far.

Can you give the steps and the error messages your see on the console ?

Thanks.

**Comment by hanspr** [comment]
That is a shame, it means that is related to my set up for some reason, my libraries versions.

This are the settings I have

![imagen](https://user-images.githubusercontent.com/1572396/66720262-27475200-edc0-11e9-983b-5346c4f64039.png)

![imagen](https://user-images.githubusercontent.com/1572396/66720268-34fcd780-edc0-11e9-876a-d321631b9d8c.png)

![imagen](https://user-images.githubusercontent.com/1572396/66720271-3e863f80-edc0-11e9-9de0-b9499472a2c4.png)

![imagen](https://user-images.githubusercontent.com/1572396/66720273-46de7a80-edc0-11e9-8499-60a8e419850f.png)

![imagen](https://user-images.githubusercontent.com/1572396/66720274-5067e280-edc0-11e9-9a5c-4084d7b920fb.png)

![imagen](https://user-images.githubusercontent.com/1572396/66720278-5958b400-edc0-11e9-8921-d9a93efcdba7.png)

Clic on new local terminal

![imagen](https://user-images.githubusercontent.com/1572396/66720307-ab013e80-edc0-11e9-84b4-27ef41f96af1.png)

Grab the bottom and move it up pass half the size (reduce more that half) and at some point it simply closes. No error at all on the terminal any where.

![imagen](https://user-images.githubusercontent.com/1572396/66720331-d5eb9280-edc0-11e9-9e46-5aad0d2f3c04.png)

**Comment by gfrenoy** [comment]
No reason to be ashamed, this is the beauty of this software to have that many options :-)

Let me ask a few more questions to see if we can troubleshoot this together:

1) Can you share your "Local Shell Options" ?

2) Even if you don't see any particular message, can you share what you see on the command line when you run Ásbrú ?  There *must* be something shown...

3) Can you try from a "clean" environment ; by renaming / backuping your ```.config/pac``` directory and try from a new one

4) If it does not contain any confidential information, can you share that ```.config/pac``` folder ?

Thanks for your help,

**Comment by hanspr** [comment]
You are right, it it does not happen with  fresh configuration, so is related to one of the options.
Give me some time to figure out which option (or combination of options) creates the issue.

**Comment by hanspr** [comment]
New discovery, on fresh install, does not closes the window, but I receive this message after shrinking it: Disconnected

![imagen](https://user-images.githubusercontent.com/1572396/66722248-01767900-edd1-11e9-92cc-d40f9d348962.png)

Because I activate this option, I have the behaiviour I report, 

![imagen](https://user-images.githubusercontent.com/1572396/66722251-12bf8580-edd1-11e9-9c81-2a4cac48fe3b.png)

If I uncheck the the option, the terminal will not close, but the problems is it disconnects.

This happens to me with a fresh install.

Regarding my pac configs, it happens with a fresh installation and the normal local shell in a tab. By shrinking the whole window.

![imagen](https://user-images.githubusercontent.com/1572396/66722446-3b487f00-edd3-11e9-86b0-68c322a3caaa.png)

This are my environment variables. In case they help.

XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_CONFIG_DIRS=/etc/xdg/xdg-cinnamon:/etc/xdg
DBUS_STARTER_ADDRESS=unix:path=/run/user/1000/bus,guid=69a2bda598fc0f7b49e958805da33914
TILIX_ID=ebf3f48f-f90b-4695-ab9e-59ec100f7d6d
LANG=es_MX.UTF-8
DISPLAY=:0
XDG_VTNR=7
LOGNAME=hans
SHLVL=1
LANGUAGE=es_MX:es
PWD=/home/hans
MANDATORY_PATH=/usr/share/gconf/cinnamon.mandatory.path
XAUTHORITY=/home/hans/.Xauthority
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/hans
JOURNAL_STREAM=9:25393
GTK_IM_MODULE=xim
COLORTERM=truecolor
XDG_SESSION_ID=c2
DESKTOP_SESSION=cinnamon
IM_CONFIG_PHASE=1
XDG_SESSION_DESKTOP=cinnamon
GDMSESSION=cinnamon
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
QT_QPA_PLATFORMTHEME=qt5ct
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus,guid=69a2bda598fc0f7b49e958805da33914
VTE_VERSION=5202
DBUS_STARTER_BUS_TYPE=session
_=/usr/bin/printenv
GTK_OVERLAY_SCROLLING=0
QT4_IM_MODULE=xim
CLUTTER_IM_MODULE=xim
XDG_DATA_DIRS=/usr/share/cinnamon:/usr/share/gnome:/home/hans/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
SHELL=/bin/zsh
GDM_LANG=es_MX
XDG_SESSION_TYPE=x11
MANAGERPID=1069
QT_ACCESSIBILITY=1
GTK_MODULES=gail:atk-bridge
SESSION_MANAGER=local/hans-desktop:@/tmp/.ICE-unix/1090,unix/hans-desktop:/tmp/.ICE-unix/1090
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
PATH=/usr/lib/go/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
XDG_CURRENT_DESKTOP=X-Cinnamon
SSH_AGENT_PID=1187
HOME=/home/hans
USER=hans
XMODIFIERS=@im=none
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
XDG_SEAT=seat0
TERM=xterm-256color
OLDPWD=/home/hans
ZSH=/home/hans/.oh-my-zsh
PERL5LIB=/home/hans/Documentos/Microflow/Productos/Desarrollo/Perl/asbru-cm/lib/ex:/home/hans/Documentos/Microflow/Productos/Desarrollo/Perl/asbru-cm/lib
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:

**Comment by hanspr** [comment]
I do not want to mix issues, but maybe this behaviour is related to the problem above, and I would also like to confirm if you are able to replicate any of this, otherwise I might have something broken in my environment.

On e fresh install, I open a local terminal

![imagen](https://user-images.githubusercontent.com/1572396/66729411-e166aa00-ee10-11e9-92c4-42489d74a92d.png)

Everything ok,

Click to open a second terminal, and the first one disconnects.

![imagen](https://user-images.githubusercontent.com/1572396/66729490-62be3c80-ee11-11e9-9a23-cd3bd48634a3.png)


![imagen](https://user-images.githubusercontent.com/1572396/66729494-6a7de100-ee11-11e9-9e6c-2cc5c833920d.png)

**Comment by gfrenoy** [comment]
This is indeed very interesting !

And I don't see the same behavior on my machine and on the "stock" Mint 19.2 VM I use for testing:
![image](https://user-images.githubusercontent.com/981546/66784698-7b932480-eedb-11e9-981d-901e205f38a1.png)

Can you maybe run this in verbose mode to better understand why the first connection is disconnecting ?

And don't you have anything in your local machine's log files that would explain the disconnection ?

**Comment by hanspr** [comment]
Sorry for the delay I was answering the other post, in a way is good new, it means that is something in my computer and not Ásbru, that has me relived. I made a clean install of Mint 19 on my computer, but perhaps, some configuration files from my home directory must be creating some conflict.

Give me a few days, I will do the same install a clean mint in a virtual machine and check what is different from mine. I will not take your time with this. And when I find the solution I will leave the answer here in case someone else gets in the same trouble.

Thanks.

**Comment by hanspr** [comment]
One more question, how did you install in the virtual machine, git clone, or a realease.

I installed Ásbru in my machine using git clone, and then began executing cpanm to install any dependencies missing.

Just to know how to install in the virtual machine so I have a version that runs correctly and that I have something to compare with.

Thanks

**Comment by gfrenoy** [comment]
> One more question, how did you install in the virtual machine

https://virt-manager.org

**Comment by hanspr** [comment]
Case closed, it was some leftover on my home directory from previous mint version. Created a new home directory, moved all my files there without config files related to cinammon, gnome. And every thing is working perfect now.
