### ISSUE TITLE
libnet-proxy-perl dependency old and deprecated

### ISSUE THREAD

**Issue by figue** [asbru-cm/asbru-cm#218]
I've been testing gtk3 build and checking dependencies saw that libnet-proxy-perl remains there but for me Net::Proxy seems old and deprecated upstream

https://metacpan.org/release/Net-Proxy

Can be replaced to somewhere else?

**Comment by KlaasT** [comment]
Do you have any information where it states that the dependency is deprecated? I checked with the Debian repositories and even sid still seems to ship that package. Otherwise we would need to search for a replacement.

**Comment by figue** [comment]
![image](https://user-images.githubusercontent.com/3238330/66750170-0d734100-ee8c-11e9-9e23-937430f9b837.png)
http://matrix.cpantesters.org/?dist=Net-Proxy+0.13

**Comment by KlaasT** [comment]
As far as I can see it is not very easy to replace that library. I'm having a look on what could be done using LWP::UserAgent but I can't find a simple drop-in replacement for NET::Proxy.

**Comment by figue** [comment]
In Archlinux I couldn't build Net::Proxy. And, as reported in matrix, probably doesn't work either. I didn't tried in Debian or other distributions, could you confirm that proxy as is works or is broken? Personally, I use custom attributes in freerdp to workaround.

**Comment by KlaasT** [comment]
It is probably broken with modern Perl versions and if the dependency is missing.

**Comment by gfrenoy** [comment]
Ásbrú does not have any dependency to Net::Proxy anymore.
