### ISSUE TITLE
desktop file is not installed to correct location

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#22]
Though asbru-cm contains a proper .desktop file, it is not linked to '/usr/share/applications/'.
But this is necessary for the application to show up in the menu of desktop environments.

Most of the entries which are already there for other apps are no symlinks though, so it might be better to just move the file there instead of symlinking it.

**Comment by KlaasT** [comment]
In RC4 the .desktop file should be installed into the /usr/share/applications/ directory. Only a symlink is being placed into /usr/bin/ for the executable.

**Comment by gfrenoy** [comment]
Just tried RC4 on plain vanilla Ubuntu 17.04 and I see it in the application list:

![image](https://user-images.githubusercontent.com/981546/32995698-b38cddc6-cd78-11e7-89f8-33357ec24818.png)

**Comment by nomike** [comment]
I can confirm this with RC4.
I was on RC3 though. I don't know when RC4 was released but I did updates with "Software Updater" at least within the last 24 hours, if not even later.
Will try tomorrow with my work PC if it updates automatically.

**Comment by gfrenoy** [comment]
RC4 is fresh out the oven ;-)  It has been released yesterday evening ... Let us know if you see the desktop icon after an update.

**Comment by F3TTT** [comment]
I think I'm seeing this with v5.0.0 asbru-cm on Fedora27.  Which I realize was just released Monday.  I can start a separate issue if you like.

I'm quite excited you've taken on this project as the lack of a good SSH manager is one of the odder things to deal with in my move to linux from a windows laptop.  I'm a unix admin and it seems like this would have been one of the first things someone built.   
![screenshot from 2017-11-22 10-01-17](https://user-images.githubusercontent.com/7294320/33136962-3570b048-cf6c-11e7-8456-61b2fa44bbc6.png)

**Comment by gfrenoy** [comment]
Thanks for the feedback Dan, I don't see it either here...There must be something wrong in the Fedora spec file.  We'll fix that along with Nerijus' remarks in issue #24.

**Comment by gfrenoy** [comment]
See discussion on #24.  In the latest snapshot : desktop file is now correctly created in /usr/share/applications but it still contents buggy references...

**Comment by gfrenoy** [comment]
This is fixed now and available in our [5.0.0 release](https://github.com/asbru-cm/asbru-cm/releases/tag/5.0.0).
