### ISSUE TITLE
KDE Neon compatibility

### ISSUE THREAD

**Issue by mazzod** [asbru-cm/asbru-cm#220]
Hello,

I just want to ask if you can create a version for KDE Neon users. 

Thanks!

**Comment by gfrenoy** [comment]
As far as [I can read](https://en.wikipedia.org/wiki/KDE_neon), KDE Neon is based on Ubuntu so I believe you can install it using our Ubuntu packages, can't you ?

I did not try but it should be something like this:

```
wget https://packagecloud.io/install/repositories/asbru-cm/gtk3/script.deb.sh
chmod +x script.deb.sh
sudo os=ubuntu dist=bionic ./script.deb.sh
```

(where you'll want to change "dist" with your base distribution...)
(I put the gtk3 branch since this the latest one we're working one but you may want to try to main one as will if you want)

This is only a suggestion, hope you can find time to investigate this further and contribute to the project... Let us know if it works for you :-)

**Comment by mazzod** [comment]
HI @gfrenoy, thanks for your suggestions but unfortunately I can't install the program.
If I follow the instruction on the site this is the error that I have:

_X55A:~$ curl os=ubuntu dist=debian -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash       
Detected operating system as neon/bionic.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/asbru-cm_asbru-cm.list...curl: (22) The requested URL returned error: 404 


Unable to download repo config from: https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/config_file.list?os=neon&dist=bionic&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this._

If I follow your instruction I can download the script but if I try to launch it this is the error:

_Unfortunately, your operating system distribution and version are not supported by this script.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

Please email support@packagecloud.io and let us know if you run into any issues._

Am I missing something?

Thanks!

**Comment by gfrenoy** [comment]
>  curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash

Read the instructions again, you did not apply them properly...

**Comment by mazzod** [comment]
Hi @gfrenoy, what's wrong with the curl? I just copy/pasted it from the instructions written on Github.

Thanks!

**Comment by gfrenoy** [comment]
See my previous comment.

**Comment by KlaasT** [comment]
I've opened a case with packagecloud. Currently it is not possible to offer a KDE Neon repository. You would have to fiddle around with a supported Ubuntu repository.

**Comment by mazzod** [comment]
Got it, thanks. I proceed to close the issue.
