### ISSUE TITLE
[gtk3] gtkSocket: only works under X11

### ISSUE THREAD

**Issue by KlaasT** [asbru-cm/asbru-cm#226]
Something I have experienced today and we need to have a look at. This happens when opening a RDP session and having Debian Buster installed. I think Buster switched over to Wayland.

```
asbru-cm:20309): Gtk-WARNING **: 13:07:02.706: GtkSocket: only works under X11

(asbru-cm:20309): Gdk-WARNING **: 13:07:02.720: ../../../../../gdk/x11/gdkwindow-x11.c:5611 drawable is not a native X11 window
Speicherzugriffsfehler
```

**Comment by egmontkob** [comment]
I'm quite certain that Wayland doesn't allow to embed another window. You can either somehow force Ásbrú to use the X11 compatibility layer XWayland, or migrate to a library-based VNC solution, or just let VNC open in a separate window. See https://github.com/asbru-cm/asbru-cm/issues/199#issuecomment-539959763.

**Comment by gfrenoy** [comment]
Does the same kind of library exist for RDP ?

**Comment by KlaasT** [comment]
I didn't find a working library or a GTK widget for that. Only a feature request at GTK to implement the commandsets for Wayland.

**Comment by gfrenoy** [comment]
https://github.com/FreeRDP/FreeRDP ?  I see some packages [libfreerdp](https://packages.ubuntu.com/bionic/libfreerdp-core1.1) ...?  I guess the tricky part will be the Perl bindings :-/

**Comment by KlaasT** [comment]
For documentation: https://bugzilla.gnome.org/show_bug.cgi?id=721224

**Comment by egmontkob** [comment]
Oops, I mixed up RDP with VNC, silly me.

**Comment by KlaasT** [comment]
I found this command to override the backend used. However I don't know if this is actually working or wanted. I tried it myself locally and it doesn't seem to have any effect. Am I doing something wrong?

> gdk_set_allowed_backends("x11")

**Comment by KlaasT** [comment]
Wayland has a compatibility layer for X11 based applications called XWayland. This is installed by default (at least on Debian based systems). Adding a env GDK_BACKEND=x11 works for asbru-cm. The software won't benefit from the performance improvements in Wayland by this however should fix the widget issues we are having at the moment for now.
