### ISSUE TITLE
(pac_conn:22985): Gtk-WARNING 

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#227]
While opening a remote ssh terminal, I'm getting this:

(pac_conn:22985): Gtk-WARNING **: 18:55:57.806: Theme parsing error: gtk.css:3408:30: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(pac_conn:22985): Gtk-WARNING **: 18:55:57.806: Theme parsing error: gtk.css:3409:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be 
removed in a future version

And while opening a local ssh sessionI I get:

(pac_conn:24387): Gtk-WARNING **: 19:01:54.127: Theme parsing error: gtk.css:3408:30: The style property GtkButton:image-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version

(pac_conn:24387): Gtk-WARNING **: 19:01:54.127: Theme parsing error: gtk.css:3409:29: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version

This is using asbru-cm-6.0.0~1571259499-1.el7.noarch.rpm om RHEL 7.7.
Regards.

**Comment by gfrenoy** [comment]
It is written ```Theme parsing``` error so I would first suspect a problem with the theme you are using...

As a matter of fact, I don't see this kind of message on my environment.

Are you using the standard RHEL 7.7 theme ?  Which one is this ?  Do you have the opportunity to try with another theme ?

**Comment by popxunga** [comment]
Hi ...
Indeed... I confimr that the issue is related with some Mint themes available from EPEL7 repo.
Switched to some other RHEL 7.7 standard theme and issue is gone.
Thanks.

**Comment by yarons** [comment]
I'm experiencing the same thing but I'm using Manjaro with KDE so I'm not sure that changing the theme will work in my case.

**Comment by gfrenoy** [comment]
@yarons 

even in KDE, you're using some Gtk theme when starting Ásbrú (or any other Gtk based application).  In Manjaro, please check System settings > Application Style > GNOME/Gtk Application Style > GTK3 theme:

![image](https://user-images.githubusercontent.com/981546/74866194-beb24800-5352-11ea-93a7-d802e0ff291d.png)

If you select "Default" there, all Gtk-warning messages should disappear.

If you want to use another theme, please report the issue to the theme project / maintainer.

**Comment by yarons** [comment]
So cool, thank you for enlightening me. :)
