### ISSUE TITLE
Reverse button order to "Cancel" "OK"?

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#229]
Confirmation dialogs of Ásbrú place the `OK` button first (left), followed by `Cancel`.

I think most software on Linux use the opposite order.

[GNOME HIG](https://developer.gnome.org/hig/stable/dialogs.html.en) says to use `Cancel` `OK`. While Ásbrú isn't a GNOME software and doesn't follow this HIG in many aspects, still, it uses GTK and thus looks somewhat similar to many GNOME software.

I tried now Tilix, Xfce4-terminal, Guake, Konsole; attempted to close them while an application was running. All of them followed this order. (For Konsole it might depend on some global KDE setting.)

macOS, Android also prefer this order. Probably Windows is the only big one with `OK` `Cancel`.

Here's a [random nice article](https://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/) arguing why it's better to have `Cancel` `OK`. (Sure I could find an opposite article as well. :)) Here are [many interesting answers pro and con](https://ux.stackexchange.com/q/1072) ([my favorite](https://ux.stackexchange.com/a/63239)). But after all, probably it's consistency across apps that matters the most.

With that in mind, I'd like to propose to swap the order throughout Ásbrú (including `Close without saving` `Save and close` in Preferences). What do you think? Vote by thumbs up/down on this post.

While at it, as per GNOME HIG, it might be a good idea to rename the `OK` button to a more specific one wherever makes sense. E.g. `Delete node foo?` should offer `Cancel` `Delete` rather than `Cancel` `OK`. Furthermore, you might also take HIG's advice not to set `OK` as the default action for destructive tasks, such as deleting stuff.

**Comment by beliys** [comment]
Maybe it’s worth making it optional, so that if someone were comfortable with the old version, he could return it as he was comfortable. I think it should not be difficult to implement.

**Comment by gfrenoy** [comment]
Making it optional does not look that trivial to me.  Consistency with the other Gnome applications should not make that change that confusing so let's try it and see how much (or not) it changes our way of using Ásbrú.

For the other points in that same issue (meaningful name, no default, ...) ; do we have specific examples ?  Or even a list of what needs to be changed ?

**Comment by KlaasT** [comment]
I think we should keep this open and at least consider moving to a standard Gnome layout.

**Comment by gfrenoy** [comment]
Shouldn't it be dedicated issue or even a project ?  I mean: the title of this issue is very specific and has been addressed...

**Comment by KlaasT** [comment]
Issue from the initial post has already been worked on. For further actions new issues should be created. Closing #229
