### ISSUE TITLE
Draw text on the banner as real text

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#234]
Magnify e.g. the "Preferences" word in the top banner of the Preferences dialog.

It contains a few brighter blue pixels just around the letter, instead of pixels that match the darker blue background. It's probably the result of cutting out the "PAC" word that used to be there and shifting the text.

For a slightly nicer look, and much nicer technical approach (e.g. internationalization – if you're planning to have that one day), the text could be removed from the image and rendered using a GtkLabel.

GtkOverlay is designed to place a widget over another, but I found that it's not necessary. On top of #233, you can just simply add this new GtkLabel as the second child of GtkLayout, with Packing -> X = 80-ish, Y = 0, Common -> Width request disabled, Height request = 50 (again, not nice to have to repeat the image's height, but whatever), and maybe General -> Attributes -> Scale = 2 and Foreground = (pick black).

Ideally I would even discouple the icon from the background, make the icon a 50x50 pixmap with alpha instead of the green-ish background, I just have no idea how to create it :) That way you could have just one banner image instead of five, or make it scale according to the window width, or just more easily replace.

These are just random ideas, you decide how much of these you address, or just leave it as-is even with the cyan-ish pixel artifacts. :)

**Comment by gfrenoy** [comment]
Thanks for the suggestion !  I'm closing this one, it is actually tackled in #233.
