### ISSUE TITLE
not found asbru-cm deb from repository

### ISSUE THREAD

**Issue by netroby** [asbru-cm/asbru-cm#237]
Hello, i set up repository as the master document said. but install not found the asbru-cm package at all
```
min ~ # ./up.sh 
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://packages.microsoft.com/repos/vscode stable InRelease                           
Hit:3 http://dl.google.com/linux/chrome/deb stable Release                                  
Hit:6 http://mirrors.ustc.edu.cn/ubuntu eoan InRelease                                      
Hit:7 http://mirrors.ustc.edu.cn/ubuntu eoan-updates InRelease
Hit:5 https://packagecloud.io/asbru-cm/asbru-cm/ubuntu eoan InRelease
Hit:8 http://mirrors.ustc.edu.cn/ubuntu eoan-backports InRelease
Hit:9 http://mirrors.ustc.edu.cn/ubuntu eoan-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
min ~ # apt install asbru-cm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package asbru-cm

```

**Comment by KlaasT** [comment]
The eoan package is currently not released yet finally. You can try the snapshots repository or the gtk3 one. However they are considered unstable yet.

In a few days we will release the new .deb packages for eoan on the main repository.

**Comment by gfrenoy** [comment]
See https://github.com/asbru-cm/asbru-cm/wiki/Installation-on-Ubuntu#snapshot-release to install 5.2.1 ; not yet released but can be considered as "nearly" stable.

You may also want to consider https://github.com/asbru-cm/asbru-cm/tree/gtk3#testing-the-gtk3-branch ; that would help the project to have more testers...

**Comment by gfrenoy** [comment]
Just tested v5.2.1 that we just released and it is now working fine on Ubuntu Eoan.

Feel free to re-open the issue if this would not be the case for you.

**Comment by Masteratom** [comment]
Hi :) 
I can't install asbru-cm:
`apt update
Stary:1 http://security.debian.org/debian-security bookworm-security InRelease
Stary:2 http://deb.debian.org/debian bookworm InRelease                                                                               
Stary:3 http://deb.debian.org/debian bookworm-updates InRelease                                                                       
Stary:4 https://packages.microsoft.com/repos/ms-teams stable InRelease                                                                
Pobieranie:5 https://dl.cloudsmith.io/public/asbru-cm/release/deb/debian bookworm InRelease [4 859 B]
Pobrano 4 859 B w 2s (3 120 B/s)         
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności... Gotowe
Odczyt informacji o stanie... Gotowe   
All packages are up to date.

apt install asbru-cm
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności... Gotowe
Odczyt informacji o stanie... Gotowe   
E: Nie udało się odnaleźć pakietu asbru-cm

`
