### ISSUE TITLE
Latest asbru-cm 6.0 builds not working on RHEL 7.7

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#240]
All the latest builds after asbru-cm-6.0.0~1571259499-1 are failing to run properly in RHEL 7.7.

Launched asbru-cm-6.0.0~1571670781-1.el7 from a terminal
When I try to open an ssh session to a remote host I get the following error message:

**Can't locate Glib/IO.pm in @INC (@INC contains: /usr/share/asbru-cm/lib /usr/share/asbru-cm/ex /usr/share/asbru-cm/edit /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/asbru-cm/lib/pac_conn line 36.
BEGIN failed--compilation aborted at /usr/share/asbru-cm/lib/pac_conn line 36.**

In the terminal from where asbru-cm was launched I see:
**Argument "1/8" isn't numeric in numeric gt (>) at /usr/share/asbru-cm/lib/PACMain.pm line 3092.**

In both packages (asbru-cm-6.0.0~1571259499-1 and asbru-cm-6.0.0~1571670781-1) the Glib/IO.pm file is provided in the same exact location:
-rw-r--r--. 1 root root 244 Out 21 20:29 /usr/share/asbru-cm/lib/ex/Glib/IO.pm

In addtion I had to build two new pre-required packages as well from rawhide sources on Koji:
perl-Glib-Object-Introspection and perl-Glib

Any ideas ?
Thanks

**Comment by nerijus** [comment]
The same problem on Fedora 30:
```Can't locate Glib/IO.pm in @INC (you may need to install the Glib::IO module) (@INC contains: /usr/share/asbru-cm/lib /usr/share/asbru-cm/ex /usr/share/asbru-cm/edit /usr/local/lib64/perl5/5.30 /usr/local/share/perl5/5.30 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/share/asbru-cm/lib/pac_conn line 36.
BEGIN failed--compilation aborted at /usr/share/asbru-cm/lib/pac_conn line 36.```
I noticed that @INC contains: ... /usr/share/asbru-cm/ex, but there is no such directory. The fix was:
```cd /usr/share/asbru-cm
ln -s lib/ex```

**Comment by popxunga** [comment]
Thanks for the workaround ....
I've been comparing the pac_conn module line 36 (along others) and it suffered some modifications when compared with the same module on asbru-cm-6.0.0~1571259499-1.
Those modifications caused the present error and so I guess they need correction.

**Comment by gfrenoy** [comment]
Thanks both for your suggestions.  I made a few changes in the [rpm spec file](https://github.com/asbru-cm/asbru-cm/blob/master/dist/rpm/asbru.spec) ; this should fix the reported issue.

Let us know if it works for you.

**Comment by nerijus** [comment]
Yes, it works now, thanks! This bug can be closed.

**Comment by popxunga** [comment]
Thanks @gfrenoy ...
Just tested with the latest automated build (asbru-cm-6.0.0~1572331898-1.el7) and I confirm that this issue is now fixed.
