### ISSUE TITLE
gtk3 utf8 encoding terminal names

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#242]
Terminal names allow utf8 strings

![imagen](https://user-images.githubusercontent.com/1572396/67255484-eac2c880-f447-11e9-8d85-cfae947c8a55.png)

But at the moment to connect the name is shown in the terminal as information of the connection status and it shows wrong characters

![imagen](https://user-images.githubusercontent.com/1572396/67255514-09c15a80-f448-11e9-8570-4783000057e5.png)

**Comment by egmontkob** [comment]
Nice catch! :)

**Comment by KlaasT** [comment]
Closed #242
