### ISSUE TITLE
Warnings when renaming a connection

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#243]
Rename a connection. As you type the new name, on each keypress this warning is printed:

    Use of uninitialized value $parent_name in string eq at [...]/asbru-cm/lib/PACUtils.pm line 1613.

Same with gtk2 and gtk3 (the shown line number matches current gtk3 head).

**Comment by gfrenoy** [comment]
How do you rename the connection ?

I tried : select the connection in the left tree, right-click > Rename Connection (or F2) and then changed the name but I don't see that message (using the latest gtk3 branch).

**Comment by egmontkob** [comment]
That's what I do, too. Or the 4th button in the upper left.

**Comment by egmontkob** [comment]
Happens with toplevel connections only, not ones under a group (and not with a topmost group name either).

**Comment by gfrenoy** [comment]
Thanks for the confirmation !  I realized all my connections are inside a group ... If I create a connection at the root level, I can see the same issue :)

Should be fixed now.

**Comment by egmontkob** [comment]
Well, this was quick :D
