### ISSUE TITLE
gtk3 Favourites

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#245]
If you group your terminals and decide to name them with the same name (in different groups). For example : "development".

![imagen](https://user-images.githubusercontent.com/1572396/67412838-a6d5dd80-f585-11e9-9e47-fc61bb039f67.png)

And then you add those terminals to your Favourites list, they are only listed by name and then you do not know which one is which

![imagen](https://user-images.githubusercontent.com/1572396/67412936-d8e73f80-f585-11e9-9cb0-fa4632f21a99.png)

The options I have implemented are:

1) Prepending the group name to each name

![imagen](https://user-images.githubusercontent.com/1572396/67412971-e8668880-f585-11e9-9b6d-1a35f1237d16.png)

2) Appending the host ip afterwards

![imagen](https://user-images.githubusercontent.com/1572396/67413016-02a06680-f586-11e9-9a80-813aae8801f1.png)

3) I could mix both, to Prepend the group and if the terminal has no group, append the ip

What solution would you prefer.?

**Comment by beliys** [comment]
1 solution
