### ISSUE TITLE
Keepalives

### ISSUE THREAD

**Issue by mooky31** [asbru-cm/asbru-cm#246]
Hello,

First of all many thanks for continuing the great work that has been done on PAC manager.

I work in an environment where my sessions are regularly disconnected by firewalls I go through.
PuTTY has two nice options, null packets and SO_KEEPALIVE, which prevents this from happening.

Would it be possible to implement something like this on asbru please ?

Best regards

**Comment by TheReptile** [comment]
Since asbru just spawns a ssh session, you could use this in your ~/.ssh/config ?
```
Host *
  ServerAliveInterval 30
```

**Comment by mooky31** [comment]
I haven't thought of that, but that's a very nice solution.
Many thanks for the advice.

**Comment by gfrenoy** [comment]
On additional note, you can set this option as an "advanced SSH options":
![image](https://user-images.githubusercontent.com/981546/67602326-a2244b80-f776-11e9-9c67-439d80f4ed30.png)
