### ISSUE TITLE
Disable ssh's X forwarding by default

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#247]
`'SSH' Options` -> `Forward X` (which translates to the `ssh -X` command) is enabled by default when defining a new connection.

This means that if the remote server is compromised, the attacker gains full access to the graphical environment of the local user. Please see the ssh manpage and presumably tons of other resources for details.

I think this option should be disabled by default.

**Comment by beliys** [comment]
I agree

**Comment by gfrenoy** [comment]
I changed the default in the gtk3 branch.  I also changed the default for compression since this is what I'm doing for all my connections ...
