### ISSUE TITLE
asbru-cm gtk3 rpm missing file

### ISSUE THREAD

**Issue by nerijus** [asbru-cm/asbru-cm#250]
On Fedora 30 I upgraded from asbru-cm.noarch 5.2.1-1.fc30 to asbru-cm.noarch 6.0.0~1572111993-1.fc30, trying to start it:
```$ asbru-cm
INFO: Ásbrú started (asbru-cm) with PID 66440
INFO: Using config directory '/home/nerijus/.config/pac'
INFO: Used config file '/home/nerijus/.config/pac/pac.nfreeze'
<broken file>:1:0Failed to import: Error opening file /usr/share/asbru-cm/res/asbru.css: No such file or directory at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67.
```

**Comment by nerijus** [comment]
Getting the file from git and putting it manually works.

**Comment by gfrenoy** [comment]
Thanks for reporting the issue @nerijus !  The missing file should now be in the latest 6.0.0 build.

Let us know if it works for you.

**Comment by nerijus** [comment]
It works, thanks!
