### ISSUE TITLE
[gtk3] Faulty link in license dialog

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#251]
Open About ("star" icon) -> License.

At the beginning of the license text, there's a faulty URL pointing to `http://asbru-cm.net)` with a closing parenthesis.

The text is defined at PACMain.pm, `_showAboutWindow`. There's no explicit URL markup here, GTK does some magic, and arguably does it wrong.

As a workaround, you could change to enclose the URL within `<` `>` instead of `(` `)`, as done below for the GPL text, it's correctly autodetected then.

Or you could just omit this URL altogether, it's already there on the main About page.

Note: GTK2 didn't automatically linkify this at all, only the URL inside `<` `>`.

**Comment by gfrenoy** [comment]
Sharp :eyes: !  Thanks, I made the change.
