### ISSUE TITLE
Removing a local/remote command/macro might remove another one

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#252]
Go to Preferences -> Local or Remote Commands, or Edit Connection -> Remote or Local macros.

(Notice the inconsistent order of the two tabs in these two windows.)

Click Add. Type something into Command. Click Add again. Leave this new one empty.

Click on Delete in the new one's row. Both entries are removed.

Start over.

Click Add. Type something. Click Add again. Type something to its Command, too. Click Add. Now the topmost (newest one) is empty, the other two are not.

Click on Delete in the middle one. Only this entry survives, the other two get deleted.

Try other weird combos too, including manually clearing one or more text fields before clicking on a Delete.

Looks to me that first the empty entries are all deleted, shifting up the remaining ones if necessary, and then the one which moved to the row of the clicked Delete button is removed.

**Comment by gfrenoy** [comment]
Thanks for reporting this strange behavior !

If I get it correctly, when reloading the configuring before deleting the entry, it was filtering it so the positions were not correct any more ... So it was not deleting the right entry.

Should be fixed now.
