### ISSUE TITLE
gtk3 Minimalist Main Window

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#262]
@gfrenoy

Hi, Gaëtan:

I would like to see if you (or any from the group) could help me with this implementation in case you consider it would be good for the project.

I know, must people like tabs, I'm the total opposite to that, I like windows. So, for window users, the Main Asbru Window is large and takes a lot of unnecessary space.

I have implemented this layout, that is very small and I would like to show it as close to the tray icon when it shows. It has all the necessary functions I need and the rest can be easily accessible with right click or the menu from the tray (like preferences)

![imagen](https://user-images.githubusercontent.com/1572396/68176738-a9eca880-ff4b-11e9-98d8-70b7c73311cb.png)

The help I need is to edit the asbru.glade and create a new option like "presentation minimal" (in the  "Look and Feel" tab), or if you think the concept could be grown to have 2 or more available layouts. Then add a combo.

![imagen](https://user-images.githubusercontent.com/1572396/68177048-b6bdcc00-ff4c-11e9-9693-2a55a8de794a.png)

Al least we could have a: "Traditional" or "Tabbed" and "Minimal" layout.

With this option I could insert the necessary "ifs" to have both layouts available. And if there is a request for another layout there would be the option to try to implement it.

Once the option is there I would implement the saving, reading and handle the change. I guess it could be possible to implement it without a need to restart, is basically show and hide buttons and attach to one or other container.

Thanks.

**Comment by gfrenoy** [comment]
Interesting :)  I personally never really get used to that "GIMP"-like layout but I perfectly understand this can be a very good way of working.

But as there are already a lot of options, this might probably add even more confusion so we might need to think a bit if we cannot merge some of these options together...

Especially that "Put Terminal TABS in Main Window" section might be the same as the "Tabbed Layout", isn't it ?

**Comment by hanspr** [comment]
> Especially that "Put Terminal TABS in Main Window" section might be the same as the "Tabbed Layout", isn't it ?

Not really, there is a difference.

"Put Terminal TABS in Main Window" instructs asbru do what you think

![imagen](https://user-images.githubusercontent.com/1572396/68232217-3a65d000-ffc2-11e9-93b0-568512c1c842.png)

but if you uncheck it

The terminals begin to tab to the first terminal created or to an external tab window.

![imagen](https://user-images.githubusercontent.com/1572396/68232283-65502400-ffc2-11e9-9697-85abb67885e3.png)


Which would work perfect with a minimal layout because you still get the tabs, but not attached to the main window.

Allowing this

![imagen](https://user-images.githubusercontent.com/1572396/68232446-b19b6400-ffc2-11e9-8f01-6f477ebb3dff.png)


So I would not left out tab users from enjoying a minimal main window

**Comment by B1tl0rd** [comment]
It works fine, although I think it should come by default, the traditional and non-compact mode. By default it starts minimized on the taskbar and in compact mode. Is this the desired behavior?

This happens using an already previous configuration.

Thanks excellent job. everyday better

**Comment by gfrenoy** [comment]
> By default it starts minimized on the taskbar and in compact mode. Is this the desired behavior?

Mmm?  No ...

If the "layout" setting is not set in your configuration file, it should be set to ```Traditional``` ... This is also the same for a brand new configuration.

**Comment by B1tl0rd** [comment]
Another more aesthetic detail is that in lower resolution screens "1366x768" the lower part is cut, tampando part of the icons. It would be nice to be able to redeem a little less.

![image](https://user-images.githubusercontent.com/12401985/69906996-597e3480-13ab-11ea-889b-900de490e6a0.png)

**Comment by B1tl0rd** [comment]
There is an error with the connection list, using the taskbar icon

![image](https://user-images.githubusercontent.com/12401985/69907195-63099b80-13af-11ea-883e-4dc84e166c89.png)

**Comment by hanspr** [comment]
@B1tl0rd 

On reference at your questions

* Traditional comes by default when you create the first time, that is what I see. If not, please open a new issue and document how to reproduce.
* Compact mode is set to be minimized, it works like a menu, so it is by design.
* Issue about size of preference window is not related or caused by this, so to be able to give a proper follow up, please open a new issue. I gave it a quick check and the glade file has to be redesigned, the Terminal , Look and feel tab, is the one that is packed with too much data and forces that minimum size.
* Groups menus, I already sent the PR, guess some merge caused a problem here, the groups naming was tripled.

I will close this thread because it is not a good idea to mix so many issues that are not related to each other.

**Comment by hanspr** [comment]
Closing

**Comment by gfrenoy** [comment]
@B1tl0rd PR merged, thanks for your quick feedback !
