### ISSUE TITLE
bulk editions

### ISSUE THREAD

**Issue by B1tl0rd** [asbru-cm/asbru-cm#263]
Mass edition
Friends there is some possibility to make multiple editions to several nodes. for example the ssh options fields
if not, I planned to manually edit the pac.yml file

![image](https://user-images.githubusercontent.com/12401985/68241297-30a59200-ffed-11e9-9db0-117362027f04.png)

**Comment by egmontkob** [comment]
There is a bulk editing feature. Highlight the desired connections in the left with Shift+click or Ctrl+click. Then click on Edit, or right-click -> Bulk Edit, or Alt+E.

It is, however, limited to a tiny set of the options, probably not what you're looking for.

**Comment by B1tl0rd** [comment]
OK. if I knew that functionality, but I had the doubt if there was another way from the interface ..
Thank you
