### ISSUE TITLE
Find option shows lots of weird characters

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#266]
**Describe the bug**
In a shell, right click and select "Find... ", Contents of current log shows quite a lot of not readable characters, that makes the ability to find quite difficult.

**To Reproduce**
1. Go to any open session
2. Right click and select "Find... "
3. See the weird characters

**Expected behavior**
The same content I see in the shell output

**Screenshots**
https://ibb.co/BBLd778

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 18.04

**Comment by gfrenoy** [comment]
Thanks for reporting the issue @ferent and thanks to @hanspr for the fix !

That "Find..." option looks way better now :)

**Comment by ferent** [comment]
Playing a bit with the find improvement, it looks really good now, but there is an small bug:
when hitting the search for second time (either searching for the same string, or a different one) the second time always return 0 results. Next click works ok, but the following doesn't.
