### ISSUE TITLE
Move all encoding to utf8

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#268]
Review all the code and move all encoding and decoding to utf8. At this moment the code uses in many points ISO-8859-1.

This will be a large review so I will begin when pending PRs are merged, to have a clear starting point.

**Comment by gfrenoy** [comment]
Very good yes :)

Btw, I've noticed that since you added ```use utf8;``` in

**Comment by egmontkob** [comment]
If the string "Ásbrú" is replaced by a string that doesn't fit Latin-1 then the accents are printed correctly, however, it's accompanied by a "Wide character in print" warning.

The solution seems to be a `binmode` call, or something similar, as per https://stackoverflow.com/q/15210532.

Ideally, instead of a `binmode ..., ":utf8"` as shown there, it should be a `binmode ..., <whatever-encoding-the-locale-says>;`, but I guess it's safe to ignore that, everyone should be using an UTF-8 locale.

**Comment by hanspr** [comment]
Yes, in part is that. That handles the output, but still we have to unify the input, and that everyone encodes the perl files in utf8 in there editors.

The other problem is that some of those messages come across a piped communication that has to be encoded and decoded properly, some go to sessions files that are written in Latin1, some go to the screen, some go to the terminals, some go to the gtk labels. 

And right now is all tied to "Latin1" or mixed, if you apply that solution in one part but not in all others the wide characters will begin showing up somewhere else, it has to be solved by unifying the encoding in all the files.

And the main reason to move away from Latin1 is, that no programmer from a non Latin alphabet will be able to use properly the application. Labels will be garbled, files could get corrupted, messages will show up with wide characters, and crashes.

**Comment by egmontkob** [comment]
I just wanted to present a quick fix to the problem Gaëtan pointed out. I know it's not the end of the story :-) You are perfectly right with your goal and insight on this topic, thanks for working on this!

**Comment by gfrenoy** [comment]
Another thing to look at about UTF8, accents are not correctly shown anymore in the "about" box:

![image](https://user-images.githubusercontent.com/981546/68534569-47721e80-0336-11ea-82de-d0d02ae62395.png)

**Comment by hanspr** [comment]
Yes, I will.

It will be a very long review and rewrite of stuff, as I commented to @egmontkob , this will hit in many places.

**Comment by gfrenoy** [comment]
Thanks :)

**Comment by gfrenoy** [comment]
Fantastic work @hanspr ; this is a great step forward !

A huge :+1: !
