### ISSUE TITLE
Terminals not closing on el7

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#269]
I've tested all Asbru 6.x packages built after 6.0.0\~1572331898-1.el7 and the terminals do not close upon logoff the session. So from this point of view, the 6.0.0\~1572331898-1 package is last one that works properly on el7.

**Comment by gfrenoy** [comment]
Can you check #259 and see if the fix works for you ?

If you start Ásbrú from the command line, do you see any error message ?

Which version of VTE are you using ?

**Comment by popxunga** [comment]
This is what I get in the command line:

[~]$ asbru-cm
INFO: Ásbrú started (asbru-cm) with PID 16989
INFO: Using config directory '/home/xxxxxxxx/.config/pac'
INFO: Used config file '/home/xxxxxxxx/.config/pac/pac.nfreeze'
INFO: Using Gnome tray icon
Argument "1/8" isn't numeric in numeric gt (>) at
/usr/share/asbru-cm/lib/PACMain.pm line 3087.
*** unhandled exception in callback:
***   need an array ref to convert to GArray at
/usr/share/asbru-cm/lib/PACUtils.pm line 3854.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 318.

These are the *vte* packages in my system:
[~]$ rpm -qa | grep -i vte
vte291-0.52.2-2.el7.x86_64
vte-0.28.2-10.el7.x86_64
perl-Gnome2-Vte-0.11-7.el7.x86_64
vte-profile-0.52.2-2.el7.x86_64
vte-devel-0.28.2-10.el7.x86_64
vte3-0.36.5-1.el7.x86_64

Maybe I'm doing something wrong, but replacing the PACUtils.pm (got it raw
format from here
https://github.com/asbru-cm/asbru-cm/blob/611f4c94f0a385f97c0625edcc6d27bd81338ae3/lib/PACUtils.pm)
causes the following error of asbru-cm:
INFO: Ásbrú started (asbru-cm) with PID 19186
INFO: Using config directory '/home/xxxxxxxx/.config/pac'
INFO: Used config file '/home/xxxxxxxx/.config/pac/pac.nfreeze'
Wide character in subroutine entry at
/usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67.
Failed to open file “/usr/bin/res/asbru_method_rdesktop.jpg”: No such file
or directory at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm
line 67.

Gaëtan Frenoy <notifications@github.com> escreveu no dia sexta, 8/11/2019
à(s) 19:16:

**Comment by gfrenoy** [comment]
So the problem very similar as #219 

For your distro, you apparently have VTE 0.52.2 but you'll need to use ```$vte->feed_child(\@arr);``` instead of  ```$vte->feed_child($str, $b);```.  See #193.  It has to do with a special patch on v0.52 for Ubuntu, I would guess.

Not sure how we can find that out automatically ?!   @egmontkob would you have a suggestion ?  Can we find out with introspection how many parameters we have for ```feed_child``` ?

@popxunga In the meantime, do not replace the whole file but simply replace ```54``` by ```52``` on line 3845 of ```PACUtils.pm``` to see if fixes the issue for you ?

**Comment by egmontkob** [comment]
Can you do a try-catch?

**Comment by gfrenoy** [comment]
try-catch "a la" perl you mean ;p  Thanks for the suggestion, I did a change, looks to wok fine for me.

@popxunga in few minutes, a new package will be ready, will you let use know if it work on your EL7 version as well ?

**Comment by popxunga** [comment]
Sure I will... As soon I get to my home :-)

A sábado, 9/11/2019, 14:19, Gaëtan Frenoy <notifications@github.com>
escreveu:

**Comment by popxunga** [comment]
With the latest build of asbru-cm-6.0.0\~1573310194-1.el7 terminals are now closing properly on EL7.
However in the terminal I see the following messages:
[\~]$ INFO: Ásbrú started (asbru-cm) with PID 3039
INFO: Using config directory '/home/xxxxxxxx/.config/pac'
INFO: Used config file '/home/xxxxxxxx/.config/pac/pac.nfreeze'
INFO: Using Gnome tray icon
Argument "1/8" isn't numeric in numeric gt (>) at /usr/share/asbru-cm/lib/PACMain.pm line 3087.
*** Vte::Terminal::feed_child: passed too many parameters (expected 2, got 3); ignoring excess at /usr/share/asbru-cm/lib/PACUtils.pm line 3855.
INFO: Finishing (asbru-cm) with pid 3039

[\~]$ INFO: Finished asbru-cm (PID:3039)...

**Comment by egmontkob** [comment]
Would a local `no warnings` fix it?

**Comment by popxunga** [comment]
In this case, I do not see any advantage in hiding the warnings.
Is the warning above trow because my VTE version doesn't allow more than 2 parameters or is the code passing excessive parameters ?

**Comment by egmontkob** [comment]
VTE 0.52 takes three parameters in Ubuntu and derivatives, two parameters in every other distribution. We cannot know in advance which version will work. So we have to try one after the other, and it's desireable to hide the warning if the first one we try (whichever that is) fails.

Another approach is to require VTE >= 0.54, or only support distributions that don't f.ck it up and blame it on Ubuntu (which is not a user-friendly approach and is apparently not what Gaëtan would happily do).

**Comment by popxunga** [comment]
In my system the **/usr/bin/vte** binary is provided by this package **vte-devel-0.28.2-10.el7** which I got via EPEL 7. 
As you can see for [VTE on koji](https://apps.fedoraproject.org/packages/vte) they are still on 0.28.2 even for the latest Fedora versions.

**Comment by egmontkob** [comment]
The vte _binary_ is irrelevant, the vte _library_ matters. 0.28 is the old one, used by Asbru 5.2 (GTK 2). The new 6.0 beta (GTK 3) branch uses the package vte291, you probably have version 0.52 or similar.

**Comment by popxunga** [comment]
If that is is the case, then I'm using this one vte291-0.52.2-2.el7.

**Comment by gfrenoy** [comment]
I've added something that should prevent the warning message to be shown.  Let us know if it works on EL7.

**Comment by popxunga** [comment]
Tested with asbru-cm-6.0.0\~1573310194 and the warning message about the # of parameters is gone. Just this one remains:
Argument "1/8" isn't numeric in numeric gt (>) at /usr/share/asbru-cm/lib/PACMain.pm line 3087.

Thanks !

**Comment by gfrenoy** [comment]
> Argument "1/8" isn't numeric in numeric gt (>) at /usr/share/asbru-cm/lib/PACMain.pm line 3087.

Does this also happens when you close a connection ?  It should be when you start a new terminal.

This corresponds to this line:

```
if (@new_terminals && scalar(%RUNNING) > 1) {
```

What can go wrong with ```scalar(%RUNNING)``` ... Mmmm?  @hanspr, do you an idea ?

**Comment by popxunga** [comment]
I confirm ... it happens each time a new terminal is opened. 

INFO: Using Gnome tray icon
Argument "1/8" isn't numeric in numeric gt (>) at /usr/share/asbru-cm/lib/PACMain.pm line 3087.
Argument "2/8" isn't numeric in numeric gt (>) at /usr/share/asbru-cm/lib/PACMain.pm line 3087.

No error message is returned when I close the terminals.

**Comment by hanspr** [comment]
I just pulled the latest gtk3 branch and the lines do not match with the code I see, could you show me the line so I can find it

![imagen](https://user-images.githubusercontent.com/1572396/68535019-42df4300-0301-11ea-9706-f2ae170e0e09.png)


We will have to change the if from scaler(..) to something else but I need to find the line

**Comment by egmontkob** [comment]
I guess you have local modifications, don't you? I do have a scalar() in the said line: https://github.com/asbru-cm/asbru-cm/blob/b7730128c5eb40cbda822f7d0de89d7bd3aebb00/lib/PACMain.pm#L3087

**Comment by hanspr** [comment]
try : `if (@new_terminals && scalar(keys %RUNNING) > 1) {`

**Comment by popxunga** [comment]
Just tested the modification suggested above and it solves the previously reported error messages on PACMain.pm line 3087.

**Comment by gfrenoy** [comment]
Thanks @hanspr !

The longer answer can be found here: https://perldoc.perl.org/perldata.html.

> If you evaluate a hash in scalar context, (...).  Prior to Perl 5.25 the value returned was a string consisting of the number of used buckets and the number of allocated buckets, separated by a slash.

So we can close this issue I guess !  Thanks everybody for your help on this.

@popxunga I tried on a CentOS7 VM but still could not find out all the dependencies to make Ásbrú running there.  Would you mind explaining in #60 how you make it working for you ?
