### ISSUE TITLE
[gtk3] Remove termcap

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#271]
Remove `res/termcap`, and its install instruction from `dist/rpm/asbru.spec`.

The file apparently contains terminal descriptions as of 1999.

VTE itself no longer uses termcap or terminfo.

Applications running inside the terminal use the `xterm-256color` description (becase this is VTE's default `$TERM`) shipped by ncurses, there's no such definition in this file.

**Comment by gfrenoy** [comment]
Looks like archaeology what we are doing ;-p

Thanks for pointing this out.
