### ISSUE TITLE
gtk3 version not running on debian 10, xfce4

### ISSUE THREAD

**Issue by The-Incubus** [asbru-cm/asbru-cm#272]
**gtk3 version not starting on debian 10 and xfce4**
After installing asbru from the official repository as explained in the documentation, it doesn't start.

**To Reproduce**
1. Install debian 10 stable
2. Install xfce4
3. Follow documentation to install asbru, gtk3 branch
4. Try to start asbru

**Expected behavior**
Asbru running

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 10, stable
 - Desktop Environment: xfce4
 - Asbru Version: 6.0.0

**Additional context**
Fresh installation, no previous configuration present.
Error show when launching from terminal:
```
Typelib file for namespace 'Vte', version '2.91' not found at /usr/lib/x86_64-linux-gnu/perl5/5.28/Glib/Object/Introspection.pm line 108.
BEGIN failed--compilation aborted at /opt/asbru/lib/PACTerminal.pm line 54.
Compilation failed in require at /opt/asbru/lib/PACMain.pm line 59.
BEGIN failed--compilation aborted at /opt/asbru/lib/PACMain.pm line 59.
Compilation failed in require at /usr/bin/asbru-cm line 84.
BEGIN failed--compilation aborted at /usr/bin/asbru-cm line 84.

```

**Comment by gfrenoy** [comment]
Do you have package ```gir1.2-vte-2.91``` installed ?

**Comment by egmontkob** [comment]
It's not listed in the `Depends` field for `dist/deb/debian/control`.

Similarly, `Gio` and `GdkX11` (their `gir` package) are also missing.

Maybe from the RPM spec file too, I haven't checked that.

**Comment by gfrenoy** [comment]
I tested on a VM with a fresh Debian 10.1 xfce ; only ```gir1.2-vte-2.91``` is missing.

I also identified at least ```gir1.2-glib-2.0``` to add (for ```Gio```) but it's a dependency of Gtk3.
Did not find anything specific for ```GdkX11```.

For RPM, I only found [perl-Glib-Object-Introspection)(https://pkgs.org/download/perl-Glib-Object-Introspection) that is a dependency of Gtk3 as well.

So let's only add ```gir1.2-vte-2.91``` for now.

@The-Incubus I just made the commit now, please update your package when it will be built (probably within 20 minutes).

**Comment by egmontkob** [comment]
> I also identified at least gir1.2-glib-2.0 to add (for Gio) but it's a dependency of Gtk3.

Really? I don't think so. (Maybe it has changed across Ubuntu versions.)

Anyway, it's always a good practice to explicitly list everything that you directly require.

**Comment by The-Incubus** [comment]
I'm happy to say the gtk3 version is now running also on my debian 10.

Thank you for your help.

**Comment by gfrenoy** [comment]
> Really? I don't think so. (Maybe it has changed across Ubuntu versions.)

Well, not Gtk3 directly.  I looked at [libgtk3-perl](https://packages.debian.org/buster/libgtk3-perl) and saw ```libglib-object-introspection-perl``` ; thought it was the same but it's not exactly it.  But having it is maybe enough.

> Anyway, it's always a good practice to explicitly list everything that you directly require.

Well, I guess the point here is that we (at least I) don't know if we really directly depends on it.  As we depend on ```libgtk3-perl```, I would expect that this package provides the introspection thing.

About the current issue, the root "bug", maybe, is that there is no ```libvte-perl``` package.  As it does not exists, we indeed need to have a direct dependency on ```gir1.2-vte-2.91```.

> I'm happy to say the gtk3 version is now running also on my debian 10.

Great news :)  Thanks for your feedback.

**Comment by egmontkob** [comment]
In order to load something via `Glib::Object::Introspection`, a `.typelib` file is needed, e.g. `Gio-2.0.typelib` and `GdkX11-3.0.typelib` for Ásbrú. On Ubuntu these are shipped by the `gir1.2-glib-2.0` and `gir1.2-gtk-3.0` packages, respectively.

`libgtk3-perl` depends on `gir1.2-gtk-3.0` which in turn depends on `gir1.2-glib-2.0`, so we are good.
