### ISSUE TITLE
Placement of the context menu after right click the asbru-cm tray icon (on EL7)

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#273]
When I right click the asbru-cm tray icon in the gnome-tray, I get the context menu anchored to the bottom left corner of the screen. Instead and as usual, it should be displayed just bellow the asbru tray icon and the tray. This is on EL7 running gnome3. This occurs with asbru 6.0 and I think it happens with 5.2.1 as well (have to downgrade to confirm).

**Comment by egmontkob** [comment]
Not sure if this comment is useful or relevant at all, or if it helps solve this problem, or if you're ready to bump the GTK requirement by so much (branch based on GTK version, or play try-catch). Anyway:

GTK 3.22 deprecated `gtk_menu_popup()`, and added three new replacements: `gtk_menu_popup_at_widget()`, `gtk_menu_popup_at_pointer()` and `gtk_menu_popup_at_rect()`.

The old `gtk_menu_popup()` also takes some `parent` arguments, maybe those aren't filled in properly.

**Comment by gfrenoy** [comment]
@popxunga Really sorry but we don't have enough information to reproduce this issue.  As a first step, we need to have a properly supported package for your environment ... Can you have a look to #60 to help on this ?

@egmontkob Look like we are not using ```menu_popup``` but ```menu``` :

https://github.com/asbru-cm/asbru-cm/blob/b7730128c5eb40cbda822f7d0de89d7bd3aebb00/lib/PACUtils.pm#L1691-L1695

**Comment by gfrenoy** [comment]
So if I get it correctly, the function ```_pos``` is calculating where the popup should be placed:

https://github.com/asbru-cm/asbru-cm/blob/b7730128c5eb40cbda822f7d0de89d7bd3aebb00/lib/PACUtils.pm#L1750-L1769

@popxunga You should add a line before ```return $x, $y;``` to display the various values there and understand why the calculation is not correct.

**Comment by popxunga** [comment]
@gfrenoy  ... just did it, and got this:

INFO: Ásbrú started (asbru-cm) with PID 18900
INFO: Using config directory '/home/xxxxxxxx/.config/pac'
INFO: Used config file '/home/xxxxxxxx/.config/pac/pac.nfreeze'
INFO: Using Gnome tray icon
X:1 Y:1392 
X:1 Y:1392 
X:1 Y:1392

**Comment by gfrenoy** [comment]
Can you display the other values ($h, $ymax, $dy, ...) to understand where it screwed up ?

And maybe the values of ($x, $y) after line 1753.

**Comment by popxunga** [comment]
INFO: Using Gnome tray icon
AFTER 1753 x:1 Y:1424 
BEFORE RETURN h:32 ymax:1080 dy:27 x:1 Y:1392

**Comment by gfrenoy** [comment]
> AFTER 1753 x:1 y:1424

So you have your tray icon on the left bottom of your screen ?!

So we should display the menu *above* the tray icon, shouldn't we ?

**Comment by popxunga** [comment]
Nope ...my try icon is located on top right of my screen.
![image](https://user-images.githubusercontent.com/37672088/68543309-652e9a80-03ad-11ea-878b-37c37e0087fa.png)

**Comment by popxunga** [comment]
Using this command **watch -t -n 0,0001 xdotool getmouselocation** this are the coordinates for the mouse location:

![image](https://user-images.githubusercontent.com/37672088/68543912-28ff3800-03b5-11ea-83e8-01be8f75719d.png)

**Comment by gfrenoy** [comment]
So ```getmouselocation``` reports a mouse location (1476, 11) that is not the same as what we see in your trace (1, 1424) ?!?  I'm lost for now :-/

**Comment by popxunga** [comment]
Maybe the x,y coordinates are switched.

By replacing the line 1753 of PACUtils.pm 

**my ($x, $y) = $event->window->get_origin;**

with 

**my ($y, $x) = $event->window->get_origin;**

I get this in the debug messages, which seems more realistic and correct:

INFO: Using Gnome tray icon
x:1396 y:1 
h:32 ymax:1080 dy:27 x:1396 y:28

... and the context menu appears in the correct place :-)

**Comment by B1tl0rd** [comment]
Will the extension for the legacy tray have anything to do with it? Try https://github.com/hardpixel/unite-shell.
in plasma / kde, it works well, I think it's a problem with the gnome shell integration, and its different versions according to the distribution

**Comment by popxunga** [comment]
I don't believe so, as I have at least another 8 different icons on the legacy tray behaving well.
These are the versions I'm using:
gnome-shell-3.28.3-13
gnome-shell-extension-top-icons-3.28.1-7.el7.noarch
Not sure if adding another extension to the equation may help in this case.

**Comment by popxunga** [comment]
@gfrenoy 
Now that both asbru-cm 5.2 and 6.0 can be installed on EL7, is that possible to pursue the debug of this issue ?

**Comment by gfrenoy** [comment]
It looks more like a Gnome issue since what we get from ```$event->window->get_origin();``` is (apparently) the location of the legacy icon tray location.  Not sure what we can do about this and that system tray has disappeared now (https://www.omgubuntu.co.uk/2017/09/will-you-miss-gnome-legacy-tray) so I'm actually surprise we still see it ?!

**Comment by popxunga** [comment]
There are a couple of gnome3 extensions that allow us to restore the functionality lost by the legacy-tray removal. As many others, I use use gnome shell extension called top-icons (package name is gnome-shell-extension-top-icons), and it works well with a sort of applications written in python, C++, etc,. 
The coordinates returned by the debug code (X:1 Y:1392) doesn't seem correct.
The asbru-cm systray context menu appears where it should with any asbru-cm 5.2.x version.
But it fails with asbru-cm 6.x.

**Comment by gfrenoy** [comment]
> The coordinates returned by the debug code (X:1 Y:1392) doesn't seem correct.

Yes, that is the point : this is a "system" call ... I don't see how we can change this inside Ásbrú.

Btw, I'm using gnome-shell 3.28.4 with Unite extension and I don't have this issue.

**Comment by popxunga** [comment]
Not sure if you got my point.I'm using gnome-shell version 3.28.3.
And using gnome-shell version 3.28.3 I get the context menu location issue with asbru-cm 6.0 but it works fine with asbru-cm 5.2.1. How can this be a gnome issue ?
If this was a gnome issue I would get the problem no matter what version of asbru-cm I'm using.
BTW, I've modified the PACUtils.pm 5.2.1 code to get the x,y coordinates and I get nothing printed in the terminal. Do you know why ?

**Comment by gfrenoy** [comment]
> How can this be a gnome issue ?

Because Ásbrú 5.2.1 is based on Gtk2 and Ásbrú 6.0.0 is based on Gtk3.  The Ásbrú code did not change (only formatting...).

**Comment by popxunga** [comment]
What's is the version of the perl-Gtk3 package in your system ?

**Comment by popxunga** [comment]
Just found that:
With perl-Gtk3-0.017-3.el7.noarch (the version available from EPEL 7) I get the issue reported.
With perl-Gtk3-0.036-1.el7.noarch (which I just built from source) it works fine.
So the perl-Gtk3 package version seems to be the culprit.

**Comment by gfrenoy** [comment]
> What's the version of the perl-Gtk3 package in your system ?

0.032-1

> With perl-Gtk3-0.036-1.el7.noarch (which I just built from source) it works fine.

Great discovery !  Thanks for your feedback.

I guess we should provide this package in our repository as well ?  Will you send it to Klaas ?

**Comment by popxunga** [comment]
Just did it ;-)

**Comment by KlaasT** [comment]
Done that.

**Comment by gfrenoy** [comment]
Great, so let's assume we fixed it :)  Thanks all for your help.
