### ISSUE TITLE
Manual password required

### ISSUE THREAD

**Issue by marc-straube** [asbru-cm/asbru-cm#283]
Hi,
I run Asbru on a couple of Arch Linux systems and so far it works good. The only thing I had to change was the regex for the password prompt.

On one system I have the problem, that Asbru opens a dialog "Manual Password requested" on all SSH connections with private key authentication. Username and passphrase are filled.
What can I do, to make Asbru use the already given password?

**Comment by hanspr** [comment]
What version are you using the main branch? If so, install the gtk3 branch version or clone if you prefere.

https://github.com/asbru-cm/asbru-cm/tree/gtk3

Must of the work is done there right now and we have been fixing many bugs, including that one, I don't think it has been back ported to the main branch.

**Comment by marc-straube** [comment]
Thanks. The change to asbru-cm-gtk3-git worked like a charm.
