### ISSUE TITLE
Add hotkeys to commands

### ISSUE THREAD

**Issue by park-land** [asbru-cm/asbru-cm#285]
There are a number of common commands that I currently use the remote commands feature to manage. 

It would be nice if I could assign a hotkey to a command so that I can simply type Ctrl-F1 for example and have the command sent to the terminal, ala MobaXterm macros.

I use the drop down below the terminal which is okay, but switching context from keyboard to mouse slows down what I'm doing and breaks the flow.

**Comment by gfrenoy** [comment]
Would be a nice enhancement, indeed :)

I guess we would want to have a configurable hotkey ?

**Comment by merikz** [comment]
Perhaps a field in the "Remote macros" pane where you can chose hotkey for the entry?

There is this "Disable next keybindings..." in the "Terminal Options" pane that I never really understood what it's good for. But it hints that maybe it's not straight forward to just pick any key combination and assign to a macro.

**Comment by hanspr** [comment]
@gfrenoy I'll take this ; with #556

**Comment by hanspr** [comment]
It has been added to next version 6.3, you can test it now if you install the Snapshot releases (I'm not sure if is already in one now) or the loki releases.

https://docs.asbru-cm.net/General/Installation/

**Comment by gfrenoy** [comment]
You should install the "loki" version to test this further.
