### ISSUE TITLE
Can not input username more than 14 symbols on Proxy tab

### ISSUE THREAD

**Issue by zolomihina** [asbru-cm/asbru-cm#288]
**Describe the bug**
Can not input username more than 14 symbols on Proxy tab

**To Reproduce**
1. Go to Connections bar
2. Click right button on available connection and choose Edit connection
3. Click on Proxy tab
4.Try to write username in User field longer than 14 symbols

**Comment by gfrenoy** [comment]
Thanks for reporting the issue @zolomihina :)

The limit has been removed (thanks @hanspr :-p) in the latest [gtk3 branch](https://github.com/asbru-cm/asbru-cm/tree/gtk3).

Let's close this for now, feel free to reopen if you should have any further question.
