### ISSUE TITLE
GTK3 about size of preference

### ISSUE THREAD

**Issue by B1tl0rd** [asbru-cm/asbru-cm#293]
**Describe the bug**
 in lower resolution screens "1366x768" the lower part is cut, hiding part of the icons. It would be nice to be able to redeem a little less.
I am using global menu, so it takes away some space but beyond that. I think I should be able to shrink a little more

![image](https://user-images.githubusercontent.com/12401985/69906996-597e3480-13ab-11ea-889b-900de490e6a0.png)

**Comment by hanspr** [comment]
Hi @B1tl0rd 

The size depends on the tallest of all the element, in this case I located the Terminal > Look and Feel to be the tallest

![imagen](https://user-images.githubusercontent.com/1572396/69908004-53d22000-13a6-11ea-9e42-e17158f358f5.png)

The easiest way to solve this (for me) is to remove elements from this window or relocate them.

The "Open new connections on", can be moved to the "Behaviour" tab, that to me makes more sense to be a behaviour than a look and feel. That is basically empty

![imagen](https://user-images.githubusercontent.com/1572396/69908018-aad7f500-13a6-11ea-8c6a-23c7bd8757d2.png)

If I do so we get this layouts

![imagen](https://user-images.githubusercontent.com/1572396/69908021-b5928a00-13a6-11ea-9f48-ea8e1e8d6206.png)

![imagen](https://user-images.githubusercontent.com/1572396/69908024-bc210180-13a6-11ea-851b-a8db1d89a499.png)

As a visual reference the total height of the Preferences window shrinks like this

Original

![imagen](https://user-images.githubusercontent.com/1572396/69908036-e5419200-13a6-11ea-86b0-fca5ccdaa06f.png)

After

![imagen](https://user-images.githubusercontent.com/1572396/69908038-f4c0db00-13a6-11ea-8dd1-0e94d16d3ddf.png)

I'm sure that there are many other options, if @gfrenoy , agrees with this moves I could send a PR, other wise, we would have to find another way to shrink everything, introduce a GtkScrolledWindow like in "Edit Connections", to have a scrollable window inside the preferences and move everithing in there.

Is not a large change, but enough for what you seem to need.

I you want to test it, is on this branch [https://github.com/hanspr/asbru-cm/tree/shrink-preferences](https://github.com/hanspr/asbru-cm/tree/shrink-preferences)

**Comment by B1tl0rd** [comment]
thanks @hanspr , it seems to be fine, let's see what you think @gfrenoy

**Comment by B1tl0rd** [comment]
perfect.
![image](https://user-images.githubusercontent.com/12401985/69908283-e386c700-13c4-11ea-91e4-356a534276d9.png)

**Comment by gfrenoy** [comment]
I strongly believe all those options are very powerful but the way it has organically grown makes it very hard to understand ; even for advanced users...

A deep redesign would be a great step forward but it goes beyond this request !

So for 6.0.0, let's do what you propose @hanspr, it makes sense and is a real "quick win" :-)  Maybe for 6.1, we'll need to have a UX designer on board to help us on this topic ...?

Another small thing I would change to reclaim space is the big "WARNING" about tray icon ; it does not make much sense for a beginner and is probably too simplistic for the advanced one.  And not sure that Topicons is the best advice today.

What would you think about removing it and having a dedicated page on the wiki that would explain this better ?

**Comment by hanspr** [comment]
> Another small thing I would change to reclaim space is the big "WARNING" about tray icon 

Well, this is one of the reasons why I wanted a global variable to detect environments. What I did is show it only in the case that we are under gnome3 and no unite extension detected.

![imagen](https://user-images.githubusercontent.com/1572396/69916573-38a4f600-1422-11ea-8eb2-493188c1cfcf.png)

It is a smaller message, updated and meaningful to gnome3 users that are the ones affected.

**Comment by gfrenoy** [comment]
Looks good to me for now.  There's probably much more work to make all dialogs nicer but let's take it step by step.

@B1tl0rd Let us know if it's OK to close this issue.

**Comment by B1tl0rd** [comment]
Excellent. resolved.
