### ISSUE TITLE
Asbru entry left on Window List (el7+el8)

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#294]
Hi ...
Seeing this on asbru-cm-6.0.0\~1575196208-1.el7 and asbru-cm-6.0.0\~1574600188-1.el8.
The "Hide to tray instead of closing" is not working correctly.
Once the asbru-cm main window close button is pressed, the window get iconified to the systray, but an entry remains in the Window List bar at the bottom (the entry should be removed as in the previous versions).
Note that on CentOS 8, the Window List extension has to be activated via gnome tweaks.
Thanks

**Comment by popxunga** [comment]
Hi @hanspr 
Just saw the description of #506 .
Is is merged into the latest loki build that I'm using ?
Thanks.

**Comment by hanspr** [comment]
Not yet.

If you are affected open settings, select Traditional, make sure close to tray is active, set to Compact, and save. You might need to restart.

**Comment by popxunga** [comment]
From my notes, the last build which worked correctly from this point of view was this one:
asbru-cm-6.0.0~1575124681-1.el7.noarch.rpm

**Comment by hanspr** [comment]
I really no not understand the top description of the problem, I need images.

**Comment by popxunga** [comment]
1 - Asbru Window opened and maximized:
![image](https://user-images.githubusercontent.com/37672088/77675356-c03fe300-6f84-11ea-8fb4-43d22b81a8ca.png)

2 - If I click the Asbru tray icon, the Asbru window gets closed into the tray and nothing is left in the Window List bar:
![image](https://user-images.githubusercontent.com/37672088/77675774-49efb080-6f85-11ea-96a7-5fdb5be9ee9f.png)

3- If I click the Asbru window close button 
![image](https://user-images.githubusercontent.com/37672088/77676246-f6ca2d80-6f85-11ea-9ebf-cae86bb18b06.png)
... I get this:
![image](https://user-images.githubusercontent.com/37672088/77676031-a521a300-6f85-11ea-9f9e-d03ddbadcddd.png)

So, pressing this button:
![image](https://user-images.githubusercontent.com/37672088/77676160-d69a6e80-6f85-11ea-8cd7-efb94aa230f0.png)
... is minimizing the window and not closing it into the tray.

As I said above, this started to happen after asbru-cm-6.0.0~1575124681-1.el7.noarch.rpm.

**Comment by hanspr** [comment]
Could you edit PACMain.pm around line 2332 like this and test?

![imagen](https://user-images.githubusercontent.com/1572396/77679052-aa67f900-6f57-11ea-87d1-380256705b0b.png)

**Comment by popxunga** [comment]
Hi @hanspr 
My PACMain.pm doesn't have that portion of code in the same line.
Is this what you asked me to do ?
`	# Capture window closing
	$$self{_GUI}{main} -> signal_connect( 'delete_event' => sub {
		if ( $$self{_CFG}{defaults}{'close to tray'} ) {
			# Show tray icon
			if	( $UNITY )	{ $$self{_TRAY}{_TRAY} -> set_active; }
			else			{ $$self{_TRAY}{_TRAY} -> set_visible( 1 ); }
			# Trigger the "lock" procedure ?
			if ( $$self{_CFG}{'defaults'}{'use gui password'} && $$self{_CFG}{'defaults'}{'use gui password tray'} ) { $$self{_GUI}{lockPACBtn} -> set_active( 1 ); }
			# Hide main window
                        if ($ENV{'ASBRU_DESKTOP'} eq 'gnome-shell' && !$UNITY) {
                            $$self{_GUI}{main} -> iconify();
                        } else {  
			$self -> _hideConnectionsList;
		} else {
			$self -> _quitProgram;
		}
		return 1;
	} );`

If yes, I'm getting the same behavior with the proposed change.
Thanks.

**Comment by hanspr** [comment]
So it did not work you mean?

**Comment by popxunga** [comment]
Yes ...
![image](https://user-images.githubusercontent.com/37672088/77682586-1b76d300-6f8f-11ea-9ce2-adff92dfdcaa.png)

**Comment by popxunga** [comment]
Hi @hanspr 
Sorry ... I edited the wrong file (from an old copy of pac under /opt which I already removed to avoid further errors.)

This turn I edited the correct one in /usr/share/asbru-cm/lib folder.
![image](https://user-images.githubusercontent.com/37672088/77687359-2a14b880-6f96-11ea-8cf5-c1726ae8bc2b.png)

And now when I press the X nothing happens, I mean, the Asbru window remain open.
Thanks.

**Comment by hanspr** [comment]
I think the fix requieres a deeper fix, I'm doing it now but I do not have a Centos 8 environment to test, just ubuntu, mint, and manjaro.

**Comment by popxunga** [comment]
Hi @hanspr 
In fact what I just described is wrong. The X was not doing nothing because there was a 2nd instance of asbru running. After kill everything and launch it again, I get the initial sympton.
I do have a CentOS 8 VM where I can test it. 
Thanks.

**Comment by hanspr** [comment]
I would try to install a Centos VM, but last time I tried to install asbru I simply quit. Is easy to install now?

**Comment by popxunga** [comment]
The Centos 8 VM installation is not difficult.
Then you just have to add epel 8 and the asbru cm repo's in order to install the asbru-cm packages and get its dependencies.

**Comment by hanspr** [comment]
> Then you just have to add epel 8 and the asbru cm repo's in order to install the asbru-cm packages and get its dependencies.

Do you have the instructions for this?

I did

```
yum install epel-release
yum update

curl -s https://packagecloud.io/install/repositories/asbru-cm/loki/script.rpm.sh | sudo bash

yum install asbru-cm
```

And I get e list of dependencies that have no candidate for installation. (SimpleList, ARP, ossp::UUID, etc)

**Comment by hanspr** [comment]
Also tried with

`dnf install asbru-cm`

Same result, no dependencies packages available

**Comment by popxunga** [comment]
Maybe because the rpm's I've built for you guys were not copied into the loki repo...

**Comment by KlaasT** [comment]
> 
> 
> Maybe because the rpm's I've built for you guys were not copied into the loki repo...

That is possible. Checking that.

**Comment by popxunga** [comment]
Just checked it. The missing package are in the asbru-cm repo only.

**Comment by hanspr** [comment]
Thanks, I installed then the master branch and I will clone the git repo to use the new one.

**Comment by popxunga** [comment]
Or you can simply add the asbru-cm repo.
curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.rpm.sh | sudo bash

**Comment by KlaasT** [comment]
The rpms have been added to the repositories.

**Comment by hanspr** [comment]
> Note that on CentOS 8, the Window List extension has to be activated via gnome tweaks.

How to I do this?

**Comment by popxunga** [comment]
Then in order to mimic what I see you will need to install this:
sudo dnf gnome-shell-extension-dash-to-dock gnome-shell-extension-top-icons

Then open the Tweaks tool and tweak the extensions like this:
![image](https://user-images.githubusercontent.com/37672088/77694729-7665f580-6fa2-11ea-8a7e-529c1926f432.png)

Then reboot.

**Comment by hanspr** [comment]
Ok, next, I do not see a tray icon, so is the same as gnome, what extension do you use to show the tray icon?

![imagen](https://user-images.githubusercontent.com/1572396/77695072-c62bc900-6f70-11ea-97b3-4b276b2d33f0.png)

**Comment by popxunga** [comment]
Have you seen my previous post ?

**Comment by hanspr** [comment]
This ?, yes. Then I have to install and find all those?, I'm not familiar with Centos


https://user-images.githubusercontent.com/37672088/77694729-7665f580-6fa2-11ea-8a7e-529c1926f432.png

**Comment by popxunga** [comment]
Re-read my post please. 
You just have to install 2 extensions. The rest should be there by default.
And then turn them on as in the screenshot.

**Comment by hanspr** [comment]
Visible

![imagen](https://user-images.githubusercontent.com/1572396/77696151-86fe7780-6f72-11ea-9c59-a82a8b9875ae.png)

Closed

![imagen](https://user-images.githubusercontent.com/1572396/77696169-8ebe1c00-6f72-11ea-975d-e70a1f05ace7.png)

**Comment by popxunga** [comment]
Exactly ... that should not appear at bottom.
I do have this set in my Asbru preferences:
![image](https://user-images.githubusercontent.com/37672088/77696850-c7c3b400-6fa5-11ea-906a-b8b35b8e5642.png)

**Comment by hanspr** [comment]
Not any more with the fix, I'm preparing the PR

**Comment by popxunga** [comment]
Thanks a lot @hanspr  !!!

**Comment by popxunga** [comment]
Hi @hanspr 
Just tested the latest loki build and I can confirm this issue is solved.
Thanks for your support.
Closing.

**Comment by wcasanova** [comment]
please add
https://github.com/ubuntu/gnome-shell-extension-appindicator
some no longer work with GNOME 40
@gfrenoy
