### ISSUE TITLE
Copy password from another connection defined in the Connections List

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#295]
Hi ...
Suppose that you have an SSH session established to host A.
Then you need to SCP a file from host B into host A and that authentication with password is required.
It would be nice to have an option in the context menu of the connection B to easily copy its password into the clipboard and then simply paste it while doing the SCP authentication on host A. 
Currently to achieve the same, we have to open the connection definitions of host B, expose the password field, select and copy the password, close the connection definitions window and finally we can paste the password while we execute the SCP command in session A.
Thanks.

**Comment by gfrenoy** [comment]
As passwords are not properly encrypted in Ásbrú, I'm not sure we should encourage its usage ... Maybe working on a better integration with KeePassXC (see #65) would be more meaningful ?

**Comment by popxunga** [comment]
I think that passwords are still widely used in most situations.
A better integration with KeepassXC is needed to. I'll l use for sure when it becomes available but until that happens, having what I'm asking for would be nice if the development effort to achieve it is not too much.

**Comment by hanspr** [comment]
This should be closed

**Comment by gfrenoy** [comment]
I tried this and actually, I would expect to have the "Copy connection password" on a right-click from the connection tree as well, don't you think ?

Said differently : I don't want to open a terminal or open the connection details to get the password.

**Comment by gfrenoy** [comment]
Nevermind, it's already there...

**Comment by gfrenoy** [comment]
@popxunga let us know if the latest snapshot is meeting your expectations.

**Comment by popxunga** [comment]
Hi @gfrenoy  ... Just tried it ... and yes it does ! Thanks a lot :-)
