### ISSUE TITLE
libgnome2-vte-perl_0.11-1_amd64.deb could not be installed on ubuntu 17.10 (artful)

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#3]
The package has a hard dependency on perlapi-5.24.1 but artful contains perlapi-5.26.0.

**Comment by gfrenoy** [comment]
Dependencies have been improved so that libgnome2-vte-perl can be installed on Ubuntu / Artful.  The new package is available on packagecloud.io.

Feel free to reopen the issue if you still have problem with this.
