### ISSUE TITLE
2FA under Authentication options

### ISSUE THREAD

**Issue by torson** [asbru-cm/asbru-cm#300]
I've found out that you can use 2FA TOTP with Asbru, you just need to select "Manual" under "Authentication".  I'm using private key authentication. On the server I'm using google-authenticator to enable 2FA TOTP.
One extra surprise/convenience is that even though that next to "Manual" it says it will not auto-login and that you need to manually enter username it does use the username set under "User / Password" . In my case the only prompt was for TOTP, after getting past that I got logged in as the user set under "User / Password".

So there is a way to use TOTP without you needing to input your username every time, it just isn't evident. 
Maybe just update the comment sentence next to the "Manual" option and also add "Use this for 2FA".

**Comment by B1tl0rd** [comment]
Interestingly, I create all functionality or measure, so that our connections are more secure, they are a priority. let's see what our colleagues say, days ago I was seeing a good customer opensource.
https://freeotp.github.io/
https://www.linode.com/docs/security/authentication/use-one-time-passwords-for-two-factor-authentication-with-ssh-on-centos-7/

**Comment by gfrenoy** [comment]
Thanks for the return of experiment :-)

We should probably have a wiki page about this ?  Can someone write down something ?  With maybe a few screenshots ?

And we can certainly modify the text to make it more intuitive.

**Comment by gfrenoy** [comment]
See https://github.com/asbru-cm/asbru-cm/wiki/Two-factor-authentication

**Comment by torson** [comment]
@gfrenoy Great. 
I would clean my part a bit, here's my proposal:

```
You can use Two-factor authentication (2FA) Time-Based One-Time Password (TOTP) with Ásbrú Connection Manager !

In the Connection Details settings do this under Authentication settings block:
- first select "User / Password" and set the username
- then select "Manual"
Even though that next to Manual it says it will not auto-login and that you need to manually enter the user name, it does use the username set under "User / Password" and log you in

After setting this up, The only prompt while connecting is for TOTP.

These instructions assume you're using private key authentication. It might also work for password authentication by adding password along the username but nobody has tested it.
```

I don't know about the requirement of using private key authentication. It might also work by adding password along the username but I haven't tested it.

**Comment by gfrenoy** [comment]
Thanks for improvements ; the wiki page has been changed accordingly !
