### ISSUE TITLE
VNC connection status is not parsed properly (always "connecting")

### ISSUE THREAD

**Issue by ValdikSS** [asbru-cm/asbru-cm#301]
**Describe the bug**
After updating to Fedora 31, VNC connections do not work properly anymore. VNC gets disconnected after several hundreds of seconds, as Asbru is unable to parse VNC connection status. Asbru thinks that VNC is still in connecting state even if it's connected, the progress bar is bouncing and after some time gets disconnected.

Asbru shows Status: SPAWNED.

**To Reproduce**
1. Open VNC connection using Asbru
2. Wait for 30 seconds

**Expected behavior**
VNC continue to work as usual.

**Actual behaviour**
VNC window is closed after 30 seconds.

**Screenshots**
Watch the video: https://files.catbox.moe/w02rm8.mp4

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Version: v5.2.1 from official repositories

**Comment by gfrenoy** [comment]
Thanks for your feedback.

I tried to reproduce this with TigerVNC v1.7.0 but it just works fine for me.  Do you know if this is specific for TigerVNC v1.10 ?

Would you have the opportunity to try with TightVNC ?

**Comment by ValdikSS** [comment]
It used to work fine on Fedora 30, also with TigerVNC 1.10.0.
I'll try TightVNC.

**Comment by gfrenoy** [comment]
Oh, I have a F30 virtual machine (no F31 yet) so I could give it a try.  Interestingly enough, I do have the issue with Fedora 30 !

**Comment by gfrenoy** [comment]
Ok found the issue...

Ásbrú is looking for: ```connected to host``` and in TigerVNC 1.10, it is now displaying: ```Connected to host``` (with a capital C ;-/) !

See here:
https://github.com/asbru-cm/asbru-cm/blob/5.2.1/lib/pac_conn#L1183-L1187

I made the fix on the master branch.  We are about to release v6.0 so I don't believe we'll fix this on the v5.x branch.

So at this stage, either you patch your version (in ```/usr/share/asbru-cm/lib/pac_conn```), either you upgrade to the latest snapshot.

**Comment by ValdikSS** [comment]
Works now, thanks!

**Comment by ValdikSS** [comment]
It would be perfect to officially release fix for 5.x branch.

**Comment by gfrenoy** [comment]
Well, it will be officially released in the _next_ version...(which is v6.0) ; you can already test it if you use the snapshot version (see https://github.com/asbru-cm/asbru-cm/wiki/Installation-on-Fedora)
