### ISSUE TITLE
RPM packaging issue: res directory is in incorrect path

### ISSUE THREAD

**Issue by ValdikSS** [asbru-cm/asbru-cm#302]
**Describe the bug**
Asbru tries to load some graphic and perl files from `/usr/share/asbru-cm/lib/res/`, which gets packaged into `/usr/share/asbru-cm/res/` (no `/lib/`) in Fedora 31 packages.
This leads to cryptic error message when SSH connection is performed with incorrect password:
```
Wide character in subroutine entry at /usr/share/asbru-cm/lib/pac_conn line 451.
Failed to open file “/usr/share/asbru-cm/lib/res/asbru-logo-64.png”: No such file or directory at /usr/share/asbru-cm/lib/pac_conn line 451.
```

Workaround: `sudo ln -s /usr/share/asbru-cm/res /usr/share/asbru-cm/lib/res`

**To Reproduce**
1. Connect to SSH server with incorrect password
2. See error

**Expected behavior**
Asbru asks for new password in new window and does not terminate with error.

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Version v5.2.1

**Comment by gfrenoy** [comment]
Thanks for the report and the workaround ValdikSS :)

I do believe I already fixed this here --> https://github.com/asbru-cm/asbru-cm/commit/0bfff0d86fe05160a8199247dfb6c226200f966d#diff-22afcf4d685b66ae7d2a5b2c9817621c

So it won't happen in the next version :)
