### ISSUE TITLE
Invalid scroll position in KDE (gtk3)

### ISSUE THREAD

**Issue by beliys** [asbru-cm/asbru-cm#303]
**Describe the bug**
After switching to the version of asbru-cm on gtk3, the scroll position was incorrect in KDE (see screenshot).

**Screenshots**
https://i.imgur.com/zkuTOo7.png
https://i.imgur.com/SZ3XhTZ.png

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version: Latest
 - DE: KDE

**Comment by beliys** [comment]
There is no such problem with other gtk3 applications

**Comment by gfrenoy** [comment]
So you mean this is not specific to Ásbrú ?  So what can we do ?

**Comment by beliys** [comment]
As I wrote above, of all gtk3 applications, the problem is only with Ásbrú. It is possible to speculate with what parameters this can be fixed. I am willing to experiment, but I do not know gtk3 (

**Comment by B1tl0rd** [comment]
I also use kde / plasma, but I don't see what the problem is in the bar. What behavior do you want, or where should I go for you?
![imagen](https://user-images.githubusercontent.com/12401985/70525449-244db100-1b26-11ea-9b6c-9fbb0ef9a35d.png)

**Comment by beliys** [comment]
@B1tl0rd try with long names of connections (both scrolls are active)

**Comment by gfrenoy** [comment]
@beliys Sorry I misread your sentence !  I'll need to give it a try by myself to better understand the different between Ásbrú and the other application.  Do you have the same for all KDE "themes" ?

**Comment by beliys** [comment]
The problem is exactly on the main gtk3 theme for KDE Breeze. In most other topics, a similar problem - somewhere it will look a little better somewhere on the contrary. At the same time, other gtk3 applications correctly display on the same topics.

**Comment by gfrenoy** [comment]
@beliys As far as I can see, this is the default behaviour of a Gtk3 application to have "overlay scrolling" at TRUE, see https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#GtkScrolledWindow--overlay-scrolling

For the connection window, you can try to add the following line:

```
$$self{_GUI}{scroll1}->set_overlay_scrolling(0);
```

at line 504 of ```PACMain.pm```

And let us know if this is what you would expect ?

**Comment by beliys** [comment]
Thanks, that really looks better. Can we add this to the master branch?

**Comment by gfrenoy** [comment]
Yes and no.  That single line is not enough... I would suggest to have this as an option because personally, I do prefer that "overlay" option that does not show the scrollbar when it is not necessary (hence provide more "useful" space).

**Comment by beliys** [comment]
I agree, as an option it will be optimal...

**Comment by beliys** [comment]
Is it possible to improve scroll style with overlay true?

**Comment by gfrenoy** [comment]
> Is it possible to improve scroll style with overlay true?

No idea.

But you may want to have a look at the new [css](https://github.com/asbru-cm/asbru-cm/blob/master/res/asbru.css) file we have.  If we apply a special class to that scrollbar, maybe we can then adjust the style in that CSS file ?

**Comment by beliys** [comment]
We can try, maybe something will turn out.

**Comment by gfrenoy** [comment]
New option added to the latest "loki" version.
