### ISSUE TITLE
Remote commands in Cluster connections  

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#304]
**Describe the bug**
When using the cluster option, and running multiple servers within that cluster, whatever you type/send to one host is being replicated to the other host. No issue there. But when I click on one of the "Global common remote commands" I have configured to run e.g. "sudo su -" it doesn't send it to all the hosts in the cluster, just to the active host.

**To Reproduce**
1. Create a cluster with 2 or more host
2. Run that cluster so it will open a new tab for each host that are in the cluster
3. Under Preferences > Remote Commands > Create one command
4. Run that command clicking the button 

**Expected behavior**
Button should sent the command to all nodes in the cluster

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Version 18.04

**Comment by gfrenoy** [comment]
@ferent Let us know if Hans' patch fixes your issue.  Thanks to both of us !

**Comment by hanspr** [comment]
This should be closed
