### ISSUE TITLE
Install failed on Centos 8

### ISSUE THREAD

**Issue by wixaw** [asbru-cm/asbru-cm#305]
**Describe the bug**
unable to install on centos 8

**To Reproduce**
1. curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.rpm.sh | sudo bash
2. dnf install asbru-cm
3. See error
```

Erreur : 
 Problème: conflicting requests
  - nothing provides perl(Crypt::Rijndael) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(Gnome2::GConf) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(Gtk2) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(Gtk2::AppIndicator) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(Gtk2::Ex::Simple::List) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(Gtk2::Ex::Simple::TiedCommon) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(Gtk2::GladeXML) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(Gtk2::SourceView2) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(Gtk2::Unique) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(HTTP::Proxy) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(IO::Stty) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(Net::ARP) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl(OSSP::uuid) needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl-Gnome2-Vte needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides perl-X11-GUITest needed by asbru-cm-5.2.1-1.el8.noarch
  - nothing provides vte needed by asbru-cm-5.2.1-1.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Centos
 - Version [e.g. 22] 8 

**Additional context**
Install it's ok on centos 7 

Thanks you in advance

**Comment by x-wolverine-x** [comment]
curl -s https://packagecloud.io/install/repositories/asbru-cm/el-test/script.rpm.sh | sudo bash
AND you have to use GTk3
curl -s https://packagecloud.io/install/repositories/asbru-cm/gtk3/script.rpm.sh | sudo bash

Check https://github.com/asbru-cm/asbru-cm/issues/60

**Comment by wixaw** [comment]
Oh thanks ! 
I did not need that for centos 7 but it works for 8 !
Maybe you can put on https://www.asbru-cm.net/

**Comment by x-wolverine-x** [comment]
I'm sure they will put it there, when they publish the gtk3 branch to master.

**Comment by gfrenoy** [comment]
Yes, that's definitely our plan to have a v6 release before Christmas 🎄 :)

And, actually we already merged the gtk3 branch with master so the "latest and greatest" release is the snapshot version:

```
curl -s https://packagecloud.io/install/repositories/asbru-cm/snapshots/script.rpm.sh | sudo bash
```

**Comment by gfrenoy** [comment]
As we won't do anything special on this ; can we consider this issue closed ?
