### ISSUE TITLE
Lack of transparency 

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#307]
**Describe the bug**
In the new snapshot version 6, transparency option is lock to 0 and can't be modified.

**To Reproduce**
1. Go to Preferences
2. Click on Terminal Options > Look and Feel 
3. Try to move Transparency bar

**Expected behavior**
Transparency bar to allow select the level of transparency you want in your shell background, as it was working in the previous version

**Screenshots**

**Desktop:**
    OS: Linux Ubuntu
    Version 18.04

**Comment by gfrenoy** [comment]
Thanks for your report.  I believe it has already been recorded under #207 .
