### ISSUE TITLE
Does Asbru do X11 forwarding? 

### ISSUE THREAD

**Issue by jdrch** [asbru-cm/asbru-cm#308]
I couldn't find information on this anywhere, so I'm asking here. Thanks!

**Comment by x-wolverine-x** [comment]
Of course. 
![image](https://user-images.githubusercontent.com/21344031/70771265-bf39cb80-1d70-11ea-8860-ad0a2c85c5bd.png)

**Comment by jdrch** [comment]
Awesome, thanks!
