### ISSUE TITLE
Mouse paste content with middle click doesn't work in V6

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#309]
Basically what the title says. 

Using Ubuntu 18.04

**Comment by gfrenoy** [comment]
On Ubuntu (and on my other distributions, I would guess), "middle click" is not a real a ```paste``` action (I mean from a ```copy``` action), it's typing the content of the last selection.  At least, it works like this on mine...

And please also note this is something that can be enabled/disabled with [Tweaks](https://wiki.gnome.org/Apps/Tweaks):
![image](https://user-images.githubusercontent.com/981546/70846723-5af43600-1e5c-11ea-95bd-9ab10000dab8.png)

**Comment by gfrenoy** [comment]
@ferent does it work for you now ?

**Comment by ferent** [comment]
Yes, you can close the ticket, thanks!

**Comment by emoxam** [comment]
What about right mouse click ?
