### ISSUE TITLE
Export or import connections in .ssh/config

### ISSUE THREAD

**Issue by ltden** [asbru-cm/asbru-cm#31]
Hello all!
Could you please explain me, is it possible to import or export connections from ".ssh/config" file?

**Comment by gfrenoy** [comment]
Hi Denis.  As far as I know (but - disclaimer! - I don't know everything ;-p), there's no tool to import information in .ssh/config to Ásbrú.

If you want to develop this kind of feature, I guess you can find some inspiration here : https://github.com/asbru-cm/asbru-cm/tree/master/utils

**Comment by ltden** [comment]
Unfortunately I'm not a developer, just desktop user :-)

**Comment by gfrenoy** [comment]
Not a problem, I know a lot of nice people who are not developer ;-)

So if we want to make progress on this topic, we need to find a developer who will be motivated to help you.

There are many ways but the starting point for sure is to make sure the task looks "easy" for him/her.  So you'll have to explain your requirement and expectation with as much as details and examples as possible.  That will help developers to understand quicker and to optimize their time.

So what I would suggest at this stage is that you take an example and that you import it "manually", make a few screenshots, maybe a screencast of what you expect from this conversion tool.

That will hopefully give inspiration to someone :)

**Comment by ltden** [comment]
I have very long .ssh/config file, like this:
Host node01
  HostName 192.168.87.57
Host node02
  HostName 192.168.87.58
Host node03
  HostName 192.168.87.13
Host node04
  HostName 192.168.87.41
Host node05
  HostName 192.168.87.42
Host node06
  HostName 192.168.87.43
Host node07
  HostName 192.168.87.46
Host node08
  HostName 192.168.87.47
Host node09
  HostName 192.168.87.48
Host node010
  HostName 192.168.87.26
.........
And I would like to move those connection to Asbru.
Actually in my current case I don't need move IP addresses, only hosts.
I need create lot of new connections with names like "node01" and "Host" fields like node01.

Or maybe simplest way to create a lot of new connections with hostnames and other params from a text file.
May be is it possible to create new connections with Asbru CLI options?

**Comment by gfrenoy** [comment]
As far as I know there is no CLI option to create a new connection.  Only to start an existing one (--start-uuid).

You should take a look at the file ```.config/pac/pac.yml``` there you will find how connections are saved in Ásbrú.

Basically, each connection is en entry under "environments" and identified by a "uuid".

So I would create a fist one "manually"; compare pac.yml before and after the addition and then replicate the same kind of entry for each "Host" of your .ssh/config file.

**Comment by ltden** [comment]
Yes, good idea.
But I need generate a new unique "uuid" for each new connection.
What a new "uuid" depends on?

**Comment by gfrenoy** [comment]
Nothing.  Just pick something that does not exist in your configuration yet (as the name suggest, it needs to be unique).

Try this to get a new one:

https://duckduckgo.com/?q=uuid&ia=answer

Or this (on any modern system ;-p):

    cat /proc/sys/kernel/random/uuid

**Comment by ltden** [comment]
I will try.
Thank you!

**Comment by ltden** [comment]
Hello gfrenoy!
I have successfully imported my simple text host list into Asbru using bash script.
I have exported one my template connection from Asbru and multiplied this connection with relapsing connection name, host name and UUID into single output yml file.
The script:
`#/bin/bach

TEMPLATE_UUID='866d11db-02a9-456c-b8e2-5d8e47b40e6c'
TEMPLATE_CONN_NAME='my_template'          #connection name and the hostname are the same in my template

HOST_LIST_FILE='host.list'
TEMPLATE_CONN_FILE='templ_conn.yml'

OUTPUT_YML_FILE='output.yml'
UUIDS_TMP_FILE='uuids.tmp'

echo -e "__PAC__EXPORTED__:\n  children:" > $UUIDS_TMP_FILE

echo "---" > $OUTPUT_YML_FILE

for i in $(cat $HOST_LIST_FILE); do
    NEWUUID=$(uuidgen)
    sed -e '1d' \
        -e "s/${TEMPLATE_UUID}/${NEWUUID}/g" \
        -e "s/${TEMPLATE_CONN_NAME}/$i/g" $TEMPLATE_CONN_FILE >> $OUTPUT_YML_FILE
    echo "    "$NEWUUID": 1" >> $UUIDS_TMP_FILE
done
cat $UUIDS_TMP_FILE >> $OUTPUT_YML_FILE
rm $UUIDS_TMP_FILE
`

However I deleted the following fragment from the template yml file manually, because I don't know how to do that using sed:
`_PAC__EXPORTED__:
  children:
    866d11db-02a9-456c-b8e2-5d8e47b40e6c: 1`

**Comment by gfrenoy** [comment]
Thanks for sharing your findings Denis !

**Comment by gfrenoy** [comment]
If there is no more activity, let's close it for now.  The Issue marked as "documentation" so one can find it later on...
