### ISSUE TITLE
Asbru gets stuck on "Status: PASSWORD:Sent (not shown)" during SSH to OpenIndiana Hipster machine

### ISSUE THREAD

**Issue by jdrch** [asbru-cm/asbru-cm#311]
**Describe the bug**

Asbru gets stuck on "Status: PASSWORD:Sent (not shown)" during SSH to OpenIndiana Hipster (latest build, 2019.10) machine. The remote prompt shows up, but is unresponsive. After about 30 seconds the connection is closed.

Connecting to this machine via SSH works both in Konsole on Debian and in MobaXterm on Windows 10.

**To Reproduce**
1. Create a connection to an OpenIndiana Hipster 2019.10 server, with the following properties:
    * **Method:** SSH
    * **Host:** Remote server IP address
    * **Port:** 22
    * **Authentication: User/Password:**
    * **SSH Version:** any
    * **IP Protocol:** any
    * **Other Options:** Forward X & Use Compression
2. Launch the connection. It will get stuck in the phase shown in the connection status bar in the screenshot

**Expected behavior**
A remote prompt I can interact with appears

**Screenshots**
![Screenshot_20191214_005139](https://user-images.githubusercontent.com/1056759/70844906-c5ca5080-1e0d-11ea-95c7-e1473e2b19ae.png)

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 10.2

**Comment by gfrenoy** [comment]
In _Main Options_ > _Advanced_ you will find what is expected as the password prompt / command prompt.  I would guess this is a bit different for OpenIndiana Hipster.

If you have can provide a testing environment, I can help finding the right regexp to establish the communication.

**Comment by gfrenoy** [comment]
@jdrch I tried with the [stock live DVD](https://www.openindiana.org/download/) and it just works fine:

![image](https://user-images.githubusercontent.com/981546/70850103-e08cdb80-1e86-11ea-83bb-608e148b201e.png)

So I you need to adapt the "Command Prompt" regular expression to your custom shell prompt and it should work fine.

**Comment by jdrch** [comment]
> you need to adapt the "Command Prompt" regular expression to your custom shell prompt

Doesn't that run the risk of causing the same problem with other remote machines that currently work?

I have:

1. 1 Ubuntu 19.10 machine running `bash-it`
2. 1 OpenIndiana Hipster 2019.10 machine running `bash-it` (the one this issue is about)
3. 1 Raspbian Buster Raspberry Pi 3 Model B+ running 'bash-it`
4. 1 GhostBSD 19.10 machine running FISH

Somehow:

* 2) above is the only one I'm having trouble with in Asbru
* All of the above work both from terminals and MobaXterm in Windows

Also, how do you usually go about determining the RegEx a Command Prompt uses? Is it in a config file somewhere?

**Comment by jdrch** [comment]
Welp, I found a workaround: 

* In the main window, click **Preferences**
* Under **Main Options** click the **Advanced** tab
* Save what's in the **Command Prompt:** field in a text file just in case you ever need it again
* Delete what's in the **Command Prompt:** field
* Click **Save and Close**

You should now be able to connect to OpenIndiana Hipster machines running `bash-it` just fine.

The only drawback with the above method is you'll have to manually enter your password for every connection on your list.

**Comment by gfrenoy** [comment]
Good if it helps but the idea would be that we find the correct *Command Prompt* regular expression that would match yours, not to delete it...

In *Preferences* > *Terminal Options* > *Advanced*, you will find the *Expect DEBUG* option that you may want to check to understand why the default *command prompt* regexp is not accepted.

If you send what you see, we can have a look.   It should look something like this:
```
spawn id(12): Does `\033[01;32muser@myhostname\033[00m:\033[01;34m~\033[00m$ '
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)])?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@\\w+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? YES!!
    Before match string: `\033[01;32madmin@chessnick\033[00m:\033[01;34m~\033[00m'
    Match string: `$'
    After match string: ` '
    Matchlist: ()
```
(Be careful, does send us everything, it may contain information you don't want to disclose)

From the screenshot I see, you may want to add the dash "-" to the list of other typical tokens that ends the command prompt, so, try to the following regexp for your command prompt:

```
[#%\\$>-]|\\:\\/\\s*$
```

Alternatively, you can send your prompt configuration so I can try to reproduce this.

**Comment by jdrch** [comment]
> `[#%\$>-]|\:\/\s*$`

That now works for all the remote machines! Thanks so much!
