### ISSUE TITLE
[gtk3] GtkDialog mapped without a transient parent

### ISSUE THREAD

**Issue by merikz** [asbru-cm/asbru-cm#312]
**Describe the bug**
When opening the About dialog, this is written to stderr:

Gtk-Message: 20:58:38.409: GtkDialog mapped without a transient parent. This is discouraged.

**To Reproduce**
1a. Go to 'main window'
2a. Click on 'Show the *so needed* "About" dialogue' button
  or
1b. Go to 'Tray icon'
2b. Click on 'About'
3. See error on stderr

```
$ /usr/bin/perl -I/home/magnus/src/asbru-cm/lib /home/magnus/src/asbru-cm/asbru-cm --no-splash
INFO: Ásbrú started (asbru-cm) with PID 18958
INFO: Desktop environment detected : cinnamon
INFO: Using config directory '/home/magnus/.config/pac'
INFO: Used config file '/home/magnus/.config/pac/pac.nfreeze'
INFO: Using Gnome tray icon
**Gtk-Message: 20:58:38.409: GtkDialog mapped without a transient parent. This is discouraged.**
```

**Expected behavior**
No error printout

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 with cinnamon 4.2.4-1~bionic0

**Additional context**
asbru-cm branch gtk3 (commit: ab6cb2c2)

**Comment by gfrenoy** [comment]
Great !  Thanks a lot :)
