### ISSUE TITLE
Gtk3.pm missing on Fedora 31

### ISSUE THREAD

**Issue by bitchecker** [asbru-cm/asbru-cm#316]
**Describe the bug**
I updated the repository and saw that some work was done on gtk3.
after this update, the asbru-cm no longer started reporting the following errors:
```
Can't locate Gtk3.pm in @INC (you may need to install the Gtk3 module) (@INC contains: ~/asbru-cm/lib ~/asbru-cm/lib/ex ~/asbru-cm/lib/edit /usr/local/lib64/perl5/5.30 /usr/local/share/perl5/5.30 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ~/asbru-cm/lib/PACMain.pm line 50.
BEGIN failed--compilation aborted at ~/asbru-cm/lib/PACMain.pm line 50.
Compilation failed in require at ~/asbru-cm/asbru-cm line 92.
BEGIN failed--compilation aborted at ~/asbru-cm/asbru-cm line 92.
```

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 31

**Comment by bitchecker** [comment]
erroneously, I had not verified that gtk3 was installed on the machine on which I was launching the command, but, once installed, I get the following error:
```
Can't locate Gtk3/SimpleList.pm in @INC (you may need to install the Gtk3::SimpleList module) (@INC contains: ~/asbru-cm/lib ~/asbru-cm/lib/ex /media/Multimedia/Docum)
entities/programmes/asbru-cm/lib/edit /usr/local/lib64/perl5/5.30 /usr/local/share/perl5/5.30 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ~/asbru-cm/lib/PA
CTerminal.pm line 48.
BEGIN failed--compilation aborted at ~/asbru-cm/lib/PACTerminal.pm line 48.
Compilation failed in require at ~/asbru-cm/lib/PACMain.pm line 63.
BEGIN failed--compilation aborted at ~/asbru-cm/lib/PACMain.pm line 63.
Compilation failed in require at ~/asbru-cm/asbru-cm line 92.
BEGIN failed--compilation aborted at ~/asbru-cm/asbru-cm line 92.

```
Installed from rpm repository, it seems to work correctly.

**Comment by KlaasT** [comment]
Probably the dependency GTk3 and GTk3-SimpleList from the rpm repository are missing for Fedora 31. We have them for el7 and el8 though I'm not sure how to build them for Fedora 31.

**Comment by bitchecker** [comment]
the packaged version works correctly

**Comment by KlaasT** [comment]
So at first you tried to run asbru-cm from a cloned repository which gave you errors?

**Comment by bitchecker** [comment]
> So at first you tried to run asbru-cm from a cloned repository which gave you errors?

yes, because the packaged version didn't work and I also pull-requested to fix a bug.

**Comment by gfrenoy** [comment]
Just tried on a brand new Fedora 31 (live image) and all looks to work fine if you are using the "snapshots" version as described in these [installation notes](https://github.com/asbru-cm/asbru-cm/wiki/Installation-on-Fedora).

Let me close this for now, feel free to reopen if you should have any further question.
