### ISSUE TITLE
Remove Net::Proxy, replace with ssh option parameters

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#323]
Hi @gfrenoy 

There are 3 bugs related to net::proxy: #218 , #67  and #280

net::proxy, does not work properly in the case of issue #280. I think its porpoise was to give a functionality that was not available through ssh some years back.

But now, with command options we can control the 2 case scenarios and remove dependency to net::proxy

* #67 : -J option
* #280: -o ProxyCommand='nc -x 127.0.0.1:5000 %h %p'

Would not be backward compatible with older ssh versions as noted on #67, but with a tunnel and ProxyCommand, you can implement the same solution in this cases, so the user could use the available option for his own ssh version.

The "Proxy" tab could be renamed to "Network settings", as in #67, and we could add the options to the connection strings in pac_conn.

The tab should have just 4 options

* No proxy
* Use global proxy
* Use proxy : host,port,user,pass
* Use Jump host
    * One jump host configuration as in image in #67, or
    * Allow configuration of multiple jumps? or a max of 3 jumps to make it easier to implement the interface?

What do you think?, should we remove net::proxy and implement everything with options?

**Comment by KlaasT** [comment]
I think that could work. 

We have to remove Net::Proxy. As in #218 the dependency is hardly supported with newer Perl versions.

**Comment by KlaasT** [comment]
Edit: Quickly edited your opener to link the issues.

**Comment by gfrenoy** [comment]
Yes that'd be great if we can get rid of this dependency.  I tried to understand how it works but I failed so I suspect nobody is using it, anyway... Have a "cleaner" (less complicated) code base will definitely help !

**Comment by KlaasT** [comment]
@gfrenoy I tried to undertand Net::Proxy in the past and had a look if it can be replaced. A replacement using Perl libraries won't be simple. Basically you would have to write an own library which we would have to support. Not the way I would like to go.

In case of older SSH versions not working we could add a check to disable these new options if OpenSSH is too old.

**Comment by hanspr** [comment]
If there are no further comments or requests, we should close this issue and related ones: #218 , #67 and #280

**Comment by gfrenoy** [comment]
For #67, see checklist here : https://github.com/asbru-cm/asbru-cm/issues/67#issuecomment-570896646

**Comment by hanspr** [comment]
I think the list is complete we should close this.

**Comment by gfrenoy** [comment]
When we start a RDP terminal (with freerdp) and using a SOCKS proxy, it adds the "-o ProxyCommand ..." option ; does this makes sense ?

**Comment by hanspr** [comment]
No I do not think so, maybe the whole proxy set up should be inside the SSH method, the truth is I only took in consideration ssh while creating this code.

**Comment by hanspr** [comment]
Do you want me to change that or are you on it

**Comment by gfrenoy** [comment]
Doing nothing for now.  It would make sense to support the SOCKS proxy but I don't see that option in ```freerdp``` so I don't know exactly how to handle this.

**Comment by hanspr** [comment]
Send a PR, moving the settings for ssh only

**Comment by gfrenoy** [comment]
So I reviewed this again and here are some thoughts:

1) showing the "SOCKS" option does not make sense for VNC or RDP (and probably anything else except SSH...).
2) the concept of "Jump Host" should be extended to mimic what a SOCKS proxy is doing
3) Remmina calls this "SSH tunnel" 
![image](https://user-images.githubusercontent.com/981546/73133808-2912e980-402e-11ea-947a-289993e641c5.png)
4) As we see on the screenshot of #67, it is called "SSH gateway" in MobaXterm
![image](https://user-images.githubusercontent.com/981546/73133845-b48c7a80-402e-11ea-8e6e-a336b55a8705.png)
5) Reaching that level is maybe not that far since Jump Host is working fine for SSH connections
6) Main difference is that for VNC or RDP, an additional SSH connection need to be started first
7) How we create the tunnel may depend on the connection type (certainly the destination port) ; we might want to add how to handle this as a public method of the connection type in ```method```
8) To avoid spawning new ```pac_conn```, maybe we should use a SSH library (see [this](https://metacpan.org/pod/Net::SSH::Perl) or [that](https://metacpan.org/pod/Net::OpenSSH))

Let me see if we can translate those thoughts into a "to do" list:

[ ] Only show the "SOCKS" option for connection types that supports it (only SSH today, afaik)
[ ] Evaluate if there is any interest to use a perl library for SSH connections or re-use what we have in ```pac_conn```
[ ] Create helpers functions/modules to start a tunnel
[ ] Add a public method on connection classes to get the connection specific parameters for the tunnel
[ ] Show "Jump Host" for all connection types
[ ] If "Jump Host" is selected for something else than SSH, create the SSH tunnel first (querying the connection specific class and using the helpers function)
[ ] Make sure the destination of the connection is replaced by the tunneled resources
[ ] Stop tunnel when connection is stopped

Might look complicated at first glance by this is really what will definitely replace the use Net::Proxy and will give us the necessary flexibility to move forward.

Let me know if this make senses and how to polish the to do list before we really dig into the implementation...

**Comment by hanspr** [comment]
Ok, my thoughts on this

The only relevant point to me is the approach to opening the tunnel.

I've been searching for a way to use the current pac_conn, to open an extra ssh tunnel. Would like to stay away from more perl libraries and more new modules to accomplish again the same thing that pac_conn does.

Got 2 very interesting threads on how to accomplish that:

https://stackoverflow.com/questions/2241063/bash-script-to-set-up-a-temporary-ssh-tunnel/15198031#15198031

https://gist.github.com/scy/6781836

__Limitations__

Will only work with public keys or passwordless private keys, because we will not have the possibility to interact with the session. But apparently all other solutions rely on this same principle, and all users apparently are familiar with this approach. 

We will need to duplicate he interface to collect all tunnel connection data to again, similar to the jump host plus the dinamyc tunnel combined. So we have the information needed to open the tunnel: user, key, passphrase, local port to bind remote port to forward. So we can build the basic  `ssh -L ... `

If you work on the interface so it looks and works like you envision. And collect the values we need to open the extra ssh connection.

I code pac_conn to open the extra tunnel inside and look for the way to control all that tunnel stuff.

**Comment by gfrenoy** [comment]
Ok so we are at step "___Evaluate if there is any interest to use a perl library for SSH connections or re-use what we have in pac_conn___".  Fine, let's start with this and we can discuss the other points later.

I don't have any reference but spawning external processes and trying to control them looks like bad practice to me.

Said differently : it would be much better to rely on a robust, supported and future-proof implementation of a SSH library.  And as all the Ásbrú code is today written in Perl, we should find a robust, supported and future-proof SSH library...

So the real question is : does this "dream" library really exist ?  Shouldn't we contact the maintainers of these libraries and see how they see the future of what they did ?  And how they are supported in the various distributions ?  The maintainer of [Net::OpenSSH](https://metacpan.org/release/Net-OpenSSH), Salva, is apparently Spanish so you even share the same language :-)

I would think we should investigate a bit more on this before jumping on external processes ; in any case ```ssh``` is based on [OpenSSH](https://www.openssh.com/) so this is the root of everything and will not disappear soon.

Again, let's take a moment to think about this and evaluate the options.

**Comment by gfrenoy** [comment]
As we now have a working code to establish tunnels ; I guess the next step is to make sure we have the proper options according the type of connection.

Shouldn't we put this into the definition of the method ?

So a new method in all ```PACMethod_*.pm``` that will tell if they support SOCKS proxy or Jump Host (or any other we may add later) ?

**Comment by KlaasT** [comment]
However a socks Proxy doesn't have the same function as a jump host.

The socks proxy is more a proxy set up to regulate traffic and requests towards internet. Don't know how a jump host can replace that

**Comment by gfrenoy** [comment]
Yes so the idea would be to have each connection type know if it supports (or not) the various network arrangement.

Example with ```freerdp```

- freerdp does not support SOCKS proxy so we would hide this option for that connection type
- Jump Host is specific for SSH so we would also hide that option for that type
- SSH tunnel can be created so we would show that option for that type

**Comment by KlaasT** [comment]
Though If your Network ist protected by a proxy (which is not transparent, for example squid) then you won't be able to connect to the outside. Not even with jump host etc. that is what the socks proxy option should be for

**Comment by gfrenoy** [comment]
Yes but if the client (example ```freerdp```) does not support a SOCKS proxy ; we are stuck... Said differently : removing ```Net::Proxy``` let use rely on the options of each type of connections.

**Comment by KlaasT** [comment]
I think you don't understand my point. Do we have any equivalent of SOCKS Proxy support for SSH?

I don't think neither VNC, SSH or RDP will support SOCKS proxy native. There always have to be a wrapper. Jumphost won't help you if you have to pass a proxy. A proxy is for filtering traffic towards the outside of your local network and companies may use this.

Means if we decide there won't be any proxy support for the software in future this can be removed completely (usually a proxy setting is global for a piece of software). I don't know if we will make some people unhappy with this.

The jumphost feature is really great, no question I like it though we have to stop thinking this is a replacement for a proper proxy support.

**Comment by gfrenoy** [comment]
> Do we have any equivalent of SOCKS Proxy support for SSH?

As "client", yes, check ```ProxyCommand``` ; this is how it is implemented now (thanks again @hanspr ;p)

https://github.com/asbru-cm/asbru-cm/blob/0e3990e137ee993566440a12ac97a1a8587b1f12/lib/pac_conn#L888-L895

> There always have to be a wrapper.

If we take the assumption that we need to remove ```Net::Proxy``` (check [your own comment](https://github.com/asbru-cm/asbru-cm/issues/323#issuecomment-569681672)), what would be the alternative ?

>  I don't know if we will make some people unhappy with this.

Don't know either.  v6.1 is ready for testing !  Let's try to find some testers :)

**Comment by KlaasT** [comment]
> > Do we have any equivalent of SOCKS Proxy support for SSH?
> 
> As "client", yes, check `ProxyCommand` ; this is how it is implemented now (thanks again @hanspr ;p)
> 
> https://github.com/asbru-cm/asbru-cm/blob/0e3990e137ee993566440a12ac97a1a8587b1f12/lib/pac_conn#L888-L895

This looks good so far. Whereas a proxy setting could be global for all. Usually you don't have one proxy per service, you normally have one proxy for your entire network.

> > There always have to be a wrapper.
> 
> If we take the assumption that we need to remove `Net::Proxy` (check [your own comment](https://github.com/asbru-cm/asbru-cm/issues/323#issuecomment-569681672)), what would be the alternative ?

I don't know. I didn't really have a chance to check for an alternative until it was decided to remove this entirely ;-)

> 
> > I don't know if we will make some people unhappy with this.
> 
> Don't know either. v6.1 is ready for testing ! Let's try to find some testers :)

Yes we need to test this. Here is an example for a proxy connection. (copied from Wikipedia). Just replace Facebook by any remote service:

![grafik](https://user-images.githubusercontent.com/1096408/73641142-d78ede00-466f-11ea-92e6-abf7ae29ba0a.png)

Proxies can be transparent (inline) like in our company. In this case you won't have to configure anything inside your software to get out of the local network.

If your proxy is next to your outgoing path you will need to configure it in every piece of software you have.

![grafik](https://user-images.githubusercontent.com/1096408/73641502-6865b980-4670-11ea-8539-15c7ed994eb4.png)

I hope this makes it clear what a proxy is and what a jumphost is about.

**Comment by hanspr** [comment]
I'm the less versed on networking here, so if I talk nonsense ignore me.

As far as I understand, this discussion

SOCKS Connectivity availability

|Service|Global|Per connection|
|--------|-------|----------------|
|SSH|Yes (1)|Yes (2)|
|VNC|No|No|
|RDP|No|No|

1. Configured in __Preferences > Networking__, Later each connection has as a default __Use Global Settings__ in "Networking Tab"
2. Configured per connection in "Networking Tab"

__VNC / RDP__

Steps to allow VNC / RDP through a SOCKS Server

1. Create connection A: configure an SSH session that goes out with proxy settings to your destination and additionally add a port forward in the tunnels tab
2. Create connection B: your VNC / RDP session connecting locally to your the tunnel opened by connection A

__Connection A__

![imagen](https://user-images.githubusercontent.com/1572396/73675241-a74b3d80-4677-11ea-8060-3ebcd70ad82d.png)

![imagen](https://user-images.githubusercontent.com/1572396/73675250-ab775b00-4677-11ea-97b3-5968a3e60d1e.png)

__Connection B__

![imagen](https://user-images.githubusercontent.com/1572396/73675268-b336ff80-4677-11ea-8437-17a6c8e0e383.png)

Does this makes sense?

If it does, there is a way out, the only thing is the setup, and that is why I wanted to have the option to link connections between them so : opening "B" would check if "A" if open, if no would open it first and the open "B".

Or we add a more complex set up on VNC/RDP connection method configurations and allow and try to duplicate the logic above and again spawn the tunnels internally like we already do for a normal VNC / RDP connection.

**Comment by KlaasT** [comment]
Thanks for the explanation. It sounds like it would work. I can't test it as I don't have a SOCKS proxy somewhere, however I could set one up.

Of course this setup would make things more complex and we should write some documentation for it. Would you mind if I take your text and screenshots to create some wiki entries? I would expect people asking how this would work and at release this should be made clear in the release notes.

And no I would not ignore you if you talk nonsense ;-) It is always quite interesting to have a look at a certain topic from different perspectives.

**Comment by hanspr** [comment]
@KlaasT 

>I can't test it as I don't have a SOCKS proxy somewhere, however I could set one up.

It would be nice to have a way to test all this, I still have a lot of questions about the magic in : `nc -x $proxy_ip:$proxy_port %h %p'`

I know it works because the person reporting this issue originally said it did. But I still can not understand some of its parameters. For example,

* When and where are __%h__ , __%p__ set?. Not in pac_conn for sure so they are going blank. Should we set them?, in which cases?
* We ask for the proxy user and password. Don't see where to pass those parameters to the proxy command. So how and when are they used?, It will be handled by expect?

This is why It would be very useful to setup a socks proxy and do some experimentation on all this combinations and complete the code or commands to make it work.

**Comment by KlaasT** [comment]
netcat (nc) is great. I managed to make our TACACS+ server to understand IPv6 by using nc.

I'll try to setup a socks proxy. I won't make it today but I should be able to create one with authentication and so on.

**Comment by hanspr** [comment]
@KlaasT , @gfrenoy 

What if, we extend the Networking configuration for VNC / RPD only, to look like this

![imagen](https://user-images.githubusercontent.com/1572396/73687983-bbe7ff80-4690-11ea-8ac2-df582db1a6ca.png)

And then use the same tunnel that we are already opening for VNC and RDP, to look something like this (maybe the order of the options have to be different, or maybe we can add the proxy instructions inside the config file that is created on the fly)

`ssh  -o ProxyCommand='nc -x $proxy_ip:$proxy_port  %h %p' -F $CFG_DIR/tmp/$uuid.conf -S $CFG_DIR/tmp/$uuid.ctl -f -N -T -M -L $LPORT:$IP:$PORT jumpserver`

Would it work?

**Comment by gfrenoy** [comment]
> What if, we extend the Networking configuration for VNC / RPD only

Yes.  Or even, if we can find the generic way, all of them and the global settings, that'd be fantastic :)

> ssh -o ProxyCommand='nc -x $proxy_ip:$proxy_port %h %p' -F $CFG_DIR/tmp/$uuid.conf -S $CFG_DIR/tmp/$uuid.ctl -f -N -T -M -L $LPORT:$IP:$PORT jumpserver
> Would it work?

No, if we only have a SOCKS proxy, we don't have any "jumpserver" to use.

But, after [some readings](https://notes.tweakblogs.net/blog/7955/using-netcat-to-build-a-simple-tcp-proxy-in-linux.html), this should work:

```
rm -f /tmp/asbru_pipe_$UUID
mkfifo /tmp/asbru_pipe_$UUID
nc -l -p $LPORT </tmp/asbru_pipe_$UUID | nc -x $proxy_ip:$proxy_port $ip $port >/tmp/asbru_pipe_$UUID
```

where
- ```$UUID``` : to have one two ways pipe per connection
- ```$LPORT``` : an arbitrary (free) port on the Ásbrú computer
- ```$proxy_ip``` and ```$proxy_port``` : address of the SOCKS proxy
- ```$ip``` and ```$port``` : address and port of the destination server

notes:
- not sure to understand how username/password would work

> I'll try to setup a socks proxy.

Well, a very simple one can be created using ```ssh -D9876 your_ssh_gateway```

> Would you mind if I take your text and screenshots to create some wiki entries?

A user manual for Ásbrú would be terrific :-)

**Comment by KlaasT** [comment]
> Well, a very simple one can be created using ssh -D9876 your_ssh_gateway

Not every system administrator has a SSH gateway to create a connection to. We need to think beyond the SSH world.

> A user manual for Ásbrú would be terrific :-)

Yes a user manual would be great and I would ask all of us who are creating new functions or cleaning them up (even for API stuff) to document the functionality bit by bit. Will make things easier for users and future contributors.

**Comment by gfrenoy** [comment]
>> Well, a very simple one can be created using ssh -D9876 your_ssh_gateway
> Not every system administrator has a SSH gateway to create a connection to. We need to think beyond the SSH world.

Just for testing !

**Comment by KlaasT** [comment]
Do as you prefer.

**Comment by gfrenoy** [comment]
> Do as you prefer.

?!?

I was just telling Hans that if he needs to have a SOCKS proxy for testing, he can have one by using the command ```ssh -D9876 your_ssh_gateway``` ; see the man page:

> -D [bind_address:]port
> Specifies a local ''dynamic'' application-level port forwarding. This works by allocating a socket
> to listen to port on the local side, optionally bound to the specified bind_address. Whenever
> a connection is made to this port, the connection is forwarded over the secure channel, and the
> application protocol is then used to determine where to connect to from the remote machine.
> Currently the SOCKS4 and SOCKS5 protocols are supported,
> and **ssh will act as a SOCKS server**

**Comment by hanspr** [comment]
I think that if @KlaasT , can help us out with a SOCKS proxy, would be grate to test on a more real environment.

> No, if we only have a SOCKS proxy, we don't have any "jumpserver" to use.

This test worked for me

```
# Open the socks proxy server for testing
ssh -D9876 destination

# Open the connection to the final destination using the socks proxy
ssh -L5900:finaldestination:5900 -o ProxyCommand='nc -x 127.0.0.1:9876 %h %p' user@destination

#launch vnc
vncviewer localhost:5900

#Success 
```

Then I tried this, and it worked too.

```
# Open the socks proxy for testing
ssh -D9876 destination

# Open the connection to the final destination using the socks proxy, and sent to the background with a socket like we do for normal vnc connections

ssh -S test.ctl -f -N -T -M -L5900:finaldestination:5900 -o ProxyCommand='nc -x 127.0.0.1:9876 %h %p'  user@destination

# launch vnc
vncviewer localhost:5900

#Success 
# Exit VNC

# close tunnel
ssh -S test.ctl -T -O exit user@destination
```

Isn't this what we are looking for?

Is the same principle that we have currently using with vncviewer and a tunnel, but adding the proxy command, no?

Still no idea about user and password, but is the first step.

**Comment by hanspr** [comment]
And now that I see it, this would work too, is the same.

```
ssh -o ProxyCommand='nc -x $proxy_ip:$proxy_port %h %p' -F $CFG_DIR/tmp/$uuid.conf -S $CFG_DIR/tmp/$uuid.ctl -f -N -T -M -L $LPORT:$IP:$PORT jumpserver
```

Remember the we use the name jump server for the first server we connect your "gateway"?.

And in the file we store

IP,PORT and identity file. But is the same

**Comment by gfrenoy** [comment]
> I think that if @KlaasT , can help us out with a SOCKS proxy, would be grate to test on a more real environment.

Of course.  Sorry if I was not clear enough but my only point was that you can quickly create a simple SOCKS server by using the -D option of SSH.  Only for testing and even though you would not have authentication so that's not the perfect testing environment but "good enough" to start with this.

> Isn't this what we are looking for?

No because you *do not* have a SSH server to connect to !

So the use case is:  you are behind a SOCKS server proxy and you do not have a SSH server available.

All traffic needs to be redirected to the SOCKS server.

So in you example above:

- You create a test proxy : ```ssh -D9876 ssh_test``` ; good
- Then you can *only* use port 9876 to make your VNC connection ; you cannot use the SSH (22) port anymore :)

**Comment by hanspr** [comment]
>No because you do not have a SSH server to connect to !

I was under the assumption that any machine we will try to connect has an ssh server to allow to create tunnels to it (Windows, Mac, Linux), or a middle gateway that has ssh capability to create ssh tunnels and forward a connection to the destination (Windows, Mac, Linux).

Under that assumption is that I proposed to replace net::proxy with ssh option parameters.

So we are trying to solve, direct connections:

`VNC/RDP --> SOCKS --> Machine without ssh`

* Shall we bring back net::proxy to solve that case only?
* Or look for another kind of service that allows to port forward connections like net::proxy does (have not found one)?
* Implement our own solution of a tiny proxy server?
* Or drop that support?

**Comment by gfrenoy** [comment]
> So we are trying to solve, direct connections:
> VNC/RDP --> SOCKS --> Machine without ssh

Exactly :)

> Shall we bring back net::proxy to solve that case only?

If this is hardly supported on some popular distributions, we have to drop it.

> Or look for another kind of service that allows to port forward connections like net::proxy does (have not found one)?

Me neither so not an option, I do fear.

> Implement our own solution of a tiny proxy server?

Check the netcat option [above](https://github.com/asbru-cm/asbru-cm/issues/323#issuecomment-581630244).  I gave it a try (manually), it works great.  It looks a bit tricky or even scary but this is a relatively simple "two ways" pipe.  If we make a function like you did for SSH tunnel, it can be achievable (I assume).  If you don't "feel" it or don't have time, let me know ; I'll give it a try.

> Or drop that support?
> And tell windows users to install openssh to make it work (...)

Would be sad and there's is an option!

**Comment by hanspr** [comment]
>If you don't "feel" it or don't have time, let me know ; I'll give it a try.

If you already understand it and have the time, you would be a better option. If you get stocked at some point you can ask and will see if we can get it done.

**Comment by gfrenoy** [comment]
@hanspr Take a look, hope it makes sense.

We'll now need to try with a user/password !  That'll for sure not work today ... I even suspect we'll need to use ```ncat``` instead of ```nc```.

But first, have some sleep :zzz:

**Comment by hanspr** [comment]
With reference to user and password.

* User and password currently only work for http
* Here this person solved it using a 3rd party utility https://unix.stackexchange.com/questions/447780/ssh-through-authentication-requiring-proxy
* corkscrew is a github proyect : https://github.com/bryanpkc/corkscrew

Will keep digging to see if something else comes up. 

I sent a PR with another scenario solved: vnc/rdp, ssh tunel, socks

**Comment by hanspr** [comment]
Forgot to mention found this little socks server to run locally, it complains when no password so at leas that works

https://github.com/kaimi-io/socks5-proxy-server

**Comment by hanspr** [comment]
Found out that corkscrew is in the ubuntu repos, will test.

If it works, perhaps what we could do is to tell the user that he needs to install the program for socks proxy with password. To avoid creating a dependency to it.

**Comment by gfrenoy** [comment]
> perhaps what we could do is to tell the user that he needs to install the program for socks proxy with password

Hu?  Why ?  Ásbrú is about connecting to an existing proxy server.  Typically it's an enterprise proxy server that you want to cope with to connect to external resources.

So no reason to install one on your own machine (I mean: except for testing purposes...).

**Comment by gfrenoy** [comment]
Thanks to [Dante](https://www.inet.no/dante/) and a very simple [configuration file](https://gist.github.com/gfrenoy/17ca766ef2069106b9b2252bae125c2d), I've been able to setup a simple SOCKS5 proxy and implement a version that use [ncat](https://nmap.org/ncat/).

I played around and it worked fine for me ... More tests will be required and I'm sure there's room for improvement ...

But I believe we have now a first "release candidate" for 6.1 ...

Don't you tink ?

**Comment by hanspr** [comment]
I think is fantastic and if you think we're ready to go, lets do it.

PS. I'm very busy this month, will try to answer as much as possible, but I will have to slow down on coding, Sorry.

**Comment by gfrenoy** [comment]
So let's consider this closed and let's now call for testers of a first 6.1 release candidate :)
