### ISSUE TITLE
Dropping support for legacy distributions

### ISSUE THREAD

**Issue by KlaasT** [asbru-cm/asbru-cm#325]
I am considering dropping support for legacy distributions which don't receive any support from the maintainers. These include:

Ubuntu Trusty (25. April 2019)
Ubuntu Coscmic (18. Juli 2019)
Fedora 26 (28. May 2018)
Fedora 27 (30 November 2018)
Fedora 28 (28. May 2019)

If anyone is greatly opposed to this he may now speak ;-)

**Comment by Mjolinir** [comment]
I have no objection, but would like to ask for support for Fedora 31 to be added. There are no builds available for Fedora 31 as of yet, I have been installing manually.

**Comment by KlaasT** [comment]
There are already builds for Fedora 31. However these are only available for the current snapshots at the moment:

$ curl -s https://packagecloud.io/install/repositories/asbru-cm/snapshots/script.rpm.sh | sudo bash
$ sudo dnf install asbru-cm

Should work for you.

As soon as the next version is released you will find Fedora 31 in the main repository too.

**Comment by Mjolinir** [comment]
Yes, that's what I meant, in the main repository. Is there a reason that its not in the main repository? Is only the previous release in the main repo?

**Comment by KlaasT** [comment]
We have no 6.0 release yet. New packages for the main repository are only generated when we release a new version by tagging a certain state of the code.

**Comment by Mjolinir** [comment]
Ok, I think I at least partially understand. Right now, if I were to do a fresh install Fedora 31 and then do:

$ curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.rpm.sh | sudo bash
$ sudo dnf install asbru-cm

There would be nothing found to install. I am not sure why there is nothing in the main repo. Why is the current stable version not built for Fedora 31?

**Comment by gfrenoy** [comment]
Well, the right question is probably : is there any reason to not consider 6.0 as the "stable" version ?

**Comment by KlaasT** [comment]
> 
> 
> Well, the right question is probably : is there any reason to not consider 6.0 as the "stable" version ?

When I look at all the issues still appearing the UI still seems to need some polishing.

**Comment by gfrenoy** [comment]
>  the UI still seems to need some polishing

For sure but does it really need more polishing than 5.1 ?  Said differently : what are the  major regression we still need to fix before moving on ?

**Comment by KlaasT** [comment]
Closing #325. New packages are being build right now.
