### ISSUE TITLE
Click on re-attached tab, open an empty window

### ISSUE THREAD

**Issue by nikuzz** [asbru-cm/asbru-cm#327]
**Describe the bug**
When dragging a tab out and then right-click inside its terminal and click "Attach Window to main tab bar", any click on the same tab open an empty window.

**To Reproduce**
1. Open a "local" shell tab (ctrl+shift+t)
2. Detach this tab dragging it out of the main tab bar (or right click on tab, then "Detach TAB to a new Window")
3. Right-click inside its terminal and click "Attach Window to main tab bar"
4. Click on "info" tab
5. Click back on the "local" tab
6. An empty window will appear

**Expected behavior**
The empty window shouldn't appear.

**Screenshots**
![Captura de pantalla de 2020-01-03 12-08-44](https://user-images.githubusercontent.com/17493820/71720407-ef313780-2e21-11ea-9d75-afd587e08708.png)

**Desktop:**
 - OS: Ubuntu 19.10
 - Version v.6.0.0

**Comment by gfrenoy** [comment]
Thanks for your feedback Nico.  I do confirm the buggy behavior... No quick fix right now, I'll need to investigate further.

**Comment by gfrenoy** [comment]
Ok I think I found the issue !  It will be fixed with the next commit that will be available in a few minutes in the snapshot release (and will be available in the next release 6.0.1).

Thanks again for the report and your support to the project !
