### ISSUE TITLE
Password is visible on the taskbar tooltip for RDP session (xfreerdp)

### ISSUE THREAD

**Issue by danielbgto** [asbru-cm/asbru-cm#328]
**Describe the bug**
Password is visible on the taskbar tooltip for RDP session.

**Expected behavior**
Password to be hidden.

**Screenshots**
![image](https://user-images.githubusercontent.com/5525957/71722114-7e454c00-2e30-11ea-84a3-6631dd15c645.png)

**Desktop (please complete the following information):**
Fedora 31 Cinnamon spin
Package installed: asbru-cm-6.0.0-1.fc31.noarch

**Comment by gfrenoy** [comment]
Thanks for your feedback !  It is now fixed in the master branch and will be released in 6.0.1.
