### ISSUE TITLE
Loki branch

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#330]
Hi ....
May you please clarify the meaning of **Beware that Loki can sometimes behave in a malicious manner to you. You might think of "sid"** ?
Thank you.

**Comment by gfrenoy** [comment]
"loki" should be considered as the unstable branch of Ásbrú CM.

See https://en.wikipedia.org/wiki/Loki and https://www.debian.org/releases/sid/

**Comment by popxunga** [comment]
Thanks for the clarification.

**Comment by grey-olli** [comment]
Well.. what is "sid" acronym here? Could you please explain it in documentation - 'malicious' in my mind associates w/ password stealing and malware. I guess it's not. But what do you mean by 'sid'?

**Comment by gfrenoy** [comment]
"sid" is the name of the unstable branch, https://www.debian.org/releases/sid/.

And "malicious" should be understood as "unexpected", "unpredictable", "unstable" ... well in short, a test branch...

I've reviewed a bit the README file to clarify this.
