### ISSUE TITLE
RDP keyboard stops to work

### ISSUE THREAD

**Issue by Adorid** [asbru-cm/asbru-cm#331]
When you start rdp session keyboard works, but if you switch to another tab and then return to rdp session keyboard not working anymore. Its just happen with rdp sessions, for ssh dont have problems.
But its just happen if switch to another tab, but in case if from new session switch to browser and then return then keyboard still works correctly.

I got another pc with older asbru version where is works correctly, so its not working correctly on latest versions. But for older version got problem if you have open rdp session and if you lock linux pc then after unlock keyboard not working in remote desktop tab too.

I use linux mint, dunno if this problem is for other linux version.

**Comment by gfrenoy** [comment]
Can you clarify the versions you are referring to ?

(note: It looks related to #148)

**Comment by gfrenoy** [comment]
Ok so I believe it's related to the change in PACMain (see [here](https://github.com/asbru-cm/asbru-cm/commit/4f4bc1d6201d2decd4d8516f07cbf10778da46d4#diff-062dcb4c9d546b670760e95d865035a2)).

Can you try to move the line 2217 one line above and let us know if it fixes the issue for you ?
(it did for me...)

**Comment by popxunga** [comment]
Seeing the same on EL7 but just for tabbed RDP sessions on the Asbru main window.
The issue does not occur with untabbed RDP sessions.

**Comment by gfrenoy** [comment]
Can you try to apply https://github.com/asbru-cm/asbru-cm/commit/fc2aebbce8acc32b3223b3eca88bbb0f91327076 and let us know if it fixes the issue ?

**Comment by popxunga** [comment]
Yes ... just tried with the latest snap version (asbru-cm-6.0.2~1578150791-1.el7.noarch) and it works fine now with the RDP tabbed sessions.

**Comment by gfrenoy** [comment]
Thanks for the feedback !

We'll likely release 6.0.2 by the end of next week...

**Comment by Adorid** [comment]
ok, I will wait for next release, for me its easier to update from the repository.

**Comment by gfrenoy** [comment]
@Adorid you can also use the "snapshot" version (see instructions [here](https://github.com/asbru-cm/asbru-cm/wiki/Installation-on-Mint)).

**Comment by hanspr** [comment]
Something is broken, I can not ssh with this changes I get blank windows

![imagen](https://user-images.githubusercontent.com/1572396/71769191-709cce80-2ee3-11ea-94ba-322b1eceb107.png)

**Comment by hanspr** [comment]
It only happens in tabbed windows, normal windows work

![imagen](https://user-images.githubusercontent.com/1572396/71769201-975b0500-2ee3-11ea-85d4-2f0be859f1ab.png)

**Comment by gfrenoy** [comment]
@hanspr This issue is related to RDP ... Let's try to find how the right way to fix your issue in #334.  Thanks.

**Comment by Adorid** [comment]
Thanks, looks like now using snapshoot version works correctly rdp

**Comment by mnadesu** [comment]
Hello dear asbru-cm Team I once looked around in the Internet because of the Windows RDP Problem. I have made it so far that I can get to the Windows login screen but then the program says that the username or password is wrong. This same username and password have been tested in Remmina there it goes. I would like to switch from Remina to asbru. Currently the only obstacle is windows RDP, otherwise I like it so far. Can you help me here?
greeting
Mathi
