### ISSUE TITLE
asbru-cm.spec file - minor correction

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#332]
Hi ...

The week day name for the 5.2.0 version in the spec file is incorrect.
Where is ...
**Mon** Apr 19 2019 Ásbrú Project Team <contact@asbru-cm.net> 5.2.0
it should be ...
**Fri** Apr 19 2019 Ásbrú Project Team <contact@asbru-cm.net> 5.2.0

Thanks.

**Comment by KlaasT** [comment]
Thanks. Closed #332
