### ISSUE TITLE
local command automated username error.

### ISSUE THREAD

**Issue by dengan** [asbru-cm/asbru-cm#341]
There is a copy/paste error in original version of PAC, which will fail local command automated authentication with username.

details are as follows:

lib/PACUtils.pm
   2854         while ($string =~ /<IP>/go) {
   2855             $string =~ s/<IP>/$ip/g; $ret = $string;
   2856         }
   2857         while ($string =~ /<USER>/go) {
   2858             $string =~ s/<USER>/$ip/g; $ret = $string;
   2859         }
where line 2858 should be 
2858             $string =~ s/<USER>/$user/g; $ret = $string;

**Comment by dengan** [comment]
Step to reproduce:
1. define a local command for sftp using filezilla, for example:

![image](https://user-images.githubusercontent.com/14981961/71810619-afa95c00-306a-11ea-9139-f9cdcfc9e00e.png)

2. setup remote connection, and right client to use sftp local command to start the filezilla session

3. authentication error occurs unless the line 2858 fixed with a restart

**Comment by gfrenoy** [comment]
Thanks for the report !  A fix should be available in the snapshot version in a few minutes.

Feel free to re-open if should still have a problem.
