### ISSUE TITLE
The problem of displaying the connection tree

### ISSUE THREAD

**Issue by shapovalovanton** [asbru-cm/asbru-cm#342]
![image](https://user-images.githubusercontent.com/31802863/71806383-55f86000-3071-11ea-8436-6b6787329a6b.png)

The connection tree is displayed incorrect

**Comment by hanspr** [comment]
This is a recurrent report, follow #306

**Comment by gfrenoy** [comment]
@shapovalovanton Can you confirm the version you are using ?

**Comment by hanspr** [comment]
@gfrenoy 

May be is referring is that the padding of the arrow and folder is reduced in deeper indentations.

To compact the tree a bit, I introduced this line

https://github.com/asbru-cm/asbru-cm/blob/8117e08961d78f8c18c36f90f3e3c257db17447a/lib/PACMain.pm#L529

in PACMain.pm

You may remove it to remove that effect.

**Comment by gfrenoy** [comment]
With v6.0.2, it does not behave like reported ; here is the result of a simple test with 6 levels of sub-folders
![image](https://user-images.githubusercontent.com/981546/71932615-7541db00-31a0-11ea-9897-ed5d9871d780.png)

@shapovalovanton can you also let us know the system that you are using (Ubuntu, Arch, Fedora / Gnome/KDE, ...) ?

**Comment by hanspr** [comment]
I think the effect is visible when the last folder is closed no open

![imagen](https://user-images.githubusercontent.com/1572396/71933086-ebc1e700-3166-11ea-9c85-5ad4c3556255.png)

**Comment by gfrenoy** [comment]
Got it !  Thanks for the additional information Hans :)

At this stage, I would say that we will not fix this a "live with it" until we indeed find a replacement for the tree widget (part of the #306 discussion).

**Comment by shapovalovanton** [comment]
> @shapovalovanton can you also let us know the system that you are using (Ubuntu, Arch, Fedora / Gnome/KDE, ...) ?

Hi, gfrenoy.
I use Ubuntu MATE 18.04 and Asbru CM 6.0.1
