### ISSUE TITLE
Keepass does not work in latest

### ISSUE THREAD

**Issue by accessone67** [asbru-cm/asbru-cm#343]
**Describe the bug**
After updating asbru to latest version It wont load if I use my keepass settings. I had to downgrade disable keepass and upgrade again, then asbru will load. But if I want to configure my keepass whit latest asbru I get error

**To Reproduce**
1. Go to asbru settings
2. Click on keepass and enableing it
3. See error
sJan  6 10:44:33 tamps asbru-cm.desktop[27882]: *** unhandled exception in callback:
Jan  6 10:44:33 tamps asbru-cm.desktop[27882]: ***   undefined value for mandatory argument 'text' encountered at /opt/asbru/lib/PACKeePass.pm line 279.
Jan  6 10:44:33 tamps asbru-cm.desktop[27882]: ***  ignoring at /usr/share/perl5/Gtk3.pm line 546.

If I dont disable keepass before upgrade I get this error after I want to startup asbru
Jan  6 10:41:12 tamps asbru-cm.desktop[27882]: *** unhandled exception in callback:
Jan  6 10:41:12 tamps asbru-cm.desktop[27882]: ***   undefined value for mandatory argument 'text' encountered at /opt/asbru/lib/PACKeePass.pm line 279.
Jan  6 10:41:12 tamps asbru-cm.desktop[27882]: ***  ignoring at /usr/share/perl5/Gtk3.pm line 546.

**Expected behavior**
To get keepass working like in old version

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Comment by gfrenoy** [comment]
I would presume it's 6.0.1 but can you confirm the version number you are using ?

**Comment by accessone67** [comment]
I got this problem from bouth versions in 6. just did upgrade to 6.0.1-1 and erros is still there

Jan  7 09:25:37 tamps asbru-cm.desktop[1942]: INFO: Ásbrú started (asbru-cm) with PID 1942
Jan  7 09:25:37 tamps asbru-cm.desktop[1942]: INFO: Desktop environment detected : gnome-shell
Jan  7 09:25:38 tamps asbru-cm.desktop[1942]: INFO: Using config directory '/home/tambet.paide/.config/pac'
Jan  7 09:25:38 tamps asbru-cm.desktop[1942]: INFO: Used config file '/home/tambet.paide/.config/pac/pac.nfreeze'
Jan  7 09:25:40 tamps asbru-cm.desktop[1942]: undefined value for mandatory argument 'text' encountered at /opt/asbru/lib/PACKeePass.pm line 279.

Only way to use asbru again is to downgrade "apt install asbru-cm=5.2.1-1" where it works again

**Comment by gfrenoy** [comment]
@accessone67 Sorry but I was not able to reproduce the issue so far.

At this stage I would suspect the content of your file that is not correctly decoded with the new version because of some utf8 changes that has been made ; but it's only a wild guess !

What I did is:
 - Create a new KeePass file ```test.kdbc```
 - In Ásbrú v5.2.1, enable KeePass, select the file, enter the password and clicked "refresh"
 - It worked fine
 - Then, using the same configuration, started Ásbrú 6.0.2
 - It started fine and I could go back to the same KeePass configuration without seeing any error message.

Can you try with a new file to see if it makes a difference ?

Thanks.

**Comment by hanspr** [comment]
Could you comment line 279

https://github.com/asbru-cm/asbru-cm/blob/ed15cd0134fced640f9fe2ab52f128139770e6b8/lib/PACKeePass.pm#L279

To see if the error moves to another line or if it works.

If it works, it means the $url variables comes undefined for some unknown reason to me right now, but it could be patched to consider this kind of situations.

**Comment by accessone67** [comment]
indeed, after commenting out line 279 it loaded up and is ready to be use. Thx hanspr :)

**Comment by hanspr** [comment]
@accessone67 

Good to know, a Pull Request has been sent to fix the issue. Right know you will not have url values loaded, because the commented line.
