### ISSUE TITLE
Host key verification throws script error

### ISSUE THREAD

**Issue by Keridos** [asbru-cm/asbru-cm#344]
**Describe the bug**
Regression causing a similar issue as #145 

**To Reproduce**
1. Connect to openssh server who asks "Are you sure you want to continue connecting(yes/no/[fingerprint])?"
2. See error

![image](https://user-images.githubusercontent.com/2742845/71818157-7849a800-3088-11ea-9da7-e18d433f3555.png)

**Expected behavior**
It should connect successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/2742845/71818178-85669700-3088-11ea-9fea-28475d2609a1.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 6.0.2 (commit 31d4c55b281efa196e25187a2da7730232e8df8c)

**Additional context**
Worked fine in 6.0.1

**Comment by gfrenoy** [comment]
Thanks for the report ! A fix should be available in the snapshot version in a few minutes.

Feel free to re-open if should still have a problem.
