### ISSUE TITLE
Session disconected after sucessful login and interactive menu showed

### ISSUE THREAD

**Issue by gizav** [asbru-cm/asbru-cm#35]
Hello,
I have an issue when I try to connect by SSH to an appliance with a interactive menu (I'm referring to E.F.A. project).  
After the login, the interactive menu appear correctly, but after the choice of the function (with a number or a letter) nothing succeding and connection go in timeout.
Is this a known issue?

Thanks.

Regards.

**Comment by gfrenoy** [comment]
Hi Giovanni.  This description does not ring any bell... Would you have some more information on how we could reproduce that problem ?  Or let us know if you see any error message somewhere ?

**Comment by gizav** [comment]
Hi Gaëtan,
no error is displayed, but I have just solved the problem. I have find an old [discussion](https://sourceforge.net/p/pacmanager/bugs/161) for a similar problem.

Simply, in "Preference->Main Options->Command prompt" I changed the default regexp with this:
`[#%\$>\]]|\:\/\s*$`
(I added a bracket square into the character class) and now the menu work. I hope this can be help someone else. 
Only for a better understanding, I attach a screenshot where it is showed the menu and the prompt that I meant :
![selezione_001](https://user-images.githubusercontent.com/17712187/33809730-b95a2b62-ddfb-11e7-8c18-c28e645ce481.png)

**Comment by gfrenoy** [comment]
Thanks for sharing your solution !  This should certainly be part of our future "user guide" :)
