### ISSUE TITLE
Port asbru_from_superputty.py to python3

### ISSUE THREAD

**Issue by egmontkob** [asbru-cm/asbru-cm#355]
Followup of #354 

There's a utility `utils/asbru_from_superputty.py` which only works with python2. Now that python2 has officially EOL'ed, this script should be ported to python3 (or rewritten in perl, or dropped).

**Comment by egmontkob** [comment]
Porting to python3 is perhaps as simple as putting `print`'s parameter in parenthesis. At least then it doesn't fail with syntax error.

**Comment by gfrenoy** [comment]
This looks to be something within my reach ;-p
