### ISSUE TITLE
ssh compression activated by change of other options

### ISSUE THREAD

**Issue by merikz** [asbru-cm/asbru-cm#359]
**Describe the bug**
When adding a Dynamic Socks Proxy (by clicking the "Add" button) for a connection, the "Use Compression" option is automatically activated.

**To Reproduce**
1. Create a new connection by clicking the "New CONNECTION" button in the connection tree panel
2. In the "Edit Connection" window -> "SSH Options": Disable the "Use Compression" option
3. In the "Dynamic Socks Proxy" tab: Click the "Add" button.
4. The "Use Compression" option is erroneously enabled again.

The same thing happens when clicking "Add" in any of the tabs, "Local Port forward", "Remote port forward", "Dynamic socks proxy" or "Advanced Options". "Use compression" always gets enabled.

**Expected behavior**
The "Use Compression" option should only change when the user clicks the check box.

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 18.04.3 Cinnamon 
 - asbru-cm v6.0.2

**Comment by gfrenoy** [comment]
Thanks for the suggestion and very detailed description !  It indeed makes the UX better.

Changes is now available on the loki branch and will be released in v6.1 soon.
