### ISSUE TITLE
Renaming node adds -

### ISSUE THREAD

**Issue by clickwir** [asbru-cm/asbru-cm#36]
When renaming a connection in the list either via right click > "Rename Connection" or via F2, the box that comes up automatically adds " - " to the beginning of TITLE when any change is made to the NAME option. 

Not sure why it does this, I don't see a good reason. It looks out of place and doesn't seem to be useful in any other screen. Maybe it's meant to be a separator, but I haven't found a screen that shows it being useful like that.

**Comment by gfrenoy** [comment]
The idea was to prefix the name with the parent name, example:
![image](https://user-images.githubusercontent.com/981546/34017426-029a870e-e126-11e7-9b42-1273f8ec1a33.png)

But if your connection is at the root, there's no parent name and it becomes indeed confusing !

Should be easy to fix.

**Comment by gfrenoy** [comment]
Oh and, guess what, by looking at the code, I found out there is an option for that:
![image](https://user-images.githubusercontent.com/981546/34017889-cb9de096-e127-11e7-8cbe-7598c90577ec.png)

**Comment by gfrenoy** [comment]
I changed the code so that it does not add a dash sign (-) when the parent folder is empty.
