### ISSUE TITLE
Please correct Debian dependencies entry in wiki

### ISSUE THREAD

**Issue by SwampRabbit** [asbru-cm/asbru-cm#361]
Please correct the wiki entry under "Manual Installation" for Additional information for Debian systems - System packages to match the actual required dependencies and or the source package provided Debian control file.

The control file under the debian folder provided by the source package has the following:
`**Depends:** perl, libvte-2.91-0, libcairo-perl, libglib-perl, libpango-perl, libsocket6-perl, libexpect-perl, libnet-proxy-perl, libyaml-perl, libcrypt-cbc-perl, libcrypt-blowfish-perl, libgtk3-perl, libnet-arp-perl, libossp-uuid-perl, openssh-client, telnet, ftp, libcrypt-rijndael-perl, libxml-parser-perl, libcanberra-gtk-module, dbus-x11, libx11-guitest-perl, libgtk3-simplelist-perl, gir1.2-wnck-3.0, gir1.2-vte-2.91`

**Comment by gfrenoy** [comment]
Thanks for the heads up!  Documentation has be updated accordingly.
