### ISSUE TITLE
6.0.2: Select-by-word characters not functioning

### ISSUE THREAD

**Issue by useronkel** [asbru-cm/asbru-cm#363]
Hi.
With the new version the select-by-word characters string ist not working anymore with linux (Ubuntu 18.04).
Neither in the global configs nor in the connection settings.
String is set to: -\._\/a-zA-Z0-9
Tested with:
root:y:0:0:root:/root:/bin/bash@notworking
Expected selection:
root:y:0:0:root:/root:/bin/bash@~~notworking~~
Real selection:
root:y:0:0:root:/root:~~/bin/bash@notworking~~

Is this a known issue?

**Comment by hanspr** [comment]
This is not a regex expression

From the vte manual

![imagen](https://user-images.githubusercontent.com/1572396/72624991-7d6ee880-390d-11ea-972d-4e0e051ba719.png)

https://developer.gnome.org/vte/0.48/VteTerminal.html#vte-terminal-set-word-char-exceptions

The default values for word selection in Asbru are: .-.:_/

![imagen](https://user-images.githubusercontent.com/1572396/72625167-e7878d80-390d-11ea-8c76-d2d7c4a4156f.png)

Which means, include those (.-.:_/) as part of a word, when selecting text (by double clicking with the mouse)

When I test a double click I get

![imagen](https://user-images.githubusercontent.com/1572396/72625283-1dc50d00-390e-11ea-9320-aab4713e6595.png)

or this

![imagen](https://user-images.githubusercontent.com/1572396/72625528-8c09cf80-390e-11ea-890e-6e5230006b9b.png)

If modify like this

![imagen](https://user-images.githubusercontent.com/1572396/72625552-96c46480-390e-11ea-8e48-df52b3e019e7.png)

I get this

![imagen](https://user-images.githubusercontent.com/1572396/72625566-9deb7280-390e-11ea-9cdb-971d2c3b3c11.png)

Can not reproduce,  in Mint.

Modify your settings to comply with vte manual instructions and then test again, document with images and the precise procedure you are doing to be able to reproduce.

**Comment by jok76** [comment]
I'm having the same Problem in KDE. With the default setting: \.:_\/a-zA-Z0-9-
":" is not selected.
![selection](https://user-images.githubusercontent.com/60010383/72629562-dc098600-3950-11ea-866b-cecffb91eb92.png)

**Comment by hanspr** [comment]
Change the defaults to : -.:_/

That default that you are showing is invalid

**Comment by jok76** [comment]
Great that works. I never changed that setting, think it's from good old PAC times ;-)
And sorry for not reading and understanding what you wrote in your first statement:
**non-alphanumeric**

**Comment by hanspr** [comment]
@useronkel 

Please confirm that changing the defaults to: -.:_/

Also works for you and close the issue if so, thanks.

**Comment by useronkel** [comment]
I'm also comming from old PAC as jok76 mentioned :-)
Thx for clarification hanspr!
