### ISSUE TITLE
Renaming a cloned connection can be confusing

### ISSUE THREAD

**Issue by clickwir** [asbru-cm/asbru-cm#37]
I have 2 systems that are just about the same, so I made a clone of the first entry and changed the Host IP. Also on that same "Edit connection" screen is a "TAB / Window Title" option. That doesn't update the name in the connections list. Just the tab when the connection is open. 

After poking around, I found the "Rename Connection" option. But it would make more sense (to me at least) that when I'm editing the connection details, I'm also updating the name. 

The connection name and tab name seem to be disconnected in their use, which might be useful for some people. But I want them to be the same, so it's confusing. At least now that I know how to fix it, I can go back and fix the others that are wrong.

Oh, also, sometimes when going out of either the Edit Connection or Rename Connection window, the highlighted connection would swap. Did it just change the sort order of 2 things that are named the same or did it just flop which one is highlighted for some reason? 

That causes me to have to go back in and out of each entry to look at the host IP a couple times to make sure I'm going to "Rename Connection" for the correct one.

**Comment by gfrenoy** [comment]
"TAB / Window Title" and "Connection Name" are indeed two different things.  And I found this a bit confusing as well.

Now, how can we change this ?  I guess some users are taking advantage of that two fields and if we get rid of one of them ... This will break their current settings.

I'm not sure of the proper way to manage this.  Ideas are welcome.

About the other issue, I'd suggest to create another entry so we don't mix up the various discussions...

**Comment by beliys** [comment]
It's not problem and for fix always need using simple algorithm:
1) clone connection
2) first rename connection
3) next edit connection

**Comment by cornfeedhobo** [comment]
@gfrenoy Maybe the solution is to alter the logic of "rename" to check if `TAB / Window Title` is identical to `Connection Name` and update both, otherwise only update `Connection Name`?

**Comment by gfrenoy** [comment]
When you right-click the node and choose "rename", you actually have the opportunity to change both:

![image](https://user-images.githubusercontent.com/981546/34467737-4feaead0-eefa-11e7-97fa-933e95efb47e.png)

First, labels look confusing to me, shouldn't we change them ?

- Enter new NAME --> Node name
- Enter new TITLE --> TAB / Window Title

And then, as @cornfeedhobo suggests, we should not change "TAB / Window Title" if it has been changed but only if it still has the default value.

Would that make more sense ?

**Comment by hanspr** [comment]
@KlaasT 

This could be closed to

**Comment by KlaasT** [comment]
Closed #37
