### ISSUE TITLE
Asbru 6.0.2 does not save text in 'info tab'

### ISSUE THREAD

**Issue by thijz** [asbru-cm/asbru-cm#372]
**Describe the bug**
When you add comment in the info tab of a connection this text is not saved.

**To Reproduce**
1) open a connection
2) goto the info tab and enter some text
3) switch to the connection tab
4) switch back to the info tab : text is gone

**Expected behavior**
IIRC there used to be a 'save' button but that is no longer there (i assume Asbru should be auto saving the text on the info tab?)

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 19.10
 - Gnome 3.34.2

**Additional context**

**Comment by hanspr** [comment]
The info tab is a notification area from the original application, and is __not__ meant to write on it or save anything at all. Should not even allow to type anything in it, to avoid creating a confusion like yours.

Perhaps you are looking more for a new feature, I would suggest that you think of what you are trying to accomplish with that action and request a new feature, and no necessarily based on editing the info tab, maybe adding "notes" to he connection settings and display them in the info tab when e connection is selected?.

**Comment by popxunga** [comment]
Can't we block the keyboard input on Info tab to avoid this ?

**Comment by thijz** [comment]
@hanspr 
Really ?  before switching to asbru (when i was still using PAC) i used the info tab all the time. it was really handy to have a place to add some extra info about the connection.
When i switches to Asbru i only noticed after a couple of days that all this info was gone. lost forever :-(
If the text in the info tab is not meant to be edited and if it does not get saved (it definitely did in PAC!) then there is indeed no reason to make it editable.
However AFAIK the only info that is ever in the info tab is the connection name.  not much added value in that IMHO.  i cant imagine that the info tab was ever added just to show the connection name ...

Would it be possible to somehow split the info tab in a RO section (for the connection name ;-) and an editable section ?  To me It just seems like the obvious place to add info about the connection is in the 'info' tab.  Dont you agree ?  :-)

**Comment by gfrenoy** [comment]
I see indeed some lines in the code that make thinking it should work as you describe:

https://github.com/asbru-cm/asbru-cm/blob/master/lib/PACMain.pm#L2169-L2182

If was not intentional to remove that feature ; just that we did not even know it was working like that ;)  I'll have a look and try to restore this.

Thanks for the heads-up.

**Comment by thijz** [comment]
thanks @gfrenoy that would be fantastic !!
oh and while you are working on it could you also add the possibility to paste screenshots there ? (and video's and flash animations  ;-D

**Comment by gfrenoy** [comment]
@thijz The last commit should have brought the feature back ... We'll release an update (6.0.4) soon and in the meantime, you can try the snapshot versions.

If you did not save your connections since then, they should be back again...Otherwise, you'll have to revert to an old copy of your configuration file.  Btw, Ásbrú makes a copy at every startup so you can recover the last 10 configurations files in ```~/.config/pac/bak```.

**Comment by gfrenoy** [comment]
Oh and thanks for the suggestion about having a "rich" editor there.  Not sure if this exists in Gtk but while discovering that feature (I never tried it!), I found out you can put emojis:
![image](https://user-images.githubusercontent.com/981546/73595347-e95d6d80-4517-11ea-86d1-b8bbd38f3b4f.png)

Thanks again for reporting the issue.

**Comment by thijz** [comment]
hmm ... just ubdated to 6.0.4 but i see no change ?
should the text auto-save ?

**Comment by gfrenoy** [comment]
I checked again with 6.0.4 and, yes, you can now change the info text and save it in your preferences.

And it will auto-save if you have activated the option that automatically save your changes (in Preferences > Main Options > Behaviour).

**Comment by thijz** [comment]
For some reason this is not working for me :-(

If i open 1 ssh connection i get 2 tabs in the main window : the ssh session + the info tab
The first time i switch to the info tab everything is still grayed out and i cant even edit
When i switch to the ssh tab and back to the info tab the text is no longer grayed out and now i can edit
However, if i add some text, switch to the ssh tab and then back to the info tab my text is gone ...

I also tried by disabling the auto save and pressing the save button after adding text in the info tab, but that makes no difference.  The text is never saved.

In the about box i can see i'm using v6.0.4

Anything else i can try?  I'm happy to help with debugging this

**Comment by thijz** [comment]
also interesting to note : i noticed that entering text in the info tab is a but sluggish
with top running i could see that Asbru is eating up all my CPU when i keep pressing a key (eg the '-' to draw a line)

**Comment by gfrenoy** [comment]
> For some reason this is not working for me :-(

Really weird.  I just did what you describe and, even if sometimes indeed a bit slow, it works fine.

> Anything else i can try? 

Can you try with a clean configuration ?

From a command line:

```
asbru-cm --config-dir=/tmp/asbru-cm
```

Then, create a new connection ; select it, change the info tab content and quit the application.
Here is how it looks for me:
![output](https://user-images.githubusercontent.com/981546/73880058-f0f57d00-485d-11ea-98b6-25920a6997f4.gif)

In the configuration file ```/tmp/asbru-cm/pac.yml```, you should find what you have typed in the field ```description```:

![image](https://user-images.githubusercontent.com/981546/73880239-5a758b80-485e-11ea-9db0-78cdca9323b2.png)

**Comment by thijz** [comment]
OMG !
i just tried what you described above and it works as you describe
so i opened asbru with my normal config, tried it ... and now it also works !!??
could it be that running asbru with a new config triggered something ?
I'll just keep using it and see what happens ...  always a bit frustrating when you cant put your finger on the issue ... but that's what you get with software ! ;-)

about the lag i'm seeing : since autosave is active i assume that each new character i type is immediately saved to the config file ?  if so, that can explain the lag i see : i have many connections configured (dont know how i can see just how many i have?) and this results in a pax.yml file of 1.2GB
So i'm not surprised that it takes some time to write to that file

**Comment by gfrenoy** [comment]
> and now it also works !!??

Good :)

> 1.2GB

Really !?!  Waaw.

>  i assume that each new character i type is immediately saved to the config file 

If I read the code correctly, the ```pac.yml``` is only saved when you properly quit the application but there's a temporary "[store](https://perldoc.perl.org/Storable.html)" file that is indeed saved at every keystroke.  This file must be more or less the same size which will certainly explain this.

> dont know how i can see just how many i have?

This will give you the number by method:

```
sed -n -e 's/^ \+method: \(.\+\)$/\1/p' pac.yml | sort | uniq -c
```

**Comment by thijz** [comment]
2 FTP
     16 Generic Command
      1 PACShell
     29 RDP (rdesktop)
      4 RDP (xfreerdp)
      1 Serial (cu)
    205 SSH
    178 Telnet
      5 VNC

so about 440 connections

Come to think of it, i looks like sth was wrong with this temp storage file since the info i added was not even retained within the same session ..
Ah well, it works now

thanks for the quick response and for keeping this project alive !!
Grtz
Thijs
