### ISSUE TITLE
Donations via Bitcoin

### ISSUE THREAD

**Issue by lukejohnsonrp** [asbru-cm/asbru-cm#379]
Could you please start accepting Bitcoin as a donation method? I've been donating Bitcoin to the PAC author and would be really happy to support Asbru same way.

An easy and fast way to create a multisignature Bitcoin wallet is to use [Electrum](https://electrum.org). It is a most popular FOSS wallet and doesn't require downloading a full blockchain.

**Comment by gfrenoy** [comment]
Thanks for your offer !  Only the fact that you want to donate is already a gift, we really appreciate it :)

At this stage, we do not consider creating a bitcoin wallet for this project.

If others really believe we should do it, please thumb up the idea.

**Comment by dpcinc** [comment]
Not bitcoin for me but if you had one time or custom one time option I would have donated, I stopped at  the recurring.

**Comment by gfrenoy** [comment]
Thanks @dpcinc, much appreciated to consider donating :)

And I understand your concern about recurring payments but actually, from the Liberapay FAQ:

> On Liberapay donations are funded in advance. You have control over how much money you put in and when. Sending more money at once results in a lower percentage of transaction fees.
> When a donation needs to be renewed we send you a notification via email so that you can fund it again, or discontinue it.

So basically, that is a one time donation ...

**Comment by dpcinc** [comment]
I just want to type in $50 and hit send!

**Comment by KlaasT** [comment]
Thanks very much @dpcinc This is really great and means a lot for us.

**Comment by dpcinc** [comment]
You will receive a lot more if you add the option for simple one time donations.

**Comment by jwx888** [comment]
Would like to donate BTC as well.

**Comment by quartznets** [comment]
any update on this?
would have liked to make a donation using cryptocurrency.

**Comment by ValdikSS** [comment]
@gfrenoy, take a look at how I made cryptocurrency donations page at my website: https://antizapret.prostovpn.org/donate.html

Ideally, you need to accept several major cryptocurrencies, like Bitcoin and Ethereum at least (you can check which are major on https://coinmarketcap.com/). For each cryptocurrency you need at least a wallet address, preferably with QR code and payment button where possible (if the cryptocurrency has its own URI scheme).

If you're not savvy in cryptocurrencies and want to make that as easy as possible, use unified wallets like [Jaxx](https://jaxx.io/) or [Exodus](https://www.exodus.io/). This is a server-backed software, but all your money is in your control, they don't provide a consolidated account unlike some web services. Just download the software and copy Bitcoin/Ethereum/etc addresses. Make sure to backup wallet's seed phrase and/or private keys of each cryptocurrency!

**Comment by gfrenoy** [comment]
Thanks @ValdikSS, we're indeed not very skilled in cryptocurrencies :-/   This "Starting Guide" is really helpful and appreciated !

Quick question to evaluate the interest for the project : do you think we can buy something that could be interesting for Ásbrú with that cryptomoney ?  Maybe web design services, perl developpers, GNOME experts, ...?

**Comment by ValdikSS** [comment]
@gfrenoy I'm sure you can, but that what should be negotiated with the people, it doesn't have anything with the technology per se.
You can buy goods and services with cryptocurrencies. Bitcoin payments are pretty common among internet service companies; not very common among retailers, but you can find some. Either way, you can always exchange cryptocurrencies to usual currencies (fiat).

**Comment by NRGLine4Sec** [comment]
Maybe you can also use [Open Collective](https://opencollective.com/) like some other Open Source project to manage donations.

**Comment by lukejohnsonrp** [comment]
I am really glad for your work guys and still would like to donate, but this is really frustrating that since January you are still stuck deciding whether Bitcoin is good or not for accepting donations and unable to create a simple BTC wallet. 

I really don't know how to help you more since there is excessive amount of information was given on that subject here.

There are at least 3 more Asbru & Bitcoin users I personally know atm that don't mind donating to your project and we are still unable to do so. 

> do you think we can buy something that could be interesting for Ásbrú with that cryptomoney 

You can pay for  dedicated and virtual servers, at least of 50% decent providers on the hosting market accept Bitcoin.
You can purchase hardware (computers&components) for testing or building machines.
You can convert it into fiat currency (traditional money) without a problem.

Hoping this resolves soon.

**Comment by gfrenoy** [comment]
All, thanks again for your help and suggestions on this!

I'm still a bit uncomfortable (too many options and choices to make ;p) but I made a first step in (hopefully) the right direction and added a link on the home page to a BTC address:
![image](https://user-images.githubusercontent.com/981546/95673905-ea699300-0bac-11eb-82df-d95650958e51.png)

Does that make sense ?  Should we have addresses for other cryptocurrencies ?  What is the best link / widget to use ?  Can someone test if this works as I think it should work ?

Thanks again for your support for this project :)

**Comment by ValdikSS** [comment]
Done. I set the fee to a very low value, expect confirmations in a day.
https://blockchair.com/bitcoin/transaction/664615664f780c9c0def21bee81252cf90e75b63dacb231d9e431b9bad8b052c

I can't recommend you widgets because I don't use one, as I didn't find any good. I [did everything myself](https://antizapret.prostovpn.org/donate.html).

**Comment by gfrenoy** [comment]
> Done

Thanks a lot @ValdikSS !  All looks to work fine:
![image](https://user-images.githubusercontent.com/981546/95676139-5acbe080-0bbc-11eb-9dfd-b429a9887a87.png)

> I did everything myself.

Yes, saw that.  Nice !  Let's start simple for now.  I guess showing the address is good enough.

Not sure to understand the pros and cons of having different types of cryptocurrencies?

>  You should consider using SegWit address

Ouch, does not look to be supported by Jaxx ; should I use Exodus instead ?  Can we transfer the the wallet management from one to other ... Oh dear, so many things to learn :)

**Comment by ValdikSS** [comment]
>Not sure to understand the pros and cons of having different types of cryptocurrencies?

There are several very major ones: Bitcoin, Ethereum, Tether. Bitcoin is the first cryptocurrency, hence the most popular one. Ethereum provides a lot of functions on blockchain which Bitcoin doesn't. Tether is a stable coin, the authors make everything for it to cost exactly 1 USD. All these have public blockchain, meaning that everyone can see all transactions and balances on all wallets.

There are private blockchain projects, "anonymous cryptocurrency", which hide transactions and/or wallet balances: Monero, Zcash, Dash. Some people prefer these coins because they don't want to make their actives and activities publicly visible.

>Ouch, does not look to be supported by Jaxx ; should I use Exodus instead ?

I personally use software for the exact coin where possible, because usually this software has the most functions the coin has. Legacy address is not something bad you should drop right away, but as I observe, many slowly switch to SegWit.

**Comment by gfrenoy** [comment]
@ValdikSS Thanks again for your help on this !
I added a new page in the documentation : https://docs.asbru-cm.net/Contributing/Financial_Contribution/

I guess we are now all set now :)  Let me close this (old) issue (and waiting for donations ;-p)...

**Comment by gfrenoy** [comment]
Thanks to the donators in BTC, much appreciated !
