### ISSUE TITLE
Help with expect regex for this system

### ISSUE THREAD

**Issue by tilkov** [asbru-cm/asbru-cm#387]
I cannot login to ESXi systems with SSH, the status stays at PASSWORD:Sent, but the terminal is logged in successfully. Can you please help me fid the proper regex for it?

Edit: if its not readable, here it is at a pastebin: http://p.ip.fi/Qt9y

`Starting EXPECT pattern matching...
 at /usr/share/perl5/Expect.pm line 562.
	Expect::expect(Expect=GLOB(0x55cb7dcab808), 40, ARRAY(0x55cb7ee89de0), ARRAY(0x55cb7ee89dc8), ARRAY(0x55cb7fede9c0), ARRAY(0x55cb7fedec18), ARRAY(0x55cb7feded08), ARRAY(0x55cb7fed2028), ...) called at /opt/asbru/lib/pac_conn line 1766
spawn id(10): list of patterns:
  #2: -eof `'
  #3: -re `\\[__PAC__SUDO__PROMPT__\\]'
  #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'
  #5: -re `.*(any key to continue|tecla para continuar).*'
  #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'
  #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'
  #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+)*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'
  #9: -re `[#%\\$>]|\\:\\/\\s*$'
 
 
spawn id(10): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+)*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.
 
Password: 
spawn id(10): Does `Password: '
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+)*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? YES!!
    Before match string: `'
    Match string: `Password: '
    After match string: `'
    Matchlist: (`Password',  `')
Calling hook CODE(0x55cb7fed21f0)...
Sending 'xxxxxx\n' to spawn id(10)
 at /usr/share/perl5/Expect.pm line 1265.
	Expect::print(Expect=GLOB(0x55cb7dcab808), "E\$X1\x{a}") called at /opt/asbru/lib/pac_conn line 592
	main::send_slow(Expect=GLOB(0x55cb7dcab808), "E\$X1\x{a}", "hide") called at /opt/asbru/lib/pac_conn line 1613
	main::__ANON__(Expect=GLOB(0x55cb7dcab808)) called at /usr/share/perl5/Expect.pm line 761
	Expect::_multi_expect(40, ARRAY(0x55cb7fed2838), ARRAY(0x55cb7fed2ef8)) called at /usr/share/perl5/Expect.pm line 566
	Expect::expect(Expect=GLOB(0x55cb7dcab808), 40, ARRAY(0x55cb7ee89de0), ARRAY(0x55cb7ee89dc8), ARRAY(0x55cb7fede9c0), ARRAY(0x55cb7fedec18), ARRAY(0x55cb7feded08), ARRAY(0x55cb7fed2028), ...) called at /opt/asbru/lib/pac_conn line 1766
[pac_conn(17385)][esx-10][esx-10]: PASSWORD:Sent (not shown)
Continuing expect, restarting timeout...
 
spawn id(10): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+)*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.
 
 
 
spawn id(10): Does `\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+)*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.
 
The time and date of this login have been sent to the system logs.
 
WARNING:
   All commands run on the ESXi shell are logged and may be included in
   support bundles. Do not provide passwords directly on the command line.
   Most tools can prompt for secrets or accept them from standard input.
 
VMware offers supported, powerful system administration tools.  Please
see www.vmware.com/go/sysadmintools for details.
 
The ESXi Shell can be disabled by an administrative user. See the
vSphere Security documentation for more information.
 
spawn id(10): Does `\r\nThe time and date of this login have been sent to the system logs.\r\n\r\nWARNING:\r\n   All commands run on the ESXi shell are logged and may be included in\r\n   support bundles. Do not provide passwords directly on the command line.\r\n   Most tools can prompt for secrets or accept them from standard input.\r\n\r\n\033[00mVMware offers supported, powerful system administration tools.  Please\r\nsee www.vmware.com/go/sysadmintools for details.\r\n\r\nThe ESXi Shell can be disabled by an administrative user. See the\r\nvSphere Security documentation for more information.\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+)*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.
 
[root@ESXi-10-r730:~] 
spawn id(10): Does `\r\nThe time and date of this login have been sent to the system logs.\r\n\r\nWARNING:\r\n   All commands run on the ESXi shell are logged and may be included in\r\n   support bundles. Do not provide passwords directly on the command line.\r\n   Most tools can prompt for secrets or accept them from standard input.\r\n\r\n\033[00mVMware offers supported, powerful system administration tools.  Please\r\nsee www.vmware.com/go/sysadmintools for details.\r\n\r\nThe ESXi Shell can be disabled by an administrative user. See the\r\nvSphere Security documentation for more information.\r\n[root@ESXi-10-r730:~] '
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+)*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.`

**Comment by gfrenoy** [comment]
Your command prompt is ```[root@ESXi-10-r730:~]``` so you'll need to change the "command prompt" parameter to match this.  The default one does not.  Here is a suggestion:

```
[#%\$>]|\:\/\s*$|^\[[a-z0-9_-]+@[0-9a-zA-Z-]+:~\]$
```

This should work as well:

```
[#%\$>\]]|\:\/\s*$
```

**Comment by tilkov** [comment]
Thank you, @gfrenoy . By the way, that was not the real password you edited out :)
