### ISSUE TITLE
Superputty to Asbru

### ISSUE THREAD

**Issue by sonicepk** [asbru-cm/asbru-cm#39]
Hi all,

I have used Brian Raaen's script to convert Superputty configs to Asbru-cm. It is very useful and you can tweak it easily. It might be useful to include a copy in the utils directory if Brian is agreeable. 
https://www.brianraaen.com/2016/11/04/superputty-to-pac-manager/

And thank you all for working on Asbru-cm. 

Regards
Eoin

**Comment by gfrenoy** [comment]
Thanks for sharing and, yes, certainly, that'd be good thing to have this in our utils !  Should we contact Brian ?  How to contact him ? Or just add it and put a note for credits ?  If someone can make a PR for this, that'd be great.

**Comment by sonicepk** [comment]
Brian, has agreed to allow his script to be included. You can see his reply to my request on his website. https://www.brianraaen.com/2016/11/04/superputty-to-pac-manager/
I created a PR for the script, feel free to use the PR or create a file. 

Regards
Eoin

**Comment by KlaasT** [comment]
Thank you for sharing this with us. I've merged Pull Request #40 into master.
