### ISSUE TITLE
 Add support for multiple IP addresses

### ISSUE THREAD

**Issue by xattack** [asbru-cm/asbru-cm#403]
**Is your feature request related to a problem? Please describe.**

This is somehow an uncommon request but , i think it could be useful for everybody.When we create a new register aka connection , we select one IP to that connection , but sometimes our clients has more than just one IP address. In my case , our costumers had many services , like DB, storage & backups , production , separate Lan , etc . Every service has an IP in order to separate services , sometimes con be more than seven in just one server , and as sysadmin you receive emails just mentioning the IP address of the service, which could be different that the one you had registered in asbru 

![Screenshot from 2020-02-04 11-34-44](https://user-images.githubusercontent.com/8902460/73771986-f6ab6f80-4744-11ea-85da-cb52248541f3.png)

**Describe the solution you'd like**

Could you add a button in which we can add more IP addresses ? 

![Screenshot from 2020-02-04 11-40-00](https://user-images.githubusercontent.com/8902460/73771973-f0b58e80-4744-11ea-9383-44fc44b319fa.png)

could you also add a second button on/off to activate/deactivate that IP to connect? 
sometimes you have to verify if that IP address is active or not .

**Describe alternatives you've considered**

My alternative until now , is edit the IP address in the connection register or open a shell and do it manually 

**Additional context**

regards

**Comment by hanspr** [comment]
Hi @xattack 

> My alternative until now , is edit the IP address in the connection register or open a shell and do it manually

I do not have this particular case, but in general when I have multiple connections with one client, I clone a connection, edit its parameters, and organize them in some meaningful groups, and name the connection to hint me what I will be doing there. 

This way I do not have to edit the connection before opening, just double click on the one that I need. 

![imagen](https://user-images.githubusercontent.com/1572396/75628273-fe6fff80-5b9c-11ea-806a-2efa2973329f.png)

And I would not be surprised that if the IPs are for different services and "Lans" as you mention, in some occasions some other connection parameters would have to change too.

I really do not know if adding an IP selection would be a good solution
* it will create an extra step before connecting
* you would have to have a list of services to IPs to remember what IP is used for what before selecting
* you loose the capability to automate some login tasks using expect for different services. Open tunnels for different connection types, etc.
* This will also lead to someone else asking for multiples ports (which is more common to separate services), and then ask for multiple user names depending on the IP or port, and multiple passwords, and multiple connection parameters, tooltips to hint what service or connection type that IP stands for, and so on.

IMHO, cloning connections and organize them in groups is a better __general__ approach.

**Comment by gfrenoy** [comment]
I believe @hanspr's reasoning is correct : the general approach should been seen differently.

You should create different entries or even create clusters to manager you servers ; having multiple IPs for the same "service" does not look correct to me.

Feel free to comment further if you believe we did not get this correctly.

**Comment by hanspr** [comment]
Kind of late, but. While documenting Ásbrú I came across this possibility, you can add <ASK:...> Substitution to the host IP and type something like this.

![imagen](https://user-images.githubusercontent.com/1572396/77828236-d6ae8180-70df-11ea-8973-1ee705259a6e.png)

When you connect you will be asked to select one of the values.

![imagen](https://user-images.githubusercontent.com/1572396/77828258-e9c15180-70df-11ea-992d-bc4d6b37f1b8.png)

In case you still need something like this.

Ásbrú documentation : https://docs.asbru-cm.net/

Substitutions: https://docs.asbru-cm.net/Manual/Substitutions/
