### ISSUE TITLE
Debian/Ubuntu 16.04 - Error during installation of package due to unmet dependencies

### ISSUE THREAD

**Issue by arvind-kvak** [asbru-cm/asbru-cm#405]
**Describe the bug**
Unable to install the latest package on ubuntu 16.04 veriosn.

**To reproduce**
using below steps:
curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash
sudo apt install asbru-cm

**Expected behavior**
Should get all dependencies and install the package
could not install the dependencies required.

**Additional context**
Logs:
u1604:~$ curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/asbru-cm_asbru-cm.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.

u1604:~$ sudo apt-get install asbru-cm
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 asbru-cm : Depends: libgtk3-simplelist-perl but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by gfrenoy** [comment]
Mmm.  Looks like that package is only available as of Ubuntu 18.04 :(  We'll see how (if) we can handle this.

In the meantime, you should find a way to get that package installed.  Would that PPA be an option for you : https://code.launchpad.net/~jeffreyratcliffe/+archive/ubuntu/ppa ?

**Comment by arvind-kvak** [comment]
After installing the PPA package, able to setup arbru-cm

Thanks for your help, appreciate it.

Please see if you can make the package available to 16.04.
