### ISSUE TITLE
create local serial connection (does this option exist?)

### ISSUE THREAD

**Issue by thijz** [asbru-cm/asbru-cm#407]
**Is your feature request related to a problem? Please describe.**
now i'm still using a separate app when i need to connect to a device via serial
would be nice to have this option in Asbru

**Describe the solution you'd like**
add a 'local com port' connection type that allows you to select any one of the serial ports known to the OS

**Describe alternatives you've considered**
i tried 'serial (cu)' and 'seria (remote tty)' but i dont think this is what i need (have no idea what i'm supposed to do)
now still using GtkTerm

**Additional context**
that's it :-)
maybe

**Comment by KlaasT** [comment]
I think that is a great idea. At the moment I'm doing the following:

Opening a local shell in Asbru
Executing: sudo screen /dev/ttyUSB0

Whereas the serial device should be configurable.

Should be possible to bring that in as a connection type (in my opinion).

**Comment by wcasanova** [comment]
another alternative is, tio

https://tio.github.io/

**Comment by thijz** [comment]
@wcasanova : there are indeed many ways to set up a connection via serial port, but it would simplify my workflow if i could just use Asbru for _all_ my connections
I have to do quite a bit of config on cisco routers so i frequently need a serial connection to troubleshoot or do initial config

**Comment by wcasanova** [comment]
Doesn't it work with "cu"?

![image](https://user-images.githubusercontent.com/12401985/73931161-93d9e580-48b6-11ea-87b3-cc459a2d5be6.png)

**Comment by KlaasT** [comment]
I'm testing if the cu option actually works. Will give feedback in a moment.

**Comment by KlaasT** [comment]
So. First of all I didn't know that asbru-cm actually has a serial connection type to create. Shame on me ;-)

cu seems to have an issue and saying that the serial line is already in use.
remote-tty gives a connection refused.

Will have to dive more into the code what is actually happening there.

**Comment by wcasanova** [comment]
could be replaced, cu and remote-tty by tio or Python-serial has a utility called miniter.py. It just had no way of testing serial connections.

**Comment by KlaasT** [comment]
Actually cu and remote-tty or more the "serial connection" is meant to be the connection to the "local com port". Though for some reason this is not really working. I've got quite a few Cisco devices at work in the lab so I will try to dig a bit deeper into it.
