### ISSUE TITLE
Add to cluster menu no longer shows new cluster name

### ISSUE THREAD

**Issue by dpcinc** [asbru-cm/asbru-cm#408]
After adding a new cluster name, the cluster name no longer shows in the 'add to new cluster' context menu of the tab'ed terminal using 6.04 . 

**To Reproduce**
1. Open connection
2.  right click tab and 'add to cluster'
3.  new cluster , type name
4.  go back into menu notice the new name is not visible in 'change to cluster', and the count of connected terminals is -1

**Expected behavior**
You should be able to use the context menu to select the newly made cluster or to change the current cluster it is in. 

**Desktop (please complete the following information):**
mint 19.3

**Additional context**
Was working relatively recently prior to 6.x I believe.

**Comment by gfrenoy** [comment]
Strangely enough, it works fine if you right click on the terminal but not if you click on the tab...
