### ISSUE TITLE
ssh port number field too small

### ISSUE THREAD

**Issue by merikz** [asbru-cm/asbru-cm#410]
**Describe the bug**
In the SSH connection window, the port field only show 4 digits.
In the example below the port number is 12345 but only 2345 is visible, the leading 1 has scrolled away.

**To Reproduce**
1. Create a new SSH connection
2. Type 12345 as port number
3. See screenshot below.

**Expected behavior**
All 5 digits should be shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/12588095/74108043-42f81480-4b76-11ea-82b7-6fa7f6db6985.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS, Cinnamon
 - Version: Asbru 6.0.4

**Additional context**
Seems like it began with GTK3. Checked all v6.0.x versions which has this behaviour, 
v5.2.1 showed complete value (as well as the legacy-v5 branch).

**Comment by merikz** [comment]
It seems this patch works for me, but I don't know how me using cinnamon make any difference here.
Anyone with more gtk experience might have some input? @hanspr ? 
```
~/src/asbru-cm$ git diff
diff --git a/res/asbru.glade b/res/asbru.glade
index 990885f..390c7c7 100644
--- a/res/asbru.glade
+++ b/res/asbru.glade
@@ -380,7 +380,7 @@ If not, see <http://www.gnu.org/licenses/>.
                                                         </child>
                                                         <child>
                                                           <object class="GtkSpinButton" id="entryPort">
-                                                            <property name="width_request">130</property>
+                                                            <property name="width_request">136</property>
                                                             <property name="visible">True</property>
                                                             <property name="can_focus">True</property>
                                                             <property name="has_tooltip">True</property>
~/src/asbru-cm $
```

**Comment by hanspr** [comment]
You have to edit the glade file, but install and use "Glade", is not recommended to edit the file directly there.

Open with glade, locate the form, select the field and add request widht

Should be similar to this

![imagen](https://user-images.githubusercontent.com/1572396/74114735-61a7dc80-4b71-11ea-94b3-eceb20294b4a.png)

**Comment by merikz** [comment]
It seems this is Desktop Environment (?) dependent. 
LXDE (Lubuntu 18.04.1) looks same as Cinnamon (Ubuntu 18.04.3), but Unity (Ubuntu 18.04.1) does not have this problem.
How do we handle these things, when the UI looks different (right?/wrong?) in different environments?
Adapt to worst case? Does anyone check how the UI looks in different distributions?
I'm happy to do a PR, but I only have easy access to the environments mentioned.

**Comment by hanspr** [comment]
I think the solution is to edit asbru.css, to take control of that. I already have a very large PR #395 but it will be included on 6.2.

**Comment by egmontkob** [comment]
Wouldn't [width-chars](https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkEntry--width-chars) (perhaps "width_chars" in glade, not sure) be a better approach?

**Comment by gfrenoy** [comment]
> Wouldn't width-chars (perhaps "width_chars" in glade, not sure) be a better approach?

I tried but did not work as expected ; maybe I did not understand something but I ended putting a requested width of 150 for all "port" fields.  But obviously that one fell into the cracks ; I'll change it for 6.1.

**Comment by gfrenoy** [comment]
Change made in loki that will be 6.1 soon...
