### ISSUE TITLE
"bad obfuscated password length" error in vnc session

### ISSUE THREAD

**Issue by calippus** [asbru-cm/asbru-cm#411]
**Describe the bug**
Connection to by using vnc is giving "bad obfuscated password length" error message.

**To Reproduce**
1. Add a connection with Method VNC
2. Choose Manual (or fill the password field in User / Password section) as Authentication.
3. Save and Close
4. Try to connect and see the error message

**Expected behavior**
To connect to host via VNC if password is given. 
To connect to host via VNC after asking password if Manual is selected. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8089902/74225226-907d9a00-4cba-11ea-9bb1-3d4ea6ad1a1a.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 31

**Additional context**

**Comment by gfrenoy** [comment]
The relevant error message is ```vncpasswd: command not found```

Not sure how to install this on Fedora though :(

**Comment by calippus** [comment]
It is not. 
When I tried directly from tigerVNC viewer, I can connect by using same password. I thought it is not necessary to mentioned it while it is so obvious.

**Comment by gfrenoy** [comment]
So the point is : today, to avoid sending the password in clear text, we are using ```vncpasswd```.  So if it is not installed, it will not work...

**Comment by calippus** [comment]
So then the point is that; there is a dependency package called tigervnc-server. isn't it?

**Comment by gfrenoy** [comment]
Apparently.  But it looks a bit overkill to me to install ```tigervnc-server``` just to have vncpasswd ; this is a question for the Fedora (rpm) packagers of [TigerVNC](https://github.com/TigerVNC/tigervnc/issues).

**Comment by allivut** [comment]
it need tigervnc-common

**Comment by FdelS** [comment]
@calippus you have dependency of `tigervnc-tools` package, you do not need to install the server.
