### ISSUE TITLE
add <PORT> to PAC internal variables

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#412]
We have USER.. PASS.. IP but..
I would like to have also PORT variable to use with local commands on non standard configurations.
eg. scp specific file to non standard port with one click

**Comment by gfrenoy** [comment]
Looks achievable.  We'll look into this.

And, we should remove "PAC" there and just name them "Internal variables".

**Comment by gfrenoy** [comment]
This is now available.  Testers are welcome on the [loki branch](https://github.com/asbru-cm/asbru-cm#testing-new-features).
