### ISSUE TITLE
Support for non system wide installed instance of KeePassXC

### ISSUE THREAD

**Issue by gfrenoy** [asbru-cm/asbru-cm#414]
**Is your feature request related to a problem? Please describe.**
If ```keepassxc-cli``` is not found as a system wide executable, KeePass integration is disabled.

![image](https://user-images.githubusercontent.com/981546/74595789-2eb88980-5046-11ea-86ab-3cda3961c074.png)

Hence, one might want to use the AppImage version of KeePassXC and in that case, the KeePassXC CLI is available through the following command:

```
./KeePassXC-*.AppImage cli
```

(see https://keepassxc.org/docs/#faq-appsnap-appimage-cli)

**Describe the solution you'd like**
Have a way to select the location of a specific version of ```keepassxc-cli``` or ```keepassxc``` (with "cli" to be added).

**Describe alternatives you've considered**
One can create a file ```keepassxc-cli``` in ```/usr/local/bin``` that contains:

```
#!/bin/bash
/path/to/KeePassXC-*.AppImage cli "$@"
```

**Comment by hanspr** [comment]
This should be closed
