### ISSUE TITLE
asbru-cm 6.1.0 rc1 on EL7 does not start

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#417]
This is the error message during Asbru startup:
**Failed to open file “/usr/share/asbru-cm/res/asbru_method_rdesktop.svg”: No such file or directory at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67.**

**Comment by gfrenoy** [comment]
SVG files were not copied in RPM package.  https://github.com/asbru-cm/asbru-cm/commit/14f3546ec9fd213de1277241ec4d2da94ca11b83 should fix this ; I did not test it ... Let me know if it works for you...

**Comment by popxunga** [comment]
Yes ... the spec file patch seems to work fine :-)
Thanks !

**Comment by gfrenoy** [comment]
Thanks for your feedback !  We need testers :)
