### ISSUE TITLE
6.1.0 rc1 SSH saved connections icon (EL7)

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#418]
Hi ...

With the 6.1.0 rc1 on EL7, the SSH saved connections has now a green padlock instead of the previous small SSH icon. Was this change intentional ?

Before 6.1.0 rc1:
![image](https://user-images.githubusercontent.com/37672088/74602052-b7621480-509c-11ea-8294-e204cb02727f.png)

After 6.1.0 rc1:
![image](https://user-images.githubusercontent.com/37672088/74602083-0f008000-509d-11ea-9732-a2c27e488b4b.png)

In addition, whenever a new SSH connection is created, it is displayed with the Windows symbol icon.

**Comment by gfrenoy** [comment]
> Was this change intentional ?

Yes :)

With 6.2, we hope you'll be able to have your own icon set.

> whenever a new SSH connection is created, it is displayed with the Windows symbol icon

Mmm, I cannot reproduce this ; can you elaborate a bit more ?

**Comment by popxunga** [comment]
Not sure why but I'm not able to reproduce it anymore... strange...
