### ISSUE TITLE
Opening a new connection maximizes the window

### ISSUE THREAD

**Issue by fringeadmin** [asbru-cm/asbru-cm#42]
This causes issues with scaling and desktop layout. I believe a new tab should simply adopt the size of the existing window.

**Comment by gfrenoy** [comment]
I remember I saw this in a previous version but it should be fixed today... What version are you using ?

Any chance to test this against the latest snapshot to confirm we are both talking about the same issue ?

**Comment by fringeadmin** [comment]
I'm using 5.0.0 rc4-1 on Fedora 27.
asbru-cm-5.0.0~rc4-1.noarch

**Comment by gfrenoy** [comment]
In Preferences > Terminal Options > Look and Feel, do you have the option "Start Terminals maximized" checked ?  Can you give it a try with that option *unchecked* ?

![image](https://user-images.githubusercontent.com/981546/34423577-40432758-ec1d-11e7-95d8-d63102c8f8bf.png)

What has recently changed is the default value (it should be unchecked by default)...

**Comment by fringeadmin** [comment]
Aha, it was checked and unchecking it works. Thanks!
