### ISSUE TITLE
Save a connection template for new connections

### ISSUE THREAD

**Issue by Catscrash** [asbru-cm/asbru-cm#420]
For each connection I have to make a lot of the same settings, that I'd love to prefill in some kind of template.

e.g. 
- domain part of the hostname
- username
- path to ssh key
- freerdp settings

**Comment by popxunga** [comment]
You can use the "Clone connection" or Copy/Paste node options.

**Comment by gfrenoy** [comment]
Another suggestion would be to automatically create entries in your ```~/.config/pac/pac.yml``` file.

That being said, we'll need more detail about the exact feature / change you would like to see in Ásbrú (see our feature request template).  Without that level of detail, hard to understand exactly what you have in mind.

**Comment by hanspr** [comment]
@Catscrash 

Check new online manual, and in particular this article: https://docs.asbru-cm.net/Managing/Templates/
