### ISSUE TITLE
App crashes (Can't find information for method TreeModel::sort_new_with_model)

### ISSUE THREAD

**Issue by wcasanova** [asbru-cm/asbru-cm#421]
**Describe the bug**
asbru 6.0.4.r86.gf896176-1
I had been using the loki branch for several days, even with the new look / themes. Everything was fine until I got this error after rebooting.

`Can't find information for method TreeModel::sort_new_with_model at /opt/asbru-cm-loki/lib/PACMain.pm line 566.
`
then it closes immediately
- Archlinux
- Kde/Plasma

**Comment by Leoten** [comment]
Same here after system update. Temporary solution: downgrade gtk-related packages (in my case gtk3, gtk-update-icon-cache) from **3.24.14** to **3.24.13**.

- Archlinux
- Plasma 5.18.0-3

**Comment by L0uac** [comment]
Same here:

    Archlinux
    Kde/Plasma

**Comment by mcarbs** [comment]
Same again, using Arch and Cinnamon.  Downgrading gtk3 and gtk-update-icon-cache as suggested about did fix the issue for me also.

**Comment by wcasanova** [comment]
`Overview of Changes in GTK+ 3.24.14
===================================

* Fix the opaque region for windows on X11

* theme:
 - Fix flat buttons in backdrop
 - Make popovers look more similar to menus
 - Tweak checkbox & radiobutton appearance
 - Add general typography classes (heading, title-1, etc)

* language bindings:
 - Fix annotations for gtk_tree_model_sort_new_with_model

* switch: Fix touch support

* infobar: Make clickable for default action

* emojichooser:
 - respect a no-emoji input hint

* fontchooser:
 - Fix an oversight with hiding the size label

* filechooser:
 - Disable recursive search without a system indexer

* modelbutton:
 - Fix a11y support to reflect button state

* input:
 - Fix touchpad gesture center calculation

* x11:
 - Fix root window scaling
 - Support _GTK_WORKAREAS_Dn property

* wayland:
 - Support a terminal purpose in input methods
 - Fix preedit cursor positioning
 - Fix enabling/disabling of text inputs
 - Support simultaneous selection requests
 - Require Wayland 1.14.91

* OS X:
 - Fix fullscreen state
 - Fix an Inkscape crash at startup
 - Fix OpenGL extension detection

* Printing:
 - Fix a crash with Avahi

* Translation updates:
 Basque
 British English
 Catalan
 Finnish
 French 
 Galician
 Japanese
 Kurdish Sorani
 Malay
 Russian
 Slovak
 Spanish
 Turkish
`

**Comment by gfrenoy** [comment]
There's definitely something that has been changed in Gtk3 that broke the Ásbrú code :(

> Fix annotations for gtk_tree_model_sort_new_with_model

I believe this corresponds to [this change](https://gitlab.gnome.org/GNOME/gtk/commit/e3247ed0d9156a385a14790abf070ba6b8fcbb3a) ... This is a comment only ; that should not hurt.

I've been able to reproduce it.  I commented out the lines that gave an error and ended up a bit later with the error:

```
Can't locate object method "get_model" via package "Gtk3::TreeStore" at /opt/asbru-cm-loki/lib/ex/PACTree.pm line 83
```

This is really confusing.  I've the feel the perl introspection is broken...

**Comment by gfrenoy** [comment]
>> Fix annotations for gtk_tree_model_sort_new_with_model
> I believe this corresponds to this change ... This is a comment only ; that should not hurt.

Well, no, there is a bit more than just comments : https://gitlab.gnome.org/GNOME/gtk/issues/1077

It's indeed related to introspection but at this stage, I don't understand what needs to be changed...

**Comment by gfrenoy** [comment]
Ok!  Got it :-)

![image](https://user-images.githubusercontent.com/981546/74778821-a54ec480-529c-11ea-869a-75c822138e01.png)

So there's an override of sort_new_with_model in the Gtk3 perl glue code that has been added to override a bug in Gtk3.  Now that the bug has been fix, that glue code is not needed anymore or even worse : it makes things crashing !

--> we need to report that to the upstream project (https://metacpan.org/pod/Gtk3)

**Comment by johnstruse** [comment]
Deleting `Gtk3::TreeModelSort::new_with_model` entirely allows asbru to launch successfully.

**Comment by wcasanova** [comment]
Yes, I commented on those lines in the code.
perl-gtk3 0.035-1
/usr/share/perl5/vendor_perl/Gtk3.pm
and already started correctly

**Comment by gfrenoy** [comment]
> we need to report that to the upstream project (https://metacpan.org/pod/Gtk3)

Done -> https://rt.cpan.org/Ticket/Display.html?id=131871

**Comment by figue** [comment]
Thanks for this issue investigation guys.

So workaround seems to comment all these lines?
```
sudo sed -e '1742,1753s/^/#/' -i /usr/share/perl5/vendor_perl/Gtk3.pm
```
If yes, can another packages be affected?

**Comment by gfrenoy** [comment]
> So workaround seems to comment all these lines?

This is one workaround, yes.

> If yes, can another packages be affected by this change?

If you are sure that the target machine has Gtk 3.24.14 (or higher), I believe it will actually fix issues for all other packages (using Gtk3 + perl) as well... Said differently : that change will likely break any package using ```Gtk3::TreeModelSort::new_with_model```.  Not sure there are so many, though :-/

Would the patch proposed to the Gtk3-perl team be an option as well ?  There I tried to check the version of Gtk and call the appropriate "introspected" function.
(see https://rt.cpan.org/Public/Bug/Display.html?id=131871)

But I'm feeling like the sorcerer's apprentice here, some feedback from the Gtk3-perl team will be much appreciated :)

**Comment by gfrenoy** [comment]
Unfortunately, no reaction on my message to the Gtk3-perl project ; can anyone try to reach them out en increase the importance of the issue ?

On the other side, I'll think about a way to workaround the issue inside the Ásbrú code base.

**Comment by gfrenoy** [comment]
Fyi, a fix has been pushed upstream (see https://gitlab.gnome.org/GNOME/perl-gtk3/-/commit/b857d1c1bf1ce29813639d35b5459755ec08462c).

Can someone test it ?

**Comment by figue** [comment]
Upstream patch is working. Thanks for the report and all your work.

**Comment by panciom** [comment]
On Debian SID the file is located on:
/usr/share/perl5/Gtk3.pm

I also confirm that deleting lines works.

Thank to all as always.
Mirko

**Comment by gfrenoy** [comment]
Fixed upstream.
