### ISSUE TITLE
Debian/Ubunt 16.04 - Issue whil einstalling Asbru-CM package with error " Failed to connect to packagecloud.io port 443: Connection timed out"

### ISSUE THREAD

**Issue by arvind-kvak** [asbru-cm/asbru-cm#422]
**Describe the bug**
Having issue while reinstalling the arbru-cm package. The connection is timing out as it cannot reach the https link.
**To Reproduce**
1) Previously i had the package running.
2) I have uninstalled  as i was having some issue with terminal
3) while trying to re install the package the htps connection is failing with error
**_"Installing /etc/apt/sources.list.d/asbru-cm_asbru-cm.list...curl: (7) Failed to connect to packagecloud.io port 443: Connection timed out

Unable to run:
    curl https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/config_file.list?os=Ubuntu&dist=xenial&source=script_**

Double check your curl installation and try again.

**Expected behavior**
expect the package to be installed as i have all the dependencies installed.

**Logs**

u1604:~$ curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/asbru-cm_asbru-cm.list...curl: (7) Failed to connect to packagecloud.io port 443: Connection timed out

Unable to run:
    curl https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/config_file.list?os=Ubuntu&dist=xenial&source=script

Double check your curl installation and try again.
avijay@avijay-u1604:~$ apt-get install curl
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

$ sudo apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.47.0-1ubuntu2.14).
The following packages were automatically installed and are no longer required:
  gir1.2-vte-2.91 gir1.2-wnck-3.0 libcairo-gobject-perl libcrypt-blowfish-perl
  libcrypt-cbc-perl libcrypt-rijndael-perl libexpect-perl
  libglib-object-introspection-perl libgtk3-perl libgtk3-simplelist-perl
  libio-pty-perl libio-stty-perl libnet-arp-perl libnet-pcap-perl
  libnet-proxy-perl libossp-uuid-perl libossp-uuid16 libvte-2.91-0
  libvte-2.91-common libwnck-3-0 libwnck-3-common libx11-guitest-perl
  libyaml-libyaml-perl libyaml-perl
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 243 not upgraded.

$ sudo apt-get install -y apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apt-transport-https : Depends: apt (>= 1.5~alpha4) but 1.2.32 is to be installed
E: Unable to correct problems, you have held broken packages.

$ sudo dpkg -i apt-transport-https_1.2.32_amd64.deb
(Reading database ... 172511 files and directories currently installed.)
Preparing to unpack apt-transport-https_1.2.32_amd64.deb ...
Unpacking apt-transport-https (1.2.32) over (1.2.32) ...
Setting up apt-transport-https (1.2.32) ...
$ sudo apt-get install -f
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gir1.2-vte-2.91 gir1.2-wnck-3.0 libcairo-gobject-perl libcrypt-blowfish-perl
  libcrypt-cbc-perl libcrypt-rijndael-perl libexpect-perl
  libglib-object-introspection-perl libgtk3-perl libgtk3-simplelist-perl
  libio-pty-perl libio-stty-perl libnet-arp-perl libnet-pcap-perl
  libnet-proxy-perl libossp-uuid-perl libossp-uuid16 libvte-2.91-0
  libvte-2.91-common libwnck-3-0 libwnck-3-common libx11-guitest-perl
  libyaml-libyaml-perl libyaml-perl
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 243 not upgraded.

$ sudo apt install ./apt-transport-https_1.2.32_amd64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'apt-transport-https' instead of './apt-transport-https_1.2.32_amd64.deb'
apt-transport-https is already the newest version (1.2.32).
The following packages were automatically installed and are no longer required:
  gir1.2-vte-2.91 gir1.2-wnck-3.0 libcairo-gobject-perl libcrypt-blowfish-perl
  libcrypt-cbc-perl libcrypt-rijndael-perl libexpect-perl
  libglib-object-introspection-perl libgtk3-perl libgtk3-simplelist-perl
  libio-pty-perl libio-stty-perl libnet-arp-perl libnet-pcap-perl
  libnet-proxy-perl libossp-uuid-perl libossp-uuid16 libvte-2.91-0
  libvte-2.91-common libwnck-3-0 libwnck-3-common libx11-guitest-perl
  libyaml-libyaml-perl libyaml-perl
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 242 not upgraded.

**Desktop (please complete the following information):**

**Additional context**

**Comment by arvind-kvak** [comment]
Please suggest me how i can resolve the above issue.

**Comment by gfrenoy** [comment]
> Failed to connect to packagecloud.io port 443: Connection timed out

According to the error message and for some reason, you cannot establish the communication to packagecloud.io server.

Sorry but we cannot help much on this, you have to check your own infrastructure and understand why that connection is not working.

**Comment by KlaasT** [comment]
A connection timed out is caused due to local network issues or if the packagecloud servers have too much load or a maintenance window for that particular moment. I'm afraid we won't be able to help there. Please try it again or check with your local network/firewall if a connection is maybe being blocked for some reason.

Closed #422
