### ISSUE TITLE
Enable port range for mosh connections

### ISSUE THREAD

**Issue by rmueck** [asbru-cm/asbru-cm#424]
First of all: I love asbru-cm! Thanks for this great software!

It would be really handy to have an option to define a port range for mosh connections!

On a normal shell session i can use:  `mosh --ssh="ssh -p 22"  -p 60000:60005 user@target.net`

But asbru-cm only got an option to define *one* port for a session.

If i try to open another session i got (as expected):

```
Failed binding to 0.0.0.0:60000
Error binding to any interface: bind: Address already in use

**Comment by hanspr** [comment]
@rmueck 

Would it suffice if we dynamically retry for the next available port (lets say from default port to +20)?

**Comment by rmueck** [comment]
> @rmueck
> 
> Would it suffice if we dynamically retry for the next available port (lets say from default port to +20)?

@hanspr 
I think this would be a valid way to make multiple connection working!  thx :)

**Comment by hanspr** [comment]
I'll take this

**Comment by hanspr** [comment]
It has been added to next version 6.3, you can test it now if you install the Snapshot releases (I'm not sure if is already in one now) or the loki releases.

https://docs.asbru-cm.net/General/Installation/

**Comment by gfrenoy** [comment]
You can test this in the "loki" version ; let us know if it works for you !

**Comment by rmueck** [comment]
Hi! 
I can confirm that the solution is working fine in 6.3.0 . 
Thank you.
