### ISSUE TITLE
Display of pseudographics picture in /etc/motd is broken

### ISSUE THREAD

**Issue by shvets-alex** [asbru-cm/asbru-cm#425]
1. Connect to the server with pseudographics picture on motd with last asbru release via ssh.

2. See unreadable symbols on screen and unreadable symbols on login line, like:
ubuntu@server:~$ 62;c62;c62;c62;c62;c62;c62;c62;c62;c

3. If I run 'cat /etc/motd' graphics seens well.

In asbru 5.2.x all works fine. The problem appeared when we started using the new version.

Crashed image:
![изображение](https://user-images.githubusercontent.com/19223066/75421992-3f210c00-5944-11ea-867e-54cfa876630a.png)

Working image:
![изображение](https://user-images.githubusercontent.com/19223066/75422037-5c55da80-5944-11ea-86ef-6a33e4be6737.png)

**Comment by gfrenoy** [comment]
Looks to be the same as #423, isn't it ?

**Comment by gfrenoy** [comment]
Can you share an example of a ```/etc/motd``` file that does not work for you ?

**Comment by gfrenoy** [comment]
Definitely the same same as #423; please join the discussion there.
