### ISSUE TITLE
First connection to RDP in compact mode fails

### ISSUE THREAD

**Issue by figue** [asbru-cm/asbru-cm#426]
**Describe the bug**
If compact mode is set, first attempt to open a RDP connection fails. In console you can see xfreerdp help which means that some parameter is wrong. I think it's /size which probably should not be added to commandline if Terminal Tabbed Window doesn't exist.

**To Reproduce**
1. Set compact mode.
2. Connect with xfreerdp to any server
3. See error
4. Tap INTRO key to connect to server

**Expected behavior**
In traditional layout, this works.

**Screenshots**
I can manage to get the commandline of 2 attempts:

fri 28 feb 2020 00:23:32 CET
/usr/bin/xfreerdp /parent-window:69207944 **/size:-9x-84** /bpp:32 +compression /kbd:0x0000040A /d:mydomain +clipboard /cert-ignore /rfx /dynamic-resolution +fonts -grab-keyboard /u:myusername /p:password /v:myserver:3389

fri 28 feb 2020 00:23:54 CET
/usr/bin/xfreerdp /parent-window:69210252 **/size:1670x913** /bpp:32 +compression /kbd:0x0000040A /d:mydomain +clipboard /cert-ignore /rfx /dynamic-resolution +fonts -grab-keyboard /u:myusername /p:password /v:myserver:3389

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version latest git, master branch

**Comment by gfrenoy** [comment]
Thanks for your feedback Joan, I believe I found the issue : Gtk does not refresh the allocated size while creating the window ; I made a change to force a redraw of the created window so that we can have the correct size before starting the RDP connection.

Let me know if it works for you !

**Comment by figue** [comment]
Thanks @gfrenoy it works.
