### ISSUE TITLE
Installation fails in Arch or Manjaro

### ISSUE THREAD

**Issue by blacknet76** [asbru-cm/asbru-cm#427]
I have tested the installation in Arch Linux and Manjaro but the installations fails because perl-expect does not exist

I used the AUR Helper yay 

Here are the output message 
==> Erstelle Paket: perl-expect 1.35-1 (Fr 28 Feb 2020 18:31:50 CET)
==> Empfange Quellen...
  -> Lade Expect-1.35.tar.gz herunter...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to search.cpan.org port 80: Verbindungsaufbau abgelehnt
==> FEHLER: Fehler beim Download von http://search.cpan.org/CPAN/authors/id/J/JA/JACOBY/Expect-1.35.tar.gz
    Breche ab...
Error downloading sources: perl-expect

The Uri http://search.cpan.org/CPAN/authors/id/J/JA/JACOBY/Expect-1.35.tar.gz does not exist.
Have anyone a workaround to install perl-expect? I searched but I can't find a working package.

**Comment by gfrenoy** [comment]
Strangely enough, that same URL works for me:

```
wget http://search.cpan.org/CPAN/authors/id/J/JA/JACOBY/Expect-1.35.tar.gz                                                              
--2020-02-28 18:47:27--  http://search.cpan.org/CPAN/authors/id/J/JA/JACOBY/Expect-1.35.tar.gz
Resolving search.cpan.org (search.cpan.org)... 151.101.14.217, 2a04:4e42:3::729
Connecting to search.cpan.org (search.cpan.org)|151.101.14.217|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cpan.metacpan.org/authors/id/J/JA/JACOBY/Expect-1.35.tar.gz [following]
--2020-02-28 18:47:32--  https://cpan.metacpan.org/authors/id/J/JA/JACOBY/Expect-1.35.tar.gz
Resolving cpan.metacpan.org (cpan.metacpan.org)... 151.101.14.217, 2a04:4e42:3::729
Connecting to cpan.metacpan.org (cpan.metacpan.org)|151.101.14.217|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 61667 (60K) [application/x-gzip]
Saving to: ‘Expect-1.35.tar.gz’

Expect-1.35.tar.gz                    100%[=======================================================================>]  60,22K  --.-KB/s    in 0,05s   

2020-02-28 18:47:33 (1,12 MB/s) - ‘Expect-1.35.tar.gz’ saved [61667/61667]
```

Can you try again or check your network settings ?

**Comment by blacknet76** [comment]
Damed, thx for the hint for the Network, Pi-hole have blocked search.cpan.org. 
You make my day. Thanks gfreony
