### ISSUE TITLE
active Terminal Tab is not marked if placed on the right or left side

### ISSUE THREAD

**Issue by jok76** [asbru-cm/asbru-cm#429]
If Terminal tab list is configured to be shown at top or buttom (Terminal Options -> Look and Feel -> Tabs position), then the active Tab is marked (blue underline) as seen here:
![asbru-tab1](https://user-images.githubusercontent.com/60010383/75624882-0c337e00-5bb9-11ea-8c2f-29f96f9e6bcf.png)
If tab list position is configured to be on the right or left, then the active tab is not marked. There is not difference between active and inactive tabs.
![asbru-tab2](https://user-images.githubusercontent.com/60010383/75624883-0ccc1480-5bb9-11ea-830b-8b0b8c4b1776.png)

Seen under Kubuntu 19.10 with arsbru 6.1.0rc1.

**Comment by gfrenoy** [comment]
What is the Gtk-theme that you are using ?

The tab is correctly marked as active by Ásbrú but the way it is rendered depends on how the Gtk-theme decides to display this.  You'll need to report this to theme maintainers, I do fear.

**Comment by jok76** [comment]
Understand. I use breeze as gtk-theme. And you are right, if I choose default there, the tab is marked correctly - whatever default means ...
Well in this case I suggest to close this issue. Thanks for the quick response, it's great to see how active this project is maintained!

**Comment by gfrenoy** [comment]
Thanks your feedback and kind words of encouragement !
