### ISSUE TITLE
Add custom hotkeys for scripts and commands

### ISSUE THREAD

**Issue by fringeadmin** [asbru-cm/asbru-cm#43]
It would be very useful to assign a hotkey to a script or command. Having to wade through menus or clutter my screen with buttons and drop downs obviates much of the benefit of having pre-programmed commands.

**Comment by gfrenoy** [comment]
I fully agree :)

Not sure how to do this today though...I guess we'll need a kind of "custom key record" Gtk widget and then adding this input control to parameter of the "Remote Macros" dialog:
![image](https://user-images.githubusercontent.com/981546/34418671-9052a516-ebff-11e7-86a1-d038da5227bd.png)

PR will be welcome :-)

**Comment by hanspr** [comment]
@gfrenoy I'll take this, with #556

**Comment by hanspr** [comment]
A bit late but here it is.

It has been added to next version 6.3, you can test it now if you install the Snapshot releases (I'm not sure if is already in one now) or the loki releases.

https://docs.asbru-cm.net/General/Installation/

**Comment by gfrenoy** [comment]
You should install the "loki" version to test this further.

That being said, I did give it a try and it's working great !  Thanks a lot :)

Let me label it as "waiting feedback" for some days, then we can close it.
