### ISSUE TITLE
Users Manual

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#430]
@gfrenoy 

I think I would like to spent some time creating a users manual. What would be the alternatives?

* Can I clone the wiki pages from here and send pull requests?
* Or use some online service?
* Use mkdocs and the publish the build project in here or some other server?.

Have not used this feature but mkdocs help says it has a deploy to github pages command

```
Usage: mkdocs [OPTIONS] COMMAND [ARGS]...

  MkDocs - Project documentation with Markdown.

Options:
  -V, --version  Show the version and exit.
  -q, --quiet    Silence warnings
  -v, --verbose  Enable verbose output
  -h, --help     Show this message and exit.

Commands:
  build      Build the MkDocs documentation
  gh-deploy  Deploy your documentation to GitHub Pages
  new        Create a new MkDocs project
  serve      Run the builtin development server
```

**Comment by gfrenoy** [comment]
I'd rather think we should not rely too much on external services.  It would be great if we can have a dedicated repository that would hold the sources of a manual.  And that we can generate different kind of output (website, pdf, ...) from those sources files.

Let us know what you would need to make progress on this topic.

**Comment by KlaasT** [comment]
I added new mkdocs generation today. It will be autogenerated for docs.asbru-cm.net

The files are being placed into the doc/ folder of the master branch and newly generated as soon a commit to master happens.

If you would like to add something to the docs feel free to work inside there. For the navigation on the left the mkdocs.yml has to be edited.

If you have any questions regarding this feel free to ask me :-)

**Comment by hanspr** [comment]
thanks @KlaasT 

I will check it out during the weekend

**Comment by hanspr** [comment]
@KlaasT 

I like to apply this theme to mkdocs, check it out and see if you like it, and if it can be added and will not create a conflict with your deployments.

https://squidfunk.github.io/mkdocs-material/

**Comment by hanspr** [comment]
Sent my first PR for documentation, lets hope it works.

I assume that should be sent to master so it publishes automatically after merged, right?

**Comment by hanspr** [comment]
And, sorry to state the obvious, English is not my mother tongue so if there is a proficient English speaking contributor that would proof my documentation you are very welcome.

**Comment by KlaasT** [comment]
You can Push them to loki If it is easier. I will merge the Docs then

**Comment by hanspr** [comment]
@KlaasT 

Hi Klass, I have a little issue with the menus, I think that multilevel entries are required.

The standard theme that we use produces this layout, that is fine but the 3 levels are lost, the second level shows indented at the level of the first, and does not collapses its content.

![imagen](https://user-images.githubusercontent.com/1572396/76166872-acdced00-6127-11ea-87b8-cf873ffd033e.png)

The second preinstalled theme is mkdocs, that layout does not looks very nice to me

![imagen](https://user-images.githubusercontent.com/1572396/76166894-cf6f0600-6127-11ea-92aa-c9966c350069.png)

The third option is the one I told you about, material.

![imagen](https://user-images.githubusercontent.com/1572396/76166906-e3b30300-6127-11ea-90c4-2ec1316a996a.png)

I will keep working with the current one, and see if at least I can indent the second level titles with an extra css.

**Comment by hanspr** [comment]
Hi @popxunga

I'm documenting the application, and need some help. I noticed that you use a lot of RDP connections.

If I upload a skeleton with images for the RDP manual page, would you have some spare time to fill it up and complete it with recommendations, tips and tricks?

**Comment by popxunga** [comment]
Hi !
Currently I'm a "little" busy with professional and personal issues.
I just have a dozen of rdp connections, but I'll be glad to help and share
what I can, if your request doesn't need to be answered with urgency.
I do not see this message/email/notification anywhere in github. Where's it
? Do you know ?
Thanks


A segunda, 16/03/2020, 15:22, Hans Peyrot <notifications@github.com>
escreveu:

**Comment by hanspr** [comment]
@popxunga 

>I just have a dozen of rdp connections

I have 2, so I think that makes you the expert.

>Currently I'm a "little" busy with professional and personal issues.

I understand and I work too, but on a weekend or some brakes, I try to give some help. There is no hurry when you can do it when you can.

> I do not see this message/email/notification anywhere in github. Where's it
? Do you know ?

Don't know what you mean, but. The manuals are located in the master branch under the directory __docs__

Just clone this master branch and the documents will be available there.

Just wait for PR #478 to be merged and the RDP skeleton will be there under

`doc/Manual/Connections/RDP.md`

Images are located in : doc/Manual/Connections/images

It uses normal github markup language.

Just clone, create a branch, push your branch, request a PR, and the documentation will publish after merge into : https://docs.asbru-cm.net/

Thanks

**Comment by popxunga** [comment]
I was referring to the email message I got from you. It doesn't come from
your email address,  but from some GitHub notification or personal message
system. So I was expecting to see it somewhere on GitHub. That's my doubt.

A segunda, 16/03/2020, 16:24, Hans Peyrot <notifications@github.com>
escreveu:

**Comment by hanspr** [comment]
Well every time you type @someuser github sends a message to that person, so that is what I did, I include your username in the previous message, and now I have pulled your intervention to this thread.

You may unsubscribe thou, with the "unsubscribe" button above.

**Comment by popxunga** [comment]
Sorry @hanspr  ... it took me while to find where you're writing this :-)
Finally I noticed the issue # in the subject of the emails.

**Comment by popxunga** [comment]
And I will have to study what you're asking as I never did it before...

**Comment by hanspr** [comment]
> And I will have to study what you're asking as I never did it before...

Welcome to the club! , I was there 3 months ago, so if I managed you will.

If you already use the `git` command, it will be very easy.

If you have never used the `git` command (like I didn't 3 months ago), it will be an interesting experience, once the learning curve is passed (less than a week), you will be very happy that you have learned it (I did, and now I use git every day in all my coding with all my client's projects).

Short basics assuming no `git` experience. And for this particular case of editing this documentation.

+ Install `git` from your repos
+ open a terminal
+ `git config --global user.email "youremail@address.com"`
    - Use any public valid email
+ `git config --global user.name "Your Name"`
+ Fork this project clicking on the top right button on this site that says "Fork"
    - How to: https://guides.github.com/activities/forking/
    - You will be sent to your own fork
+ Create a directory in any path where you want to work, for example porpoises, lets say : `/home/myuser/github/` from here on we will reference as `GIT_PATH`
+ cd GIT_PATH
+ First time only
    - `git clone https://github.com/popxpunga/asbru-cm`
    - This will create a subdirectory: `asbru-cm`
+ `cd asbru-cm`
+ Subsequent times after cloning, and before start editing if some days have passed
    - `git pull https://github.com/asbru-cm/asbru-cm.git master`
    - This will pull all changes that everybody has sent and will merge them with your changes
    - This could be complicated for coding but for documentation should not be any issue
+ cd to the docs directory that you will edit `cd docs/Manual/Connections`
+ `git checkout -b docs-rdp master`
    - This creates a branch where you will edit and track your changes
    - As you send more merges try to number your branches : docs-rdp2, docs-rdp3, or any way you like.
+ Edit the `.md` files in docs directory, as you wish
    - Any text editor will do (Visual code has a preview)
    - For a reference of the markup language : https://guides.github.com/features/mastering-markdown/
    - Save your work
+ When finishing editing or you want to save the status of your work
    - `git commit -a -m 'my personal message of what I did'`
+ When finished documenting and want to upload your changes
+ `git push origin docs-rdp`
+ In your browser come to this site (https://github.com/asbru-cm)
+ You will see a warning on the top that says that you have pushed a new branch in your repo if you want to create a PR to asbru-cm
    - Click on the button to create a merge.
    - Fill the comments with any information you find useful for the team to know about.
    - Click on create merge and that is it.
    - When you PR has been accepted
    - `git checkout master`
    - You will be now in your local master branch
    - git pull https://github.com/asbru-cm/asbru-cm.git master`
    - You will pull all the changes from the main project
    - `git branch -D docs-rdp`
    - This will delete your local branch, you already have it in the master
    - `git push -d origin docs-rdp`
    - This will delete your remote branch
+ And back to create a branch and make more changes.
+ Basic tutorial and some videos: https://guides.github.com/introduction/git-handbook/

----

mkdocs

If you want to install mkdocs so you can preview of the manuals and changes in your browser while editing.

+ https://www.mkdocs.org/#installation

+ `cd asbru-cm`
+ `mkdocs serve`
    - This will start a local http server and you can preview your documentation and changes in
    - `http://127.0.0.1:8000/`
+ `<ctrl-C> to stop the server when you are done`

**Comment by popxunga** [comment]
Thanks for the instructions @hanspr !

**Comment by hanspr** [comment]
Hi @merikz 

Sorry to drag you here.

I'm documenting asbru.

https://docs.asbru-cm.net/

And I need some help.

Lately, I just uploaded the manual for SSH. And I have noticed (in several occasions) that your are a very skilled and knowledgable ssh user.

Would it be possible if you could revise and complete the documentation for SSH, and even better write an article about how to take advantage of ssh in asbru?. Give us some tips, tricks, whatever you think any of us would eventually need?

The documentation is located in master at : `doc/Manual/Connections/SSH.md`

You would need to pull, edit, push your changes, and after is merged it would be updated.

If you could share an article would be fantastic. Just put it in : docs/Managing/SSH.md

And if you are familiar with mkdocs then add the document path to the main index or we can do that is no problem.

Hope you could gives as a hand on this, thanks for the help you had given me with your ssh in many of the issues and changes around ssh .

**Comment by merikz** [comment]
Hi,
Thank you Hans for kicking this in motion!
I'll see what I can do, but I'm afraid it might be slow. 

In the mean time, if anyone else have ideas, don't let my possible inaction stop you. Documentation benefit from more than one perspective. 
Co-operation is key!

**Comment by hanspr** [comment]
@KlaasT 

You had never confirm to me if I can test the material theme or if we stick to the current one and I do not move that. Just to be on the same channel.

**Comment by hanspr** [comment]
The documentation project has been started, no need to keep this open.

**Comment by gfrenoy** [comment]
@hanspr : the "material" theme is now activated :)

See https://docs.asbru-cm.net/

**Comment by hanspr** [comment]
> @hanspr : the "material" theme is now activated :)

What do you think, better or worst?
