### ISSUE TITLE
asbru 6.2 (loki branch) vs asbru 6.1.0rc1 - Colors

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#431]
Hi ! 
I just gave a try to the loki branch version to see how it goes.
I'm using adwaita-dark default theme on gnome3.
This is how the connection tree looks on 6.1.0rc1:
![image](https://user-images.githubusercontent.com/37672088/75630888-46674480-5be6-11ea-83b9-6d8c6ddb581e.png)
And this is how it looks on 6.2.0~1583062339-1.el7:
![image](https://user-images.githubusercontent.com/37672088/75630895-5bdc6e80-5be6-11ea-8b67-094dcf844b7a.png)
As you can see, with the exception of the highlighted connection, the rest is pretty hard to read with the new loki branch color scheme.
Is there anything that can be done to get this better ?
Thanks.

**Comment by hanspr** [comment]
We added a protected and not protected color settings in new settings "Look and Feel"

![imagen](https://user-images.githubusercontent.com/1572396/75631107-abef0d00-5bb5-11ea-813d-a427ad37fa70.png)

You will have to play with the foreground colour of your protected and not protected fields now.

It was added to give more flexibility to stand out either protected or not protected nodes.

**Comment by popxunga** [comment]
Thanks for the tip ...
However I've played with those options but nothing changes that I can see, I mean the colors remain the same everywhere, no matter what colors I select with those "Color for" controls. 
I do not see any errors in the terminal from where I launched asbru.
What am I missing ?

**Comment by hanspr** [comment]
Even after restart Asbru?

Get mi an image of how are you configured the options to see what did you do

**Comment by hanspr** [comment]
For example I have this combination in a dark backgroud

![imagen](https://user-images.githubusercontent.com/1572396/75633388-f67a8480-5bc9-11ea-8df1-4356b8774da5.png)

**Comment by popxunga** [comment]
After Asbru restart it works (shame on me) :-) 
If a restart is required as it seems, I suggest adding a legend bellow the "Color for", something like: (* restart required)

**Comment by popxunga** [comment]
Well ... I've just found something similar to what I suggested in the Main Preferences Behaviour tab:
![image](https://user-images.githubusercontent.com/37672088/75808669-62eab480-5d7f-11ea-9bb5-c124f748f414.png)

BTW ... the message still mentions PAC instead of Asbru.

And in the Look & Feel tab as well:
![image](https://user-images.githubusercontent.com/37672088/75808996-e60c0a80-5d7f-11ea-850b-2f9966a6dbc1.png)
So it is just a matter of adding the missing (*) :-)

**Comment by gfrenoy** [comment]
Just pushed a changed on loki to take your remarks into consideration.  Let me know if there's any other star (*) we need to add.  Otherwise, let's close this issue for now.

Thanks for your feedback !

**Comment by popxunga** [comment]
Hi @gfrenoy 
Not that I'm aware of without testing all them :-)

Now you may want to normalize the messages as well.
In the Behaviour tab: 
![image](https://user-images.githubusercontent.com/37672088/75811159-da224780-5d83-11ea-8770-3c87fe89b6d3.png)
In the Look & Feel tab:
![image](https://user-images.githubusercontent.com/37672088/75811277-08a02280-5d84-11ea-9f25-2dc2b103e0ec.png)

Thanks.

**Comment by gfrenoy** [comment]
I believe I changed this already (see https://github.com/asbru-cm/asbru-cm/commit/63f7facf2d4b418c7e1933fc30792c1ee80f85b8).

Check with the latest loki build and let me know if you still see something to change (or close the issue if OK).

**Comment by popxunga** [comment]
True @gfrenoy ... just tested the last loki build and it is fine :-)
I'm closing the issue now. Thanks !
