### ISSUE TITLE
6.1.0rc1 crashes on startup

### ISSUE THREAD

**Issue by yarons** [asbru-cm/asbru-cm#433]
**Describe the bug**
When trying to start the app (either using the icon or the command line) the app crashes although the loading screen appears for a short while.

**To Reproduce**
1. Click on the application icon

Alternative:
1. Run `asbru-cm` using CLI

**Expected behavior**
The app should start.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version 19.0.1

**Additional context**
My perl version is v5.30.1.

Error message is:
```
INFO: Ásbrú Connection Manager 6.1.0rc1 (asbru-cm) started with PID 1457
INFO: Desktop environment detected : other
INFO: Using config directory '/home/yaron/.config/pac'
INFO: Used config file '/home/yaron/.config/pac/pac.nfreeze'
Can't find information for method TreeModel::sort_new_with_model at /opt/asbru-cm/lib/PACMain.pm line 537.
```

**Comment by gfrenoy** [comment]
See #421

**Comment by yarons** [comment]
Sorry.
