### ISSUE TITLE
6.0.4-1 - The tabs are not closed

### ISSUE THREAD

**Issue by The-Course** [asbru-cm/asbru-cm#434]
**Describe the bug**
When I try to close a TAB it doesn't close

**To Reproduce**
ASBRU version 6.0.4-1

1. I open a saved connection
2. I close the tab -> I confirm that I want to close it
3. The TAB does not close

**Expected behavior**
That the TAB would close

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Version 19.10

**Additional context**
Running CLI asbru-cm I find the following output when I try to close the TAB :

```
*** Vte::Terminal::feed_child: passed too many parameters (expected 2, got 3); ignoring excess at /opt/asbru/lib/PACUtils.pm line 3881.
*** unhandled exception in callback:
***   need an array ref to convert to GArray at /opt/asbru/lib/PACUtils.pm line 3881.
***  ignoring at /usr/share/perl5/Gtk3.pm line 572.
```

**Comment by gfrenoy** [comment]
Can you confirm the version of VTE you are using ?

This should be given by:
```
apt show libvte-2.91-0
```

You may also want to share the output of
```
 dpkg -l | grep "libvte"
```

**Comment by The-Course** [comment]
Hello,

below the required output:

```
thecourse@thecourse-ThinkPad-T440s:~$ dpkg -l | grep "libvte"
ii  libvte-2.91-0:amd64                           0.58.2-1ubuntu2                             amd64        Terminal emulator widget for GTK+ 3.0 - runtime files
ii  libvte-2.91-common                            0.58.2-1ubuntu2                             all          Terminal emulator widget for GTK+ 3.0 - common files
ii  libvte-2.91-dev:amd64                         0.58.2-1ubuntu2                             amd64        Terminal emulator widget for GTK+ 3.0 - development files
ii  libvte-2.91-doc                               0.58.2-1ubuntu2                             all          Terminal emulator widget for GTK+ 3.0 - documentation
ii  libvte-common                                 1:0.28.2-6build1                            all          Terminal emulator widget for GTK+ 2.x - common files
ii  libvte-dev                                    1:0.28.2-6build1                            amd64        Terminal emulator widget for GTK+ 2.0 - development files
ii  libvte9                                       1:0.28.2-6build1                            amd64        Terminal emulator widget for GTK+ 2.0 - runtime files
ii  libvted-3-0                                   3.9.0-1                                     amd64        Terminal emulator widget for GTK+ - D bindings
thecourse@thecourse-ThinkPad-T440s:~$ apt show libvte-2.91-0
Package: libvte-2.91-0
Version: 0.58.2-1ubuntu2
Priority: optional
Section: libs
Source: vte2.91
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 526 kB
Depends: libvte-2.91-common (>= 0.58.2-1ubuntu2), libatk1.0-0 (>= 1.12.4), libc6 (>= 2.28), libcairo2 (>= 1.10.0), libfribidi0 (>= 1.0.0), libglib2.0-0 (>= 2.40.0), libgnutls30 (>= 3.6.5), libgtk-3-0 (>= 3.20), libpango-1.0-0 (>= 1.22.0), libpangocairo-1.0-0 (>= 1.22.0), libpcre2-8-0 (>= 10.32), libstdc++6 (>= 5.2), zlib1g (>= 1:1.2.0)
Homepage: https://wiki.gnome.org/Apps/Terminal/VTE
Task: ubuntu-desktop-minimal, ubuntu-desktop, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, xubuntu-core, xubuntu-desktop, ubuntustudio-desktop-core, ubuntustudio-desktop, ubuntukylin-desktop, ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-budgie-desktop
Supported: 9m
Download-Size: 180 kB
APT-Manual-Installed: no
APT-Sources: http://it.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
Description: Terminal emulator widget for GTK+ 3.0 - runtime files
 The VTE library provides a terminal emulator widget VteTerminal for
 applications using the GTK+ toolkit. It also provides the VtePTY object
 containing functions for starting a new process on a new
 pseudo-terminal and for manipulating pseudo-terminals.
 .
 This package contains the runtime library, needed by programs using the
 VTE widget with GTK+ 3.0.
```

**Comment by gfrenoy** [comment]
Ok thanks.  Let me give it a try with VTE 0.58 and see if I observe the same...

**Comment by gfrenoy** [comment]
On my Ubuntu 19.10 test environment, using VTE 0.58, all is working as expected.

I do suspect it is not use the right version of VTE... Don't you have a manually installed version of VTE ?  From a legacy PAC install, maybe ?

To make sure we are on the right track, can you add the following line in ```sub new``` of ```PACMain.pm```:

```
    print STDERR "INFO: Using VTE " . Vte::get_major_version() . "." . Vte::get_minor_version() . "\n";
```

This should confirm the exact version that is used by Ásbrú.

Thanks for your help !

**Comment by The-Course** [comment]
Good morning,

thank you for your availability.

I added the line in `PACMain.pm` and the output is the following:

```
INFO: Ásbrú started (asbru-cm) with PID 28702
INFO: Desktop environment detected : other
INFO: Using VTE 0.50
....
....
```
so there is a version misalignment of the VTE.

I made the installation through this guide:

http://www.linuxfromscratch.org/blfs/view/svn/gnome/vte.html

Is there a more correct procedure to install the VTE?

Thanks in advance!

**Comment by gfrenoy** [comment]
> INFO: Using VTE 0.50

Ah ah.  This is interesting :)

So now I understand why we cannot easily reproduce what you see : this is very unexpected version on Ubuntu 19.10 !

> http://www.linuxfromscratch.org/blfs/view/svn/gnome/vte.html

Mmm, the latest version is 0.58 so how do you explain you have 0.50 ?  Can you go to that procedure again with the latest sources ?

> Is there a more correct procedure to install the VTE?

Well, there's basically nothing to do...

The package ```libvte-2.91``` (that is part of the Ásbrú dependencies) should provide you the necessary files.

Unless you have a good reason to do so, I would uninstall any specific version of VTE and use the Ubuntu package.

If you really want to have you own build, please make sure you have at least 0.52.

**Comment by The-Course** [comment]
Good morning,

I have tried to remove the libvte-2.91 package via apt and its dependent packages (including asbru-cm).
I have reinstalled libvte-2.91, and subsequently asbru-cm, but in any case the startup recognizes me version 0.50 of the VTE:

```
INFO: Ásbrú Connection Manager 6.2.0 (asbru-cm) started with PID 6447
INFO: Desktop environment detected : other
INFO: Config directory is '/home/thecourse/.config/pac'
INFO: Used config file '/home/thecourse/.config/pac/pac.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.50
INFO: Theme directory is '/opt/asbru/res/themes/asbru-color'
```

BUT with the latest update to 6.2.0 (loki!) The problem of the boards has been solved, and this even before doing the VTE removal and reinstallation tests!
The tests above I wanted to do only to see if the version detected by asbru changed.

So for me the bug is solved!
But if further tests and tests were needed to help improve asbru I am more than happy to make myself available!

**Comment by gfrenoy** [comment]
> I have tried to remove the libvte-2.91 package

No.  That one is a requirement, you should keep it.  What you need to remove is the "custom install" you did "from scratch" (see http://www.linuxfromscratch.org/blfs/view/svn/gnome/vte.html you mentioned).

Said differently: if you are using Ubuntu 19.10 and libvte-2.91 : you should see VTE version 0.58 !  If you don't see that ; you screwed up your system in a strange way...

> BUT with the latest update to 6.2.0 (loki!) (...)
> So for me the bug is solved!

Yes, in 6.1 (and 6.2) ; we added code to cope with older version.  We do not intend to backport this to 6.0.

> But if further tests and tests were needed to help improve asbru I am more than happy to make myself available!

Thanks!  Tests and accurate feedbacks are important to make progress, great to have your contribution to the project :)
