### ISSUE TITLE
Ásbrú crash on rdp logout in compact mode

### ISSUE THREAD

**Issue by figue** [asbru-cm/asbru-cm#436]
**Describe the bug**
Ásbrú closes itself when you logout from a RDP server in compact mode.

**To Reproduce**
1. Open RDP session in compact mode
2. Logout from remote windows server
3. See error

**Desktop (please complete the following information):**
 - OS: Archlinux
 - 6.1.0RC1

**Additional context**
Console output:
```
figue@pluto ~ % asbru-cm
INFO: Ásbrú Connection Manager 6.1.0rc1 (asbru-cm) started with PID 26784
Use of uninitialized value $ENV{"XDG_SESSION_DESKTOP"} in string eq at /usr/bin/asbru-cm line 197.
INFO: Desktop environment detected : xfce
INFO: Using config directory '/home/figue/.config/pac'
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/lib/perl5/5.30/vendor_perl/Glib/Object/Introspection.pm line 67.
INFO: Used config file '/home/figue/.config/pac/pac.nfreeze'
INFO: Using Gnome tray icon

(asbru-cm:26784): Gdk-ERROR **: 18:36:59.023: The program 'asbru-cm' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 24526 error_code 3 request_code 40 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
zsh: trace trap (core dumped)  asbru-cm
```

**Comment by gfrenoy** [comment]
Does this happens all the time (every time you log out) or only "sometimes" ?

**Comment by hanspr** [comment]
I'm in mint, cinnamon and does not happen to me.

So I guess it has to do with something in xfce. Or the configuration settings. Or some other unexpected updates in arch.

Could you please export your configurations in Preferences > Export > Data for DEBUG, to see if it helps to reproduce.

**Comment by figue** [comment]
> Does this happen all the time (every time you log out) or only "sometimes" ?

You are right, it's sometimes... I'll try to figure out when exactly. Now I have logout 2 times to reproduce the crash.

Config attached:
[debug.yml.gz](https://github.com/asbru-cm/asbru-cm/files/4283249/debug.yml.gz)

**Comment by hanspr** [comment]
@figue 

Ok, I found a problem (not the one described here), with this setting "Enable dynamic resolution"

![imagen](https://user-images.githubusercontent.com/1572396/75822696-0038ef00-5d66-11ea-9d49-51a0b4147516.png)

Try inactivating options that are not relevant and see if at some point the problem disappears, if not, place an image with the minimal options active, that produces your error to see if I can replicate.

**Comment by figue** [comment]
Sorry, I can't reproduce this issue anymore. Will close and if it starts again will open a new issue. Thanks
