### ISSUE TITLE
Loki branch - Improve anonymized configuration export

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#439]
Hi @hanspr ...

By inspecting my own configuration export I would anonymize:

1. The global variables names and values;
2. Any Keepass related info (including the database location and name);
3. All Prepend Commands;
4. RDP Domain and Shared Disk parameters;
5. SSH Options (Local & Remote Port Forwarding options, Dynamic socks proxy and probably Advanced options too);
6. #HOSTNAME, #DESKTOP_STARTUP_ID or anything containing the HOSTNAME value.

Thanks

**Comment by hanspr** [comment]
@popxunga 

Sent a PR, when is merged hope you can run more tests to see if I cached correctly all of them.

**Comment by popxunga** [comment]
Hi @hanspr 
Just tested the latest loki build and the anonymized export is almost there.
RDP Domain and Shared Disk parameters are still being exported unmasked;
And I just detected a couple of ssh sessions using expect that didn't get masked as well (needs additional investigation). 
Everything else seems fine.
Thanks.

**Comment by popxunga** [comment]
Hi @hanspr 

I do have a couple of ssh nodes where I'm using expect, and where I'm sending a string like this uppon command prompt detection:
ssh userid@hostname
This data does not get masked in the exported file.

Found another minor glitch during the export operation related with the file name.
When exporting the anonymized configuration I get the prompt file name:
![image](https://user-images.githubusercontent.com/37672088/75875134-09c86280-5e0b-11ea-8937-80f280e0c267.png)

But after export completes, I get this:
![image](https://user-images.githubusercontent.com/37672088/75875193-2369aa00-5e0b-11ea-9a8b-21655b224c48.png)

So 1st it show's debug.txt but then it saves the file as debug.yml.
When choosing the export yml path, the default file name is always asbru.yml.

Thanks once more.

**Comment by hanspr** [comment]
>Just tested the latest loki build and the anonymized export is almost there.
RDP Domain and Shared Disk parameters are still being exported unmasked;
Everything else seems fine.

I will need more than just a comment, please send an image to see the records that were not processed and see how they are saved, you may blur what you consider sensitive data, but I need more information to be able to fix.

**Comment by popxunga** [comment]
Hi @hanspr 
Do you want screenshots of what ? the RDP options ? the ssh expect options ? both ?

**Comment by hanspr** [comment]
All the lines with information that you still consider should be removed.

The best would be the lines in the debug.yml file that were not cleaned, so I can see how data is stored.

Something like

![imagen](https://user-images.githubusercontent.com/1572396/75896944-67ee4900-5dfd-11ea-9d39-16585fa0b2cc.png)

If you like to send the image of that configuration to show how to reproduce the record It helps to

![imagen](https://user-images.githubusercontent.com/1572396/75897316-febb0580-5dfd-11ea-8b78-fc3cfb1c979c.png)

The more detailed and clear is the information that I can receive, the more precise I can be in my solutions, otherwise I'm left with my imagination and I do not trust it very much.

**Comment by hanspr** [comment]
@popxunga 

Sent a PR round 2, when merged check and lets see if I got it right this time.

**Comment by gfrenoy** [comment]
Great discussion and improvement !  Thanks both for your contribution.

**Comment by popxunga** [comment]
Hi @hanspr ...
Just tested with asbru-cm-6.2.0~1583362318-1.el7.noarch.rpm and the domain and shared disk options in the RDP connections are still being written in the anonymized yml file. Example:
method: RDP (rdesktop)
    name: 'name 103'
    options: ' -5 -a 16 -P -g 1600x900 -k pt -r sound:off -r clipboard:PRIMARYCLIPBOARD -**d XXXXXXXXX -r disk:xxxxxxx="/xxx/xxxxxx/xxxxxxxx"**'
    parent: f4875dc0-59b8-4411-bc96-bf9e7fc1d908

Everything else looks fine.
Thanks for your support.

**Comment by hanspr** [comment]
Ok, I only use xfreerdp, I have never been able to use rdesktop, thank for the line, the parameters are different than the ones from xfreerdp, will send the next PR soon.

**Comment by hanspr** [comment]
Uploaded new PR, when merged, check that if there is still anything else.

**Comment by hanspr** [comment]
>options: ' -a 24 -g 1400x800 -k pt -d removed --plugin cliprdr --plugin rdpdr --data disk:XXXXXXXX:"/xxx/xxxxxx/xxxxxxx" --'

Guau, this options are different from mine. Well, will send another PR, later.

**Comment by hanspr** [comment]
Thanks @popxunga 

Sent PR 4, to include this variation. Test after merged.

**Comment by popxunga** [comment]
Hi @hanspr & @gfrenoy 
Just tested with the new PR4 and found no additional issues after a quick check :-)
So this can be closed now.
Thanks !

**Comment by gfrenoy** [comment]
Thanks for the improvements brought to this feature.
