### ISSUE TITLE
asbru-cm freeze

### ISSUE THREAD

**Issue by skuran** [asbru-cm/asbru-cm#441]
**Describe the bug**
asbru-cm v6.1.0rc1 main window hangs when a connection is made.

**To Reproduce**
1. Run asbru make a connection, just after the connection is made , main window freeze , the connections tab gets kindda grey and the mouse pointer turns into "busy" . The connection is also disconnects.

**Expected behavior**
No freeze expected.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 16.04

**Additional context**

When run from terminal:

$ asbru-cm 
INFO: Ásbrú Connection Manager 6.1.0rc1 (asbru-cm) started with PID 10015
INFO: Desktop environment detected : other
INFO: Using config directory '/home/meter/.config/pac'
INFO: Used config file '/home/meter/.config/pac/pac.nfreeze'
INFO: Using Gnome tray icon
*** unhandled exception in callback:
***   Can't locate object method "set_bold_is_bright" via package "Vte::Terminal" at /opt/asbru/lib/PACTerminal.pm line 456.
***  ignoring at /usr/lib/x86_64-linux-gnu/perl5/5.22/Glib/Object/Introspection.pm line 67.

**Comment by skuran** [comment]
When I downgrade to 6.0.4 , freeze gone. 
$  dpkg -l | grep "libvte"
ii  libvte-2.91-0:amd64                        0.42.5-1ubuntu1                                          amd64        Terminal emulator widget for GTK+ 3.0 - runtime files
ii  libvte-2.91-common                         0.42.5-1ubuntu1                                          all          Terminal emulator widget for GTK+ 3.0 - common files

**Comment by The-Course** [comment]
Let's discuss this in #435 and #434.

**Comment by gfrenoy** [comment]
@skuran Commit https://github.com/asbru-cm/asbru-cm/commit/4004637770904cc9989bbee727e32fd60bb7ff4b should have fixed this.  It will be available in our next release.

In the meantime, you can try our snapshot release (see [instructions](https://github.com/asbru-cm/asbru-cm/wiki/installation-on-ubuntu)).

**Comment by skuran** [comment]
Latest snapshot 6.1.0rc2 fixed 

Great !
