### ISSUE TITLE
Synchronize asbru configuration on multiple computers

### ISSUE THREAD

**Issue by The-Course** [asbru-cm/asbru-cm#458]
**Is your feature request related to a problem? Please describe.**
Having more computers that I use for work (from the fixed location to the notebook) I need to have the washed-out connections synchronized between the various computers.

**Describe the solution you'd like**
An option that makes it possible to position the configurations and connections saved on an ftp / webdav protocol and that are dynamically loaded / updated with each modification / closure of asbru.

**Describe alternatives you've considered**
An option that makes it possible to automatically save the connections with each change / every time asbru is closed in a certain path, if this path was shared on the various computers (network disk, google drive / owncloud / etc folder) the various stations would be synchronized.

**Additional context**
Currently, with osync (https://github.com/deajan/osync) I am copying the .config / pac folder on a path that is synchronized on my owncloud server.
This path is on every compuer where I need to have synchronized asbru.

**Comment by gfrenoy** [comment]
See #34, #198

You can also consider the option ```--config-dir``` (see [manual](https://docs.asbru-cm.net/Manual/CommandLine/)).
