### ISSUE TITLE
Add a way to force a reconnect

### ISSUE THREAD

**Issue by fringeadmin** [asbru-cm/asbru-cm#46]
Very often I find that an SSH session disconnects but the terminal window stays hung. This means that I can't reconnect without opening a new tab, which in turn means that I can't save the history of the previous tab.

This could be addressed by fixing the timeout issue, but there are still scenarios where a session might take a long time to timeout. A better overall solution would be to allow a forced reconnect in the tab. This would abort the existing connection and start a new one.

**Comment by gfrenoy** [comment]
Did you try the CTRL+SHIFT+R shortcut key ?  That should do it.

In the terminal, it's also available with a right-click > Session > Disconnect and Restart session:
![image](https://user-images.githubusercontent.com/981546/34641194-a1509b5e-f300-11e7-8556-7268a8bbae32.png)

Let us know if this matches your need.

**Comment by fringeadmin** [comment]
Perfect, thank you that meets my needs exactly.
