### ISSUE TITLE
Ubuntu 16.04 error with version 6.1.0rc1-1

### ISSUE THREAD

**Issue by thriskel** [asbru-cm/asbru-cm#468]
Once the ssh connection is established, the software freezes, like the main frame was busy doing some process.

To reproduce the error you would just have to start a ssh connection, once its connected it will freeze the GUI.

Only errors I caught were these:
***   Can't locate object method "set_bold_is_bright" via package "Vte::Terminal" at /opt/asbru/lib/PACTerminal.pm line 456.
***  ignoring at /usr/lib/x86_64-linux-gnu/perl5/5.22/Glib/Object/Introspection.pm line 67.

 - OS: Ubuntu 16.04 x64
 - Kernel: 4.4.0-174-generic

**Comment by hanspr** [comment]
Hi, @KlaasT 

This has already been fixed with the last merges in loki, but it is still a recurring issue, how can @thriskel update to a patched version or when the new release will be available?

**Comment by KlaasT** [comment]
We have fixed this in master. I will release a new RC this afternoon. This should be fixed in the new RC.

**Comment by thriskel** [comment]
Alright, will test it once it is released!

**Comment by gfrenoy** [comment]
See #441
