### ISSUE TITLE
RPM package installs /asbru-cm in root

### ISSUE THREAD

**Issue by ValdikSS** [asbru-cm/asbru-cm#47]
RPM package asbru-cm-5.0.0-1.fc27.noarch installs script file /asbru-cm, right in the root folder. This shouldn't happen.

**Comment by gfrenoy** [comment]
Indeed.  Looks to be the [completion script](https://github.com/asbru-cm/asbru-cm/blob/master/res/asbru_bash_completion):
![image](https://user-images.githubusercontent.com/981546/34650504-8c702f98-f3c2-11e7-825f-16bb7882f67e.png)

I suspect that [line 1 of the spec file](https://github.com/asbru-cm/asbru-cm/blob/master/dist/rpm/asbru.spec#L1) did not work on the build machine...?

**Comment by KlaasT** [comment]
Going to look at that one

**Comment by Cris70** [comment]
Confirmed here

**Comment by KlaasT** [comment]
Already tried to fix that. At the moment I do not understand why the build process isn't respecting the variable. Need to do some further investigations.

**Comment by KlaasT** [comment]
Fixed in https://github.com/asbru-cm/asbru-cm/commit/6252a5f7debc3c68dd3f24bdeeb1ed4355718e28 will be in the next release.
