### ISSUE TITLE
Loki branch - Pseudo-jump server

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#470]
Hi Team !

Sometimes the key exchange process necessary to use a normal jump server is not allowed.
By pseudo-jump server I mean use any existing ssh connection as a jump server. 
The idea would be select one existing connection as a pass through to reach a final target ssh host. 
So, having something like follows may help a lot, specially when the password of the account used to login into the pseudo-jump server gets changed:
![image](https://user-images.githubusercontent.com/37672088/76661879-6a2a7300-6574-11ea-9f60-7715e7817145.png)

The red rectangle represents a combo-box from where we would select the intended pseudo-jump server (the combo-box list should be filled with list of existing connections, except the one being edited).

As an workaround I currently use the Expect feature to achieve a similar result, but is more difficult to maintain. In addition my current plan is remove all password's stored in Asbru config as soon as the integration with Keepassxc get's mature enough. Tested it for while on latest PAC version and it was unusable. Will start testing it on Asbru very soon. 
Storing the pseudo-jump servers passwords in global variables would make things easier considering an expired password scenario, but it doesn't look a good alternative from the security point of view either.

Thanks.

**Comment by hanspr** [comment]
I'll take this

**Comment by popxunga** [comment]
Hi @hanspr and @gfrenoy ...
Just tested the pseudo-jump feature.
It is mostly working, except when I select the "Add Url KeePassXC" option in the Terminal Host or in the IP/Host fields. Looks like the lookup process on KeePassXC is not working properly for these fields. May you check it please ?
Thanks a lot for your support :-)

**Comment by popxunga** [comment]
Hi @gfrenoy and @hanspr 
Working fine after the last commit :-)
Not sure if you want to get this one closed, so I'll let it open for now.
Thanks !

**Comment by gfrenoy** [comment]
Great !  Thanks for the review and tests :)  Yes, we can close it ; it is marked for 6.3.0.
