### ISSUE TITLE
Loki branch - Change Expired Password

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#473]
Hi Team ...

While changing an expired password I'm getting a dialog pop-up like this:
![image](https://user-images.githubusercontent.com/37672088/76681472-03946c00-65eb-11ea-838f-5e030421f2bd.png)

I enter the old password and then I get a new pop-up asking for the new password:
![image](https://user-images.githubusercontent.com/37672088/76681486-39395500-65eb-11ea-8468-49c3070f7f17.png)

Then I would expect to get a third pop-up asking for the new password confirmation, but I get nothing.
And when I try to paste the new password in the ssh window, the paste option is disabled in the context menu:
![image](https://user-images.githubusercontent.com/37672088/76681538-f75cde80-65eb-11ea-89b3-c35d0ff9737c.png)

Is there a way to avoid those GTK pop-ups ?
Or can we get the 3rd pop-up in order to complete the change password process ?

Thanks for your support.

**Comment by gfrenoy** [comment]
This is a follow up of #138 and, indeed, it was not foreseen to check for password confirmation...

Should be possible though ; do you know how the remote server should be configured to ask for this confirmation ?

**Comment by popxunga** [comment]
Hi @gfrenoy & @hanspr 

Not sure if I understood your question about configuration.

An expired password change process works like follows in any Unix system I worked with so far (except for root accounts where step 3 doesn't occur).
1- You login with the old password;
2- You get a reply stating that the password is expired and ...;
3- ... the old password is requested once again;
4- The new password is requested;
5- The new password confirmation is requested.

The existing process works fine from 1 to 4 and stops. 
But we are missing step 5.

Thanks.

**Comment by gfrenoy** [comment]
> Not sure if I understood your question about configuration

To be able to reproduce what you see, I was wondering how to configure the remote SSH server so that is asks for a confirmation.  As far as I remember, when I did the change for #138, it did not ask me for a confirmation...?

**Comment by popxunga** [comment]
I think there's no special configuration on SSH server's to achieve the described behavior, which I'm sure is the default on most operating systems and tested on Centos 7/8, Mint 19.3, Ubuntu Server 18.3, AIX, etc,. Here you have an example taken an Ubuntu Server:
![image](https://user-images.githubusercontent.com/37672088/76703005-1af45780-66c6-11ea-85de-5db4bfd56d30.png)

At least a setting to disable those ridiculous pop-up's should be provided to let us deal with the change password process directly in the terminal.

**Comment by gfrenoy** [comment]
Mmm, can you check your ```PASSWORD prompt``` setting in ```Preferences``` ?

Default is ```([pP]ass|[pP]ass[wW]or[dt](\s+for\s+|\w+@\w+)*|[cC]ontrase.a|Enter passphrase for key '.+')\s*:\s*$``` and does not trigger a popup in my case.

**Comment by hanspr** [comment]
@gfrenoy , I think he means that we should not use a "pop up window" to collect the password and then send it to the login session.

I do not think this is possible, having expect and an interactive window at the same time, or is it? Do not see any examples of this in the Expect module documentation.

**Comment by hanspr** [comment]
Ha, big surprise , it is possible, thow the password is shown in the terminal. I will give it a tray, I think that removing the pop up, if possible would be good.

We would get rid of the using popup with untransient parent warning off, the login would be more natural on the same terminal.

**Comment by popxunga** [comment]
Hi @hanspr ...
I should say that I don't remember to see those popup's until recently.
I'm sure that I never saw those pop-up's on PAC 4.x and Asbru 5.x.
They started with Asbru 6.x... not sure with which version however.

**Comment by popxunga** [comment]
> Mmm, can you check your `PASSWORD prompt` setting in `Preferences` ?
> 
> Default is `([pP]ass|[pP]ass[wW]or[dt](\s+for\s+|\w+@\w+)*|[cC]ontrase.a|Enter passphrase for key '.+')\s*:\s*$` and does not trigger a popup in my case.
@gfrenoy ... mine looks like this:
[pP]ass|[pP]ass[wW]or[dt](\s+for\s+|\w+@\w+)*|[cC]ontrase.a|Enter passphrase for key '.+')\s*:\s*$

**Comment by hanspr** [comment]
@popxunga 

Try with this regex for the password prompt.

`(?mi)(pass(word|phrase)|contrase).*?:.*$`

**Comment by popxunga** [comment]
@hanspr 
With that regex expression, I still got the pop-ups (3x this turn) which allowed me to complete the change password process successfully.
Thanks.

**Comment by popxunga** [comment]
Hi @hanspr 
Be aware that some systems my trow messages like this during login:

_userid@xxx.xxx.xxx.xxx's password: 
[compat]: xxxx-xxx Your password will expire: Mon Mar 23 17:54:11 WET 2020_

or other messages during password change process, stating that the new password being entered does not meet some security established criteria.

With the old regex, the login illustrated above succeeds.
With the new regex, the login fails, but I think you didn't merge the fix into the loki branch yet.
Will wait for the fix to re-test.

**Comment by popxunga** [comment]
Hi @hanspr ...

And messages like this should be ignored as well during the login process:

_Last login: Qui Mar  5 19:06:16 WET 2020 on pts/2
Last failed login: Seg Mar 16 09:45:30 WET 2020 on pts/5
There was 1 failed login attempt since the last successful login._

**Comment by hanspr** [comment]
Yes, that was a very general regex

This should work better, give it a test:

`(?mi)(pass(word|phrase)|contrase).*?:\s*$`

I need some other small changes in place to have the final one that should be:

`(?mi)(pass(word|phrase)|contraseña).*?:\s*$`

**Comment by popxunga** [comment]
Hi @hanspr ...
Yes ... it works better. 
Let's wait for the other small changes and then the final one.
Thanks.

**Comment by gfrenoy** [comment]
Sorry I'm a bit lost and could not follow up all the details.

1) I do not see the popups in my testing environment
2) Playing with the PASSWORD prompt looks to provide a solution

So do we really need to change the code at this stage ?

**Comment by hanspr** [comment]
1. It was the regex, it needs more improvements, with that change it works, with or without popups. And you should see popups if you are changing password or do not have a password set for a connection.

2. No.

But I would like to leave the new parameter in `sub wEnterValue` so it can be implemented later with a simple added parameter or by adding an option to later be able to choose how to interact.

And for the time being call the routine with false so it behaves with popups.

Do you have some time to chat?, contact you there?

**Comment by popxunga** [comment]
Hi @hanspr 

In one of my clients, the system's admin decided to widely setup PS1 variable as follows:
[hostname:userid:/home/userid:]

I just tested the last couple of loki builds with the 3 regex expressions, the default one and the two mentioned above, and the with that PS1 the login process never completes.

May you suggest something that can make the automated login process survive to things like this ?
Thanks

**Comment by hanspr** [comment]
>In one of my clients, the system's admin decided to widely setup PS1 variable as follows:
[hostname:userid:/home/userid:]

How does the login process looks like, I can not imagine it

Show me the sequence that is printed on the screen.

**Comment by popxunga** [comment]
Hi @hanspr ...
Does this help ?
`CONNECTING WITH hostname - (XXX) - XXX - X (Thu Mar 19 16:17:15 2020)

[pac_conn(23857)][hostname - (XXX)][hostname - (XXX) - XXX - X]: !!_PAC_AUTH_[pac_PID{7611}_n14]!!
[pac_conn(23857)][hostname - (XXX)][hostname - (XXX) - XXX - X]: SPAWNING:<GV:XXX> ssh -p 22   -x -C -L XXX.x.x.x:xxxxx:xxx.x.x.x:xxxxx -l userid xx.xxx.xxx.xxx
[pac_conn(23857)][hostname - (XXX)][hostname - (XXX) - XXX - X]: SPAWNED:'<GV:XXX> ssh -p 22   -x -C -L XXX.x.x.x:xxxxx:xxx.x.x.x:xxxxx -l userid xx.xxx.xxx.xxx' (PID:23857)
Starting EXPECT pattern matching...
 at /usr/share/perl5/vendor_perl/Expect.pm line 561.
	Expect::expect('Expect=GLOB(0x39315a8)', 40, 'ARRAY(0x39d7a50)', 'ARRAY(0x39d1aa0)', 'ARRAY(0x39d1800)', 'ARRAY(0x39d1578)', 'ARRAY(0x39d1458)', 'ARRAY(0x39d1068)', 'ARRAY(0x39d0eb8)', ...) called at /usr/share/asbru-cm/lib/pac_conn line 1783
spawn id(13): list of patterns:
  #2: -eof `'
  #3: -re `\\[__PAC__SUDO__PROMPT__\\]'
  #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'
  #5: -re `.*(any key to continue|tecla para continuar).*'
  #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'
  #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'
  #8: -re `(?mi)(pass(word|phrase)|contrase).*?:\\s*$'
  #9: -re `[#%\\$>]|\\:\\/\\s*$'


spawn id(13): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `(?mi)(pass(word|phrase)|contrase).*?:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

userid@xx.xxx.xxx.xxx's password: 
spawn id(13): Does `userid@xx.xxx.xxx.xxx\'s password: '
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `(?mi)(pass(word|phrase)|contrase).*?:\\s*$'? YES!!
    Before match string: `userid@xx.xxx.xxx.xxx\'s '
    Match string: `password: '
    After match string: `'
    Matchlist: (`password',  `word')
Calling hook CODE(0x39d0e58)...
Sending 'password\n' to spawn id(13)
 at /usr/share/perl5/vendor_perl/Expect.pm line 1264.
	Expect::print('Expect=GLOB(0x39315a8)', '5G\b?\;$/?x3<VE\x{a}') called at /usr/share/asbru-cm/lib/pac_conn line 513
	main::send_slow('Expect=GLOB(0x39315a8)', '5G\b?\;$/?x3<VE\x{a}', 'hide') called at /usr/share/asbru-cm/lib/pac_conn line 1632
	main::__ANON__('Expect=GLOB(0x39315a8)') called at /usr/share/perl5/vendor_perl/Expect.pm line 760
	Expect::_multi_expect(40, 'ARRAY(0x39cc648)', 'ARRAY(0x39cbee0)') called at /usr/share/perl5/vendor_perl/Expect.pm line 565
	Expect::expect('Expect=GLOB(0x39315a8)', 40, 'ARRAY(0x39d7a50)', 'ARRAY(0x39d1aa0)', 'ARRAY(0x39d1800)', 'ARRAY(0x39d1578)', 'ARRAY(0x39d1458)', 'ARRAY(0x39d1068)', 'ARRAY(0x39d0eb8)', ...) called at /usr/share/asbru-cm/lib/pac_conn line 1783
[pac_conn(23857)][hostname - (XXX)][hostname - (XXX) - XXX - X]: PASSWORD:Sent (not shown)
Continuing expect, restarting timeout...

spawn id(13): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `(?mi)(pass(word|phrase)|contrase).*?:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.



spawn id(13): Does `\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `(?mi)(pass(word|phrase)|contrase).*?:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

Last unsuccessful login: Wed Mar 18 21:27:53 WET 2020 on ssh from xxx.xx.xxx.xxx
Last login: Thu Mar 19 09:19:23 WET 2020 on ssh from xxx.xx.xxx.xxx

spawn id(13): Does `\r\nLast unsuccessful login: Wed Mar 18 21:27:53 WET 2020 on ssh from xxx.xx.xxx.xxx\r\nLast login: Thu Mar 19 09:19:23 WET 2020 on ssh from xxx.xx.xxx.xxx\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `(?mi)(pass(word|phrase)|contrase).*?:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

===============================================================================
=             O DIREITO DE ACESSO A ESTE SISTEMA E' RESERVADO !!              =
===============================================================================

spawn id(13): Does `\r\nLast unsuccessful login: Wed Mar 18 21:27:53 WET 2020 on ssh from xxx.xx.xxx.xxx\r\nLast login: Thu Mar 19 09:19:23 WET 2020 on ssh from xxx.xx.xxx.xxx\r\n===============================================================================\r\n=             O DIREITO DE ACESSO A ESTE SISTEMA E\' RESERVADO !!              =\r\n===============================================================================\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `(?mi)(pass(word|phrase)|contrase).*?:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

=                                                                             =
=      Este sistema deve ser utilizado apenas em actividades de xxxxxxx       =
=                       autorizada pela Xxxxxx xx Xxxx xxxxx XX               =
=                                                                             =
===============================================================================
=    Este sistema esta' sujeito a auditorias efectuadas a qualquer momento.   =
===============================================================================


spawn id(13): Does `\r\nLast unsuccessful login: Wed Mar 18 21:27:53 WET 2020 on ssh from xxx.xx.xxx.xxx\r\nLast login: Thu Mar 19 09:19:23 WET 2020 on ssh from xxx.xx.xxx.xxx\r\n===============================================================================\r\n=             O DIREITO DE ACESSO A ESTE SISTEMA E\' RESERVADO !!              =\r\n===============================================================================\r\n=                                                                             =\r\n=      Este sistema deve ser utilizado apenas em actividades de xxxxxxx       =\r\n=                       autorizada pela Xxxxxx xx Xxxx xxxxx XX               =\r\n=                                                                             =\r\n===============================================================================\r\n=    Este sistema esta\' sujeito a auditorias efectuadas a qualquer momento.   =\r\n===============================================================================\r\n\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `(?mi)(pass(word|phrase)|contrase).*?:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

[hostname:userid:/home/userid:] 
spawn id(13): Does `...nsuccessful login: Wed Mar 18 21:27:53 WET 2020 on ssh from xxx.xx.xxx.xxx\r\nLast login: Thu Mar 19 09:19:23 WET 2020 on ssh from xxx.xx.xxx.xxx\r\n===============================================================================\r\n=             O DIREITO DE ACESSO A ESTE SISTEMA E\' RESERVADO !!              =\r\n===============================================================================\r\n=                                                                             =\r\n=      Este sistema deve ser utilizado apenas em actividades de xxxxxxx       =\r\n=                       autorizada pela Xxxxxx xx Xxxx xxxxx XX               =\r\n=                                                                             =\r\n===============================================================================\r\n=    Este sistema esta\' sujeito a auditorias efectuadas a qualquer momento.   =\r\n===============================================================================\r\n\r\n[hostname:userid:/home/userid:] '
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `(?mi)(pass(word|phrase)|contrase).*?:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

[pac_conn(23857)][hostname - (XXX)][hostname - (XXX) - XXX - X]: CLOSE:TIMEOUT:40 seconds trying to connect or get prompt!!
[pac_conn(23857)][hostname - (XXX)][hostname - (XXX) - XXX - X]: DISCONNECTING
[pac_conn(23857)][hostname - (XXX)][hostname - (XXX) - XXX - X]: DISCONNECTED
[pac_conn(23857)][hostname - (XXX)][hostname - (XXX) - XXX - X]: DISCONNECTING
[pac_conn(23857)][hostname - (XXX)][hostname - (XXX) - XXX - X]: DISCONNECTED

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Thu Mar 19 16:17:58 2020)
`

**Comment by hanspr** [comment]
Hi  @popxunga 

Thank, it helped a lot.

So, you will need a particular regex to detect the prompt command.

![imagen](https://user-images.githubusercontent.com/1572396/77091191-dc181780-69cd-11ea-902f-b4596a642584.png)

But, I do not think that for this particular case, is wise to modify the global regex

I would configure a regex for that or those particular connections in their connections terminal options.

![imagen](https://user-images.githubusercontent.com/1572396/77091378-15508780-69ce-11ea-8c05-e65caf0b724a.png)

I suppose a regex similar to this should work.

`\[.+?:\]\s*$`

Can I use this case to create another article about all this process and document it in the manuals?

**Comment by popxunga** [comment]
Hi @hanspr ...
I tested the regex expression above at global level and it generates problems with other clients connections. So, I prefer to use the private terminal options for this particular client connections. 
I tested the first couple of regex expressions and both worked fine; so I keep the simpler one :-)
Yes you can use this case to create another article.

**Comment by hanspr** [comment]
This should be closed.

The original problem has already been solved.
