### ISSUE TITLE
Loki branch - Copy connection password having the connection set with Keepass

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#475]
Hi Team ...
The improvement added with [#295](https://github.com/asbru-cm/asbru-cm/issues/295) does not work properly when the connection credentials is setup with Keepass.
Once the Copy password option is selected from the Node context menu, the password is not being obtained from the Keepass vault; instead I get the string written in the Password field after setup the connection with Keepass, e.g. <password|/group//host>.
Thanks.

**Comment by gfrenoy** [comment]
Should be fixed by the [latest commit](https://github.com/asbru-cm/asbru-cm/commit/46cc0d735de302202b7c269ce961372ae33f24fd) ; let us know if it works for you.

**Comment by popxunga** [comment]
Yes it works fine now. Thanks.
