### ISSUE TITLE
Copy-Paste in ASBRU terminal adds 0~ and 1~

### ISSUE THREAD

**Issue by KarelWintersky** [asbru-cm/asbru-cm#479]
**Describe the bug**
Copy-Paste in terminal adds 0~ and 1~

**Comment by gfrenoy** [comment]
Please describe a bit more in detail how you perform that "copy-paste" operation.
Please also specify the version you are using.

As a matter of fact, copy-paste works fine for me...

**Comment by syco** [comment]
Little late, but it might still be useful..
I don't think this is a problem with asbru terminal per se, I had the same issue on terminator some time ago.
Here's the explanation/solution I found online:
https://unix.stackexchange.com/questions/196098/copy-paste-in-xfce4-terminal-adds-0-and-1
