### ISSUE TITLE
Mass-Import from a csv File

### ISSUE THREAD

**Issue by Thuemmi** [asbru-cm/asbru-cm#48]
Hi,
i search a way for an mass-import (more the 100 hosts) from a csv? Any way for that?

thx
Thuemmi

**Comment by gfrenoy** [comment]
Did you check issue #31 ?  There are some hints there and also a starting script to do what you would like to do.

**Comment by gfrenoy** [comment]
Supposedly fixed due to inactivity.  Feel free to re-open if required.
