### ISSUE TITLE
Find connection tree (Ctrl-Shift-F) moves app to most left screen

### ISSUE THREAD

**Issue by Ragzid** [asbru-cm/asbru-cm#486]
**Describe the bug**
When Ctrl-Shift-F is pressed the whole application is moved to most left screen

**To Reproduce**
1. Open AsbruCM
2. Press Ctrl-Shift-F

**Expected behavior**
The should remain on same screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 10 stable
 - both 5.x (tested shortly before upgrading to 6.0) and 6.x (including latest 6.1.0rc2-1 from packagecloud)
 - DE: Gnome 3.30, LXDE (same behaviour, using mostly default settings)

**Additional context**
I discovered shortcut Ctrl-Shift-F for "blind" search in connection tree.
Everything works great using main desktop setup when left monitor is left.
Issue is when Laptop becomes secondary display placed left of main LCD screen - I wish the app remains at this main screen.

**Comment by gfrenoy** [comment]
Thanks for your report ; this issue has been fixed and should be available in our snapshot release in a few minutes and in our next release.
