### ISSUE TITLE
sftp does not honor jump host setting

### ISSUE THREAD

**Issue by merikz** [asbru-cm/asbru-cm#489]
**Describe the bug**
sftp session is attempted directly to target, without using the jump host.

**To Reproduce**
1. Open a connection with a Jump Host active in Preferences-Network Settings
2. Right click in the session window, and select "Open new sftp window"
3. The connection fails, as the sftp does not go through the Jump host

**Expected behavior**
sftp  should go though the Jump Host

**Screenshots**
The command for the failing sftp is
sftp -i "/home/user/.ssh/id_rsa_lab" -P 22  username@labhost.example.com 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Version: asbru v6.1.0rc1

**Additional context**
sftp on my system does not honor the -J option, but this command works:
sftp -i /home/user/.ssh/id_rsa_lab -P 22  -F /home/user/.config/pac/tmp/b8284b55-3c8b-4198-a727-bd389b30e245.conf -o Proxyjump=jumpserver username@labhost.example.com
Where the conf file is the one used for the "parent" ssh session.

**Comment by hanspr** [comment]
@merikz 

Sent the PR with your configuration line, it does work. Thanks !
