### ISSUE TITLE
Jump Server authentication

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#490]
Implement authentication for the JumpServer

Idea

+ Password fields in : general network and Connection network
+ KeyFile or username / passwd
    - If keyfile is defined, then saved password is a passphrase
    - If key file is absent, then is user name and password
+ Try to determine which password / passprhase is being asked for each connection, one for the jump server and the end machine
    - If keyfile configured, we can determine password being requested by comparing the key file path saved vs. the keyfile path in the expect
    - Worst case, both authentications are user/password, we might need to use flags assuming jumpserver authentication comes first.

**Comment by popxunga** [comment]
Hi @hanspr ...
I think that this idea may cover in some extent what I requested on #470.
Would it be possible in the situation where "If key file is absent, then is user name and password" to get the userid and password values from Keepasscx ?
Thanks

**Comment by hanspr** [comment]
I'll take this
