### ISSUE TITLE
right click on last version

### ISSUE THREAD

**Issue by sarnovich** [asbru-cm/asbru-cm#492]
Im using debian 10 with KDE.
When i goint to right click it not working.

(asbru-cm:6263): Gtk-WARNING **: 13:33:37.678: MenuParentRedUno (Puerto Madrin) :179:EndMenuParent: missing action MenuParentRedUno (Puerto Madrin) :179:EndMenuParent

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.679: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.680: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.681: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.682: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.683: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_menu_item_get_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(asbru-cm:6263): Gtk-CRITICAL **: 13:33:37.684: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed

**Comment by sarnovich** [comment]
Start-Date: 2020-03-20  12:04:18
Commandline: packagekit role='update-packages'
Requested-By: ivan (1000)
Upgrade: lightning:amd64 (1:68.5.0-1~deb10u1, 1:68.6.0-1~deb10u1), thunderbird:amd64 (1:68.5.0-1~deb10u1, 1:68.6.0-1~deb10u1), code:amd64 (1.43.0-1583783132, 1.43.1-1584515895), thunderbird-l10n-es-ar:amd64 (1:68.5.0-1~deb10u1, 1:68.6.0-1~deb10u1)
End-Date: 2020-03-20  12:04:51

Start-Date: 2020-03-20  13:17:58
Commandline: packagekit role='install-files'
Requested-By: ivan (1000)
Downgrade: asbru-cm:amd64 (6.1.0rc2-1, 6.1.0rc1-1)
End-Date: 2020-03-20  13:18:00

Start-Date: 2020-03-20  13:19:43
Commandline: packagekit role='install-files'
Requested-By: ivan (1000)
Downgrade: asbru-cm:amd64 (6.1.0rc1-1, 6.0.4-1)
End-Date: 2020-03-20  13:19:44

Start-Date: 2020-03-20  13:21:25
Commandline: apt remove asbru-cm
Requested-By: ivan (1000)
Remove: asbru-cm:amd64 (6.0.4-1)
End-Date: 2020-03-20  13:21:26

Start-Date: 2020-03-20  13:21:50
Commandline: apt install asbru-cm
Requested-By: ivan (1000)
Install: asbru-cm:amd64 (6.1.0rc2-1)
End-Date: 2020-03-20  13:21:51

Start-Date: 2020-03-20  13:23:17
Commandline: apt-get purge --remove asbru-cm
Requested-By: ivan (1000)
Purge: asbru-cm:amd64 (6.1.0rc2-1)
End-Date: 2020-03-20  13:23:18

Start-Date: 2020-03-20  13:33:07
Commandline: apt install asbru-cm
Requested-By: ivan (1000)
Install: asbru-cm:amd64 (6.1.0rc2-1)
End-Date: 2020-03-20  13:33:08

**Comment by hanspr** [comment]
Right click where?. In the connection tree?, Terminal, Tabs, Info tab?, Clusters?, Editing a Connection?

Please updload an image of where you are clicking to be able to reproduce.

**Comment by sarnovich** [comment]
oh yes... you are right.. my foult!!! it is on right click into the terminal or some server conected.
Im trie on Gnome and KDE. 
Delete all files but i cant use the right click.

(asbru-cm:5051): Gtk-CRITICAL **: 15:03:38.976: gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed
*** unhandled exception in callback:
***   Can't call method "set" on an undefined value at /opt/asbru/lib/PACUtils.pm line 1683.
***  ignoring at /usr/share/perl5/Gtk3.pm line 568.

**Comment by hanspr** [comment]
Something must be wrong with your configuration file.

I you could edit : `/opt/asbru/lib/PACUtils.pm`

And change line 1683

![imagen](https://user-images.githubusercontent.com/1572396/77196663-6a150080-6aa9-11ea-8994-0226433ecf1f.png)

To this

![imagen](https://user-images.githubusercontent.com/1572396/77196729-887afc00-6aa9-11ea-8528-d99b04be45b3.png)

And run asbru from the command line to see if it shows any useful information when you right click.

If it works you may leave it like this at the end

![imagen](https://user-images.githubusercontent.com/1572396/77196673-6ed9b480-6aa9-11ea-8990-843f80089755.png)

Also want to see this option in your settings

![imagen](https://user-images.githubusercontent.com/1572396/77196906-da238680-6aa9-11ea-9ebf-a1c291b35da6.png)

**Comment by sarnovich** [comment]
YEEESSSSSSSSSSSSS it work now!!! thank you very much!!! i love this soft!!!

**Comment by hanspr** [comment]
I know, but I would really need the feed back, could you send the messages about the paths that were invalid?
