### ISSUE TITLE
Window position not properly restored

### ISSUE THREAD

**Issue by gfrenoy** [asbru-cm/asbru-cm#498]
**Describe the bug**
The position of the main Ásbrú window (in classic mode) is not restored to the position it was when the application was closed.  It is always restored to the top-left corner.

**To Reproduce**
1. Open Ásbrú and position it in a given position of the screen
2. Quit the application
3. Restart Ásbrú

**Expected behavior**
Ásbrú should be at the same position as in step 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/981546/77254959-827d4a80-6c64-11ea-8dae-db4bcf4b16d0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: 6.1 and above

**Additional context**
As said in https://wiki.gnome.org/HowDoI/SaveWindowState and https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-get-position, it is best to leave the window position to the window manager so I'd suggest to remove the position management by Ásbrú.

I'll push a fix into loki, this works better for me ; let me know if this should break anything for your distribution / window mananger.

**Comment by popxunga** [comment]
Hi @gfrenoy 
Running RHEL 7.7 here with gnome3 (non-classic mode).
I observed no difference before and after this patch (tested with today loki builds).
If the Asbru main window is closed while not it maximized state, on reopen it get anchored on the top left corner.
