### ISSUE TITLE
text color in dark plasma themes

### ISSUE THREAD

**Issue by wcasanova** [asbru-cm/asbru-cm#499]
**Describe the bug**
friends in the data entry boxes, the cursor is not appreciated, I do not know if it is a problem with the plasma gtk theme "breeze-dark", the problem is that the text is not well appreciated, or the position of the cursor in the text. I present this problem from previous versions

**Screenshots**
![imagen](https://user-images.githubusercontent.com/12401985/77258227-fbc27080-6c57-11ea-97e8-0f5f7d50c73f.png)

**Desktop (please complete the following information):**
 - OS: KDE/Plasma , Archilinux
 -  Asbrú 8f6e217

**Comment by hanspr** [comment]
Edit the file as suggested on the PR #500 to confirm it actually works.

While testing color change it worked for me. Guess your caret color mus be the same as the background

**Comment by wcasanova** [comment]
it worked for the host, but the port did not.

![imagen](https://user-images.githubusercontent.com/12401985/77262224-574e2780-6c73-11ea-87d7-4c7f4f6f467f.png)

**Comment by hanspr** [comment]
Updated #500, apply additional changes, should work for spin buttons too.

**Comment by wcasanova** [comment]
thanks, it's fine

**Comment by gfrenoy** [comment]
Thanks for the report ; it's now available in loki.

**Comment by popxunga** [comment]
Hi @hanspr ...

Just tested with the latest loki build, and this is what I'm seeing:
![image](https://user-images.githubusercontent.com/37672088/77368008-4248c580-6d53-11ea-9a64-da8429f20b3c.png)
The values looks good despite the font is a bit thin.

But the -/+ controls doesn't look good except when the pointer is over them:
![image](https://user-images.githubusercontent.com/37672088/77368303-d581fb00-6d53-11ea-85a3-3a6ea272f966.png)

Thanks.

**Comment by gfrenoy** [comment]
On Ubuntu 16.04, the ```caret-color``` is apparently not supported:

```
asbru.css:17:15'caret-color' is not a valid property name at /usr/lib/x86_64-linux-gnu/perl5/5.22/Glib/Object/Introspection.pm line 67.
```

**Comment by hanspr** [comment]
The only way out is to have a dark theme, added new PR #503 with 2 additional themes: dark and system

If any dark theme user wants to improve the dark theme is welcome.

**Comment by popxunga** [comment]
Hi @hanspr  & @gfrenoy 
Just to say that I tested the latest loki builld with the new Asbru dark mode set in preferences, and it looks good:
![image](https://user-images.githubusercontent.com/37672088/77752883-4fe69f80-7020-11ea-9170-888bfcac73f8.png)

Thanks!

**Comment by ferent** [comment]
I've observed that if you set transparency at any percentage but 0% and restart, the different areas are surrounded by white squares. 

Switched back to 0% transparency and restart shows the areas perfectly fine. 

Tested in Ubuntu 18:04
