### ISSUE TITLE
Expect function doesn't work as expected

### ISSUE THREAD

**Issue by QkiZMR** [asbru-cm/asbru-cm#505]
**Describe the bug**
Expect string is ignored. No matter what I type there Expect is always executed.

**To Reproduce**
1. Add some Expect string
2. Start session
3. See that Expect function is always triggered no matter is Expect string matched or not.

**Expected behavior**
Trigger Expect only when Expect string is matched.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 19.10
 - Asrbu: v6.1.0rc2

**Additional context**
I want to use Expect function to automatic typing password for sudo.

![image](https://user-images.githubusercontent.com/7574087/77568018-434f3380-6ec8-11ea-8ab4-7774477f94f0.png)

![image](https://user-images.githubusercontent.com/7574087/77567483-8230b980-6ec7-11ea-82e6-592a2a905252.png)

**Comment by hanspr** [comment]
Hi @QkiZMR 

Please document with an image of your expect regex, where you are writing it and an image of the connection screen where you say it does not work, to see what you mean. Your asrbu version as well.

**Comment by popxunga** [comment]
Hi !
Something like this should work:
![image](https://user-images.githubusercontent.com/37672088/77549838-3f131e00-6ea8-11ea-93f6-f6f1645bbe31.png)

But if it doesn't, show us what you have defined in the Expect section.

In addtion, in the main preferences uncheck the following:
![image](https://user-images.githubusercontent.com/37672088/77550297-de381580-6ea8-11ea-9505-5cbc59f5bc29.png)

And check the following:
![image](https://user-images.githubusercontent.com/37672088/77550428-06277900-6ea9-11ea-87c2-a90da717339c.png)

Save the main preferences, open your connection, and post the entire output you'll get in the terminal here.

**Comment by QkiZMR** [comment]
> Hi @QkiZMR
> 
> Please document with an image of your expect regex, where you are writing it and an image of the connection screen where you say it does not work, to see what you mean. Your asrbu version as well.

post updated
```
@popxunga debug output:
Starting EXPECT pattern matching...
 at /usr/share/perl5/Expect.pm line 562.
	Expect::expect(Expect=GLOB(0x55dfaac54a40), 60, ARRAY(0x55dfad135280), ARRAY(0x55dfad135388), ARRAY(0x55dfad1355b0), ARRAY(0x55dfad135700)) called at /opt/asbru/lib/pac_conn line 1827
	main::__ANON__(Expect=GLOB(0x55dfaac54a40)) called at /usr/share/perl5/Expect.pm line 761
	Expect::_multi_expect(40, ARRAY(0x55dfad133fc8), ARRAY(0x55dfad134c50)) called at /usr/share/perl5/Expect.pm line 566
	Expect::expect(Expect=GLOB(0x55dfaac54a40), 40, ARRAY(0x55dfad12a1a8), ARRAY(0x55dfad12ab68), ARRAY(0x55dfad12adc0), ARRAY(0x55dfad133260), ARRAY(0x55dfad133350), ARRAY(0x55dfad133758), ...) called at /opt/asbru/lib/pac_conn line 1870
spawn id(12): list of patterns:
  #2: -eof `'
  #3: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'
  #4: -re `'


spawn id(12): Does ` '
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #4: -re `'? YES!!
    Before match string: `'
    Match string: `'
    After match string: ` '
    Matchlist: ()
Calling hook CODE(0x55dfad135610)...
[pac_conn(2685)][jenkins][jenkins - PKOL]: EXPECT:SENDING:<<HIDDEN STRING>>\n
Sending 'password' to spawn id(12)
 at /usr/share/perl5/Expect.pm line 1265.
	Expect::print(Expect=GLOB(0x55dfaac54a40), "password") called at /opt/asbru/lib/pac_conn line 571
	main::send_slow(Expect=GLOB(0x55dfaac54a40), "password") called at /opt/asbru/lib/pac_conn line 1858
	main::__ANON__(Expect=GLOB(0x55dfaac54a40)) called at /usr/share/perl5/Expect.pm line 761
	Expect::_multi_expect(40, ARRAY(0x55dfad133fc8), ARRAY(0x55dfad134c50)) called at /usr/share/perl5/Expect.pm line 566
	Expect::expect(Expect=GLOB(0x55dfaac54a40), 40, ARRAY(0x55dfad12a1a8), ARRAY(0x55dfad12ab68), ARRAY(0x55dfad12adc0), ARRAY(0x55dfad133260), ARRAY(0x55dfad133350), ARRAY(0x55dfad133758), ...) called at /opt/asbru/lib/pac_conn line 1870
Sending '\n' to spawn id(12)
 at /usr/share/perl5/Expect.pm line 1265.
	Expect::print(Expect=GLOB(0x55dfaac54a40), "\x{a}") called at /opt/asbru/lib/pac_conn line 571
	main::send_slow(Expect=GLOB(0x55dfaac54a40), "\x{a}") called at /opt/asbru/lib/pac_conn line 1859
	main::__ANON__(Expect=GLOB(0x55dfaac54a40)) called at /usr/share/perl5/Expect.pm line 761
	Expect::_multi_expect(40, ARRAY(0x55dfad133fc8), ARRAY(0x55dfad134c50)) called at /usr/share/perl5/Expect.pm line 566
	Expect::expect(Expect=GLOB(0x55dfaac54a40), 40, ARRAY(0x55dfad12a1a8), ARRAY(0x55dfad12ab68), ARRAY(0x55dfad12adc0), ARRAY(0x55dfad133260), ARRAY(0x55dfad133350), ARRAY(0x55dfad133758), ...) called at /opt/asbru/lib/pac_conn line 1870
[pac_conn(2685)][jenkins][jenkins - PKOL]: TITLE:jenkins - PKOL
[pac_conn(2685)][jenkins][jenkins - PKOL]: CONNECTED
password
password: command not found

```
After connecting normal prompt is appearing and then string from Send field is pasted with return. 
Of course there was no expected string in terminal.

**Comment by popxunga** [comment]
Hi @QkiZMR,

This looks similar to a case I got a couple of days ago.
Try the following in your jenkins connection definition:

![image](https://user-images.githubusercontent.com/37672088/77569562-4ba47000-6ec2-11ea-8b90-5981431a08e7.png)

Save it and try again.

**Comment by hanspr** [comment]
@QkiZMR 

So when you say `expect` is not working you mean the `regex` for password detection at login is not working for you.

I would still need the full sequence of the login on that machine so I can understand the patterns. Try to login manually so I can see the sequence of messages and the format of the password prompt.

**Comment by QkiZMR** [comment]
@hanspr not really. I mean when I use `sudo` command and system is asking me for a password I want to detect it by expect function and automatic paste password from KeePass for example.

**Comment by hanspr** [comment]
As I understand this last comment.

1) You are login correctly
2) You are at the prompt and then you type `sudo ....`. And then you want that an expect detects that; and prompt you for your password.

If I understood correctly, then the answer is: __that is not possible__.

Ásbrú is not continuously monitoring you typing, Expect only works at the login and then executes your sequences until it ends. Once it ends is over no more expect. Is to automate login and a sequence of continuous events during the login process only.

You could use "Global Variables" or "Remote Commands" to try to accomplish what you want. In combination with KeePass Integration. (Currently while writting detected that KeePass Integration is not linked jet to global commands, so you would have to manually add the mask)

https://docs.asbru-cm.net/Manual/Preferences/RemoteCommands/

https://docs.asbru-cm.net/Manual/Preferences/GlobalVariables/

https://docs.asbru-cm.net/Manual/Preferences/KeePassXC/

For example, you create a remote command like this.

Command `<password|/path/to/my/key/in/keepass>`

Description : `Sudo Passwords: general`

To group your passwords, read the manual links above.

![imagen](https://user-images.githubusercontent.com/1572396/77583848-5f8ea880-6ea7-11ea-922d-23bfb1b19208.png)

Or a global variable, or Remote commands in each terminal if passwords are different.

You would have a way to organize them in a way it works for you.

---

__If I miss understood you, gain__

Please, show me your expects configuration window so I can understand your logic (blur any part you feel is sensitive information, but only the sensitive part, not the hole line or I will not understand it again). And explain as clear and detailed as possible what you try to accomplish, not what you think is wrong.

This is one of my expects.

![imagen](https://user-images.githubusercontent.com/1572396/77581536-7e8b3b80-6ea3-11ea-98aa-ab810597ce4b.png)

After successful login, wait for the prompt, execute `esscgi`

After that, no more expects, finished.

**Comment by hanspr** [comment]
Sorry, never look back at the top of this thread, I see that you have added the images above at the beginning (would prefer you add them in the answer to avoid confusion), this thread is so long, I did not see them before at the top.

Think got you right, then, sorry, not possible. Read the above documentations and possible solutions.

**Comment by hanspr** [comment]
Another small detail on the regex that you use

![imagen](https://user-images.githubusercontent.com/1572396/77661594-7503e100-6f40-11ea-92b5-f770e18bfceb.png)

`[sudo] password for mkukielka`

This would wait a match for: 

`s  password for mkukielka` or
`o  password for mkukielka` or
`d  password for mkukielka` or
`o  password for mkukielka`

But would never match for

`[sudo] password for mkukielka`

Because the brackets tell the regex expression to match any character inside `once` and not including the `[]`

This should be

`\[sudo\] password for mkukielka`

**Comment by QkiZMR** [comment]
> Ásbrú is not continuously monitoring you typing, Expect only works at the login and then executes your sequences until it ends. Once it ends is over no more expect. Is to automate login and a sequence of continuous events during the login process only.

Ok, I understand but what is the difference between Expect and Post Exec function?
I will try a workaround with Global variable/Remote commands and will see if it helps.

**Comment by QkiZMR** [comment]
OMG using remote command is like shooting in your own feet. It shows my password on screen, anybody can read it. Asbru wants me to accept password.
Here is Remote commands config:
![image](https://user-images.githubusercontent.com/7574087/77898032-caaaf700-727a-11ea-9366-4d6c508935c6.png)

And this is window with my password:
![image](https://user-images.githubusercontent.com/7574087/77898126-f8903b80-727a-11ea-991f-b039bd93857c.png)

**Comment by popxunga** [comment]
Hi @QkiZMR 

The Expect function works during the normal login procedure and if you define something in the Expect section of your connection definitions.
The Pre Exec function, executes something before the login begins.
The Post Exec function, executes something after you logout.

Now regarding your initial purpose, this is what I recommend:
If you always run **sudo su -** upon login, you should use the Expect function.
If you need to run **sudo su -** just occasionally, enter sudo su - in the terminal, press Enter, then right click the terminal, select the "Paste Connection Password" option and press Enter.

**Comment by hanspr** [comment]
Hi @QkiZMR 

We are in the process of documenting Ásbrú, is still work in progress.

> what is the difference between Expect and Post Exec function?

Hope this can help

https://docs.asbru-cm.net/Manual/Connections/SSH/

https://docs.asbru-cm.net/Managing/Expect/

> OMG using remote command is like shooting in your own feet

The official releases still have the old implementation of KeePassXC. Do not use KeePass then, the new implementation will not be compatible with anything you do there, so better not use it. And as you have seen it has many issues.

Or if you are willing, you may want to install the loki builds and use the must current one under development.

https://docs.asbru-cm.net/General/Installation/

Follow instruction for : __Testing new features__

And then read how new KeePass integretion works.

https://docs.asbru-cm.net/Manual/Preferences/KeePassXC/

**Comment by QkiZMR** [comment]
> The official releases still have the old implementation of KeePassXC. Do not use KeePass then, the new implementation will not be compatible with anything you do there, so better not use it. And as you have seen it has many issues.
I'm using KeePassXC 2.5.3.
But this window from my previous post (this one with clear text password) was from Asbru, not from KeePassXC.

**Comment by hanspr** [comment]
And I'm referring to Ásbrú too. And I know that the window was from Ásbrú, and my comment was about Ásbrú.

I would recommend to reading the docs

https://docs.asbru-cm.net/Manual/Preferences/KeePassXC/
