### ISSUE TITLE
Drag and drop open tabs 

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#510]
To me the only thing that I miss for asbru to be 100% perfect is to have the ability to drag and drop (to basically reorder) already opened session tabs. 

It happens to me that I have to open a few tabs along the day and I end up with a mess of opened sessions. Every time that happens I think how wonderful it would be if I could order the opened sessions just drag and drop them under or bellow others. 

I don't know how difficult it is to implement this feature and maybe this is just something not feasible, but I'd like to ask the community. 

Thanks for all the effort.

**Comment by gfrenoy** [comment]
For me, it already works but is a bit picky in the allowed moves to achieve it :)

The trick is that you should not get out of the "tab" area and keep your movement "horizontal", see:

![output](https://user-images.githubusercontent.com/981546/77823423-6ada1200-70fb-11ea-84dd-3cad1f56abe6.gif)

Does that work for you ?

Fyi, if you get out the "tab area", it will pop out the connection to a separated window.

**Comment by ferent** [comment]
True! this works for me if I don't move the mouse out of the specific area! Thanks and please proceed to close the ticket.

**Comment by gpavinteractiv** [comment]
@gfrenoy 
This trick doesn't work for me on fedora 41. 
The tab I try to move, exactly as in your exemple, gets kicked to a new window no matter what.
