### ISSUE TITLE
Asbru 6.1 on Mint/Tricia

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#517]
Hi ...
Just tried to update Asbru to 6.1 using the official repo.
While not sure why I'm getting the 6.1 rc2:

~$ date
Fri Mar 27 11:02:57 WET 2020

~$ sudo apt install asbru-cm 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  asbru-cm
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 453 kB of archives.
After this operation, 2510 kB of additional disk space will be used.
Get:1 https://packagecloud.io/asbru-cm/asbru-cm/linuxmint tricia/main amd64 asbru-cm all 6.1.0rc2-1 [453 kB]
Fetched 453 kB in 1s (361 kB/s)
Selecting previously unselected package asbru-cm.
(Reading database ... 491257 files and directories currently installed.)
Preparing to unpack .../asbru-cm_6.1.0rc2-1_all.deb ...
Unpacking asbru-cm (6.1.0rc2-1) ...
Setting up asbru-cm (6.1.0rc2-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23+linuxmint8) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

I checked the asbru-cm repo and I see that the 6.1 release package is there.
Was the asbru-cm repo metadata updated properly ?
Thanks.

**Comment by KlaasT** [comment]
Yes that was my mistake. Release candidates have to be versioned like 6.1.0~rc1 and not 6.1.0rc1 or rc2. I'm fixing the repository right now.

**Comment by KlaasT** [comment]
Pushed 6.1.1 to fix the Debian repository. Sorry for the confusion.
