### ISSUE TITLE
Empty value for "Get Command line"

### ISSUE THREAD

**Issue by beliys** [asbru-cm/asbru-cm#518]
**Describe the bug**
Empty value for "Get Command line"

**To Reproduce**
1. Go to 'Edit Connection' for ssh connection
2. Click on 'Connection->Advanced parameters->Get Command line'
3. See empty result

**Screenshots**
https://i.imgur.com/97fKsj4.png

**Desktop (please complete the following information):**
 - OS: Manjaro KDE
 - Version: latest

**Comment by gfrenoy** [comment]
Thanks for your report !  The issue has been fixed on both loki and 6.1.x branches.  It will be available in the next 6.1.2 release.

(btw, "latest" version is a bit confusing, especially when we will look later one ... better to specify 6.1.x, thanks).

**Comment by popxunga** [comment]
Hi @gfrenoy & @hanspr 
Tested with latest loki build a few minutes ago (where I think the patch is merged already) and got and empty value. 

In the terminal I see this:
[~]$ INFO: Ásbrú Connection Manager 6.2.0 (asbru-cm) started with PID 16329
INFO: Desktop environment detected : gnome-shell:gnome-withtray
INFO: Config directory is '/home/xxxxxxxx/.config/pac'
INFO: Used config file '/home/xxxxxxxx/.config/pac/pac.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.52
INFO: Theme directory is '/usr/share/asbru-cm/res/themes/asbru-dark'
INFO: Using Gnome tray icon
Can't exec "/usr/bin/lib/pac_conn": No such file or directory at /usr/share/asbru-cm/lib/PACEdit.pm line 334.
Use of uninitialized value $cmd in concatenation (.) or string at /usr/share/asbru-cm/lib/PACEdit.pm line 335.

Thanks.

**Comment by gfrenoy** [comment]
Mmm, interesting... You are using the RPM package, right ?

**Comment by gfrenoy** [comment]
If this is what I believe it is, it should be fixed ... Let me know if I guessed it correctly :)

And thanks for the early testing and prompt report !

**Comment by popxunga** [comment]
Hi @gfrenoy 

You're welcome !

We are almost there but not yet. 
You're right about the $Realbin, but there's something else that needs correction.

Upon Asbru launch, if I edit the connection, select Advanced Parms and press the Get Command line button, I get and empty command, and in the terminal I get this:

[~]$ INFO: Ásbrú Connection Manager 6.2.0 (asbru-cm) started with PID 30158
INFO: Desktop environment detected : gnome-shell:gnome-withtray
INFO: Config directory is '/home/xxxxxxxx/.config/pac'
INFO: Used config file '/home/xxxxxxxx/.config/pac/pac.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.52
INFO: Theme directory is '/usr/share/asbru-cm/res/themes/asbru-dark'
INFO: Using Gnome tray icon
Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt.
Died at /usr/share/asbru-cm/lib/pac_conn line 191.

However, if I first open the session, I get the prompt for the credentials, the session gets established,
and just after doing this, the Get Command button works at it should.
If I close the session, and then edit it again, the Get Command button still works fine.

Thanks.

**Comment by popxunga** [comment]
> Mmm, interesting... You are using the RPM package, right ?

And yes ...I'm testing on EL7 ;-)

**Comment by hanspr** [comment]
This is related to KeePass, not having the password set when traing to get the command line and there are fields with the keepass mask, I'll try to fix it now

**Comment by popxunga** [comment]
Hi @hanspr & @gfrenoy ...
Working fine now :-)
Thanks !
