### ISSUE TITLE
Fedora 31 - Transparancy doesn't work

### ISSUE THREAD

**Issue by mvrk69** [asbru-cm/asbru-cm#530]
Hi,

Terminal transparency doesn't work on Fedora 31, is there any way to make it work?

**Comment by gfrenoy** [comment]
According to these lines:

https://github.com/asbru-cm/asbru-cm/blob/a11cb85baf5e94fd6335b1d2ead843facac3c507/lib/PACMain.pm#L468-L470

I'm assuming you are in classic mode with "terminals tabs in main window" checked.  In that case, you need to activate transparency for all terminals in the global preferences.

If for some window you don't want transparency ; you'll have to override the terminal options.

@hanspr this looks a bit cumbersome and counter intuitive, I would suggest we *always* call ```_setWindowPaintable```, what's your call on this ?

**Comment by mvrk69** [comment]
Yes, i activated transparency in global preferences. But still nothing.

**Comment by gfrenoy** [comment]
Should work.  Did you restart the application ?

**Comment by mvrk69** [comment]
Ha sorry, i didn't had that option of "Put Terminals TABS on main window", as soon as i checked that and restarted app it now has transparency. 

But why only works with that option?

**Comment by gfrenoy** [comment]
Don't believe it's necessary but let's wait for Hans' feeback ; maybe there is a particular reason.

In the meantime, if you want to give it a try on your side, you can try to remove the "if" around ```_setWindowPaintable``` ; that should make it work for all cases.

**Comment by hanspr** [comment]
@gfrenoy 

I just finished testing, I never tested for he option "open terminals in tabbed window"

We need to apply the `setWindowPaintable` the the correct window.

+ In the case of "place tabs in main window" it has to be on the "main window"
+ When terminals in different windows, then on each window
+ I missed that there must be another window for the 3rd option.

With respect to setting the window paintable always (or any), I personally think that we should not apply something if is not needed, mostly hacks like this one.

"set to no transparecy" to me means "remove the hack".

We have seen unexpected changes in gtk3 that break stuff. And the hacks can stops working at any moment. If it comes the time for this hack to stop working and the window terminal becomes useless with this hack on. Then there would be no way for a user to go back to a safe setting like "no transparency" to be able to keep working.

I'll find the right window to apply apply the hack for the 3rd case

**Comment by gfrenoy** [comment]
@mvrk69 Improvements have been done about transparency in the last commit.

The number of scenarios were transparency works has been increased ;)

Those changes should be available on the loki branches in a few minutes and in our next major release (not date planned yet).

To test with loki, see instructions here: https://docs.asbru-cm.net/General/Installation/#testing-new-features.

Let us know if this works better for you (or not...)

**Comment by hanspr** [comment]
This should be closed

**Comment by mvrk69** [comment]
Yes, now works fine.

Thanks.
