### ISSUE TITLE
Interface edges less round then PAC

### ISSUE THREAD

**Issue by mvrk69** [asbru-cm/asbru-cm#535]
Hi,

I started trying Asbrus since yesterday, and i noticed the interface is less "roundy" which for me makes it less apealing, dunno if this is supposed to be like this, or some bug?

Here we can see the connections tab edges are rectangular:
![image](https://user-images.githubusercontent.com/3237472/77848078-6d536f00-71c2-11ea-858e-6baeed3d093b.png)

While on pac the edges are round:
![image](https://user-images.githubusercontent.com/3237472/77848085-76444080-71c2-11ea-9678-9883928a228f.png)

Here on the main preferences screen the same thing:
![image](https://user-images.githubusercontent.com/3237472/77848129-d2a76000-71c2-11ea-945e-62d33ed9f4e7.png)

While on PAC much more round edges which look much better:
![image](https://user-images.githubusercontent.com/3237472/77848140-e5ba3000-71c2-11ea-85de-82ed6a70d20b.png)

On the terminal tabs the status bar is too big:
![image](https://user-images.githubusercontent.com/3237472/77848155-1b5f1900-71c3-11ea-95c9-bd83f1ef8fde.png)

Compared to PAC which looks smaller and much more nice:
![image](https://user-images.githubusercontent.com/3237472/77848162-30d44300-71c3-11ea-99e2-51a25b3b3eb1.png)

**Comment by gfrenoy** [comment]
PAC was based on Gtk2.  Ásbrú has migrated to Gtk3 so it is not surprising that this is not exactly the same look & feel.

There are many Gtk themes around so you should try some and find the one that better matches your expectation.

Personally I'm usning [Arc](https://github.com/horst3180/arc-theme). To reclaim empty space, you may want to try a minimalist theme like http://xenlism.github.io/minimalism/.

**Comment by mvrk69** [comment]
I'm using Fedora 31, on gnome-tweak i can see the theme is Adwaita, but everything else looking fine on my desktop, only Asbrus looks a bit ugly.

![image](https://user-images.githubusercontent.com/3237472/77848667-a8f03800-71c6-11ea-8ba7-4492d52caf0c.png)

**Comment by mvrk69** [comment]
hmm... seems no adwaita-gtk3 package:

rpm -qa | grep adwaita
adwaita-icon-theme-3.34.3-2.fc31.noarch
adwaita-qt-common-1.1.1-2.fc31.x86_64
adwaita-cursor-theme-3.34.3-2.fc31.noarch
adwaita-qt5-1.1.1-2.fc31.x86_64
adwaita-gtk2-theme-3.28-6.fc31.x86_64
adwaita-qt4-1.1.1-2.fc31.x86_64
adwaita-gtk2-theme-3.28-6.fc31.i686
adwaita-qt-1.1.1-2.fc31.x86_64

I will try to pick some other theme and try how it looks on Asbrus

**Comment by popxunga** [comment]
Hi @mvrk69 
You may wanna try with Adwaita-dark and Asbru-dark theme selected.
