### ISSUE TITLE
256 color support

### ISSUE THREAD

**Issue by Keridos** [asbru-cm/asbru-cm#54]
Would be nice to have support to emulate up to 256 colors.

**Comment by gfrenoy** [comment]
I first tried a short test found on [here](https://askubuntu.com/questions/821157/print-a-256-color-test-pattern-in-the-terminal#821163):
![image](https://user-images.githubusercontent.com/981546/35192434-66a11eaa-fe92-11e7-80e9-59aad1992c61.png)

Well, it looks that we have 256 colors, aren't we ?

I also found this article : https://codeyarns.com/2015/03/18/how-to-set-term-to-xterm-256color/.  Maybe this can help ?

**Comment by gfrenoy** [comment]
Supposedly works due to inactivity.  Feel free to re-open if required.
