### ISSUE TITLE
search function : Ctrl-F only works when focus is on connections pane

### ISSUE THREAD

**Issue by thijz** [asbru-cm/asbru-cm#543]
**Is your feature request related to a problem? Please describe.**
Hitting Ctrl-F only opens the search box when the focus is on the connections pane
If you are working in a terminal tab Ctrl-F does nothing

**Describe the solution you'd like**
Would be great to have the search box open no matter where you are working

**Describe alternatives you've considered**

**Additional context**

**Comment by gfrenoy** [comment]
Ctrl-Shift+F is the shortcut you can use when the focus is on a terminal.

**Comment by thijz** [comment]
ah ok,
it seems that this search function is limited to the connection names.  it does not search for ip's

**Comment by gfrenoy** [comment]
This should work better in the loki branch : Ctrl+F is now showing the same search form ; whatever the place you're searching for.  The other request will be handled in #544.

Let us know if this works for you.
