### ISSUE TITLE
Loki - EL7 - Keepass master password popup send warning message to terminal

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#549]
Hi ...

Minor issue.

This message is sent to terminal upon Keepass master password dialog popup:

WARN: Wrong parent parameter received _wEnterValue

Thanks

**Comment by gfrenoy** [comment]
Warning message removed when called from main window.

There is another when called directly from ```pac_conn```, not sure how to handle that one.

**Comment by popxunga** [comment]
I'm not seeing the first message anymore with the latest loki build.
Not sure how to reproduce that one that may be generated by pac_conn.

**Comment by gfrenoy** [comment]
> I'm not seeing the first message anymore with the latest loki build.

Ok so that's probably the most important :)

> Not sure how to reproduce that one that may be generated by pac_conn.

When the password is asked for the first time, click "cancel".  It will be asked a second time and that will generate a message inside the terminal.

**Comment by popxunga** [comment]
> > I'm not seeing the first message anymore with the latest loki build.
> 
> Ok so that's probably the most important :)
> 
> > Not sure how to reproduce that one that may be generated by pac_conn.
> 
> When the password is asked for the first time, click "cancel". It will be asked a second time and that will generate a message inside the terminal.

True ... if there's no obvious solution, let's forget the 2nd for now...
Thanks.

**Comment by popxunga** [comment]
Closing.
