### ISSUE TITLE
Icons and some buttons are small on 4K display

### ISSUE THREAD

**Issue by ltden** [asbru-cm/asbru-cm#55]
Hello!
I'm using Linux Mint 18.3 Cinnamon with 4K display.
Double Hi-DPI scaling is on but some icons and buttons are too small, please see attached screenshot:

![asbru](https://user-images.githubusercontent.com/20603656/35166497-83929bd8-fd6b-11e7-94dd-b6a69285becd.jpg)

**Comment by gfrenoy** [comment]
Does not look good, indeed.  Has anyone an idea on how to support this ?

**Comment by ltden** [comment]
Possible GTK3 version supports the scaling better, but I don't know how to build Asbru with GTK3

**Comment by KlaasT** [comment]
We've got a branch for a migration to GTK3 however it isn't finished. We would appreciate help there https://github.com/asbru-cm/asbru-cm/tree/feature-gtk3

**Comment by gfrenoy** [comment]
Don't have a 4K display, can anyone tell us if Ásbrú 6.0 (based on GTK3) looks better or if the problem remains ?

**Comment by nikuzz** [comment]
4K Scale 100%
![4K Scale 100%](https://user-images.githubusercontent.com/17493820/72186368-03aa9c80-33ed-11ea-8434-5f0359935cf4.png)
4K Scale 200%
![4K Scale 200%](https://user-images.githubusercontent.com/17493820/72186385-0dcc9b00-33ed-11ea-954b-3205fe02f5f9.png)

I think it's solved with gtk3! On my Dell XPS 13 (3200x1800) with Double Hi-DPI scaling looks great!

**Comment by gfrenoy** [comment]
Cool :sunglasses: !   And thanks for your feedback!
