### ISSUE TITLE
Right click in connection pane brings up selected item properties, not under-mouse item properties

### ISSUE THREAD

**Issue by demirdag** [asbru-cm/asbru-cm#550]
**Describe the bug**
Richt clicking a connection in the connections window brings up the context menu for the currently selected item, not the item that is under the mouse cursor when it is right-clicked.

**To Reproduce**
1. Go to Connections pane
2. Left-Click **once** on a random connection
3. Hover mouse over another connection and Right-Click this item.
4. Choose "Edit Connection"
5. Observe the properties of the item, they are the properties of the first selected item in step 2.

**Expected behavior**
Properties of the item that is under the mouse. Because when you hover over an item, the item background changes color, to show me that this is the item the mouse-click will react to/on.

**Screenshots**
Won't help

**Desktop (please complete the following information):**
 - OS: Arch
 - Version: Bleeding Edge

**Comment by gfrenoy** [comment]
Thanks for your feedback and accurate report !

It actually annoys me for years as well but never took the time to look at it.

It looks like the event was simply cancelled when showing up the menu.  I let the event happen.  It looks to work fine.

Do you or anybody would see any problem with this ?

**Comment by gfrenoy** [comment]
Ok so this change is now available for the loki branch.  Feel free to comment or re-open if this should cause any issue.
