### ISSUE TITLE
notice repositories that contain old packages like pygpgme

### ISSUE THREAD

**Issue by grey-olli** [asbru-cm/asbru-cm#555]
**Is your feature request related to a problem? Please describe.**
some unsupported packages require old repositories. When speaking about install script from packagecloud.io I miss information about which repo should I install to get those old things. Manual installation dox notice EPEL repos, but people in chats tell that EPEL things are not for current fedora 31.. when you build for fedora you enable some repos - could you please notice those repos w/ samples in dox.

 
**Describe the solution you'd like**
Manual installation documentation for fedora should provide exact relations where should a user get old rpm since you check for pygpgme by rpm not by pip.

**Describe alternatives you've considered**
I want just install and view is it what I want or it is something that is not for me. 
there're too many alternatives & most are about 'use docker', 'use flatpak', 'use podman' - do not install too old stuff in your fresh distribution directly. 

**Additional context**
I'm not that happy with curl -s something | sudo bash , 1st I do curl -s something | bash -nv , things I see make me not very happy - pygpgme is python thing & having it in your system as rpm looks okay for people using same distribution for years & upgrading it, not reinstalling. I asked a friend of mine - he has that package since fedora28 & it's okay for him. My situation is diffrent - I use fedora since I have to. I like Qubes OS, but my hardware & job make use fedora currently & I follow guidelines for fresh fedora. Documentation should be more precise here - getting deep into becomes too hard.

Colleague recommended to look for asbru-cm .. He told that it is convenient . Documentation on installation is not that convenient as it should be.

**Comment by gfrenoy** [comment]
>  I use fedora (...)
> Documentation on installation is not that convenient as it should be.

See https://docs.asbru-cm.net/General/Installation/#fedora

If works exactly as documented on a fresh Fedora 31 install ; don't believe we can make it easier...

**Comment by grey-olli** [comment]
> > I use fedora (...)
> > Documentation on installation is not that convenient as it should be.
> 
> See https://docs.asbru-cm.net/General/Installation/#fedora
> 
> If works exactly as documented on a fresh Fedora 31 install ; don't believe we can make it easier...
Since I've checked what it should do & I know it won't harm - I've just made a run as root & copypaste strings the install script gives:

----------
....
Installing pygpgme to verify GPG signatures...
...
No match for argument: pygpgme
----------
Manual installation should notice where should I get this as rpm (or tell that it's okay to install w/ pip).
What you notice is automative installattion, not manual/advanced one.

BTW: I'd like to install loki branch since it is much newer. :)

**Comment by grey-olli** [comment]
Yes, it installs if you just do those two commands, but it always tells about pygpgme on fedora (I had this on Fedora 30 , I've this on Fedora 31): 'This means GPG verification is not possible for any RPM installed on your system.' 

 **asbru-cm should tell user that above problem does NOT affect asbru-cm itself.**

**Comment by gfrenoy** [comment]
> Manual installation should notice where should I get this as rpm

https://packagecloud.io/asbru-cm/asbru-cm/install#manual-rpm

>  it always tells about pygpgme on fedora

As stated in the above page : "You may need to install the EPEL repository for your system to install these packages."

> asbru-cm should tell user that above problem does NOT affect asbru-cm itself

Well, the packagecloud.io script is fairly verbose and explicit.  And their documentation is quite extensive ; would a link to their doc website would help ?  I can maybe add a short in the install section about this ?

**Comment by grey-olli** [comment]
> As stated in the above page : "You may need to install the EPEL repository for your system to install these packages."

If I understand correctly the problem is solved wrong way. EPEL repositories are okay for very old fedora . When I see the notice about EPEL repos I go reading a lot of EPEL documentation for nothing - the repo is installed anyway. This is python thing & should be checked via pip . Notice on EPEL repos  gives you a lot of questions & if you succeed enabling it you wasted a lot of time for a single package that is anyway packaged 'noarch' & is unsupported 3 months already.  python2 stuff is outdated & unsupported from january  2020. packagecloud.io script provides a warning that gives more confusion than help when using  supported fedora. Having warning about system  problem by detecting that noarch unsupported package is missing is bad design from my point of view. If asbru-cm require pygpgme for some actions when running asbru-cm - that is one point (1). If asbru-cm needs the pygpgme only at the moment of enabling the repository - that is another point(2).
I guess we have the (2) in reality.  I think that you should clarify in documentation that we have NO situation #(1) & this will save a lot of time for users who just want to install & try w/o digging deep into enabling repositories for just one outdated package.

**Comment by grey-olli** [comment]
sudo yum install pygpgme yum-utils . Why not pip install pygpgme? Do I really need yum-utils when dnf is a few years a preferred way to manage packages on fedora & there're dnf-utils for yum compatibility. If all this is about to getting one pygpgme - this is wasting my time.

In current Fedora 31 after installation from Loki branch I've this:
[root@dell15 openfortivpn]# rpm -qa |grep -i yum
yum-4.2.18-1.fc31.noarch
[root@dell15 openfortivpn]# 

No yum utils & this is fine. I've made pip install pygpgme, but I'm unsure it is really needed.

**Comment by grey-olli** [comment]
And more questions related to documentation: 

1) when I set a string as 'hidden' in expect I see in config or in backups of config ($home/.config/pac/bak/pac.yml.0) a string like '53616c74<omited>cd8493645' . 
Is this string is something encoded (what used to encode?) or is this is something encrypted(what used to encrypt)? 
2) If I set GUI password - does it change encoding / encryption behaviour for strings in .config/pac ?

Above two questions should be documented. I need to know how hard it would be for an attacker to access my passwords and sensitive expect strings (i.e. some systems require same password entered multiple times) if she steals asbru-cm config files.

I'm asking since I didn't find this on 1st page of google search. The asbru-cm seem to be nice. Thank you, developers & support team.

**Comment by grey-olli** [comment]
+1 question: 

Usually I try some program with a separate linux user, then I copy configuration to my primary one. Looks like the proper way is exporting connections. I see import/export for connection, but only export in configuration. What is proper way to import configuration?

**Comment by gfrenoy** [comment]
> +1 question:

Better to create a separate issue ; each issue is supposed to stay on topic.  Thanks.

**Comment by gfrenoy** [comment]
>  I've made pip install pygpgme, but I'm unsure it is really needed.

As far I understand how packagecloud.io manages this ; it's a way to check the package signature so, as such, it is not absolutely mandatory.  It works fine without it.

If you don't trust packagecloud.io, just go for the manual setup.

As a summary, I don't believe there is much we can do ; except saying that is something we may want to report to packagecloud.io.  But this is not seen as a priority for the core-team, would you do so and report your concerns them ?
