### ISSUE TITLE
Loki - EL7 - Make Get Command Line dialog copiable

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#558]
Hi Team ...

It would be useful if we could select and copy the commands shown in the dialog after press the "Make Get Command Line" button:

![image](https://user-images.githubusercontent.com/37672088/78505377-0a864880-776b-11ea-9828-5925f3a178f4.png)

Thanks.

**Comment by gfrenoy** [comment]
Oh yes, that one was also annoying me for a long time !

Found out the trick here:
https://stackoverflow.com/questions/3249053/copying-the-text-from-a-gtk-messagedialog

Just made the commit, should be ready in a few minutes.

Thanks for the heads-up :)

**Comment by popxunga** [comment]
Hi ...
Just tested and got an empty command line as it used to happen some time ago :-/
Thanks.

**Comment by gfrenoy** [comment]
Mmmm, strangely enough the executable mode of ```pac_conn``` has been changed in my last commit ?  That was not intentional for sure.  I set it back ; let me know if this helps.

**Comment by popxunga** [comment]
Hi ...
Just tested with latest loki build and yes ! It helped :+1: 
Now I see the command's and I can select and copy them.
Thanks a lot.
Closing
