### ISSUE TITLE
Error/warnings in starting any connection.

### ISSUE THREAD

**Issue by demirdag** [asbru-cm/asbru-cm#559]
**Describe the bug**
Some errors/warning on starting any connection. See:
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/perl5/5.30/vendor_perl/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/perl5/5.30/vendor_perl/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/vendor_perl/Gtk3.pm line 555.

**To Reproduce**
Start any connection

**Expected behavior**
Empty screen only filled bij output of connected server, no errors/warning that are not neccessary for a user.

**Screenshots**
CONNECTING WITH Home - archmini (Mon Apr  6 10:54:04 2020)

GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/perl5/5.30/vendor_perl/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/perl5/5.30/vendor_perl/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/vendor_perl/Gtk3.pm line 555.
Last login: Fri Apr  3 14:57:30 2020 from 217.114.101.70
----------------------------------------------------------------------------------
"Your mother was a hamster, and your father smelt of elderberrys!"
		-- Monty Python and the Holy Grail
----------------------------------------------------------------------------------
Be careful, Have fun! :)
[Prompt]

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Archie

**Additional context**
It's not a major issue but it just annoys me that these warnings are displayed on screen in stead of in a bug-report of some sort.

**Comment by gfrenoy** [comment]
Thanks for your feedback.  See #432 for the follow-up.
