### ISSUE TITLE
Add KeePassx key file support

### ISSUE THREAD

**Issue by Dodewaard** [asbru-cm/asbru-cm#56]
Hello,

I would love to use the KeePassx feature, but our database uses an additional key file to unlock the database. 
Currently there seems to be no support to use a key file in addition to the master password to unlock the database. Maybe this could be a nice feature to add in the future.

Thanks for keeping this tool alive!

**Comment by gfrenoy** [comment]
Ásbrú now supports KeePass key file ; testers are welcome on the [loki branch](https://github.com/asbru-cm/asbru-cm#testing-new-features).
