### ISSUE TITLE
Loki - EL7 - Can't select text from the begining of a line on ssh terminal

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#560]
Hi ...
This is with latest loki build EL7 with gnome3 (non-classic mode).
When the Connections section is collapsed, in any ssh terminal, I can use the mouse to select some text to copy, starting at the beginning of the line.
When the Connections section is not collapsed, I cannot start selecting from the beginning of the line, because when I put the mouse over the 1st char, the mouse pointer assumes I want to change the width of the Connections section.
As a workaround I have to select the text from the end to the beginning of the line (from right to left). 
Not sure if this happens while using other distro's, but is there anything that can be done to correct it ? I do not remember to have this difficulty before starting to test loki. 
Thanks.

**Comment by gfrenoy** [comment]
Noticed that as well (and found the same workaround ;-p).

Not sure when it has been introduced but fact is that most of the margins has been decreased.  I overlooked that change but I guess it's part of the major theme rework.

At this stage ; I'm wondering if this is a Gtk/theme related issue or if we are doing something wrong with the app...?  My guts say it's a Gtk issue but I don't have an evidence at this stage.

**Comment by gfrenoy** [comment]
This should be fixed in the latest loki build (at least it is for me ;p).

Do you confirm ?

**Comment by popxunga** [comment]
Yep ! ... Confirmed !
Thanks :-)
