### ISSUE TITLE
What is proper way to import configuration?

### ISSUE THREAD

**Issue by grey-olli** [asbru-cm/asbru-cm#562]
Documentation question:

Usually I try some program with a separate linux user, then I copy configuration to my primary one. Looks like the proper way is exporting connections. I see import/export for connection, but only export in configuration. What is proper way to import configuration?

**Comment by gfrenoy** [comment]
import/export is indeed an option but the easiest way is probably to copy the ```.config/pac``` over to the new profile...Make sure you remove the ```pac.nfreeze``` to that the .yml file is properly reloaded.

And before you start, maybe check in ```pac.yml``` if you need to search/replace some directories.

Said differently: all your settings (both connections and global preferences) are stored in ```pac.yml```.

**Comment by grey-olli** [comment]
thanks. That also worth documenting.. May be I'll add this later. Currently quite busy.

**Comment by TitussPulo** [comment]
> Documentation question:
> 
> Usually I try some program with a separate linux user, then I copy configuration to my primary one. Looks like the proper way is exporting connections. I see import/export for connection, but only export in configuration. What is proper way to import configuration?

For me, running Ubuntu Zorin Pro, I had to delete all the files in the root of asbru (not the folders) Just  Files = asbru.dumper, asbru.nfreeze, asbru.yml, asbru.yml.gui, asbru.yml.tree and asbru_stats.nfreeze.  Then reopening Asbru showed cleaned slate.  Then to test that the export config works, I Then copied the exported asbru.yml backup file into the root of your home/.config/asbru folder.  Then the next time you open Asbru, all your saved connections will be there and it recreates all the other files you deleted.
