### ISSUE TITLE
are sensitive configs values have protection?

### ISSUE THREAD

**Issue by grey-olli** [asbru-cm/asbru-cm#563]
Making this a separate questions related to documentation:    

when I set a string as 'hidden' in expect I see in config or in backups of config ($home/.config/pac/bak/pac.yml.0) a string like '53616c74-omited-848993645' .

 1. Is this string is something encoded (what used to encode?) or is this is something encrypted(what used to encrypt)?

  2. If I set GUI password - does it change encoding / encryption behaviour for strings in .config/pac ?

Above two questions should be exactly documented. Users should  know how hard it would be for an attacker to access their passwords and sensitive expect strings (i.e. some systems require same password entered multiple times) if an attacker steals asbru-cm config files.

**Comment by gfrenoy** [comment]
There is no real protection of your sensitive data provided by Ásbrú.  It is simply encoded but can be decoded easily.

We strongly discourage you from storing any sensitive data there.  And if you do, you should consider the .yml configuration (and the backup copies) with adequate care.

For sensitive data, we recommend to store them into KeePass and retrieve the information you need using the _new_ (6.2) KeePass integration module, see https://docs.asbru-cm.net/Manual/Preferences/KeePassXC/.

**Comment by grey-olli** [comment]
Thank you. Thing that worth a separate  notice in documentation.

**Comment by gfrenoy** [comment]
Sure thing.

Feel free to propose any improvement in https://github.com/asbru-cm/asbru-cm/tree/master/doc ; this project is yours !

**Comment by grey-olli** [comment]
Is it okay to just add a file with a branch (i.e. 'grey-olli-documentation-patch-1') via github.com web, or should I clone, add file to master & provide a pool-request from cloned repo to this one?

**Comment by gfrenoy** [comment]
In the meantime, I believe you found it out :)  But for the records, Hans made a quite extensive description here : https://github.com/asbru-cm/asbru-cm/issues/430#issuecomment-599817592
