### ISSUE TITLE
clarification of documentation for KeePassXC entry protection

### ISSUE THREAD

**Issue by grey-olli** [asbru-cm/asbru-cm#565]
https://docs.asbru-cm.net/Manual/Preferences/KeePassXC/ question:

As about KeePassXC integration:

"The cli access will not allow to have an "unlocked" state."

At the same time:

"This will create a delay of up to 5 seconds to unlock the database on every connection."

There's still one point not exactly cleared by documentation page - there're a few places to access KeePassXC DB: connection password , EXPECT lines w/ additional secrets. 

The question: since cli does not unlock DB (if I understood above correctly) - each EXPECT entry using KeePassXC will waste time unlocking DB or all entries for a connection are fetched at once when connection is used 1st time?

I.e. I've one KeePassXC entry for user, one for password and also two KeePassXC entries accessed for two EXPECT lines. Say the DB timeout is 5 seconds - there will be 20 seconds additional timeout then?

**Comment by hanspr** [comment]
The 5 seconds are only if you use version 4 and the highest encryption level (and you computer power as well)

All the values from a __single entry path__ are extracted at once (title, username, password, notes).

<username|path1> and <password|path1> (1 path, 1 connection).
<username|path1> and <password|path2> (2 paths, 2 connections)

So and exercise under the premise of 5 seconds would be:

* User name and password in the connection data same path : 5 seconds
* User name and password in connection data, and title from the same path : 5 seconds
* User from path1, password from path2, title from path3 : 15 seconds
* User and password from path1, 2 expects each using 2 different paths : 15 seconds

If this solves you question, please close the ticket to clear the board. Thanks

**Comment by grey-olli** [comment]
Yes, this solves the question. I think this should be added to documentation. Okay to close.
