### ISSUE TITLE
UI should notice that EXPECT timeouts set for a line are greater than global EXPECT timeout setting.

### ISSUE THREAD

**Issue by grey-olli** [asbru-cm/asbru-cm#566]
**Is your feature request related to a problem? Please describe.**
A user may set global timeout & forget it. Or forget that there's default global timeout.
If a user sets EXPECT timeout greater than global EXPECT timeout the setting is useless.
UI should tell user about this.

**Describe the solution you'd like**
a popup with notice on global timeout value appearing if custom timeout is larger than global one. 

**Describe alternatives you've considered**
As a workaround I set EXPECT and logon timeouts to maximum (99 seconds) and use custom timeouts for a connection. 

**Additional context**
Some remote servers are slow from time to time. I.e. at night almost no users - quick answer. Noon - lots of connections - slow answer (more than 40 seconds).

**Comment by hanspr** [comment]
Reading the code, the expect timeout (if set), will override the global timeout regardless of the global value.

If this is not the case, please document the settings that you are using so we can reproduce the error. Document with images all the relevant sections, to be completely sure that we cant set the tests exactly as your case.

**Comment by grey-olli** [comment]
Thank you. Seems global login timeout could be a reason (as far as I remember).  Next time I'll make a new connection I'll check this again. Now I close.
