### ISSUE TITLE
Announcement for testers : configuration file change

### ISSUE THREAD

**Issue by gfrenoy** [asbru-cm/asbru-cm#569]
Dear testers,

We are about to merge a change that will require your attention as it may have some impact on your working environment.

This change is related to #182 and will basically rename the default configuration file from ```~/.config/pac``` to ```~/.config/asbru``` to move forward in the rebranding of the forked application.

As of version 6.2.0, that is under testing in our ["loki" branch](https://github.com/asbru-cm/asbru-cm#testing-new-features), you will be required to migrate your existing configuration to the new file layout.

At application startup, a warning message will give you the opportunity to think twice about it:

![image](https://user-images.githubusercontent.com/981546/79063765-ec0cd980-7ca3-11ea-9969-196cca656cbc.png)

We believe we did everything to make this as smooth and transparent as possible.

But what you may want to understand:
- Nothing will be lost
- A safe copy of your existing configuration will be done to ```~/.config/pac.old```
- Older versions of Ásbrú will not be able to read that new configuration
- When starting an old version (6.0 or higher), you can use ```--config-dir ~/.config/pac.old``` to use your old configuration
- When starting an old version (6.1.x), Ásbrú will propose to downgrade your migrated configuration or recover your old configuration
- Upgrade and downgrade scripts are available in the ```utils``` directory

Please let us know if you have any concern with this change ; or simply thumb up this issue if you understand what will happen in the next days and are ready to test this to ensure a proper release of 6.2.0 :)

Thanks for your help and collaboration.

----------------------------
Update, here is our pan (and where we are with it ;p):

- [X] merge support for downgrade from migrated files into master branch
- [X] release 6.1.2 to included the latest fix and support for downgrade
- [X] announcement that a configuration change will happen in loki ; warn users to be careful the next time they upgrade
- [X] merge 515 into loki
- [X] merge latest changes from master
- [X] code freeze, tests and feedback in loki
- [X] merge loki into master --> 6.2 available in snapshots
- [X] at the same time, move loki to 6.3.0 --> for the next bunch of changes (to be decided...)
- [X] release 6.2.0~rc1 on master --> first release with migrated configuration file ; 6.1.3 become legacy with downgrade support

**Comment by grey-olli** [comment]
BTW: does github allow fast forwards to the original repository via their web interface? I've made a change in doc according to the changes here, but 1st I need to get my own cloned repo be fast forwarded to this one. I'm busy & if this works via few clicks it's faster than getting work via console.

**Comment by popxunga** [comment]
Hi ...
I was using loki already.
Downgraded to 6.1.2 (which at this stage is pretty unusable to me) and then upgraded to 6.2.0 latest loki. I do not see any backup config directories being created.
Is this the expected behavior or am I missing something ?
Thanks.

**Comment by Croydon** [comment]
Are you trying to brand yourself as `asbru` or `asbru-cm`? On a very quick look (i.e. you know much better what you are doing) this looks inconsistent to me

**Comment by gfrenoy** [comment]
> Downgraded to 6.1.2 (which at this stage is pretty unusable to me) and then upgraded to 6.2.0 latest loki. I do not see any backup config directories being created.
> Is this the expected behavior or am I missing something ?

Yes this is expected.
PR #515 has not been merged to loki yet.  It is planned for tomorrow or Wednesday.

To test it today; you'll need to clone the [PR branch](https://github.com/hanspr/asbru-cm/tree/fix182).

> Are you trying to brand yourself as asbru or asbru-cm?

First objective is to rebrand to "not pac" :)

>  On a very quick look (i.e. you know much better what you are doing) this looks inconsistent to me

The main entry point (incl. icon file) is using ```asbru-cm``` but all of the files are using the short version ```asbru``` (including the new configuration file names).  At this stage, this is considered "consistent enough".

**Comment by gfrenoy** [comment]
Dear, for your information, the "big changes" have been merged to loki.  The new version shall be ready in a few minutes.

So be prepared to see the warning message the next time you refresh your loki code base (and restart the application).

**Comment by wcasanova** [comment]
already updated, everything seems to be fine, I only had a problem when updating it gave me an error with pac2asbru.pl
, it was because I did not have executable permissions but after giving it the permissions I performed the migration, maybe it has to do with @figue , so that it grants the permissions when creating the package in the PKGBUILD

**Comment by popxunga** [comment]
Hi @gfrenoy 
Just tested it on EL7 and it doesn't work here:
1- I'm not getting any notification.
2- If the config is on the default place ~/.config/pac, I do see that a new ~/.config/asbru directory is created, but the configuration does not contain my sessions, what means that the migration process didn't work.
![image](https://user-images.githubusercontent.com/37672088/79351000-0b1f9b80-7f30-11ea-80e6-bb6c038ee32a.png)
3- When the configuration is located somewhere else and Asbru is started using the "--config-dir=" directive, I end with a pac directory, a pac_migration directory and no asbru directory, and again my Connections list is empty.
I do not see any error or messages in the terminal from where I launched Asbru.
Downgrading now to the previous loki version.
Thanks.

**Comment by figue** [comment]
> already updated, everything seems to be fine, I only had a problem when updating it gave me an error with pac2asbru.pl
> , it was because I did not have executable permissions but after giving it the permissions I performed the migration, maybe it has to do with @figue , so that it grants the permissions when creating the package in the PKGBUILD

Fixed: https://aur.archlinux.org/cgit/aur.git/commit/?h=asbru-cm-loki-git&id=f4d4b842c9f81fe1c70bbec367a950570e10c8a3

My migration works fine. Good job!

**Comment by popxunga** [comment]
In addition, I do see this warning when building from source rpm:

warning: Ignoring invalid regex ^%{_scl_prefix}/.*$|%{_root_sysconfdir}/rpm/macros.devtoolset-9-config

But this doesn't look loki build problem as I could see the same warning while building 6.0.4 from source.

**Comment by gfrenoy** [comment]
@popxunga 
> I'm not getting any notification popup window.

Mmm, I see : script ```pac2asbru.pl``` is not there (not packaged properly in the rpm):

https://github.com/asbru-cm/asbru-cm/blob/ba6fd0154da84ab1e60e591a558efe221b5f6d8e/asbru-cm#L213

Let me see what we can do about this.

**Comment by gfrenoy** [comment]
@popxunga The release that is now in loki should work better with EL7 (and other RPM-based distrbib) ; will you give it another try ?  Thanks.

**Comment by popxunga** [comment]
@gfrenoy 

Just tested it. 

In fact I tested 3 different scenarios and the good news are:
- I always got the popup warning window;
- The migration was successful in the 3 cases.

However the results were not quite the same in terms of the backup directories and/or the final directories where the new configurations gets stored.

**Scenario # 1- Config in the default location (~/.config/pac) and Asbru started normally **

[~]$ INFO: Ásbrú Connection Manager 6.2.0 (asbru-cm) started with PID 13719
INFO: Migration of default directory
INFO: Executing migration from PAC to Ásbrú
INFO: /home/xxxxxxxx/.config/pac , /home/xxxxxxxx/.config/asbru
INFO: RealBin = /usr/share/asbru-cm/utils
INFO: Migration messages:
  - Show confirmation dialog
  - Create /home/xxxxxxxx/.config/asbru
  - move pac.yml -> asbru.yml
  - move pac_notray.notified -> asbru_notray.notified
  - move pac.pcc -> asbru.pcc
  - move pac.yml.gui -> asbru.yml.gui
  - move pac.yml.tree -> asbru.yml.tree
  - move pac.dumper -> asbru.dumper
  - Move backups
  - Rename screenshots
  - Fix paths in asbru.yml
  - Remove nfreeze files to be recreated
INFO: Desktop environment detected : gnome-shell:gnome-withtray
INFO: Config directory is '/home/xxxxxxxx/.config/asbru'
INFO: Used config file '/home/xxxxxxxx/.config/asbru/asbru.yml'
INFO: Virtual terminal emulator (VTE) version is 0.52
       - has_bright = 1
       - major_version = 0
       - minor_version = 52
       - vte_feed_binary = 1
       - vte_feed_child = 1
INFO: Theme directory is '/usr/share/asbru-cm/res/themes/asbru-dark'
INFO: Using Gnome tray icon
DEBUG: Starting window position = (0, 0} ; window size (1790, 983)
DEBUG: Saving window position = (0, 0) ; window size (1790, 983)

This scenario seems to work correctly. 
The old pac configuration directory is renamed to pac.old
And the new migrated configuration is stored in ~/.config/asbru

**Scenario # 2- Config in /some/filesystem/Config/pac and Asbru started with --config-dir directive**

[~]$ INFO: Ásbrú Connection Manager 6.2.0 (asbru-cm) started with PID 14812
INFO: Migration of alternate directory
INFO: Executing migration from PAC to Ásbrú
INFO: /some/filesystem/Config/pac.migration , /some/filesystem/Config/pac
INFO: RealBin = /usr/share/asbru-cm/utils
INFO: Migration messages:
  - Show confirmation dialog
  - Create /some/filesystem/Config/pac
  - move pac.yml -> asbru.yml
  - move pac_notray.notified -> asbru_notray.notified
  - move pac.pcc -> asbru.pcc
  - move pac.yml.gui -> asbru.yml.gui
  - move pac.yml.tree -> asbru.yml.tree
  - move pac.dumper -> asbru.dumper
  - Move backups
  - Rename screenshots
  - Fix paths in asbru.yml
  - Remove nfreeze files to be recreated
INFO: Desktop environment detected : gnome-shell:gnome-withtray
INFO: Config directory is '/some/filesystem/Config/pac'
INFO: Used config file '/some/filesystem/Config/pac/asbru.yml'
INFO: Virtual terminal emulator (VTE) version is 0.52
       - has_bright = 1
       - major_version = 0
       - minor_version = 52
       - vte_feed_binary = 1
       - vte_feed_child = 1
INFO: Theme directory is '/usr/share/asbru-cm/res/themes/asbru-dark'
INFO: Using Gnome tray icon
DEBUG: Starting window position = (0, 0} ; window size (1790, 983)
DEBUG: Saving window position = (0, 0) ; window size (1790, 983)

In this case, the original config directory gets renamed to /some/filesystem/Config/pac.migration.old.
And the new migrated configuration is stored in /some/filesystem/Config/pac.

**Scenario # 3- Config in /some/filesystem/Config/pac with a symlink on ~/config/pac pointing to the config location, and Asbru started normally **

[~]$ INFO: Ásbrú Connection Manager 6.2.0 (asbru-cm) started with PID 15848
INFO: Migration of default directory
INFO: Executing migration from PAC to Ásbrú
INFO: /home/xxxxxxxx/.config/pac , /home/xxxxxxxx/.config/asbru
INFO: RealBin = /usr/share/asbru-cm/utils
INFO: Migration messages:
  - Show confirmation dialog
  - Create /home/xxxxxxxx/.config/asbru
  - move pac.yml -> asbru.yml
  - move pac_notray.notified -> asbru_notray.notified
  - move pac.pcc -> asbru.pcc
  - move pac.yml.gui -> asbru.yml.gui
  - move pac.yml.tree -> asbru.yml.tree
  - move pac.dumper -> asbru.dumper
  - Move backups
  - Rename screenshots
  - Fix paths in asbru.yml
  - Remove nfreeze files to be recreated
INFO: Desktop environment detected : gnome-shell:gnome-withtray
INFO: Config directory is '/home/xxxxxxxx/.config/asbru'
INFO: Used config file '/home/xxxxxxxx/.config/asbru/asbru.yml'
INFO: Virtual terminal emulator (VTE) version is 0.52
       - has_bright = 1
       - major_version = 0
       - minor_version = 52
       - vte_feed_binary = 1
       - vte_feed_child = 1
INFO: Theme directory is '/usr/share/asbru-cm/res/themes/asbru-dark'
INFO: Using Gnome tray icon
DEBUG: Starting window position = (0, 0} ; window size (1790, 983)
DEBUG: Saving window position = (0, 0) ; window size (1790, 983)

The old pac configuration directory (a symlink) on ~/config was gone.
The old config gets backed up in ~/.config/pac.old
A new symlink named asbru is created in ~/.config pointing to the same place where the original (now migrated) configuration was (/some/filesystem/Config/pac).

As I said, the 3 migrations worked fine and this is the most important point, but what happens at the filesystem level doesn't look consistent. 

Thanks a lot for your support.

**Comment by gfrenoy** [comment]
Thanks for the additional tests :)

So what the migration does is:

- Make a copy of the current configuration directory
- Rename "in place" the current configuration directory

So 1 & 3 looks consistent (it renamed the symlink).  About 3, not sure why we are adding ".migration" at the end of the current directory; @hanspr, any comment ?

**Comment by popxunga** [comment]
Hi @gfrenoy 

Just noticed these messages a couple of minutes ago:

[~]$ WARN: Unable to write into the session logs folder [/home/xxxxxxxx/.config/pac/session_logs], session logs will not be recorded.
WARN: Check your terminal settings to fix the issue.
WARN: Unable to write into the session logs folder [/home/xxxxxxxx/.config/pac/session_logs], session logs will not be recorded.
WARN: Check your terminal settings to fix the issue.
WARN: Unable to write into the session logs folder [/home/xxxxxxxx/.config/pac/session_logs], session logs will not be recorded.
WARN: Check your terminal settings to fix the issue.

My configuration is being loaded from /some/filesystem/Config/pac and Asbru is started with --config-dir directive.

Why is Asbru is trying to save the session logs under /home/xxxxxxxx/.config/pac/session_logs ?

Thanks.

**Comment by popxunga** [comment]
> Thanks for the additional tests :)
> 
> So what the migration does is:
> 
>     * Make a copy of the current configuration directory
> 
>     * Rename "in place" the current configuration directory
> 
> 
> So 1 & 3 looks consistent (it renamed the symlink). About 3, not sure why we are adding ".migration" at the end of the current directory; @hanspr, any comment ?

It's about Scenario #  2 and not # 3 ...
Scenario 3 is not important since I was told about the --config-dir directive. Just tested by curiosity.

**Comment by gfrenoy** [comment]
> It's about Scenario # 2 and not # 3 ...

Yes sorry, it was a typo.  Fixed now.

**Comment by gfrenoy** [comment]
> Why is Asbru trying to save the session logs under /home/xxxxxxxx/.config/pac/session_logs ?

As suggested, can you check in your settings and replace the path there ?

See also #561

**Comment by popxunga** [comment]
I could get rid of the error messages in terminal, either by adjusting the log session folder save in location in the terminal preferences GUI, or by closing Asbru, remove asbru.nfreeze and adjust the path's directly in asbru.yml. But the sessions log files are not being saved anywhere.

The Autosave Session logs is turned off in Asbru global preferences (like it was before ... didn't change it). I only want to save logs for some sessions and not for all them. So it makes sense to turn session logging on at the connection level and not globally.

**Comment by popxunga** [comment]
Hi @gfrenoy & @hanspr 
After the fix above the session log feature is working again.
Thanks !

**Comment by popxunga** [comment]
Hi @gfrenoy &  @hanspr ...
The autosave session logs issue is not correctly resolved yet.
It saved the log for one of the sessions I had, but it not saving it to other session I tried a couple of minutes ago. Need to figure out what's going on.

**Comment by hanspr** [comment]
You will have to check all your paths, the migration was designed for the main pac to asbru configuration.

But if you used alternative paths and links as I read onece, all your paths will be wrong. Edit to your asbru.yml file and verify. If they are wrong, search and replace the paths to fixed all at once.

**Comment by popxunga** [comment]
Is this the procedure ? 

1. Close Asbru, 
2. remove the .nfreeze file, 
3. Edit the yml file 

?

**Comment by hanspr** [comment]
Yes that would be the correct way to do it.

**Comment by hanspr** [comment]
Look for the "session logs folder" entries

![imagen](https://user-images.githubusercontent.com/1572396/79588007-f4e11f00-8098-11ea-9b12-ea5f864d45c7.png)

They will have some wrong path there.

**Comment by popxunga** [comment]
Yep @hanspr ... it's working fine now.

By editing the pac.yml file I was able to correct all entries at once with a simple search & replace.
I did it before the final patch was merged, but then I rolled back my config and forgot to do it again.

Suggestion: 
Consider saving these path's in the configuration as relative path's. 
It would help when the user wants to move Asbru configuration somewhere without the need to manually editing the configuration.

Thanks !

**Comment by hanspr** [comment]
>  Consider saving these path's in the configuration as relative path's.

Thought of it, but because you can set the destination to any place  (Download Folder, Home, /root/tmp, /home/otheruser/, etc) it would create issues in some other way.

I guess the only problem will arise with I migrations. Lets hope we do not have that many.

**Comment by popxunga** [comment]
Another option would be clearly state that moving configuration around may cause issues if not done by using the import/export configuration feature. In this scenario, we would assume the ~/.config/asbru as default, but letting the user to specify/change the base configuration directory during the import config operation. A simple test to check if the directory being selected is writable by the user is simple to implement I guess.

**Comment by gfrenoy** [comment]
Dear,

We have moved one step forward in our 6.2 release process.

1) The "loki" branch has now been merge to the master branch 
2) Master branch is now version 6.2
3) Loki is now moving to version 6.3

6.2 is consequently now available in the "snapshots" repository.  Testers are welcome before we do release 6.2.0~rc1.

Thanks to all who contributed to this new achievement for this project :)

**Comment by popxunga** [comment]
Hi ! Good news !
Just installed it and briefly tested it :-) 
Everything looking fine so far :+1: 
Thanks !

**Comment by hanspr** [comment]
If 6.2 has been released then this should be closed

**Comment by gfrenoy** [comment]
Tadaaa!  Yes, version 6.2 [is ready and available](https://github.com/asbru-cm/asbru-cm/releases/tag/6.2.0) in the main repository :)

Thanks again for all your support and valuable comments.
