### ISSUE TITLE
Better hightlight of selected connection tab

### ISSUE THREAD

**Issue by mvrk69** [asbru-cm/asbru-cm#570]
Hi,

Would be good to have an option to choose a colour for the selected connection tab or at least make it more darker then the rest of the tabs.

**Comment by gfrenoy** [comment]
Isn't that something you can change in your Gtk theme ?

**Comment by mvrk69** [comment]
Yes, i guess you are right.

I had changed to Arc them because on adwaita tabs are not rounded, but i on the other hand on adwaita its more clear which tab is selected.

I guess i will have to get some digging on gtk3 themes and maybe make my own.

**Comment by gfrenoy** [comment]
This might help you:
https://www.preining.info/blog/2020/03/de-uglify-gtk3-tabs-of-terminals/
