### ISSUE TITLE
Add support for Ubuntu 20.04LTS focal

### ISSUE THREAD

**Issue by aranwe** [asbru-cm/asbru-cm#571]
Hello,

I would like to ask for support of Ubuntu 20.04LTS focal in the travis CI and packagecloud deb repositories as the 20.04LTS will be with us for quite some time :) 

Thank you very much!
Cheers,
O.

**Comment by gfrenoy** [comment]
Fyi, a build for Ubuntu 20.04 Focal is now available in the snapshots and in the loki branch.

**Comment by zendre4** [comment]
For  other people who don't know where to find the snapshots :

https://packagecloud.io/asbru-cm/snapshots/

**Comment by jdrch** [comment]
[Loki branch works just fine for me on 20.04](https://github.com/asbru-cm/asbru-cm/issues/585#issuecomment-619109346).

**Comment by KlaasT** [comment]
Ubuntu 20.04 support has been added for snapshots and loki. We will have stable packages on the next release. Closed #571

**Comment by franckcharpentier** [comment]
Thank you very much.

**Comment by aranwe** [comment]
Thank you! :) I can confirm it's working.

**Comment by franckcharpentier** [comment]
It's working but a warning message is displayed when logging in SSH.

CONNECTING WITH xxx (Tue Apr 28 15:01:53 2020)

GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-91-generic x86_64)

**Comment by gfrenoy** [comment]
Franck, yes that's an known issue ; see #432 if you want to follow this up or help.

**Comment by master-vineet** [comment]
It's not working with windows system (6.1.4) but the previous PAC is working fine with the same configuration.

CONNECTING WITH SPECTRA-WIN - SPECTRA-26 (Wed Apr 29 17:10:25 2020)

GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.
[__PAC__SUDO__PROMPT__]LOG **: Name com.canonical.AppMenu.Registrar does not exist on the session bus

Sorry, try again.
[__PAC__SUDO__PROMPT__]
DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Wed Apr 29 17:10:41 2020)

**Comment by gfrenoy** [comment]
@master-vineet the "setenv/putenv" messages do not help but I've the feeling it's not related to this issue.

It looks more like a "prompt" issue ; did you check your advanced options (see [here](https://docs.asbru-cm.net/Manual/Preferences/MOAdvanced/)) ?  And compared them with what you had before ?

If the problems should persist, please create a separate issue (this one is closed) with the exact version of the software that was working and more details about your configuration and the target destination.
