### ISSUE TITLE
Keepass - 2 open databases - only shows entries from 2nd database

### ISSUE THREAD

**Issue by mvrk69** [asbru-cm/asbru-cm#573]
Hi,

I have keepass with 2 databases open, but asbru only shows me entries of one of the databases.

**Comment by gfrenoy** [comment]
>  but asbru only shows me entries of one of the databases.

This works as designed, I do fear : Ásbrú will only use the database file that is specified in your preferences:
![image](https://user-images.githubusercontent.com/981546/79363483-3e6e2480-7f48-11ea-8c9f-dd5fe8341ea3.png)

Said differently : it will not use the GUI that is currently open.

**Comment by mvrk69** [comment]
Ha yes, i see, no way to use 2 DBs at the same time.

Maybe developers can consider an improvement feature for the future?

**Comment by gfrenoy** [comment]
Sorry but this feature is currently not considered.
