### ISSUE TITLE
Alternative keys to insert into the terminal.

### ISSUE THREAD

**Issue by gasRU76** [asbru-cm/asbru-cm#575]
Hi,

Thanks for the work.
l have a little bit question. Can l change paste key: ctrl + shift + v -> alt + v? Maybe, do you have patch or hack for it?

Kind regards,
Alexander, from Russia.

**Comment by gfrenoy** [comment]
Custom keybinding is not possible today and already considered in #556.

To hack it yourself (but it will be lost after the next upgrade), you'll have to look into the PACTerminal.pm file (search for <Ctrl><Shift>).
