### ISSUE TITLE
Connection UI enhancements

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#579]
I'm trying to use as many features as possible in Asbru as I find it makes my life easier, but there are a few parts that I don't understand what are they for and I think it would be great if it can be added a description on each part about them. 

I'm talking about: 
Edit Connection >> Pre Exec
Edit Connection >> Post Exec
Edit Connection >> Expect
Edit Connection >> Remote Macros
Edit Connection >> Local Macros
Edit Connection >> User variables

They should have a small description in the current window telling what is this for, and  the little question mark button that redirects to the official documentation, pointing to that specific part, and that document should have a couple of examples/tips about how to use it.

This will make Asbru more user friendly and easy to use. 

Thanks

**Comment by hanspr** [comment]
https://docs.asbru-cm.net/Manual/Connections/SSH/

https://docs.asbru-cm.net/Manual/Preferences/GlobalVariables/

https://docs.asbru-cm.net/Manual/Preferences/LocalCommands/

https://docs.asbru-cm.net/Manual/Preferences/RemoteCommands/

**Comment by ferent** [comment]
Great, so what about adding the question mark buttons in the interface to link to these docs?

**Comment by hanspr** [comment]
@ferent 

>what about adding the question mark buttons in the interface to link to these docs?

This has been added to version 6.2 that has been released.

This issue should be closed.
