### ISSUE TITLE
Connections Tree Panel reopenes when you switch tabs

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#58]
If you close the connections tree panel by clicking the button below a terminal, it automatically re-appears whenever you switch to another tab.

I would expect it to remain closed until I manually reopen it.

**Comment by gfrenoy** [comment]
Confirmed.  I would also expect that it remains closed.  That's probably something we could easily fix ; thanks for your feedback !

**Comment by gfrenoy** [comment]
I will now commit a fix for this.  I also took this opportunity to clean up the concepts (a bit) and make them more straightforward to understand.

So we have now 2 options:

1) Hide connections list (on terminal open)
2) Auto show/hide when entering/leaving connections list

The first one will hide only hide the connections list when a new terminal is open (and only at that time).

The second will automatically show the connections list when you are hovering on it and hide it when you are leaving.

Hope this helps.
