### ISSUE TITLE
Ubuntu Focal 20.04 LTS packaging

### ISSUE THREAD

**Issue by franckcharpentier** [asbru-cm/asbru-cm#587]
Could you build a package for the new Ubuntu Focal 20.04 LTS ?

**Comment by KlaasT** [comment]
We've got snapshots for 20.04. We will release official Ubuntu 20.04 packages soon.

**Comment by gfrenoy** [comment]
See also #571

**Comment by KlaasT** [comment]
Ubuntu Focal 20.04 support will be released with 6.1.3. Closed #587
