### ISSUE TITLE
Add a "Close disconnected tabs" option to tab-bar-rightclick-menu

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#59]
Next to "Close terminal" and "Close ALL terminals" it would be nice to have a "Close disconnected terminals" option.
I don't know though how to deal with RDP connections and stuff as I don't use this feature.

**Comment by gfrenoy** [comment]
Very interesting idea :)  RDP connections also have a "disconnected" status ; in that case, the tab title would become red and that new options would delete all "red" tabs ; that sounds nice and achievable.

**Comment by gfrenoy** [comment]
The next commit implements this feature that will be available for the next release.  Short key is CTRL+SHIFT+N.
