### ISSUE TITLE
warning messages before getting connected setenv() putenv()

### ISSUE THREAD

**Issue by SlavaSafronov** [asbru-cm/asbru-cm#593]
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.

Running asbru on ubuntu 20.04, messages started appearing just after ubuntu upgrade from 18.04 to 20.04

**Comment by gfrenoy** [comment]
See #432
