### ISSUE TITLE
Support for Fedora 32

### ISSUE THREAD

**Issue by TimmiORG** [asbru-cm/asbru-cm#594]
Hi,
would be great if you could add support for Fedora 32.
Best regards

**Comment by gfrenoy** [comment]
Request posted ; we're waiting for packagecloud.io to support fedora/32.

**Comment by gfrenoy** [comment]
A loki package for Fedora 32 is now available...

Testers welcome :)

**Comment by TimmiORG** [comment]
I was able to install the repo now.

**Comment by tfabik** [comment]
Hello, how did you manage to install Asbru on F32? I was able to install the asbru-cm repo too, but when I try to install the app itself using "dnf install asbru-cm", I always get the following message:
```
No match for argument: asbru-cm
Error: Unable to find a match: asbru-cm
```

**Comment by TimmiORG** [comment]
> Hello, how did you manage to install Asbru on F32? I was able to install the asbru-cm repo too, but when I try to install the app itself using "dnf install asbru-cm", I always get the following message:
> 
> ```
> No match for argument: asbru-cm
> Error: Unable to find a match: asbru-cm
> ```

I just tested it a fresh system. Repo is available but packet is not build I guess.
The repo is empty.

**Comment by gfrenoy** [comment]
It is only available in the *loki* repository today ; see https://docs.asbru-cm.net/General/Installation/#fedora

**Comment by gfrenoy** [comment]
Build for Fedora is now also available in the "snapshots" repository and will soon be in the main repository as we release 6.2.0~rc1.

Let me close this for now ; feel free to create a new issue if it should not work for F32 after the release.
