### ISSUE TITLE
Bring back multi instance/ read only?

### ISSUE THREAD

**Issue by dpcinc** [asbru-cm/asbru-cm#595]
What happened to being able to open multiple instances?

Is it not possible anymore?

asbru-cm --read-only
INFO: Ásbrú Connection Manager 6.1.3 (asbru-cm) started with PID 3979
INFO: Desktop environment detected : cinnamon
INFO: VTE version is 0.52
INFO: Using config directory '/home/****/.config/pac'
INFO: Used config file '/home/****/.config/pac/pac.nfreeze'
INFO: Ásbrú is already running.
INFO: No more instances allowed!
WARN: Ásbrú aborted.

I like to keep my clusters in their own instance for organization of the connections basically.

**Comment by gfrenoy** [comment]
It should still work if the corresponding setting is set in Preferences > Main Options > Advanced,

![image](https://user-images.githubusercontent.com/981546/80891897-4a3b4400-8cc7-11ea-9f8c-9681623ce486.png)

Can you double check this in your preferences ?

**Comment by dpcinc** [comment]
![image](https://user-images.githubusercontent.com/7432668/80892640-8bf4cc00-8c80-11ea-95c0-0c7e7ee70a9f.png)
That option is not shown for me?

**Comment by gfrenoy** [comment]
My bad, in 6.1.x, this setting is to be found in Main Options > Look and Feel

![image](https://user-images.githubusercontent.com/981546/80892842-807bc200-8ccd-11ea-9603-8d23a9bcba68.png)

(not sure why it's in "Advanced" for loki ; I'll have a look)

**Comment by dpcinc** [comment]
Thanks I totally missed that!
