### ISSUE TITLE
Unable to install asbru-cm on Ubuntu 20.04 due to uninstallable Perl dependencies

### ISSUE THREAD

**Issue by SegiH** [asbru-cm/asbru-cm#596]
**Describe the bug**
I followed the instructions to install asbru-cm on an installation of Ubuntu upgraded from 19.10 to 20.04.When I run 

`sudo apt-get install asbru-cm`

I get a large number of errors about missing, uninstallable Perl dependencies.

**To Reproduce**
Steps to reproduce the behavior: Per [official instructions](https://github.com/asbru-cm/asbru-cm)

1. Run `sudo curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash`. This command runs fine without any errors.
2. `sudo apt update`. All repos are loaded without any errors
3. `sudo apt install asbru-cm`.
4. Receive errors about uninstallable Perl dependencies

**Expected behavior**
I expect apt to install all dependencies since `apt-cache policy asbru-cm` shows version 6.1.3 which the Asbru-cm change logs say that Ubuntu Focal (20.04) is now supported.

**Screenshots**
Screenshot below

**Environment (please complete the following information):**
 - Ubuntu 20.04 Focal
 - Ásbrú Version 6.1.3 (Trying to install this version as found by running `apt-cache policy asbru-cm`

**Additional context**
Another laptop running Ubuntu 19.10 works fine so something with dependencies changed between 19.04 and 20.04.
![asbrucm](https://user-images.githubusercontent.com/3309961/80943521-42999f00-8d9c-11ea-84d2-a6f80f572fcf.png)

**Comment by gfrenoy** [comment]
Try to activate the "multiverse" repository, see https://docs.asbru-cm.net/General/Installation/#ubuntu

**Comment by SegiH** [comment]
Thank you! That did the trick. I'm not sure It would be really helpful to add this to the docs

**Comment by gfrenoy** [comment]
Well, it is in the docs (that's the link I sent you).

Now, do we want to show this on the front page ?  Not sure since the goal is maybe to understand why we need this and to get rid of this dependency...

**Comment by SegiH** [comment]
gfrenoy,

I did mean that it should be on the main page. Maybe it should say "If you run into errors that refer to uninstallable Perl dependencies, add the multiverse repo according to [this link](https://docs.asbru-cm.net/General/Installation/#ubuntu) and try again"

**Comment by gfrenoy** [comment]
Yes a small note on the front page would certainly help.  Let me close this one and add a note to #351 ; we already have an issue about the need to review the home page...

If anyone is fluent with Jekyll or want to learn, the website code is available here --> https://github.com/asbru-cm/asbru-cm.github.io ; contributions are welcome :)
