### ISSUE TITLE
RDP Session broken

### ISSUE THREAD

**Issue by 4Syno** [asbru-cm/asbru-cm#597]
Hello;

I went from ubuntu 18.04 to 20.04; Since now I can‘t connect windows 10 clients (rdp).
Xrdp linux clients still working; Ásbrú version before and after [6.1.3] 
The GUI shows nothing; start connecting…; configured are rdesktop sessions.

1. Add Connection
2. Method: rdesktop
3. Host: Windows 10
4. save and connect
5. See error with --verbose Mode

**Expected behavior**
RDP Session to my jump hosts ;)

**Environment (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Ásbrú Version [ 6.1.3]

**Additional context**
```
4syno@Desk:~$ asbru-cm --verbose
INFO: Ásbrú Connection Manager 6.1.3 (asbru-cm) started with PID 506858
INFO: Desktop environment detected : other
INFO: VTE version is 0.60
INFO: Using config directory '/home/4syno/.config/pac'
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
LOG **: Name com.canonical.AppMenu.Registrar does not exist on the session bus
INFO: Used config file '/home/4syno/.config/pac/pac.nfreeze'
INFO: Using Gnome tray icon
*** unhandled exception in callback:
***   Can't call method "hide" on an undefined value at /opt/asbru/lib/PACTerminal.pm line 4206.
***  ignoring at /opt/asbru/lib/PACTerminal.pm line 588.
*** unhandled exception in callback:
```

Thank you very much.
Syno

**Comment by gfrenoy** [comment]
Can you let me know what you see when you click on the "Show Message" button ?
![image](https://user-images.githubusercontent.com/981546/81007272-37547b00-8e51-11ea-99ba-6d9d361b27b8.png)

I tested this on a fresh Ubuntu 20.04 machine and, the first time you connect to the remote target, it shows you a message about accepting the certificate.

After I went through this (had to do it outside Ásbrú), it worked fine...

**Comment by 4Syno** [comment]
Haven’t seen that message button all the time :D Good to know!
That's how my screen looks to the reported message above: 
![Auswahl_742](https://user-images.githubusercontent.com/31743671/81010173-5baa5a80-8e45-11ea-830c-ff9473ac2f12.png)
I installed a new windows10 test client; From the command line rdesktop is working fine, as you describe it. But not inside Ásbrú; the connection shows me still the same behavior. 
"Do you trust this certificate"... Looks like that the outside generated trust is in my case not valid inside Ásbrú :(

**Comment by gfrenoy** [comment]
Apparently you are using a KeePass database file to provide the password and this does not work for some reason.

So you are asked to enter a password from the command prompt.

I do fear KeePass is not working well in 6.1.x ; we have changed this deeply in 6.2.x and it should work better...

Can you try without using KeePass to validate this hypothesis ?

**Comment by 4Syno** [comment]
Yes definitely "better" without, and for the windows 10 clients I messed up with the dns suffix.
That was not equal to Ásbrú host connection. Every rdp client in the known_certs list from rdesktop needs to be written exactly the same way inside Ásbrú (case sensitive; fqdn). It works for now! Glad to hear that you are already working on a new version :) 
Many thanks for your support!
