### ISSUE TITLE
help by script 

### ISSUE THREAD

**Issue by dl6dbh** [asbru-cm/asbru-cm#598]
Hallo 
i am looking for an example script. maybe anybody can help me .

receive in terminal      "login: "
send       the username 

receive in terminal      "password: "
send the password 

Best Regards

**Comment by hanspr** [comment]
From your question, as it is, looks like you are trying to jump from one server to another.

If your servers allow to use the -J option, read, how to set up a jump server

https://docs.asbru-cm.net/Manual/Connections/SSH/

If it does not work for you , then do it with expect

https://docs.asbru-cm.net/Managing/Expect/

Basically set up 2 (or 3) expect lines:

1) to expect your prompt, and send the ssh command to connect to the second server

2) expect the "username:" prompt and send the user

3) expect the "password:" prompt and send the password


If you actually want to code a perl script, the only examples we have are the ones included in the "Script Manager"

![imagen](https://user-images.githubusercontent.com/1572396/81114727-36225d00-8ee8-11ea-83bf-244dd9de395d.png)

And I do not know if anyone has ever wrote a script, I know I haven't. So this is as far as I can go in that.
