### ISSUE TITLE
Starting an entry from the connections tree maximizes the progam window

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#6]
This is always reproducible with asbru on XUbuntu 17.10 xfce4 and happens with original pac on Ubuntu 17.04 Gnome3 too.

**Comment by gfrenoy** [comment]
Yes, I know that one.  The "maximized" state was not correctly saved when you close the application.

I just fixed it less than an hour ago on aabbe12429c53133f807cc0ee693a9656b4b6e57 so it will be available with RC3 I guess :)

**Comment by gfrenoy** [comment]
Fixed in RC3
