### ISSUE TITLE
An option to include time info in the session logs

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#603]
Hi Asbru Team ..

It would be useful to have an option to include time information while writing the session logs.
Something like this:

YYYY-MM-DD HH:MM:SS  log line 1
YYYY-MM-DD HH:MM:SS  log line 2
...
YYYY-MM-DD HH:MM:SS  log line n

Thanks in advance.

**Comment by hanspr** [comment]
What do you need this for?

**Comment by popxunga** [comment]
The inclusion of time information is always useful in any type of log file.
In my case, for example:
To determine the time I executed something when that time does not get recorded elsewhere;
To determine the amount of time needed to execute a set of actions.

**Comment by popxunga** [comment]
Hi @hanspr 

Briefly tested it and it looks like that the timestamp is being written in the log on each keystroke, which I think its an unexpected behavior. Here is the log produced in my test:

`2020-05-15 16:40:10 : Last failed login: Fri May 15 10:40:02 CDT 2020 from xxx.xxx.xxx.xx on ssh:notty
                      Last login: Fri May 15 10:39:44 2020 from 10.3.220.202

2020-05-15 16:40:10 : root@test:~
[root@test ~]# 
2020-05-15 16:40:11 : l
2020-05-15 16:40:11 : s
2020-05-15 16:40:11 :  
2020-05-15 16:40:11 : -
2020-05-15 16:40:11 : a
2020-05-15 16:40:11 : l
2020-05-15 16:40:11 :  
2020-05-15 16:40:12 : 
2020-05-15 16:40:12 : total 88
                      dr-xr-x---.  7 root root  4096 Mai 13 12:49 .
                      dr-xr-xr-x. 24 root root  4096 Mai  5 14:02 ..
                      drwx------.  3 root root  4096 Abr 20 05:06 .ansible
                      -rw-------.  1 root root 18381 Mai 15 10:40 .bash_history
                      -rw-r--r--.  1 root root    18 Dez 28  2013 .bash_logout
                      -rw-r--r--.  1 root root   176 Dez 28  2013 .bash_profile
                      -rw-r--r--.  1 root root   176 Dez 28  2013 .bashrc
                      -rw-r--r--.  1 root root   100 Dez 28  2013 .cshrc
                      drwxr-xr-x.  3 root root  4096 Mai 13 12:28 xxx.tmp.15627
                      -rw-r--r--.  1 root root   473 Mai  5 13:57 fstab.bk
                      -rw-r--r--.  1 root root 12787 Abr 20 04:56 index.html
                      drwxr-xr-x.  2 root root  4096 Mai  3 12:34 isus
                      drwxr-----.  3 root root  4096 Abr 20 04:58 .pki
                      drwx------.  2 root root  4096 Mai  3 09:13 .ssh
                      -rw-r--r--.  1 root root   129 Dez 28  2013 .tcshrc
2020-05-15 16:40:12 : root@test:~
[root@test ~]# 
2020-05-15 16:40:14 : l
2020-05-15 16:40:14 : s
2020-05-15 16:40:14 :  
2020-05-15 16:40:15 : a
2020-05-15 16:40:15 : l
2020-05-15 16:40:15 :  
2020-05-15 16:40:15 : 
2020-05-15 16:40:15 : 
2020-05-15 16:40:16 : 
2020-05-15 16:40:16 : -
2020-05-15 16:40:16 : a
2020-05-15 16:40:16 : l
2020-05-15 16:40:16 :  
2020-05-15 16:40:16 : 
2020-05-15 16:40:16 : total 88
                      dr-xr-x---.  7 root root  4096 Mai 13 12:49 .
                      dr-xr-xr-x. 24 root root  4096 Mai  5 14:02 ..
                      drwx------.  3 root root  4096 Abr 20 05:06 .ansible
                      -rw-------.  1 root root 18381 Mai 15 10:40 .bash_history
                      -rw-r--r--.  1 root root    18 Dez 28  2013 .bash_logout
                      -rw-r--r--.  1 root root   176 Dez 28  2013 .bash_profile
                      -rw-r--r--.  1 root root   176 Dez 28  2013 .bashrc
                      -rw-r--r--.  1 root root   100 Dez 28  2013 .cshrc
                      drwxr-xr-x.  3 root root  4096 Mai 13 12:28 xxx.tmp.15627
                      -rw-r--r--.  1 root root   473 Mai  5 13:57 fstab.bk
                      -rw-r--r--.  1 root root 12787 Abr 20 04:56 index.html
                      drwxr-xr-x.  2 root root  4096 Mai  3 12:34 isus
                      drwxr-----.  3 root root  4096 Abr 20 04:58 .pki
                      drwx------.  2 root root  4096 Mai  3 09:13 .ssh
                      -rw-r--r--.  1 root root   129 Dez 28  2013 .tcshrc
                      root@test:~
[root@test ~]# 2020-05-15 16:40:17 : l
2020-05-15 16:40:17 : s
2020-05-15 16:40:17 :  
2020-05-15 16:40:18 : -
2020-05-15 16:40:18 : a
2020-05-15 16:40:18 : l
2020-05-15 16:40:18 :  
2020-05-15 16:40:18 : 
2020-05-15 16:40:18 : total 88
                      dr-xr-x---.  7 root root  4096 Mai 13 12:49 .
                      dr-xr-xr-x. 24 root root  4096 Mai  5 14:02 ..
                      drwx------.  3 root root  4096 Abr 20 05:06 .ansible
                      -rw-------.  1 root root 18381 Mai 15 10:40 .bash_history
                      -rw-r--r--.  1 root root    18 Dez 28  2013 .bash_logout
                      -rw-r--r--.  1 root root   176 Dez 28  2013 .bash_profile
                      -rw-r--r--.  1 root root   176 Dez 28  2013 .bashrc
                      -rw-r--r--.  1 root root   100 Dez 28  2013 .cshrc
                      drwxr-xr-x.  3 root root  4096 Mai 13 12:28 xxx.tmp.15627
                      -rw-r--r--.  1 root root   473 Mai  5 13:57 fstab.bk
                      -rw-r--r--.  1 root root 12787 Abr 20 04:56 index.html
                      drwxr-xr-x.  2 root root  4096 Mai  3 12:34 isus
                      drwxr-----.  3 root root  4096 Abr 20 04:58 .pki
                      drwx------.  2 root root  4096 Mai  3 09:13 .ssh
                      -rw-r--r--.  1 root root   129 Dez 28  2013 .tcshrc
                      root@test:~
[root@test ~]# 2020-05-15 16:41:21 : e
2020-05-15 16:41:21 : x
2020-05-15 16:41:21 : i
2020-05-15 16:41:22 : t
2020-05-15 16:41:22 : 
                      logout
2020-05-15 16:41:22 : Connection to xx.xxx.xx.xxx closed.
`

By activating the remove control char's option in configuration, I guess the final result may be very good.

Thanks for adding this functionality.

**Comment by hanspr** [comment]
Yes you would have to leave with that, the information arrives in chunks and with the echo, I can no do anything about it.

The procedure received the strings in chunks (cut at any place) and the manipulation has to be short and none intrusive to avoid communication problems or delays.

**Comment by popxunga** [comment]
No problem. I can leave with that. 
Thanks again.
