### ISSUE TITLE
Right click in a terminal should switch the focus to that terminal 

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#604]
Hi ...

To reproduce the issue:

1. Open a terminal to host A;
2. Write some command in that terminal (eg scp something from host B...);
3. Copy the password of host B from the B node defined in the connections section;
4. Right click terminal A, select Paste from the context menu + Press Enter;
5. At this point, the password should be pasted in the terminal A but is doesn't; instead a new terminal is opened for host B.

Shouldn't the terminal A receive focus when we right click it ?

This is with loki build on EL7.

Thanks !

**Comment by gfrenoy** [comment]
This should now be fixed on the loki branch (to be released in 6.3).

Let us know if it works for you (or not :stuck_out_tongue:).

**Comment by popxunga** [comment]
Hi @gfrenoy ...
Yes it works :-)
Closing this issue.
Thanks a lot !
