### ISSUE TITLE
Option to diable Close session dialog

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#606]
Along the working day session I have to open and close multiple remote sessions, and is a bit annoying that every time I want to close one opened session the "Are you sure you want to close XXX" dialog appears. 

Could you add an option in the settings to enable/disable this? 

Thanks

**Comment by demirdag** [comment]
Ok I just added a feature request without seeing your question. Deleting mine and getting behind yours

**Comment by hanspr** [comment]
Follow discussion on #592

I proposed the same there, and others want just to move the default option to OK, but @gfrenoy needs more feed back to make up his mind, so better go there and update your comments and put more momentum on that thread.

**Comment by ferent** [comment]
Oh didn't see this ticket. Thanks.

**Comment by hanspr** [comment]
You may consider this tip from that thread too.

>If you set the General Settings > Terminal Options > Close terminal on disconnect. You can avoid any confirmation. You would have to always exit properly from a session : type `exit` in ssh (sftp,mosh) sessions, log out on rdp sessions, and so on. Which is convenient; since, if you log out properly, you know you are not leaving anything incomplete by mistake.

**Comment by gfrenoy** [comment]
Yes, please vote on #592 !

**Comment by emoxam** [comment]
I am voting for option to disable this dialog. It's redudant for me.

**Comment by siriusgithub** [comment]
I concur, please remove the close confirmation dialog box.

**Comment by emoxam** [comment]
I don't think something is going to be added, it's hard to discuss app when dev thinks it's ideal.
