### ISSUE TITLE
Problem auto connect password

### ISSUE THREAD

**Issue by alienos** [asbru-cm/asbru-cm#61]
Hi
I have it like that.
Password for test@s1.test.com:
And you do not automatically log in with the password.

**Comment by gfrenoy** [comment]
I do fear we'll need more information to really help...

What kind of connection are you trying to make (SSH, RDP, VNC, ...) ?
What error message do you see ?  Can you make a screenshot ?
What version are you using ?  On which system ?

**Comment by alienos** [comment]
SSH 
Config:
![config](https://user-images.githubusercontent.com/7785010/36384644-47ca3b6e-1590-11e8-9666-fcaaddaf2126.png)
Error(Enable option Expect Debug )
![error](https://user-images.githubusercontent.com/7785010/36384657-527cd6fc-1590-11e8-8233-2513304aa851.png)
Manjaro 17.1.5

**Comment by gfrenoy** [comment]
Interesting so it looks the regular expression does not match your prompt...

Can you try to change your "PASSWORD prompt" parameter (in global Preferences) and add a dot (.) just before the star (*) as shown in this screenshot:

![image](https://user-images.githubusercontent.com/981546/36396508-e697d430-15be-11e8-8ff0-eb4eb3f97582.png)

So at the end your password prompt parameter should be:

    ([p|P]ass|[p|P]ass[w|W]or[d|t](\s+for\s+).*|[c|C]ontrase.a|Enter passphrase for key '.+')\s*:\s*$

**Comment by alienos** [comment]
>  CONNECTING WITH 'ct8' (Tue Feb 20 15:25:33 2018) =->

[pac_conn(986)][ct8][ct8]: !!_PAC_AUTH_[pac_PID818_n3]!!
[pac_conn(986)][ct8][ct8]: SPAWNING:ssh -p 22   -X -l obcy ct8.pl
[pac_conn(986)][ct8][ct8]: SPAWNED:'ssh -p 22   -X -l obcy ct8.pl' (PID:986)
Starting EXPECT pattern matching...
 at /usr/share/perl5/vendor_perl/Expect.pm line 597.
	Expect::expect(Expect=GLOB(0x56163e51dd80), 40, ARRAY(0x56163f3f87d0), ARRAY(0x56163f3f8998), ARRAY(0x56163f406a08), ARRAY(0x56163f406c18), ARRAY(0x56163f406cf0), ARRAY(0x56163f4070f8), ...) called at /opt/asbru/lib/pac_conn line 1572
spawn id(3): list of patterns:
  #2: -eof `'
  #3: -re `\\[__PAC__SUDO__PROMPT__\\]'
  #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'
  #5: -re `.*(any key to continue|tecla para continuar).*'
  #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'
  #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'
  #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+).*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'
  #9: -re `[#%\\$>]|\\:\\/\\s*$'


spawn id(3): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+).*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

Password for obcy@s1.ct8.pl:
spawn id(3): Does `Password for obcy@s1.ct8.pl:'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+).*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? YES!!
    Before match string: `'
    Match string: `Password for obcy@s1.ct8.pl:'
    After match string: `'
    Matchlist: (`Password for obcy@s1.ct8.pl',  ` for ')
Calling hook CODE(0x56163f4072a8)...
Sending 'Secret password\n' to spawn id(3)
 at /usr/share/perl5/vendor_perl/Expect.pm line 1421.
	Expect::print(Expect=GLOB(0x56163e51dd80), "Secret password\x{a}") called at /opt/asbru/lib/pac_conn line 516
	main::send_slow(Expect=GLOB(0x56163e51dd80), "Secret password\x{a}", "hide") called at /opt/asbru/lib/pac_conn line 1435
	main::__ANON__(Expect=GLOB(0x56163e51dd80)) called at /usr/share/perl5/vendor_perl/Expect.pm line 825
	Expect::_multi_expect(40, ARRAY(0x56163f3fc208), ARRAY(0x56163f3fcc10)) called at /usr/share/perl5/vendor_perl/Expect.pm line 602
	Expect::expect(Expect=GLOB(0x56163e51dd80), 40, ARRAY(0x56163f3f87d0), ARRAY(0x56163f3f8998), ARRAY(0x56163f406a08), ARRAY(0x56163f406c18), ARRAY(0x56163f406cf0), ARRAY(0x56163f4070f8), ...) called at /opt/asbru/lib/pac_conn line 1572
[pac_conn(986)][ct8][ct8]: PASSWORD:Sent (not shown)
Continuing expect, restarting timeout...

spawn id(3): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+).*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.



spawn id(3): Does `\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+).*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

X11 forwarding request failed on channel 0

spawn id(3): Does `\r\nX11 forwarding request failed on channel 0\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+).*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

Last login: Tue Feb 20 15:25:13 2018 from Ip number

spawn id(3): Does `\r\nX11 forwarding request failed on channel 0\r\nLast login: Tue Feb 20 15:25:13 2018 from Ip number\r\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+).*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

                 
spawn id(3): Does `\r\nX11 forwarding request failed on channel 0\r\nLast login: Tue Feb 20 15:25:13 2018 from Ip number\r\r\nżó�\202�\207żó�\202�\207\033[6n\r                 \r'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\((.+)\\/(.+)\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([l|L]ogin|[u|U]suario|([u|U]ser-?)*[n|N]ame.*|[u|U]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([p|P]ass|[p|P]ass[w|W]or[d|t](\\s+for\\s+).*|[c|C]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

^[[59;9R[pac_conn(986)][ct8][ct8]: CLOSE:TIMEOUT:40 seconds trying to connect or get prompt!!
[pac_conn(986)][ct8][ct8]: DISCONNECTING
[pac_conn(986)][ct8][ct8]: DISCONNECTED

 <-= DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Tue Feb 20 15:26:14 2018)

**Comment by gfrenoy** [comment]
You are now connected and Ásbrú is now looking for the command prompt that must match:

    [#%\$>]|\:\/\s*$

If you prompt is different, you'll need to adapt the regular expression in parameter "Command Prompt" (Preferences > Main Options > Advanced).

**Comment by alienos** [comment]
Thank you for your help
