### ISSUE TITLE
Unable to connect to SSH hosts on Ubuntu 20.04

### ISSUE THREAD

**Issue by vectr0n** [asbru-cm/asbru-cm#614]
**Describe the bug**
When I try and open a terminal for a remote ssh host it just sits at yes/no/fingerprint. When you type yes it just sits there and then times out.

**To Reproduce**
1. Open Remote SSH Host
2. See Error

**Expected behavior**
It should accept the key difference and move on. I do not get the key difference message when connecting on a normal command line.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Ásbrú Version: 6.1.3

**Additional context**
CONNECTING WITH ircd1: xx.xx.xx.xx (Tue May 12 19:29:51 2020)

GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.
The authenticity of host 'ircd1.example.com (fd26:48b:41:24::10)' can't be established.
ECDSA key fingerprint is SHA256:xxxx.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes/no
Please type 'yes', 'no' or the fingerprint: yes
Terminated

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Tue May 12 19:30:32 2020)

**Comment by hanspr** [comment]
This looks like an issue related to expect, please read this section

https://docs.asbru-cm.net/Managing/Expect/

You may need to modify your regex for that connection to detect the correct prompt strings. 

If you need further help for that, you will have to run the connection turning "Expect DEBUG", as explained in the article. And upload the messages to understand the login sequence you are having.

You will need to obfuscate any sensitive data that comes out of that log before uploading, passwords could be visible.

**Comment by vectr0n** [comment]
This doesn't really make much sense to me as I am using the exact same config and version on Debian 10 and have no issues logging in, so not sure why I would need to change anything.

**Comment by hanspr** [comment]
A simple test, to check if it is related or not to Expect, is that you change your connection details to "Manual", so you log manually to that SSH session.

![imagen](https://user-images.githubusercontent.com/1572396/81758558-ca139c00-9487-11ea-9150-fdd018e6132e.png)

If you can manually login, then is an Expect issue. If you can not, then is an SSH issue.

If you can login, then check what happens with the expect sequence, it will bring some light to the problem.

**Comment by vectr0n** [comment]
So when I do one round of Manual then switch it back to private key it's all good.

**Comment by hanspr** [comment]
That means is an Expect sequence that is not working properly, must likely the sequence related to accept the key.

You may debug that part and share the results with us, so we all know how to handle that sequence and improve the involved regex.

**Comment by vectr0n** [comment]
I would assume the added [fingerprint] option in Ubuntu 20.04 ssh might be the issue:

```
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

**Comment by hanspr** [comment]
Possibly, but if we can not reproduce, we can not fix it.

Maybe @gfrenoy  has some Debian 10 virtual machine to reproduce the issue. I don't, sorry. I depend more on logs, and stuff like that to study and fix errors.

**Comment by vectr0n** [comment]
There are 0 issues on Debian 10, it's Ubuntu 20.04 where the issue is. People on fresh installs of Ubuntu 20.04 will definitely run into this issue as key's won't be auto accepted.

**Comment by gfrenoy** [comment]
Can you check issue #145 ?

In particular there is an option to check to auto accept this and the host-key verification regexp must be up to date (if you upgraded from an old version, you may not have the latest one).

**Comment by vectr0n** [comment]
@gfrenoy thanks for the reply. I have been using the same config since many many PAC versions so I would appear it never got "updated" but altering the regex from #145  solved the problem :)
