### ISSUE TITLE
Left click on several selected connections deselcts selection befores popup shows

### ISSUE THREAD

**Issue by hanspr** [asbru-cm/asbru-cm#617]
If you select several nodes from the connections tree, and then right click, the selection will be lost and only the last clicked node is selected.

![Peek 13-05-2020 08-51](https://user-images.githubusercontent.com/1572396/81821010-fc101700-94f6-11ea-9942-6f92f5505615.gif)

1. Select several nodes with shift click 
2. Right click on any of the selected nodes
3. Selection is lost, onli node with right click is selected

Expected

Select should remain and popup menu show

+ Mint
+ Loki branch

**Comment by gfrenoy** [comment]
Fixed by the last commit, thanks a lot !
