### ISSUE TITLE
Fatal crash on post exec

### ISSUE THREAD

**Issue by accessone67** [asbru-cm/asbru-cm#618]
**Describe the bug**
In SSH connection method asbru totally crash when using pre-exec/post-exec.

**To Reproduce**
I'm using this script and asbru totaly fatal crash.

If connecting to server the script executed right and everything Ok, if disconnected the asbru fatal crash and closes.

My /etc/sudoers:
```
XX ALL=(ALL:ALL) NOPASSWD:/home/XX/mount_share.sh
XX ALL=(ALL:ALL) NOPASSWD:/home/XX/umount_share.sh

```
pre-exec: 
`sudo /home/XX/mount_share.sh
`

mount_share.sh:
`mount -t cifs //127.0.0.1/share/folder  /mnt/share -o username=xxxx,password='xxxx',ip=127.0.0.1,port=3698
`

post-exec:
`sudo /home/XX/umount_share.sh`

umount_share.sh
`umount /mnt/share`

the scripts works fine if manualy run

syslog error:
![image](https://user-images.githubusercontent.com/7426496/81844624-08788c00-9558-11ea-9efd-621044fdf15d.png)

**Comment by hanspr** [comment]
What Ásrbrú version are you using upgrade to 6.1.3 , 6.2 prefered and check again.

**Comment by accessone67** [comment]
I'm using latest version v6.1.3

**Comment by hanspr** [comment]
It is fixed in 6.2, I do not see 6.2 available in the releases, I don't know if is available in your package managers.

@gfrenoy is it 6.2 already available? or when will it be?

**Comment by KlaasT** [comment]
Should be released not so far in the future :)

**Comment by hanspr** [comment]
6.2 has been released, install check that it works.

If it works please close the ticket to clear the board.

**Comment by accessone67** [comment]
Everything works now as expected. Thank you :+1:
