### ISSUE TITLE
Add support for cipher 

### ISSUE THREAD

**Issue by rizmut** [asbru-cm/asbru-cm#624]
I would like to see the ability to define custom cipher since I got

`port 22: no matching cipher found. Their offer: 3des-cbc,aes128-cbc,aes192-cbc,aes256-cbc`

from my device.

I failed to managed to bypass this with **Chipers** option and **3des-cbc** or **aes123-cbc** in the value  (**SSH Options > Advanced Options**).  Or may am I wrong in this case?

**Comment by rizmut** [comment]
With 
`ssh -o Ciphers=3des-cbc user@ip-address `

I got 

```
Received disconnect from ip-address port 22:2: Authent
Disconnected from ip-address port 22
```

What's wrong here?

**Comment by gfrenoy** [comment]
> port 22: no matching cipher found

This is a negotiation between the SSH client and server ; if they cannot find a common cipher, you may first want to upgrade to a compatible version.

You may also want to read the [ssh_config man page](http://man7.org/linux/man-pages/man5/ssh_config.5.html) and check the list of available ciphers on your machine (ssh -Q cipher).

> Received disconnect from ip-address port 22:2: Authent

I don't recognize this error message but it looks like an authentication error, isn't it ?  Try to make it more verbose (preferably on both sides) to collect more information.

That being said, the advanced option ```Chiphers``` is available so you can specify it as you wish in Ásbrú:
![image](https://user-images.githubusercontent.com/981546/82140552-b5405b00-982f-11ea-84f0-d94d08d4a42d.png)

Not sure of your particular case but it is not related to Ásbrú and we cannot help further, I do fear.
