### ISSUE TITLE
Impossible to edit generic command connections after updating to 6.2.0

### ISSUE THREAD

**Issue by alfaustus** [asbru-cm/asbru-cm#625]
After updating to 6.2.0-1 via apt on Ubuntu 18.04 I can't edit generic command connections.
Steps to reproduce:
 - export all connections on PAC Manager v.4.5.7;
 - import on asbru-cm v.6.1.3-1;
 - restart asbru-cm with performing connections database migration;
 - in result there is no possibility to edit existing and even new generic command connection after its creation.
There is no reaction for Alt+E or Edit connection context menu entry unfortunately.

**Comment by hanspr** [comment]
Open a local terminal and run asbru-cm from the command line to see if we can get more information about the problem.

You may also create a debug file so we can test the configuration file and try to reproduce.

https://docs.asbru-cm.net/Manual/Preferences/Preferences/#anonymized-data-for-debug

**Comment by gfrenoy** [comment]
Thanks for reporting the issue !

An unfortunate change occurred, back in March  - see [here](https://github.com/asbru-cm/asbru-cm/commit/2f995c74a2bf13b373e782629a1755e67affbfcd#diff-e7b6708ed6429446d88002004f7b2c87L1207).

I fixed it on both the master (what will be 6.2.1) and loki (what will be 6.3.0) branches.

In the meantime, you can use our "snapshot release" (see https://docs.asbru-cm.net/General/Installation/) ; let us know if this correctly fixes the problem.
