### ISSUE TITLE
Remote Desktop connection with xfreerdp not working

### ISSUE THREAD

**Issue by blackjack9797** [asbru-cm/asbru-cm#628]
Added a RDP-Connection with Method "RDP (xfreerdp), when trying to connect I get the following error message:
CONNECTING WITH W10-daily-01 (Sun May 24 20:26:34 2020)
[20:26:34:397] [14562:14562] [ERROR][com.winpr.commandline] - Failed at index 1 [/parent-window:207850268]: Invalid sigil
FreeRDP - A Free Remote Desktop Protocol Implementation
See www.freerdp.com for more information
Usage: xfreerdp [file] [options] [/v:<server>[:port]]
.....

**To Reproduce**
1. Add a new RDP-connection with method "RDP (xfreerdp)
2. Open the connection
3. See error

**Expected behavior**
The window with the RDP-Connection should be opened.
When using "RDP (rdesktop) it works, but only if NLA is not forced.
It also works when opening the connection manually with xfreerdp /u:"username" /v:IPADDRESS:3389

**Screenshots**
![image](https://user-images.githubusercontent.com/65866520/82761924-181c8e00-9dfe-11ea-8b61-188b7387ffb8.png)

**Environment (please complete the following information):**
 - OS: Linux Mint 19.3
 - Ásbrú Version 6.2.0

**Comment by gfrenoy** [comment]
I did not test specifically with Mint 19.3 but, as far as I know, it is based on Ubuntu 18.04 which is the system I'm using.  And for Ubuntu 18.04 ; xfreerdp is working fine.

"[Invalid sigil](https://github.com/FreeRDP/FreeRDP/blob/baca062321919864b40cb350398a416ac0a42c5d/winpr/libwinpr/utils/cmdline.c#L158)" seems to indicate the command line is not properly parsed.

Maybe there is special character or something in the username or hostname ?

Can you maybe share what is given by the "Get Command Line" button in Connection > Advanced Parameters ?

**Comment by blackjack9797** [comment]
Commandline:
xfreerdp /parent-window:207968878 /size:1713x1050  /bpp:24  -5 -a 24 -r sound:off -r clipboard:PRIMARYCLIPBOARD /u:'username' /p:'53616c7465645df4vf5f313233343536373840cdd0bddd00087b2ea4148c6c6b5d6515a394b9095cd53500d29d5fec89ba2502d2f9b415cb' /v:192.168.111.232:3389

**Comment by blackjack9797** [comment]
Yes, its based on Ubuntu 18.04, and no, no special characters in username and/or password.

**Comment by gfrenoy** [comment]
Can you try to uncheck all options ?  I suspect one of these is not supported anymore...

Here I only have options:
/parent-window
/size
/bpp
/u
/p
/v

**Comment by gfrenoy** [comment]
Looks like options like ```-5``` and ```-r sound:off``` are specific to ```rdesktop```.  So I guess you switched from ```rdesktop``` to ```xfreerdp``` and that it messed it up somehow :-/

I believe that if you create the entry from scratch, it should work.

If you can let me know the steps to reproduce this, I'll see what we can do to avoid it.

**Comment by blackjack9797** [comment]
You got it!
Yes, I tried switching around with rdesktop and xfreerdp when I got issues with rdesktop and NLA.
But now it is working fine.
Thanks a lot for your really fast help on a Sunday evening!
