### ISSUE TITLE
Handle untrusted certificates with rdesktop connection

### ISSUE THREAD

**Issue by minizx** [asbru-cm/asbru-cm#629]
Hello
When you connect to rdesktop on the windows machine, if you receive a certificate confirmation message, the rdesktop connection is not working properly.
(Certificate is normally connected when stored. )

To resolve this issue, access is normal when using the command below, but the option to always connect from asbru-cm to that option seems difficult.

echo yes | rdesktop remote_server_ip

* Problem environment
Ubnut 20.04 64bit
asbru-cm 6.2.0
rdesktop 1.9.0
Destination If Windows Device is first

* Example of Certificate confirmation message
[id@ubuntu20.04 to]$ rdesktop remote_server_ip
Autoselecting keyboard map 'ko' from locale

ATTENTION! The server uses and invalid security certificate which can not be trusted for
the following identified res(s);

1.Certificate is not trusted by this system.

Issuer: CN=remote_server_ip

Review the following certificate before you trust it to be added as an extension.
If you do not trust the certificate the connection will be addressed:

Subject: CN=remote_server_ip
Issuer: CN=remote_server_ip
Valid From: Tue Apr 21 10:29:46 2020
To: Wed Oct 21 10:29:46 2020

Certificate fingerprints:

sha1: aaa36a9c052ce7d5c83f8891731c69622859975
sha256: aaaaf9c0b0b0ba654fdb0a4a4a4ca1c892bdf52b2bf66755d578c4130af1c9bf

Do you trust this certificate (yes/no)?

**Comment by gfrenoy** [comment]
What is wrong here is that there is no way to handle this from within Ásbrú ; you need to add that certificate to the rdesktop known hosts (typically in `.local/share/rdesktop/certs/known_hosts`) by connecting a first time outside Ásbrú.  Then it should work fine.

So the question is : how do we want to handle this ?

I see several options / ideas to analyse a bit further:

- Intercept the message ("Do you trust this certificate") and ask the same interactively (in a message dialog box)
- Show the "messages" window and allow interactive answer inside the message window
- Have an option in the rdesktop settings to silently accept any certificate
- ... and probably some other

Any comment or suggestions to find the proper way to handle this will be welcome

**Comment by minizx** [comment]
I think number 1 is a function that should be provided by default.
In case of number 2, I think it's a good option if you can provide it.

    1. Show the "messages" window and allow interactive answer inside the message window
    2. Have an option in the rdesktop settings to silently accept any certificate


If it's hard to implement or takes a long time, I'd like to have the message displayed in the console window available on the screen.
Currently, there are no certificate messages, so we don't know why we can't connect within the asbru-cm program.

**Comment by gfrenoy** [comment]
Thanks for your feedback !

**Comment by gfrenoy** [comment]
@minizx Just pushed a change that must greatly improve the user experience.

1) The remote desktop window is hidden until it is actually created by the subprocess
2) You can now interact with the command line

Consequently, if the subprocess is asking you to review some untrusted certificates and accept them, you can now do it directly with Ásbrú :)

This change is now available on the loki branch and will be available in the next 6.3.0 release (whenever it is released...).

Let us know if you have the opportunity to test this further and give you feedback.
