### ISSUE TITLE
Adding new codenames in repository for Linux Mint (18.x)

### ISSUE THREAD

**Issue by marcinbojko** [asbru-cm/asbru-cm#63]
Currently, adding Linux Mint 18.3 (Sylvia) we got in /etc/apt/sources.lists.d/asbru-cm_asbru-cm.list

>this file was generated by packagecloud.io for
>the repository at https://packagecloud.io/asbru-cm/asbru-cm
>deb https://packagecloud.io/asbru-cm/asbru-cm/linuxmint/ sylvia main
>deb-src https://packagecloud.io/asbru-cm/asbru-cm/linuxmint/ sylvia main

which ends with apt being unable to find proper repo.
Changing to

>this file was generated by packagecloud.io for
>the repository at https://packagecloud.io/asbru-cm/asbru-cm
>deb https://packagecloud.io/asbru-cm/asbru-cm/linuxmint/ **sonya** main
>deb-src https://packagecloud.io/asbru-cm/asbru-cm/linuxmint/ **sonya** main
allowes us to install asbru-cm properly.

Is it possible to add another keywords in repo for us, Mint-lovers? ;)

**Comment by KlaasT** [comment]
We can try to add Sylvia. Do you know on which Debian version Sylvia is based on? We always have an issue on dependencies and need to know if these can be met.

**Comment by KlaasT** [comment]
Please have a look on our snapshots repository https://packagecloud.io/asbru-cm/snapshots

You should be able to find Sylvia there. The packages still have to be tested if they work correctly. Feel free to help. :-)

**Comment by marcinbojko** [comment]
Thanks ;)
All 18.x releases are based on Ubuntu 16.04 LTS. After changing (manually) repos - packages for sonya work like a charm:)
I'd like to help in my limited way :)
Package: asbru-cm_5.0.1~1519116414-1_amd64.deb works :)

**Comment by marcinbojko** [comment]
@gfrenoy , small steps, but:
>The repository 'https://packagecloud.io/asbru-cm/asbru-cm/linuxmint sylvia Release' does not have a Release file.

**Comment by KlaasT** [comment]
At the moment sylvia is only available at the snapshort repository. As soon as we release the next version we will have it in the main repository too. So if the snapshot works everything is fine and we know we can release it for the distribution soon.

**Comment by marcinbojko** [comment]
Snapshot works, script for adding repo to sources.lists.d works correctly.
Awaiting next release.

**Comment by KlaasT** [comment]
Wonderful. I'll close that one for now and we will have them ready for the next release :-)
