### ISSUE TITLE
"CTRL+TAB goes to" setting is now obsolete

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#630]
Hi, I'm using Loki branch atm, and after the last updates (can't tell since which specific version), the setting to use CTRL+TAB to go to the Next tab doesn't seems to work any more, it always goes to the last focused tab, and pressing CTRL+TAB again goes back to the initial tab, so it only switches between two tabs all the time.

Thanks

**Comment by gfrenoy** [comment]
With the review of all key bindings (credits to @hanspr :1st_place_medal:), some choice needed to be done and Ctrl+Tab indeed does not behave exactly the same in loki than in 6.2.

The good news is that you can customize this as you wish:

![image](https://user-images.githubusercontent.com/981546/83003342-77e98380-a00e-11ea-81b5-8ee722edb032.png)

I think you want to assign "Ctrl+Tab" to "Next Tab" (and probably "Ctrl+Shift+Tab" to "Previous Tab").

Would that work for you ?

**Comment by ferent** [comment]
oh this works great, thanks, then the setting under Main Options should be removed to avoid any confusion.

**Comment by gfrenoy** [comment]
> the setting under Main Options should be removed to avoid any confusion.

Indeed, very good point !  Thanks for the suggestion, will definitely do that :)

**Comment by gfrenoy** [comment]
Just pushed a change that removes that setting.
