### ISSUE TITLE
File transfer functions like SecureCRT are required

### ISSUE THREAD

**Issue by ccrescent** [asbru-cm/asbru-cm#632]
**Is your feature request related to a problem? Please describe.**

File transfer functions like SecureCRT are required. Access the server through SecureCRT, and then jump to the sub server in the intranet. The file cannot be copied with SCP.
Thankyou

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gfrenoy** [comment]
Can you describe a bit more in details what you have in mind and analyse a bit further what needs to be modified in Ásbrú, including what it can bring to the project ?

**Comment by gfrenoy** [comment]
As a matter of fact, a SFTP connection type is already available
![image](https://user-images.githubusercontent.com/981546/83239705-9ed3c100-a198-11ea-97c4-f14bda758fbb.png)

and you also have the option to open a SFTP from any SSH connection using the context menu:
![image](https://user-images.githubusercontent.com/981546/83239573-6502ba80-a198-11ea-91cc-1ce1d89c7dbf.png)

Is that what you are looking for ?
