### ISSUE TITLE
closing one tab in cluster disconnects whole cluster

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#634]
when I click on tab X and confirm closing tab all nodes from cluster got disconnected and below message is printed on other terminals

__PAC__STOP__addc1458-2a61-4b14-a59d-f796ff73a00d__32692__

debian 10 (proxmox) + xfce, loki 6.3.0

**Comment by gfrenoy** [comment]
Confirmed on the latest Gtk & Ásbrú version.

**Comment by gfrenoy** [comment]
Thanks for the fix @hanspr ; it worked for me :)  @vibo69 let us know if the latest loki build also works for you.

**Comment by vibo69** [comment]
in latest (today) version problem is eliminated. but.. i see another new problem in this version. will describe in new issue
