### ISSUE TITLE
Authentication failed - escaping $ in passwords field (VNC)

### ISSUE THREAD

**Issue by doman18** [asbru-cm/asbru-cm#641]
Kubuntu 18.04 Asbruu v6.2.0

I have some passwords like $something$else$ from my client (i cant change them). In KRDC they work well (KDEWallet) but i had an issue with VNC in Asbruu. TigerVNC and xtightvnc were giving me Authentication error. 

As workarround i used slashes  \\$something\\$else\\$. It took me loooong time before i realised where the problem is.

**Comment by gfrenoy** [comment]
Thanks for your report!  The password was indeed not properly escaped when using a VNC termainal.  It is fixed in the last commit that will be available in the next 6.2.1 release.
