### ISSUE TITLE
Close all terminals on F4 key

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#645]
How can I change this key binding? or disable it?
I tried editing config file with no results. It is really frustrating without F4 available.

1. close asbru
2. edit asbru.yml
3. start asbru

I still can't use F4 key :| 

latest loki

**Comment by gfrenoy** [comment]
Use Preferences > Key bindings ; select the line with "Close all terminals" and press the desired key (or delete to disable it).

![image](https://user-images.githubusercontent.com/981546/84066921-eb07d800-a9c6-11ea-823d-6d72a9f771fe.png)

See also our manual : https://docs.asbru-cm.net/Manual/Preferences/KeyBindings/

**Comment by vibo69** [comment]
thanks, thats what i missed out ;) I think only F4 is a bit wrong keybinding. I suggest adding ALT to it or whatever (by default)

**Comment by gfrenoy** [comment]
The key for "Close all tabs" was Ctrl+Shift+F4 in 6.2.1 ; not sure why it has been changed but I reverted it to the previous value.  Thanks for the heads up.
