### ISSUE TITLE
Suggest packages to create all supported types of connections

### ISSUE THREAD

**Issue by gfrenoy** [asbru-cm/asbru-cm#647]
**Is your feature request related to a problem? Please describe.**
Review dependencies and especially what is "recommended" and "suggested".

**Describe the solution you'd like**
Ásbrú can manage many types of connections (ssh, telnet, rdp, vnc, ...) ; all these connections will only work if some other packages are installed (xfreerdp, tigervnc, ...).

In the current package dependencies, we do install:

- openssh-client
- telnet
- ftp

By reading a bit more the [Debian documentation](https://manpages.debian.org/stretch/dpkg-dev/deb-control.5.en.html), I realized there are three types of dependencies we can have:

Depends: an absolute dependency (Ásbrú will not work at all if we don't have them)
Recommends: strong, but not absolute, dependency (Ásbrú can work with limitations)
Suggests: no dependency but can perhaps enhance Ásbrú usefulness

(note: RPM has the same kind of definitions)

According to these definitions, I would like to propose to:

- keep openssh-client ; it could but nothing would really work without ssh which is the typical connection type to start with
- move telnet and ftp from "Depends" to "Suggests" ; don't believe many of you are using them (I don't) and this is for sure not an absolute requirement
- remove keepassx ; it has been superseded by keepassxc
- keep keepassxc in "Recommends" since it is not a dependency but we strongly recommend to keep your passwords secured
- add all other connection types packages (with alternatives) to "Suggests": freerdp-x11 | rdesktop, tigervnc-viewer | xtightvncviewer, mosh, cu | remote-tty, c3270 | x3270

**Comment by gfrenoy** [comment]
Before I proceed with this, any comment or suggest will be warmly welcome :)

**Comment by popxunga** [comment]
Hi @gfrenoy 
That would be fine on EL8 where the rpm-build package currently at version 4.14.2 supports the "Recommends" and "Suggests" tags but not on EL7 where the rpm-build package 4.11.3 does not.
I'll investigate if it is possible to get a more recent version of the rpm-build package working on EL7.
By looking at all the possible connection types, looks like you're missing the dependencies for 3270 and 5250 connections which on the RPM world should be x3270-x11 and tn5250.
Thanks.

**Comment by gfrenoy** [comment]
Mmm, I see ; so we should have a specific file for EL7 :-/  Not sure we can do that easily...

@KlaasT any idea ?

**Comment by popxunga** [comment]
Looks like that the minimum rpm-build version required is 4.12 (http://rpm.org/wiki/Releases/4.12.0).

**Comment by gfrenoy** [comment]
Found this : https://docs.fedoraproject.org/en-US/packaging-guidelines/DistTag/

Not yet sure of the final syntax though...

**Comment by popxunga** [comment]
That's pretty common.
See the KeepassXC spec file to have an idea how it works.

**Comment by popxunga** [comment]
Hi @gfrenoy ... just updated my previous post ...

**Comment by gfrenoy** [comment]
Thanks :+1:  !

So what we can do is simply skip the "recommends" and "suggests" for EL7 with somethings like:

```
%if 0%{?el7}
Depends: telnet
Depends: ftp
%else
Recommends: keepassxc
Suggests: telnet
Suggests: ftp
%endif
```

I'll give it a try...

**Comment by popxunga** [comment]
Just to let you know that I've built both el7 and el8 Loki builds successfuly.

**Comment by gfrenoy** [comment]
I believe this is OK for now on the loki branch so let's close this for now.
