### ISSUE TITLE
Key to open connection list

### ISSUE THREAD

**Issue by chenchix** [asbru-cm/asbru-cm#649]
Maybe it exists and I was not able to find it but, I would like a key (or combination) to open connection list once you have selected "Hide connection list (on terminal open)"

**Comment by gfrenoy** [comment]
Just realized there is already something : `Alt+n`.

Note that it only works when you have the focus on a terminal today.

And as of 6.3 ; all keys are indeed customizable (see [docs](https://docs.asbru-cm.net/Manual/Preferences/KeyBindings/)) ; it would only be the default.

**Comment by chenchix** [comment]
Cool! 

I am in 6.1.1, i will update. 
Thank you and sorry for wasting your time.

**Comment by gfrenoy** [comment]
No problem, you point was certainly valid !

I made a few more changes to better support that shortcut key.  You can test the changes on the loki branch (https://docs.asbru-cm.net/General/Installation/).

When upgrading from 6.1.x ; your configuration files will be migrated.  It is safe but, just in case, please make sure you have a safe copy of your `~/.config/pac` before proceeding.

**Comment by chenchix** [comment]
Testing loki.
You rock!

**Comment by popxunga** [comment]
Hi ...
Are these warning messages supposed to be written into the terminal ?
![image](https://user-images.githubusercontent.com/37672088/84644768-82a18500-aef7-11ea-9aee-62067c67302d.png)
Thanks.

**Comment by gfrenoy** [comment]
> Are these warning messages written into the terminal expected ?

Once, after a new key binding has been added ; yes.

If that key binding has been saved in your configuration, you should not see it anymore.

**Comment by popxunga** [comment]
> > Are these warning messages written into the terminal expected ?
> 
> Once, after a new key binding has been added ; yes.
> 
> If that key binding has been saved in your configuration, you should not see it anymore.

Indeed ... Thanks !
