### ISSUE TITLE
Proper KeePass support

### ISSUE THREAD

**Issue by yennor** [asbru-cm/asbru-cm#65]
Right now Asbru supports KeePass files, but the support is suboptimal.
- only old kdbx 3.1 file format is supported
- Asbru does not notice when passwords are changed or added to the keepass file.
- asbru insist on, that the password needs to be saved with the config files. That means it will be stored unencrypted. It would be better if asbru asks on start up for the keepass file password.

The best solution in general would propably be, if asbru could support the browser integration protocol of KeePassXc. It is a  little bit described here: 
https://keepassxc.org/docs/keepassxc-browser-migration/

Like that most above points are  solved. Additionally the user only needs to delock the database once.

what do you think?

**Comment by gfrenoy** [comment]
I definitely support the idea :)  We need to link to issue #56 as well.

Now, how can we make progress on this ?  Is there anybody willing to work on this ?

**Comment by Cris70** [comment]
Yes, please! Add the support for KeepassXC!! :+1:

**Comment by Prototype-X** [comment]
The KeePassX password is stored in a configuration file and is easily decrypted.
Can you fix this?
1. Do not store the KeePassX password in the configuration
2. Ask for KeePassX password when starting asbru

**Comment by Stunherald** [comment]
I second to that. Please add KeePassXC support :)

**Comment by mbreskovec** [comment]
Hello guys, any progress in this case, or any time estimation? This is something what really makes me cry, when I need to change password for all my connections manually.

**Comment by gfrenoy** [comment]
I'd love to see progress but I do fear the project will need your help ; anyone to follow-up on my last questions:

> how can we make progress on this ?
> Is there anybody willing to work on this ?

**Comment by gfrenoy** [comment]
Oups.  Did not mean to close the issue ; sorry.

**Comment by figue** [comment]
Recently I have been converting my kdb databases to version 4.0 and have suffered this issue, because only 3.1 is supported. Will be a very good addition to support new version as reported.

**Comment by skipperTux** [comment]
With regards to [yennor's](https://github.com/asbru-cm/asbru-cm/issues/65#issue-303488703) comment I did some googling for KeePassXC integration via browser integration. This integration type solves a few of the above problems like

- no support of different file formats necessary
- no storing of Master-password necessary

because access of the password database is all going through the unlocked KeePassXC application using a proxy.

A more detailed description of the protocol can be found at [keepassxc-protocol](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-protocol.md) and the [browser plugin](https://github.com/keepassxreboot/keepassxc-browser) may be used as a blueprint. The communication with KeePassXC using [TweetNaCl.js](https://github.com/dchest/tweetnacl-js) is done in [keepass.js](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/background/keepass.js) - full source code available. The TweetNaCl project also provides some [Examples](https://github.com/dchest/tweetnacl-js/wiki/Examples). However all of this code is in JavaScript.

I also found two Perl libraries for TweetNacl/NaCL.

TweetNacl : https://github.com/soundart/perl6-tweetnacl
Crypt::Sodium (Perl bindings for libsodium (NaCL)) : https://metacpan.org/pod/Crypt::Sodium

Bad luck I have no Perl background, so this is where my support/help is ending.

**Comment by gfrenoy** [comment]
Thanks for the additional information!  It really helps :)

While searching about this topic, I found KeePassXC also implement the Freedesktop.org Secret Storage spec :  https://github.com/keepassxreboot/keepassxc/pull/2726 ; not sure what it exactly means and if it can be useful but wanted to keep track of this :)

**Comment by skipperTux** [comment]
According to the [spec](https://www.freedesktop.org/wiki/Specifications/secret-storage-spec/) the freedesktop.org Secret Service API is [_a common way to store secrets, a desktop agnostic version of GNOME Keyring and KWallet desgined by GNOME and KDE developers_](https://specifications.freedesktop.org/secret-service/latest/ch01.html). The API also provides several [interfaces](https://specifications.freedesktop.org/secret-service/latest/ch13.html) for getting secrets and searching items.

By simple googling I could not find any Perl library supporting D-Bus Secret Service API, so all D-Bus communication might have to be written from scratch using [Net::DBus](https://metacpan.org/pod/Net::DBus). The [secretstorage](https://github.com/mitya57/secretstorage) Python library could serve as a blueprint.

Using this generic API might even be a better and more flexible approach for integrating KeePassXC or other secret storages.

**Comment by hanspr** [comment]
@gfrenoy , @KlaasT 

I have come around this issue several times on previous months, and my personal take on this.

* I checked the specifications of keepassx-protocol, and I'm discourage to implement over engineered  solutions. I do not like the protocol, and I did not like the way it works, returning an array of "all possible matched entries" and not able to look for a specific one, you have to dedicate time creating relationships in the fields to make it work.
    * I use keepassxc, with auto type, make sure all my window titles are different and I simply spit out all sort of key combinations to the terminal
* Freedesktop Secret Storage, creating more dependencies that will change with time

The yml file __does have encrypted passwords__, but we all use the same key. And this is to me the final issue.

I can, implement

* Allowing to set your own key
* Encrypt all password fields in the yml file or the full file if you prefer
    * Maintaining the whole file encrypted on disk should be farely simple to implement. And just have the file loaded in memory.
   * But entrypt password field only is already implemented, the key is the problem.
    * We already added the Copy password option from the terminal and from the connection list, that has added more functionality regarding password management in Asbru
    * Have noticed from the issues and comments, that some people uses Global commands, Variables, Spects, to store passwords, implement sudo actions or other automated actions. We need to secure those and this are out of the scope of keepassxc
* I guess the main concern is loosing the yml file, get it stolen, having the need to transfer it over email.
    * I do not plan to address securing data already loaded in memory, if some one is working on such hostile environment this would not suffice.

Sorry if it is not what everybody wants, but let me know if you like me to work on this solution.

Benefits:

* Self controlled, not dependencies
* Safe storage and moving yml file around

Cons

* Duplicated information Asbru and external password storage application
* Keepassxc, would be a backup storage application, not an integrated one

**Comment by gfrenoy** [comment]
Well, having your own encryption key would be an **other** interesting feature.

But Ásbrú will never replace KeePass so the need for a good integration with KeePass will remain anyway...

Maybe the CLI interface would be a more solid base to interact with the KeePass database:
  https://www.mankier.com/1/keepassxc-cli
?

With the ```open``` command, you can interactively interact with the database.  If we open a "pipe" with the CLI, we can probably read any informatie that we need (just a guess at this stage...).

**Comment by hanspr** [comment]
was not aware of keepassxc-cli , if we manage to send the password (not available as an option) to unlock the database, then it would be possible to integrate this way. I will take a look to this road during the next week.

Still we need to secure the yml file, if we are going to store the password for keepassxc on our side, or path to the keyfile, and any other sensitive things that I mentioned before.

**Comment by hanspr** [comment]
Look at this, with this tiny code you can query the database with ease

```perl
#!/usr/bin/perl

use IPC::Open2;

$pid = open2(*Reader, *Writer, "keepassxc-cli show ~/path/myfile.kdbx '82b160d30b153744af7b7c5b176113f5'");
print Writer "passphrase\n";
while ($got = <Reader>) {
    print "$got";
}
```

![imagen](https://user-images.githubusercontent.com/1572396/71784344-2fc2b980-2fb8-11ea-9eec-12d84fce63d7.png)

**Comment by hanspr** [comment]
This is my proposal to rewrite all this stuff.

I will break everything most probably.

__KeePass Options__

* Remove the list
    * One of the reasons I never used Keepass integration is that I have more than 500 passwords in there and PAC used to choke opening, searching etc. 
* Remove option to multiple passwords
    * Should not happen, it makes no sense if you do a correct relation between asbru and keepassxc, this should not be necessary.

![imagen](https://user-images.githubusercontent.com/1572396/71784925-ddd16200-2fbe-11ea-8c5a-5816b2fbc44c.png)

__On connections__

![imagen](https://user-images.githubusercontent.com/1572396/71785060-d90dad80-2fc0-11ea-8d02-315f161d3dd5.png)


* The format of the entries to associate with a keepass entry should be
    * `<[field name]:[uuid|title]>`

__Field Name:__ one of the available field names presented with show: username, password, title, url, notes (as seen in above image)

__Title:__ being this one (should be unique, will not care for duplicates, first occurrence will be selected always)

![imagen](https://user-images.githubusercontent.com/1572396/71785023-6e5c7200-2fc0-11ea-855a-f2b9dcdbc990.png)

__Uuid:__ is preferred to avoid duplicate entries. (located at the info tab in keepassxc)

![imagen](https://user-images.githubusercontent.com/1572396/71785038-a2379780-2fc0-11ea-9eec-79e206a72068.png)

* To facilitate all this (have not decided to use double click on the field or add an icon), would open a new window to search by title and select the desired entry from keepassxc database, and write the values with the requested format `<username:uuid>` or `<password:uuid>` into the respective fields.

So when the time comes to convert this values into actual user names and passwords, we check the format, connect to the database, extract the values and substitute on real time at the moment of the connection.

This will remove all passwords from asbru and we will have only references to keepassxc

Suggestions are welcome.

---

On the second version will work to add user, password substitution to : expect, commands, variables, etc.

So usernames and passwords can be included safely into those fields.

**Comment by skipperTux** [comment]
> But Ásbrú will never replace KeePass so the need for a good integration with KeePass will remain anyway...

I second that.

In addition to @hanspr 's comments.
I prefer to not have my KeePassXC master password stored anywhere but in my brain (and maybe a sheet of paper stored in a safe place, as a backup). I would prefer to store it a) not at all, b) in memory, while asbru is running (~ session) or - convenience over security - c) in the yml file. Having this as three options is the most flexible solution IMHO.

Also my findings about keepassxc-cli in a nutshell.

- The password can also be piped into keepassxc-cli. This seemed to have worked for most KeePassXC versions, including the latest 2.5.1 version, [except some 2.4.x version](https://github.com/keepassxreboot/keepassxc/issues/1297#issuecomment-486541892).
`echo 'myPassword' | keepassxc-cli show /home/user/keepass/database.kdbx 'amazon.com'`

- The `--quiet` option seems not to take a path, as claimed in the [online help](https://www.mankier.com/1/keepassxc-cli#Options-General_options). The CLI help does not show that it takes a path, and this seems to be correct.
```
$ keepassxc-cli help show
Usage: keepassxc-cli show [options] database entry
Show an entry's information.

Options:
  -q, --quiet                   Silence password prompt and other secondary
                                outputs.
[...]
```

- Supplying a key-file is also supported via CLI
`echo 'myPassword' | keepassxc-cli show --key-file /home/user/.keepass/keyfile.key /home/user/keepass/database.kdbx 'amazon.com'`

- To return the password - and not only PROTECTED -, option `--show-protected` needs to be added.
`echo 'myPassword' | keepassxc-cli show --show-protected --key-file /home/user/.keepass/keyfile.key /home/user/keepass/database.kdbx 'amazon.com'`

- The `open` command opens a shell-like session, commands can be entered in the shell without providing the key-file and password for each command.
```
echo 'myPassword' | keepassxc-cli open --key-file /home/user/.keepass/keyfile.key /home/user/keepass/database.kdbx
Database> show "amazon.com" ## only double-quotes work here
Title: amazon.com
UserName: user
Password: PROTECTED
URL: http://www.amazon.com/
Notes: 
Database> exit ## quit throws Segmentation fault
```

**Comment by hanspr** [comment]
I have KeePassXC version 2.3.1, which returns passwords unprotected and has a reduced set of available commands.

Version 2.3.1 does __not__ support: `--key-file`, `open`,`--show-protected`

Will have to implement ways to handle the queries dependent of the capabilities of different versions.

Master password, had intended to make it optional. If not saved in asbru, will ask at the beginning and retain it for the session.

**Comment by skipperTux** [comment]
Master password, great to hear about the options. Thanks!

KeePassXC versions, hmm, this adds an extra complexity. The KeePassXC [changelog](https://github.com/keepassxreboot/keepassxc/wiki/KeePassXC-Changelog) provides some information about the CLI. The changelog in the Wiki stops at version 2.4.3 June 2019, but information about the latest versions can be found on the [releases page](https://github.com/keepassxreboot/keepassxc/releases).

- The CLI tool was added in [version 2.2.0](https://github.com/keepassxreboot/keepassxc/wiki/KeePassXC-Changelog#220-2017-06-26).
- According to the changelog the `--key-file` option was added in [version 2.3.0](https://github.com/keepassxreboot/keepassxc/wiki/KeePassXC-Changelog#230-2018-02-27).
- The `open` command was added in [version 2.5.0](https://github.com/keepassxreboot/keepassxc/releases/tag/2.5.0).
- The `--show-protected` option is brand new, it was added in [version 2.5.1](https://github.com/keepassxreboot/keepassxc/releases/tag/2.5.1).

Searching on the changelog pages with 'CLI' shows most of the changes/commits with regards to keepassxc-cli.

If I can further support/help by posting help [command] output, testing or else just give me a hint.

**Comment by skipperTux** [comment]
(Just for the sake of completeness to have all options listed: I learned that KeePassXC supports a [D-Bus interface](https://github.com/keepassxreboot/keepassxc/wiki/Using-DBus-with-KeePassXC), however it looks very limited and seems to be dropped in favor of the [Secret Service API](https://github.com/keepassxreboot/keepassxc/issues/1403). As I understand it not worth to follow up.)

**Comment by hanspr** [comment]
A Pull Request with fix has been published on loki branch

Hope there are some testers willing to check it out.

* Not tested: Opening the database with a key file.

Please read instructions in PR. #345

**Comment by gfrenoy** [comment]
Ásbrú now supports KeePass key file ; testers are welcome on the [loki branch](https://github.com/asbru-cm/asbru-cm#testing-new-features).
