### ISSUE TITLE
Jump host missing password and not save passwords

### ISSUE THREAD

**Issue by embaka** [asbru-cm/asbru-cm#650]
Missing password field in "Network Settings" in "Use a Jump Host".
When trying to connect, it asks for the password from the tunnel, and then the password from the second connection

**Comment by gfrenoy** [comment]
I do fear you have to use SSH key to connect to your jump host.  There are limitations that makes the connection with a password complicated.

**Comment by just4id** [comment]
> Missing password field in "Network Settings" in "Use a Jump Host".
> When trying to connect, it asks for the password from the tunnel, and then the password from the second connection

I also met this problem that password field is missing. The UI is different with manual site pages here:
https://docs.asbru-cm.net/Manual/Connections/SSH/

I think it's a bug.

**Comment by embaka** [comment]
> I also met this problem that password field is missing on master branch. The UI is different with manual site pages here:
> https://docs.asbru-cm.net/Manual/Connections/SSH/
> 
> While I pull loki branch and found the UI is same with the wiki page's showing. So you may need switch loki branch and pull to use.

It`s working after change to loki branch. Many thanks. This branch is the same as in the manual.
