### ISSUE TITLE
Error in generated autostart file

### ISSUE THREAD

**Issue by me2000** [asbru-cm/asbru-cm#651]
The generated autostart file (Start at session startup) has an error. The binary called in the line "Exec" is called asbru instead of asbru-cm. The complete line in ~/.config/autostart/asbru_start.desktop should look like this:

Exec=/usr/bin/asbru-cm --no-spash --iconified

Tested with asbru 6.2.2 from git on Arch Linux and XFCE 4.14.2

**Comment by gfrenoy** [comment]
Not sure to understand this one...?

The only "[desktop](https://github.com/asbru-cm/asbru-cm/blob/master/res/asbru-cm.desktop)" file we have is using `asbru-cm`.

@figue, is this something you are changing in the arch build process ?  Can you help ?

**Comment by figue** [comment]
Nope... The package only install this:
```shell
figue@pluto ~ % cat /usr/share/applications/asbru-cm.desktop 
[Desktop Entry]
Name=Ásbrú Connection Manager
Comment=Ásbrú Connection Manager is a user interface that helps organizing remote terminal sessions and automating repetitive tasks.
Terminal=false
Icon=asbru-cm
Type=Application
Exec=env GDK_BACKEND=x11 asbru-cm
StartupNotify=true
Categories=Utility;TerminalEmulator;GTK;
X-GNOME-Autostart-enabled=false
Actions=Shell;Quick;ReadOnly;Tray;

[Desktop Action Shell]
Name=Start local shell
Exec=env GDK_BACKEND=x11 asbru-cm --start-shell

[Desktop Action Quick]
Name=Quick connect...
Exec=env GDK_BACKEND=x11 asbru-cm --quick-conn

[Desktop Action ReadOnly]
Name=Start Read-Only instance
Exec=env GDK_BACKEND=x11 asbru-cm --readonly --no-backup

[Desktop Action Tray]
Name=Start in system tray
Exec=env GDK_BACKEND=x11 asbru-cm --iconified
```

**Comment by me2000** [comment]
OK, let me clarify this behavior, maybe first post was not precise enough. Sorry for that.

Fresh install on Arch Linux from aur, package aur-cm-git with glib-perl version 1.3293. asbru-cm reports as version 6.2.2.

When starting with a fresh config the option "Start at session startup" is disabled. Checking it, saving config, closing asbru and starting it again leads to an again unchecked option "Start at session startup". The reason for that is that there is not directory "/home/user/.config/autostart".

Manually creating "~/.config/autostart" changes this. Now checking the option "Start at session startup" stays checked across restarts of asbru-cm and there is a file created in ~/.config/autostart" called "asbru_start.desktop". This is what it looks like:

```
[Desktop Entry]
Name=PAC
Comment=Perl Auto Connector (auto start)
Terminal=false
Icon=pac
Type=Application
Exec=/usr/bin/asbru --no-splash
StartupNotify=false
Name[en_US]=PAC
Comment[en_US]=Perl Auto Connector (auto start)
Categories=Applications;Network;
X-GNOME-Autostart-enabled=true
```

Note the line starting "Exec", here the wrong executable "asbru" is called and at session startup asbru-cm is not started. Correcting this manually (either by directly editing ~/.config/autostart/asbru_cm.desktop or though the XFCE settings GUI" fixes this and asbru-cm is started as expected when the session starts.

If I check the option "Iconified in 'systray'" the line starting with "Exec" in "~/.config/autostart/asbru_start.desktop" changes to

```
Exec=/usr/bin/asbru --no-splash --iconified
```

so I assume that this file is generated from asbru-cm.

I hope that clarifies the behaviour.

**Comment by gfrenoy** [comment]
Thanks for the additional information !

Looks like there are a few places where `/usr/bin/asbru` is hardcoded:

https://github.com/asbru-cm/asbru-cm/blob/9c52566be5c8d4c93a48612429f11fac00a9daaa/lib/PACConfig.pm#L1183

https://github.com/asbru-cm/asbru-cm/blob/9c52566be5c8d4c93a48612429f11fac00a9daaa/lib/PACUtils.pm#L222

Replacing `asbru` with `asbru-cm` is trivial but it would probably be more clever to avoid any hardcoded path.

I'll check what I can do.

Thanks for reporting the issue !

**Comment by gfrenoy** [comment]
The issue should now be fixed in the master branch (labelled 6.2.2) ; did you have the opportunity to give it a try and confirm it works better ?

**Comment by me2000** [comment]
I tested the master branch from git and I do confirm that it works now as expected, both iconified and not.

When testing an older branch (g9f10b16) I did see another behaviour. This branch put a symbolic link from ~/.config/autostart to /opt/asbru-cm/res/asbru_start.desktop. The latter file does not exist and so again autostart does not work. Don't know if that is a problem of the specific arch linux aur build or of that particular branch. If this is irrelevant please just disregard my remark.

**Comment by gfrenoy** [comment]
Made more changes to ensure the `autostart` directory is created and remove that symbolic link ; not sure why we had that but it obviously does not work (the target of the link never existed...).

Hope this makes things a bit cleaner.  Thanks again for your feedback.
