### ISSUE TITLE
Copy and paste Cyrillic text

### ISSUE THREAD

**Issue by Shamanky** [asbru-cm/asbru-cm#652]
When copying/pasting сyrillic text, either not all selected text or something \u043a\u043e\u043c\ u0430\u043d\Uffffffff is inserted

1. Launch new local shell
2. I lead the сyrillic text with a mouse.
3. On the keyboard I press Shift + insert
on the screen \u041f\u0440\u043e\u0432\u0435\u0440\u043a\u0430\u043a\u043e\u043f\ u0438\ u0440\u043e\uffffffff

![Снимок экрана от 2020-06-21 13-04-00](https://user-images.githubusercontent.com/51577758/85219739-c694fe00-b3bf-11ea-8686-5dce02fe713b.png)

or
1. Launch new local shell
2. With a mouse I lead a part of the text in English and the Cyrillic text
3. On the keyboard I press Shift + insert
on the All-Series screen: ~ $ Check copy and paste Пр, more text was selected than inserted

![Снимок экрана от 2020-06-21 13-11-08](https://user-images.githubusercontent.com/51577758/85219928-10caaf00-b3c1-11ea-977e-56982733d7b1.png)

OS Ubuntu 20.04

**Comment by gfrenoy** [comment]
As far as I can see; what we are doing is:

```
my $vte = (...) ; # whatever to retrieve the considered VTE widget
$vte->paste_clipboard();
```

So not really anything we can do inside this project ; I do fear.

Noticeably, if I try this:

```
my $txt = $vte->get_clipboard(Gtk3::Gdk::Atom::intern_static_string('CLIPBOARD'))->wait_for_text();
```

`$txt` does not contain the selected text ; I would guess the same internal function is used in `paste_clipboard` (did not check) ?

One more thing I noticed: if I do a `right-click` / `Copy` on the selected text then `Shift+Insert`, the problem does not appear.

`Right-click` / `Copy` calls `$vte->copy_clipboard();` behind the scene.  Note sure to understand why this works better...

@egmontkob : any comment, suggestion or tip ?

**Additional notes and context**:

- A quick workaround is thus to use `Ctrl+Insert` / `Shift+Insert` to force a proper copy of the selected text ;
- Here is a cyrillic test to try out: `Кири́ллица`
- Ubuntu 20.04 is VTE 0.60 but got the same on Ubuntu 18.04 / VTE 0.52

**Comment by gfrenoy** [comment]
I've been able to reproduce this outside of Ásbrú:

```perl
use strict;
use Gtk3 -init;
use Glib::Object::Introspection;

Glib::Object::Introspection->setup(basename => 'Vte', version => '2.91', package => 'Vte');

my $window = Gtk3::Window->new();
my $scrollbar = Gtk3::VScrollbar->new();
my $hbox = Gtk3::HBox->new();
my $terminal = Vte::Terminal->new();
  
$window->add($hbox);
$hbox->pack_start($terminal, 1, 1, 0);
$hbox->pack_start($scrollbar, 0, 0, 0);
 
$terminal->spawn_sync('VTE_PTY_DEFAULT', '/tmp', ['/bin/bash', '-l'], undef, 'G_SPAWN_FILE_AND_ARGV_ZERO', undef, undef, undef);
$terminal->signal_connect (child_exited => sub { Gtk3->main_quit(); });
$window->signal_connect (delete_event => sub { Gtk3->main_quit(); 0 });
$terminal->signal_connect('key_press_event' => sub {
    my ($widget, $event) = @_;
    my $keyval  = Gtk3::Gdk::keyval_name($event->keyval) // '';
    my $ctrl    = $event->get_state() * ['control-mask'];

    if ($ctrl && $keyval eq 'i') {
        print("Paste clipboard...\n");
        $terminal->paste_clipboard();
        return 1;
    }
    if ($ctrl && $keyval eq 't') {
        my $txt = $terminal->get_clipboard(Gtk3::Gdk::Atom::intern_static_string('CLIPBOARD'))->wait_for_text();
        print("Get clipboard = [$txt]\n");
        return 1;
    }
    return 0;
});

$window->show_all();
Gtk3->main();
```

If you use `Shift+Insert`, the paste operation just works fine.  But if you handle this through a custom key (`Ctrl+I` in my example), the сyrillic text is not properly pasted by `$vte->paste_clipboard()`.

Next step would be to dig into the VTE code to understand the difference between the default handler and our custom handler.

**Comment by gfrenoy** [comment]
Looks like the default `Shift+Insert` is using the primary selection, instead of clipboard (see https://gitlab.gnome.org/GNOME/vte/-/blob/master/src/vte.cc#L4727) so I changed the code in Ásbrú accordingly.

Can you give it a try by using the "snapshot" branch (see [instructions](https://docs.asbru-cm.net/General/Installation/#ubuntu)) and let us know if it works for you ?

**Comment by Shamanky** [comment]
> Looks like the default `Shift+Insert` is using the primary selection, instead of clipboard (see https://gitlab.gnome.org/GNOME/vte/-/blob/master/src/vte.cc#L4727) so I changed the code in Ásbrú accordingly.
> 
> Can you give it a try by using the "snapshot" branch (see [instructions](https://docs.asbru-cm.net/General/Installation/#ubuntu)) and let us know if it works for you ?

Thank. Copy and paste work.
