### ISSUE TITLE
[Solved] Can't locate OSSP/uuid.pm after today update of Arch 

### ISSUE THREAD

**Issue by urosh990** [asbru-cm/asbru-cm#654]
**Describe the bug**
After update Arch linux where Perl was updated too, asbru no longer works. From the command line, there is an error:
```
Can't locate OSSP/uuid.pm in @INC (you may need to install the OSSP::uuid module) (@INC contains: /opt/asbru/lib /opt/asbru/lib/ex /opt/asbru/lib/edit /home/urosh/perl5/lib/perl5/5.32.0/x86_64-linux-thread-multi /home/urosh/perl5/lib/perl5/5.32.0 /home/urosh/perl5/lib/perl5/x86_64-linux-thread-multi /home/urosh/perl5/lib/perl5 /usr/lib/perl5/5.32/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.32/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.32/core_perl /usr/share/perl5/core_perl) at /opt/asbru/lib/PACMain.pm line 44.
BEGIN failed--compilation aborted at /opt/asbru/lib/PACMain.pm line 44.
Compilation failed in require at /usr/bin/asbru-cm line 93.
BEGIN failed--compilation aborted at /usr/bin/asbru-cm line 93.
```

**More info**
```
WARNING: '/usr/lib/perl5/5.30' contains data from at least 4 packages which will NOT be used by the installed perl interpreter.
 -> Run the following command to get a list of affected packages: pacman -Qqo '/usr/lib/perl5/5.30'
```
```
pacman -Qqo '/usr/lib/perl5/5.30'
perl-crypt-rijndael
perl-expect
perl-net-arp
uuid

```
**To Reproduce**
When starting asbru-cm

**Environment (please complete the following information):**
 - OS: Arch
 - Ásbrú Version: asbru-cm 6.2.1-1

**Comment by wcasanova** [comment]
Perl update to 5.32.
Rebuild glib-perl perl-crypt-rijndael perl-expect perl-net-arp uuid

**Comment by urosh990** [comment]
> Perl update to 5.32.
> Rebuild glib-perl perl-crypt-rijndael perl-expect perl-net-arp uuid
> 
> example
> yay -S glib-perl perl-crypt-rijndael perl-expect perl-net-arp uuid --rebuildall

Exactly... the thing that I missed is --rebuildall...
Thank you so much...

**Comment by bukajsytlos** [comment]
thanks again

**Comment by TeMaTiK0** [comment]
many thanks!

**Comment by reddare** [comment]
Same problem, with 5.38 now.
```
Can't locate OSSP/uuid.pm in @INC (you may need to install the OSSP::uuid module) (@INC entries checked: /opt/asbru/lib /opt/asbru/lib/ex /opt/asbru/lib/edit /usr/lib/perl5/5.38/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.38/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.38/core_perl /usr/share/perl5/core_perl) at /opt/asbru/lib/PACMain.pm line 44.
BEGIN failed--compilation aborted at /opt/asbru/lib/PACMain.pm line 44.
Compilation failed in require at /usr/bin/asbru-cm line 102.
BEGIN failed--compilation aborted at /usr/bin/asbru-cm line 102.
```

**Comment by bukajsytlos** [comment]
"Rebuild" did not help in my case. Had to confirm cleanBuild

**Comment by MrHappy** [comment]
Also tried rebuild and cleanbuild. Both cases didn't fix it for me...
```
> asbru-cm --verbose
Can't locate OSSP/uuid.pm in @INC (you may need to install the OSSP::uuid module) (@INC entries checked: /opt/asbru/lib /opt/asbru/lib/ex /opt/asbru/lib/edit /usr/lib/perl5/5.38/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.38/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.38/core_perl /usr/share/perl5/core_perl) at /opt/asbru/lib/PACMain.pm line 44.
BEGIN failed--compilation aborted at /opt/asbru/lib/PACMain.pm line 44.
Compilation failed in require at /usr/bin/asbru-cm line 102.
BEGIN failed--compilation aborted at /usr/bin/asbru-cm line 102.
```

**Comment by bukajsytlos** [comment]
I did this `yay -S perl vte3 cairo-perl glib-perl pango-perl perl-socket6 perl-expect perl-yaml perl-crypt-cbc perl-crypt-blowfish perl-gtk3 perl-net-arp uuid openssh inetutils perl-crypt-rijndael perl-xml-parser libcanberra perl-gtk3-simplelist libwnck3 perl-io-stty perl-io-tty --rebuildtree` when asking about clean build I selected all and also `sudo pacman -Rns $(pacman -Qtdq)` but not sure if that was necessary. maybe try to rebuild asbru too

**Comment by MrHappy** [comment]
@bukajsytlos Thanks. That put me in the right direction. I rebuild the components it was nagging about and after that asbru-cm worked fine again.

**Comment by dlj2019** [comment]
> I did this `yay -S perl vte3 cairo-perl glib-perl pango-perl perl-socket6 perl-expect perl-yaml perl-crypt-cbc perl-crypt-blowfish perl-gtk3 perl-net-arp uuid openssh inetutils perl-crypt-rijndael perl-xml-parser libcanberra perl-gtk3-simplelist libwnck3 perl-io-stty perl-io-tty --rebuildtree` when asking about clean build I selected all and also `sudo pacman -Rns $(pacman -Qtdq)` but not sure if that was necessary. maybe try to rebuild asbru too

Thanks for sharing @bukajsytlos. I followed your steps but it did not work for me. Do you have any other suggestions?

**Comment by bukajsytlos** [comment]
> > I did this `yay -S perl vte3 cairo-perl glib-perl pango-perl perl-socket6 perl-expect perl-yaml perl-crypt-cbc perl-crypt-blowfish perl-gtk3 perl-net-arp uuid openssh inetutils perl-crypt-rijndael perl-xml-parser libcanberra perl-gtk3-simplelist libwnck3 perl-io-stty perl-io-tty --rebuildtree` when asking about clean build I selected all and also `sudo pacman -Rns $(pacman -Qtdq)` but not sure if that was necessary. maybe try to rebuild asbru too
> 
> Thanks for sharing @bukajsytlos. I followed your steps but it did not work for me. Do you have any other suggestions?

which one exactly?

**Comment by dlj2019** [comment]
> > > I did this `yay -S perl vte3 cairo-perl glib-perl pango-perl perl-socket6 perl-expect perl-yaml perl-crypt-cbc perl-crypt-blowfish perl-gtk3 perl-net-arp uuid openssh inetutils perl-crypt-rijndael perl-xml-parser libcanberra perl-gtk3-simplelist libwnck3 perl-io-stty perl-io-tty --rebuildtree` when asking about clean build I selected all and also `sudo pacman -Rns $(pacman -Qtdq)` but not sure if that was necessary. maybe try to rebuild asbru too
> > 
> > 
> > Thanks for sharing @bukajsytlos. I followed your steps but it did not work for me. Do you have any other suggestions?
> 
> which one exactly?

I tried this one but it did not work for me.

`yay -S perl vte3 cairo-perl glib-perl pango-perl perl-socket6 perl-expect perl-yaml perl-crypt-cbc perl-crypt-blowfish perl-gtk3 perl-net-arp uuid openssh inetutils perl-crypt-rijndael perl-xml-parser libcanberra perl-gtk3-simplelist libwnck3 perl-io-stty perl-io-tty --rebuildtree`

**Comment by bukajsytlos** [comment]
did you also rebuild asbru itself?

**Comment by dlj2019** [comment]
> did you also rebuild asbru itself?

-Yes i did. Still the same here.

'asbru-cm --verbose'
Can't locate OSSP/uuid.pm in @INC (you may need to install the OSSP::uuid module) (@INC entries checked: /opt/asbru-cm/lib /opt/asbru-cm/lib/ex /opt/asbru-cm/lib/edit /usr/lib/perl5/5.38/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.38/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.38/core_perl /usr/share/perl5/core_perl) at /opt/asbru-cm/lib/PACMain.pm line 44.
BEGIN failed--compilation aborted at /opt/asbru-cm/lib/PACMain.pm line 44.
Compilation failed in require at /usr/bin/asbru-cm line 102.
BEGIN failed--compilation aborted at /usr/bin/asbru-cm line 102.

**Comment by bukajsytlos** [comment]
and you confirmed cleanBuild in prompt?

**Comment by dlj2019** [comment]
> and you confirmed cleanBuild in prompt?

@bukajsytlos. Yes...I've tried everything so far with no success. Unless i am missing something :(

**Comment by dlj2019** [comment]
> @bukajsytlos Thanks. That put me in the right direction. I rebuild the components it was nagging about and after that asbru-cm worked fine again.

@MrHappy Would you mind to share the steps you took in order to work again?

**Comment by MrHappy** [comment]
> > @bukajsytlos Thanks. That put me in the right direction. I rebuild the components it was nagging about and after that asbru-cm worked fine again.
> 
> @MrHappy Would you mind to share the steps you took in order to work again?

I ran yay again for the components the install was complaining about and chose a cleabuild for each of them.
After that I did a clean build of asbru.

**Comment by dlj2019** [comment]
> > and you confirmed cleanBuild in prompt?
> 
> @bukajsytlos. Yes...I've tried everything so far with no success. Unless i am missing something :(
> 
> I would like to say Thank you for your help!

@bukajsytlos Thank you so much again for all your help here. I really appreciate it! " for some reason 3rd time clean build" worked for me. You guys are the best!!!

**Comment by dlj2019** [comment]
> yay -S perl vte3 cairo-perl glib-perl pango-perl perl-socket6 perl-expect perl-yaml perl-crypt-cbc perl-crypt-blowfish perl-gtk3 perl-net-arp uuid openssh inetutils perl-crypt-rijndael perl-xml-parser libcanberra perl-gtk3-simplelist libwnck3 perl-io-stty perl-io-tty --rebuildtree



> > > @bukajsytlos Thanks. That put me in the right direction. I rebuild the components it was nagging about and after that asbru-cm worked fine again.
> > 
> > 
> > @MrHappy Would you mind to share the steps you took in order to work again?
> 
> I ran yay again for the components the install was complaining about and chose a cleabuild for each of them. After that I did a clean build of asbru.

For some reason, 3rd time worked for me! Thank you

**Comment by urosh990** [comment]
I haven't booted Arch for a while, I updated the system as usual. I can confirm that asbru-cm didn't work, but also I can confirm that this worked again: `yay -S glib-perl perl-crypt-rijndael perl-expect perl-net-arp uuid --rebuildall`

**Comment by VAL3v3** [comment]
Can't solve in all the way you report.
The library is always installed for Perl 5.36, but I have perl 5.38 and I am not able to install for it:

```

WARNING: '/usr/lib/perl5/5.36' contains data from at least 4 packages which will NOT be used by the installed perl interpreter.
 -> Run the following command to get a list of affected packages: pacman -Qqo '/usr/lib/perl5/5.36'
╰─>$ pacman -Qqo '/usr/lib/perl5/5.36'
perl-crypt-rijndael
perl-expect
perl-net-arp
uuid
```


Can someone help me?

**Comment by VAL3v3** [comment]
Solved compiling modules from GitHub
