### ISSUE TITLE
$TERMINAL{expect} Not Picking Up Anything

### ISSUE THREAD

**Issue by isaacvonaaron** [asbru-cm/asbru-cm#656]
Hello

I'm trying to write a perl script that would automatically issue "sudo -s" for me. I will then use the script with selected hosts. For that purpose I tried to write a small perl script but it seems that no matter what the case is, $TERMINAL{expect} isn't picking up anything.

**To Reproduce**
Use this code: I originally didn't have the "\n" sent at the beginning. This is just to demonstrate the script's inability to pick up text from the connection. I originally tried to pick up the $ sign with backslash-$ .
sub CONNECTION
{
    # Do things on every started/selected connection
   my $res;
    $TERMINAL{send}("\n");
   $res = $TERMINAL{expect}('thehostname');
    if ( $res ) {
    $TERMINAL{send}("#YAY\n");
	} else {
	    $TERMINAL{send}("# ".$TERMINAL{error}."\n");
	}
    $TERMINAL{send}("sudo -s\n");
    $res = $TERMINAL{expect}("password",0.5);
    $TERMINAL{send}($COMMON{subst}("<PASS>")."\n");

    return 1;
}

**Expected behavior**
The above script should have said "YAY!" but instead it issues the error message.
Instead I get:
[asbru_conn(21608)][thehostname][thehostname - BBL]: SCRIPT_SUB_SEND[NAME:sudo.pl][PID:21608][PARAMS:
                                                                                                 ]
[asbru_conn(21608)][thehostname][thehostname - BBL]: SCRIPT_SUB_EXPECT[NAME:sudo.pl][PID:21608][PARAMS:thehostname, 1]
[iaaron@qb@thehostname ~]$ [asbru_conn(21608)][thehostname][thehostname - BBL]: SCRIPT_SUB_SEND[NAME:sudo.pl][PID:21608][PARAMS:# Timeout (1 seconds) waiting for pattern 'thehostname'
          ]

**Screenshots**
I  have attached output.log
[output.log](https://github.com/asbru-cm/asbru-cm/files/4842159/output.log)

**Environment (please complete the following information):**
 - OS:Ubuntu 20.04
 - Ásbrú Version 6.2.1-1 (from the repo)

**Comment by gfrenoy** [comment]
Issue confirmed.  Thanks for the great report !

The last commit should fix the expect logic.

Can you give it a try by using the "snapshot" branch (see [instructions](https://docs.asbru-cm.net/General/Installation/#ubuntu)) and let us know if it works for you ?

**Comment by isaacvonaaron** [comment]
Worked like a charm...!
However, and I'm not sure if it's like that by design - In case you want to 'expect' the first prompt, you can't because the Perl scripts runs after the prompt is displayed.
So if I want to make sure I'm in a prompt I _have_ to send backslash-n and expect something like the $ prompt, a trick that worked for me very nicely.

Thank you very much for the help!

**Comment by gfrenoy** [comment]
Thanks for the additional test and confirmation :)

On my environment, I tried both (with and without `\n`) and it was able to catch it in both cases.

That being said, the script is executed after we have reached the "CONNECTED" status.  And this status is only reached if we have matched the `COMMAND PROMPT` (see [docs](https://docs.asbru-cm.net/Manual/Preferences/MOAdvanced/)) so I would think you don't need that expect in your custom script...
