### ISSUE TITLE
SSH cannot log in when .bashrc asks for user input

### ISSUE THREAD

**Issue by Silex** [asbru-cm/asbru-cm#657]
**Describe the bug**

Whenever we want to log in to a box that asks for user input in its .bashrc we cannot login. Entering user input works but it's not forwarded to the real SSH session. I guess it waits to receive a "valid terminal" before connecting the user input. Could not find a way to make it work.

**Screenshots**

![Screenshot from 2020-06-29 15-25-05](https://user-images.githubusercontent.com/16015/86011490-0772bf80-ba1d-11ea-82a6-b4eb122d7356.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Ásbrú Version 6.2.1

**Comment by gfrenoy** [comment]
Yes it waits for the "command prompt" ; you can tweak the value of what is expected in the "Command Prompt" settings in `Preferences` > `Main Options` > `Advanced` > `Command Prompt`.

**Comment by Silex** [comment]
Thanks!
