### ISSUE TITLE
changing password in bulk/batch-job

### ISSUE THREAD

**Issue by trueshanti** [asbru-cm/asbru-cm#658]
I have some hundred ssh-connections stored in asbru , and am looking for an easy way to bulk-change passwords in the config ..

i am pretty lame when it comes to perl-storage, so my only way is to change them one-by-one
i would love to see some bulk-password-changer (CLI or gui)

thanks for considering
br
-c-

**Comment by vibo69** [comment]
use global variables for that. works for me ;) (<GV:...>)

**Comment by gfrenoy** [comment]
If you right-click on a folder or on a multi-selection and select `Bulk Edit Connections` ; you should be able to mass change them:

![image](https://user-images.githubusercontent.com/981546/86490564-1b455b00-bd68-11ea-8552-9c29a3351e69.png)

(note: don't forget to have a safe copy of your configuration files before experimenting this feature).

That being said, using variables is probably a good idea :)
