### ISSUE TITLE
Add support for bionic

### ISSUE THREAD

**Issue by jkwedar** [asbru-cm/asbru-cm#66]
Can we add support for bionic in the script downloaded? I follow the steps on the summary for daily build on Bionic/Ubuntu and if fails because it creates the sourcelist file with bionic and there is no tag for bionic on packagecloud.io/asbru-cm so it fails when doing the "sudo apt install asbru-cm".

Work around is to put "artful" for the sourcelist and "sudo apt update && sudo apt install asbru-cm"

```
# cat asbru-cm_asbru-cm.list 
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/asbru-cm/asbru-cm

deb https://packagecloud.io/asbru-cm/asbru-cm/ubuntu/ artful main
deb-src https://packagecloud.io/asbru-cm/asbru-cm/ubuntu/ artful main
```

```
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu Bionic Beaver (development branch)"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Bionic Beaver (development branch)"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by gfrenoy** [comment]
Bionic is not yet supported by [packpack](https://github.com/packpack/packpack) so we are currently unable to build Ásbrú for this platform.

As Bionic release is only [foreseen](https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule) for April 26th, I believe we can keep this workaround until then...

**Comment by jkwedar** [comment]
Agreed, just noticed it and thought i would add it for when it does. Work around works fine.

**Comment by KlaasT** [comment]
We've just added a bionic build to our snapshots repository. Please let us know if this works for you:

https://packagecloud.io/asbru-cm/snapshots/install

**Comment by KlaasT** [comment]
At the moment bionic is only available on the snapshot repository which is based on the master.

You can find the install instructions here: https://packagecloud.io/asbru-cm/snapshots/install

**Comment by garyx** [comment]
I was trying to install Asbru using the snapshot but it fails. 

sudo apt install asbru-cm
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 asbru-cm : Depends: libgnome2-vte-perl but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by gfrenoy** [comment]
We just uploaded the [libgnome2-vte-perl](https://packagecloud.io/asbru-cm/asbru-cm/packages/ubuntu/bionic/libgnome2-vte-perl_0.11-1_amd64.deb) package for bionic on the asbru-cm repository.  So you'll need to add both snapshots and asbru-cm repos and it should now work fine.

**Comment by gfrenoy** [comment]
Since release of [5.1](https://github.com/asbru-cm/asbru-cm/releases/tag/5.1.0), Ásbrú CM can be installed on Ubuntu Bionic from the main repository.
