### ISSUE TITLE
Close All terminals doesn't work

### ISSUE THREAD

**Issue by ferent** [asbru-cm/asbru-cm#660]
Basically, when multiple tabs open and hitting right click with the mouse over one of the opened tabs and select Close All terminals, I select Ok in the confirmation window and it doesn't close any of them. 

I have "Put Terminal TABS in main window" option selected and organized on the right of the window.

**Comment by gfrenoy** [comment]
Thanks for the report !  The issue has been fixed on the loki branch.

Let us know if this works for you.

**Comment by ferent** [comment]
it works perfectly fine now, Thanks!!
