### ISSUE TITLE
Linux Mint 20 Support - PackageCloud

### ISSUE THREAD

**Issue by m8** [asbru-cm/asbru-cm#663]
Hi, according to latest release I could not see Linux Mint 20 Ulyana. When I tried to download from packege cloud I get this error. 
```bash
Unable to download repo config from: https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/config_file.list?os=LinuxMint&dist=ulyana&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.
```
Now I'm using from source code. However, it would be nice if you can add Ulyana to packagecloud. Thanks

**Comment by gfrenoy** [comment]
Thanks for the heads up.

linuxmint/ulyana is not yet supported by packagecould.io ; I sent them a short message to add it ; whenever it is done, I'll add it to our automated build.

**Comment by m8** [comment]
good news thanks!

**Comment by gfrenoy** [comment]
Strangely enough, packagecloud did not do anything yet.  In the past they were quite reactive on this :-/

To increase the priority of this request, can someone else ask them when they will support LinuxMint 20 ?

**Comment by stefanocog** [comment]
But latest version is compatible with Mint 20? I would like to update from 19.3 but I don't know if the current version works on Mint 20

**Comment by jim-p** [comment]
It works fine for me on Mint 20. Probably not the greatest idea but I setup packagecloud by telling it I was on ubuntu/focal

**Comment by m8** [comment]
There is no problem with Mint 20, we're waiting to packagecloud to add Linux Mint. you can use directly from source code or it can be done as @jim-p done.

**Comment by lenr9** [comment]
Hey jim-p, I'm sure I am missing something obvious, can you please explain how you "setup packagecloud by telling it I was on ubuntu/focal" ?

**Comment by jim-p** [comment]
> Hey jim-p, I'm sure I am missing something obvious, can you please explain how you "setup packagecloud by telling it I was on ubuntu/focal" ?

Download the install script and run it with the os and dist variables set in the environment, like so:

`env os=ubuntu dist=focal ./script.sh`

**Comment by lenr9** [comment]
Worked great, thanks for the help.

**Comment by gfrenoy** [comment]
Checked this morning and the tag is still not created.  This is really worrisome for the future of packagecloud :-/

**Comment by KlaasT** [comment]
As packagecloud still didn't add the Linux Mint 20 tag I searched for some alternatives and created a repository at Cloudsmith which supports Mint 20.

You can find the instructions here. https://cloudsmith.io/~asbru-cm/repos/snapshots/setup/#formats-deb

**Comment by gfrenoy** [comment]
Packagecloud is definitely not answering our requests anymore ; our packages are now available on [cloudsmith](https://cloudsmith.com/).

Since the release of 6.2.2, Ásbrú stable release can be installed on Linux Mint 20 using the following:

```
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
sudo apt install asbru-cm
```
