### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Silex** [asbru-cm/asbru-cm#665]
Hello,

The wiki at https://github.com/asbru-cm/asbru-cm/wiki/Tips-and-Tricks mentions `.config/pac/pac.yml`, but it looks like this is now `.config/asbru/asbru.yml`.

Also, should we use this file or right click the connections root and select "Export"? The contents for the hosts are slightly different.

**Comment by gfrenoy** [comment]
> The wiki at https://github.com/asbru-cm/asbru-cm/wiki/Tips-and-Tricks mentions .config/pac/pac.yml, but it looks like this is now .config/asbru/asbru.yml.

Thanks !  This is updated now.

> Also, should we use this file or right click the connections root and select "Export"? The contents for the hosts are slightly different.

That export file only contains the data about your connections but not the other options (preferences).

**Comment by Silex** [comment]
@gfrenoy: thanks! By the way, when I edit this file and then run asbru my changes are overwritten. How do I edit this file?

**Comment by gfrenoy** [comment]
> when I edit this file and then run asbru my changes are overwritten. How do I edit this file?

I guess "this file" means `asbru.yml` ?

In that case, there's indeed a trick : Ásbrú first load a cache copy (`asbru.dumper`) and if it does not find it ; will load `asbru.yml` (and your latest changes).

So whenever you change `asbru.yml`, you'll need to delete `asbru.dumper` to make sure `asbru.yml` is loaded properly.

**Comment by Silex** [comment]
Thanks!

**Comment by gfrenoy** [comment]
Oh wait, it's `asbru.nfreeze` that is the cache file; .dumper is only an export.

**Comment by Silex** [comment]
@gfrenoy: FYI there are still references to pac.yml at https://github.com/asbru-cm/asbru-cm/blob/master/doc/General/sensitive-info-notice.md

I guess you can grep for pac.yml and find all references.

I also noticed a typo here: https://docs.asbru-cm.net/Manual/Preferences/KeePassXC/

`This new integration brakes compatibility` -> `This new integration breaks compatibility`

Sorry no time to make PR cause I'm soon on holidays.

By the way, how are passwords encrypted? It looks like base64 but it isn't. Couldn't quickly find in the source, if you know from the top of your head it'd be a good head start (I'm generating asbru configs from another source).

**Comment by gfrenoy** [comment]
Thanks for the improvement suggestions, I'll fix that.

> By the way, how are passwords encrypted?

Check `_chipherCFG` :

https://github.com/asbru-cm/asbru-cm/blob/4f058d08811f0ef57c746f8ccedc3f55d24ba4bd/lib/PACUtils.pm#L2678-L2718

and `_decipherCFG`.

It is using a [Crypt::CBC](https://metacpan.org/pod/Crypt::CBC) with hardcoded keys / salt.

See also how `$CIPHER` is created:

https://github.com/asbru-cm/asbru-cm/blob/4f058d08811f0ef57c746f8ccedc3f55d24ba4bd/lib/PACUtils.pm#L143

Not secure at all, actually, so the recommendation is to use a KeyPass database to store your passwords.

**Comment by Silex** [comment]
Thanks! :+1:
