### ISSUE TITLE
Copy Node Password doesn't work

### ISSUE THREAD

**Issue by octaviofilipepereira** [asbru-cm/asbru-cm#666]
**Describe the bug**
Copy Node Password doesn't work.
Nothing is copied.

**Environment (please complete the following information):**
 - OS: Linux Mint 19.3 Tricia
 - Ásbrú v6.2.2

**Comment by gfrenoy** [comment]
Can you check #664, it looks like the same issue.  And https://github.com/asbru-cm/asbru-cm/commit/78d2e82ac7e2536f9f5fe1ce99f876b23066efa9 should have fixed it.

6.2.2 is not released yet, are you using the git version ?  Did you pull the latest changes ?

**Comment by octaviofilipepereira** [comment]
Hi!

I use Ásbrú apt sources list:

*asbru-cm_asbru-cm.list
*deb https://packagecloud.io/asbru-cm/asbru-cm/linuxmint/ tina main
deb-src https://packagecloud.io/asbru-cm/asbru-cm/linuxmint/ tina main*
*

*asbru-cm_snapshots.list*
deb https://packagecloud.io/asbru-cm/snapshots/linuxmint/ tina main
deb-src https://packagecloud.io/asbru-cm/snapshots/linuxmint/ tina main

And yes i use 6.2.2 version (screenshot attach).

Regarding the issue #664 
<https://github.com/asbru-cm/asbru-cm/issues/664>, yes it's similar and 
i think the patch 78d2e82 
<https://github.com/asbru-cm/asbru-cm/commit/78d2e82ac7e2536f9f5fe1ce99f876b23066efa9> 
will solve the problem.

Maybe this patch isn't available in apt sources list yet.

Regards,

Octávio Filipe Gonçalves

**Comment by gfrenoy** [comment]
Ah OK, you're using the `snapshots` repository.  So there are several releases with the same version number.

Did you update it recently ?

Can you check you have `6.2.2~1594113620-1` installed ?  (you can use `apt show asbru-cm` to see this).

**Comment by octaviofilipepereira** [comment]
Hi!

Yes i've update Ásbrú. I can't remember exactly, but i think was last 
Monday.

Version: 6.2.2~1594113613-1

Well, my version is lower then yours.
I just run apt to get a new upgrade, but i don't have a new release 
available, at this moment.

Seems to me, the better is wait for the new release deployed in 
snapshots source :-)

Regards,

Octávio Filipe Gonçalves

**Comment by gfrenoy** [comment]
> Version: 6.2.2~1594113613-1

This is a package for Tina but anyway, this is the latest one.

I tried again here with this version but it works fine for me.  Could you explain again what you do exactly ?  I mean: the detailed steps of what is not working for you...?
