### ISSUE TITLE
Right click menu not working

### ISSUE THREAD

**Issue by Brishen** [asbru-cm/asbru-cm#668]
**Describe the bug**
The right click menu for the terminal will not open when a remote command is defined

**To Reproduce**
1. Add a remote command to either global or to a specific connection
2. Start the connection to a remote computer or start a local shell
3. Attempt to right click inside the terminal on a remote or local shell

**Expected behavior**
The menu should show up.

**Environment (please complete the following information):**
Manjaro i3
asbru-cm 6.2.2 installed from AUR on 7/9/20

**Comment by gfrenoy** [comment]
Sorry, I cannot reproduce this one.  I tried with the remote command `ls -la` and the menu shows up correctly.

A few questions to troubleshoot this further:
- Did you have the same issue (or not) with a previous version ?
- When started from the command line (`asbru-cm`), do you see any error message ?
- Is there any special character in your command ?
- Can you try with a new configuration file (eg: `asbru-cm --config-dir=/tmp/asbru`) ?
