### ISSUE TITLE
Add a option to stop cursor blinking

### ISSUE THREAD

**Issue by ltwell** [asbru-cm/asbru-cm#669]

**Comment by gfrenoy** [comment]
Ásbrú is using the global GNOME setting:

![image](https://user-images.githubusercontent.com/981546/87150656-ca2aef00-c2b2-11ea-8af8-a1b451207f99.png)

See also https://help.gnome.org/users/gnome-help/stable/keyboard-cursor-blink.html.en

**Comment by ltwell** [comment]
Thank you I got it
