### ISSUE TITLE
Add support for the "jump host" functionality of SSH

### ISSUE THREAD

**Issue by Cris70** [asbru-cm/asbru-cm#67]
Hi, it would be very nice to have a straightforward way to use the "jump host" (option -J) functionality of SSH.

I'm attaching a screenshot of the way it is implemented (GUI-wise) in MobaXterm, it may be an inspiration for how to model it in Asbrù.

![screenshot_20180319_120431](https://user-images.githubusercontent.com/5107224/37594175-c2978b54-2b74-11e8-8d41-50d541b23348.png)

**Comment by gfrenoy** [comment]
Is there any requirement to be able to use that "-J" option ?  I mean: I don't see that option in my SSH (Ubuntu 16.04):
`ssh -v`
`    usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]`

**Comment by Cris70** [comment]
Which version of ssh?
I'm on openSUSE Tumbleweed here and I have it:

```
cris@PolariSuse [~]$ ssh -V
OpenSSH_7.6p1, OpenSSL 1.1.0g-fips  2 Nov 2017
```

```
cris@PolariSuse [~]$ ssh
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-J [user@]host[:port]] [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port] [-Q query_option] [-R address]
           [-S ctl_path] [-W host:port] [-w local_tun[:remote_tun]]
           [user@]hostname [command]
```

**Comment by gfrenoy** [comment]
Looks like Bionic will be very welcome :)

    $ ssh -V
    OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016

Apparently it is available since v7.3 (see [here](http://www.openssh.com/txt/release-7.3)).

Anyway, it just means we probably need to check for ssh version and do something different for v7.2 and below (see [here](https://en.wikibooks.org/wiki/OpenSSH%2FCookbook%2FProxies_and_Jump_Hosts).

**Comment by Cris70** [comment]
Thank you @gfrenoy , it would be very useful it this could be implemented!

**Comment by ValdikSS** [comment]
On older OpenSSH versions it could be emulated using `ProxyCommand`

**Comment by jucajuca** [comment]
I agree that having ssh hops would be nice.
@Cris70 have you tried to add the options in the host  field? I have a connection that requires an special option "IdentitiesOnly=yes" I tried using it like this and it worked:

host:
-o IdentitiesOnly=yes our.domain.com

**Comment by gfrenoy** [comment]
For sure we need to add this option !  Any contribution will be warmly welcome (on the gtk3 branch, please).

In the meantime, you can also use the "Generic Command" method.  Not very nice but it should work.

**Comment by Cris70** [comment]
> @Cris70 have you tried to add the options in the host field? I have a connection that requires an special option "IdentitiesOnly=yes" I tried using it like this and it worked:

Unfortunately I don't have Asbru-CM installed anymore, so I cannot test.

@gfrenoy would it be possible to have a package for openSUSE Tumbleweed too? An appimage would also be welcome. Should I open a separate issue?

**Comment by gfrenoy** [comment]
With the latest "loki" build, I was able to successfully use the "Jump" option in Ásbrú !

![image](https://user-images.githubusercontent.com/981546/71777928-6b08bc80-2fa7-11ea-8786-118a6ec0245b.png)

That's really a great improvement since the configuration of such jumps can be really cumbersome and this option really simplifies 

Thanks a lot @hansr :-)

I guess we need more testers and "polish" this a little bit the most difficult part of the job seems to be behind us.

What I saw while testing:
- we'll need to review all tooltips to make sure they given the appropriate description
- width of the port field should be increased
- when no private key is selected
- when using a jump host, the SSH tunnels options are ignored
- it always use the field ```Private Key``` > ```User``` in ```Connection Details``` for the connection to main host ; especially if that field is empty, it will fail ; I believe we should check if ```User / Password``` is checked and use that if given (with ```PreferredAuthentications``` to ```password```)
- As we are using the -F option of ssh, the system-wide file will be ignored ; either we just document this or maybe we can try to include them in the on-fly-generated config file ?

**Comment by KlaasT** [comment]
Thanks for that feature. I was not able to test it yet but do we have some kind of tip or information which informs the user if the OpenSSH version is too old for using this feature?

**Comment by hanspr** [comment]
I was not included in this thread so I'm recently reading all this.

I really do not know if you can open more tunnels with jump host if it already a tunnel, but if you can create the command line and test that it works, we can implemented.

> it always use the field Private Key > User in Connection Details for the connection to main host 

You have to, jump host works with password less connections.

>As we are using the -F option of ssh, the system-wide file will be ignored.

I could read that file and add it at the top.

> (Klaas) disable option (or have a fallback?) for older version of SSH

Guess could do something similar to what I did with the Keepass implementation, but I would not know the version of the server side, that one could be the old one and not the local one.

Will check during the weekend and see what I can add

**Comment by gfrenoy** [comment]
> I really do not know if you can open more tunnels with jump host if it already a tunnel

Yes, it works...

> but if you can create the command line and test that it works, we can implemented.

We should should just use the "options" parameters of the connection ; like you would do without the Jump option.

I'll give it a try...Check the next commit.

**Comment by hanspr** [comment]
> Once selected, it's not possible to remove the private key. Is a "clear" button needed or is there any other trick to clear that field ?

This has already been fixed on #357

This can be closed.

**Comment by gfrenoy** [comment]
Found a few more glitches (see list above) ; will work on it now.

**Comment by gfrenoy** [comment]
Do we support "multiple jumps" ?

I tried but it's a bit complicated ; we need to end up with the following command line:

```
ssh -p TARGET_PORT TARGET_USER@TARGET_HOST -J JUMP_HOST_A_USER@JUMP_HOST_A:JUMP_HOST_A_PORT,JUMP_HOST_B_USER@JUMP_HOST_B:JUMP_HOST_B_PORT
```

Unless you one has a quick idea to do this, let's leave this for a later version...

**Comment by hanspr** [comment]
No multi jump, would require a redisign of the jump configuration, that now is shared with the rdp/vnc configuration.

If someone has that need, it it would be easier to setup the whole thing inside his ssh/config, and just use the name of that config name in the host configuration.

**Comment by gfrenoy** [comment]
> If someone has that need,

I do have this case :)

>  it it would be easier to setup the whole thing inside his ssh/config

No, you just create a tunnel "manually".  This is what I'm doing for years for many connections that are behind firewalls/gateways but that new "jump hosts" feature makes it so easy !  Now I want more :-)

But I do agree, it will require some more rework, let's keep this for later.  I create an issue so we don't forget it.

Beside that, I think we can close this one ; it all works very well :)
