### ISSUE TITLE
Ubuntu 20.04  setenv()/putenv() are not thread-safe alert

### ISSUE THREAD

**Issue by ltwell** [asbru-cm/asbru-cm#670]
**Describe the bug**
setenv()/putenv() are not thread-safe alert
**To Reproduce**
3. See error

open new session can produce alert as 

GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 19.04, Fedora 31 or Arch]
 - Ásbrú Version [e.g. 6.1.1 or 6.2.0 or loki]

**Additional context**

**Comment by gfrenoy** [comment]
See #432
