### ISSUE TITLE
[Solved] SSH-Connection / Load key - invalid format

### ISSUE THREAD

**Issue by torstenzenk** [asbru-cm/asbru-cm#671]
**Describe the bug**
Under "Edit Connection > Connection > Connection Details > Private Key >Private Key file" i select a name.ppk file **_that works perfectly_** in putty on Debian. 
The output in Asbru-cm is:
`Load key "/home/myusername/files/name.ppk": invalid format`:

Renaming the file to just name throws the same message:
`Load key "/home/myusername/files/name": invalid format`

ls -la in that folder:
drwxr-xr-x  2 myusername.myusername  4096 Jul 14 21:51 .
drwxr-xr-x 30 myusername.myusername  4096 Jul 14 13:40 ..
-rwx------  1 myusername.myusername         1482 Jul 14 21:51 name
-rwx------  1 myusername.myusername  1482 Okt 27  2018 name.ppk

**To Reproduce**
0. Make SSH Connection
1. Go to '..Edit Connection > Connection > Connection Details > Private Key >Private Key file.'
2. Add a keyfile > Click on 'Save and Close.'
3. Choose that connection and connect
3. See error

**Expected behavior**
Smooth login as in putty:

<login as: myusername
Authenticating with public key: rsa-key-20181027
Passphrase for key "rsa-key-20181027": 
servername:$>

**Screenshots**

**Environment (please complete the following information):**
 - Client OS: Debian GNU/Linux 10 (buster)

  - Ásbrú Version 
Ásbrú Connection Manager 6.2.1 (asbru-cm) started with PID 13275
INFO: Desktop environment detected : xfce
INFO: Config directory is '/home/myusername/.config/asbru'
INFO: Used config file '/home/myusername/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.54
INFO: Theme directory is '/opt/asbru/res/themes/default'

**Additional context**
this happens on all my external servers where i can ssh to with putty without any problem.
I have to say the the ssh-servers only accept auth with publickey. Anything else is permitted.

**Comment by gfrenoy** [comment]
> Load key "/home/myusername/files/name.ppk": invalid format

Ásbrú is based on `openssh` that does not support the PuTTY native format (ppk) ; you should first convert your public key to the format defined by [RFC 4716](https://tools.ietf.org/html/rfc4716#section-3) ; this can be done using _PuTTY Key Generator_ and the option _Conversions_ > _Export OpenSSH key_

Further references about this:
- https://the.earth.li/~sgtatham/putty/0.69/htmldoc/Chapter8.html#puttygen-conversions
- https://stackoverflow.com/a/44391850

**Comment by torstenzenk** [comment]
Yes!!! That was it. 

For the possibility that others coming from putty on Linux or Windows:
What i had to do:
1. Use PUTTYgen as described above and save the new file as openssh.key
2. sudo chmod 700 openssh.key
3. Edited the connection and introduced the new file > Save > Connect 

Again thanks for your very fast and good help. And thanks forthis great tool!
