### ISSUE TITLE
Show/hide button for side pane (MyConnections etc.)

### ISSUE THREAD

**Issue by skipperTux** [asbru-cm/asbru-cm#675]
**Is your feature request related to a problem? Please describe.**
When working a lot in remote machines (SSH or RDP) embedded in tabs (TabView) it would be great to have more screen space available. Fast switching between machines can be done by switching tabs. TabView is more flexible when switching machines compared to fullscreen or single windows.

**Describe the solution you'd like**
Have a show/hide button for the side pane, same as for the button bar. Click on the show/hide button to fold or unfold the side pane (MyConnections etc.); see screen mockup below. Might be related to #659

**Describe alternatives you've considered**
Making the splitter smaller: not really an alternative, as it is cumbersome and the side pane has a min-size constraint.

**Additional context**
![asbru-show-hide-sidebar-mock](https://user-images.githubusercontent.com/3322442/88956866-4dca7100-d29e-11ea-8bce-a94f03f87bdc.png)

**Comment by gfrenoy** [comment]
There is already such a button, isn't it ?

![image](https://user-images.githubusercontent.com/981546/88961803-d26cbd80-d2a5-11ea-804d-9427bc52a234.png)

You can also use the `Alt+n` shortcut key.

**Comment by skipperTux** [comment]
Stupid me, using Ásbrú (PACMan) for years now and missed the obvious. Sorry and thanks!
Yes, button is there. However `Alt+n` is not working on my machine. Is this to set in the Preferences? I did not find `Alt+n` when searching this GitHub repository. Is there an Ásbrú keyboard shortcut overview?
Running Fedora 32 and Ásbrú Connection Manager version 6.2.1

**Comment by gfrenoy** [comment]
Indeed, the shortcut key is not yet released (see #649).  Will be available in 6.3.0.
