### ISSUE TITLE
Fixed black font color of connections names causes issues with dark system themes

### ISSUE THREAD

**Issue by doman18** [asbru-cm/asbru-cm#676]
Im using black theme in Kubuntu. Black font color of connections causes them to be unreadable on dark background. I see that  other fonts on other panels are white so i assume that only that one is fixed and the rest is inherited from OS.

![image](https://user-images.githubusercontent.com/25553932/89014399-c3255880-d315-11ea-92ef-9204d7b1382b.png)

**Comment by gfrenoy** [comment]
Can you check #640 and see if it helps ?

**Comment by yderi** [comment]
Hello all

Recently using Asbru 6.3.2. Ubuntu Mate 20.04.2 LTS, Dark Theme used.
The problem still persists.

**Comment by gfrenoy** [comment]
Yes, this issue should be addressed in #640 that is still open.
