### ISSUE TITLE
Remove unimplemented option "Check port status at connect"

### ISSUE THREAD

**Issue by syco** [asbru-cm/asbru-cm#677]
Hi,
I'm working on a new functionality (I'll give more info on that when it's tested and working).
So I was looking to see how "Check port status at connect" is implemented and I can't find it anywhere.
Unless I missed something I think that checkbox doesn't do anything..
What do you think??

**Comment by gfrenoy** [comment]
Doesn't look to be used anywhere, you're right.  In the configuration, it is named `ping port before connect` but it is never used (even in v5 / gtk2)...

I think we can safely remove it (or do something with it...).

**Comment by syco** [comment]
I would say remove it.. all connection types already manage their own timeouts..
And I guess this question can be closed as well.
Thanks for confirming I'm not blind

**Comment by gfrenoy** [comment]
Code cleaned up in https://github.com/asbru-cm/asbru-cm/commit/4e14cda5f236cc4d3261cb208a7f607d7f21e8f6
