### ISSUE TITLE
Option for cluster to open each connection in their own window

### ISSUE THREAD

**Issue by stderr-to-devnull** [asbru-cm/asbru-cm#679]
**Is your feature request related to a problem? Please describe.**
As I understand, it is not so easy to do: https://github.com/asbru-cm/asbru-cm/issues/419 / https://github.com/asbru-cm/asbru-cm/issues/17 but maybe we can have the next best thing? Right now I can drag each tab and upon release they transform into their own window.

**Describe the solution you'd like**
A simple check box on each cluster config page that would allow all sessions from that cluster to be opened in their own independent window, much like how CSSH works.

**Describe alternatives you've considered**
N/A

**Additional context**
Check CSSH

**Comment by stderr-to-devnull** [comment]
I just discovered the powerful features of Power Cluster Controller. It does exactly what I needed, unfortunately the features and usefulness are not documented in detail. I will make some time to contribute with documentation.

**Comment by gfrenoy** [comment]
>  I will make some time to contribute with documentation.

That would be great !  Documentation can be found here --> https://github.com/asbru-cm/asbru-cm/tree/master/doc and you can find a short "starting guide" here --> https://github.com/asbru-cm/asbru-cm/issues/430#issuecomment-599817592

Thanks :)

And should we close this issue then ?

**Comment by stderr-to-devnull** [comment]
Yes, closing and will make time to document. Thank you!
