### ISSUE TITLE
Old pac bugs are also present in asbru-cm

### ISSUE THREAD

**Issue by nugzarg** [asbru-cm/asbru-cm#68]
https://sourceforge.net/p/pacmanager/bugs/160/
https://sourceforge.net/p/pacmanager/bugs/197/

**Comment by gfrenoy** [comment]
Thanks for the feedback nugzarg !  Would you mind creating one issue per bug and copy/paste title and bug description to github ?  This may look like a detail but it really helps the one who would like to look at the issue... Thanks !

**Comment by gfrenoy** [comment]
Split topics.
