### ISSUE TITLE
Cluster session detach/re-attach toggle

### ISSUE THREAD

**Issue by stderr-to-devnull** [asbru-cm/asbru-cm#680]
**Is your feature request related to a problem? Please describe.**
Sometimes after opening a cluster, I want to try out a command / do some preliminary tests on one of the sessions, then issue the command(s) on the (other) clustered sessions, including the one used for tests or not. This is easy to do with CSSH, typing in a session window will not send command to the others.

**Describe the solution you'd like**
A cluster detach/re-attach toggle button available for clustered sessions (bottom bar, only toggle-able for that type of sessions, otherwise greyed out) that allows a specific session to detach from the cluster so that commands entered there will not be sent to the others (until re-attach toggle is pressed). Also, when detached toggle is pressed, indicate this on session tab/window like color or * char etc.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hanspr** [comment]
Just in case, the functionality currently exists

__To detach__
* Alt+Ctrl+c
* Or right click on window and select detach

__To reatach__
Because Asbru allows to have multiple clusters running, you have to
* Right click on terminal select the cluster where you want to retach to
