### ISSUE TITLE
Prepend command for xfreerdp

### ISSUE THREAD

**Issue by reddare** [asbru-cm/asbru-cm#681]
**Describe the bug**
When using `SSH -L` in prepend command `xfreerdp` cannot start.

**To Reproduce**
1. Go to `Edit Connection` -> `Connection Details` -> `Method: xfreerdp`, then `Advanced Parameters` -> `Prepend command`   
`ssh -L 9000:192.168.10.10:5432 user@192.168.10.5`

2. Click on `Save and Close`

3. See error in log:   
`bash: xfreerdp: command not found`

**Expected behavior**
1. Start ssh with forwarding
2. Connect with xfreerdp to host

 - OS: Arch
 - Ásbrú Version 6.2.1

**Command line:**
`ssh -L 9000:192.168.10.10:5432 user@192.168.10.5 "xfreerdp /parent-window:98689563 /size:2558x1380  /bpp:24 +clipboard /dynamic-resolution  /cert-tofu /u:'user' /p:'53616c7465645f5f3132333435363738438bb8c08e004b7bbc13ddb837441178' /v:127.0.0.1:3389`

Option `Surround connection command with quotes` did not fix problem.

**Comment by gfrenoy** [comment]
What you describe works "as designed".  The prepend command is correcty set before the `xfreerdp` command.

To say it differently, what is the command _outside_ Ásbrú that you are trying to execute ?

If I understand correctly what you are trying to achieve, you're looking for the "Jump Host" feature, aren't you ?
See article here : https://github.com/asbru-cm/asbru-cm/wiki/Support-of-SSH-Jump-Host

**Comment by reddare** [comment]
Yes, thank you!
