### ISSUE TITLE
How do I select row from a start symbol with hiding connection tree?

### ISSUE THREAD

**Issue by ahtohio** [asbru-cm/asbru-cm#683]
**Is your feature request related to a problem? Please describe.**
Hi! I've set up my connection tree to hide and appear only when mouse moves to the left window border. But with this setup I'm unable to select any row right from the start, because once I move my cursor to the first symbol of the row connection tree appears. I know, I could move tree to the right side, but I prefer left side more.

**Describe the solution you'd like**
I see two pretty good solutions - option to hide tree at all on any tab except Info or first solution + keybinding to force tree to appear.

**Additional context**
Asbru-cm 6.3.0

**Comment by gfrenoy** [comment]
Thanks for your feedback :)

For the option "keybinding", it should should with `Alt+n` (see #649).

About being able to see the connections tree when only the "Info" tab is shown, it looks like a bug to me ... Should be able to fix it soon.

**Comment by gfrenoy** [comment]
Ok so it was not as easy as I had initially thought but I believe the last commit will fix the issue.

For my own records: the `Gtk3::Frame` object is not emitting the `motion_notify` event.  So I had to add an `Gtk3::EventBox` around it (see also [here](https://developer.gnome.org/gtk3/stable/GtkEventBox.html)).

Will you give it a try with the latest loki build and let us know if it works better for you ?

Thanks again for the great feedback.
