### ISSUE TITLE
Installation on Ubuntu 20 not working, couldn't locate package and yaml module missing

### ISSUE THREAD

**Issue by aderchox** [asbru-cm/asbru-cm#686]
**Describe the bug**
Installing using the two lines on the main site, I get these messages(first one is a success, second line gives an error):
```
The repository is setup! You can now install packages.
user@host:~$ sudo apt install asbru-cm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package asbru-cm
```

Installing from source, ./asbru-cm gives this:
```
Can't locate YAML.pm in @INC (you may need to install the YAML module) (@INC contains: /home/user/Downloads/asbru-cm-6.2.1Downloads/asbru-cm-6.2.1/lib/ex /home/user/Downloads/asbru-cm-6.2.1/lib/edit /etc/perl /usr/local/lib/x86_64-linux-gnu/pershare/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.te_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./asbru-cm line 92.
BEGIN failed--compilation aborted at ./asbru-cm line 92.
```
I'm not sure what YAML module I'm missing? 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Ásbrú Version 6.2.1

**Comment by gfrenoy** [comment]
1) Installation on Ubuntu 20.04 is known to work so I would guess the "two lines install" did not work for some reason.  Can you share the output that you see if you try to set it up again ?

2) To install from sources, you'll need to install the dependencies manually.  See our [manual installation instructions](https://github.com/asbru-cm/asbru-cm/wiki/Manual-installation) for details.
