### ISSUE TITLE
Improve Terminal Split-View Mechanic

### ISSUE THREAD

**Issue by m-neero** [asbru-cm/asbru-cm#689]
Currently I really can't find a way to work with multiple (more than two) ssh sessions at once using asbru.

Is there a way to have more than two sessions split and active at once in asbru?

I'm coming from GCM (Gnome-Connection-Manager) where this is a really great feature. Looks (for example) like this:
![gcm](https://user-images.githubusercontent.com/56535208/93577775-c0052b00-f99c-11ea-9714-f246475a39d8.png)

Notice also the separate Tabs for each Split-View.
With an active Tab you are able to simply move it into a new View with the buttons at the top. Vertically or horizontally.

Would something similar for Asbru be possible?

**Comment by gfrenoy** [comment]
Except the horizontal or vertical split, there is nothing "out of the box" in Ásbrú to arrange terminals.  This is old request that is not really easy to implement, see #17.  Let me close this for now and continue discussion in #17.
