### ISSUE TITLE
Prompt login with PS3 is not possible

### ISSUE THREAD

**Issue by raknerak** [asbru-cm/asbru-cm#690]
I had added some selection point for exporting profiles purpose in .bash_profile with PS3 which is expecting input from the user. 
When I select right option, connection cannot be established in Asbru. However, it is working with SecureCRT or standard linux terminal.

.bash_profile input can be something like below:

![image](https://user-images.githubusercontent.com/7880734/93715578-f09ebd80-fb72-11ea-98fe-893ef7371ad4.png)

When I select 1 and press enter; terminal is hanged and I cannot login.

![image](https://user-images.githubusercontent.com/7880734/93715650-42474800-fb73-11ea-810b-901ea6f982e9.png)

You can test and generate this issue with adding below entry at the end of any user's bash_profile:

PS3="respond with hello: "
    select i in "Hello"
    do
      case $i in
              "Hello") echo "Hello user: ${USER}"; break;;
      esac
      break
    done

**Comment by gfrenoy** [comment]
How Ásbrú is working today is that we expect a given password and login prompt that is described in `Preferences` > `Main Options` > `Advanced`:

![image](https://user-images.githubusercontent.com/981546/94745802-b0fa8180-037b-11eb-9058-97e5eb60bc77.png)

If you tweak this to you prompt, it should work fine.

Now, we might need to think about a way to still accept user input if we don't match any of the expected prompt.

Any suggestion for an option or a way to manage this will be warmly welcome.

**Comment by raknerak** [comment]
Hi Frenoy,

I didn't understand how to configure it. Can you please provide more explanation on this? Actually, I was expecting to enter manual reply to option w/ PS3 use case. Let's say I have two different applications and it has 2 different environment variables and when  I make ssh I was expecting to get reply to source requested application profile before entering bash shell environment.

BR,
Ahmet

**Comment by gfrenoy** [comment]
Ásbrú will consider the terminal as "connected" and accept input if it finds a match for the "Command prompt" regular expression.  So you may want to try to use one of the characters in that expression in your question.

In your example, you can try the following for `Command Prompt`:
```
hello: $
```
This means that whenever we encounter `hello: ` at the end of a line, it means the terminal is connected and waiting for input.

Doing so, no other kind of "standard" prompt would work so you'll may want to add it to the standard value, 
```
[#%\$>]|\:\/\s*$|hello: $
```

**Comment by raknerak** [comment]
Hi Frenoy; 

It is working with single selection however, in multiple case scenario it does not work because it is automatically responding with 1. My requirement is sourcing different profiles according to user's selection during login operation. I hope, I could able to explain it. There is no problem with doing ssh from standard linux terminal or SecureCRT.


PS3="respond with hello: "
select i in "app1 app2"
do
case $i in
"app1")  source .app1_profile break;;
"app2")  source .app2_profile break;;
esac
break
done

**Comment by gfrenoy** [comment]
Please read again what I wrote above ; if you modify the `Command Prompt` regexp to match your prompt, it should work like you expect it.

As a matter of fact, the proposed regexp works fine with the example you give:
![asbru-login-prompt-example](https://user-images.githubusercontent.com/981546/96299970-21003d00-0ff5-11eb-84cb-9d8accb2a1d0.gif)

What it does is considering `hello: ` as the matching string to start considering user inputs.

**Comment by raknerak** [comment]
Hi Frenoy;

Yes, I did the same and I'm doing it again however, it is sending value "1" automatically. There is no chance to select "2".  I didn't understand the reason. I will try to send a recoding like yours above.
