### ISSUE TITLE
SSH Connections Show Errors

### ISSUE THREAD

**Issue by telemix** [asbru-cm/asbru-cm#691]
When I connect to a server using SSH (I've not tested any other type of connection), the first few lines show this :

![asbru-error-screenshot](https://user-images.githubusercontent.com/16132815/94018431-840d0400-fda8-11ea-9fb7-8ca5723a43cb.png)

Here are the lines pasted : 

GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.

Nothing seems broken during use, so the "errors" might well be benign.

Cannot for the life of me workout how to display the version information, but I downloaded it yesterday so at the time of writing it's the latest version.

**Comment by psyray** [comment]
Same problem for me
`Linux Mint 20 ulyana (Ubuntu 20.04)`
`Asbru v6.2.1`

**Comment by gfrenoy** [comment]
Please check issue #432

**Comment by psyray** [comment]
@gfrenoy 
:+1:
