### ISSUE TITLE
Fingerprint validation fails on new ssh connection

### ISSUE THREAD

**Issue by bitchecker** [asbru-cm/asbru-cm#692]
**Describe the bug**
When you try connect to a new host, firgerprint validation will ask to verify server's key but, when you type `yes` asbru-cm hangs and connection will closed

**To Reproduce**
1. Go to `new connection -> put server parameters for SSH/MOSH connection`
2. Click on `Connect and try to validate fingerprint`
3. See error

**Expected behavior**
After type `yes` to validate server's fingerprint, you should able to login into specified server

**Screenshots**
![image](https://user-images.githubusercontent.com/11056930/94128659-b37c4900-fe5a-11ea-9519-63ed2bd6ce86.png)

**Environment (please complete the following information):**
 - OS: `Fedora 32` && `Ubuntu 19.10`
 - Ásbrú Version: `v6.2.1`

**Comment by psyray** [comment]
Same problem for me
Linux Mint 20 ulyana (Ubuntu 20.04)
As a workaround,  I need to open an SSH connection in the terminal, set yes to fingerprint and connection works fine again in Asbru

**Comment by gfrenoy** [comment]
In `Preferences` > `Main Options`, did you try to check the option "Auto-Accept or delete unknown or offending SSH keys" ?

![image](https://user-images.githubusercontent.com/981546/94743800-43008b00-0378-11eb-9021-83338641a02e.png)

**Comment by bitchecker** [comment]
Yes, already selected.

**Comment by psyray** [comment]
Same for me, already selected
![image](https://user-images.githubusercontent.com/1230954/94779293-fee8a700-03c6-11eb-9011-e5b20526b728.png)

**Comment by gfrenoy** [comment]
Can you check #145 and try with the suggest regex (in https://github.com/asbru-cm/asbru-cm/issues/145#issuecomment-491524424) for Host-key verification ?

**Comment by psyray** [comment]
@gfrenoy 

Working !!!
Thanks ;)
