### ISSUE TITLE
KeePass password asked every time it is required

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#694]
Hi ..
Today, after a system update on EL 8.2, asbru started to ask for the keepassx password each time I try to open a terminal.
This is happening with the last two loki versions (the yesterday one and the previous one released 3 month's ago) and so I think this is not even asbru-cm related. 
But do you have any ideas where I should look at ? I do not see any error/warning messages in the terminal from where I launch asbru nor in the system log. 
So I wonder why this behavior change.
Any help will be welcome. 
Thanks

**Comment by gfrenoy** [comment]
You can maybe try to add some debug info in `testMasterKey' (in https://github.com/asbru-cm/asbru-cm/blob/loki/lib/PACKeePass.pm#L170) ?  And especially what is the value of `$msg` on [line 192](https://github.com/asbru-cm/asbru-cm/blob/loki/lib/PACKeePass.pm#L192) ?

What is does is opening the KeePass file and providing the password to `keepass-cli` ; if there are some warning in the command line, it may think it is not working ...?

**Comment by hanspr** [comment]
Try to run the cli command directly in your local terminal to see if you get any errors from keepass-cli

Replace "mydatabase.kdbx" for the full path to your keepass database

```
keepassxc-cli show mydatabase.kdbx 'server'
```

If there is an error asbru should show a red screen with some sort of message.

What messages and information do you see in the preferences window (does it looks correct?), reselect the file and see if there are any errors or messages in that window. And send the image to see what version of the cli was detected, may be you have a version that works differently. 

![imagen](https://user-images.githubusercontent.com/1572396/95219180-b3653d00-07ba-11eb-90d6-060bfc665a73.png)

```
keepassxc-cli -v
```

**Comment by popxunga** [comment]
> You can maybe try to add some debug info in `testMasterKey' (in https://github.com/asbru-cm/asbru-cm/blob/loki/lib/PACKeePass.pm#L170) ? And especially what is the value of `$msg` on [line 192](https://github.com/asbru-cm/asbru-cm/blob/loki/lib/PACKeePass.pm#L192) ?
> 
> What is does is opening the KeePass file and providing the password to `keepass-cli` ; if there are some warning in the command line, it may think it is not working ...?
Hi ! ...

No warnings in the command line ...
Just added some debug code following your instructions, but the issue that started to occur 2 days ago stopped yesterday (I didn't change my system in this period). So I'm waiting for a new occurrence.

Anyway, the debug message displayed upon the 1st login try, which I guess is normal, is the following:
`DEBUG: MSG= Could not find entry with path ASBRUKeePassXCTEST.`

Thanks.

**Comment by popxunga** [comment]
> Try to run the cli command directly in your local terminal to see if you get any errors from keepass-cli
> 
> Replace "mydatabase.kdbx" for the full path to your keepass database
> 
> ```
> keepassxc-cli show mydatabase.kdbx 'server'
> ```
> 
> If there is an error asbru should show a red screen with some sort of message.
> 
> What messages and information do you see in the preferences window (does it looks correct?), reselect the file and see if there are any errors or messages in that window. And send the image to see what version of the cli was detected, may be you have a version that works differently.
> 
> ![imagen](https://user-images.githubusercontent.com/1572396/95219180-b3653d00-07ba-11eb-90d6-060bfc665a73.png)
> 
> ```
> keepassxc-cli -v
> ```
I didn't see any errors anywhere and that's why I'm a bit lost in this situation.
I'm using keepassxc-cli 2.4.3 (that's the one available on EL8.x currently), building a more recent verion of KeepassXC on EL8.2 is currently a dependencies nightmare.
I've played with it from the command line and it behaves normally; no errors or warnings seen).
Let see if the debug line suggested by gfrenoy helps when the issue arises again.
Thanks.

**Comment by popxunga** [comment]
Hi @gfrenoy & @hanspr 

Just added a print "$msg" and this is what I get written in each terminal I try to open:

```
Gtk-Message: 10:18:44.797: GtkDialog mapped without a transient parent. This is discouraged.
print=Could not find entry with path ASBRUKeePassXCTEST.
```
This is using the latest loki build.

Any ideas ?
Thanks

**Comment by popxunga** [comment]
Humm ... 
I think that I may have figured it out.
The problem occurs with a couple of sessions where I'm using a private key to login.
I've nothing defined on those sessions that needs the keepassxc services (eg getting the ip userid or password).
So I wonder why the keepassxc password dialog is being invoked in these cases.
Once I login into a sessions that get the values from keepassxc, the login into sessions using a private key does not pop up the keepassxc password anymore, unless I change something on Keepassxc ... that that is expected.
Thanks.

**Comment by gfrenoy** [comment]
> GtkDialog mapped without a transient parent. This is discouraged.

This message appears when we display a popup without a parent.  I thought Hans did something to avoid it but looks like there's one more case when it happens.  This would certainly be good candidate to fix the root issue.

> The problem occurs with a couple of sessions where I'm using a private key to login.

Most of my sessions are using a private key to login.  Can you recap how you can reproduce the issue ?

**Comment by popxunga** [comment]
> Most of my sessions are using a private key to login. Can you recap how you can reproduce the issue ?

Sure:

1. Setup Asbru to use Keepassxc (do not store the keepassxc password master key in asbru config);
2. Define an ssh session A that uses Keepassxc to get some some value (url and/or userid and/or password);
3. Define an ssh session B that uses only a private key for login purposes;
4. Save everything and Close Asbru;
5. Start Asbru;
6. Try to login to the previously defined session B on step 3.
7. You will get the password prompt for Keepassxc which isn't required at all to get the B session logged in.

And this is the issue.
Then:

8. Login to session A (you will me prompted for the Keepassxc password).
9. Login to session B (you will not get the Keepassxc password because you successfully logged in to A using Keepassxc).

**Comment by hanspr** [comment]
I can not reproduce, I have plenty of mixed setups like that and it does not fail.

So,

Try to install the latest loky version so we have the same code (we recently merged some code change on this).

This can only happen here : PACTerminal.pm , 310

![imagen](https://user-images.githubusercontent.com/1572396/95682755-aa0a1500-0bac-11eb-9347-3ab60d847724.png)

The line hasKeePassField, is saying that something in your session B looks like a keepass field and requires to ask for the password.

So add a debug line at 311 

print "There is a keepass value?!\n";

And on PACKeePass.pm

Near this sub

Add this debugin lines

```
print "KeePass field detected in : $fieldName -> $$cfg{'environments'}{$uuid}{$fieldName}\n";

print "KeePass field detected in expect : $$exp{'send'}\n";
```

![imagen](https://user-images.githubusercontent.com/1572396/95682967-0457a580-0bae-11eb-924c-ebf3498ada08.png)

Lets see if we have more information.

**Comment by hanspr** [comment]
And just to make sure

In PACKeePass.pm

Add this other debug line, just in case the situation happens during the connection process.

![imagen](https://user-images.githubusercontent.com/1572396/95683140-0706ca80-0baf-11eb-9c77-1f95c254c995.png)


The previous debugin lines would be shown on your asbru-cm execution and this ones would show on your actual connection if it happens during the connection

**Comment by popxunga** [comment]
As I said I'm using the latest loki build publish yesterday (asbru-cm-6.3.0~1602346379-1.el8.noarch.rpm).
None of those debug print produced any output except when I try to establish an ssh session that uses Keepassxc.
When I try to establish an ssh session using a private key, nothing is printed except the 1st debug msg:
`DEBUG: MSG= Could not find entry with path ASBRUKeePassXCTEST.`
Thanks.

**Comment by hanspr** [comment]
@popxunga 

Then I'm completely lost. 

1. I open asbru
2. I execute the ssh session with no keepass configuration, and see __no__ debugin lines as expected. And no password asked.

![imagen](https://user-images.githubusercontent.com/1572396/95690439-6b408300-0bdd-11eb-996f-229e2c474165.png)

3. Close that terminal
4. Open the ssh session with keepass configuration, and see debugin messages, and password asked.

![imagen](https://user-images.githubusercontent.com/1572396/95690454-80b5ad00-0bdd-11eb-8ef6-aa23e336c7f1.png)


You say that you do not see any debugin messages, even in the session with a keepass configuration. So I'm completely lost. Can not figure out where is the code flowing in your session then.

The debug message  `DEBUG: MSG= Could not find entry with path ASBRUKeePassXCTEST.` is irrelevant because is intentionally created to fail.

**Comment by popxunga** [comment]
> You say that you do not see any debugin messages, even in the session with a keepass configuration.

That's not what I wrote.

**Comment by hanspr** [comment]
Do you have time? right now and get a Temviewer meeting?

**Comment by popxunga** [comment]
> Do you have time? right now and get a Temviewer meeting?

Hi Hans ...
Sorry but I'm not allowed to use TeamViewer In the machine were I'm having the issue. Let me prepare a virtual machine in another PC. Then we will try to schedule a session when possible for both.
Thanks a lot !

**Comment by hanspr** [comment]
Could you show me the connection details of the connection that asks the password?

By any chance it has a keepass mask even in a field that is disabled? (like in the user or password or passphrase)
At the time of the connection it will not consider if that method is disabled, it will load KeePass even if disabled.

This would cause to ask for the keepass password needlessly

![imagen](https://user-images.githubusercontent.com/1572396/95691133-78ac3c00-0be2-11eb-8947-9ee2a894d4cb.png)

But it puzzles me that you do not see any debbugin messages, I see them.

**Comment by popxunga** [comment]
Here it is:
The Host field as an ip address and the User/Password fields are empty.
![image](https://user-images.githubusercontent.com/37672088/95691335-546a5280-0c16-11eb-906d-ff58bf99dca7.png)

![image](https://user-images.githubusercontent.com/37672088/95691456-4963f200-0c17-11eb-9337-e27cd9ab05fe.png)

Just found that having the Global Options Network Settings like follows, causes the issue:
![image](https://user-images.githubusercontent.com/37672088/95691597-1b32e200-0c18-11eb-8470-8c0c5cf6a7aa.png)

By removing the proxy credentials from the Global Options Network Settings the problem is gone:

**Comment by hanspr** [comment]
Ok,

Add this debuggin line around this lines (I have already moved my version)

PACUtils.pm

![imagen](https://user-images.githubusercontent.com/1572396/95692441-6e427000-0beb-11eb-9ef9-9ee16f20f3d1.png)

Run the terminal that cases the incurrect kepass password. And check the RET debug lines.

One of them must necessarily have a keepass pattern. It could be coming from any global or connection configuration.

`<[username|password|title]|/path/to/key>`

If there is one, try to check where is it configured.

If it is configured in some global configuration, it would cause the password trigger always. If it is at connection label, then remove it or check why was configured there (example an Expect configuration in that terminal connection)

**Comment by hanspr** [comment]
@popxunga 

`By removing the proxy credentials from the Global Options Network Settings the problem is gone:`

Sorry, it what expected, missed it from your post

So as I mentioned, if you leave a keepassmask in a disabled field it will trigger asking for the password. The problem is that the individual options are not validated inside the KeePass library. It assumes that if it is set it will ask for the password.

**Comment by popxunga** [comment]
Hi @hanspr ....
Thanks for the fix(es) (not yet merged as I can see) which if I understood correctly, will remove any Keepassxc setting from the session or global network options as soon the user disable and save them.
But as per your explanation, I wonder if we could avoid the call to the KeePass lib whenever any Keepass option is set but is disabled, either in the session or in the global network options.
Thanks for you support.

**Comment by popxunga** [comment]
Hi @gfrenoy  + @hanspr  ...
Just to say that I tested the latest loki build (after the inclusion of the commit above) and it is working as expected.
Thanks for you support.

**Comment by gfrenoy** [comment]
:sunglasses: so we can close the issue?

**Comment by popxunga** [comment]
Sure ... We do not have best solution, but the one we have works, and that's enough for now ;-)
Thanks!
