### ISSUE TITLE
Startup script to run Ásbrú on Windows 10 ?

### ISSUE THREAD

**Issue by gfrenoy** [asbru-cm/asbru-cm#695]
From https://github.com/SegiH and issue #659:

> I wanted to ask you if you would care or be interested in an simple app that I wrote for Windows which lets you run 
> Asbru-CM on Windows 10 without any background console windows open.It does rely on you to have already 
> installed WSL/WSL2 + Ubuntu image from MS Store + XMing.

**Comment by gfrenoy** [comment]
I personally don't use Windows for years but I'd be glad to see more users of Ásbrú, so yes, that'd be great to have a simple way to run Ásbrú from another OS !

**Comment by SegiH** [comment]
I just published the code for Asbru-CM-runner to my Github page. You can find it [here](https://github.com/SegiH/Asbru-CM-Runner) It is a command line application.

I created a release package with pre-compiled binaries for those who don't want to compile it themselves.

Instructions are in the readme.

**Comment by gfrenoy** [comment]
Thanks for sharing !

Let me keep this issue open as we may want to write some words about it in our [documentation](https://docs.asbru-cm.net/)... Files to change it are available in the `[doc](https://github.com/asbru-cm/asbru-cm/tree/master/doc)` folder.  PR are welcome :)

**Comment by SegiH** [comment]
I'd be happy to update the docs and submit a PR if you can point me in the right direction as to which doc file you'd like me to update

**Comment by SegiH** [comment]
Scratch that. PR has already been submitted for your review
