### ISSUE TITLE
Shift key is not recognized in keybindings (ver 6.3.0)

### ISSUE THREAD

**Issue by minizx** [asbru-cm/asbru-cm#698]
* Version used: 6.3.0
* Phenomenon: Cannot recognize Shift key when changing shortcut key (Preferences> Keybindings)
* Explanation
When changing to a custom shortcut key, the shift key cannot be used.
   Change desired key: Ctrl + Shift + C
   Recognized key: Ctrl + V

**Comment by gfrenoy** [comment]
It works fine for me but be careful that the display might be a bit confusing today : if you hit `Ctrl + Shift + c`, it will actually show `Ctrl + C` (with a capital C).  If you hit `Ctrl + c`, it shows `Ctrl + c` (with a small letter c).

But it should work fine ...

**Comment by minizx** [comment]
Thank you for your answer.

As you mentioned, we have confirmed that the shift keys are distinct between "c" and "C".

But it doesn't work if you enter a shortcut in the actual terminal after setup.
> Actual operation: When entering Ctrl + Shift + V key, enter only ^V characters in the terminal

**Comment by gfrenoy** [comment]
> But it doesn't work if you enter a shortcut in the actual terminal after setup.

Mmm, that works fine for me : I can use `Ctrl+Shift+C` as a keybinding.  Or I can use `Ctrl+Shift+V`.

Note that if `Ctrl+Shift+V` is not associated to anything, it will indeed display `^V` in the terminal but that's the expected behavior.

Sorry but you'll need to describe your issue a bit more in details.

**Comment by minizx** [comment]
I think there is a compatibility problem with xfce4 or Clipman.
(https://docs.xfce.org/panel-plugins/xfce4-clipman-plugin)

I'll check further and let you know.
There was no problem with the stable version 6.2.x.

**Comment by gfrenoy** [comment]
> I'll check further and let you know

Thanks!

> There was no problem with the stable version 6.2.x.

Yes, we (well, ... Hans) made a lot of changes so we might indeed face some compatibility issues.  If we can find the root issue, we can hopefully fix it but further help to troubleshoot this further will definitely be appreciated.

**Comment by minizx** [comment]
I think Cliffman's problem is right.
The problem has been solved in the following way.

1. Changing from xfce4 to Clipman Extension Disable
2. Reboot
3. Setting shortcuts in asbru
4. Changing from xfce4 to using the Clipman extension
5. Shortcuts Normal Operation in Asbru


* Usage environment
Ubuntu 20.04.1 LTS
xfce4.14
Clipman 1.4.4
