### ISSUE TITLE
Send variable using asbru (like SendEnv)

### ISSUE THREAD

**Issue by IIPoliII** [asbru-cm/asbru-cm#699]
Hey everyone,

I need to send an APIKEY when I connect to a machine, however it works really well using simply ssh and putting SendEnv APIKEY. And if I connect using the `ssh` command it works well.

Now I tried to do the same using global and local variables on Asbru. I can't find the PAC config as well. I am on this issues since 2 days now. Is it possible to use SendEnv somewhere maybe?
Thanks for your help

**Comment by gfrenoy** [comment]
Did you try `SSH Options` > `Advanced Options` ?  There you can add any `ssh` options you want:
![image](https://user-images.githubusercontent.com/981546/95343996-6e740000-08b9-11eb-8e0e-79f0def59349.png)

**Comment by IIPoliII** [comment]
Is it possible to apply it globally on every machine that I connect globally or in a folder?

**Comment by IIPoliII** [comment]
I tried it but it doesn't transfer the variable correctly
:thinking:

**Comment by gfrenoy** [comment]
> Is it possible to apply it globally on every machine that I connect globally or in a folder?

Not that I'm aware of.

If you really have a lot, one idea could be to change the configuration file `asbru.yml` (see the `options` field of each SSH connection).

> So why not on asbru? 

Ásbrú is simply re-using `ssh` commands to it should work...Now, there might be reason why your configuration is not correct.

To troubleshoot this further, here are a few ideas:

- Use the `Show Command Line` button under `Connection` > `Advanced Parameters` of your SSH connection
- Check that the environment variables are correctly set when you start Ásbrú

Good luck.

**Comment by IIPoliII** [comment]
So I tried using the Show Command Line I can use the exact same command and it sends the variable I want. But not on Asbru any ideas for futher debugging?

**Comment by gfrenoy** [comment]
> But not on Asbru any ideas for futher debugging?

My best guess would be that you don't have the same environment when starting from the command line and starting Ásbrú.

How do you start Ásbrú ?

Can you start it from the same terminal (hence with the same environment) and see if this makes a difference ?

**Comment by IIPoliII** [comment]
Mhmm........ It works now I was directly launching it from my kde start menu. It's really weird I don't know with which user it starts then...
