### ISSUE TITLE
Colors are not initialized correctly

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#7]
When asbru is started for the first time, without an existing config, terminal colors default to a black background and the standard color scheme.
But when you open the preferences and save the dialog, the default colors set on 'Terminal Options' - 'Look and Feel' are applied instead and used henceforth.

**Comment by gfrenoy** [comment]
Mmm yes, I've seen that already but it should have been fixed in RC2 ?!

**Comment by gfrenoy** [comment]
Fixed in RC2.
