### ISSUE TITLE
Replay session saved log.

### ISSUE THREAD

**Issue by rsantellan** [asbru-cm/asbru-cm#701]
Hi,
Is there a way to replay saved session logs ? 

Thanks in advance.

**Comment by gfrenoy** [comment]
No (as far as I know) this is not possible today.

**Comment by rsantellan** [comment]
Hi @gfrenoy it is possible to use another program to do a replay in a video form ?
Does it use a particular format ? I just found out that functionality after years of using PAC/Asbru and can't find any doc about it.
Regards

**Comment by gfrenoy** [comment]
Yes, this software is full of surprising features :)

As far as I understand the code, it's just a raw recording of the data exchanged.  It is not using any particular format that we can reuse.

Are you look for something like https://asciinema.org/ ?

**Comment by gfrenoy** [comment]
Did not try myself but as far as I understand how asciinema is working, you can just use it once you are connected to the terminal ... I don't see how Ásbrú can really help here ?

To load the session records into asciinema, I would guess you should contact the asciinema team instead.

**Comment by rsantellan** [comment]
Hi @gfrenoy I will ask to the asciinema team.

Regards
