### ISSUE TITLE
FreeBSD login error again

### ISSUE THREAD

**Issue by Magisdn** [asbru-cm/asbru-cm#708]
Despite the option to automatically enter a password. A prompt of the form appears: Password for user @ server: I enter the password and it is visible. After pressing Enter - disconnection.
In connection mode with a saved password, for some reason, an invitation to enter the password appears and it is visible. In manual mode, the password is not visible and after entering it, the connection is established.

 - OS: FreeBSD 11.3, 12
 - Ásbrú Version 6.2.2

**Comment by gfrenoy** [comment]
Checked on a fresh FreeBSD 11.3 install and all works as expected.

You'll need to give more details about the error message you see.  If you don't see any error message, try to activate the "Expect DEBUG" option in "Preferences > Terminal Options > Advanced" and check why the password prompt is not triggering.

**Comment by Magisdn** [comment]
Starting EXPECT pattern matching...
 at /usr/share/perl5/vendor_perl/Expect.pm line 597.
	Expect::expect(Expect=GLOB(0x564217dafe00), 40, ARRAY(0x56421a1e95d8), ARRAY(0x56421a252ec8), ARRAY(0x56421a2531c8), ARRAY(0x56421a253420), ARRAY(0x56421a253510), ARRAY(0x56421a2540a0), ...) called at /opt/asbru-cm-loki/lib/asbru_conn line 1915
spawn id(5): list of patterns:
  #2: -eof `'
  #3: -re `\\[__PAC__SUDO__PROMPT__\\]'
  #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'
  #5: -re `.*(any key to continue|tecla para continuar).*'
  #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'
  #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'
  #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@\\w+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'
  #9: -re `[#%\\$>]|\\:\\/\\s*$'


spawn id(5): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@\\w+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

[asbru_conn(41118)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: CLOSE:TIMEOUT:40 seconds trying to connect or get prompt!!
[asbru_conn(41118)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: DISCONNECTED:1:TIMEOUT
[asbru_conn(41118)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: DISCONNECTED

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Sat Oct 17 12:10:13 2020)

**Comment by gfrenoy** [comment]
This log is not complete, we just see the last answer from the server ; the whole "conversation" will be required to understand why it does not detect the password prompt.

You'll need to scroll up to see the previous messages or to enable the session logs in Connection > Advanced Parameters.

**Comment by Magisdn** [comment]
asbru_conn(41118)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: !!_PAC_AUTH_[asbru_PID{37796}_n2]!!
[asbru_conn(41118)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: GET_TITLE:
[asbru_conn(41118)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: SPAWNING:ssh -p 22 -o "PreferredAuthentications=password,keyboard-interactive"  -2 -4 -x -l waiik xxx.xxx.xxx.xxx
[asbru_conn(41118)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: SPAWNED:'ssh -p 22 -o "PreferredAuthentications=password,keyboard-interactive"  -2 -4 -x -l waiik xxx.xxx.xxx.xxx' (PID:41118)

**Comment by gfrenoy** [comment]
This is still very partial ... Sorry but to understand why it does not match, we'll need more details ; especially on what is answered by the server and why it does not match the expect patterns.

**Comment by Magisdn** [comment]
Get command line
ssh -p 22   -x -l user xxx.xxx.xxx.xxx (ip address)
In session log file only
Password for user@domainname:
Full debug output:
CONNECTING WITH xxx.xxx.xxx.xxx-web (Sat Oct 17 22:56:25 2020)

[asbru_conn(33662)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: !!_PAC_AUTH_[asbru_PID{33206}_n4]!!
[asbru_conn(33662)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: SPAWNING:ssh -p 22 -o "PreferredAuthentications=password,keyboard-interactive"  -x -l user xxx.xxx.xxx.xxx
[asbru_conn(33662)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: SPAWNED:'ssh -p 22 -o "PreferredAuthentications=password,keyboard-interactive"  -x -l user xxx.xxx.xxx.xxx' (PID:33662)
Starting EXPECT pattern matching...
 at /usr/share/perl5/vendor_perl/Expect.pm line 597.
	Expect::expect(Expect=GLOB(0x56515a59bbe0), 40, ARRAY(0x56515c9ed9d8), ARRAY(0x56515c9fa4c0), ARRAY(0x56515c9fa7c0), ARRAY(0x56515c9faa18), ARRAY(0x56515c9fab08), ARRAY(0x56515c9faf10), ...) called at /opt/asbru/lib/asbru_conn line 1717
spawn id(5): list of patterns:
  #2: -eof `'
  #3: -re `\\[__PAC__SUDO__PROMPT__\\]'
  #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'
  #5: -re `.*(any key to continue|tecla para continuar).*'
  #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'
  #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'
  #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@\\w+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'
  #9: -re `[#%\\$>]|\\:\\/\\s*$'


spawn id(5): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@\\w+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

Password for user@domain.com:
spawn id(5): Does `\rPassword for user@domain.com:'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@\\w+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>]|\\:\\/\\s*$'? No.

password (The entered password is displayed)
[asbru_conn(33662)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: CLOSE:TIMEOUT:40 seconds trying to connect or get prompt!!
[asbru_conn(33662)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: DISCONNECTING
[asbru_conn(33662)][xxx.xxx.xxx.xxx-web][xxx.xxx.xxx.xxx-web]: DISCONNECTED

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Sat Oct 17 22:57:08 2020)

**Comment by gfrenoy** [comment]
> Password for user@domain.com

`\w` is not matching `domain.com`

Try using the following `Password Prompt` (instead of the default):

`
([pP]ass|[pP]ass[wW]or[dt](\s+for\s+|\w+@[\w\.]+)*|[cC]ontrase.a|Enter passphrase for key '.+')\s*:\s*$
`

What has changed is `\w+` for the host name that is now `[\w\.]+`.

If you have other special characters in the domain name, you'll need to add them as well.

**Comment by Magisdn** [comment]
Yes! Its work! Very thanks!

**Comment by Magisdn** [comment]
In the password prompt, Password for user@domain.com: domain.com is not a domain name, but a hostname that changes from server to server. on another server it is freebsd-control, i.e. Praol's invitation looks like this Password for user @ freebsd-control: and the password is not automatically entered again.

**Comment by gfrenoy** [comment]
As said above you need to add an special character, here `-`:

`
([pP]ass|[pP]ass[wW]or[dt](\s+for\s+|\w+@[\w\.-]+)*|[cC]ontrase.a|Enter passphrase for key '.+')\s*:\s*$
`

**Comment by Magisdn** [comment]
Password prompts:
Password for waiik@zabbix.camera.domain.com:
and 
Password for waiik@zabbix-proxy-01.camera.domain.com:
Such password prompts cause the Manual password requested window to appear
and 
user@xxx.xxx.xxx.xxx: Permission denied (publickey,keyboard-interactive)

**Comment by gfrenoy** [comment]
> Such password prompts cause the Manual password requested window to appear

This typically happens when you have an empty password set in the connection configuration.

**Comment by Magisdn** [comment]
No password is entered and it is transmitted once automatically, and then a window appears for entering it manually. After entering the password twice, the message waiik@10.248.47.12 appears: Permission denied (publickey, keyboard-interactive).

Password for user@zabbix.camera.domain.com:
Password for user@zabbix.camera.domain.com:
Password for user@zabbix.camera.domain.com:
user@xxx.xxx.xxx.xxx: Permission denied (publickey,keyboard-interactive).

**Comment by gfrenoy** [comment]
This looks like the password is not correct.  Check the server log ... Sorry but this all seems to work as expected.

**Comment by Magisdn** [comment]
Ок, I check it. Thanks!
