### ISSUE TITLE
Icon is not shown in tray bar anymore (Loki on EL8.2)

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#709]
Hi 
With asbru-cm-6.3.0-1602927173-1.el8 the asbru icon on systray get's hidden/invisible.
With the previous build (asbru-cm-6.3.0-1602891514.el8) it works fine.
Any ideas ?
Thanks!

**Comment by gfrenoy** [comment]
I have this from time to time on Ubuntu as well.  If you click on the "transparent" icon, it will eventually be shown...

**Comment by gfrenoy** [comment]
Mmm, just upgraded my system and now it happens all the time !  Looks like something has changed in on of the underlying libraries :-/

**Comment by popxunga** [comment]
Yeap ... and that's why I opened this issue ;-)
The previous loki build works fine.
My system didn't get any other updates between the installation of both loki builds.
So I guess that the changes introduced with the last couple of commits on the loki branch cause this as a side effect.

**Comment by gfrenoy** [comment]
Made some changes on loki.  Here it's "better" as it's the same as before : most of the time, the icon is there but sometimes, it is not shown, for some reason I cannot understand today.

Let me know how it behaves on your system...

And thanks for your help !

**Comment by popxunga** [comment]
> Made some changes on loki. Here it's "better" as it's the same as before : most of the time, the icon is there but sometimes, it is not shown, for some reason I cannot understand today.
> 
> Let me know how it behaves on your system...
> 
> And thanks for your help !

Asbru systray icon is back :-) 
I do have this type of issue with Slack (rarely) and with one VPN client software (always).
I should say that I never had any issue with Asbru systray icon invisibility on EL 8.2 in 3 months.
But now that we have it back, let's see how it works for a couple of days more.
Thanks for your support.

**Comment by popxunga** [comment]
Hi ...
Just say that this have been rock solid so far on EL 8.2 (icon always visible on systray).
Thanks ...

**Comment by popxunga** [comment]
@gfrenoy ,
Briefly tested latest loki build and the tray icon got invisible again.

**Comment by popxunga** [comment]
@gfrenoy ..
Ignore my previous post ... the asbru icon is visible...
