### ISSUE TITLE
Hangs when oh-my-zsh asks to update on login

### ISSUE THREAD

**Issue by chripede** [asbru-cm/asbru-cm#710]
**Describe the bug**
When logging into a server running oh-my-zsh and it asks to update, the login will hang forever.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Ásbrú Version 6.2 and Loki

**Additional context**

![image](https://user-images.githubusercontent.com/406836/96443135-706c8600-120c-11eb-9d96-06d357472268.png)

**Comment by gfrenoy** [comment]
The way Ásbrú is working is that it's looking for a `Command Prompt` to consider the connection as established. See Preferences > Main Options > Advanced.

So, you'll need to tweak the `Command Prompt` to match the prompt generated by oh-my-zsh.

**Comment by chripede** [comment]
Thank you.

In case this happens for any one else, I changed the above setting to
`[#%\$>]|\:\/\s*$|\[oh-my-zsh\]`
and it now works.
