### ISSUE TITLE
Use of uninitialized value in string eq at /opt/asbru/lib/asbru_conn line 175.

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#711]
Hi, 
steps to reproduce:

1. open ssh connection
2. open 'new sftp window ' (window from step 1)
3. rename connection / change title
4. disconnect sftp 
5. press enter to reconnect

gives:

Use of uninitialized value in string eq at /opt/asbru/lib/asbru_conn line 175.
Use of uninitialized value $METHOD in string ne at /opt/asbru/lib/asbru_conn line 1317.
Use of uninitialized value $METHOD in pattern match (m//) at /opt/asbru/lib/asbru_conn line 1332.
Use of uninitialized value $METHOD in pattern match (m//) at /opt/asbru/lib/asbru_conn line 1332.
Use of uninitialized value $METHOD in string eq at /opt/asbru/lib/asbru_conn line 1332.
Use of uninitialized value $METHOD in pattern match (m//) at /opt/asbru/lib/asbru_conn line 1414.
Use of uninitialized value $METHOD in string eq at /opt/asbru/lib/asbru_conn line 1414.
Use of uninitialized value $METHOD in pattern match (m//) at /opt/asbru/lib/asbru_conn line 1498.
Use of uninitialized value $METHOD in string eq at /opt/asbru/lib/asbru_conn line 1498.
Use of uninitialized value $METHOD in pattern match (m//) at /opt/asbru/lib/asbru_conn line 1498.
Use of uninitialized value $METHOD in string eq at /opt/asbru/lib/asbru_conn line 1498.
Use of uninitialized value $METHOD in string eq at /opt/asbru/lib/asbru_conn line 1609.

debian 10 + xfce, latest loki

**Comment by gfrenoy** [comment]
Thanks.  I've been able to reproduce this.

Not an easy to fix though :-/

When you rename a connection, its internal UUID is changed.  Any open connection will still have the old UUID so when you try to reconnect, that UUID is not known anymore.

Not sure what would be the best option here:
a) prevent renaming a connection that is still open (difficult to catch, likely)
b) properly catch the errors and show a nice error message saying that the connection does not exist anymore and cannot be restarted (might be the best option)
c) ensure the UUID is correctly propagated to any open connection (not sure how to do this, looks very complicated)

Any comment or suggestion will be welcome.

**Comment by figue** [comment]
Occam's razor likes b)

**Comment by vibo69** [comment]
I think. every connections should just have 'my-new-uuid-for-this-session'. just find every window with old/renamed one and set additional variable to it

**Comment by vibo69** [comment]
my observations from today:
even if connection is not renamed and host will brake connection you still have the same (or similar error)

sftp> Connection to 192.168.10.19 closed by remote host.
Connection closed.  

sftp> ls
Couldn't send packet: Broken pipe

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Fri Oct 23 15:15:50 2020)


CONNECTING WITH ------- (Fri Oct 23 15:15:50 2020)

Use of uninitialized value in string eq at /opt/asbru/lib/asbru_conn line 175.
Use of uninitialized value $AUTH in string eq at /opt/asbru/lib/asbru_conn line 216.
Use of uninitialized value $METHOD in string ne at /opt/asbru/lib/asbru_conn line 1323.
Use of uninitialized value $METHOD in pattern match (m//) at /opt/asbru/lib/asbru_conn line 1339.
Use of uninitialized value $METHOD in pattern match (m//) at /opt/asbru/lib/asbru_conn line 1339.
Use of uninitialized value $METHOD in string eq at /opt/asbru/lib/asbru_conn line 1339.
Use of uninitialized value $METHOD in pattern match (m//) at /opt/asbru/lib/asbru_conn line 1421.
Use of uninitialized value $METHOD in string eq at /opt/asbru/lib/asbru_conn line 1421.
Use of uninitialized value $METHOD in pattern match (m//) at /opt/asbru/lib/asbru_conn line 1505.
Use of uninitialized value $METHOD in string eq at /opt/asbru/lib/asbru_conn line 1505.
Use of uninitialized value $METHOD in pattern match (m//) at /opt/asbru/lib/asbru_conn line 1505.
Use of uninitialized value $METHOD in string eq at /opt/asbru/lib/asbru_conn line 1505.
Use of uninitialized value $METHOD in string eq at /opt/asbru/lib/asbru_conn line 1616.
Use of uninitialized value $METHOD in string ne at /opt/asbru/lib/asbru_conn line 1941.

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Fri Oct 23 15:15:51 2020)

**Comment by gfrenoy** [comment]
> even if connection is not renamed and host will brake connection you still have the same (or similar error)

Cannot reproduce this.  Are you sure you did not move the node or anything other manipulation in the connection tree ?

Anyway, in this issue, I'd like to focus on the initial description first and find a way to properly catch the error.

**Comment by vibo69** [comment]
Now I see I could be more precise.. I opened existing ssh connection in my connection tree (nothing was changed with it since last asbru close). then opened new sftp tab with this connection. then host was restarted so both connections died. then I got that error when trying to reconnect

**Comment by gfrenoy** [comment]
Into the `_cfgSanityCheck`, I found out that the temporary sessions are deleted:

https://github.com/asbru-cm/asbru-cm/blob/1f8e8c445f08013c4b1db43972813f4da2c1b6a8/lib/PACUtils.pm#L2254-L2256

That's the reason why it cannot be restarted.

Now I need to find out in which cases `_cfgSanityCheck` really needs to wipe out the temporary session.

**Comment by vibo69** [comment]
so they should not be deleted until window/tab is closed ;)

**Comment by gfrenoy** [comment]
Please try the latest commit and let us know if you notice some improvements.

Now Ásbrú will preserve the temporary sessions when saving the configuration.  There might be other cases when `_cfgSanityCheck` but this should fix the most common cases (rename, configuration change, ...).

**Comment by vibo69** [comment]
Hi, with latest loki branch issue is solved (at least for host reboots)

**Comment by gfrenoy** [comment]
> at least for host reboots

Don't believe this has anything to do with the reboot.  Likely a configuration reloads happened in between.

Anyway, let's consider this closed for now.
