### ISSUE TITLE
Maximum number of clients reached (asbru_conn:5864): Gtk-WARNING **: 14:45:53.545: cannot open display: :0.0

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#712]
Hi, is it depends from asbru? ..or is it X setting to be modified?

**Comment by gfrenoy** [comment]
Don't believe this has anything to do with Ásbrú... Do you have any way to reproduce this behavior ?

**Comment by vibo69** [comment]
just open a lot of tabs. usually I work with 50+ terminals everyday. at about 75 opened this would happen

**Comment by gfrenoy** [comment]
Gee, 75 terminals is a lot :)  I don't have that many different terminals so I tried to open 10 times the same 10 terminals and did not encounter any particular issue...

From what I can find out, you can use `xlsclients` to find out the open clients and there are options to increase that maximum, see https://unix.stackexchange.com/a/515786 as an example

**Comment by vibo69** [comment]
well.. I am responsible for about 750 nodes.. so 50 terminals is really nothing special :D 
```
$ xlsclients |wc -l
114
```
;)

**Comment by gfrenoy** [comment]
Tried to open 150 connections here, no particular issue:

```
$ xlsclients |wc -l                                                                                                                                                     
57
$ xlsclients |wc -l                                                                                                                                                     
65
$ xlsclients |wc -l                                                                                                                                                     
97
$ xlsclients |wc -l                                                                                                                                                     
129
$ xlsclients |wc -l                                                                                                                                                     
169
$ xlsclients |wc -l                                                                                                                                                     
193
$ xlsclients |wc -l                                                                                                                                                     
201
```

I would assume it's a limitation / configuration issue in your X environment but I cannot help further on this.
