### ISSUE TITLE
Fedora 33 Support

### ISSUE THREAD

**Issue by danilohawila** [asbru-cm/asbru-cm#713]
**Describe the bug**
The fedora team marked some packages as obsolete in version 33, including the needed one "perl-X11-GUITest" https://bugzilla.redhat.com/show_bug.cgi?id=1884617
When installing, the error follows:

nothing provides perl-X11-GUITest needed by asbru-cm-6.2.1-1.fc32.noarch (try to add '--skip-broken' to skip uninstallable packages)A clear and concise description of what the bug is.

**Environment (please complete the following information):**
 - OS: Fedora 33 Beta
 - Ásbrú Version 6.2.1

**Comment by popxunga** [comment]
Have a look into #707 ...

**Comment by danilohawila** [comment]
Thanks @popxunga 
I had not seen this issue 
Closed.
