### ISSUE TITLE
Asbru processing lists of IP addresses

### ISSUE THREAD

**Issue by xattack** [asbru-cm/asbru-cm#715]
Hi everybody !!

   This is a feature request that i would like to see in Asbru-CM 

    Sometimes customers ask to validate if certain service is running or enabled in n number of servers. I get this list today 
asking to verify if NTP service is up and running  

 172.19.210.155 
172.19.210.208 
172.19.210.209  
172.19.202.134 
172.19.251.2 
172.19.251.7  
172.29.64.187  
172.29.64.186    
172.29.65.187 
172.29.65.186 
172.29.64.193 
172.29.64.194 
172.29.65.194 
172.19.207.236
172.19.207.249
172.19.204.129 

   Is it possible to enable in asbru this feauture, to  process this kind of petitions ?  I know i can feed it one by one , or create a temporary cluster , which i don't want cause its time consuming  and then just delete it. And even more , I've already this servers registered in my asbru client !

 I am thinking to feed asbru with the list and then get into the servers just like when you get into one of them.

**Comment by gfrenoy** [comment]
Not sure how you want to integrate this into Ásbrú.  [nmap](https://nmap.org/) is probably what you're looking for, with the option `-iL` to read a list of IP addresses and `-p 123 -sU` to check for NTP service.

**Comment by popxunga** [comment]
> Hi everybody !!
> 
> This is a feature request that i would like to see in Asbru-CM
> 
> ```
> Sometimes customers ask to validate if certain service is running or enabled in n number of servers. I get this list today 
> ```
> 
> asking to verify if NTP service is up and running
> 
> 172.19.210.155
> 172.19.210.208
> 172.19.210.209
> 172.19.202.134
> 172.19.251.2
> 172.19.251.7
> 172.29.64.187
> 172.29.64.186
> 172.29.65.187
> 172.29.65.186
> 172.29.64.193
> 172.29.64.194
> 172.29.65.194
> 172.19.207.236
> 172.19.207.249
> 172.19.204.129
> 
> Is it possible to enable in asbru this feauture, to process this kind of petitions ? I know i can feed it one by one , or create a temporary cluster , which i don't want cause its time consuming and then just delete it. And even more , I've already this servers registered in my asbru client !
> 
> I am thinking to feed asbru with the list and then get into the servers just like when you get into one of them.

Suggestion: Use Ansible :-)

**Comment by xattack** [comment]
Both of you , are correct . We can use nmap or solve it with ansible or any other execution engines 

any way , thank you for your answers !!
