### ISSUE TITLE
Another issue in generated autostart file

### ISSUE THREAD

**Issue by ErikTerwan** [asbru-cm/asbru-cm#718]
I've seen your work on https://github.com/asbru-cm/asbru-cm/issues/651, but I have another issue concerning the generated autostart file.

I patched both `PACConfig.pm` and `PACUtils.pm` on my system (`Exec=/usr/bin/asbru` -> `Exec=/usr/bin/asbru-cm`). My generated autostart file reflected the changes, but still wasn't autostarting on Fedora 32.

Then I looked at [asbru-cm.desktop](https://github.com/asbru-cm/asbru-cm/blob/master/res/asbru-cm.desktop) (`/usr/share/applications/asbru-cm.desktop`) and noticed another version of the `Exec=` line: `Exec=env GDK_BACKEND=x11 asbru-cm`. Applying `env GDK_BACKEND=x11` to `PACConfig.pm` and `PACUtils.pm` and regenerating the autostart file, did the trick.

**Comment by gfrenoy** [comment]
Looks like a great suggestion :)  Would you mind created a PR for this ?  Thanks!

**Comment by ErikTerwan** [comment]
Working on it...

**Comment by gfrenoy** [comment]
Thanks a lot for your help !  Your fix is now merged to master and scheduled for the next 6.2.2 version.
