### ISSUE TITLE
Fedora 33 Support - (PackageCloud) / obsoleted perl-X11-GUITest

### ISSUE THREAD

**Issue by Frankstar** [asbru-cm/asbru-cm#719]
any plans on this?

currently i get the following error if i try to upgrade from f32 to f33:

```Error: 
 Problem: problem with installed package asbru-cm-6.2.1-1.fc32.noarch
  - package asbru-cm-6.2.1-1.fc32.noarch requires perl-X11-GUITest, but none of the providers can be installed
  - package asbru-cm-6.2.0-1.fc32.noarch requires perl-X11-GUITest, but none of the providers can be installed
  - perl-X11-GUITest-0.28-19.fc32.x86_64 does not belong to a distupgrade repository
```

looks like `perl-X11-GUITest`  is obsoleted.
https://bugzilla.redhat.com/show_bug.cgi?id=1884617

**Comment by nlpsuge** [comment]
Same problems here.

**Comment by bitchecker** [comment]
on Fedora 33, no repository available:
```
Errors during downloading metadata for repository 'asbru-cm':
  - Status code: 404 for https://packagecloud.io/asbru-cm/asbru-cm/fedora/33/x86_64/repodata/repomd.xml (IP: 54.193.34.251)
Error: Failed to download metadata for repo 'asbru-cm': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by popxunga** [comment]
Have a look here: #707

**Comment by gfrenoy** [comment]
#1 perl-X11-GUITest obsolete --> will be made optional as of 6.2.2 ; you can try our "snapshot" version in the meantime.
#2 no repository available --> I asked packagecloud to support F33 ; waiting for their answer

**Comment by nerijus** [comment]
I've done:
On Fedora 22:
yumdownloader --source perl-X11-GUITest
On Fedora 33:
rpmbuild --rebuild perl-X11-GUITest-0.28-19.fc32.src.rpm 
rpm -Uvh perl-X11-GUITest-0.28-19.fc33.x86_64.rpm 

and then asbru-cm installs and works. I'd suggest adding perl-X11-GUITest package to asbru-cm F33 repo.

**Comment by Frankstar** [comment]
adding an obsolete and not maintained package is not really the way to go ....

**Comment by gfrenoy** [comment]
6.2.2 is now available for Fedora 33 in the snapshots on [Cloudsmith](https://cloudsmith.io/~asbru-cm/repos/snapshots/packages/?q=distribution%3Afedora+AND+distribution%3A33) ; install instructions are:

```
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/snapshots/cfg/setup/bash.rpm.sh' | sudo -E bash
sudo dnf install asbru-cm
```

**Comment by gfrenoy** [comment]
6.2.2 is now available in the latest release:

```
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.rpm.sh' | sudo -E bash
sudo dnf install asbru-cm
```
