### ISSUE TITLE
Login via pgp hardware usb key (e.g. Nitrokey Pro)

### ISSUE THREAD

**Issue by iprofor** [asbru-cm/asbru-cm#72]
Hello,

I would like to use the NitroKey Pro usb key to authenticate onto the server. They have an excellent How-to for enabling pgp for ssh [here](https://www.nitrokey.com/documentation/applications#ssh-for-server-administration), however I do not understand how to make Asbru use the private key from the key.

Is it possible? If not, could it be implemented in the next versions of Asbru?

Thank you

**Comment by gfrenoy** [comment]
As far as I can read and understand, on the client side, you just need to make sure ```gpg-agent``` is up and running and properly configured.

To troubleshoot, you may want to try to start Ásbrú from the command line and, in the same shell, look what is returned by:

    echo $SSH_AUTH_SOCK

If this is correct, that ```gpg-agent``` is up and running and that you server is properly configured as well ; I don't think there's anything to do in Ásbrú.

Let us know what you find out and if anything could be done in Ásbrú to ease that process.
