### ISSUE TITLE
Support for Lubuntu 20.10

### ISSUE THREAD

**Issue by donixa** [asbru-cm/asbru-cm#720]
I did try install by using mentioned command line from Lubuntu 20.10,
It said OS is not supported, when are you going to support Lubuntu 20.10,

I was long time secureCRT users, hopefully this can replace it, Thank you!

**Comment by gfrenoy** [comment]
It was not as easy as usual but we finally managed to make Ásbrú packaged for Ubuntu "Groovy" 20.10 :)

Early testers will be very welcome:
```
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/snapshots/cfg/setup/bash.deb.sh' | sudo -E bash
```

Or on loki:
```
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/loki/cfg/setup/bash.deb.sh' | sudo -E bash
```

And then:
```
sudo apt install asbru-cm
```

**Comment by donixa** [comment]
yes its working thank u, i havent try it yet
