### ISSUE TITLE
Not connect with socks

### ISSUE THREAD

**Issue by Dead365-dev** [asbru-cm/asbru-cm#721]
Work fine without socks, because not working with local socks5 
Arch Linux

**Comment by gfrenoy** [comment]
Can you elaborate a little more on what does not work (if you see any error messages, as an example) ?

**Comment by Dead365-dev** [comment]
Tor socks service
Error: Couldn't resolve host "127.0.0.1:9050"
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535

**Comment by gfrenoy** [comment]
Sorry, these messages do not tell much about the root issue.

Is there an publicly available socks5 proxy I can use to test and reproduce the issue ?

**Comment by gfrenoy** [comment]
Oh and very important question : which version are you using ?  Socks5 will only work with loki !
