### ISSUE TITLE
Issue with Vte::Terminal::feed_child version

### ISSUE THREAD

**Issue by syco** [asbru-cm/asbru-cm#723]
Hi,
I'm on OpenSUSE with the latest loki.
I've a weird issue with clusters not sending keystrokes to all terminals and sending copy and paste only up to the second last letter.

I've done a screen capture of it, as I'm not sure how to explain it better:
![Peek 2020-11-03 16-05](https://user-images.githubusercontent.com/54575/98013083-cf77f080-1df1-11eb-9d78-fc0d42c2ec8a.gif)
Here's a log file of the execution:
[asbru.log](https://github.com/asbru-cm/asbru-cm/files/5482632/asbru.log)

I found a solution that works for me, that is remove the feed version detection and use version 1, but I'm not sure if this breaks other os:
[https://github.com/asbru-cm/asbru-cm/compare/loki...syco:loki-feature-force-feed-version](https://github.com/asbru-cm/asbru-cm/compare/loki...syco:loki-feature-force-feed-version)
```patch
--- a/lib/PACUtils.pm
+++ b/lib/PACUtils.pm
@@ -3776,34 +3776,18 @@ sub _vteFeed {
 sub _vteFeedChild {
     my $vte = shift;
     my $str = shift;
-    my $feedVersion = $PACMain::FUNCS{_MAIN}{_Vte}{vte_feed_child};
 
-    use bytes;
-    my $b = length($str);
     my @arr = unpack ('C*', $str);
 
-    if ($feedVersion == 1) {
-        # Newer version only requires 1 parameter
         $vte->feed_child(\@arr);
-    } else {
-        # Elder versions requires 2 parameters
-        $vte->feed_child($str, $b);
-    }
 }
 
 sub _vteFeedChildBinary {
     my $vte = shift;
     my $str = shift;
     my @arr = unpack ('C*', $str);
-    my $feedVersion = $PACMain::FUNCS{_MAIN}{_Vte}{vte_feed_binary};
 
-    if ($feedVersion == 1) {
-        # Newer version only requires 1 parameter
         $vte->feed_child_binary(\@arr);
-    } else {
-        # Elder versions requires 2 parameters
-        $vte->feed_child_binary(\@arr, length(\@arr));
-    }
 }
 
 sub _createBanner {
```

**Comment by gfrenoy** [comment]
For other OSes, we indeed need to support both methods.  This is supposed to be depending on the VTE version but we already noticed some glitches in this logic.

You'd better look into `_setVteCapabilities` and see if you can improve the detection logic for you system (without changing the logic for others...):

https://github.com/asbru-cm/asbru-cm/blob/0e911e19917a508128444b3f7d1390bc4fc58191/lib/PACMain.pm#L4809-L4828

For your OS, `vte_feed_child` should be 1...

Thanks!

**Comment by syco** [comment]
Found it!
As [https://perlmaven.com/fatal-errors-in-external-modules](https://perlmaven.com/fatal-errors-in-external-modules) explains, that `1` in the `eval` statement makes it always return true.
That's why the `or do` part is never executed for me.
I've created a pull request for it: [https://github.com/asbru-cm/asbru-cm/pull/725](https://github.com/asbru-cm/asbru-cm/pull/725)

**Comment by syco** [comment]
Hi,
it required some more testing than I expected, but the problem is definitely there.
The `eval` needs to die if there's a warning, while in my case it doesn't and the `or do` is never executed.

I've created a pull request with my definitive answer: [https://github.com/asbru-cm/asbru-cm/pull/726](https://github.com/asbru-cm/asbru-cm/pull/726)

Thanks..

**Comment by gfrenoy** [comment]
Fixed by your commit, thanks again !
