### ISSUE TITLE
(pac_conn:22985): Gtk-WARNING Theme parsing error

### ISSUE THREAD

**Issue by throwawayaccountbeepboop** [asbru-cm/asbru-cm#727]
While opening a remote ssh terminal, I'm getting this: https://i.imgur.com/jTasgNZ.png

I was looking @ https://github.com/asbru-cm/asbru-cm/issues/227

but when I go into my KDE settings I am missing said options. https://i.imgur.com/7agAEAa.png

I tried to click the bottom right button on the last screen and setting it to 'default' but that doesn't seem to fix this problem.
https://i.imgur.com/rchxCkf.png

**Comment by gfrenoy** [comment]
Same conclusion as #227 : you are using a GTK theme that is having an issue.

I'm really not familiar with KDE so I'm not sure how to force the theme.  But your screenshot does not look like the one on #227 so I do suspect you are not changing the GTK3 theme.  Maybe this can help you --> https://askubuntu.com/a/179341 ?
