### ISSUE TITLE
copy paste works only once

### ISSUE THREAD

**Issue by vokborok** [asbru-cm/asbru-cm#729]
**Describe the bug**
A node (group of nodes) can be copied only once 

**To Reproduce**
1. right-click the node
2. Copy node
2. right-click to the folder you want to add node
3. Paste node
4. right-click to another folder you want to add node
5. "Paste node" is not clickable

**Expected behavior**
Paste as many times as required

**Environment (please complete the following information):**
 - OS: [Ubuntu 20.04.1 LTS]
 - Ásbrú Version [6.1.2]

**Comment by gfrenoy** [comment]
Indeed.  I see the same behavior in the latest versions as well.
I'll need to check if this is really a bug or because of the application design (and consequently difficult to fix).

In all cases: thanks for the interesting feedback :)

**Comment by gfrenoy** [comment]
@hanspr I gave the last commit a try but it does not work for me... Did I apply the correct changes on the loki branch ?  Is it supposed to work ?  Thanks.

**Comment by hanspr** [comment]
It works with Ctrl-V, I did not implemented with right click, I will assume you are using the mouse clic paste

how are you testing?

![Peek 06-11-2021 14-13](https://user-images.githubusercontent.com/1572396/140622662-0dff079d-bb69-4dba-b2b5-cf95ae359e76.gif)

**Comment by gfrenoy** [comment]
Indeed, I did not try with keyboard only ; I just saw the menu entry was grayed out and did not try further.

Anyway, you figured it out and the last commit is working great.

Thanks a lot !
