### ISSUE TITLE
Global credentials

### ISSUE THREAD

**Issue by vokborok** [asbru-cm/asbru-cm#730]
**Describe the solution you'd like**
It would be great to have an option to configure creds globally and later pick certain global cred for particular node rather than write user/password (or specify certificate) manually for every node. That will save a lot of time.

**Comment by gfrenoy** [comment]
You can use [global variables](https://docs.asbru-cm.net/Manual/Preferences/GlobalVariables/), can"t you?

Or, probably better, use the [KeepassXC](https://docs.asbru-cm.net/Manual/Preferences/KeePassXC/) integration.

**Comment by vokborok** [comment]
I mean, like:
You create a list of global creds, for example: 
qa ( user: qa_user, pass: pqssword1)
dev (user: dev_user, pass: password2)

And later in Connection settings, you can choose a particular one from the drop-down menu (qa/dev)

didn't use Keepass integration before, will try

**Comment by vibo69** [comment]
just use global variables for that. i do ;)

**Comment by gfrenoy** [comment]
As global varialbe should address the need, let me close this for now.

If you believe there should be an alternative way, feel free to create a new issue.

Thanks.
