### ISSUE TITLE
Conecction Type: https/http

### ISSUE THREAD

**Issue by tyl0re** [asbru-cm/asbru-cm#731]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be Great also Manage weblogins in the Connection Manager. 

**Describe alternatives you've considered**
There is no Alternative

**Additional context**
Mobaxterm under Windows Have similiar feature. I look forward to have the similiar Features under Linux with Asbru

**Comment by gfrenoy** [comment]
Can you describe the changes you would expect a little more ?

This description is not detailed enough to know how to proceed further.  Thanks.
