### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by vokborok** [asbru-cm/asbru-cm#732]
Are there plans for asbru to run on mac systems ?

**Comment by gfrenoy** [comment]
See #116

**Comment by alecs** [comment]
Started work on this but there is a graphics issue on M1, that can not be easily bypassed.
On Intel Mac it should probably work if you meet all the deps and just run
`perl asbru-cm`

![image](https://user-images.githubusercontent.com/1592826/220616287-c9780cc2-faec-41bd-b45e-18f0a14d999d.png)

Also, I did not fully try to built all with Rosetta, which might get me closer to the final goal.
![image](https://user-images.githubusercontent.com/1592826/220617937-f107605b-7972-4b2c-a157-27b306081cad.png)

**Comment by otkachov** [comment]
> Started work on this but there is a graphics issue on M1, that can not be easily bypassed. On Intel Mac it should probably work if you meet all the deps and just run `perl asbru-cm`

Could you create an instruction for Mac with detailed steps?

**Comment by alecs** [comment]
> > Started work on this but there is a graphics issue on M1, that can not be easily bypassed. On Intel Mac it should probably work if you meet all the deps and just run `perl asbru-cm`
> 
> Could you create an instruction for Mac with detailed steps?

I intend to create a package but have multiple ongoing projects and time is limited :)
Thing is you just need to install all deps and match the arch. If you are on x86 Mac it should work by just installing the deps from ports (if you use perl from ports) or from brew (and some manual things too, with `perl -MCPAN -e shell`.

**Comment by alecs** [comment]
This is the current status on my side.
On M1 Apple, due to the bug referenced at [XQuartz issue 31](https://github.com/XQuartz/XQuartz/issues/31), we can only work with a dark theme.

![image](https://user-images.githubusercontent.com/1592826/225041861-9ea68a46-f824-4ada-8fb9-e731690eacbd.png)


I'll be preparing a how-to run on mac and fixing some other issues that appear on mac only.
I don't think it makes sense to create a dmg, since it would be mostly rebuilding stuff from ports and having them installed separately.

**Comment by alecs** [comment]
Ok, was able to make it work decently, even though I did not write a howto.
Eventually packed it with par packer:  [PAR-Packer](https://metacpan.org/dist/PAR-Packer)
By using:
```
/opt/local/libexec/perl5.34/sitebin/pp -M B:: -M Cairo:: -M Clone:: -M Cwd:: -M DB_File:: -M Digest:: -M Encode:: -M Fcntl:: -M GDBM_File:: -M GSSAPI:: -M Glib:: -M IO:: -M JSON:: -M Locale:: -M NDBM_File:: -M Opcode:: -M POSIX:: -M Pango:: -M PerlIO:: -M SDBM_File:: -M Socket:: -M Socket6:: -M Storable:: -M attributes:: -M mro:: -M re:: -M threads -o asbru.bin asbru-cm
```
Attached file, for whoever wants to try.

```
  ~/git/asbru-cm/ [master*] file asbru.bin                 [23/03/16 02:27:22]
asbru.bin: Mach-O 64-bit executable x86_64
  ~/git/asbru-cm/ [master*] md5sum asbru.bin               [23/03/16 02:30:02]
7bce45b4cd96706478138cd31800eff9  asbru.bin
```

[asbru.bin.zip](https://github.com/asbru-cm/asbru-cm/files/10985572/asbru.bin.zip)

**Comment by alecs** [comment]
Updated above comment and file, had some missing libs.

![image](https://user-images.githubusercontent.com/1592826/225480607-2ae453b0-8ce9-4479-b8a4-bdd446f0446d.png)

**Comment by alecs** [comment]
So, tested a bit on multiple systems:

To have it working, you need to:

1. install xquartz
2. setup macports
3. install the following
```
port install cairo freetype glib2 gobject-introspection graphviz intltool libffi libgit2 ossp-uuid +universal
```
Comes with a lot of dependencies.

4. Run the asbru.bin attached above.

If you prefer to run it from source, there are some changes needed in a few files (which I am gonna do a PR for), and you need a lot more packages:
```
port install Xft2 adwaita-icon-theme aom asciidoctor at-spi2-atk at-spi2-core atk autoconf autoconf-archive automake bison bison-runtime brotli bzip2 cairo cargo cargo-c ccache cctools cmake curl curl-ca-bundle cython_select dav1d db48 dbus docbook-xml docbook-xml-4.1.2 docbook-xml-4.2 docbook-xml-4.3 docbook-xml-4.4 docbook-xml-4.5 docbook-xml-5.0 docbook-xsl-nons docutils_select expat flex fontconfig freetype fribidi gd2 gdbm gdk-pixbuf2 gettext gettext-runtime gettext-tools-libs ghostscript gi-docgen giflib git glib2 gmake gmp gnutls gobject-introspection graphite2 graphviz groff gtk-doc gtk2 gtk3 gts harfbuzz help2man hicolor-icon-theme hiredis icu intltool itstool jasper jbig2dec jbigkit kerberos5 lcms2 lerc libLASi libarchive libb2 libcomerr libcxx libde265 libedit libepoxy libffi libgit2 libheif libiconv libidn libidn2 libjpeg-turbo libnetpbm libpaper libpixman libpng libpsl librsvg libssh2 libtasn1 libtextstyle libtool libunistring libuv libwnck3 libxml2 libxslt libyaml lmdb lz4 lzo2 m4 mesa meson nasm ncurses netpbm nettle nghttp2 ninja openjpeg openssl openssl11 openssl3 ossp-uuid p11-kit p5.34-authen-sasl p5.34-cairo p5.34-cairo-gobject p5.34-cgi p5.34-clone p5.34-common-sense p5.34-compress-raw-bzip2 p5.34-compress-raw-zlib p5.34-cpan-meta-requirements p5.34-crypt-blowfish p5.34-crypt-cbc p5.34-crypt-rijndael p5.34-data-dump p5.34-devel-checkbin p5.34-devel-checklib p5.34-digest-hmac p5.34-digest-sha1 p5.34-encode p5.34-encode-locale p5.34-error p5.34-expect p5.34-expect-simple p5.34-extutils-depends p5.34-extutils-makemaker p5.34-extutils-manifest p5.34-extutils-pkgconfig p5.34-file-listing p5.34-file-slurper p5.34-file-which p5.34-font-freetype p5.34-getopt-long p5.34-glib p5.34-glib-object-introspection p5.34-gssapi p5.34-gtk3 p5.34-gtk3-simplelist p5.34-html-form p5.34-html-parser p5.34-html-tagset p5.34-http-cookies p5.34-http-daemon p5.34-http-date p5.34-http-message p5.34-http-negotiate p5.34-io-compress p5.34-io-compress-brotli p5.34-io-html p5.34-io-socket-ip p5.34-io-socket-ssl p5.34-io-stty p5.34-io-tty p5.34-json p5.34-json-xs p5.34-libwww-perl p5.34-locale-gettext p5.34-lwp-mediatypes p5.34-mozilla-ca p5.34-net-http p5.34-net-libidn p5.34-net-smtp-ssl p5.34-net-ssleay p5.34-pathtools p5.34-pod-escapes p5.34-pod-simple p5.34-scalar-list-utils p5.34-socket p5.34-sub-name p5.34-term-readkey p5.34-test-cpan-meta p5.34-test-cpan-meta-json p5.34-test-pod p5.34-test-warnings p5.34-time-hires p5.34-time-local p5.34-timedate p5.34-try-tiny p5.34-types-serialiser p5.34-uri p5.34-www-robotrules p5.34-xml-parser p5.34-yaml pango pcre pcre2 perl5 perl5.34 pkgconfig popt psutils py310-mako py310-markupsafe py310-setuptools py311-anytree py311-build py311-cython py311-docutils py311-installer py311-jinja2 py311-libxml2 py311-lxml py311-mako py311-markdown py311-markupsafe py311-packaging py311-pep517 py311-pygments py311-roman py311-setuptools py311-six py311-smartypants py311-toml py311-typogrify py311-wheel pygments_select python310 python311 python3_select python_select rav1e re2c readline rsync ruby30 ruby_select rust scite shared-mime-info sqlite3 startup-notification texinfo tiff uchardet urw-fonts vala vte webp x265 xmlcatmgr xmodmap xorg-libX11 xorg-libXau xorg-libXaw xorg-libXcomposite xorg-libXcursor xorg-libXdamage xorg-libXdmcp xorg-libXext xorg-libXfixes xorg-libXi xorg-libXinerama xorg-libXmu xorg-libXrandr xorg-libXres xorg-libXt xorg-libXtst xorg-libice xorg-libpthread-stubs xorg-libsm xorg-libxcb xorg-util-macros xorg-xcb-proto xorg-xcb-util xorg-xorgproto xorg-xtrans xpm xrender xxhashlib xz yasm zlib zstd
```

Then, you should be able to just do: `perl5.34 asbru-cm`

Attached packed binary and deps archive for the impatient.
[asbru-bin.zip](https://github.com/asbru-cm/asbru-cm/files/10985644/asbru.bin.zip)
[asbru.deps.zip](https://github.com/asbru-cm/asbru-cm/files/10989682/asbru.deps.zip)

Also, if running `./asbru.bin` fails, you need to do `sudo xattr -rd com.apple.quarantine asbru.bin` and try again. Can also use the **System Preferences -> Security -> General -> Open anyway**.

**Comment by otkachov** [comment]
Thank you!

**Comment by rrajp** [comment]
@alecs  I am getting following with your mentioned steps. I did install ossp-uuid separately.


```
Can't load '/var/folders/pk/4zjp95t11kd_6jl07c28fylm0000gq/T/par-7261766972616a/cache-4bb4ccf7e08f2b6f10e0671040fd9ab50fe064b2/1198e0d6.bundle' for module OSSP::uuid: dlopen(/var/folders/pk/4zjp95t11kd_6jl07c28fylm0000gq/T/par-7261766972616a/cache-4bb4ccf7e08f2b6f10e0671040fd9ab50fe064b2/1198e0d6.bundle, 0x0001): Library not loaded: /opt/local/lib/libuuid.16.dylib
  Referenced from: <7F83FC61-9F1C-34B5-83EB-975733F6295B> /private/var/folders/pk/4zjp95t11kd_6jl07c28fylm0000gq/T/par-7261766972616a/cache-4bb4ccf7e08f2b6f10e0671040fd9ab50fe064b2/1198e0d6.bundle
  Reason: tried: '/var/folders/pk/4zjp95t11kd_6jl07c28fylm0000gq/T//par-7261766972616a/cache-4bb4ccf7e08f2b6f10e0671040fd9ab50fe064b2/libuuid.16.dylib' (no such file), '/opt/local/lib/libuuid.16.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libuuid.16.dylib' (no such file), '/opt/local/lib/libuuid.16.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libuuid.16.dylib' (no such file), '/usr/lib/libuuid.16.dylib' (no such file, not in dyld cache) at <embedded>/DynaLoader.pm line 197.
 at <embedded>/PAR/Heavy.pm line 140.
Compilation failed in require at /var/folders/pk/4zjp95t11kd_6jl07c28fylm0000gq/T/par-7261766972616a/cache-4bb4ccf7e08f2b6f10e0671040fd9ab50fe064b2/inc/lib/PACMain.pm line 44.
BEGIN failed--compilation aborted at /var/folders/pk/4zjp95t11kd_6jl07c28fylm0000gq/T/par-7261766972616a/cache-4bb4ccf7e08f2b6f10e0671040fd9ab50fe064b2/inc/lib/PACMain.pm line 44.
Compilation failed in require at script/asbru-cm line 97.
BEGIN failed--compilation aborted at script/asbru-cm line 97.
```

**Comment by alecs** [comment]
@rrajp are you on M1/M2 ? Did you use the brew ossp or the ports one ? Did you change arch, are you multi arch ?

**Comment by kabhotz** [comment]
@alecs if you want I can test the brew package on Mac x86!

**Comment by alecs** [comment]
> @alecs if you want I can test the brew package on Mac x86!

There is no brew package for now, have been swamped with stuff so it's only the above package which isn't quite portable now. Tested on m1 and x86 and there are changes needed.

**Comment by Gr33nR10t** [comment]
@alecs have you some documentation on how to make Asbru work?

I assume that you have installed the Perl module manually; should be interesting to create a Brew recipe to make it work.
