### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by larrryfisherthefisherman** [asbru-cm/asbru-cm#734]
How do I scroll back through the history of my ssh session? When I use my mouse wheel it just flips between my last commands I ran, and there is no phyiscal scroll bar that I can see that I can use.

Thanks in advanced.

**Comment by gfrenoy** [comment]
There is nothing specific in Ásbrú for this, this is managed by your shell.  Typically, you would use the arrow keys to navigate through your history.

**Comment by gfrenoy** [comment]
Still, you may want to have a look to #739
