### ISSUE TITLE
Cant enter User / Password for new SSH-Connection

### ISSUE THREAD

**Issue by Frankstar** [asbru-cm/asbru-cm#735]
Cant enter User / Password for ssh connection.
its "greyed out"
Therefor i cant save it.

![image](https://user-images.githubusercontent.com/176627/99720730-71fcc880-2aae-11eb-96a8-e0d5f071f251.png)
![image](https://user-images.githubusercontent.com/176627/99720705-68736080-2aae-11eb-9812-143759de3ff2.png)

i must worked - cause i have alot of ssh connection added previously.
I dont know since when this occurs.

**Comment by gfrenoy** [comment]
I've been able to reproduce this if you switch the connection type to "Generic Command" ; this will gray out those option.  When re-select SSH or even if you close the connection settings and re-open them ; the options remain grayed out !

I'll try to fix this.

In the meantime, you'll simply need to restart Ásbrú and then it should work again.

**Comment by Frankstar** [comment]
oh you are right.
thats the problem. 
I tryed changing from generic-command to ssh.

didnt think of "restart asbru an try create a new ssh connection".
Good catch!

**Comment by gfrenoy** [comment]
Just pushed a change that should fix the issue.
It will be available for testing in our snapshot release in a couple of hours.
Let us know if this works for you !

**Comment by Frankstar** [comment]
oh - forgot to respond.
Fix worked / works!
