### ISSUE TITLE
lock and unlock functions

### ISSUE THREAD

**Issue by syco** [asbru-cm/asbru-cm#736]
Hi,
I'm sort of working on a new feature I want to propose, and that's bringing me on a long journey on the discovery of our friend PACTerminal..

So here's a question:
https://github.com/asbru-cm/asbru-cm/blob/b7ef45a16d4cc890dedb5e71aa690072da96ac65/lib/PACTerminal.pm#L617-L632
these lock and unlock functions seems to me they are only used in here:
https://github.com/asbru-cm/asbru-cm/blob/b7ef45a16d4cc890dedb5e71aa690072da96ac65/lib/PACMain.pm#L2394-L2449
but these _lockAsbru and _unlockAsbru are never used.

The lock button on the gui instead is hooked up to a function that doesn't exist:
https://github.com/asbru-cm/asbru-cm/blob/b7ef45a16d4cc890dedb5e71aa690072da96ac65/lib/PACMain.pm#L2105

Should we just remove this functionality?
Clearly no one has used it in a long time if this has passed unnoticed..
and also, I don't know what kind of security freezing the application can bring when the configuration file is in plain text..

---
edit:
I've put together a patch to remove it in case this is the preferred option:
[https://github.com/asbru-cm/asbru-cm/compare/loki...syco:loki-feature-nolock?expand=1](https://github.com/asbru-cm/asbru-cm/compare/loki...syco:loki-feature-nolock?expand=1)

**Comment by gfrenoy** [comment]
I don't personally use this option[1] but it should still be a working feature, see in the bottom bar:
![image](https://user-images.githubusercontent.com/981546/99874418-24847680-2be8-11eb-93d7-0b7acd10ab93.png)

It can also normally be activated from the tray icon.  To have that button enable you need to check "Protect with password" in the main preferences.

Now, it seems that some refactoring activities in loki have broken that feature !  I just pushed a commit to fix this, it is now working for me.

All in all, I don't believe we have to remove that part of the code, it was not intentionally broken :-/

Thanks for the good point though !  And I'm now looking forwarding understanding a bit more about the new feature you're working on :)

[1] And apparently, nobody using the loki branch either ;-p

**Comment by syco** [comment]
Well played!
I'll post something about it when it's working better, there's too many things to improve right now..
In the meantime, thanks for looking at this.
