### ISSUE TITLE
Can't see the passwd field in the networking settings for the Jump Host and the box for the Pseudo jump server

### ISSUE THREAD

**Issue by ovigia** [asbru-cm/asbru-cm#740]
Hello all,

i am unable to see the passwd field/box in the Networking Settings for the Jump Host as well as the check box for the Pseudo jump server

**To Reproduce**
1. Go to edit connection
2. Click on Network Settings
3. Can't see the passwd field for the passwd as well i cannot see the check box for the Pseudo jump server

**Expected behavior**
I should see both fields/check box

**Screenshots**

**Environment (please complete the following information):**
 - OS: RHEL 7.8
 - Ásbrú Version 6.2.2

**Comment by ovigia** [comment]
![Editing 'HanoverP01' : Ásbrú Connection Manager (v6 2 2)_001](https://user-images.githubusercontent.com/2945051/101166078-99679f80-362f-11eb-9293-70be0c84fadc.png)

**Comment by gfrenoy** [comment]
This field will be available in our next version (that will be 6.3.0) and that you can already test today on our 'loki' builds.
See https://docs.asbru-cm.net/General/Installation/ for instructions.

**Comment by ovigia** [comment]
> This field will be available in our next version (that will be 6.3.0) and that you can already test today on our 'loki' builds.
> See https://docs.asbru-cm.net/General/Installation/ for instructions.

oh... thanks a lot, since it was already in the docs i thought it was already implemented.

thank you
