### ISSUE TITLE
Disconnects from ESXi server SSH server

### ISSUE THREAD

**Issue by larrryfisherthefisherman** [asbru-cm/asbru-cm#741]
**Describe the bug**
When I connect to my ESXi server with ssh shortly after it will automatically disconnect me. I can run commands until that happens. I also can't paste into the ssh window anymore its just completely unhighlighted but I can pasted into every other program. I used another SSH client to get my work done so its not my ESXi server.

**To Reproduce**
1. Connect to SSH on ESXi
2. Wait a few seconds for it to disconnect you. 

**Expected behavior**
Stays connected and allows me to paste.

**Environment (please complete the following information):**
 - OS: Manjaro KDE
 - In Asbru it says 6.2.3 but the package in pamac says asbru-cm-git 6.2.2.r2.g39ab6f0-1

**Additional context**
Console output:

Password: 
The time and date of this login have been sent to the system logs.

WARNING:
   All commands run on the ESXi shell are logged and may be included in
   support bundles. Do not provide passwords directly on the command line.
   Most tools can prompt for secrets or accept them from standard input.

VMware offers supported, powerful system administration tools.  Please
see www.vmware.com/go/sysadmintools for details.

The ESXi Shell can be disabled by an administrative user. See the
vSphere Security documentation for more information.
[root@esxi:~] 	(in cleanup) 	(in cleanup)  at /usr/share/perl5/vendor_perl/Expect.pm line 1842 during global destruction.

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Fri Dec  4 11:02:42 2020)

**Comment by gfrenoy** [comment]
>  (in cleanup) (in cleanup) at /usr/share/perl5/vendor_perl/Expect.pm line 1842 during global destruction

This seems to suggest that we have a crash in [Expect](https://metacpan.org/pod/release/RGIERSIG/Expect-1.15/Expect.pod) but that will be too complicated to "guess" without additional information or being able to reproduce this.

If you can provide an access to an ESXi console I can use to troubleshoot this further, please contact me in private.

**Comment by larrryfisherthefisherman** [comment]
I don't know how to contact in private here on github, if you let me know I'll provide access to my local ESXi machine here at home.

**Comment by gfrenoy** [comment]
There's no private channel on GitHub but you can leave a message on our [IRC channel](https://webchat.st-city.net/#asbru-cm) as an example.

**Comment by gfrenoy** [comment]
Thanks for providing a temporary access.  The error message about Expect was misleading.  The command prompt of your ESXi (`[root@esxi:~]`) does not match the default command prompt configured in Ásbrú.

You should add the following to `Preference > Main Options > Advanced`: 
  `|^\[.*@.*:.*\]\s*$`

Let me know if this helps.

**Comment by larrryfisherthefisherman** [comment]
Will this potentially break other server connections?

**Comment by gfrenoy** [comment]
Very unlikely, this only detects when the first command prompt is found (and hence that the connection status can be set to "connected").
