### ISSUE TITLE
Ctrl-Shift-R closes the terminal

### ISSUE THREAD

**Issue by toptnc** [asbru-cm/asbru-cm#744]
**Describe the bug**
I don't know if this is a bug or a feature, but when I press Ctrl-Shift-R (reverse search in bash) the terminal windows closes without warning or confirmation.

I have searched in preferences the keybindings options but haven't found anything apart of Ctrl-F4.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a terminal, remote or local
2. Press Ctrl-Shift-R
3. The window closes

**Expected behaviour**
Reverse i-search in bash

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Ásbrú Version 6.2.2

**Comment by gfrenoy** [comment]
It's a feature :smile: 

By default, this keybinding is associated to the 'Restart Connection' action.

![image](https://user-images.githubusercontent.com/981546/101992833-4d170200-3cb6-11eb-820e-d01e1e7d403f.png)

So you'll need to remove (or change) the keybinding to `Ctrl+Shift+r`.
(Note that we display `Ctrl+Shift+r` as `Ctrl+R` (capital r) that is not the same as `Ctrl+r`)

**Comment by toptnc** [comment]
Were are that keybindings defined? I can't find them. It is supposed to be in a tab under 'Keepass integration' but my version doesn't have it. My version is 6.2.2

**Comment by gfrenoy** [comment]
Ah indeed, keybindings management is only available on our like branch right now (the "to be" 6.3.0)... See https://docs.asbru-cm.net/General/Installation/.

**Comment by toptnc** [comment]
Ok. I'll wait then.

Thank you.
