### ISSUE TITLE
Ásbrú's terminal uses X11 PRIMARY clipboard, ignores CLIPBOARD

### ISSUE THREAD

**Issue by ValdikSS** [asbru-cm/asbru-cm#746]
**Describe the bug**
Ásbrú's terminal copy and paste text only from/to X11 PRIMARY clipboard ("middle-click clipboard"), and can't handle CLIPBOARD clipboard (the common one, which is used by ctrl+c/ctrl+v).
I can't copy text from the notepad selected with ctrl+a and copied with with ctrl+c (or with right click → copy) and paste it to Ásbrú's **terminal window** — ctrl+shift+v and right click → paste inserts PRIMARY clipboard contents.

Non-terminal window (all text fields) handle copy/paste as expected.

**To Reproduce**
1. Open terminal window (by connecting to a server for example)
2. Copy text from text editor by selecting it with ctrl+a and pressing ctrl+c or right click → copy (make sure your text editor does not copy/sync to PRIMARY).
3. Try to paste text to Ásbrú's terminal window.

**Expected behavior**
Ásbrú's terminal window pastes what you copied from the notepad

**Screenshots**
Please watch the video.

https://user-images.githubusercontent.com/3054729/103098417-c5b58100-461b-11eb-9e48-418cbfd344ab.mp4

**Environment (please complete the following information):**
 - OS: Fedora 33
 - Ásbrú Version: v6.2.2, from official cloudsmith repository (`asbru-cm-6.2.2-1.fc33.noarch`)

**Additional context**
Also check another bug: #747

**Comment by beliys** [comment]
I also reproduced this problem. As a temporary solution, I used the "Synchronize contents of the clipboard and selection" option in Klipper (I use KDE).
https://userbase.kde.org/images.userbase/thumb/a/aa/Klipper-conf.png/677px-Klipper-conf.png

**Comment by gfrenoy** [comment]
See #673.  Would you be able to test the loki branch and let us know if this works as expected ?

Then we should probably think about releasing 6.3 ;-p

**Comment by gfrenoy** [comment]
@ValdikSS Can you let me know if 6.3.0 is helping ?

**Comment by ValdikSS** [comment]
Yes, seems fixed in 6.3.0.

**Comment by ValdikSS** [comment]
I'm afraid this fix introduced new issue (regression): copying with CTRL+SHIFT+C now propagates to the terminal (as CTRL+C). This leads to current program termination when you're trying to copy the text.
