### ISSUE TITLE
Ásbrú's terminal automatically copies selection to clipboard

### ISSUE THREAD

**Issue by ValdikSS** [asbru-cm/asbru-cm#747]
**Describe the bug**
Ásbrú's terminal copies selected text into the clipboard (X11 CLIPBOARD), or automatically syncs PRIMARY buffer to CLIPBOARD buffer.

**To Reproduce**
1. Open terminal window (by connecting to a server for example)
2. Select any text from the terminal window, do NOT press right click → copy or ctrl+shift+c.
3. Try to paste text from the clipboard with ctrl+v or right click → paste to text editor
4. Selected (but not copied) text from the terminal window pastes to text editor.

**Expected behavior**
Ásbrú's terminal should copy text only when right click → copy or ctrl+shift+c is pressed.

**Screenshots**
Please watch the video.

https://user-images.githubusercontent.com/3054729/103098746-f649ea80-461c-11eb-8531-6420838695b8.mp4

**Environment (please complete the following information):**
 - OS: Fedora 33
 - Ásbrú Version: v6.2.2, from official cloudsmith repository (`asbru-cm-6.2.2-1.fc33.noarch`)

**Additional context**
Also check another bug: #746

**Comment by hanspr** [comment]
Uncheck the option and will work as you want, others may prefer the current behaviour, saves a lot of time

![imagen](https://user-images.githubusercontent.com/1572396/118967595-8708c600-b930-11eb-937c-9b11ba693f4a.png)
