### ISSUE TITLE
Force LANG=en_US.UTF-8 on startup

### ISSUE THREAD

**Issue by shaygover** [asbru-cm/asbru-cm#748]
**Describe the bug**
Asbru went RTL. My system language is RTL but asbru implementation is problematic. How do I change it back to LTR and English?

**To Reproduce**
1. Start Asbru with RTL locale

**Expected behavior**
Ability to change language.

**Environment (please complete the following information):**
 - OS: Arch
 - Ásbrú Version 6.2.2

**Comment by ValdikSS** [comment]
Try
`LANG=en_US.UTF-8 asbru-cm`

**Comment by shaygover** [comment]
Yea. That's what I did. But I would like to get a software choice.

**Comment by gfrenoy** [comment]
Ásbrú has not been designed to support multiple languages.
It can be changed for sure but it's a major change that will require time and, hopefully, help.

In the meantime, should we force the "LANG" environment variable to `en_US.UTF-8` at the application start up ?  Does that have any side effect for you ?

**Comment by shaygover** [comment]
Forcing it is better currently as the translation is minimal and RTL is
just a mess.

**Comment by gfrenoy** [comment]
@shaygover What is the value of your `LANG` variable ?  [so I can better understand how it looks...]

**Comment by shaygover** [comment]
he_IL.UTF-8

**Comment by gfrenoy** [comment]
I pushed a change to force locale.  I tried to reproduce your issue with he_IL.UTF-8 but could not really see the difference :-/

A new build for 6.3 will be ready in a couple of hours.  Will you let me know if this makes a difference for you ?

Thanks.
