### ISSUE TITLE
rdp connection over xfreerdp doesn't work with special characters in  password

### ISSUE THREAD

**Issue by yennor** [asbru-cm/asbru-cm#75]
I tried to do a rdp connection using xfreerdp.
Somebody made me the favour and gave me a password with some special characters.
Following characters are in the password:
```
:
=
>
::
```

When I try to use the password from the command line I need to quote it, then it works.
When I try to use it in pac, it can not connect. It just creates an empty session log. When I replace the password with "asdf" a session log is created.

**Comment by gfrenoy** [comment]
Thanks for the feedback yennor.

I had a very quick look. It looks like the password is not properly quoted when building the command line.  See lines [956 and 957 of pac_conn](https://github.com/asbru-cm/asbru-cm/blob/master/lib/pac_conn#L956).

Anyone to propose a PR for this ?
