### ISSUE TITLE
asbru asks me to type keepassxc password everytimes when I run connection. However master password already set in global settings.

### ISSUE THREAD

**Issue by ynasida** [asbru-cm/asbru-cm#750]
Hello,

asbru asks me to type keepassxc password everytimes when I run ssh connection. However master password is set in global settings already. I can press cancel and connection will be established (using master password already set) but It's the pain to press cancel for every new connection i run.

Please advice how to avoid this.

Thanks.

**Comment by gfrenoy** [comment]
Can you specify the Ásbrú version you are using ?

And did you check #694 ?  There are some clues there to troubleshoot this further.

Thanks.

**Comment by ynasida** [comment]
It's v6.2.2 installed at linux mint 20 using official instruction form Ásbrú site.

I do not see any errors thus  #694  is not related.

My question is how to get asbru stop  asking the password at this window (attached) ? 

![2021-01-05_18-15](https://user-images.githubusercontent.com/34458485/103663414-1e710c00-4f82-11eb-8b62-2cb0ebcebc12.png)

Master password is set already (global preferences).

**Comment by ynasida** [comment]
Fixed. Sorry that was because of my custom changes with location of asbru.yml file. 
Issue happens in case I move this file to other folder (crypted)
I don't like that this file keeps master password of keepassxc.

**Comment by gfrenoy** [comment]
Thanks for the additional information.  I can indeed reproduce this with 6.2.2 but it looks to be fixed on the loki branch (the "to be" 6.3.x).  Would you mind giving it a try ?

**Comment by ynasida** [comment]
Cool. Yes, it's working at 6.3.0, thanks.
