### ISSUE TITLE
Clusters view appears empty on startup

### ISSUE THREAD

**Issue by Random-Chain** [asbru-cm/asbru-cm#753]
I've set my starting tab to Clusters under Preferences  > Main > Look and Feel.
When I first open Asbru, the Clusters tab is empty. 
Looks like it doesn't load the list properly until I switch to another view (like Connections) and go back, then I see the clusters list.
Just a small cosmetic issue, but it's a bit annoying.

**Environment:**
 - OS: Pop!_OS 20.04
 - Ásbrú Version: 6.2.2-1

**Comment by gfrenoy** [comment]
Confirmed and reproduced!  Thanks for your feedback and helpful description.

**Comment by gfrenoy** [comment]
The last commit does fix the issue.  You can test this on the loki and snapshot releases.

It will be released in 6.3.1 soon.

Feel free to re-open if it should not work for you.
