### ISSUE TITLE
Make port number optional (to support for ~/.ssh/config defined hosts)

### ISSUE THREAD

**Issue by cebas** [asbru-cm/asbru-cm#754]
I have all my ssh connections defined in ~/.ssh/config file. To connect to a host I just use "ssh host_alias" from the terminal.
It would be very useful to use those same connections config from asbru.
You are very near...
I tried to set an alias as a host name on asbru and it almost worked because it used the port and user from it's own config. 
The only thing you need to do is accept an empty port number and empty user in asbru connection configuration. They'll be picked from the config file as the host name is being picked now.

**Comment by gfrenoy** [comment]
For user, did you try the "Manual" authentication mode ?

For port number, yes, it is indeed a mandatory one today ; I believe we can make this optional.  Or maybe accept "0" that would mean "no port number".  Would that work for your use case ?

**Comment by gfrenoy** [comment]
@cebas Can you give the loki branch a try ?  I made a change, if you set the port number to "0", it will not be specified in the command line.  With the "manual" authentication, you should be able to easily use your entries in your `~/.ssh/config` file.

**Comment by cebas** [comment]
Setting the port to 0 works as it doesn't set the port to ssh command line. But the connection fails. 
It opens a new tab, starts the connection and login, and then it closes the tab.
The command line is created correctly (ssh -x host_alias), and typing that command line in gnome terminal, of course works fine.
So there must be something else. Do you have any logs I can send you?

**Comment by gfrenoy** [comment]
Good for the default port :)

The screencast is "flickering" but it looks to eventually connect.  Do you have a screencast when it fails ?

Note: about the setenv()/putenv() error message, check #432.

**Comment by cebas** [comment]
The flicker was made by me double clicking to connect, and the connection
failing and closing the tab. The last try succeeded.

Any logs to check why it's not working?

**Comment by gfrenoy** [comment]
> The flicker was made by me double clicking to connect, and the connection failing and closing the tab. The last try succeeded.

Aah, OK, I understand better now.  You can enable the debug in the preferences and start Ásbrú from a command line to see if you can spot any particular message.

But can we create a separate issue about this, I'd like to close this one ?  Or do you believe it's related to the default port ?

Thanks.

**Comment by cebas** [comment]
I cannot find the debug option. I enabled the "Expect DEBUG" options, but no sure if it's what you want.
Running asbru from a terminal dooesn't help. The last message shown is "INFO: Using Gnome tray icon", and nothing more during connection.
I switched off the option to close the terminal after diconnect to avoid the flicker and be able to see the messages.
Within the terminal, I see these messages:

> CONNECTING WITH ltsp 2 - VIP (Tue Feb  9 19:51:47 2021)
> 
> GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
> GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
> GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.
> LOG **: Initializing XApp GtkModule at /usr/share/perl5/Gtk3.pm line 555.
> LOG **: Adding a Favorites shortcut to GtkPlacesSideBars at /usr/share/perl5/Gtk3.pm line 555.
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: !!_PAC_AUTH_[asbru_PID{729239}_n3]!!
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: GET_TITLE:
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: SPAWNING:ssh -x ltsp
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: SPAWNED:'ssh -x ltsp' (PID:730287)
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: CONNECTING:Manual authentication requested
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: TITLE:ltsp 2 - VIP
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: CONNECTED
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: DISCONNECTED
> 
> DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Tue Feb  9 19:51:47 2021)
> 

thanks

**Comment by cebas** [comment]
> But can we create a separate issue about this, I'd like to close this one ? Or do you believe it's related to the default port ?

can't say if they are related, until we find why it's closing the connection

**Comment by gfrenoy** [comment]
> can't say if they are related

It is very unlikely related.  If you want to confirm this, try to configure dedicated entries (with and without default port).  They behave the same way for me.

We would like to releave 6.3 asap so let me close this for now and let's create another dedicated issue to troubleshoot the disconnection.
