### ISSUE TITLE
"Linux" type function keys support as putty does

### ISSUE THREAD

**Issue by cebas** [asbru-cm/asbru-cm#755]
I connect to a Linux server that has a somehow strange configuration to run some old ncurses programs which use function keys.
I use Linux version of putty with "Linux" function keys setting to be able to use function keys.
Can we have the same ability in asbru?

See the putty mentioned setting here:  https://imgur.com/a/VZxAE5C

**Comment by gfrenoy** [comment]
If you can give more details about what that "Linux function keys" exactly mean in [VTE](https://wiki.gnome.org/Apps/Terminal/VTE), I guess we can add the same option, yes, certainly.

**Comment by cebas** [comment]
I couldn't find anything related on VTE docs. Gnome terminal didn't have any option for this. So I guess nothing can be done with VTE api.
Maybe this can be done with some kind of macro or definition of what function keys must send. Take a look at putty docs: 

https://the.earth.li/~sgtatham/putty/0.74/htmldoc/Chapter4.html#config-keyboard

> 4.4.3 Changing the action of the function keys and keypad
> 
> This option affects the function keys (F1 to F12) and the top row of the numeric keypad.
> 
> In the default mode, labelled ESC [n~, the function keys generate sequences like ESC [11~, ESC [12~ and so on. This matches the general behaviour of Digital's terminals.
> **In Linux mode, F6 to F12 behave just like the default mode, but F1 to F5 generate ESC [[A through to ESC [[E. This mimics the Linux virtual console.**
> In Xterm R6 mode, F5 to F12 behave like the default mode, but F1 to F4 generate ESC OP through to ESC OS, which are the sequences produced by the top row of the keypad on Digital's terminals.
> In VT400 mode, all the function keys behave like the default mode, but the actual top row of the numeric keypad generates ESC OP through to ESC OS.
> In VT100+ mode, the function keys generate ESC OP through to ESC O[
> In SCO mode, the function keys F1 to F12 generate ESC [M through to ESC [X. Together with shift, they generate ESC [Y through to ESC [j. With control they generate ESC [k through to ESC [v, and with shift and control together they generate ESC [w through to ESC [{.
>

**Comment by gfrenoy** [comment]
Thanks for the check in VTE & putty documentation, very useful.

I would indeed think it is something we should be able to manage through customization rather that "hard coded" in Ásbrú.  There's apparently so many "flavours" that it will be hard for the project to maintain them all.

Maybe we can do this using a "Remote Command" (see [doc](https://docs.asbru-cm.net/Manual/Preferences/RemoteCommands/)) in the connection settings assiociated with some keybidings ?
![image](https://user-images.githubusercontent.com/981546/105875676-61148a00-5ffe-11eb-9e8e-68153ad481e9.png)

But as shown in the above screenshot, we'll likely need to add some additional pseudo-keywords to generate the correct sequence ...

Any further analysis or comment will be welcome...

**Comment by cebas** [comment]
I think it's a good way to do it. I don't like hardcoding either.

Some suggestions: 
1) You don't need to define pseudo-keywords. Just accept some escaping scheme like \x1B or \27 for ESC, in the macro definition.
2) The macros should be defined application wide, and then used in the connection definition. Because this macros would be used in several connections (at least in my use case). I connect to the same host with different users and/or options. I wouldn't want do define the macros within the connection definition for each one.
3) Nice to have: the macros can be defined in a group and then this group used in the connection. In my case, I need 5 macros defined at application level, and then 5 macros used in each connection. It'll be easier if I can define a group named "Linux function keys" having the 5 macros, and then, just use the group in the connection definition.
4) Thinking in possible other scenarios, the connection may need to use more than one group at a time.

**Comment by hanspr** [comment]
I'll take this.

There are basically , 7 Function keys configurations according to this table.

![imagen](https://user-images.githubusercontent.com/1572396/141596662-d901b236-48f1-4fe7-8f97-2356ff9efa8c.png)

And we already have a very cluttered tab with terminal options.

The option at the bottom takes too much space (character encoding), I can shrink it, and then place a selection box to select one of the possible terminal variations, and then implement the translation of the keys in the PACKeybindings.pm package. I have already tested and it works.

![imagen](https://user-images.githubusercontent.com/1572396/141596725-12fd16f5-4574-47bc-80f2-0ff793faa8fd.png)
