### ISSUE TITLE
GLOBAL commands doesn't work in cluster when triggered from button bar

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#758]
1. create cluster with nodes (ssh)
2. define global command (eg: ls)
3. enable global commands as buttons (show macros: as buttons, show global commands in terminals)
4. start/connect to cluster
5. click on your defined global command button (on button bar)

command is directed only to active window. it is not executed in rest of the cluster. this was working before and stopped (i don't know when - don't use it often). also if u click to open context menu in the terminal window and choose your global command from there then it works fine - in all terminals of the cluster. playing with 'sending THIS/CLUSTER' (button bar) doesn't change anything.

**Expected behavior**
global commands executed in whole cluster when triggered from button bar

**Environment (please complete the following information):**
Debian 10, xfce
latest loki

**Comment by gfrenoy** [comment]
Confirmed.  Let me see if I can fix this...

**Comment by gfrenoy** [comment]
Just push a change.  The build is ongoing and will be available soon.

There are two main changes:
- I forced the default value of 'THIS/CLUSTER', according to the fact that the terminal is part of a cluster or not
- If CLUSTER is selected, the command is sent to all members of the cluster.

Let us know if this helps.

**Comment by vibo69** [comment]
yup. problem solved ;)
