### ISSUE TITLE
Add feature to see RDP connection log (especially errors) directly in asbru-cm

### ISSUE THREAD

**Issue by yennor** [asbru-cm/asbru-cm#76]
Very often when I try to create a new rdp connection they don't directly work out of different reasons (wrong password, certificate, other errors).
Unfortunately asbru doesnt show why a connection doesn't work, only an empty screen is shown.
It is possible to activate session logging, and read the log afterwards, but it is a quite uncomfortable solution (and at the begining I didn't even know that log exists).
So if asbru could somehow show messages, why a connection can not be established, eg. just directly show the output of xfreerdp, would make live a lot easier.
This could be in a separate window. or just show the messages in the rdp window, until the rdp connection is established.

**Comment by gfrenoy** [comment]
This is for sure a good idea :-)

Not sure how to do this though.  We first need to collect the command output and probably display them in a sub-window of the newly created tab.  Any proposal will be warmly welcome.

**Comment by park-land** [comment]
Could it be handled in the same way as you currently do rdesktop? Ie: it first opens in a terminal screen and that is replaced by the RDP session when it has successfully connected.

**Comment by gfrenoy** [comment]
While looking at #181, I now better understand how that RDP connection is embed in Ásbrú.

I indeed would like to have another window that collects a kind of "log" about what is happening.

Stay tuned...

**Comment by gfrenoy** [comment]
@park-land @yennor Can you try the latest version on the [gtk3 branch](https://github.com/asbru-cm/asbru-cm/tree/gtk3) ?

On this new version, if something wrong happens while establishing the RDP connection, it will revert back to the VTE terminal spawning the RDP process and display the (hopefully) relevant error messages:

![image](https://user-images.githubusercontent.com/981546/69906827-db7d5600-13c9-11ea-8982-63edbb4decb8.png)

Let me know if it helps !
