### ISSUE TITLE
after connect can not execute command of remote vm (asbru 6.2.3)

### ISSUE THREAD

**Issue by donixa** [asbru-cm/asbru-cm#761]
Lubuntu 20.10
Asbru 6.2.3

after connected/logged in as root of remote vm, I simply can not execute any command,
thats it,
pressing enter just put cursor down the line, and so on,
Am I missing something?

**Comment by gfrenoy** [comment]
What is your target system ?

You might need to tweak the `Command Prompt` parameter.  If it is not match, if would behaves as you describe.
See https://docs.asbru-cm.net/Manual/Preferences/MOAdvanced/

If you can, please provide a screenshot or so more information that will help us troubleshooting this further.

**Comment by donixa** [comment]
OK I can see the problem now, 
I was using https://github.com/Bash-it/bash-it for prompt theme,

When I revert back to original, Asbru (connected session) is working again,

So in Asbru, I have to adjust https://docs.asbru-cm.net/Manual/Preferences/MOAdvanced/
every time I change my prompt theme?

**Comment by gfrenoy** [comment]
> every time I change my prompt theme?

No, the `Command Prompt` is a regular expression that should capture all your cases.

> I see I may have to read and review the regex manualy

Yes but I can probably help.

How does you prompt look like ?

**Comment by donixa** [comment]
I use this (currently)
https://github.com/Bash-it/bash-it/tree/master/themes/bobby

nano /root/.bashrc
# Lock and Load a custom theme file.
# Leave empty to disable theming.
# location /.bash_it/themes/

export BASH_IT_THEME='bobby'

root# exec bash

![image](https://user-images.githubusercontent.com/1473100/107183595-a6c74e80-6a11-11eb-8acf-0ddf9daed3ec.png)

**Comment by donixa** [comment]
I just simply use different themes from bash-it such as "slick" like below they are just more than enough for me,
it just work out of the box,

perhaps if you could explain abit more detail how to handle the situation in doc? thanks for replying my issue,

![image](https://user-images.githubusercontent.com/1473100/107403952-a0ae9c00-6afd-11eb-820f-a8ec7f220319.png)

**Comment by gfrenoy** [comment]
What you need to do is to add the arrow (→) in the `Command Prompt`.

So changing the default prompt from:

```
[#%\$>]|\:\/\s*$
```
to 

```
[#%\$>→]|\:\/\s*$
```

And, yes, a better documentation could help.  A PR is always welcome :)

Or an alternative way to detect that we are "connected" since that `Command Prompt` thing is really not reliable on all environment.
