### ISSUE TITLE
Possibility to launch more than one instance of asbru

### ISSUE THREAD

**Issue by lephiloux** [asbru-cm/asbru-cm#763]
Hi,
It would be nice to have the possibility to start more than one instance.
currently when i try to start a second instance i got this

INFO: Ásbrú is already running.
INFO: No more instances allowed!

It would be nice to be able to launch a second instance when working with dual screen configuration.

Kr
Philippe

**Comment by syco** [comment]
Hi,

have you tried this option?
![image](https://user-images.githubusercontent.com/54575/107400770-0f89f600-6afa-11eb-9fb4-f06ea966a782.png)

**Comment by lephiloux** [comment]
Doesn't seen this one ;-)


Le mar. 9 févr. 2021 à 18:13, Alberto Rinaudo <notifications@github.com> a
écrit :
