### ISSUE TITLE
Ping/Reconnect option in disconnected windows

### ISSUE THREAD

**Issue by dkavlakov** [asbru-cm/asbru-cm#764]
Hello

I work in environment where multiple machines have to be restarted occasionally and constantly find myself rebooting one, opening console to ping it's IP to see when it is back, then switching back to reconnect. Most likely I'm far from being the only one to have to do this. A new Ping/Reconnect option in disconnected windows may be usable in such cases. I imagine it as alternative to current "Enter to reconnect", that starts to ping remote IP and after receiving for example 10 responses (may be configurable) tries to reconnect. Waiting for more than one response is usable, as typically some time passes between network and server initialization.

**Comment by gfrenoy** [comment]
What about the `reconnect on disconnection` option ?

![image](https://user-images.githubusercontent.com/981546/107878413-c7404e80-6ed2-11eb-960b-a71d2c330087.png)

It does not ping but will try several times until it can reconnect.  Waiting longer and longer between each attempt.

**Comment by gfrenoy** [comment]
See also suggestion #728
