### ISSUE TITLE
ctrl+alt+s opens ssh instead of sftp when autossh is enabled

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#766]
Hi, as in topic. there is not really more to add ;)

**Comment by gfrenoy** [comment]
> there is not really more to add

well, don't believe it's important for that case but the version you are using is always good to specify.

That being said, we were indeed cloning the current connection, including the fact that the actual command is replaced by autossh.  I disabled autossh on the cloned connection.  According to my tests it looks to work.

Let us know if you still have the same issue on the next loki build (please wait 30 min. before it is completed).
