### ISSUE TITLE
Connection fails without any error

### ISSUE THREAD

**Issue by gfrenoy** [asbru-cm/asbru-cm#767]
_Originally posted by @cebas in https://github.com/asbru-cm/asbru-cm/issues/754#issuecomment-767536892_

The connection fails. 
It opens a new tab, starts the connection and login, and then it closes the tab.
The command line is created correctly (ssh -x host_alias), and typing that command line in gnome terminal, of course works fine.
So there must be something else. Do you have any logs I can send you?

Edit: doing some more tests, I found that this not always fails. Some times it works fine, and others don't.
screencast: https://youtu.be/yUN6fqLykho

**Comment by gfrenoy** [comment]
_Originally posted by @cebas in https://github.com/asbru-cm/asbru-cm/issues/754#issuecomment-776300236_

I cannot find the debug option. I enabled the "Expect DEBUG" options, but no sure if it's what you want.
Running asbru from a terminal dooesn't help. The last message shown is "INFO: Using Gnome tray icon", and nothing more during connection.
I switched off the option to close the terminal after diconnect to avoid the flicker and be able to see the messages.
Within the terminal, I see these messages:

> CONNECTING WITH ltsp 2 - VIP (Tue Feb  9 19:51:47 2021)
> 
> GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
> GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
> GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.
> LOG **: Initializing XApp GtkModule at /usr/share/perl5/Gtk3.pm line 555.
> LOG **: Adding a Favorites shortcut to GtkPlacesSideBars at /usr/share/perl5/Gtk3.pm line 555.
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: !!_PAC_AUTH_[asbru_PID{729239}_n3]!!
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: GET_TITLE:
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: SPAWNING:ssh -x ltsp
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: SPAWNED:'ssh -x ltsp' (PID:730287)
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: CONNECTING:Manual authentication requested
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: TITLE:ltsp 2 - VIP
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: CONNECTED
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: DISCONNECTED
> 
> DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Tue Feb  9 19:51:47 2021)

**Comment by gfrenoy** [comment]
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: CONNECTED
> [asbru_conn(730287)][ltsp 2][ltsp 2 - VIP]: DISCONNECTED

It seems that the server did decide the disconnection ... Do you have access to the logs on the server side to understand why ?

**Comment by cebas** [comment]
> It seems that the server did decide the disconnection ... Do you have access to the logs on the server side to understand why ?

I have 3 different servers (CentOS 5.11, Ubuntu 14.04 and Ubuntu 18.04). The results are the same in all of them.
My client is a Linux Mint 20 latest version.
asbru is loki 6.3.0~1612915067-1

When connecting and disconnecting succesfully, there are several events in the logs noting the connection. When the connection fails, nothing is being logged. So, my guess is that is something within asbru.
In all cases, I'm using certificates to login. No passwords are being used.

I also tried to set ssh LogLevel to DEBUG3 and nothing shows when the connection fails:

[asbru_conn(963690)][facumate][facumate - VIP]: SPAWNED:'ssh -x -o "LogLevel=DEBUG3" facu' (PID:963690)
[asbru_conn(963690)][facumate][facumate - VIP]: CONNECTING:Manual authentication requested
[asbru_conn(963690)][facumate][facumate - VIP]: TITLE:facumate - VIP
[asbru_conn(963690)][facumate][facumate - VIP]: CONNECTED
[asbru_conn(963690)][facumate][facumate - VIP]: DISCONNECTED

Let me know how can I help debug this issue.

**Comment by gfrenoy** [comment]
> do suspect the `-o "PreferredAuthentications=password,keyboard-interactive"` is conflicting with what you have in your `.ssh/config` file, isn't it ?

Wrong guess, I see in your debug that you have disabled it.

I made some more experiments and I ended up with the same behaviour as you described ... Not sure to understand this correctly yet but at least I can reproduce it...

**Comment by cebas** [comment]
> What happens if you copy/pasted the generated command line in a terminal (see in `Connection` > `Advanced Parameters` > `Get Command line`) ?

I've tried several times copy/pasting the command line shown on the terminal on yellow during connection, and it worked fine.

**Comment by cebas** [comment]
> I made some more experiments and I ended up with the same behaviour as you described ... Not sure to understand this correctly yet but at least I can reproduce it...
great!

happy debugging!

**Comment by cebas** [comment]
I have one new strange behaviour:

In a connection I have with hostname and port explicitily set - not using ssh config for that, and having selected Manual Authentication on asbru to let ssh use the certificates, the connection failed. This didn't happen before (AFAIK).
Now I'm using loki 6.3.0-1613220846-1 that was updated yesterday.

So I'm guessing that the default port or host alias has nothing to do here.

[asbru_conn(1583664)][facumate full][facumate full - VIP]: SPAWNED:'ssh -p nnnn -x -o "LogLevel=DEBUG3" actual.host.name' (PID:1583664)
[asbru_conn(1583664)][facumate full][facumate full - VIP]: CONNECTING:Manual authentication requested
[asbru_conn(1583664)][facumate full][facumate full - VIP]: TITLE:facumate full - VIP
[asbru_conn(1583664)][facumate full][facumate full - VIP]: CONNECTED
[asbru_conn(1583664)][facumate full][facumate full - VIP]: DISCONNECTED

**Comment by gfrenoy** [comment]
>  I'm guessing that the default port or host alias has nothing to do here.

Yes, I'm sure also.

It's the temporary file that is created to spawn the terminal that is - sometimes - deleted too quickly ...

If you are looking for a quick fix, comment out the line `unlink($cmd_file);` in `asbru_conn`.

**Comment by gfrenoy** [comment]
The last fix changes the way we delete that temporary file.  Hopefully more robust.

Let us know if it works better for you !

And thanks a lot for your great feedback.

**Comment by cebas** [comment]
> The last fix changes the way we delete that temporary file. Hopefully more robust.
> 
> Let us know if it works better for you !
> 
> And thanks a lot for your great feedback.

commenting the unlink definitely solve the problem. thanks for the workaround!
when will the new version hit the repos?

btw: wouldn't be cleaner to create temp files in system temp directory instead in user config directory?

**Comment by cebas** [comment]
> And thanks a lot for your great feedback.
you're welcome
thanks for your responsiveness!

**Comment by gfrenoy** [comment]
> when will the new version hit the repos?

It usually takes between 15 min and 1h to rebuild everything.  You'll see a green check near the commit when it's done:
![image](https://user-images.githubusercontent.com/981546/107880893-e8f50200-6ee1-11eb-9f6a-5fe62608e3ff.png)

Should be done now.  Let me know if you still have the same issue with the latest build.

> wouldn't be cleaner to create temp files in system temp directory instead in user config directory?

Don't see really pros/cons of each option.  At this stage, I'd say: if it works, don't fix it :-p

**Comment by cebas** [comment]
> Should be done now. Let me know if you still have the same issue with the latest build.
it's working now. thanks

> > wouldn't be cleaner to create temp files in system temp directory instead in user config directory?
> Don't see really pros/cons of each option. At this stage, I'd say: if it works, don't fix it :-p

Sure, it works, but that doesn't mean it's a clean or optimal solution.
I prefer to put binaries, data and configuration, each on its own place. I think this is not a matter of preferences, anyway.
But this is not the place to discuss about programming best practices.

**Comment by gfrenoy** [comment]
> this is not the place to discuss about programming best practices.

Not on this particular issue but this project will be happy to follow best practices !  Feel free to open a new issue that would explain pros/cons of the best place for temporary files ; and what needs to be changed.

In the meantime, let's close this one.

It was really a great feedback and problem description for a problem that nobody really noticed, thanks a million !

**Comment by cebas** [comment]
you're welcome

**Comment by DiManKWWIDAL** [comment]
可以支持中文显示配置界面吗
