### ISSUE TITLE
Window gets centered on screen on open connection

### ISSUE THREAD

**Issue by cebas** [asbru-cm/asbru-cm#768]
Every time I connect to any host I have saved, with double click or with the Connect button, asbru's window gets centered on the screen.

I have Linux Mint 20.1 Cinnamon
I hava a two monitors setup. This issue happens on both monitors te same way.

**Comment by gfrenoy** [comment]
I'm using a tiling window manager, don't really understand what is wrong.  Would you mind showing this on a video or with some screenshots ?  Thanks.

**Comment by cebas** [comment]
sure, give your email or telegram to send you the video

**Comment by gfrenoy** [comment]
Check our [IRC channel](https://www.asbru-cm.net/support.html) ; be patient but an answer will eventually be given :)

**Comment by cebas** [comment]
I don't use IRC, and don't want to post a video with personal information in this public place. Please give me a more private way of sharing the video with you.

**Comment by gfrenoy** [comment]
I meant: contact me on IRC to have those private details...

**Comment by gfrenoy** [comment]
Thanks for the additionial information, it looks like something we should improve !

**Comment by gfrenoy** [comment]
This was actually a regression introduced [here](https://github.com/asbru-cm/asbru-cm/commit/df70d444ba17073d3646bf8e43fbf83a0732b2c5) ; I made a change that should fix the issue.

Let us know if it works for you.

**Comment by cebas** [comment]
it's fixed
I'm on loki 6.4.0-1613481957
