### ISSUE TITLE
Can't close tabbed terminal with its keybind

### ISSUE THREAD

**Issue by cebas** [asbru-cm/asbru-cm#769]
I have a terminal opened and hit the assigned keybind for _Terminal/Close Terminal_ (ctrl+w) and nothing happens.
I tried to assing a new bind to that action, but the result is the same.
This happens in opened working terminals, and with disconnected terminals too.

Linux Mint 20.1 Cinnamon

**Comment by gfrenoy** [comment]
Good catch, thanks!

It looks like, since we implemented the custom keybindings, that shortcut was only working for non tabbed terminal.  This should be fixed now.

Feel free to re-open if this should not be the case.

**Comment by cebas** [comment]
confirm it's working. thanks
