### ISSUE TITLE
Better error message handling when KeepassXC lookup values got changed.

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#770]
Hi Team ...

Let's say that we have an SSH session defined on Asbru like follows:

![image](https://user-images.githubusercontent.com/37672088/107882428-2a38e200-6ee1-11eb-89dd-7d25280c7d41.png)

Then go to KeepassXC and change the Group or the Title of the stored credential used by the Asbru session.
For this test purpose I changed the Title field value from Test to Test1 on KeepassXC:

![image](https://user-images.githubusercontent.com/37672088/107882497-99aed180-6ee1-11eb-8068-bfdf8dfea457.png)

Once we try to use the Asbru session after the above change on KeepassXC, the connection fails because the lookup on KeepassXC fails, and this message is displayed:

![image](https://user-images.githubusercontent.com/37672088/107882551-e1cdf400-6ee1-11eb-93d8-825c0ca85276.png)

Guess we can handle this better ;-)

Thanks and stay safe !

**Comment by gfrenoy** [comment]
> Guess we can handle this better ;-)

For sure.  Let's mark this for 6.4.  Thanks for the feedback !

**Comment by gfrenoy** [comment]
Made some cosmetic changes, feel free to re-open if you were thinking about something different.

**Comment by popxunga** [comment]
Hi @gfrenoy ...
Looks good enough :-D
Thanks a lot !
