### ISSUE TITLE
nmap is now a dependency?

### ISSUE THREAD

**Issue by SwampRabbit** [asbru-cm/asbru-cm#776]
Hello, I package ASBRU-CM for MX Linux.  First of all, thank you for updating the control file under dist/deb/debian.

But I have a question about the dependency changes, I noticed nmap is now a hard runtime dependency, is this correct?

If so, what is nmap actually being used for/with?   (sorry if I couldn't locate where/why it was added).  Thanks

Edit: Nevermind, I see it was changed here [b7ef45a16d4cc890dedb5e71aa690072da96ac65](https://github.com/asbru-cm/asbru-cm/commit/f975c51b40f55139f3ea4db5448ed4f7eba2c42c)

I guess I am still wondering why nmap is a hard runtime dependency, I haven't been packaging ASBRU-CM with nmap as a dependency at all, and no users have complained.

**Comment by gfrenoy** [comment]
`ncat` is used to support proxy with user/password.  And it is part of the nmap project, indeed.  We are testing if ncat is installed before using and displaying an error message if it's not the case so I guess we can make it optional...

Has anybody another comment or suggestion about this ?

**Comment by SwampRabbit** [comment]
@gfrenoy understood, thank you for the response.  I saw mention of ncat for proxy support, and see that ncat was replaced with nmap.

In Debian nmap and ncat are two separate packages under the nmap "source package".
[Source Package: nmap](https://packages.debian.org/source/bullseye/nmap)

Installing the nmap package itself does not pull in ncat as it is only a "suggest" of nmap package.  nmap is not a dependency of ncat.  So I think for at least Debian based distros, the old dependency of ncat is correct.

**Comment by gfrenoy** [comment]
Thanks for your clarification !  I'll revert back to ncat for 6.3.1.

**Comment by gfrenoy** [comment]
See #782, we have a regression for systems based on Ubuntu 19.10 (and earlier) as Linux Mint Tessa.

If there way to select `nmap` if `ncat` is not available ?

**Comment by gfrenoy** [comment]
@SwampRabbit I put `ncat | nmap` in the Debian control file, let me know if this should not make sense.

**Comment by SwampRabbit** [comment]
@gfrenoy apologies on not catching the update until now, but yes that should be fine actually.  Distro package maintainers can always change it if they need to.  ;)
