### ISSUE TITLE
--config-dir="/home/user/some dir" fails due space in version 6.3 (not in v6.2)

### ISSUE THREAD

**Issue by dennisTGC** [asbru-cm/asbru-cm#777]
I have configured Asbru with --config-dir="/home/user/some dir/asbru/sync" in version 6.3, but this gives me an error while connecting to a terminal:
```
sh: 0: Can't open /home/user/some
```

I don't have this problem with version 6.2.2-1 or if i use a dir without spaces (like `--config-dir="/home/user/asbru/sync"`).

I didn't do much other research, but let me know if I need to test stuff or give more information. I'm on Ubuntu 20.04.2 with KDE on a Dell Precision T3420.

**Comment by gfrenoy** [comment]
Thanks for your feedback !

The temporary file created when starting a connection (introduced in 6.3.0) was indeed not properly managing space in the configuration directory.  This will be fixed in the next commit and published in 6.3.1.

**Comment by dennisTGC** [comment]
thank you for all the great work!

**Comment by gfrenoy** [comment]
Glad it can help :)  This fix can be tested in our loki or snapshots release and will be packaged in 6.3.1 soon.  Feel free to reopen if required.

**Comment by dennisTGC** [comment]
Ok, I tested with the Loki branch (i was on the stable branch to test for this issue) and it installed:   
`asbru-cm/focal,focal,now 6.4.0~1613681731-1`

And with that version I don't have the issue anymore, as far as I'm concerned it's been fixed and you can close the issue. thank you for the swift response!
