### ISSUE TITLE
Copy in the terminal do not work

### ISSUE THREAD

**Issue by rsantellan** [asbru-cm/asbru-cm#779]
**Describe the bug**
When trying to copy text on the terminal it send CTRL + C instead of CTRL + SHIFT + C

**To Reproduce**
1. Login to any session
2. Do ls /
3. Try to copy any of the output.

**Expected behavior**
Work as any linux terminal.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Ásbrú Version 6.3.0
 
**Additional context**
Had to revert to 6.2.2 that is working without a problem.

**Comment by gfrenoy** [comment]
As of 6.3 you can customize your own shortcut keys.  The default shortcut to copy selection to clipboard is `Ctrl+Insert` but feel free to change it to your most convenient choice:

![image](https://user-images.githubusercontent.com/981546/108270874-4f8f4f80-7170-11eb-9bf6-9de064322d09.png)

**Comment by rsantellan** [comment]
Hi @gfrenoy I switch to Linux Mint 20 and all work as intended, but on my old machine I couldn't copy and paste using the default. I didn't touch the keybindings. Perhaps on the upgrade I miss configure something. I will close it because I can't reproduce it anymore. Regards.

**Comment by rsantellan** [comment]
Today I updated to latest version and I can't change copy the keybinding of copy to ctrl + shift + C

![image](https://user-images.githubusercontent.com/1820598/109399699-25cde980-7923-11eb-9cae-239c6d9c4ea9.png)

It only puts ctrl + C, how can I change this ? Regards

**Comment by gfrenoy** [comment]
Dislplay is indeed a bit confusing.

But `Ctrl + Capital C` is equivalent to `Ctrl + Shift + c` so it works as expected...

**Comment by rsantellan** [comment]
Hi @gfrenoy the Shift is not registered when I press it, I try left and right one. Is there a file where I can change this config ?

**Comment by gfrenoy** [comment]
It *is* registered...

Try `Ctrl+k` then `Ctrl+Shift+k` ; you will see that it is shown as `Ctrk+k` and `Ctrl+K`.

In other words : `c` is different from `C`.

**Comment by rsantellan** [comment]
Ohhh is soo confusing! Why the close all tabs is CtrlShift + F4 ?
After setting it again is working.
Regards

**Comment by gfrenoy** [comment]
Yes, it's confusing  :confused: ... I agree.

Will try to display this better in the next version, stay tuned.

**Comment by gfrenoy** [comment]
See #787, it should now be better and less confusing in our latest loki release ; see the defaults:

![image](https://user-images.githubusercontent.com/981546/109567838-4e521100-7ae6-11eb-9e7b-0f331161a894.png)

**Comment by rsantellan** [comment]
@gfrenoy now is more readable!!
