### ISSUE TITLE
Crash (Delete connection)

### ISSUE THREAD

**Issue by Antoineb2s** [asbru-cm/asbru-cm#78]
Hi,

When you want to remove a connection on left panel (last git version ) asbru crashes with : 
`[1]    1516 segmentation fault (core dumped)  asbru-cm`

**Comment by gfrenoy** [comment]
Confirmed!  It looks like it crashes when it's trying to save the configuration.

**Comment by GreenItSolutions** [comment]
Hi,
Same error when cutting a connection for pasting in another folder.

**Comment by GreenItSolutions** [comment]
I will verify asap

**Comment by gfrenoy** [comment]
I'm using this fix for a while now and did not notice any side effect.  Let's consider it closed.
