### ISSUE TITLE
Connections using keePass no longer work

### ISSUE THREAD

**Issue by dmorrison-bw** [asbru-cm/asbru-cm#780]
**Describe the bug**
After upgrading to v6.3.0 connections that previously integrated with KeePass no longer work. When opening one of those connections, I get the following error:

`CONNECTING WITH ATL - Network - ROUTER-01B (Wed Feb 17 10:39:58 2021)

GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.
Died at /opt/asbru/lib/asbru_conn line 213.

DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Wed Feb 17 10:39:58 2021)
`
When editing the connection, the KeePass option is no longer there

**To Reproduce**
1. Open Asbru v6.3.0
2. Double Click on Connection that used KeePass
3. See error

**Expected behavior**
Connection opens and is usable

**Screenshots**
![image](https://user-images.githubusercontent.com/42274062/108228827-386b4600-710d-11eb-95b9-3b764fc90ec9.png)

**Environment (please complete the following information):**
 - OS: 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Ásbrú Version 6.3.0

**Additional context**

**Comment by gfrenoy** [comment]
> Died at /opt/asbru/lib/asbru_conn line 213.

Retrieving the username is failing but I don't see any obvious reason :-/  Would you mind trying to recreate a new connection to see if this happens the same way ?

> When editing the connection, the KeePass option is no longer there

Yes, the button has been move at the top of screen since you can even replace the host with what is set in KeePass.

![image](https://user-images.githubusercontent.com/981546/108271327-ec51ed00-7170-11eb-91bc-d59609bf50c7.png)

**Comment by gfrenoy** [comment]
Could it be that your entry changed in your KeePass file ?  See #770.

**Comment by dmorrison-bw** [comment]
Nothing in my KeePass file has changed, and when I revert back to 6.2.2 I no longer have the issue, and everything works again as expected.

On 6.3, when I attempt to use create a new connection, using KeePass, when I search for my database it does not exist.

![image](https://user-images.githubusercontent.com/42274062/108274042-6159fe00-7142-11eb-938c-3733ca9bb0e6.png)

In preferences, my KeePass settings don't appear to have changed:

![image](https://user-images.githubusercontent.com/42274062/108274158-80f12680-7142-11eb-9466-08ee170051a8.png)

**Comment by gfrenoy** [comment]
Sorry, I don't see any obvious reason for this issue.  Let's try to troubleshoot this further to understand the root reason.

1)
Would you mind creating a new configuration file:

```
asbru-cm --config-dir=/tmp/asbru-test
```

And see if you can reproduce the same issue from a "blank" configuration ?

2)
Do you see any particular error message when running the KeePass CLI, eg:

```
keepassxc-cli show /path/to/idm.kdbx idm
```

**Comment by dmorrison-bw** [comment]
With a blank configuration file, I am unable to reproduce this issue, it
works as expected. The hostname was auto-populated with "<url|/idm>" and I
had to change that to an IP address to be the same as my regular config
file, not sure if anything changed on that front.

The keepass cli seems to be working fine:

~:>keepassxc-cli show idm.kdbx idm
Insert password to unlock idm.kdbx:
Title: idm
UserName: ABC
Password: XYZ
URL:
Notes:



[image: BandwidthGreen.png]



David Morrison  •  IP Network Engineer

900 Main Campus Drive, Suite 100, Raleigh, NC 27606



o: 919-238-1429  •  m: 919-342-8133

e: dmorrison@bandwidth.com

**Comment by gfrenoy** [comment]
> I had to change that to an IP address to be the same as my regular config file, not sure if anything changed on that front.

Yes, see #639

> The keepass cli seems to be working fine:

Indeed.

I'm out of ideas for the moment, would you mind [sending](https://cloud.frenoy.net/index.php/s/q6Dnzj3sJTXcPzW) an anonymized version of your configuration file so I can give it a try here ?  See "Export Config..." in Preferences ?

**Comment by luiggi-ff** [comment]
Hi, having the same issue here.  I use keepass only to store user and password, host is hardcoded in the connection configuration (we authenticate against active directory so user/pass is the same for al servers).

**Comment by gfrenoy** [comment]
Thanks for your feedback @luiggi-ff.

Can you somehow reproduce the issue in a configuration / KeePass file that you can share ?   I tried on my side but it's just working fine for me so I need more information...

What if you create a new configuration:

```
asbru-cm --config-dir=/tmp/asbru-test
```

And a dummy KeePass file...?

Do you see the same problem ?

Thanks.

**Comment by luiggi-ff** [comment]
Hi, I was not able to reproduce the issue using a new asbru configuration. Seems like exporting connections from my regular asbru instance and then importing them in a new asbru instance solves the issue, even using the same keepass file.
