### ISSUE TITLE
Install problem on linuxmint Tessa

### ISSUE THREAD

**Issue by hvtien** [asbru-cm/asbru-cm#782]
**Describe the bug**
asbru-cm : Depends: ncat but it is not installable

**To Reproduce**
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
Output:
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=linuxmint  version=19.1  codename=tessa  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

sudo apt-get install asbru-cm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 asbru-cm : Depends: ncat but it is not installable
E: Unable to correct problems, you have held broken packages.

ncat does exist on machine

which ncat
Output:
/usr/bin/ncat

**Expected behavior**

How can I found the problem to install the new version ?

**Screenshots**

**Environment (please complete the following information):**
distro=linuxmint  version=19.1  codename=tessa  arch=x86_64
 Actual asbru-cm version: 6.3.0

Thank you

**Comment by gfrenoy** [comment]
Ah, now I understand better why we put `nmap` as a dependency instead of `ncat` (see #776) !  `ncat` package only exists as of Ubuntu 20.04 (and Linux Mint 20).

If you are in a hurry, you should force installation, despite the missing dependency, then install `nmap` manually.

And I'll try to see if and how we can have different dependencies according to the target OS.

**Comment by hvtien** [comment]
Thank you for prompt reply
I checked on my machine to install nmap manually, but it was installed
correctly

sudo apt install nmap
Output:
Reading package lists... Done
Building dependency tree
Reading state information... Done
nmap is already the newest version (7.60-1ubuntu5).

which nmap
/usr/lib/nmap

Cheers,
Tien

**Comment by gfrenoy** [comment]
Yes so you should force the installation.  See [here](https://askubuntu.com/questions/74523/how-can-i-install-a-package-without-installing-some-dependencies).  Disclaimer: this is NOT recommended !!  Only do this if you understand what you are doing...

Otherwise, please wait for the next release ; we'll sort that out :-p

**Comment by hvtien** [comment]
Do you mean that I can force the installation of asbru-cm with the option
no-install-recommends?

sudo apt install asbru-cm —no-install-recommends

Cheers,

Tien

**Comment by gfrenoy** [comment]
The last commits should have fixed the issue.

You can give it a try on our snapshot or loki builds (see our [manual](https://docs.asbru-cm.net/General/Installation/) for details) and it will be included in our next 6.3.2 release that will be published soon.

**Comment by hvtien** [comment]
Thank you very much
