### ISSUE TITLE
Problem with show/hide connection list

### ISSUE THREAD

**Issue by pandiloko** [asbru-cm/asbru-cm#786]
Focus doesn't change to the connection list when favorites is active. I can't change the keybinding to old-skool alt-c

**To Reproduce**
1. Click on Favorites tab
2. from the terminal use the keybinding to show/hide connection list
3. terminal doesn't have focus anymore
4. you can't navigate through the list of favorite connections

1. Go to keybindings in settings
2. click on Main Window show/hide connection list 
3. try to assign it to alt-c
4. alt will activate the dialog shortcut and c will select "close without saving"

**Expected behavior**
I guess the focus is sent to the connection list, which is not the same as favorites. But since favorites is active I think it should get the focus instead. 

In the keybinding settings disable the alt shortcuts.

**Environment (please complete the following information):**
 - OS: KDE Neon (Ubuntu 20.04)
 - Ásbrú Version 6.3.2

Otherwise I greatly appreciate this new feature. Thanks for this project!!

**Comment by gfrenoy** [comment]
Good point !  Thanks for your feedback.

The last commit should have fixed this.  You'll be able to test this in 30 min on our loki release (see https://docs.asbru-cm.net/General/Installation/).

Will you let us know if it works for you ?

**Comment by pandiloko** [comment]
Sorry I'm afraid the two problems are still there. I hope I changed my apt config correctly. I updated and now the version is 6.4.0. 

I'm not sure if I explained myself well enough. If I use the keybinding to show Connection Tree, the Connection Tree gets indeed the focus and I can even move around with the arrows and open a new connection with "return". BUT if Favorites is active I can move around Connection Tree in the background but what I see is the Favorites List. In other words: how can I give the focus to the Favorites list?

In addition to that. The old keybinding to show the connection Tree was "alt-c". I wanted to change from "alt-n" back to "alt-c" now it is not possible because alt-c triggers the "Close without saving" dialog option. 

Thanks for the quick response even on weekend!

**Comment by gfrenoy** [comment]
Ah yes, I did not read your initial description correctly !  Thanks for the additional explanations :)

I made some more commits on our loki branch ; they should now hopefully fix the correct issues !

The new version should be ready in about 30 minutes.  Let me know if it now works better for you.

And thanks for your great feedback.

**Comment by pandiloko** [comment]
Sorry, the last version came in only today or perhaps the problem was still there in the last one. I have the loki version enabled in the repos but the version info just says 6.4.0 so I don't know exactly what version I was running. Anyway today I updated and both issues are now fixed. Thank you!!
