### ISSUE TITLE
Field ssh Authentication dont save username, when used Manual checkbox

### ISSUE THREAD

**Issue by Prototype-X** [asbru-cm/asbru-cm#788]
**Describe the bug**
Field ssh Authentication dont save username, when used Manual checkbox

**To Reproduce**
1. Go to Edit Connection -> Method: SSH
2. Check User/Password -> input User
3. Check Manual
4. Save and Close 
5. Field User - clear
6. ssh use default username

**Expected behavior**
1. Go to Edit Connection -> Method: SSH
2. Check User/Password -> input User
3. Check Manual
4. Save and Close 
5. Field User - not clear
6. ssh use username in field User

**Screenshots**
Not work Asbru ver. v6.3.1-2
![image](https://user-images.githubusercontent.com/12714643/109414252-0b4b4d00-79c3-11eb-896f-d7c35b59300a.png)
worked on previous versions
![image](https://user-images.githubusercontent.com/12714643/109414549-7a757100-79c4-11eb-907e-a59ca677f44c.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Ásbrú Version 6.3.2

**Comment by gfrenoy** [comment]
Mmm, this has be changed on purpose, see [here](https://github.com/asbru-cm/asbru-cm/commit/3fb5b0af569a18f1ca7a4418dd0235544f21316d#diff-6a6bfcee6278a0e1089034a1eded0786c193e0ee53af0db815ff2d2416ae2d36) and #694.

To get it correctly, why the user/password would not work in your case ?

**Comment by Prototype-X** [comment]
> Mmm, this has be changed on purpose, see [here](https://github.com/asbru-cm/asbru-cm/commit/3fb5b0af569a18f1ca7a4418dd0235544f21316d#diff-6a6bfcee6278a0e1089034a1eded0786c193e0ee53af0db815ff2d2416ae2d36) and #694.
> 
> To get it correctly, why the user/password would not work in your case ?

I am confused by the password prompt popup. 
It is more convenient to enter the password directly into the terminal. 
This has worked before.

**Comment by gfrenoy** [comment]
Mmmm.  I see.

Maybe the popup should be only displayed if `<<ASK_PASS>>` is explicitly set but, if password is left empty, we should just display the standard password prompt ?

Would that be an option ?

**Comment by gfrenoy** [comment]
> if password is left empty, we should just display the standard password prompt ?

Too tricky... I changed my mind.

In the last commit, I tried to re-arrange the dialog, see:
![image](https://user-images.githubusercontent.com/981546/109566693-835d6400-7ae4-11eb-9fe8-5d8f4f885bc1.png)

Now the user name can be used for both user/pass and manual modes.  And as a consequence, user name is not "forgetten" when you save the settings.

Will you give it a try and let me know what you think about this ?

**Comment by Prototype-X** [comment]
> > if password is left empty, we should just display the standard password prompt ?
> 
> Too tricky... I changed my mind.
> 
> In the last commit, I tried to re-arrange the dialog, see:
> ![image](https://user-images.githubusercontent.com/981546/109566693-835d6400-7ae4-11eb-9fe8-5d8f4f885bc1.png)
> 
> Now the user name can be used for both user/pass and manual modes. And as a consequence, user name is not "forgetten" when you save the settings.
> 
> Will you give it a try and let me know what you think about this ?

Perfect solution, if popup not showed and password input in terminal.

**Comment by gfrenoy** [comment]
> if popup not showed and password input in terminal

Yes, that is working for me.  You can give it a try on the loki release...

**Comment by Prototype-X** [comment]
Tested on the loki release, it works. Many thanks :)
