### ISSUE TITLE
Support for Pop!_OS 20.04

### ISSUE THREAD

**Issue by shai50** [asbru-cm/asbru-cm#789]
Hi i'm trying to install it on my popos 20.04 laptop,
i have followed the instructions 

$ curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=pop  version=20.04  codename=focal  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

$ sudo apt-get install asbru-cm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package asbru-cm

as shown, the curl step returns no errors, but the apt finds no package name asbru-cm...

i have also added multiverse repo with no errors...

**Comment by gfrenoy** [comment]
Thanks for your feedback.

We did not build our package for Pop OS yet, I just added it to the [snapshot release](https://docs.asbru-cm.net/General/Installation/), you'll be able to give it a try in about 30 minutes:

```
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/snapshots/cfg/setup/bash.deb.sh' | sudo -E bash
```

Alternatively, you need to force the use of the Ubuntu repository:

```
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E distro=ubuntu bash
```

**Comment by shai50** [comment]
That worked great! thanks
