### ISSUE TITLE
'Start a shell upon startup' does not start a shell on startup

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#79]
When I go to 'Settings' --> 'Local Shell Options' and check 'Start a shelll upon startup' and restart asbru-cm, it doesn't automatically start a local shell on startup as I would have expected.

**Comment by gfrenoy** [comment]
Confirmed.  As far as I can see in the code, this option has been foreseen but has not been used anywhere in the code !

If one wants to give it a try, look for ```autostart shell upon PAC start``` in the code.

**Comment by gfrenoy** [comment]
Actually the option was foreseen but the name of the option was wrong !  I just fixed it now so it will be available in the snapshot soon and into the next release.
