### ISSUE TITLE
Power Cluster Controller (PCC) can't close multiple exploded tabs

### ISSUE THREAD

**Issue by xattack** [asbru-cm/asbru-cm#791]
**Describe the bug**

Power Cluster Controller (PCC) can't close multiple exploded tabs

**To Reproduce**
1. Open as many servers as you want of a list of registered servers
2. Use PCC to explode them 
3. Click on the close all button and select OK 
4. Nothing happens

**Expected behavior**
Being able to close all the terminals that you already open

**Screenshots**
![Screenshot from 2021-03-03 16-03-05](https://user-images.githubusercontent.com/8902460/109997997-6b4d3680-7cd6-11eb-8a58-f36876e0aeb0.png)

**Environment (please complete the following information):**
 - OS: Linux Mint 19.3 Tricia
 - Ásbrú Version 6.3.2 

From cli opened asbru-cm and get this 
![Screenshot from 2021-03-04 10-48-20](https://user-images.githubusercontent.com/8902460/109998947-5cb34f00-7cd7-11eb-802c-7b720b21a3fb.png)

hope it helps

**Comment by gfrenoy** [comment]
Thanks a lot for the detailed feedback.  The last fix should fix this issue.  You will be able to test it in about 30 minutes in our snapshot release.  Let us know if it works for you.

**Comment by xattack** [comment]
Thank you very much , the reported issue its resolved ! 

cheers !!
