### ISSUE TITLE
No menu on right click in terminal

### ISSUE THREAD

**Issue by PiotruAK** [asbru-cm/asbru-cm#793]
Describe the bug
The right click menu for the terminal will not open when a remote command is defined

To Reproduce

Add a remote command to either global or to a specific connection
Start the connection to a remote computer or start a local shell
Attempt to right click inside the terminal on a remote or local shell
Expected behavior
The menu should show up.

This description is not mine, but i made something similar and i lost right menu, but only in terminal on open connection. Right menu on tree is avalible.
Additional i remove all configuration files in path: /home/mint/.config/asbru
After running again Asbru i create new conection and i have right menu again.
After restoring my previous configuration again i lost menu.
I think so problem is in my config files... 
I dont want build a new tree of connections, because this problem can back again. Best solution is solve problem.

Environment (please complete the following information):
Linux Mint 20.1
asbru-cm 6.3.2

**Comment by gfrenoy** [comment]
Thanks for your feedback but I'm unable to reproduce that issue.

Do you know which command is causing that behaviour ?

Or can you [drop me](https://cloud.frenoy.net/index.php/s/z2GB5TpoBgqo5YL) an anonymised version (see `Preferences` > `Export Config...`) of your configuration file so that I can try to reproduce it ?

**Comment by PiotruAK** [comment]
Hello, 
Sorry for late answer, but through this time i was far from this computer.
I was put to you my export file - called: asbru_export.yml

If you still will have a problem with reproduce this problem i can put you whole Asbru files from path: /home/mint/.config/asbru
With this files i'm sure so you will can reproduce this problem.

Thanks a lot, and i'm hope so you will can find solution.
