### ISSUE TITLE
Error when using an entry of a KeePass database with a pipe ("|") on title

### ISSUE THREAD

**Issue by mrplow-github** [asbru-cm/asbru-cm#794]
**Describe the bug**
I use Ásbrú connected with a KeePass database. In KeePass, I often use the pipe character as a separator on the title of many entries and found an error when Ásbrú tries to use them. I'm able to create the new entry, but when I want to establish a connection I get an "Died at /opt/asbru/lib/asbru_conn line 213." error.

**To Reproduce**
1. Add a new connection
2. Click the KeePass button
3. Select the entry with a pipe in the title
4. Save the new connection
5. Start the new connection

**Expected behavior**
A new connection should be established, but it fails with the error message already written.

**Screenshots**
I don't think it is needed.

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 10.8 "buster"
 - Ásbrú v6.3.2

**Additional context**
Nothing else.

**Comment by gfrenoy** [comment]
Thanks for the great feedback and issue description.

The last commit should fix the issue.  You will be able to test this in our "snapshot" build in about 30 minutes.  If OK it will be released in our next version (likely 6.3.3).

Let us know if works for you.

**Comment by mrplow-github** [comment]
Great! Thank you very much!
It's working as expected now.
