### ISSUE TITLE
SSH Manual Authentication option assumes local user for username

### ISSUE THREAD

**Issue by daxm** [asbru-cm/asbru-cm#797]
**Describe the bug**
Selecting MANUAL for SSH Authentication doesn't allow me to set the username during connection establishment.

**To Reproduce**
1.  Create SSH connection and set Authentication to "Manual".
2.  Attempt to connect.  When prompted to authenticate the username is already set to local host's user.

**Expected behavior**
I should be able to type in the remote username during authentication.

**Screenshots**
```
CONNECTING WITH 9348-39 - Console (Thu Mar 11 10:42:34 2021)

GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: setenv()/putenv() are not thread-safe and should not be used after threads are created at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
GLib-LOG **: unsetenv() is not thread-safe and should not be used after threads are created at /usr/share/perl5/Gtk3.pm line 555.
[asbru_conn(39523)][9348-39][9348-39 - Console]: !!_PAC_AUTH_[asbru_PID{38141}_n7]!!
[asbru_conn(39523)][9348-39][9348-39 - Console]: GET_TITLE:
[asbru_conn(39523)][9348-39][9348-39 - Console]: SPAWNING:ssh -p 22 -o "PreferredAuthentications=password,keyboard-interactive" -x 10.0.4.4
[asbru_conn(39523)][9348-39][9348-39 - Console]: SPAWNED:'ssh -p 22 -o "PreferredAuthentications=password,keyboard-interactive" -x 10.0.4.4' (PID:39523)
[asbru_conn(39523)][9348-39][9348-39 - Console]: CONNECTING:Manual authentication requested
[asbru_conn(39523)][9348-39][9348-39 - Console]: TITLE:9348-39 - Console
[asbru_conn(39523)][9348-39][9348-39 - Console]: CONNECTED
daxm@10.0.4.4's password: 
```
I don't want 'daxm' as the username.  I want the ability to type in a username (or have that set in the settings for this connection).

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Ásbrú Version v6.3.2

**Additional context**
None

**Comment by xattack** [comment]
Try this [https://github.com/asbru-cm/asbru-cm/issues/127](url)

**Comment by daxm** [comment]
> Try this [https://github.com/asbru-cm/asbru-cm/issues/127](url)

That would probably work but it doesn't address the issue with the Manual feature.

**Comment by gfrenoy** [comment]
Please check #788.
