### ISSUE TITLE
KeepassXC password exposed on asbru-cm local shell terminal

### ISSUE THREAD

**Issue by xattack** [asbru-cm/asbru-cm#801]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]th

   I was playing with Asbru-cm local terminal reviewing some stuff, and tried  env  command... 
  To my surprise i could see in plain text a local variable named  KPXC_MP = KeepassXC password 

    It was , something i didn't expect to found in clear, plain text. I know its not the best practice to use 
the password in that way, also understand that if any attacker want to retrieve it, first has to gain access 
where ever asbru-cm is installed, and so on ... not so easy by the way. 

    **Describe the solution you'd like**

    Could be , trying a more secure way to manage Keepass password from asbru-cm ? 

**Describe alternatives you've considered**
      

Honestly i cannot offer an alternative to do this ...may be private / public keys ?
![asbru-cm-surprise](https://user-images.githubusercontent.com/8902460/112761235-a1b96100-8fb7-11eb-9b65-be61d7f1ee9b.png)

**Additional context**

**Comment by gfrenoy** [comment]
Indeed, not very nice :(

An environment variable is used to exchange the information between the main process and the subprocesses that are started when a new connection is started.

The very least that we can do is, once started, to delete it in the subprocess.

I'll have a look.

**Comment by gfrenoy** [comment]
Made a change in both snapshot and loki branches.  Will you give it a try ?

**Comment by xattack** [comment]
Thank you very much @gfrenoy  

   I can confirm that in the snapshots branch ,  the environmental variable no longer can be found exposed 

     
![Screenshot from 2021-04-06 10-37-12](https://user-images.githubusercontent.com/8902460/113738404-7b38ab80-96c4-11eb-9f36-5b52d05b40a9.png)

**Comment by gfrenoy** [comment]
Good :)  That's indeed better !

But I do suspect that the environment variable on the main process can still be accessed by other means ; let's leave that issue open ... There must be a better way to "remember" the password and share it to the subprocesses.

If anyone has an idea, I'd be happy to give it a try.

**Comment by popxunga** [comment]
Hi @gfrenoy ...
Maybe [this](https://metacpan.org/pod/Passwd::Keyring::Auto) helps ... 
Regards !
