### ISSUE TITLE
Each connection prompts for a push and how to get rid of them

### ISSUE THREAD

**Issue by imkos** [asbru-cm/asbru-cm#806]
The operating system :  manjaro kde 21.

CONNECTING WITH node1 - test (Thu Apr 22 11:12:09 2021)

(asbru_conn:5214): Gtk-WARNING **: 11:12:09.555: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(asbru_conn:5214): Gtk-WARNING **: 11:12:09.555: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(asbru_conn:5214): Gtk-WARNING **: 11:12:09.555: Theme parsing error: gtk.css:70:34: The style property GtkCheckButton:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(asbru_conn:5214): Gtk-WARNING **: 11:12:09.555: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(asbru_conn:5214): Gtk-WARNING **: 11:12:09.555: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(asbru_conn:5214): Gtk-WARNING **: 11:12:09.555: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(asbru_conn:5214): Gtk-WARNING **: 11:12:09.555: Theme parsing error: gtk.css:83:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version

**Comment by imkos** [comment]
The operating system I use is manjaro kde 21.

**Comment by gfrenoy** [comment]
See #727 and #227.

**Comment by imkos** [comment]
![image](https://user-images.githubusercontent.com/17872894/116180106-f7199700-a74a-11eb-8399-c919da43d10a.png)
manjaro kde 21.

**Comment by gfrenoy** [comment]
Ok, so you have to report the issue to the author of the "Breath" theme...
