### ISSUE TITLE
Fedora 34 Support - (PackageCloud)

### ISSUE THREAD

**Issue by pablomenino** [asbru-cm/asbru-cm#807]
any plans on this?

and yes I known, Fedora 34 was release today, but I can't wait. :)

**Comment by KlaasT** [comment]
I can try. Need to check if we can get docker images for building or if we need to make them from scratch.

**Comment by gfrenoy** [comment]
Fyi, Ásbrú package for Fedora 34 is now available in our "snapshot" release.

Testers are welcome :)

(instructions to use the "snapshot" release can be found [here](https://docs.asbru-cm.net/General/Installation/))
