### ISSUE TITLE
ZMODEM protocol support!

### ISSUE THREAD

**Issue by imkos** [asbru-cm/asbru-cm#808]
Zmodem uses 2 commands to transfer data (additional installation is required on the server)
sz: send the selected file to the local machine
rz: Run this command will pop up a file selection window, select the file from the local and upload it to the server (receive)

```
yum install lrzsz
```

```
apt install lrzsz
```

rz/sz is used for the file transfer between Linux and Win, so if there is a similar tool which can transfer the files between Linux, including "Local Linux" and “remote Linux"(While may be several levels of login) directly , which can be great time saving and free of several times of scp .

**Comment by gfrenoy** [comment]
Can you check #88 ; with a generic command, I think you can achieve what you're looking for.
