### ISSUE TITLE
Typing ~. closes any SSH session

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#809]
**Describe the bug**
If I type **~.** in any SSH session, the session is immediately closed.

**To Reproduce**
1. Establish SSH session:
2. Type **~.**
3. Session is closed.

**Expected behavior**
Session shouldn't close.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: EL8
 - Latest Ásbrú loki

**Additional context**
n/a

**Comment by kjuanman** [comment]
Its a feature of openssh.
~ is the default escape character and . the command to disconnect the session.
You can disable escape character with:
Edit Connection -> SSH Connection -> Advanced Options -> Add -> Option: EscapeChar -> Value: none

More info: https://linux.die.net/man/1/ssh
