### ISSUE TITLE
[rdesktop] Exhance parameters for rdesktop (or any other client)

### ISSUE THREAD

**Issue by marcinbojko** [asbru-cm/asbru-cm#81]
Hi.
I'd like to propose a new setting for rdesktop connections.
We can influence a few parameters, bu still, there is a lots of them we could use. Of course, we can create an alias, but this solution is not so convienient as it should be.
So, what about creating extra (empty) parameters for passing them to rdesktop in **raw form?**
Let's say we'd like to pass extra 'x' parameter to set proper "rdp experience'. Allowing us to pass it as:
`-x l`
or 
`-x [hexcode]`
would be kind of solution for evergrowing list of parameters for any client.

**Comment by gfrenoy** [comment]
Looks indeed a very good idea :)

If one wants to give it a try, check file https://github.com/asbru-cm/asbru-cm/blob/master/lib/method/PACMethod_rdesktop.pm, at line [248](https://github.com/asbru-cm/asbru-cm/blob/master/lib/method/PACMethod_rdesktop.pm#L248), this is the function that builds the GUI (as the function name suggests ;p).

**Comment by figue** [comment]
Just saw this... I've just implemented for freerdp in my own branch 

Duplicate #158

**Comment by gfrenoy** [comment]
Fixed by #163
