### ISSUE TITLE
manual username cleared on save

### ISSUE THREAD

**Issue by dpcinc** [asbru-cm/asbru-cm#810]
With 6.3.2, when adding a new connection, if you add a username to the manual login details, and change the mode to 'manual' , asbru no longers saves the username you want to login with. 

**To Reproduce**
add a new connection
update username in user / password area
change method to manual
save and close
open connection, it will now try to use your default user

**Expected behavior**
Save the username under user / password and attempt to use it to login 

**Environment (please complete the following information):**
mint 20
re.

**Comment by Noles** [comment]
Seems to be related to #788

**Comment by dpcinc** [comment]
yes duplicate for sure
