### ISSUE TITLE
Appimage - uuid.c: loadable library and perl binaries are mismatched

### ISSUE THREAD

**Issue by onelittlehope** [asbru-cm/asbru-cm#811]
**Describe the bug**
Cannot execute the appimage for Asbru release 6.3.2.

**To Reproduce**
1. Download https://github.com/asbru-cm/asbru-cm/releases/download/6.3.2/asbru-cm-6.3.2-1-x86_64.AppImage
2. chmod u+x ./asbru-cm-6.3.2-1-x86_64.AppImage
3. ./asbru-cm-6.3.2-1-x86_64.AppImage

```
~/Downloads> ./asbru-cm-6.3.2-1-x86_64.AppImage 
uuid.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xed00080)
```

**Expected behavior**
Expected Asbru to execute correctly.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Ásbrú Version: 6.3.2

**Additional context**

**Comment by barkely128** [comment]
Archlinux here:

$ ./asbru-cm-6.3.2-1-x86_64.AppImage 
uuid.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xeb00080)

**Comment by Sect-31** [comment]
Would it make you "more comfortable" with this matter to find the root case if you knew it's happening on Kubuntu 20.10 as well ?
Hmm ? Or do you just Not care to be made... Uncomfortable ?

**Comment by barkely128** [comment]
He's not experienced with AppImage enough to find the cause without wasting lots of time. That's what he meant. Still fixing it would end the dependency hell. Anyone who's capable and has some free time is welcome to help.

**Comment by Fabick75** [comment]
Hello,
same here, on Slackware Current 64bit and latest AppImage package :
~> ./asbru-cm-6.3.2-2-x86_64.AppImage
uuid.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xeb00080)

This mean that the problem was never resolved nor investigated ?
