### ISSUE TITLE
Create builds for Debian Bullseye

### ISSUE THREAD

**Issue by bmunger** [asbru-cm/asbru-cm#812]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Create a release build on Packagecloud for Debian Bullseye

**Describe alternatives you've considered**
Appimage will work for now.

**Additional context**
Debian Bullseye is currently still in testing but will release as stable soon.  A package available for installation before release to stable would be preferable.

**Comment by gfrenoy** [comment]
Fyi, Ásbrú package for Debian Bullseye is available since a couple of weeks in our "snapshot" release.

Testers are welcome :)

**Comment by bmunger** [comment]
I can definitely test this for you!  However, I can't find the release.  I see the commit that added the build target in .travis.yml and the option to build on packagecloud, but I can't find the release.  Could you please let me know where it's built?  Thanks.

**Comment by gfrenoy** [comment]
The build is not yet available in the official (master) releases.

You need to setup the "snapshot" repository to have access to the latest builds, see instructions here:
  https://docs.asbru-cm.net/General/Installation/

(disclaimer: those builds might not be as stable as the official releases, of course).

**Comment by bmunger** [comment]
Thanks!  I was able to install and use it without any problems so far.  I will report if I find anything but so far it works perfectly.

**Comment by Joelp** [comment]
There is still no Debian 11 package in `release` repo

**Comment by NRGLine4Sec** [comment]
I need it too.

**Comment by ber-red** [comment]
I would be very pleased too, to see asbru-cm bulleye package in `release` repo

**Comment by KlaasT** [comment]
Hopefully we can get this done soon. In the meantime you should be able to find a package in the snapshot repository.
