### ISSUE TITLE
Can't install on Ubuntu 21 Hirsute

### ISSUE THREAD

**Issue by Aerya** [asbru-cm/asbru-cm#813]
Hello,

**Describe the bug**
I can't install on Ubuntu 21.x Hirsute

**To Reproduce**
I tried:
 - Install instruction as per https://www.asbru-cm.net/
 - Install instruction as per https://github.com/asbru-cm/asbru-cm/wiki
 - The .appimage (nothing launches)

**Screenshots**
```
aerya@aerya:~$ sudo apt install asbru-cm.
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
E: Impossible de trouver le paquet asbru-cm.
E: Impossible de trouver de paquet correspondant à l'expression rationnelle « asbru-cm. »
```
```
aerya@aerya:~/Téléchargements/asbru-cm$ ./asbru-cm 
INFO: Ásbrú Connection Manager 6.3.3 (asbru-cm) started with PID 87981
INFO: Language detected : fr_FR.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : xfce
INFO: Config directory is '/home/aerya/.config/asbru'
WARN: No configuration file found in '/home/aerya/.config/asbru', creating a new one...
INFO: Virtual terminal emulator (VTE) version is 0.62
INFO: Theme directory is '/home/aerya/TÃ©lÃ©chargements/asbru-cm/res/themes/default'
<broken file>:1:0Failed to import: Erreur lors de l’ouverture du fichier /home/aerya/TÃ©lÃ©chargements/asbru-cm/res/themes/default/asbru.css : Aucun fichier ou dossier de ce type at /usr/lib/x86_64-linux-gnu/perl5/5.32/Glib/Object/Introspection.pm line 67.
```
The error is [a known one](https://github.com/asbru-cm/asbru-cm/issues/432) but nevermind, asbru-cm don't launch.

**Environment (please complete the following information):**
```
aerya@aerya:~$ uname -a
Linux aerya 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
aerya@aerya:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
```
Fresh install (both VM/VPS)

**Comment by Aerya** [comment]
Forgot to mention I could install for Groovy after modifying the source-list.

**Comment by gfrenoy** [comment]
Took me a while to figure out that the default Travis docker version had a bug that affected Ubuntu hirsute (see [here](https://stackoverflow.com/questions/66319610/gpg-error-in-ubuntu-21-04-after-second-apt-get-update-during-docker-build)).

This is now fixed and Ásbrú package for Hirsute is now available in our "snapshot" release.

Testers are welcome :)
