### ISSUE TITLE
Asbru hang 

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#814]
**Describe the bug**
Asbru hangs if the searched KeepassXC entry has a leading blank in the userid field.

**To Reproduce**
1. Create an entry on KeepassXC with a leading blank in the userid field.
2. Define a new ssh session, press the KeepassXC lookup button to search for the host defined in step 1.
3. Select the KeepassXC entry and Asbru hangs.

**Expected behavior**
The leading blank should be ignored and Asbru should not hang.

**Screenshots**
n/a.

**Environment (please complete the following information):**
 - OS: EL 8.3
 - Loki Ásbrú Version
 - KeepassXC v2.6.4

**Additional context**
n/a.

**Comment by gfrenoy** [comment]
Hello.  I did try but was not able to reproduce this...

The leading space and silently ignored and the connection is working fine.

Do you see any error message on the command line ?

**Comment by popxunga** [comment]
Hello ... 
I'm not able to replicate this anymore, and I don't recall if any message was trow in the terminal ... but I think not.
Thanks ...
