### ISSUE TITLE
Keybinding change not work

### ISSUE THREAD

**Issue by onyn** [asbru-cm/asbru-cm#815]
**Describe the bug**
By default `Ctrl + q` keybind cause asbru exiting which is clashes with XON flow control signal. When I change this keybinding to another combination asbru still catches `Ctrl + q` and handle it as exit action.

**To Reproduce**
1. Change exit keybindng to anything (`Ctrl + Alt + w` for example)
1. Connect to ssh session
2. Press `Ctrl + q`
3. See asbru exit confirmation popup

**Screenshots**
![image](https://user-images.githubusercontent.com/329168/119516855-c6477480-bd7f-11eb-81d3-7348db52f610.png)

**Environment (please complete the following information):**
 - OS: Linux Mint 20.1
 - Ásbrú Version 6.3.2

**Comment by kjuanman** [comment]
Hello

This is because there is another Exit Ásbrú in Window "Terminal". If you have the Terminal attached to Main Window, both "exit ásbrú" Keybinds works.

Regards

**Comment by onyn** [comment]
Thanks

**Comment by QkiZMR** [comment]
This does not work. No matter if a terminal is attached to the main window or a separate window CTRL+Q doesn't work. Should be the option to disable keyboard shortcuts entirely.
