### ISSUE TITLE
Can't close tab after doing split-unsplit

### ISSUE THREAD

**Issue by Random-Chain** [asbru-cm/asbru-cm#817]
**To Reproduce**
1. Open 2 connection tabs
2. Split both tabs
3. Unsplit the tabs
4. Exit connection and try to close the tabs with "x" button
(I have Asbru set not to auto-close tab on SSH exit)

**Expected behavior**
Both tabs should close, but you can only close one. On the other tab the "x" button doesn't do anything.
You can workaround it by detaching the unclosable tab and then closing the window.

**Environment:**
 - OS: Pop!_OS 20.04
 - Ásbrú Version: 6.3.2-1

**Comment by kjuanman** [comment]
I confirm.
"Close all terminals" is another workaround (of course, that close others terminals that you have).

**Comment by gfrenoy** [comment]
Thanks for the great bug report :)

I just pushed a fix... The new build will be available soon in the "snapshop" and "loki" repositories.

Let me know if this works for you.

**Comment by kjuanman** [comment]
> Thanks for the great bug report :)
> 
> I just pushed a fix... The new build will be available soon in the "snapshop" and "loki" repositories.
> 
> Let me know if this works for you.

Works for me!
