### ISSUE TITLE
Ubuntu Budgie wont install asbru

### ISSUE THREAD

**Issue by Skaranorak** [asbru-cm/asbru-cm#818]
I've followed the instructions listed for Ubuntu on the site and the wiki but keep coming to this outcome bellow.

sudo apt install asbru-cm
[sudo] password for enigma: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package asbru-cm

I'm using Ubuntu Budgie as my flavour

**Comment by barkely128** [comment]
I don't think you should be missing this step:

curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash

**Comment by Skaranorak** [comment]
I'm not, I run that successfully but the install command afterwards returns the what I posted in the first message.

**Comment by Skaranorak** [comment]
> I don't think you should be missing this step:
> 
> curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash

**Comment by Skaranorak** [comment]
> I don't think you should be missing this step:
> 
> curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash


I'm not, I run that successfully but the install command afterwards returns the what I posted in the first message.

**Comment by kjuanman** [comment]
What version of Ubuntu Budgie do you have?
You can try:
sudo apt-get update
sudo apt install asbru-cm

**Comment by Skaranorak** [comment]
> What version of Ubuntu Budgie do you have?
> You can try:
> sudo apt-get update
> sudo apt install asbru-cm

I am using Ubuntu 21.04
Gnome  3.38.5

**Comment by kjuanman** [comment]
I confirm. The issue is with 21.04, not budgie related.
I send a Pull Request for add support to ubuntu 21.04 in builds.

Ugly workaround: 
```
sudo sed -i 's/hirsute/focal/g' /etc/apt/sources.list.d/asbru-cm-release.list
sudo apt update
sudo apt install asbru-cm
```

**Comment by Skaranorak** [comment]
> I confirm. The issue is with 21.04, not budgie related.
> I send a Pull Request for add support to ubuntu 21.04 in builds.
> 
> Ugly workaround:
> 
> ```
> sudo sed -i 's/hirsute/focal/g' /etc/apt/sources.list.d/asbru-cm-release.list
> sudo apt update
> sudo apt install asbru-cm
> ```

Sweet that did it alright. thank you !

**Comment by gfrenoy** [comment]
See #813
