### ISSUE TITLE
Cannot install in Ubuntu 18.04

### ISSUE THREAD

**Issue by marcgise** [asbru-cm/asbru-cm#82]
I'm always having an error following the steps for installing the application:
![image](https://user-images.githubusercontent.com/4680243/39675802-ba723836-5160-11e8-911b-01a586b25446.png)

The message says that the package asbru-cm is not available, but another package refers to it. That means that the package is not available, it's obsolete or it's only available through other source.

**Comment by gfrenoy** [comment]
See #66 (there's a workaround there).

**Comment by Prototype-X** [comment]
Edit /etc/apt/sources.list.d/asbru-cm_asbru-cm.list
Change bionic to artful:
`
# cat asbru-cm_asbru-cm.list 
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/asbru-cm/asbru-cm

deb https://packagecloud.io/asbru-cm/asbru-cm/ubuntu/ artful main
deb-src https://packagecloud.io/asbru-cm/asbru-cm/ubuntu/ artful main
`

**Comment by marcgise** [comment]
You saved my life :D This worked like a charm.
