### ISSUE TITLE
Tabs mouse scroll not working after update

### ISSUE THREAD

**Issue by Jungo495** [asbru-cm/asbru-cm#824]
After updating debian 9 -> debian 10, scrolling by open tabs stopped working. Can you please tell me how to fix it?

**To Reproduce**
1. Navigate mouse to opened tabs.
2. Scroll you mouse wheel slowly.
3. Active tab not changing.

**Environment (please complete the following information):**
 - OS: Debian 10.10
 - Ásbrú Version asbru-cm 6.3.2-1 installed via APT

**Comment by gfrenoy** [comment]
Is this the same as #636 ?

**Comment by Jungo495** [comment]
> Is this the same as #636 ?

yes!
