### ISSUE TITLE
Tabs height increased after update.

### ISSUE THREAD

**Issue by Jungo495** [asbru-cm/asbru-cm#825]
In the older version, the height of the tabs was very compact. Perhaps you know how you can reduce this height? I can dig into the code and try to make such a setting if you tell me what to do approximately. I have very little programming experience, but I would like to make the product better. Thanks for developing the product!

OS Debian 10.10 Gnome 3
Asbru asbru-cm 6.3.2-1

![Screenshot from 2021-06-30 18-07-56](https://user-images.githubusercontent.com/19645759/123987081-910df200-d9cf-11eb-9f30-07408da0da48.png)

**Comment by gfrenoy** [comment]
We don't control the height of the tab bar ; this is controlled by the window manager.  Likely the change is caused by a new "GTK theme".  You may want to try one that has a more compact layout...
