### ISSUE TITLE
Can't save Connections on Arch

### ISSUE THREAD

**Issue by MaxiFlaxiBoii** [asbru-cm/asbru-cm#826]
(Sorry if my english is bad)

Hey, i have the Problem, that if i install the Package asbru-cm, i can't save connections. I can click on "Create new Connection" and i also get the window to insert my address, username and password but if i click on "save and close" it does not close the window. However if I close the windows manually i see my connection and i can connect to it. But if i restart my Asbru, the connection is not there anymore.

I also tried to install the Package asbr-cm-git but if i do so, i get the following error: "Could not find all required packages:
        perl-crypt-cbc<3 (Wanted by: asbru-cm-loki-git)"

If i try to install that missing dependency with "sudo pacman -S perl-crypt-cbc" i get the error it still gives me that error.

**Comment by figue** [comment]
Hi, you have to downgrade perl-crypt-cbc to version 2.33-4

I personally use https://aur.archlinux.org/packages/downgrade/ script to downgrade packages.

**Comment by MaxiFlaxiBoii** [comment]
Hi figue,

thank you for your reply.

If i do that i still don't have the Version 2.33. It is still a version 3.x. How do i downgrade to that specific version?

**Comment by figue** [comment]
In my case, downgrade can install 2.33...
```
figue on pluto ~ took 2s ✗  sudo LC_ALL=C downgrade perl-crypt-cbc
Available packages (community):

   1)  perl-crypt-cbc    2.33  3  remote
+  2)  perl-crypt-cbc    2.33  4  remote
-  3)  perl-crypt-cbc    3.04  1  remote

select a package by number: 2
```

**Comment by MaxiFlaxiBoii** [comment]
If i execute the downgrade command, it automatically downgrades to the version before. I don't even have the choice to select what version i want. 

It just goes to version 3.04

**Comment by figue** [comment]
It seems the source archive comes from archive.org. Try to force it with --ala-only

https://github.com/pbrisbin/downgrade

**Comment by MaxiFlaxiBoii** [comment]
OMG, tysm.

With that i could choose the version and asbru now saves my connections :D
