### ISSUE TITLE
Can't install package in Manjaro Linux

### ISSUE THREAD

**Issue by lucas-engen** [asbru-cm/asbru-cm#827]
**Describe the bug**
Failed to install asbru on arch linux

**To Reproduce**
1. Open shell and run the following commands
 - ```sudo pacman -Sy```
 - ```git clone https://aur.archlinux.org/asbru-cm-git.git && cd asbru-cm-git```
 - ```makepkg -si```

**Expected behavior**
The program should be installed correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/13322110/124863367-538c0480-df8d-11eb-92ec-34e4accbf4d8.png)

**Environment**
![image](https://user-images.githubusercontent.com/13322110/124863460-79b1a480-df8d-11eb-900c-1bb59e168024.png)

**Additional context**
The package has been updated before starting to clone asbru repo

**Comment by gfrenoy** [comment]
Not a Arch/Manjaro user but from your screenshot, I'd guess you're missing some additional repositories ?

Did you check the comments in @figue's AUR project, see https://aur.archlinux.org/packages/asbru-cm-git#comment-760766, it looks like the same issue to me.

**Comment by figue** [comment]
All those dependencies are in AUR, so you can't install them with makepkg. You can use some AUR wrapper first (I think Manjaro can handle itself with pamac) to install them or you can use the wrapper directly to install asbru-cm-git. In any case, the perl-crypt-cbc package has to be downgraded manually first because version 3.0 is not compatible with Ásbrú. Check #816 and #826

**Comment by lucas-engen** [comment]
This link helped me: https://aur.archlinux.org/packages/asbru-cm-git#comment-760766

I installed it with **trizen -S asbru-cm-git** but it failed to find dependency 'perl-crypt-cbc<3'

I edited asbru-cm-git/PKGBUILD and changed 'perl-crypt-cbc<3' to 'perl-crypt-cbc' and the asbru has been installed but seems to malfunctioning. I couldn't find methods to downgrade perl-crypt-cbc manually.

**Comment by lucas-engen** [comment]
This is the line edited:

![image](https://user-images.githubusercontent.com/13322110/125140052-10927400-e0e8-11eb-8e67-3f397eb17840.png)

**Comment by lucas-engen** [comment]
Hi guys it works

1 - I replaced 'perl-cbc-crypt<3' with 'perl-cbc-crypt' on **asbru-cm-git/PKGBUILD** to install all packages without error
2 - ``trizen -S asbru-cm-git to install asbru``
3 - ``sudo pacman -U https://archive.archlinux.org/packages/p/perl-crypt-cbc/perl-crypt-cbc-2.33-4-any.pkg.tar.zst`` to downgrade perl-cbc-crypt

Thanks for help @figue and @gfrenoy

**Comment by nquoctuan** [comment]
hi @lucas-engen , I have to login github to say thanks to you, man it took me days to check why.

**Comment by lucas-engen** [comment]
> hi @lucas-engen , I have to login github to say thanks to you, man it took me days to check why.

Thanks man. I'm glad I helped you in some way
