### ISSUE TITLE
Can not install - missing perl dependencies

### ISSUE THREAD

**Issue by wl72096** [asbru-cm/asbru-cm#829]
Can not install package due to missing perl dependencies:

[root@proton ~]# dnf install asbru-cm.noarch
asbru-cm-release                                                                                          475  B/s | 473  B     00:00    
asbru-cm-release-noarch                                                                                   413  B/s | 473  B     00:01    
asbru-cm-release-source                                                                                   466  B/s | 473  B     00:01    
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides perl(Gtk3::SimpleList) needed by asbru-cm-6.3.2-1.el8.noarch
  - nothing provides perl(OSSP::uuid) needed by asbru-cm-6.3.2-1.el8.noarch
  - nothing provides perl-IO-Tty needed by asbru-cm-6.3.2-1.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

# uname -r
4.18.0-305.7.1.el8_4.x86_64

Can anyone please advise where I can get those perl packages needed here?   Thanks a lot!

**Comment by gfrenoy** [comment]
Can you provide more information about the instructions you executed before `dnf install` ?

And here you will find some additional instructions that may help on CentOS:
  https://github.com/asbru-cm/asbru-cm/wiki/Installation-on-CentOS

**Comment by wl72096** [comment]
Hi:  thanks for the response!   This is what I did - please let me know if I am missing something:

[root@proton ~]# dnf search asbru-cm
Last metadata expiration check: 18:37:33 ago on Thu 08 Jul 2021 07:48:49 PM EDT.
====================================================================== Name Exactly Matched: asbru-cm =======================================================================
asbru-cm.noarch : A user interface that helps organizing remote terminal sessions and automating repetitive tasks.
asbru-cm.src : A user interface that helps organizing remote terminal sessions and automating repetitive tasks.

[root@proton ~]# dnf info asbru-cm.noarch
asbru-cm-release                                                                                                                             458  B/s | 473  B     00:01    
asbru-cm-release-noarch                                                                                                                      466  B/s | 473  B     00:01    
asbru-cm-release-source                                                                                                                      466  B/s | 473  B     00:01    
Available Packages
Name         : asbru-cm
Version      : 6.3.2
Release      : 1.el8
Architecture : noarch
Size         : 509 k
Source       : asbru-cm-6.3.2-1.el8.src.rpm
Repository   : asbru-cm-release-noarch
Summary      : A user interface that helps organizing remote terminal sessions and automating repetitive tasks.
URL          : https://asbru-cm.net
License      : GPLv3+
Description  : Ásbrú Connection Manager is a user interface that helps organizing remote terminal sessions and automating repetitive tasks.

[root@proton ~]# dnf repolist
repo id                                                       repo name
asbru-cm-release                                              asbru-cm-release
asbru-cm-release-noarch                                       asbru-cm-release-noarch
asbru-cm-release-source                                       asbru-cm-release-source
epel                                                          Extra Packages for Enterprise Linux 8 - x86_64
epel-modular                                                  Extra Packages for Enterprise Linux Modular 8 - x86_64
google-chrome                                                 google-chrome
nux-dextop                                                    Nux.Ro RPMs for general desktop use
ol8_UEKR6                                                     Latest Unbreakable Enterprise Kernel Release 6 for Oracle Linux 8 (x86_64)
ol8_appstream                                                 Oracle Linux 8 Application Stream (x86_64)
ol8_baseos_latest                                             Oracle Linux 8 BaseOS Latest (x86_64)
ol8_developer_EPEL                                            Oracle Linux 8 EPEL Packages for Development (x86_64)
rpmfusion-free-updates                                        RPM Fusion for EL 8 - Free - Updates
rpmfusion-nonfree-updates                                     RPM Fusion for EL 8 - Nonfree - Updates
slack                                                         slack
virtualbox                                                    Oracle Linux / RHEL / CentOS-8 / x86_64 - VirtualBox

[root@proton ~]# dnf install asbru-cm.noarch
Last metadata expiration check: 0:02:57 ago on Fri 09 Jul 2021 02:26:38 PM EDT.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides perl(Gtk3::SimpleList) needed by asbru-cm-6.3.2-1.el8.noarch
  - nothing provides perl(OSSP::uuid) needed by asbru-cm-6.3.2-1.el8.noarch
  - nothing provides perl-IO-Tty needed by asbru-cm-6.3.2-1.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by gfrenoy** [comment]
I'm really not a CentOS expert but what I can tell you is that the `Gtk3::SimpleList` for EL8 is available on our packacloud repository (see [here](https://packagecloud.io/asbru-cm/asbru-cm/packages/el/8/perl-Gtk3-SimpleList-0.18-4.el8.noarch.rpm)).

So if you have done this:
```
curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.rpm.sh | sudo bash
```

That package shall be available for you...

I'm also wondering why you add `.noarch` in the dnf install ?  Why not just `dnf install asbru-cm` ?

@popxunga Maybe you can shed a better light on this ?

**Comment by wl72096** [comment]
Thanks for the tip!   Unfortunately OL8 (which is what I am running) is not supported - crying

[root@proton ~]# curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.rpm.sh | sudo bash
Detected operating system as ol/8.
Checking for curl...
Detected curl...
Downloading repository file: https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/config_file.repo?os=ol&dist=8&source=script
curl: (22) The requested URL returned error: 404 


Unable to download repo config from: https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/config_file.repo?os=ol&dist=8&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force CentOS 6: os=el dist=6 ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.

**Comment by wl72096** [comment]
Thanks a lot for the help and I managed to force the os=el and get this tool installed!  So excited!   Time to play with the toy...
