### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by Croydon** [asbru-cm/asbru-cm#83]
Would be awesome if there would be Flatpak support.

This would reach much more distributions compared to deb/rpm

**Comment by KlaasT** [comment]
I must admit I've never heard of Flatpak. I'll have a look at the developers docs.

**Comment by gfrenoy** [comment]
Any way that can easy installation of Ásbrú would for sure be great !  At this stage (tl;dr), I don't understand what needs to be done to support [Flatpak](https://www.flatpak.org/).

At first glance, I'd say this is something the "core team" should not put as a high priority but anybody that would like to contribute is warmly welcome to help us preparing whatever is required to support this new technology.

**Comment by KlaasT** [comment]
I will be closing this for now. If anyone is keen to help us adding Flatpak support and maintaining it this help will be very welcome. However at the moment we are concentrating on the standard formats (rpm, deb etc) and the code itself. Closing #83
