### ISSUE TITLE
Need some clarifications on `Support for Crypt::CBC 3.04`

### ISSUE THREAD

**Issue by syco** [asbru-cm/asbru-cm#832]
Hi,

Not really a bug, but I noticed that since [https://github.com/asbru-cm/asbru-cm/commit/61372995970756c913e11ff26e63990fbabb50ef](https://github.com/asbru-cm/asbru-cm/commit/61372995970756c913e11ff26e63990fbabb50ef) and [https://github.com/asbru-cm/asbru-cm/commit/5caa1e4a502801bfd89b4053fb166f8abe826260](https://github.com/asbru-cm/asbru-cm/commit/5caa1e4a502801bfd89b4053fb166f8abe826260), every time I open and close the application, all `pass:` and `passphrase:` in `asbru.yml` change.

This would normally be fine, but I sync the configuration using a git solution, that means every time I use the app there's a new commit to the configuration, with a lot more conflicts to resolve.

Is this expected behavior? Re-hash passwords every time the application is used?

Thanks

**Comment by syco** [comment]
I did some more digging around `Crypt::CBC`.
If this was not intended it can be reverted by giving a valid salt:

```patch
diff --git a/lib/PACConfig.pm b/lib/PACConfig.pm
index 437eef4..ba7c425 100644
--- a/lib/PACConfig.pm
+++ b/lib/PACConfig.pm
@@ -66,7 +66,7 @@ my $CFG_DIR = $ENV{"ASBRU_CFG"};
 my $RES_DIR = "$RealBin/res";
 my $THEME_DIR = "$RES_DIR/themes/default";
 
-my $CIPHER = Crypt::CBC->new(-key => 'PAC Manager (David Torrejon Vaquerizas, david.tv@gmail.com)', -cipher => 'Blowfish', -salt => '1', -pbkdf => 'opensslv1', -nodeprecate => 1) or die "ERROR: $!";
+my $CIPHER = Crypt::CBC->new(-key => 'PAC Manager (David Torrejon Vaquerizas, david.tv@gmail.com)', -cipher => 'Blowfish', -salt => '12345678', -pbkdf => 'opensslv1', -nodeprecate => 1) or die "ERROR: $!";
 
 # END: Define GLOBAL CLASS variables
 ###################################################################
diff --git a/lib/PACMain.pm b/lib/PACMain.pm
index 6e89656..c2a0483 100644
--- a/lib/PACMain.pm
+++ b/lib/PACMain.pm
@@ -117,7 +117,7 @@ my $NEW_VERSION = 0;
 my $NEW_CHANGES = '';
 our $_NO_SPLASH = 0;
 
-my $CIPHER = Crypt::CBC->new(-key => 'PAC Manager (David Torrejon Vaquerizas, david.tv@gmail.com)', -cipher => 'Blowfish', -salt => '1', -pbkdf => 'opensslv1', -nodeprecate => 1) or die "ERROR: $!";
+my $CIPHER = Crypt::CBC->new(-key => 'PAC Manager (David Torrejon Vaquerizas, david.tv@gmail.com)', -cipher => 'Blowfish', -salt => '12345678', -pbkdf => 'opensslv1', -nodeprecate => 1) or die "ERROR: $!";
 
 our %RUNNING;
 our %FUNCS;
diff --git a/lib/PACUtils.pm b/lib/PACUtils.pm
index c4a26a1..9b43051 100644
--- a/lib/PACUtils.pm
+++ b/lib/PACUtils.pm
@@ -142,7 +142,7 @@ my $SPLASH_IMG = "$RES_DIR/asbru-logo-400.png";
 my $CFG_DIR = $ENV{"ASBRU_CFG"};
 my $CFG_FILE = "$CFG_DIR/asbru.yml";
 my $R_CFG_FILE = $PACMain::R_CFG_FILE;
-my $CIPHER = Crypt::CBC->new(-key => 'PAC Manager (David Torrejon Vaquerizas, david.tv@gmail.com)', -cipher => 'Blowfish', -salt => '1', -pbkdf => 'opensslv1', -nodeprecate => 1) or die "ERROR: $!";
+my $CIPHER = Crypt::CBC->new(-key => 'PAC Manager (David Torrejon Vaquerizas, david.tv@gmail.com)', -cipher => 'Blowfish', -salt => '12345678', -pbkdf => 'opensslv1', -nodeprecate => 1) or die "ERROR: $!";
 
 my %WINDOWSPLASH;
 my %WINDOWPROGRESS;
```

**Comment by gfrenoy** [comment]
The newer version of Crypt::CBC requires a 8-byte character string for that paramter ; search for "salt" in the [documentation](https://metacpan.org/pod/Crypt::CBC).

For some reason I don't understand today, `12345678` was not a 8-byte character string so I believed we have to to change it.

In the Crypt::CBC documentation, I read:
```
For backward compatibility reasons, passing a value of "1" will generate a random salt, the same as if no -salt argument was provided.
```

So I thought it would be easier to set "1" but maybe we should use a fixed one for the problem you are mentionning... 

Any suggestion will be welcome :)

**Comment by syco** [comment]
I'm using that patch above on Arch with `perl-crypt-cbc 3.04-1` and it's working.
Is there a different distribution I should test with?

Maybe we could enforce the salt to be 8 bytes by doing `-salt => pack('Q', '12345678')`
I tested this as well and for me they both work.

**Comment by gfrenoy** [comment]
Thanks a lot Alberto, I made some tests with `-salt => pack('Q', '12345678')` and it indeed seems to do the trick !  See the last commit (https://github.com/asbru-cm/asbru-cm/commit/3f8cfbf210e0eee0340d81fec2a976322d57f58a).

On my side, I tested it on the following environements:
 - Ubuntu 18.04 with Crypt::CBC 2.33
 - Ubuntu 20.04 with Crypt::CBC 3.04 

For the records, this issue is related to #816.

**Comment by syco** [comment]
Thanks for the update, I think that's all with this one...
