### ISSUE TITLE
Huuuuge info icon

### ISSUE THREAD

**Issue by psad73** [asbru-cm/asbru-cm#833]
**Describe the bug**
The icon in info tab is huge, not lined up with text or any other icons.

**To Reproduce**
Just starting the software

**Expected behavior**
Expected would be a slightly smaller icon, fit into the tab section.

**Screenshots**
[Screenshot](https://imgur.com/a/V6DIKj3)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04, Budgie Desktop
 - Ásbrú Version 6.2.3
 
**Additional context**
Not a serious, but a very annoying bug

**Comment by gfrenoy** [comment]
I suspect this is related to your Gtk theme ; did you try to change the theme and see if you have the same behaviour ?
