### ISSUE TITLE
Support for Pop!_OS 21

### ISSUE THREAD

**Issue by GekoCH** [asbru-cm/asbru-cm#834]
I saw the post about the integration for Pop!_OS 20.04.
However I'm on 21 and the trick in the thread "Support for Pop!_OS 20.04" does not work
Can someone help me or update asbru to be used with PopOS 21

**Comment by gfrenoy** [comment]
Hirsute version is available in our "snapshot" releases ; I did not try but this should work fine:

```
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/snapshots/cfg/setup/bash.deb.sh' | sudo -E distro=ubuntu bash
```

(note: I'll eventually add Pop!_OS 21.04)

**Comment by GekoCH** [comment]
thx  lot that solved the problem
