### ISSUE TITLE
variable not allowed to be undef where GtkTreePath is wanted (Loki branch)

### ISSUE THREAD

**Issue by lenonk** [asbru-cm/asbru-cm#839]
**Describe the bug**
When attempting to search my KeePass DB after clicking the KeyPass button while editing any connection:

*** unhandled exception in callback:
***   variable not allowed to be undef where GtkTreePath is wanted at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 59.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
INFO: Finishing (asbru-cm-loki) with pid 2770993
INFO: Finished Ásbrú Connection Manager 6.4.0 (asbru-cm-loki) (PID:2770993)...

**To Reproduce**
1. Running Manjaro with all the latest updates
2. Configure KeypassXc in Preferences
3. Open/Create a connection
4. Enter any search text and press Return

**Expected behavior**
I expected to see the entries in my KeePass DB matching my search text.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Manjaro
 - Ásbrú Version: Loki

**Additional context**

**Comment by gfrenoy** [comment]
I tried again to reproduce this today with perl 5.34 and KeePassXC 2.6.6 but all is working as expected.  If you have any additional information, feel free to add them in this issue.  In the meantime, let's close it for now.
