### ISSUE TITLE
Fedora 27/28: Permission denied opening ssh/rdp

### ISSUE THREAD

**Issue by skipperTux** [asbru-cm/asbru-cm#84]
Hi,
I installed asbru-cm on Fedora 27 using the asbru-cm-5.0.0-1.fedora-27.noarch.rpm release. Opening any ssh or rdp connection results in asbru-cm freezing, and the following error in the logs:

> May 09 12:29:58 notebook asbru-cm.desktop[10336]: INFO: Using 'Unity' tray icon
May 09 12:30:01 notebook asbru-cm.desktop[10336]: *** unhandled exception in callback:
May 09 12:30:01 notebook asbru-cm.desktop[10336]: ***   ERROR:Permission denied at /usr/share/asbru-cm/lib/PACTerminal.pm line 187.
May 09 12:30:01 notebook asbru-cm.desktop[10336]: ***  ignoring at /usr/share/asbru-cm/lib/PACMain.pm line 1405.

I have set SELinux to permissive, no change, but if I run asbru-cm as root, all works fine (whether SELinux is set to enforcing or permissive.) Same error also on Fedora 28.

Any idea how to run asbru-cm as non-root user on Fedora 27/28?

**Comment by KlaasT** [comment]
Thanks for reporting that issue. Line 187 in PACTerminal.pm tries to open a socket inside its configuration directory. (As far as I understand). It could be a permission error on the configuration directory.

**Comment by skipperTux** [comment]
Thanks for hint. Issue resolved.
I copied the ~/.config/pac folder from my other installation, that is a different distribution. So user and group did not match. After chown everything works fine.
