### ISSUE TITLE
Support to run ssh1 command for allow legacy ssh connections

### ISSUE THREAD

**Issue by davermeca** [asbru-cm/asbru-cm#842]
**Describe the bug**
Using the ssh version 8.2 in ubuntu 20.4 is not possible to connect to legacy device:
ssh -V
OpenSSH_8.2p1 Ubuntu-4, OpenSSL 1.1.1f  31 Mar 2020
you get:
ssh_dispatch_run_fatal: Connection to X.Y.Z.W port 22: Invalid key length

But if you install ssh1 you can connect to legacy device as you can see below:

 ssh1 -V
OpenSSH_7.5p1 Ubuntu-11build1, OpenSSL 1.1.1f  31 Mar 2020

 ssh1 user@X.Y.Z.W
/etc/ssh/ssh_config line 52: Unsupported option "gssapiauthentication"
Password:
HOST_LEGACY#

**To Reproduce**
Using the ssh version 8.2 in ubuntu 20.4 is not possible to connect to legacy device:
ssh -V
OpenSSH_8.2p1 Ubuntu-4, OpenSSL 1.1.1f  31 Mar 2020
you get:
ssh_dispatch_run_fatal: Connection to X.Y.Z.W port 22: Invalid key length

**Expected behavior**
ssh1 user@X.Y.Z.W
/etc/ssh/ssh_config line 52: Unsupported option "gssapiauthentication"
Password:
HOST_LEGACY#

So here is how I can select to use ssh or ssh1 command to do flexible for legacy nodes that can not connect using the updated node os define to use 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Ásbrú Version  6.3.2

**Comment by xattack** [comment]
How about recompile ?   it's an option you will always have. That way you could have a ssh client which allow you to connect to legacy and newer servers whitout problem. 

     In this [link](https://itectec.com/ubuntu/ubuntu-ssh-invalid-key-length-on-embedded-device/)  you can find the answer to this problem.
