### ISSUE TITLE
password not correct on 6.4.0

### ISSUE THREAD

**Issue by dennisTGC** [asbru-cm/asbru-cm#844]
**Describe the bug**
I have configured Asbru with --config-dir="/home/user/some dir/asbru/sync" in version 6.4.0, but this gives me an error when filling in the password:

password incorrect.

I don't have this problem with version 6.3 on another machine, so I'm sure this password is correct.  or if i use a dir without spaces (like --config-dir="/home/user/asbru/sync").

I didn't do much other research, but let me know if I need to test stuff or give more information. 

**To Reproduce**
- remove 6.4
- install 6.3

**Expected behavior**
I should be able to use my password.

**Environment (please complete the following information):**
I'm on Ubuntu 20.04.3 with KDE on a Dell Precision T3420 (both machines)

**Additional context**
I use the options
* protect with password
* keepass integration with database file and master password

**Comment by hanspr** [comment]
Hi @gfrenoy , I noticed a few months back that openssl libraries are being updated.

I recently found the very ugly way that encryption algorithms change through version changes and you can not decrypt  with a newer library that was encoded with an older one. No matter you are using the same commands, encryption algorithm names.

All encryptions are being updated with new releases, all must be related to openssl, probably many packages use those libraries.

I had to get a previous openssl library (openssl-1.0.2k) to be able to decrypt my encrypted backups, and encrypt them again with the new ones. Probably there are some flags that can be used to do this sort of migrations, but I did not dedicate time to check it.

This sounds very similar to me.
