### ISSUE TITLE
Merging of two yaml configurations asbru-cm (for wiki)

### ISSUE THREAD

**Issue by Prototype-X** [asbru-cm/asbru-cm#85]
Task: append hosts and groups from `pac-src.yml` to `pac-dst.yml`

1. Open `pac-src.yml` and copy all between tags `environments:` and `tmp:`
2. Paste to `pac-dst.yaml` between last host `variables: []` and `tmp:`
3. Find in `pac-src.yml`: `__PAC__ROOT__:`, copy children UUID
4. Find in `pac-dst.yml`: first `__PAC__ROOT__:`, append children UUID
5. Find in `pac-dst.yml` second `__PAC__ROOT__:`and remove it
6. Save file `pac-dst.yml`
7. Import connections from `pac-dst.yml`

Request feature: Import connections with merge

**Comment by gfrenoy** [comment]
Thanks for your help !  Your tip has been added to the [wiki](https://github.com/asbru-cm/asbru-cm/wiki/Tips-and-Tricks) :)
