### ISSUE TITLE
Support for "postpend" options on generic command

### ISSUE THREAD

**Issue by teicors** [asbru-cm/asbru-cm#850]
I like to colourize the output of my logs in order to catch better the faults, the errors and so on.
I patched the pac_conn line 1098 (ver 6.1.3) in order to add the command ct (ChromTerm) as below:

$connection_cmd = "$METHOD -p $PORT $key $CONNECT_OPTS " . ($USER ? "-l $USER " : '') . "$IP|/home/user/anaconda3/bin/ct";

I cannot able to add a flag in order to put or not the part "|/home/angelo/anaconda3/bin/ct" in the command line in order to use or not ChromTerm.
Can do you do this ?

Cheers,
Angelo

**Comment by teicors** [comment]
in the latest 6.3.3 the line 1099
                          . " $IP |/home/user/anaconda3/bin/ct";

**Comment by kjuanman** [comment]
Great, please send a link to a fork with your code and I will test it.
You can create a pull request too. I dont have permissions to approve a Pull Request, but I can test it.

**Comment by gfrenoy** [comment]
@teicors Can you confirm all is now working as expected on the `loki` branch ?  Thanks !

**Comment by teicors** [comment]
Yes. It works as expected.
