### ISSUE TITLE
Trigger local macros from right click menu

### ISSUE THREAD

**Issue by erenseymen** [asbru-cm/asbru-cm#851]
**SETUP:**

I use a local macro to sftp with my file manager (nautilus).

![image](https://user-images.githubusercontent.com/27849007/136695994-6204bcda-0cb6-43e8-9294-f04c62983290.png)

I've assigned a keyboard shortcut in order to trigger this local macro.

**REQUEST:**

Please add local macros to the [right click menu of connections](https://user-images.githubusercontent.com/27849007/136696421-bb9f353a-d1bb-461b-b8e1-365b66812902.png) so custom commands can be run easily.

mRemoteNG has this feature as below:

![image](https://user-images.githubusercontent.com/27849007/136696826-f35bddea-98a0-4579-bde9-b76b4eb4cb96.png)

**Comment by xattack** [comment]
Hi @erenseymen 

  This feature it's already part of asbru-cm , just use the right click and you can see it . By the way I didn't assign a
keyboard shortcut to it.



  
![IMG_20211010_141545266](https://user-images.githubusercontent.com/8902460/136710356-18b1ee10-426a-43d6-88a9-1a4eaa95af23.jpg)
