### ISSUE TITLE
elementaryOS6

### ISSUE THREAD

**Issue by VigourZHAO** [asbru-cm/asbru-cm#855]
**Describe the bug**
Install tools failed.

**To Reproduce**
1. curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
2. Click on 'Enter'
3. Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=elementary  version=6  codename=odin  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
 NOPE: Checking if upstream install config is OK ...
 ^^^^: ... Failed to fetch configuration for your OS distribution release/version.
 >>>>:
 >>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=elementary  version=6  codename=odin  arch=x86_64  
 >>>>:
 >>>>: You can force this script to use a particular value by specifying distro,
 >>>>: version, or codename via environment variable. E.g., to specify a distro
 >>>>: such as Ubuntu/Xenial (16.04), use the following:
 >>>>:
 >>>>:   <curl command> | distro=ubuntu version=16.04 codename=xenial sudo -E bash
 >>>>:
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact asbru-cm for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/asbru-cm/asbru-cm
 !!!!: 
 !!!!: Last 20 log lines from .csm_setup_Dh2iNqgiY (might not be errors, nor even relevant):
 !!!!:
 !!!!: > Warning: apt-key output should not be parsed (stdout is not a terminal)
 !!!!: > OK

**Expected behavior**
Looking forward to your reply

**Screenshots**
![image](https://user-images.githubusercontent.com/56986081/138220542-682f36c7-7ca3-49a3-8806-d29353a25b92.png)

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/56986081/138220611-82f019f3-36aa-49a4-a743-9dc30c891ecc.png)

**Comment by xinxilas** [comment]
Can you add to Zorin OS to?
>>>>:
 >>>>: ... distro=zorin  version=16  codename=focal  arch=x86_64  
 >>>>:

**Comment by TytussPulo** [comment]
Could you add support for Zorin Pro 17 as well?

 >>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=zorin  version=17  codename=jammy  arch=x86_64
