### ISSUE TITLE
"Save and Close" button does not save configuration to a file and does not close configuration window

### ISSUE THREAD

**Issue by alexus-m** [asbru-cm/asbru-cm#858]
**Describe the bug**
"Save and Close" button successfully applies changes but does not saves configuration to a file and does not close configuration window neither connection's configuration nor general preferences.

**To Reproduce**
It is the first installation of Asbru-CM. There was neither configuration folder "\~/.config/asbru/" nor legacy "\~/.config/pac*".
1. Start Asbru-CM.
  Open "Edit connection" or general "Preferences" window.
2. Make some configuration changes then press "Save and Close" button.
3. The configuration window left opened on screen:
  The configuration changes are successfully applied to a current process but configuration does not saved to a configuration file and configuration window is not closed. The window can still get closed via neighbour "Close without saving" button.)
There are some debug records appear in terminal window:
DEBUG:KEEPASS: Update usage
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /usr/share/asbru-cm/lib/PACUtils.pm line 2713.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.

4. If try to close Asbru-CM window via Ctrl-Q or via "Quit" button then asbru-cm process left running in background and "new" start of Asbru-CM shows up all the configuration I made and "saved".
  If I close the main window via window management "X" button then asbru-cm process disappears and new start begin with clean configuration.
  There is no asbru.yml file appears in ~/.config/asbru/. But some files are there, e.g. 
asbru.pcc
asbru_stats.nfreeze
asbru.yml.gui
asbru.yml.tree
**autostart
bak
screenshots
scripts
session_logs
sockets
tmp**

**Expected behavior**
"Save and Close" button should save configuration to a file and then close the configuration window after changes have been saved.

**Screenshots**
No need.

**Environment (please complete the following information):**
 - OS: Fedora 35
 - Ásbrú Version: loki (asbru-cm-6.4.0~1635596963-1.fc34.noarch)

**Comment by gfrenoy** [comment]
Likely related to #816, strange that it does not work for you... Can you confirm which version of Crypt::CBC ?

**Comment by alexus-m** [comment]
> Likely related to #816, strange that it does not work for you... Can you confirm which version of Crypt::CBC you are using (likely 3.04) ?

Hi @gfrenoy ! Thanks a lot for your response!
$ rpm -qa | grep -i perl.*cbc
perl-Crypt-CBC-3.04-4.fc35.noarch

**Comment by alexus-m** [comment]
I'm not familiar with perl but did a try an attempt to take a look into that via modification on Crypt::CBC library. I've inserted some print-s in a chain of called subroutines:
sub encrypt_hex (\$$)
sub decrypt_hex (\$$)
sub crypt (\$$)
  Result of
"perl -MCarp::Always $(which asbru-cm) &>/tmp/asbru-cm.log"
attached.
  It is visible out of the log that asbru-cm has some invocations of "decrypt_hex" in the very beginning and interesting are the first 3 of therm:
1. the first one looks good:
decrypt_hex() called parameters:
        2 = Crypt::CBC=HASH(0x556b5e8d4480) 
crypt() called parameters:
        0 = 
crypt() variables:
        Decript = 1
        Salt = **Na¼^@^@^@^@^@**
2. the second has unexpected "<<ASK_PASS>>":
decrypt_hex() called parameters:
        2 = Crypt::CBC=HASH(0x556b5e8d4480) **<<ASK_PASS>>**
crypt() called parameters:
        0 = 
crypt() variables:
        Decript = 1
        Salt = 
3.  the third and all other attempts look wrong - with empty salt:
decrypt_hex() called parameters:
        2 = Crypt::CBC=HASH(0x556b5e8d4480) 
crypt() called parameters:
        0 = 
crypt() variables:
        Decript = 1
        Salt = 

  Then encrypt goes in the same wrong way:
encrypt_hex() called parameters:
        2 = Crypt::CBC=HASH(0x556b5e8d4480) 
crypt() called parameters:
        0 = 
crypt() variables:
        Decript = 
        Salt =

**Comment by alexus-m** [comment]
I'm sorry - accidentally touched "Close with comment"...
Reopened then.

**Comment by alexus-m** [comment]
INFO: Finishing (asbru-cm) with pid 166421
DEBUG: Saving window position = (26, 23) ; window size (1024, 768)
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /usr/share/perl5/vendor_perl/Crypt/CBC.pm line 632.
***   	Crypt::CBC::set_key_and_iv(Crypt::CBC=HASH(0x565420bebd90)) called at /usr/share/perl5/vendor_perl/Crypt/CBC.pm line 699
***   	Crypt::CBC::_generate_iv_and_cipher_from_options(Crypt::CBC=HASH(0x565420bebd90)) called at /usr/share/perl5/vendor_perl/Crypt/CBC.pm line 192
***   	Crypt::CBC::crypt(Crypt::CBC=HASH(0x565420bebd90), "") called at /usr/share/perl5/vendor_perl/Crypt/CBC.pm line 127
***   	Crypt::CBC::encrypt(Crypt::CBC=HASH(0x565420bebd90), "") called at /usr/share/perl5/vendor_perl/Crypt/CBC.pm line 142
***   	Crypt::CBC::encrypt_hex(Crypt::CBC=HASH(0x565420bebd90), "") called at /usr/share/asbru-cm/lib/PACUtils.pm line 2713
***   	PACUtils::_cipherCFG(HASH(0x56541f1e0228)) called at /usr/share/asbru-cm/lib/PACConfig.pm line 630
***   	PACConfig::_exporter(PACConfig=HASH(0x565422c8ca28), "yaml", "/home/mayorov/.config/asbru/asbru.yml") called at /usr/share/asbru-cm/lib/PACMain.pm line 3360
***   	PACMain::_quitProgram(PACMain=HASH(0x56541f1dffb8)) called at /usr/share/asbru-cm/lib/PACMain.pm line 2332
***   	PACMain::__ANON__(Gtk3::Window=HASH(0x565422bb9838), Gtk3::Gdk::Event=SCALAR(0x565423f0b2d8)) called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
***   	eval {...} called at /usr/share/perl5/vendor_perl/Gtk3.pm line 572
***   	Gtk3::main("Gtk3") called at /usr/share/asbru-cm/lib/PACMain.pm line 438
***   	PACMain::start(PACMain=HASH(0x56541f1dffb8)) called at /usr/bin/asbru-cm line 203
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
	Gtk3::main("Gtk3") called at /usr/share/asbru-cm/lib/PACMain.pm line 438
	PACMain::start(PACMain=HASH(0x56541f1dffb8)) called at /usr/bin/asbru-cm line 203
Segmentation fault (core dumped)

**Comment by gfrenoy** [comment]
@alexus-m Will you test the latest loki build and let us know if the latest commit correctly fixed the issue ?

Thanks again for reporting it !

**Comment by alexus-m** [comment]
Dear team,
asbru-cm-6.4.0~1638052815-1.fc34.noarch
on Fedora 25
now works as expected:
In case of there is no ~/.config/asbru folder then Asbru successfully saves configuration file asbru.yml from scratch before exit and closed window with it's process without any problem.
Thank you for the solution!

**Comment by lometur** [comment]
I apologize if I am commenting improperly, however this issue is also occurring for me running Ubuntu 22.04. The highest version I can go to is 6.3.3, which is appropriate given that according to this repo, 6.3.3 was released 5 days ago, however, I see that the solution was 6.4.0? I apologize for my ignorance and if I have commented incorrectly. Is 6.4.0 going to be available soon to fix this issue or is there something else I must do, or something I have missed?

**Comment by gfrenoy** [comment]
For those who were redirected here, until a new stable version is released : please try the latest `loki` branch (see https://docs.asbru-cm.net/General/Installation/) or our AppImage (see https://www.appimagehub.com/p/1796061).  It has been fixed there.
