### ISSUE TITLE
scrollable tab bar

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#868]
Hi, because i daily open a lot of terminals i placed my tab bar on the right side (more tabs are visible). What is the pain is scrolling through them when my tabs exceeds available screen space. It would be nice to have ability to scroll this list with mouse wheel. The same way like the list with connections. What would be even better is option to use the same widget like for connections. It occupies less space and is scrollable

**Comment by gfrenoy** [comment]
This is the same as #636 & #358, isn't it ?

**Comment by vibo69** [comment]
yup. the goal is the same
