### ISSUE TITLE
Tray Icon in Unity

### ISSUE THREAD

**Issue by toptnc** [asbru-cm/asbru-cm#870]
**Is your feature request related to a problem? Please describe.**
Since GTK3::Appindicator does not exists, tray icon in Unity has been disabled

**Describe the solution you'd like**
Other GTK3 Perl apps like Shutter have solved the problem without needing a Gtk3::Appindicator module.
https://github.com/shutter-project/shutter/blob/master/bin/shutter#L647

It seems like Gtk3::StatusIcon may work in Gnome Shell and Unity

**Comment by toptnc** [comment]
I think I have done it. 

Patch is attached.


[indicator-unity.diff.gz](https://github.com/asbru-cm/asbru-cm/files/7513274/indicator-unity.diff.gz)

**Comment by gfrenoy** [comment]
Thanks a lot for your help on this !  That'd be great if we can manage this properly !

Let's keep this open until we finalize the PR...

**Comment by gfrenoy** [comment]
Fernando, it seems that this is causing some side issues and I'd like to enable the use of `AppIndicator3` only when required and use the default tray icon as the first choice.

Can you give me a bit more information about your environment:
- which distro (Ubuntu I guess)
- which version (Unity is not used anymore by default...)
- value of environment variables `XDG_SESSION_DESKTOP`
- are using using GNOME extensions like Unite or Top Icons ?
- what is shown when you run `./asbru-cm` from the commandl line (especially the detected environment)

Thanks.

**Comment by toptnc** [comment]
Distro: Ubuntu 20.04
Unity Version: 7.5.1+20.04.20211026
XDG_SESSION_DESKTOP=unity
Not, i'm not using Gnome extensions since I don't use Gnome

This is my output when I run asbru-cm from the command line

***@***.***:~$ /opt/asbru/asbru-cm
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 298610
INFO: Language detected : es_ES.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : other
INFO: Config directory is '/home/fsancho/.config/asbru'
GLib-LOG **: unsetenv() is not thread-safe and should not be used after
threads are created at
/usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
INFO: Used config file '/home/fsancho/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.60
INFO: Theme directory is '/opt/asbru/res/themes/default'
INFO: Using Unity tray icon

**Comment by gfrenoy** [comment]
Thanks for your feedback !  As the code is now and as shown by your trace:

>    INFO: Using Unity tray icon

I'd guess the detection is working fine for your case...Let's leave this open for a few more days and if no other remarks is given, let's close the issue.
