### ISSUE TITLE
Asbru-cm 6.3.3 not saving connections - fedora34

### ISSUE THREAD

**Issue by ferchimi** [asbru-cm/asbru-cm#879]
**Describe the bug**
I can create new connections and make correct use of them, but, despite I manually save them or enable autosave, they never ever get saved
**To Reproduce**
1. Install or simply clone repo and run asbru-cm
2. Create a new connection or group: "Save and close" button does not close connection creation window, AND on terminal I get
WARNING: The key derivation method "opensslv1" is deprecated. Using -pbkdf=>'pbkdf2' would be better.
Pass -nodeprecate=>1 to inhibit this message.
 at /root/asbru-cm/lib/PACUtils.pm line 2718.
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /root/asbru-cm/lib/PACUtils.pm line 2718.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
WARNING: The key derivation method "opensslv1" is deprecated. Using -pbkdf=>'pbkdf2' would be better.
Pass -nodeprecate=>1 to inhibit this message.
 at /root/asbru-cm/lib/PACUtils.pm line 2718.
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /root/asbru-cm/lib/PACUtils.pm line 2718.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
3. Manually save connections or check autosave
4. No errors get displayed on gnome window, but on terminal I get on clicking "Save"
WARNING: The key derivation method "opensslv1" is deprecated. Using -pbkdf=>'pbkdf2' would be better.
Pass -nodeprecate=>1 to inhibit this message.
 at /root/asbru-cm/lib/PACUtils.pm line 2718.
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /root/asbru-cm/lib/PACUtils.pm line 2718.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.

**Expected behavior**
Asbru correctly saves all configuration including connections

**Screenshots**

**Environment (please complete the following information):**
 - OS: Fedora release 34 (Thirty Four)
 - Ásbrú Version 6.3.3 and loki 6.4.0 tested

**Additional context**

**Comment by Moltenkore** [comment]
I'm having the same issue in 6.3.2

```
WARNING: The key derivation method "opensslv1" is deprecated. Using -pbkdf=>'pbkdf2' would be better.
Pass -nodeprecate=>1 to inhibit this message
```

**Comment by gfrenoy** [comment]
See #816
