### ISSUE TITLE
zssh support

### ISSUE THREAD

**Issue by w420372197** [asbru-cm/asbru-cm#88]
This software support zssh ？ i want use rz sz upload/download file

**Comment by gfrenoy** [comment]
I've never seen anything about zssh in Ásbrú so I guess it is not supported.

As Ásbrú is not a file transfer software, I don't see exactly how you would use zssh inside Ásbrú...?

**Comment by w420372197** [comment]
transmission file use ftp need new window，this is not convenient，use rz/sz transmission file is convenient。i publish project need operation Multiple linux，window too many.。in china company use rz/sz  transmission file great many

**Comment by gfrenoy** [comment]
So [rz/sz](https://linux.die.net/man/1/zssh) can be used like you would any other file transfer command (like [scp](https://linux.die.net/man/1/scp)).  It's a command line tool so you can use it today if you are connected to a machine that has that tool installed, can't you ?

Said differently : can you describe a bit more in details how you would integrate rz in Ásbrú ?

**Comment by gfrenoy** [comment]
I still don't get the point here ... I believe we would need a more detailed description (with screenshots maybe?) on how you would envision this integration.

Thanks.

**Comment by gfrenoy** [comment]
Closed due to inactivity; feel free to re-open when you can provide detailed description.

**Comment by netroby** [comment]
@gfrenoy may i using zssh replace builtin ssh ? because we really need using zssh to run (rz sz)
To download , upload file

**Comment by netroby** [comment]
I found it is possible to run zssh with asbru-cm
![screenshot_2019-02-26_14-56-35](https://user-images.githubusercontent.com/278153/53457557-c441be80-3a6d-11e9-9412-e9954ad1b949.png)
While connect to the server, press CTRL+SHIFT+2, you can open zssh window, and you now can upload file by sz filename.ext

**Comment by gfrenoy** [comment]
Thanks for your feedback !

"Generic Command" is indeed the way to go for custom command lines.

**Comment by netroby** [comment]
This can be add into asbru-cm documentation.
