### ISSUE TITLE
asbru-cm loki latest -Main window doesn't show up when I click the systray icon

### ISSUE THREAD

**Issue by luca-martino** [asbru-cm/asbru-cm#880]
**Describe the bug**
Can't locate object method "get_visible" via package "AppIndicator::Indicator" at /usr/share/asbru-cm/lib/PACMain.pm line 1103.

**To Reproduce**
DNF Update
On Fedora 34 - Repo: asbru-cm_loki | version 6.4.0~1636892049-1.fc33
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 1148
INFO: Language detected : it_IT.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : gnome-shell:gnome-xorg
INFO: Config directory is '/home/xeon/.config/asbru'
INFO: Used config file '/home/xeon/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.64
INFO: Theme directory is '/usr/share/asbru-cm/res/themes/asbru-dark'
INFO: Using Unity tray icon
Can't locate object method "get_visible" via package "AppIndicator::Indicator" at /usr/share/asbru-cm/lib/PACMain.pm line 1103.

**Environment:**
 - OS: Fedora 34
 - Ásbrú Version asbru-cm_loki 6.4.0~1636892049-1.fc33

Rollback to 6.4.0~1636279692-1.fc33

**Comment by gfrenoy** [comment]
The latest PR (#872) indeed introduced an issue in compact mode.  Thanks for reporting !

I just pushed a fix for that ; the build is ongoing and shall be ready in 30 min for testing.  Let me know if this should not resolve the issue.

**Comment by luca-martino** [comment]
Now asbru-cm starts up correctly on compact mode ...but the connections menu it's displayed always the first time and always on the left upper corner. 

6.4.0~1637012486-1.fc33

![immagine](https://user-images.githubusercontent.com/17565704/142029740-f3dcd29b-35d6-4165-bb39-62d34affa278.png)

**Comment by gfrenoy** [comment]
>Now asbru-cm starts up correctly on compact mode

Yes, I did not find a way to find the icon position with [libappIndicator](https://launchpad.net/libappindicator).

See the portion of code that needs to be completed / improved:

https://github.com/asbru-cm/asbru-cm/blob/47fe9abe51fb46a8f387c71d33bb2332afadbf06/lib/PACTrayUnity.pm#L116-L122

**Comment by gfrenoy** [comment]
I made a change to revert back to the old way of managing the tray icon.  This should avoid the problem introduced with the use of `AppIndicator3`.

Let me know if this fixes the issue.  Thanks.

**Comment by luca-martino** [comment]
> I made a change to revert back to the old way of managing the tray icon. This should avoid the problem introduced with the use of `AppIndicator3`.
> 
> Let me know if this fixes the issue. Thanks.

Asbru main window doesn't show up when I click the systray icon.

Steps to reproduce the behavior:
   - Have Asbru setup to start iconified;
   - Left click the systray icon;
   - Just the systray icon menu is show (Asbru Window does not show up);
   - In order to get the Asbru window opened is necessary to select the Show Window option from the systray icon context menu.

Environment:
    OS: Fedora 34
`Name        : asbru-cm`
`Version     : 6.4.0~1638701613`
`Release     : 1.fc34`
`Architecture: noarch`
`Install Date: Thu 09 Dec 2021 09:55:37 AM CET`
`Source RPM  : asbru-cm-6.4.0~1638701613-1.fc34.src.rpm`
`Build Date  : Sun 05 Dec 2021 11:55:08 AM CET`
`Build Host  : e3bbabee46e2`

...  [(884)](https://github.com/asbru-cm/asbru-cm/issues/884)

**Comment by luca-martino** [comment]
> > Just the systray icon menu is show (Asbru Window does not show up);
> 
> This is happening because `AppIndicator3` has been detected.
> 
> Can you start Ásbrú on the command line and let me know what you see, preferably in verbose mode --> `asbru-cm --verbose`.


INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 4894
INFO: Language detected : it_IT.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : gnome-shell:gnome-xorg
INFO: Config directory is '/home/xeon/.config/asbru'
INFO: Crypt::CBC version is 3.01
INFO: Used config file '/home/xeon/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.64
       - has_bright = 1
       - major_version = 0
       - minor_version = 64
       - vte_feed_binary = 1
       - vte_feed_child = 1
INFO: Theme directory is '/usr/share/asbru-cm/res/themes/asbru-dark'
INFO: Trying to loading Unity specific tray icon package...
INFO: Using Unity tray icon
DEBUG: Starting window position = (0, 0} ; window size (220, 600)
DEBUG: Saving window position = (0, 0) ; window size (220, 600)

**Comment by gfrenoy** [comment]
> INFO: Desktop environment detected : gnome-shell:gnome-xorg

Mmm, it did not detect any tray extension (like [Unite](https://extensions.gnome.org/extension/1287/unite/) or [Top Icons](https://extensions.gnome.org/extension/495/topicons/)), are you using another one ?

**Comment by luca-martino** [comment]
> > INFO: Desktop environment detected : gnome-shell:gnome-xorg
> 
> Mmm, it did not detect any tray extension (like [Unite](https://extensions.gnome.org/extension/1287/unite/) or [Top Icons](https://extensions.gnome.org/extension/495/topicons/)), are you using another one ?
Extensions list:
![immagine](https://user-images.githubusercontent.com/17565704/147389745-eb5d6f4e-69f0-42cd-bdfb-9589bb5dd0f3.png)

**Comment by gfrenoy** [comment]
Ok I've added `https://github.com/ubuntu/gnome-shell-extension-appindicator` to the list.  Will be available in the next loki build ; let me know if this helps.

**Comment by luca-martino** [comment]
> Ok I've added `https://github.com/ubuntu/gnome-shell-extension-appindicator` to the list. Will be available in the next loki build ; let me know if this helps.

...it works like a charm, as always great job
