### ISSUE TITLE
huge tray icon

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#883]
as you can see below.. this weird thing on my tray/notification applet is in fact cropped asbru icon :D 

![image](https://user-images.githubusercontent.com/33600494/141961615-335847e0-6d91-47bd-a35e-9b13fbb5e92e.png)

this is 'indicator plugin' for xfce4

everything is debian 10 stable up to date
asbru-cm (6.4.0~1637012478-1) loki

also default action for single click on the icon changed.. it shows menu instead of hide/unhide asbru

**Comment by vibo69** [comment]
maybe related to #870 ?

**Comment by vibo69** [comment]
downgrade to 6.4.0~1636279685-1 resolves the problem in my case

**Comment by gfrenoy** [comment]
The last commit should revert back to the old way of managing the tray icon. This should avoid the problem introduced with the use of `AppIndicator3`.

Let me know if this fixes the issue. Thanks.
