### ISSUE TITLE
Asbru main window doesn't open/show when I click the systray icon

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#884]
**Describe the bug**
Asbru main window doesn't show up when I click the systray icon.

**To Reproduce**
1. Have Asbru setup to start iconified;
2. Left click the systray icon;
3. Just the systray icon menu is show (Asbru Window does not show up);
4. In order to get  the Asbru window opened is necessary to select the Show Window option from the systray icon context menu.
5. Additionally, If there's is another Window already open in the desktop, let's say a terminal, the Asbru Window is show behind that window.

**Expected behavior**
Asbru Window should be shown when the systray icon is left clicked and should be shown on front of other opened windows.
Asbru systray context menu should be shown when the systray icon is right clicked.

**Environment (please complete the following information):**
 - RHEL 8.4 and CentOS Stream release 8
 - Ásbrú  Loki latest version (asbru-cm-6.4.0~1637012480-1.el8.src.rpm)

**Additional context**
Not sure if the error message displayed on terminal upon Asbru startup e related or not:
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 1379405
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : gnome-shell:gnome-withtray
INFO: Config directory is '/xxx/xxx/xxxx/pac'
INFO: Used config file '/xxx/xxx/xxx/pac/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.52
INFO: Theme directory is '/usr/share/asbru-cm/res/themes/asbru-dark'
INFO: Using Unity tray icon

(asbru-cm:1379405): Gdk-CRITICAL **: 16:51:06.684: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Thanks for your support.

**Comment by popxunga** [comment]
Hi @gfrenoy and @hanspr 
Could #872 be the cause ?
If yes please consider revert the PR merge.
Thanks.

**Comment by popxunga** [comment]
Just retested with the latest loki build asbru-cm-6.4.0~1638052800-1.el8.src.rpm and the problem still occurs on RHEL 8.4 but but it doesn't occur on CentOS Stream Release 8 anymore.
So I guess the issue might not be in the Asbru code but in some other dependent package as I don't see any related commit.
The reported error message while starting Asbru now appears on RHEL 8.4 only. So I guess it is directly related with this issue.

**Comment by gfrenoy** [comment]
It has to do with the detection of `AppIndicator3` or `AyatanaAppIndicator3` ; if it is installed, we use it.  Otherwise, we are using our own tray icon based on `Gtk3::StatusIcon`.

I'm currently reviewing the code the make `Gtk3::StatusIcon` the default but I'm struggeling understand when we would like to use `AppIndicator3` ?!

See also #870.

In any case, expect to have the previous behaviour reverted in the next build.

**Comment by gfrenoy** [comment]
The last commit should revert back to the old way of managing the tray icon. This should avoid the problem introduced with the use of `AppIndicator3`.

Let me know if this fixes the issue. Thanks.

**Comment by popxunga** [comment]
Hi @gfrenoy 
Yes it does. Thanks.
However the EXPECT processing after login is broken in the last two loki builds (I didn't test/check the 3rd oldest loki build).
I got back to asbru-cm-6.4.0~1637012480-1.el8 which has the systray icon problem but where the EXPECT works fine.

**Comment by gfrenoy** [comment]
> EXPECT processing after login is broken

Mmm, I'd guess this commit bb92cd2f0a229e45ae6eb79b102c592a9be42a3e (see #876) is responsible for the change but it actually fixed a behaviour that was not correct.

Can you elaborate on what is not working anymore for you ?

**Comment by popxunga** [comment]
Hi @gfrenoy  ... sure ...

In a simple Expect sequence defined as follows, the step 0 is ignored/not processed:

![image](https://user-images.githubusercontent.com/37672088/143947428-bb1c5329-bc30-4d07-9c24-3b0a25bb17a7.png)

In fact from a brief test looks like it is ignoring any step where  <command prompt> is expected.

**Comment by alexus-m** [comment]
> > EXPECT processing after login is broken
> 
> Mmm, I'd guess this commit [bb92cd2](https://github.com/asbru-cm/asbru-cm/commit/bb92cd2f0a229e45ae6eb79b102c592a9be42a3e) (see #876) is responsible for the change but it actually fixed a behaviour that was not correct.

Hi @gfrenoy!
I left a comment on the commit bb92cd2 with my findings with an example. It looks like match part of detected command prompt is not forwarded to the first expect evaluation but "After match string" only. The latter depends on received prompt string and could be just few last symbols, only the last white space or even empty string.

**Comment by gfrenoy** [comment]
> In a simple Expect sequence defined as follows, the step 0 is ignored/not processed

Let's create another issue to fix this.  The original purpose of this one has been fixed, right ?

**Comment by popxunga** [comment]
Hi @gfrenoy 
Just created issue #897.
Closing this one.
Thanks for your support.
