### ISSUE TITLE
asbru frozen when local command executed via keybinding

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#889]
1. create local command. eg: vncviewer <IP>
2. setup keybinding to this command
3. execute using this keybinding

as in topic - when you run local command via keybinding whole asbru is frozen/unresponsive untill you exit this local command. in my case vncviewer. 
if I execute this from context menu everything is working fine

asbru-cm (6.4.0~1636279685-1) loki

**Comment by hanspr** [comment]
PR #890 sent

you may uncheck the "send intro" option in your local command to avoid the issue.

**Comment by vibo69** [comment]
I unchecked 'intro' and it is now better but if you execute command via keybinding again it is not working:
1. execute via keybinding
2. close (eg. vncviewer)
3. repeat 1 step
I have 3 commands defined with keybindings. each one works only once. you cant execute it again in that specific terminal.
also if keybinding involves ctrl+s terminal freezes on second time. in my case it is ctrl+alt+s. so it behaves like there were no alt pressed

**Comment by hanspr** [comment]
Then you will have to wait for the PR to be merged

**Comment by gfrenoy** [comment]
@vibo69 Will you give it a try with the latest loki build and let us know if the issue has been fixed ?

**Comment by vibo69** [comment]
`$ asbru-cm --verbose
INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 19888
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : xfce
INFO: Config directory is '/home/vibo/.config/asbru'
INFO: Crypt::CBC version is 2.33
INFO: Used config file '/home/vibo/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.54
       - has_bright = 1
       - major_version = 0
       - minor_version = 54
       - vte_feed_binary = 1
       - vte_feed_child = 1
INFO: Theme directory is '/opt/asbru/res/themes/asbru-dark'
INFO: Using Unity tray icon
DEBUG: Starting window position = (maximized, maximized} ; window size (maximized, maximized)

TigerVNC Viewer 64-bit v1.9.0
Built on: 2020-09-29 18:21
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.

`

asbru-cm (6.4.0~1638052794-1)

freezing fixed in this version no matter if 'sending intro' is enabled or not.
2nd run same command no matter if i exit from it or not doesnt lunch this command (every command can be run only once in exact terminal session). if you run local command from context menu you can run it as many times you want. but not with keybinding shortcut

**Comment by gfrenoy** [comment]
@vibo69 Not sure to understand if we still have an open issue here (or not), can you confirm if the original issue has been fixed, thanks.

**Comment by vibo69** [comment]
fixed in latest release. thanks ;)
