### ISSUE TITLE
Unable to install a working version on Opensuse 15.3 

### ISSUE THREAD

**Issue by marcheschi** [asbru-cm/asbru-cm#891]
Hi 
First of all thank you for your effort, the software appears great.
I tried everything and cannot install a working latest version.
I tried also to compile it, but it produces a lot of docker errors.
Also, the AppImage that usually work fine in openSUSE, fails.
Is there a solution in order to make it work?
Thank you
Best regards
Paolo

**Comment by marcheschi** [comment]
I find out that if the appimage is executed with:
GI_TYPELIB_PATH=/usr/lib64/girepository-1.0/ ./asbru-cm-6.3.2-2-x86_64.AppImage 
it is better (It shows the splash screen) and  goes ahead but with another error:
WARN: Adding new keybinding [Ctrl+R] for [Terminal]/[Restart connection (close and start)]...
WARN: Adding new keybinding [Ctrl+b] for [Terminal]/[Paste and regex delete]...
Can't find information for method TreeModel::sort_new_with_model at /tmp/.mount_asbru-ZwQtpa/opt/asbru/lib/PACCluster.pm line 403.
it seems to me the same error as #421
Paolo

**Comment by gfrenoy** [comment]
Thanks for your contribution and findings, this is very interesting !  Please let continue the discussion on #804.
(Basically, we need to have an AppImage expert on board ...)

**Comment by marcheschi** [comment]
Solved here: https://github.com/asbru-cm/asbru-cm/issues/804#issuecomment-993678884
