### ISSUE TITLE
Get along with dark color schemes

### ISSUE THREAD

**Issue by SteveSte** [asbru-cm/asbru-cm#892]
I'm using a dark gnome color scheme, 
It's weird that the left connections panel uses a black text color with a dark gray background making it barely readable.
Note that the History panel uses a white text color. 
![image](https://user-images.githubusercontent.com/10895560/143784823-4c72bb9c-c7a0-499f-92ee-d4fb93fb1811.png)

**Comment by gfrenoy** [comment]
The defaults are not good for dark themes, indeed.  You can override this manually.

See #640 for details.
