### ISSUE TITLE
Rocky Linux 8.5 Support

### ISSUE THREAD

**Issue by plazarch** [asbru-cm/asbru-cm#894]
Please add support for Rocky Linux 8.5

 NOPE: Checking for dnf dependency 'dnf-plugin-config-manager' ...
   OK: Attempting to install 'dnf-plugin-config-manager' ...
 NOPE: Checking if upstream install config is OK ...
 ^^^^: ... Failed to fetch configuration for your OS distribution release/version.
 >>>>:
 >>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=rocky  version=8.5  codename=Green  arch=x86_64  
 >>>>:
 >>>>: You can force this script to use a particular value by specifying distro,
 >>>>: version, or codename via environment variable. E.g., to specify a distro
 >>>>: such as SUSE Linux Enterprise Server 12, use the following:
 >>>>:
 >>>>:   <curl command> | distro=sles version=12.1 codename= sudo -E bash
 >>>>:
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact asbru-cm for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/asbru-cm/asbru-cm
 !!!!: 
 !!!!: Last 20 log lines from .csm_setup_r5ohIcDnB (might not be errors, nor even relevant):
 !!!!:
 !!!!: > AtomEditor_atom                                 545  B/s | 833  B
 !!!!: > 00:01
 !!!!: > AtomEditor_atom-source                          639  B/s | 819  B
 !!!!: > 00:01
 !!!!: > Package dnf-plugins-core-4.0.21-3.el8.noarch is already installed.
 !!!!: > Dependencies resolved.
 !!!!: > Nothing to do.
 !!!!: > Complete!

**Comment by plazarch** [comment]
I used this install from issue #305 and everything is working fine now.

curl -s https://packagecloud.io/install/repositories/asbru-cm/el-test/script.rpm.sh | sudo bash
AND you have to use GTk3
curl -s https://packagecloud.io/install/repositories/asbru-cm/gtk3/script.rpm.sh | sudo bash

**Comment by gfrenoy** [comment]
As suggested in the message above, did you try to overload the environment variable to get back to one of the known distro ?

So maybe (not tested) something like:

`distro=el version=8 codename= sudo -E bash`

As time goes, it becomes more and more difficult to build binary for all the possible distro ; you might also want to contact Rocky maintainers and ask what would they need to support Ásbrú as a standard package.

**Comment by plazarch** [comment]
> As suggested in the message above, did you try to overload the environment variable to get back to one of the known distro ?
> 
> So maybe (not tested) something like:
> 
> `distro=el version=8 codename= sudo -E bash`
> 
> As time goes, it becomes more and more difficult to build binary for all the possible distro ; you might also want to contact Rocky maintainers and ask what would they need to support Ásbrú as a standard package.

As noted right above, I used the test install script and everything is working very well.
