### ISSUE TITLE
Use another combined assignment operator

### ISSUE THREAD

**Issue by elfring** [asbru-cm/asbru-cm#895]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://perldoc.perl.org/perlop#Assignment-Operators "Description for assignment operators") accordingly.

```diff
diff --git a/lib/PACMain.pm b/lib/PACMain.pm
index 5b29b61..991faed 100644
--- a/lib/PACMain.pm
+++ b/lib/PACMain.pm
@@ -4170,7 +4170,7 @@ sub _pasteNodes {
     $$self{_CFG}{'environments'}{$uuid}{'parent'} = $parent;
     $$self{_CFG}{'environments'}{$parent}{'children'}{$uuid} = 1;
     # DevNote: a pasted folder cannot be protected otherwise recursiveness will likely fail
-    $$self{_CFG}{'environments'}{$uuid}{'_protected'} = $$self{_CFG}{'environments'}{$uuid}{'_protected'} && !$$self{_CFG}{'environments'}{$uuid}{'_is_group'};
+    $$self{_CFG}{'environments'}{$uuid}{'_protected'} &&= !$$self{_CFG}{'environments'}{$uuid}{'_is_group'};
 
     # Add new node to Connections Tree
     $$self{_GUI}{treeConnections}->_addNode(
```

**Comment by gfrenoy** [comment]
Thanks for your feedback.  I made the suggested change.

> Some source code analysis tools can help to find opportunities for improving software components

Would you have suggestions of such a tool for perl ?

**Comment by elfring** [comment]
>I made the suggested change.

Thanks. ‒ Which commit will contain it?


>Would you have suggestions of such a tool for perl ?

:thought_balloon: My update suggestion was generated with the help of a Perl command which I published together with some similar source code transformation proposals.

**Comment by gfrenoy** [comment]
> Which commit will contain it?

Only on my machine for new, I did not publish the change yet.  I'll update this issue when done.

> My update suggestion was generated with the help of a Perl command

Would you have some references about how this works?  Feel also free to submit pull requests that will increase the code quality, they will of course be very welcome :)

**Comment by elfring** [comment]
:thought_balloon: Do you get any further development ideas from [similar transformation suggestions which I published for various software components](https://github.com/issues?q=is%3Aissue+author%3Aelfring+%22Increase+the+usage+of+combined+assignment+operators%22 "Proposals")?

**Comment by gfrenoy** [comment]
Many examples yes but you don't explain how you find them and how to automate or delegate this work as much as possible to reduce the workload on the core team...

**Comment by elfring** [comment]
>Many examples yes

Did you find any Perl command variants in referenced issues?


>but you don't explain how you find them

:thought_balloon: Try replacement approaches out with the help of advanced regular expressions.


>… to reduce the workload on the core team...

Thus it was just a single assignment statement found for a simple improvement in this software.
