### ISSUE TITLE
Not able to install asbru-cm on xubuntu impish 21.10

### ISSUE THREAD

**Issue by abhaysap** [asbru-cm/asbru-cm#896]
Not able to install asbru-cm on xubuntu impish 21.10

abhay@abhay-XPS-15-9510:~$ sudo curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
[sudo] password for abhay: 
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=21.10  codename=impish  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
 NOPE: Updating apt repository metadata cache ...
Failed to update via apt-get update
Hit:1 http://in.archive.ubuntu.com/ubuntu impish InRelease
Get:2 http://in.archive.ubuntu.com/ubuntu impish-updates InRelease [110 kB]
Get:3 http://in.archive.ubuntu.com/ubuntu impish-backports InRelease [101 kB]
Hit:4 http://archive.canonical.com/ubuntu impish InRelease
Get:5 http://in.archive.ubuntu.com/ubuntu impish-updates/main i386 Packages [84.7 kB]
Get:6 http://security.ubuntu.com/ubuntu impish-security InRelease [110 kB]
Get:7 http://in.archive.ubuntu.com/ubuntu impish-updates/main amd64 Packages [174 kB]
Get:8 http://in.archive.ubuntu.com/ubuntu impish-updates/main amd64 DEP-11 Metadata [18.8 kB]
Get:9 http://in.archive.ubuntu.com/ubuntu impish-updates/main DEP-11 48x48 Icons [20.9 kB]
Get:10 http://in.archive.ubuntu.com/ubuntu impish-updates/universe amd64 Packages [51.8 kB]
Get:11 http://in.archive.ubuntu.com/ubuntu impish-updates/universe i386 Packages [27.9 kB]
Get:12 http://in.archive.ubuntu.com/ubuntu impish-updates/universe amd64 DEP-11 Metadata [4,480 B]
Get:13 http://in.archive.ubuntu.com/ubuntu impish-backports/universe amd64 DEP-11 Metadata [9,288 B]
Get:14 https://dl.cloudsmith.io/public/asbru-cm/loki/deb/ubuntu impish InRelease [4,886 B]
Get:15 https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu impish InRelease [4,855 B]
Ign:16 https://packagecloud.io/asbru-cm/v5/ubuntu impish InRelease
Get:17 http://security.ubuntu.com/ubuntu impish-security/main amd64 DEP-11 Metadata [6,432 B]
Get:18 http://security.ubuntu.com/ubuntu impish-security/universe amd64 DEP-11 Metadata [2,308 B]
Get:19 https://dl.cloudsmith.io/public/asbru-cm/snapshots/deb/ubuntu impish InRelease [4,875 B]
Err:20 https://packagecloud.io/asbru-cm/v5/ubuntu impish Release
  404  Not Found [IP: 52.52.239.191 443]
Reading package lists...
W: Skipping acquire of configured file 'multiverse/source/Sources' as repository 'http://archive.canonical.com/ubuntu impish InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/binary-i386/Packages' as repository 'http://archive.canonical.com/ubuntu impish InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/binary-amd64/Packages' as repository 'http://archive.canonical.com/ubuntu impish InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/i18n/Translation-en_IN' as repository 'http://archive.canonical.com/ubuntu impish InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/i18n/Translation-en' as repository 'http://archive.canonical.com/ubuntu impish InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/dep11/Components-amd64.yml' as repository 'http://archive.canonical.com/ubuntu impish InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/dep11/icons-48x48.tar' as repository 'http://archive.canonical.com/ubuntu impish InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/dep11/icons-64x64.tar' as repository 'http://archive.canonical.com/ubuntu impish InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'multiverse/cnf/Commands-amd64' as repository 'http://archive.canonical.com/ubuntu impish InRelease' doesn't have the component 'multiverse' (component misspelt in sources.list?)
E: The repository 'https://packagecloud.io/asbru-cm/v5/ubuntu impish Release' does not have a Release file.
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact asbru-cm for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/asbru-cm/asbru-cm
 !!!!: 

sudo apt install asbru-cm
[sudo] password for abhay: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package asbru-cm
abhay@abhay-XPS-15-9510:~$ 

When will support on impish be available.

**Comment by gfrenoy** [comment]
See #861
