### ISSUE TITLE
Expect processing not working 

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#897]
**Describe the bug**
@gfrenoy   ... Opening new issue as requested ...

In a simple Expect sequence defined as follows, the step 0 is ignored/not processed:

![image](https://user-images.githubusercontent.com/37672088/143947428-bb1c5329-bc30-4d07-9c24-3b0a25bb17a7.png)

In fact from a brief test looks like that any step where  `<command prompt>` is expected is ignored.

**Expected behavior**
The expect sequence should be processed correctly.

**Environment (please complete the following information):**
 - OS: RHEL 8.4
 - Ásbrú Version Loki

**Comment by gfrenoy** [comment]
@popxunga Just gave it a try with the latest loki version and I'm still confused and don't understand what does not work properly...

What I see is that is is waiting for the command prompt RegEx that is defined in the preferences ; when found, it jumps to expect #1 that is always matching so it runs `ls -la`.

Can you give me more detail about what is not working ?

**Comment by popxunga** [comment]
Hi @gfrenoy  ...
The 1st screenshot was not the best case to illustrate the issue which is still present with latest loki build.
In fact the issue is best seen if the sudo or su command being executed asks for a password.
Try like this:
![image](https://user-images.githubusercontent.com/37672088/147407161-c8c0057e-4076-47e0-82a7-44df6d06e572.png)
Thanks a lot !

**Comment by gfrenoy** [comment]
Ah !  I think I got it ; you mean: the command (either `sudo su -` or `su - testuser` in your examples) are not executed ; only the "on match goto" part is processed but no statement is sent.  I see now, thanks for the clarifications :)

**Comment by popxunga** [comment]
Here you have the expect debug....

The last line is the testuser password which is hidden in the screenshot:

CONNECTING WITH testserver01 (Sun Dec 26 11:58:15 2021)

[asbru_conn(86495)][testserver01][testserver01]: !!_PAC_AUTH_[asbru_PID{22349}_n10]!!
[asbru_conn(86495)][testserver01][testserver01]: GET_TITLE:
[asbru_conn(86495)][testserver01][testserver01]: SPAWNING:ssh -p 22 -x -l zzzzzz  999.999.999.999
[asbru_conn(86495)][testserver01][testserver01]: SPAWNED:'ssh -p 22 -x -l zzzzzz  999.999.999.999' (PID:86495)
Starting EXPECT pattern matching...
 at /usr/share/perl5/vendor_perl/Expect.pm line 597.
	Expect::expect(Expect=GLOB(0x556596fd0ab8), 40, ARRAY(0x556599330590), ARRAY(0x556599330800), ARRAY(0x556599330c38), ARRAY(0x556599330e90), ARRAY(0x556599331d18), ARRAY(0x556599332120), ...) called at /usr/share/asbru-cm/lib/asbru_conn line 1972
spawn id(5): list of patterns:
  #2: -eof `'
  #3: -re `\\[__PAC__SUDO__PROMPT__\\]'
  #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'
  #5: -re `.*(any key to continue|tecla para continuar).*'
  #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'
  #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'
  #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@[\\w\\-\\.]+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'
  #9: -re `[#%\\$>~�\206\222]|\\:\\/\\s*$'


spawn id(5): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@[\\w\\-\\.]+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>~�\206\222]|\\:\\/\\s*$'? No.

zzzzzz@999.999.999.999's password: 
spawn id(5): Does `\rzzzzzz@999.999.999.999\'s password: '
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@[\\w\\-\\.]+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? YES!!
    Before match string: `\rzzzzzz@999.999.999.999\'s '
    Match string: `password: '
    After match string: `'
    Matchlist: (`password',  `')
Calling hook CODE(0x5565993322d0)...
Sending 'xxxxxxxxxxx\n' to spawn id(5)
 at /usr/share/perl5/vendor_perl/Expect.pm line 1421.
	Expect::print(Expect=GLOB(0x556596fd0ab8), "xxxxxxxxxxx\x{a}") called at /usr/share/asbru-cm/lib/asbru_conn line 491
	main::send_slow(Expect=GLOB(0x556596fd0ab8), "xxxxxxxxxxx\x{a}", "hide") called at /usr/share/asbru-cm/lib/asbru_conn line 1806
	main::__ANON__(Expect=GLOB(0x556596fd0ab8)) called at /usr/share/perl5/vendor_perl/Expect.pm line 825
	Expect::_multi_expect(40, ARRAY(0x556599332990), ARRAY(0x55659933c3a0)) called at /usr/share/perl5/vendor_perl/Expect.pm line 602
	Expect::expect(Expect=GLOB(0x556596fd0ab8), 40, ARRAY(0x556599330590), ARRAY(0x556599330800), ARRAY(0x556599330c38), ARRAY(0x556599330e90), ARRAY(0x556599331d18), ARRAY(0x556599332120), ...) called at /usr/share/asbru-cm/lib/asbru_conn line 1972
[asbru_conn(86495)][testserver01][testserver01]: PASSWORD:Sent (not shown)
Continuing expect, restarting timeout...

spawn id(5): Does `'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@[\\w\\-\\.]+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>~�\206\222]|\\:\\/\\s*$'? No.



spawn id(5): Does `\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@[\\w\\-\\.]+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>~�\206\222]|\\:\\/\\s*$'? No.

Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-1047-raspi armv7l)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 updates can be applied immediately.


Last login: Sun Dec 26 11:57:56 2021 from xxx.xxx.xxx.xxx

spawn id(5): Does `\r\nWelcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-1047-raspi armv7l)\r\n\r\n * Documentation:  https://help.ubuntu.com\r\n * Management:     https://landscape.canonical.com\r\n * Support:        https://ubuntu.com/advantage\r\n\r\n * Super-optimized for small spaces - read how we shrank the memory\r\n   footprint of MicroK8s to make it the smallest full K8s around.\r\n\r\n   https://ubuntu.com/blog/microk8s-memory-optimisation\r\n\r\n  Get cloud support with Ubuntu Advantage Cloud Guest:\r\n    http://www.ubuntu.com/business/services/cloud\r\n\r\n0 updates can be applied immediately.\r\n\r\n\r\nLast login: Sun Dec 26 11:57:56 2021 from xxx.xxx.xxx.xxx\r\r\n'
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@[\\w\\-\\.]+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>~�\206\222]|\\:\\/\\s*$'? No.

zzzzzz@testserver01:~$ 
spawn id(5): Does `\r\nWelcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-1047-raspi armv7l)\r\n\r\n * Documentation:  https://help.ubuntu.com\r\n * Management:     https://landscape.canonical.com\r\n * Support:        https://ubuntu.com/advantage\r\n\r\n * Super-optimized for small spaces - read how we shrank the memory\r\n   footprint of MicroK8s to make it the smallest full K8s around.\r\n\r\n   https://ubuntu.com/blog/microk8s-memory-optimisation\r\n\r\n  Get cloud support with Ubuntu Advantage Cloud Guest:\r\n    http://www.ubuntu.com/business/services/cloud\r\n\r\n0 updates can be applied immediately.\r\n\r\n\r\nLast login: Sun Dec 26 11:57:56 2021 from xxx.xxx.xxx.xxx\r\r\n\033]0;zzzzzz@testserver01: ~\007\033[01;32mzzzzzz@testserver01\033[00m:\033[01;34m~\033[00m$ '
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `\\[__PAC__SUDO__PROMPT__\\]'? No.
  pattern #4: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #5: -re `.*(any key to continue|tecla para continuar).*'? No.
  pattern #6: -re `.*ffending .*key in (.+?)\\:(\\d+).*'? No.
  pattern #7: -re `([lL]ogin|[uU]suario|([uU]ser-?)*[nN]ame.*|[uU]ser)\\s*:\\s*$'? No.
  pattern #8: -re `([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@[\\w\\-\\.]+)*|[cC]ontrase.a|Enter passphrase for key \'.+\')\\s*:\\s*$'? No.
  pattern #9: -re `[#%\\$>~�\206\222]|\\:\\/\\s*$'? YES!!
    Before match string: `\r\nWelcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-1047-raspi armv7l)\r\n\r\n * Documentation:  https://help.ubuntu.com\r\n * Management:     https://landscape.canonical.com\r\n * Support:        https://ubuntu.com/advantage\r\n\r\n * Super-optimized for small spaces - read how we shrank the memory\r\n   footprint of MicroK8s to make it the smallest full K8s around.\r\n\r\n   https://ubuntu.com/blog/microk8s-memory-optimisation\r\n\r\n  Get cloud support with Ubuntu Advantage Cloud Guest:\r\n    http://www.ubuntu.com/business/services/cloud\r\n\r\n0 updates can be applied immediately.\r\n\r\n\r\nLast login: Sun Dec 26 11:57:56 2021 from xxx.xxx.xxx.xxx\r\r\n\033]0;zzzzzz@testserver01: '
    Match string: `~'
    After match string: `\007\033[01;32mzzzzzz@testserver01\033[00m:\033[01;34m~\033[00m$ '
    Matchlist: ()
Calling hook CODE(0x556599332510)...
[asbru_conn(86495)][testserver01][testserver01]: EXPECT:WAITING:[#%\$>~→]|\:\/\s*$
Starting EXPECT pattern matching...
 at /usr/share/perl5/vendor_perl/Expect.pm line 597.
	Expect::expect(Expect=GLOB(0x556596fd0ab8), 5, ARRAY(0x55659933cc28), ARRAY(0x55659933c6d0), ARRAY(0x55659933c988), ARRAY(0x55659933cee0)) called at /usr/share/asbru-cm/lib/asbru_conn line 1929
	main::__ANON__(Expect=GLOB(0x556596fd0ab8)) called at /usr/share/perl5/vendor_perl/Expect.pm line 825
	Expect::_multi_expect(40, ARRAY(0x556599332990), ARRAY(0x55659933c3a0)) called at /usr/share/perl5/vendor_perl/Expect.pm line 602
	Expect::expect(Expect=GLOB(0x556596fd0ab8), 40, ARRAY(0x556599330590), ARRAY(0x556599330800), ARRAY(0x556599330c38), ARRAY(0x556599330e90), ARRAY(0x556599331d18), ARRAY(0x556599332120), ...) called at /usr/share/asbru-cm/lib/asbru_conn line 1972
spawn id(5): list of patterns:
  #2: -eof `'
  #3: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'
  #4: -re `[#%\\$>~�\206\222]|\\:\\/\\s*$'


spawn id(5): Does `\007\033[01;32mzzzzzz@testserver01\033[00m:\033[01;34m~\033[00m$ '
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #4: -re `[#%\\$>~�\206\222]|\\:\\/\\s*$'? YES!!
    Before match string: `\007\033[01;32mzzzzzz@testserver01\033[00m:\033[01;34m'
    Match string: `~'
    After match string: `\033[00m$ '
    Matchlist: ()
Calling hook CODE(0x55659933cdc0)...
[asbru_conn(86495)][testserver01][testserver01]: EXPECT:ON_MATCH:found pattern '[#%\$>~→]|\:\/\s*$'. Jumping to '1'
[asbru_conn(86495)][testserver01][testserver01]: EXPECT:WAITING:ssword
Starting EXPECT pattern matching...
 at /usr/share/perl5/vendor_perl/Expect.pm line 597.
	Expect::expect(Expect=GLOB(0x556596fd0ab8), 5, ARRAY(0x55659933ca48), ARRAY(0x55659933ca30), ARRAY(0x55659933c988), ARRAY(0x55659933cee0)) called at /usr/share/asbru-cm/lib/asbru_conn line 1929
	main::__ANON__(Expect=GLOB(0x556596fd0ab8)) called at /usr/share/perl5/vendor_perl/Expect.pm line 825
	Expect::_multi_expect(40, ARRAY(0x556599332990), ARRAY(0x55659933c3a0)) called at /usr/share/perl5/vendor_perl/Expect.pm line 602
	Expect::expect(Expect=GLOB(0x556596fd0ab8), 40, ARRAY(0x556599330590), ARRAY(0x556599330800), ARRAY(0x556599330c38), ARRAY(0x556599330e90), ARRAY(0x556599331d18), ARRAY(0x556599332120), ...) called at /usr/share/asbru-cm/lib/asbru_conn line 1972
spawn id(5): list of patterns:
  #2: -eof `'
  #3: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'
  #4: -re `'


spawn id(5): Does `\033[00m$ '
match:
  pattern #2: -eof `'? No.
  pattern #3: -re `^.+ontinue connecting \\(([^/]+)\\/([^/]+)(?:[^)]+)?\\)\\?\\s*$'? No.
  pattern #4: -re `'? YES!!
    Before match string: `'
    Match string: `'
    After match string: `\033[00m$ '
    Matchlist: ()
Calling hook CODE(0x55659933cdd8)...
[asbru_conn(86495)][testserver01][testserver01]: EXPECT:SENDING:<<HIDDEN STRING>>\n
Sending 'test' to spawn id(5)
 at /usr/share/perl5/vendor_perl/Expect.pm line 1421.
	Expect::print(Expect=GLOB(0x556596fd0ab8), "test") called at /usr/share/asbru-cm/lib/asbru_conn line 491
	main::send_slow(Expect=GLOB(0x556596fd0ab8), "test") called at /usr/share/asbru-cm/lib/asbru_conn line 1960
	main::__ANON__(Expect=GLOB(0x556596fd0ab8)) called at /usr/share/perl5/vendor_perl/Expect.pm line 825
	Expect::_multi_expect(40, ARRAY(0x556599332990), ARRAY(0x55659933c3a0)) called at /usr/share/perl5/vendor_perl/Expect.pm line 602
	Expect::expect(Expect=GLOB(0x556596fd0ab8), 40, ARRAY(0x556599330590), ARRAY(0x556599330800), ARRAY(0x556599330c38), ARRAY(0x556599330e90), ARRAY(0x556599331d18), ARRAY(0x556599332120), ...) called at /usr/share/asbru-cm/lib/asbru_conn line 1972
Sending '\n' to spawn id(5)
 at /usr/share/perl5/vendor_perl/Expect.pm line 1421.
	Expect::print(Expect=GLOB(0x556596fd0ab8), "\x{a}") called at /usr/share/asbru-cm/lib/asbru_conn line 491
	main::send_slow(Expect=GLOB(0x556596fd0ab8), "\x{a}") called at /usr/share/asbru-cm/lib/asbru_conn line 1961
	main::__ANON__(Expect=GLOB(0x556596fd0ab8)) called at /usr/share/perl5/vendor_perl/Expect.pm line 825
	Expect::_multi_expect(40, ARRAY(0x556599332990), ARRAY(0x55659933c3a0)) called at /usr/share/perl5/vendor_perl/Expect.pm line 602
	Expect::expect(Expect=GLOB(0x556596fd0ab8), 40, ARRAY(0x556599330590), ARRAY(0x556599330800), ARRAY(0x556599330c38), ARRAY(0x556599330e90), ARRAY(0x556599331d18), ARRAY(0x556599332120), ...) called at /usr/share/asbru-cm/lib/asbru_conn line 1972
[asbru_conn(86495)][testserver01][testserver01]: TITLE:testserver01
[asbru_conn(86495)][testserver01][testserver01]: CONNECTED
test

**Comment by gfrenoy** [comment]
According to what I see in the code, the command is always skipped if "On match / goto" is selected.

I made the change to execute the command even if "on match / goto" is selected.

Let me know if this helps.

**Comment by popxunga** [comment]
I should say that I use this feature since it exists and it worked fine as far as I can remember.
So it looks a bit strange that such type of bug was there all the time. 
I will test as soon the el8 loki build is available.

**Comment by gfrenoy** [comment]
> such type of bug was there all the time.

No it was not there all the time ; sorry, I think it has been introduced here https://github.com/asbru-cm/asbru-cm/commit/bb92cd2f0a229e45ae6eb79b102c592a9be42a3e

> I will test as soon the el8 loki build is available.

Thanks a lot :)

**Comment by popxunga** [comment]
> > such type of bug was there all the time.
> 
> No it was not there all the time ; sorry, I think it has been introduced here [bb92cd2](https://github.com/asbru-cm/asbru-cm/commit/bb92cd2f0a229e45ae6eb79b102c592a9be42a3e)
Ah ... that's better ;-)

> 
> > I will test as soon the el8 loki build is available.
Just briefly tested it ... and it works :-)

> Thanks a lot :)
You're welcome ! Thank you too !

**Comment by popxunga** [comment]
@gfrenoy ... just did some additional tests and all looks good.
Closing...
