### ISSUE TITLE
Issue with "expect" : 'Quantifier follows nothing'

### ISSUE THREAD

**Issue by deelerke** [asbru-cm/asbru-cm#898]
I have an issue with "expect" , this was working fine in version 6.3 but broke in 6.4
I'm on Debian Sid 5.15.0-2-amd64

The connection is SSH to a Cisco switch, and I want to automate the 'enable' command.
As a first step in expect, I  entered *>
when matched it sends 'enable' and the password
But now it throws this error:

`Quantifier follows nothing in regex; marked by <-- HERE in m/* <-- HERE >()/ at /usr/share/perl5/Expect.pm line 710.`

![image](https://user-images.githubusercontent.com/6661131/144748174-94835200-2928-476c-b699-8069ae1697f8.png)

**Comment by hanspr** [comment]
If you are trying to match an '*>' you should write '\*'

If you are trying to match anything before '>' you should write '.*>' 

But '*>' is an incorrect regex expression, even if it worked before.

**Comment by deelerke** [comment]
thanks for your response
I tried .*> and now it waits and eventually times out

![image](https://user-images.githubusercontent.com/6661131/144760678-ed0c2a48-e8eb-4563-bf92-251c11162c15.png)

**Comment by hanspr** [comment]
Does your expect has a space at the end? something like `.*>(space)`

The expression `.*>` without any space at after the greater than sign should work.

If it does not work, you may have to degbug the login process that requires to activate the Expect Debug

![imagen](https://user-images.githubusercontent.com/1572396/144761748-606e4c72-21b2-4a97-9201-27750be82450.png)

If you do and upload the messages just **make sure you remove any sensitive data from the print out.**

**Comment by hanspr** [comment]
The other thing I  would try is:

First expect : blank (nothing to expect), most likely asbru already detected the prompt before you, and now you just execute `enable`

I do not know what would enable do, but must likely it will lead to a new prompt.

So on the second expect add the new prompt to expect : `.*>`, so it waits for this second prompt before doing what ever the global variable will print out.

**Comment by deelerke** [comment]
great !  
![image](https://user-images.githubusercontent.com/6661131/144763028-da47f6c0-3949-40da-828c-54a4c36a40c0.png)
that works!
no idea why though... there is no '>' in previous text during login
I'll try that expect debug option to find out.
thanks!!
