### ISSUE TITLE
Missing dependency in .deb package

### ISSUE THREAD

**Issue by nomike** [asbru-cm/asbru-cm#90]
I'm setting up Ubuntu 18.04 with the new "Windows Subsystem for Windows" feature.
I'v installed an X11 server and installed asbru-cm as per instructions.

When I tried to start it I got the following output on the shell:
```
 Fri 15 Jun - 13:29 > ~/.config/pac >
 @micpos > /opt/asbru/asbru-cm
Ásbrú started (asbru-cm) with PID 18006
INFO: Used config file '/home/micpos/.config/pac/pac.yml'
INFO: Ásbrú already running
INFO: No more instances allowed!

(asbru-cm:18006): Unique-DBus-WARNING **: 13:29:49.523: Unable to open a connection to the session bus: D-Bus library appears to be incorrectly set up: see the manual page for dbus-uuidgen to correct this issue. (Failed to open "/var/lib/dbus/machine-id": No such file or directory; UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text)

(asbru-cm:18006): Unique-DBus-WARNING **: 13:29:49.545: Unable to connect to the running instance, aborting.
Ásbrú not started. Is Ásbrú already running?
```

I then went forward and did
`sudo apt install ubuntu-desktop`

and now asbru-cm starts. There seems to be some dependency missing in the debian package.

**Comment by gfrenoy** [comment]
```ubuntu-desktop``` is a meta-package (see [here](https://packages.ubuntu.com/bionic/ubuntu-desktop)), any more accurate idea of the package that would be needed ?

**Comment by commodus-sebastien** [comment]
Hello,

I encountered the same issue. 
I installed the dbus-x11 package and it solved the problem on my side.

Hope this helps

**Comment by gfrenoy** [comment]
Now available in the latest release.
