### ISSUE TITLE
AUR-> app settings are not saved | AppImage -> app won't start

### ISSUE THREAD

**Issue by David-Nahorniak** [asbru-cm/asbru-cm#900]
**Describe the bug**
1. When I make any change (in settings, adding a connection, etc.) that requires any kind of save, nothing happens.
Log:
`
(asbru-cm:89101): Gtk-WARNING **: 18:10:32.628: Theme parsing error: gtk-dark.css:5822:26: '-shadow' is not a valid color name

(asbru-cm:89101): Gtk-WARNING **: 18:10:32.628: Theme parsing error: gtk-dark.css:5825:14: not a number

(asbru-cm:89101): Gtk-WARNING **: 18:10:32.628: Theme parsing error: gtk-dark.css:5826:13: not a number

(asbru-cm:89101): Gtk-WARNING **: 18:10:32.628: Theme parsing error: gtk-dark.css:5827:11: Expected a length
INFO: Ásbrú Connection Manager 6.3.2 (asbru-cm) started with PID 89101
INFO: Language detected : cs_CZ.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : other
INFO: Config directory is '/home/user/.config/asbru'
WARN: No configuration file found in '/home/user/.config/asbru', creating a new one...
INFO: Virtual terminal emulator (VTE) version is 0.66
GLib-GObject-WARNING **: invalid (NULL) pointer instance at /opt/asbru/lib/PACMain.pm line 4910.
GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed at /opt/asbru/lib/PACMain.pm line 4910.
INFO: Theme directory is '/opt/asbru/res/themes/default'
INFO: Using Gnome tray icon
WARN: Adding new keybinding [Ctrl+d] for [Connections Tree]/[Clone connection]...
.....
WARN: Adding new keybinding [Ctrl+Page_Up] for [Tabs]/[Previous Tab]...
Use of uninitialized value $parent_uuid in hash element at /opt/asbru/lib/PACMain.pm line 2761.
WARNING: The key derivation method "opensslv1" is deprecated. Using -pbkdf=>'pbkdf2' would be better.
Pass -nodeprecate=>1 to inhibit this message.
at /opt/asbru/lib/PACUtils.pm line 2718.
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /opt/asbru/lib/PACUtils.pm line 2718.
***  ignoring at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67.
`

2. AppImage will not launch at all.

**To Reproduce**
1. Opening the application
2. Open preferences
3. Any change (like icons theme)
4. Clicking save and close
5. After clicking nothing happens, the window stays open, the next time you run it the change is not applied

**Expected behavior**
I would expect that when the save button is clicked, the action will be saved and the next time the application is open, the change will be reloaded.
I would expect the app to launch when I click on AppImage.

**Environment (please complete the following information):**
 - OS: Arch -> Garuda linux -> ZEN SMP PREEMPT Thu, 02 Dec 2021 15:47:07 +0000
 - Ásbrú Version 6.3.2 (aur/asbru-cm)

**Additional context**
First experience with Ásbrú Connection Manager.

**Comment by David-Nahorniak** [comment]
Problem with installation from AUR solved:
I installed the **asbru-cm-loki-git** package
https://aur.archlinux.org/packages/asbru-cm-loki-git/

The problem with AppImage persists.

**Comment by gfrenoy** [comment]
Please check #804 to contribute to the AppImage issue.
