### ISSUE TITLE
Won't install on Linux mint 20.2

### ISSUE THREAD

**Issue by begemoti** [asbru-cm/asbru-cm#903]
Trying to install on Mint 20.2 but no success.

dz@dz-PC:~$ curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash
Detected operating system as LinuxMint/uma.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/asbru-cm_asbru-cm.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.

dz@dz-PC:~$ sudo apt install asbru-cm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package asbru-cm

**Comment by madmogie** [comment]
Same issue/same output.  Long time Asbru user on Linux Mint.  Built a new VM on Mint 20.2 and cannot install.  To test, also built a new Ubuntu 21.10 VM and having the same problem.  Kinda makes sense as Mint is based off Ubuntu.  The problem is bigger than Mint 20.2.

mogie@ubuntu:~$ sudo apt install asbru-cm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package asbru-cm

**Comment by gfrenoy** [comment]
Mint Uma is not yet built but I can add it easily and see if we suffer from the same issue.

Stay tuned :)

**Comment by gfrenoy** [comment]
Ásbrú is now built for Mint Uma in our "snapshots" repository and will be made available on the main repository for the next release.

Feel free to re-open if you should have any issue with this.

**Comment by madmogie** [comment]
Works with the snapshot repository now.  Thanks gfrenoy!

**Comment by guilhem-lk** [comment]
Hello, I tried the loki repository but still cannot find package asbru-cm :(

`curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/loki/cfg/setup/bash.deb.sh' | sudo -E bash
sudo apt install asbru-cm`

Did I miss something?

**Comment by dcheslow** [comment]
I am still seeing this behaviour in Linux Mint 20.3.

`$ cat /etc/issue
Linux Mint 20.3 Una \n \l

$ curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=linuxmint  version=20.3  codename=una  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

$ sudo apt install asbru-cm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package asbru-cm
`

**Comment by hanqingwu** [comment]
the same problem 
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=linuxmint  version=20.3  codename=una  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
 NOPE: Updating apt repository metadata cache ...
Failed to update via apt-get update
命中:1 http://ftp.sjtu.edu.cn/ubuntu focal InRelease
命中:2 http://ftp.sjtu.edu.cn/ubuntu focal-updates InRelease
命中:3 http://ftp.sjtu.edu.cn/ubuntu focal-backports InRelease
忽略:4 https://mirrors.bfsu.edu.cn/linuxmint una InRelease
命中:5 https://mirrors.bfsu.edu.cn/linuxmint una Release
命中:6 http://security.ubuntu.com/ubuntu focal-security InRelease
命中:7 http://archive.canonical.com/ubuntu focal InRelease
忽略:8 https://deepin-wine.i-m.dev  InRelease
忽略:9 https://packagecloud.io/asbru-cm/v5/linuxmint una InRelease
命中:10 https://deepin-wine.i-m.dev  Release
获取:11 https://dl.cloudsmith.io/public/asbru-cm/loki/deb/linuxmint una InRelease [4,973 B]
忽略:13 https://deepin-wine.i-m.dev  Release.gpg
获取:14 https://dl.cloudsmith.io/public/asbru-cm/release/deb/linuxmint una InRelease [4,849 B]
错误:15 https://packagecloud.io/asbru-cm/v5/linuxmint una Release
  404  Not Found [IP: 50.18.207.89 443]
正在读取软件包列表...
E: 仓库 “https://packagecloud.io/asbru-cm/v5/linuxmint una Release” 没有 Release 文件。
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact asbru-cm for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/asbru-cm/asbru-cm
 !!!!:

**Comment by hanqingwu** [comment]
try this script:

curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash
sudo apt-get install asbru-cm
