### ISSUE TITLE
Asbru-CM not available on Fedora 35

### ISSUE THREAD

**Issue by mmneimne** [asbru-cm/asbru-cm#907]
**Describe the bug**
After running the installation scripts, I get the below:
Last metadata expiration check: 0:01:21 ago on Wed 12 Jan 2022 03:29:29 AM EST.
No match for argument: asbru-cm
Error: Unable to find a match: asbru-cm

**Environment (please complete the following information):**
 - OS: Fedora 35

**Comment by swamig007** [comment]
I got it to install not sure if this method is clean, but workaround for now . 

I altered the repo file in /etc/yum.repos.d/asbru-cm-release.repo and changed the version from 35 to 33 and 
I am able to install and run asbru-cm ... 


```
[asbru-cm-release]
name=asbru-cm-release
baseurl=https://dl.cloudsmith.io/public/asbru-cm/release/rpm/fedora/33/$basearch
repo_gpgcheck=1
enabled=1
gpgkey=https://dl.cloudsmith.io/public/asbru-cm/release/gpg.7684B0670B1C65E8.key
gpgcheck=1
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
pkg_gpgcheck=1
autorefresh=1
type=rpm-md

[asbru-cm-release-noarch]
name=asbru-cm-release-noarch
baseurl=https://dl.cloudsmith.io/public/asbru-cm/release/rpm/fedora/33/noarch
repo_gpgcheck=1
enabled=1
gpgkey=https://dl.cloudsmith.io/public/asbru-cm/release/gpg.7684B0670B1C65E8.key
gpgcheck=1
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
pkg_gpgcheck=1
autorefresh=1
type=rpm-md

[asbru-cm-release-source]
name=asbru-cm-release-source
baseurl=https://dl.cloudsmith.io/public/asbru-cm/release/rpm/fedora/33/SRPMS
repo_gpgcheck=1
enabled=1
gpgkey=https://dl.cloudsmith.io/public/asbru-cm/release/gpg.7684B0670B1C65E8.key
gpgcheck=1
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
pkg_gpgcheck=1
autorefresh=1
type=rpm-md
```

**Comment by mmneimne** [comment]
> I got it to install not sure if this method is clean, but workaround for now .
> 
> I altered the repo file in /etc/yum.repos.d/asbru-cm-release.repo and changed the version from 35 to 33 and I am able to install and run asbru-cm ...
> 
> ```
> [asbru-cm-release]
> name=asbru-cm-release
> baseurl=https://dl.cloudsmith.io/public/asbru-cm/release/rpm/fedora/33/$basearch
> repo_gpgcheck=1
> enabled=1
> gpgkey=https://dl.cloudsmith.io/public/asbru-cm/release/gpg.7684B0670B1C65E8.key
> gpgcheck=1
> sslverify=1
> sslcacert=/etc/pki/tls/certs/ca-bundle.crt
> metadata_expire=300
> pkg_gpgcheck=1
> autorefresh=1
> type=rpm-md
> 
> [asbru-cm-release-noarch]
> name=asbru-cm-release-noarch
> baseurl=https://dl.cloudsmith.io/public/asbru-cm/release/rpm/fedora/33/noarch
> repo_gpgcheck=1
> enabled=1
> gpgkey=https://dl.cloudsmith.io/public/asbru-cm/release/gpg.7684B0670B1C65E8.key
> gpgcheck=1
> sslverify=1
> sslcacert=/etc/pki/tls/certs/ca-bundle.crt
> metadata_expire=300
> pkg_gpgcheck=1
> autorefresh=1
> type=rpm-md
> 
> [asbru-cm-release-source]
> name=asbru-cm-release-source
> baseurl=https://dl.cloudsmith.io/public/asbru-cm/release/rpm/fedora/33/SRPMS
> repo_gpgcheck=1
> enabled=1
> gpgkey=https://dl.cloudsmith.io/public/asbru-cm/release/gpg.7684B0670B1C65E8.key
> gpgcheck=1
> sslverify=1
> sslcacert=/etc/pki/tls/certs/ca-bundle.crt
> metadata_expire=300
> pkg_gpgcheck=1
> autorefresh=1
> type=rpm-md
> ```

yep, I tried this as well. Got it to work, but looking for a clean solution as you said.

**Comment by gfrenoy** [comment]
A cleaner solution is to force the 

`curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.rpm.sh' | version=33 sudo -E bash`

or if you want to use the latest snapshot:

`curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/snapshots/cfg/setup/bash.rpm.sh' | version=34 sudo -E bash`

And i'll add F35 to the build to you'll have it soon automatically for the snapshots and loki.
