### ISSUE TITLE
SSH terminals partly freezing

### ISSUE THREAD

**Issue by akemper** [asbru-cm/asbru-cm#908]
Hi,

after some period of inactivity (< 1h) terminals to remote servers partly freeze, i. e. if a command like 'ls' produces multiple lines of output only the first few lines are shown. Subsequently no further interaction is possible until reconnecting to the server. Since I never observed this behavior with Ubuntu's default SSH client, I guess it is related to some timeout settings in Asbru-cm and / or even a bug?
Thanks for pointing me to possible solutions for this.

Andreas

**Comment by popxunga** [comment]
Usually the timeout's are set on the servers side and/or firewalls between your machine and the servers you're working with.
You may try add these options on your terminal definitions:
![image](https://user-images.githubusercontent.com/37672088/151033550-7d534e2b-963d-4d1d-8903-87aed9b2ade1.png)

**Comment by akemper** [comment]
Thanks a lot. This seems to have fixed the issue, while I must omit I didn't see the advanced options there yet.

**Comment by popxunga** [comment]
Try with loki build ...
