### ISSUE TITLE
Connection " is of type ", which is not supported....

### ISSUE THREAD

**Issue by lghamie** [asbru-cm/asbru-cm#91]
I'm getting this error when trying to edit a connection.

Happens with all connections.

![image](https://user-images.githubusercontent.com/2054883/41728343-fdc1c5b0-754c-11e8-9114-701d8abd8d1b.png)

**Comment by gfrenoy** [comment]
Inside quotes you should have the name of the connection and the method type.  As in both cases, it displays an empty string, I would suspect it cannot read you configuration file properly.

Did you try to backup your configuration directory ```.config/pac``` and then restart from a clean configuration ?

**Comment by lghamie** [comment]
Yes.
I've tried re-installing. It works for some time, but it breaks before one day of use.

Something important, I'm running ubuntu 18.04, which doesn't seem to be supported. I was seeing the same behaviour with PAC, and that's why I've switched. The same problem has been reported in their forum two years ago and doens't seem to have been solved.

This is the error that I'm getting:
``
Ásbrú started (asbru-cm) with PID 32390
INFO: Used config file '/home/lucas/.config/pac/pac.nfreeze'
INFO: Using 'standard Gnome2' tray icon
Use of uninitialized value in numeric eq (==) at /opt/asbru/lib/PACEdit.pm line 641.
Use of uninitialized value in numeric eq (==) at /opt/asbru/lib/PACEdit.pm line 642.
Use of uninitialized value in numeric eq (==) at /opt/asbru/lib/PACEdit.pm line 643.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 645.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 645.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 647.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 647.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 648.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 648.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 658.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 658.
Use of uninitialized value in string ne at /opt/asbru/lib/PACEdit.pm line 661.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 664.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 664.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 665.
Use of uninitialized value in subroutine entry at /opt/asbru/lib/PACEdit.pm line 666.
Use of uninitialized value in hash element at /opt/asbru/lib/PACEdit.pm line 669.
Use of uninitialized value in string eq at /opt/asbru/lib/PACUtils.pm line 382.
Use of uninitialized value in string eq at /opt/asbru/lib/PACUtils.pm line 392.
Use of uninitialized value in string eq at /opt/asbru/lib/PACUtils.pm line 395.
Use of uninitialized value $cmd_line in split at /opt/asbru/lib/method/PACMethod_rdesktop.pm line 182.
Use of uninitialized value in concatenation (.) or string at /opt/asbru/lib/PACEdit.pm line 670.
Use of uninitialized value in concatenation (.) or string at /opt/asbru/lib/PACEdit.pm line 671.
Use of uninitialized value in concatenation (.) or string at /opt/asbru/lib/PACEdit.pm line 682.
Use of uninitialized value in substitution (s///) at /opt/asbru/lib/edit/PACMethod.pm line 144.
Use of uninitialized value in concatenation (.) or string at /opt/asbru/lib/edit/PACMethod.pm line 147.
Use of uninitialized value in concatenation (.) or string at /opt/asbru/lib/edit/PACMethod.pm line 147.
Use of uninitialized value in string eq at /opt/asbru/lib/PACUtils.pm line 382.
Use of uninitialized value in string eq at /opt/asbru/lib/PACUtils.pm line 392.
Use of uninitialized value in string eq at /opt/asbru/lib/PACUtils.pm line 395.
Use of uninitialized value in string eq at /opt/asbru/lib/PACEdit.pm line 730.
Use of uninitialized value in string eq at /opt/asbru/lib/PACEdit.pm line 731.
Use of uninitialized value in string eq at /opt/asbru/lib/PACEdit.pm line 732.
Use of uninitialized value in concatenation (.) or string at /opt/asbru/lib/PACEdit.pm line 141.
``

**Comment by gfrenoy** [comment]
Luca, the log confirms your configuration file is somehow corrupted.

If it works when you remove the configuration directory ; we need to understand how it get corrupted.

If there is no sensible information in it, can you share what you see in ```.config/pac``` when it does not work ?  Especially ```.config/pac/pac.yml``` ?

About 18.04, I don't use it on a daily basis but it should work fine...Can someone who is using Ásbrú on Ubuntu 18.04 can confirm this (or not) ?

**Comment by lghamie** [comment]
This happened to me with 17.10 aswell, so I don't think its 18.04 related. 

I'll try to review the pac.yml file to check for sensible information in it, but mine is 4000 lines long. If you ask me, I'm inclining myself in the permissions direction, but it sounds strange still.

Thanks!

**Comment by gfrenoy** [comment]
There is definitely an issue here but I'm unable to reproduce the problem and consequently unable to suggest a fix.

A few more questions/remarks to try to understand it better:

- Ok not specific to 18.04
- My pac.yml is also ~4000 lines long and I never encounter this kind of issue so I don't think it's a matter of file length.  Nevertheless, did you encounter the same kind of issue with a "default" installation without any specific configuration ?
- Is your file "corrupted" when it happens ?  I mean: do you just need to stop Ásbrú and restart it ?  Or do you need to restore the configuration from a backup ?
- Do you have "auto-save" enabled ?  Did you try with our without it ?
- You mentionned you had the same issue with PAC.  Did you report the issue ?  Any reference to a past discussion about it ?

And any other information would be helpful...

**Comment by gfrenoy** [comment]
Thanks for the additional information.  I don't use clusters so that might indeed be a good hint...  I'll give it a try (after I back up my config, he he).

Could you try a while with auto-save disabled ?  I would suspect a problem when saving your file, that would reduce the probabilty to encounter the failure, for sure...

Last question : when your pac.yml file is corrupted ; how does it look ?  Very different from the good one ?  Can you share a diff of both files ?

**Comment by lghamie** [comment]
I've disabled auto-save.
Then tried re-importing but it it didn't work like it has worked previously.

**Comment by gfrenoy** [comment]
> Then tried re-importing but it didn't work like it has worked previously.

What do you mean ?  The configuration did not reload properly ?  Or you got the exact same behaviour ?

> Any way of showing extra debug info?

No.

It's possible to use a debugger with [Eclipse](https://www.eclipse.org/) and [EPIC](http://www.epic-ide.org/).  I got some notes to setup that environment, I can share them if you would like.
