### ISSUE TITLE
When copy content from termial whitespace changed to tab

### ISSUE THREAD

**Issue by ltwell** [asbru-cm/asbru-cm#910]
**Describe the bug**
When copy content from termial whitespace changed to tab

**To Reproduce**
1.use sqlplus connect to oracle database
2.use set autot trace to produce execution plan
3.copy the plan content to vscode
4.when done,whitespace changed to tab
**Expected behavior**

**Screenshots**
Copy from konsole
![image](https://user-images.githubusercontent.com/3428309/151316919-614b0805-6472-4994-b9c4-e47fa897c704.png)
copy from asbru-cm
![image](https://user-images.githubusercontent.com/3428309/151317012-5e5df7c9-0d9a-4450-9756-f381e1c76ce6.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 21.10
 - Ásbrú Version [loki]

**Additional context**

**Comment by gfrenoy** [comment]
Interesting :)  Do you have this kind of behavior with something else than Oracle sqlplus ?
