### ISSUE TITLE
Support for Linux Mint 20.3 "Una"

### ISSUE THREAD

**Issue by ArneNachlass** [asbru-cm/asbru-cm#911]
**Describe the bug**
Fail to install Asbru on fresh Linux Mint 20.3 "Una" -> E: Package asbru-cm cannot be found.

**To Reproduce**
Follow the installation guide
sudo apt-add-repository multiverse
sudo apt install curl
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
sudo apt install asbru-cm

**Expected behavior**
Installation should start after "sudo apt install asbru-cm"

**Screenshots**
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket asbru-cm kann nicht gefunden werden.

Package lists are read... Ready
Dependency tree is built.       
Status information is read.... Done
E: Package asbru-cm cannot be found.

**Environment (please complete the following information):**
Linux Mint 20.3 "Una"

**Comment by gfrenoy** [comment]
Una will be supported in the next release (6.3.3).

In the meantime, did you try the "snapshots" repository ?

`curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/snapshots/cfg/setup/bash.deb.sh' | sudo -E bash`

**Comment by ArneNachlass** [comment]
great, thank you!

Encrypt your communication

**Comment by varunmaster** [comment]
Was having the same issue with my Linux Mint Una release. Spent such a long time trying to fix it but the work-around works! 

Thank you for a great tool!
