### ISSUE TITLE
sftp via jumphost to target with private key instead of password doesn't work

### ISSUE THREAD

**Issue by akemper** [asbru-cm/asbru-cm#913]
I'm trying to set-up sftp connections to different target hosts in our lab environment via a common jumphost. On the command line this works with e. g. `sftp -J jump@192.168.1.1 -i keyfile target@10.10.10.1`

I put the settings for the target host with authentication by private key and leaving the passphrase field empty in the connection details, plus complete jumphost credentials in the network settings. Triggering the connection it successfully connects to the jumphost with the stored password, but subsequently a dialog pops up asking for a password of the target host.

Looking at the temporary configuration file from getting the command line, everything including "IdentityFile ..." is in there, thus I don't understand why it still asks me for a password of the target host. Any suggestions how to fix this?

Thanks
Andreas

**Comment by gfrenoy** [comment]
Thanks for reporting the issue Andreas, I believe I fixed this on the `master` and `loki` branches.  The change will be available in a few minutes in our "snapshots" and "loki" repositories.

Let us know if this also fixes the issue for you.

**Comment by akemper** [comment]
Thanks a lot for the quick support. Works like a charm for the 6.4.0 version from Loki branch.
