### ISSUE TITLE
UI freezes after a while

### ISSUE THREAD

**Issue by nebojsac** [asbru-cm/asbru-cm#915]
I start asbru-cm via commandline (or through shortcut) and it runs ok for a while. After that the UI freezes but the connections are still active. For example I can open up settings windows but can't see changes in the open tabs. I can click the X to close a specific tab if I know where it is but the UI does not update

EDIT: looks like it happens when I switch between workspaces.

The only thing I have to go on here is this error in the console:

```
(asbru-cm:30348): GLib-GIO-WARNING **: 11:40:02.353: Your application did not unregister from D-Bus before destruction. Consider using g_application_run().
```

**Environment (please complete the following information):**
 - OS: Ubuntu 21.04
 - Ásbrú Version v6.3.2

**Comment by nebojsac** [comment]
@jsarola 
Switch to Xorg Ubuntu (instead of Wayland) and the issue goes away, at least it did for me.
I used these instructions: https://www.maketecheasier.com/switch-xorg-wayland-ubuntu1710/

**Comment by gfrenoy** [comment]
So maybe an issue related to Wayland but more information will be required to troubleshoot this further...

**Comment by Kupuyc** [comment]
I have same issue - terminal freezes after switch of workspace. It works (htop shows all fine, for example) but not possible to type.

**Environment**:

- OS: Ubuntu 22.04
- Ásbrú: v6.3.2-1
- `echo $XDG_SESSION_TYPE` shows `x11`

**Comment by gfrenoy** [comment]
@Kupuyc thanks for the info.  Does this happen systematically, very often or very exceptionnally ?

Don't you see a popup somewhere else (on another workspace or something), that would explain the behaviour...

**Comment by jsarola** [comment]
> @jsarola Switch to Xorg Ubuntu (instead of Wayland) and the issue goes away, at least it did for me. I used these instructions: https://www.maketecheasier.com/switch-xorg-wayland-ubuntu1710/

After changing to xorg, asbru-cm doesn't freeze (10 days testing the app). Today I update asbru-cm (from repo) to 6.3.3, and it works.

**Environment:**
- OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
- Ásbrú : 
INFO: Ásbrú Connection Manager 6.3.3 (asbru-cm) started with PID 18145
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : gnome-shell:ubuntu-xorg
INFO: Virtual terminal emulator (VTE) version is 0.68

**Comment by gfrenoy** [comment]
Let's close this if the problem could be workarounded.
