### ISSUE TITLE
Pop!_OS 21.10 support

### ISSUE THREAD

**Issue by guytrance** [asbru-cm/asbru-cm#916]
Hi There,

I think i tried every trick i could find to install asbru-cm on the latest Pop! distro (21.10 impish) 

I cant seem to do it, can you add support for this distro?

I followed the workaround on [#789](https://github.com/asbru-cm/asbru-cm/issues/789) issue, i only managed to make the curl command go through but "sudo apt-get install asbru-cm" gives me this:

> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> E: Unable to locate package asbru-cm
>

**Comment by xattack** [comment]
According to #852 you can use snapshots to solve this issue 

  Hope it can help you

cheers !

**Comment by imakiro** [comment]
I tested both the snapshot option, as well as the distro overide, none seem to work.

**Comment by gfrenoy** [comment]
The tag for this distro is not available on cloudsmith ; I asked them to add it.  Waiting for their answer.

**Comment by gfrenoy** [comment]
Cloudsmith does now support Pop!OS 21.10 (and 22.04, btw).  The package is now available on the `loki` and `snapshots` repositories.
