### ISSUE TITLE
Make it possible to close the Info tab

### ISSUE THREAD

**Issue by landstander668** [asbru-cm/asbru-cm#92]
Assuming that I haven't overlooked something, it doesn't currently appear to be possible to close the Info tab. While it's not all *that* intrusive, I'd love to be able to to make the beastie disappear.

**Comment by gfrenoy** [comment]
Well, why not...?

A few questions to make super the requirement is correctly defined:

- Where would you put this option ?
- How would you revert it ?
- Think about #86 and #89 : if you have both options enabled, I do fear we would be stuck without the bottom buttons and info tab.

And this looks like a good idea for the one(s) who would want to start collaborating to the code :)  I'll start a new label to mark them clearly.
