### ISSUE TITLE
no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

### ISSUE THREAD

**Issue by openkasnet** [asbru-cm/asbru-cm#920]
Hello, I can't connect to a server using the old protocol

CONNECTING WITH  (Mon Mar 14 16:29:08 2022)
Unable to negotiate with xx.xx.xx.xx port 22: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DISCONNECTED (PRESS <ENTER> TO RECONNECT) (Mon Mar 14 16:29:08 2022)

Asbru ver. v6.3.3
OS: Arch Linux 
Kernel: x86_64 Linux 5.16.14-arch1-1

Thanks.

**Comment by openkasnet** [comment]
close the request 

Added the config to /etc/ssh/ssh_config

Host *
   Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc
    KexAlgorithms +diffie-hellman-group1-sha1
    HostKeyAlgorithms=+ssh-dss


thanks to the developers for the program

**Comment by vgrosdoy** [comment]
I have the same issue (ASBRU version 6.4.1)
I added following lines in /etc/ssh/ssh_config
`
Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc
HostkeyAlgorithms +ssh-dss,ssh-rsa,rsa-sha2-512,rsa-sha2-256
KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
`
ssh works fine from the terminal but not from ASBRU
I have the following error message
`
Gtk-Message: 11:45:19.427: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
readline() on closed filehandle SSHC at /snap/asbru/26/bin/lib/asbru_conn line 773.
Unable to negotiate with 10.22.22.1 port 22: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha
`
