### ISSUE TITLE
Settings do not persist across process restarts

### ISSUE THREAD

**Issue by mindsolve** [asbru-cm/asbru-cm#921]
**Describe the bug**
All changes/settings are lost when restarting asbru-cm.
In my case, this is observable directly after installation and replicable every time (I have not yet got it working in any way).

**To Reproduce**
1. Install asbru-cm on a fresh system (or delete configuration folder `~/.config/asbru`)
2. Create new connection
3. Exit asbru-cm
4. Restart computer (as asbru continues running in the background)
5. Observe lost settings in asbru-cm

**Expected behavior**
I expect settings made to persist, unless I manually reset them.

**Screenshots**
*None*

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 x64 (German locale)
 - Ásbrú Version `v6.3.3` (from `hirsuite` deb repo, according to workaround in issue 861)

**Additional context**
Log file with parameter `--verbose`: [asbru.log](https://github.com/asbru-cm/asbru-cm/files/8306196/asbru.log)

**Comment by gfrenoy** [comment]
See #831 and #816.
