### ISSUE TITLE
Settings password set if dialogs canceled

### ISSUE THREAD

**Issue by mindsolve** [asbru-cm/asbru-cm#922]
**Describe the bug**
If the dialogs after checking `Protect with password` are canceled, an unknown password is set, locking out the user from all password protected functions.

**To Reproduce**
1. Open `Preferences`
2. Click on `Protect with password`
3. Close both dialogs with `Cancel`
4. Observe the unknown & unchangeable set password

**Expected behavior**
I expect the `Cancel` buttons in the dialogs to cancel the password setting activity, not set an unknown password.

**Screenshots**
*I don't think screenshots are necessary, as the issue can't be well documented with screenshots*

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 x64 (German locale)
 - Ásbrú Version `v6.3.3` (from `hirsuite` deb repo, according to workaround in issue #861)

**Additional context**

**Comment by gfrenoy** [comment]
Very good point !  Thanks a lot for reporting :)

It's a regression ... It has apparently been introduced here --> ff459d599a92c7a9404255dcfc4ab8b9e6e04869

I'll submit a fix soon, it should be available in the snapshot and loki build in a couple of hours.

Let us know if

**Comment by mindsolve** [comment]
Can confirm this to be fixed (`6.3.3~1649529787-1`) - thanks a lot :) :tada:
