### ISSUE TITLE
ssh to a previously unknown host hangs at "are you sure you want to continue connecting"?

### ISSUE THREAD

**Issue by Kurgan-** [asbru-cm/asbru-cm#923]
Running Asbru 6.3.2 on Linux Mint 20.3 "Una".

I have found that when I set up a connection to a new remote host, I cannot go past the 
`Are you sure you want to continue connecting (yes/no/[fingerprint])? yes/no`
question.

I type "yes" and press enter, and the connection window stalls. After some seconds it times out and disconnects.

To work around this issue I have to ssh to the new host in a console (out of Asbru CM), answer "yes" to the question so the remote host fingerprint is saved in "known-hosts", and then Asbru CM works fine.

This is a screenshot taken just as I have typed "yes" and enter.
![image](https://user-images.githubusercontent.com/10371854/159134670-c233581b-8a6f-44d1-991f-7a600d99364e.png)

Thanks a lot for your help.

**Comment by gfrenoy** [comment]
Don't you want to have the "Auto-accept or delete unknown or offending SSH keys" options checked ?

![image](https://user-images.githubusercontent.com/981546/162587069-63e77cc7-891f-496d-ae0f-ad57abd4deb3.png)

**Comment by Kurgan-** [comment]
Yes, I do, and it worked on older Linux Mint versions.

**Comment by gfrenoy** [comment]
As suggested in the mentioned option, you need to check the related parameters (Host-key in your case).  See also https://github.com/asbru-cm/asbru-cm/issues/145#issuecomment-491524424 and #344.
