### ISSUE TITLE
Cannot get credentials from KeepassXC

### ISSUE THREAD

**Issue by xattack** [asbru-cm/asbru-cm#924]
**Describe the bug**

After getting an update for KeepassXC , it appears that asbru cannot get the 
passwords from KeepassXC  in new connections

**To Reproduce**
1. Create a new connection
2. try to assign the proper credentials 
3. It hangs

**Expected behavior**

  Getting the operations done

**Screenshots**

Asbru cannot complete the operations , even search for already know credentials 

![asbru-issue](https://user-images.githubusercontent.com/8902460/159970893-418795e5-b043-4da1-83c4-bf5ca039ed39.png)

In the console , this is what I get 

![asbru-console-messages](https://user-images.githubusercontent.com/8902460/159970935-a6a55f85-26a8-4c67-899c-d3eecc527dca.png)

The new version of KeepassXC 

![keepassXC-2 7 0](https://user-images.githubusercontent.com/8902460/159970965-eaa692fb-a473-4251-afba-7e120e9c7368.png)

I tried to assign manually the chains that it gets when it works, in the username space <username|/root group/sub group/name definition> and in password <password|/root group/sub group/name definition>, and it didn't work

![asbru-test](https://user-images.githubusercontent.com/8902460/159970989-d3c67ed5-629b-4f97-9280-ce9330f39e5e.png)

![Screenshot from 2022-03-24 11-12-38](https://user-images.githubusercontent.com/8902460/159972639-99d15f81-b33d-467a-a157-4ac8d33a2aea.png)

**Environment (please complete the following information):**
 - OS: Linux Mint 19.3 Tricia
 - Ásbrú Version 6.3.3

**Additional context**

**Comment by popxunga** [comment]
Hi ...
I'm unable to search credentials when using Keepassxc 2.7.1 on CentOS 8 Stream and RHEL 8.5.
I could not find any exceptions/errors.
May you please have a look into this @gfrenoy ?
Thanks a lot.

**Comment by gfrenoy** [comment]
It looks like the `locate` command has been replaced by `search`.... We'll need to check the version and change the code accordingly.

In the meantime, a quick fix would be to replace the keyword in `_locateEntries` (file lib/PACKeePass.pm)...

**Comment by gfrenoy** [comment]
Just pushed a fix for both the master and loki branches.  Let me know if it works for you.

**Comment by popxunga** [comment]
Thanks @gfrenoy ...
Nope it doesn't yet.
I notice a short CPU hog when I typing in the search box ... but still no results are shown.

**Comment by gfrenoy** [comment]
Strange, the search now works fine here.  Connections using KP are already working correctly.

Is this working fine from the command line:

```
keepassxc-cli search '<your-kdbx-file>' '/'
```

To make sure the command is correctly prapred, you can also display it?  Add some `print` in `PACKeePass.pm`...

**Comment by popxunga** [comment]
Hi ... 

Here are the commandl line test results:

```
[mockbuild@testc8]$ keepassxc-cli search 'Test.kdbx' '/'
Enter password to unlock Test.kdbx: 
No results for that search term.

[mockbuild@testc8]$ keepassxc-cli search 'Test.kdbx' 'rasp'
Enter password to unlock Test.kdbx: 
/Test/raspserver
```

And this is using the Asbru GUI:

![image](https://user-images.githubusercontent.com/37672088/162582360-efeac1a6-5916-4064-87bd-f7db2abca844.png)

![image](https://user-images.githubusercontent.com/37672088/162582420-67131c2c-5f65-489c-984b-4c8ada0736fd.png)

How to debug this further ?

**Comment by popxunga** [comment]
I added one in the sub _locateEntries function and it always print something like this no matter how many keys I press ,,,

`keepassxc-cli  search  '/home/mockbuild/Test.kdbx' '/'`

I guess I added it in the wrong place ...

**Comment by gfrenoy** [comment]
> I added one in the sub _locateEntries function and it always print something like this no matter how many keys I press ,,,

Yes, that is expected.

> `keepassxc-cli search '/home/mockbuild/Test.kdbx' '/'`

What is not expected is that this does not match any entry in your file ?!?  It is supposed to match all entries...

> I guess I added it in the wrong place ...

No this is OK :)  Ásbrú is reading all the entries and doing the filtering in memory.

**Comment by gfrenoy** [comment]
I think I get it ... We should have an "empty" term instead of `'/'`... As it is now, it will only match entries into subfolders but not the root entries.

Need to leave the keyboad now but I'll push another fix in a couple of hours.

In the meantime, you should remove the slash on this line:

```
$pid = open2(*Reader,*Writer,"$CLI $$self{kpxc_cli} ${search_command} $$self{kpxc_keyfile_opt} '$$cfg{database}' '/'");
```

So the line should be:

```
$pid = open2(*Reader,*Writer,"$CLI $$self{kpxc_cli} ${search_command} $$self{kpxc_keyfile_opt} '$$cfg{database}' ''");
```

**Comment by popxunga** [comment]
That makes sense as per the command line test executed previously.
The '/' argument worked fine with KeepasXC versions below 2.7.0. Maybe that changed as well..
Meanwhile tested this code in the `sub _locateEntries `function and it works fine:
```

            if (version->parse($$self{kpxc_version}) >= version->parse("2.7.0")) {
                $pid = open2(*Reader,*Writer,"$CLI $$self{kpxc_cli} ${search_command} $$self{kpxc_keyfile_opt} '$$cfg{database}' ''");
            } else {
                $pid = open2(*Reader,*Writer,"$CLI $$self{kpxc_cli} ${search_command} $$self{kpxc_keyfile_opt} '$$cfg{database}' '/'");
            }
```

**Comment by gfrenoy** [comment]
Thanks for the check, I made the change and it has been pushed to master & loki so it should be in the snapshots and loki repository in 20 minutes.

**Comment by popxunga** [comment]
Still not working ...
Re-added the print instruction and now nothing is printed into the terminal.
I noticed you added the search_term variable to the KeePassXC version test and are using it ithe the open2 call, but something is wrong (not sure what ... I do have to learn Pear).
By replacing it with the code in my previous update is works.

**Comment by gfrenoy** [comment]
Ouch!  Sorry, looks like I'm tired today ... I made a typo :-/  Should now be fixed... Thanks for your patience!

**Comment by popxunga** [comment]
This code works:
`$pid = open2(*Reader,*Writer,"$CLI $$self{kpxc_cli} ${search_command} $$self{kpxc_keyfile_opt} '$$cfg{database}' '${search_term}'");`

**Comment by popxunga** [comment]
The latest Loki build (asbru-cm-6.4.0~1649531693-1.el8) works fine!
Thanks a lot @gfrenoy !
