### ISSUE TITLE
Unable to install on Ubuntu 22.04

### ISSUE THREAD

**Issue by m0j072** [asbru-cm/asbru-cm#926]
This is likely a case of user error but I can't work out where I'm going wrong.  I see others have logged issues that are already running this on Jammy, so I think I should be able to install it.  I run the script and it seems to successfully set up the repo:

$ curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash

Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=22.04  codename=jammy  arch=x86_64  
 >>>>:
 NOPE: Checking for apt dependency 'apt-transport-https' ...
   OK: Updating apt repository metadata cache ...
   OK: Attempting to install 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!
   
I do an 'apt update' and then try to install but can't find the package.

$ sudo apt install asbru-cm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package asbru-cm

Any idea what I've missed or where I'm going wrong?

**Comment by m0j072** [comment]
Never mind.  Just downloaded the .deb and did a manual install.  Not sure if that was the best method, but it seems to be working.

**Comment by adm-surf-account1** [comment]
There isn't a asbru-cm repository for ubuntu 22.04 configured yet, so it can't find the source. Installing the .deb will fix it but there is also an option to use the 20.04 repo by editing the apt source:
```sudo nano /etc/apt/sources.list.d/asbru-cm-release.list```
change `jammy` to `focal`

I'm sure this will be fixed in the future when the devs get around to it, ubuntu 22.04 has been just released. The 20.04 version won't even offer it until the release of 22.04.1, which is in oktober I think.
