### ISSUE TITLE
Fedora: Not able to install when using the guide in the official docs

### ISSUE THREAD

**Issue by marie-dk** [asbru-cm/asbru-cm#928]
**Describe the bug**
asbru-cm is missing in the repository when installing for Fedora 35.

**To Reproduce**
1. Run the command: 
`curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.rpm.sh' | sudo -E bash`
It all works fine and ends in:
`OK: The repository has been installed successfully - You're ready to rock!`
2. Install asbru-cm:
```
dnf install asbru-cm
Last metadata expiration check: 0:00:49 ago on Thu Mar 2022 11:28:33 AM CEST.
No match for argument: asbru-cm
```

**Expected behavior**
Expected asbru-com to be found in the repository

**Screenshots**

**Environment (please complete the following information):**
 - OS: Fedora 35
 - Ásbrú Version: 6.3.2

**Additional context**
I succeeded by installing from snapshots instead:
```
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/snapshots/cfg/setup/bash.rpm.sh' | sudo bash
sudo dnf install asbru-cm
```
I don't know if this is the official way of installing... If so, the docs should be updated.

**Comment by gfrenoy** [comment]
The latest version (6.3.3) will be available on F35 but it has not been released to the main repository yet.
Hence it's only available in the `snapshots` repository.

See also #907
