### ISSUE TITLE
Ubuntu 22.04 apt-key is depreciated - installation script needs to be updated

### ISSUE THREAD

**Issue by StormTrooper** [asbru-cm/asbru-cm#929]
When installing asbru with the installation script:
```curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash```

The following warning is reported:
```
W: https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

This is due to apt-key being depreciated on Debian/Ubuntu/Mint/etc

**To Reproduce**
1. Run the installation script on Ubuntu 22.04

**Expected behavior**
Script should run without errors.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by AonDuine** [comment]
Hello @[xattack](https://github.com/xattack) 

Im facing thesame issue and i can't find a way to fix it. 

Can you please elaborate more about a possible solution

**Comment by StormTrooper** [comment]
I was able to fix it by doing the following:

Export the asbru key its into own keyfile:
```
sudo apt-key export 0B1C65E8 | sudo gpg --dearmour -o /usr/share/keyrings/asbru.gpg
```

Edit 
```
/etc/apt/sources.list.d/asbru-cm-release.list
```
(Or whatever your list file is called on your machine) and update to:

```
deb [arch=amd64 signed-by=/usr/share/keyrings/asbru.gpg] https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu jammy main
deb-src [arch=amd64 signed-by=/usr/share/keyrings/asbru.gpg] https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu jammy main
```

Then run
```sudo apt update```
to check if the error is gone, and then finally remove the old key.

```
sudo apt-key del 0B1C65E8
```

**Comment by gfrenoy** [comment]
Thanks for the report and the solution !  I guess there's nothing more we can do in Ásbrú about this...

**Comment by AonDuine** [comment]
i follow the solution @[StormTrooper](https://github.com/StormTrooper) suggested, but i can't install asbru yet.....

**Comment by StormTrooper** [comment]
> i follow the solution @[StormTrooper](https://github.com/StormTrooper) suggested, but i can't install asbru yet.....

What error are you getting?

**Comment by AonDuine** [comment]
Im starting the installation :

`sudo apt-add-repository multiverse
sudo apt install curl
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash`


And i'm getting the following error:

`W: https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
 ^^^^: ... Failed to update via apt-get update - Context above.
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact asbru-cm for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/asbru-cm/asbru-cm
 !!!!: 
`

I'm following the solution that @[StormTrooper](https://github.com/StormTrooper) has suggested:

First i run the command :

`sudo apt-key export 0B1C65E8 | sudo gpg --dearmour -o /usr/share/keyrings/asbru.gpg`

Then i'm updateing the  sudo vim /etc/apt/sources.list.d/asbru-cm-release.list as follows:

`# Source: asbru-cm
# Site: https://github.com/asbru-cm/asbru-cm
# Repository: asbru-cm / release
# Description: A certifiably-awesome open-source package repository curated by asbru-cm, hosted by Cloudsmith.


#deb https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu jammy main
#deb-src https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu jammy main

deb [arch=amd64 signed-by=/usr/share/keyrings/asbru.gpg] https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu jammy main
deb-src [arch=amd64 signed-by=/usr/share/keyrings/asbru.gpg] https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu jammy main
`

And then i run the update where it's seems the everything is ok, and i'm removing the key. 

But when i'm trying to install the package says that its unable to locate it. 

` sudo apt install asbru-cm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package asbru-cm
`

**Comment by StormTrooper** [comment]
What the output from:
```
lsb_release -a
```

**Comment by AonDuine** [comment]
Here it is: 

```No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Jammy Jellyfish (development branch)
Release:	22.04
Codename:	jammy
```

**Comment by StormTrooper** [comment]
Ok, I've run into the same issue. The reason I didn't experience it is I had asbru installed before the upgrade. 

The reason it doesn't install is that there is no build for ubuntu jammy.  

https://packagecloud.io/app/asbru-cm/asbru-cm/search?q=asbru-cm&filter=all&dist=ubuntu%2Fjammy


This issue will need to be re-opened @gfrenoy

As a workaround you will need to install the version for focal which also works on jammy

```

wget https://packagecloud.io/asbru-cm/asbru-cm/packages/ubuntu/focal/asbru-cm_6.3.2-1_all.deb/download.deb -O asbru-cm_6.3.2-1_all.deb


sudo dpkg -i asbru-cm_6.3.2-1_all.deb
```

if you run any any dependency issues you can fix them with 

```
sudo apt --fix-broken install
```

**Comment by AonDuine** [comment]
thanks, @StormTrooper, that worked.
