### ISSUE TITLE
Debian - build libgnome2-vte-perl need additional dependency

### ISSUE THREAD

**Issue by AdrianBan** [asbru-cm/asbru-cm#93]
Hi,

I've tried to install asbru-cm, but because I'm using Buster distribution there is no release for this.
So I can still use the Stretch one but I need to recompile the VTE Perl module for Buster.
As a suggestion you can add to libgnome2-vte-perl/debian/control those additional libs which are needed for building VTE:

```
Source: libgnome2-vte-perl
Section: perl
Priority: optional
Maintainer: Klaas Tammling <klaas@tammling.hamburg>
Build-Depends: debhelper (>= 9),
 libextutils-depends-perl (>= 0.20),
 libextutils-pkgconfig-perl (>= 1.03),
 libglib-perl (>= 1.01),
 libgtk2-perl (>= 1.00),
 libpango-1.0-0 (>= 1.00),
 libgtk2.0-0 (>= 2.00),
 perl
Standards-Version: 3.9.8
Homepage: https://metacpan.org/release/Gnome2-Vte

Package: libgnome2-vte-perl
Architecture: any
Depends: ${misc:Depends}, ${perl:Depends}, ${shlibs:Depends}, libpango-1.0-0, libgtk2.0-0
Description: Perl interface to the Virtual Terminal Emulation library
  This module allows you to use the Virtual Terminal Emulation library (libvte for short) from Perl.
  .
  The canonical API documentation can be found at:
    http://developer.gnome.org/doc/API/2.0/vte/index.html
  Gnome2::Vte also comes with automatically generated API documentation.  Its index can be accessed with:
    perldoc Gnome2::Vte::index


```

The problem is that if you are not installing libpango1.0-dev and libgtk2.0-dev the compilation will return an error but the packaging will still continue and create the .deb archive but without the lib inside.

Kind regard,
Adrian

**Comment by gfrenoy** [comment]
Dependencies have been reviewed, see https://github.com/asbru-cm/packages/commit/6e8a8417c13459035c6bf7cfb97faa6febb4462a
