### ISSUE TITLE
Unable to install on Ubuntu 22.04 (Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg))

### ISSUE THREAD

**Issue by BernardoGiordano** [asbru-cm/asbru-cm#930]
**Describe the bug**
I'm unable to install asbru-cm through apt on my Ubuntu 22.04 system.

**To Reproduce**
1. Run `curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash`
2. Run `sudo apt-get update`
3. See error

**Screenshots**
```
~$ curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=ubuntu  version=22.04  codename=jammy  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

~$ sudo apt-get update
Scaricamento di:1 https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu jammy InRelease [4.853 B]
Scaricamento di:2 http://it.archive.ubuntu.com/ubuntu jammy InRelease [270 kB]         
Trovato:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Trovato:4 http://it.archive.ubuntu.com/ubuntu jammy-updates InRelease
Trovato:5 http://it.archive.ubuntu.com/ubuntu jammy-backports InRelease
Recuperati 275 kB in 1s (430 kB/s)
Lettura elenco dei pacchetti... Fatto
W: https://dl.cloudsmith.io/public/asbru-cm/release/deb/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Ásbrú Version: the latest one provided through the cloudsmith repository at the time of writing

**Comment by xattack** [comment]
Hello @BernardoGiordano 


   Please refer to[ #929](https://github.com/asbru-cm/asbru-cm/issues/929)  , follow the instructions hope this can help you , cheers !

**Comment by BernardoGiordano** [comment]
Thank you, @StormTrooper workaround worked, but I guess the issue on the repository still needs to be addressed. Will leave this open for now. Thanks for reaching out

**Comment by javierjcf** [comment]
Same here.
Can't install for kubuntu 22.04.
When i try the workarrounnd of installing .deb package, asbru is not saving my conections.
When i reopen Asbru is all empty.
¿Some way to solve this?

I think the repository for ubuntu 22.04 should be fixed.

**Comment by braammalan** [comment]
> Same here. Can't install for kubuntu 22.04. When i try the workarrounnd of installing .deb package, asbru is not saving my conections. When i reopen Asbru is all empty. ¿Some way to solve this?
> 
> I think the repository for ubuntu 22.04 should be fixed.

I have the exact same issue on Fedora 35.  Maybe check #826

**Comment by gfrenoy** [comment]
Here are the instruction for a fresh Ubuntu 22.04 install:

```
sudo apt install curl
udo apt-add-repository universe
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/loki/setup.deb.sh' | sudo -E bash
sudo apt-key del 0B1C65E8
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/loki/gpg.1C9DA11D84B20237.key' | sudo gpg --dearmour -o /usr/share/keyrings/asbru.gpg
sudo sed -i 's/deb https:\/\/dl.cloudsmith.io/deb [signed-by=\/usr\/share\/keyrings\/asbru.gpg] https:\/\/dl.cloudsmith.io/' /etc/apt/sources.list.d/asbru-cm-loki.list
sudo sed -i 's/deb-src https:\/\/dl.cloudsmith.io/deb-src [signed-by=\/usr\/share\/keyrings\/asbru.gpg] https:\/\/dl.cloudsmith.io/' /etc/apt/sources.list.d/asbru-cm-loki.list
sudo apt update
sudo apt install asbru-cm
```

What this basically do is:
 - remove the Cloudsmith key from the default keyring
 - add the cloudsmith key in a newly created and dedicated keyring for Ásbrú in `/usr/share/keyrings/asbru.gpg`
 - use that keyring for the asbru repository on cloudsmith

I've open a discussing with cloudsmith to understand if they can integrate this into their default script.

**Comment by gfrenoy** [comment]
Cloudsmith support confirmed the problem has been fixed on their side.

Can anyone git it a new try and confirm it now works seamlessly ?

Thanks.

**Comment by nikuzz** [comment]
I can confirm it's working on Ubuntu 22.04 fresh install with the procedure exposed on https://www.asbru-cm.net/

Ásbrú 6.3.3

**Comment by braammalan** [comment]
so how do i get this to work in fedora 35?

**Comment by javierjcf** [comment]
I can confirm is working now woth asbru 6.3.4 on Ubuntu 22.04
