### ISSUE TITLE
Crash when opening new connection

### ISSUE THREAD

**Issue by Random-Chain** [asbru-cm/asbru-cm#931]
**Describe the bug**
I've recently started getting crashes when clicking the "Start a new connection" button.
Not sure what changed in my system, and the logs I find don't show a clear reason.

**Logs**
Syslog:
```
Apr 27 10:34:16 kernel: [ 5873.018224] show_signal: 19 callbacks suppressed
Apr 27 10:34:16 kernel: [ 5873.018232] traps: asbru-cm[40873] general protection fault ip:7fa0eab9268e sp:7fa0d51eb978 error:0 in libc-2.31.so[7fa0eaa29000+178000]
Apr 27 10:34:16 kernel: [ 5873.018257] asbru-cm[8674]: segfault at 20 ip 000055fcceadaaea sp 00007ffc66152f40 error 4 in perl[55fccea09000+16a000]
Apr 27 10:34:16 kernel: [ 5873.018284] Code: 8b 53 10 48 8b 40 10 c6 04 02 00 eb 9a 0f 1f 00 f3 0f 1e fa 41 54 53 48 89 f3 48 83 ec 18 4c 8b a7 08 01 00 00 4d 85 e4 74 56 <49> 8b 04 24 48 83 87 00 01 00 00 01 48 89 87 08 01 00 00 49 c7 04
```

Crash dump:
[_opt_asbru_asbru-cm.1000.crash.gz](https://github.com/asbru-cm/asbru-cm/files/8570078/_opt_asbru_asbru-cm.1000.crash.gz)

**Environment:**
 - OS: Pop!_OS 20.04
 - Ásbrú Version 6.3.2

**Comment by gfrenoy** [comment]
Mmm, that will be complicated to understand the root reason without additional information ...

How often does this happen?  Can you give it a try with the snapshot or loki release and see if it helps?

**Comment by Random-Chain** [comment]
I have already reinstalled my laptop with Pop!_OS 22.04 and not getting these crashes since. 
So whatever was causing this issue, I can't reproduce it now.

**Comment by gfrenoy** [comment]
Thanks for the feedback.  Let's close this one for now.
