### ISSUE TITLE
dont have repo package for Rocky Linux 8.5

### ISSUE THREAD

**Issue by sacy80** [asbru-cm/asbru-cm#932]
**Describe the bug**

**To Reproduce**
[root@localhost ~]# dnf install asbru-cm
asbru-cm-release                                417  B/s | 473  B     00:01    
asbru-cm-release-noarch                         459  B/s | 473  B     00:01    
asbru-cm-release-source                         457  B/s | 473  B     00:01    
asbru-cm-snapshots                              437  B/s | 473  B     00:01    
asbru-cm-snapshots-noarch                       419  B/s | 473  B     00:01    
asbru-cm-snapshots-source                       422  B/s | 473  B     00:01    
No match for argument: asbru-cm
Error: Unable to find a match: asbru-cm

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Rocky Linux 8.5
 - Ásbrú Version 6.3.2

**Additional context**

**Comment by gfrenoy** [comment]
See #894
