### ISSUE TITLE
Prepend command fails to auto login with saved password

### ISSUE THREAD

**Issue by ninokotur** [asbru-cm/asbru-cm#933]
**Describe the bug**
I found 6 month old post about when this was being developed on githubmemory for using chromaterm for coloring SSH session however i have issue with it as if i use "Prepend" option from advanced parameters connection won't auto connect it freezes on asking for password.

**To Reproduce**
1. Go to 'Edit connection > Prepend command
2. Enter /path/to/chromaterm
3. Try to connect on session that has username/password defined

**Expected behavior**
Connection connects with ssh through chromaterm

**Screenshots**
![image](https://user-images.githubusercontent.com/28425750/166123803-40f4db6d-f2cf-4b7d-8d1d-f275bc34b0f8.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu 20.04 on WSL, tried on Ubuntu 20.04 desktop VM as well]
 - Ásbrú Version [6.3.2]

I'm just linking here github memory post i'm reffering to
https://githubmemory.com/repo/asbru-cm/asbru-cm/issues/850?page=1

Also i want to mention that if adding to HOST section "192.168.10.32 | ct" works just fine, so i'm assuming there is some issue with prepend command and how its being processed?

**Comment by gfrenoy** [comment]
Don't you need the "postpend" option to make chromaterm to work ?  This was the prupose of #850 and has been implemented.  You need to use the `loki` branch to give it a try.
