### ISSUE TITLE
Bulk Edit Login Method

### ISSUE THREAD

**Issue by Thuemmi** [asbru-cm/asbru-cm#934]
i will change the Authentification from user/password to manual.
In the addressbook stay more then 1000 Hosts. Some way for that? Can i do that in any file with an editor?

thx
G.Thuemmler

**Comment by gfrenoy** [comment]
The first idea I would explore would be to:
- Stop Ásbrú
- Make a backup copy of `~/.config/asbru/asbru.yml`
- Start Ásbrú
- Make the change for one connection (& save your changes)
- Stop Ásbrú
- Examine the difference between your backup copy and the new version of `~/.config/asbru/asbru.yml`
- Use `sed` or any text editor to apply the same change to all your connections
- Replace `~/.config/asbru/asbru.yml` with your modified version
- Delete `~/.config/asbru/asbru.nfreeze`
- Start Ásbrú

Let us know if it worked for you...
