### ISSUE TITLE
Can't save any connections Fedora 35

### ISSUE THREAD

**Issue by braammalan** [asbru-cm/asbru-cm#935]
I have exactly the same issue as with Issue "Can't save Connections on Arch #826".  But I run Fedora 35.

I have tried to see if I can downgrade the "perl-Crypt-CBC" package to version 2.33.
It doesn't seem to be an option?

 - OS: Fedora 35
 - Ásbrú Version 6.3.3

**Comment by javierjcf** [comment]
Hi, 

I solve this problem in this:
https://github.com/asbru-cm/asbru-cm/issues/930

**Comment by zim333** [comment]
Hello, 
I got the same problem on Ubuntu 22.04 and solved by modifying the line 
`my $CIPHER = Crypt::CBC->new(-key => 'PAC Manager (David Torrejon Vaquerizas, david.tv@gmail.com)', -cipher => 'Blowfish', -salt => '12345678') or die "ERROR: $!";`

by

`my $CIPHER = Crypt::CBC->new(-key => 'PAC Manager (David Torrejon Vaquerizas, david.tv@gmail.com)', -cipher => 'Blowfish', -salt => '1', -pbkdf => 'pbkdf2') or die "ERROR: $!";`

On file /opt/asbru/lib/PACUtils.pm

**Comment by gfrenoy** [comment]
Please use the `loki` branch unti 6.4.0 is released.  See #816.
