### ISSUE TITLE
Fresh install on Linux Mint - paket not found

### ISSUE THREAD

**Issue by SvenPausH** [asbru-cm/asbru-cm#937]
**Describe the bug**
`root@lp-sven-2:~# curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
Executing the  setup script for the 'asbru-cm/release' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=linuxmint  version=20.3  codename=una  arch=x86_64  
 >>>>:
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'asbru-cm/release' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'asbru-cm/release' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

root@lp-sven-2:~# apt update

root@lp-sven-2:~# apt install asbru-cm
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket asbru-cm kann nicht gefunden werden.
`

**Environment (please complete the following information):**
Linux Mint 20.3 Una

**Comment by xattack** [comment]
wie gehts @SvenPausH 

In tha last [release](https://github.com/asbru-cm/asbru-cm/releases/tag/6.3.2) theres no Linux Mint 20.3 package. 

See #911 to workaround this issue

cheers !  

auf wiedersehen
