### ISSUE TITLE
the use of sudo for me does not work

### ISSUE THREAD

**Issue by liprox** [asbru-cm/asbru-cm#938]
Hi you!
I need a little help for the login with sudo.
For example: ssh login as user _max_ with (for example) the  
`sudo -i`
command. And without promt for the sudo password?
Is this possible? Now I get the sudo password popup. (if I write the correct password, the answer is in German that is has not work "das hat nicht funktioniert")
But my goal is working without writing the sudo password.
Any tips for me? 
for now I do not change the advance Preferences "sudo password promt", ther is
` [__PAC__SUDO__PROMPT__] ` and ` <<ASK_PASS>> `
But you does not have the same sudo password for all connection. But you have the same password for _max_ and for his sudo ...
hmmm, I need a little help ...
regards,
gerd

**Comment by xattack** [comment]
wie ghets @liprox 

   If you dont want to be asked for password using sudo , you must [edit the sudoers](https://www.cyberciti.biz/faq/linux-unix-running-sudo-command-without-a-password/) file and chage some parts for the user that you want . 

It's not related with asbru  

   cheers !

auf wiedersehen

**Comment by liprox** [comment]
Hi xattack,

thank you, danke ;-)
OT:
I have to think about it. I will use ssh keys in combination with a token (like onlykey or yubikey). I think it's simpler to work with root. On the other side, with  passwordless sudo, I can ban the remote root login and then it is a little bit more secure, because of the unknown name of the user ... hmmm.
regards, und Grüße,
 gerd
