### ISSUE TITLE
Colors are different in Asbru-CM vs terminal or PAC Manager

### ISSUE THREAD

**Issue by AdrianBan** [asbru-cm/asbru-cm#94]
Hi,

I've notice that the colors in MC for example are different from terminal and PAC Manager vb Asbru-CM. There is an option to change the colors for Asbru-CM?

![asbru-cm](https://user-images.githubusercontent.com/1823016/42158851-013fab64-7df2-11e8-89c4-e35db159f9ed.png)
![pac-manager](https://user-images.githubusercontent.com/1823016/42158852-0177155e-7df2-11e8-8d4f-664d7cddc5a5.png)

**Comment by gfrenoy** [comment]
Did you check #7 ?

**Comment by AdrianBan** [comment]
Hi,

Thanks. Indeed I've found that are some new options:
![asbru-cm-color](https://user-images.githubusercontent.com/1823016/42162585-7ab32b80-7dff-11e8-8528-8a6580b06510.png)
Which are not present in PAC Manager. Now I've fixed the colors and are like the old ones.
I've replaced Blue with #1818B2 and Cyan with #18B2B2.

Kind regards,
Adrian

**Comment by gfrenoy** [comment]
Actually, I meant #13 but glad to read you found out a solution :)

I've added this question to our FAQ : https://github.com/asbru-cm/asbru-cm/wiki/Frequently-Asked-Questions#colors-are-different-in-%C3%81sbr%C3%BA-cm-terminals-vs-pac-manager-terminals
