### ISSUE TITLE
Ubuntu 22.04 import doesn't work

### ISSUE THREAD

**Issue by AlexO-85** [asbru-cm/asbru-cm#940]
When i try to import list of connections exported from Asbru 6.3.2 on Ubuntu 18.04 to Asbru 6.3.2 on Ubuntu 22.04 import stuck once first connection is imported. The one imported is random from the list.

![image](https://user-images.githubusercontent.com/12782062/168128858-4310120e-281b-4434-b38c-b4914541a213.png)

If i run the app from CMD and try to import i receive the following messages: 

```
(asbru-cm:103405): Gtk-WARNING **: 19:48:05.004: Error loading theme icon 'network-idle' for stock: Icon 'network-idle' not present in theme breeze-dark
Use of uninitialized value $parent_uuid in hash element at /opt/asbru/lib/PACMain.pm line 2761.
WARNING: The key derivation method "opensslv1" is deprecated. Using -pbkdf=>'pbkdf2' would be better.
Pass -nodeprecate=>1 to inhibit this message.
 at /opt/asbru/lib/PACUtils.pm line 2718.
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /opt/asbru/lib/PACUtils.pm line 2718.
***  ignoring at /usr/share/perl5/Gtk3.pm line 572.
```

Could you please advise how to import connections?

Thanks in advance!

Regards,
Alex.

**Comment by zim333** [comment]
Hello, can you try this  https://github.com/asbru-cm/asbru-cm/issues/935#issuecomment-1124961326.

**Comment by gfrenoy** [comment]
6.3.2 won't work on Ubuntu 22.04 ; if you want to try an early version that fixes the issue, please try the one of the `loki` branch.
