### ISSUE TITLE
Unable to install asbru-cm on fedora 36.

### ISSUE THREAD

**Issue by 1smawell** [asbru-cm/asbru-cm#941]
I'm trying to install asbru-cm on a new installation of fedora 36.

I just follow the documentation for installing the application on fedora, but when i run sudo dnf install -y asbru-cm i get the error:

No match for argument: asbru-cm
Error: Unable to find a match: asbru-cm

I tried to install fedora 35 rpm but it didn't work.

The commands i executed were:
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.rpm.sh' | sudo -E bash
sudo dnf install asbru-cm

**Comment by 1smawell** [comment]
Solved installing asbru-cm-6.3.3~1652624949-1.fc35.noarch.rpm

**Comment by gfrenoy** [comment]
Ásbrú is now available in the `loki` and `snapshots` repositories.
