### ISSUE TITLE
Dumped core 

### ISSUE THREAD

**Issue by seteBR** [asbru-cm/asbru-cm#943]
**Describe the bug**
Lost all saved connections after exit the 6.3.2 version.

`[🡕] Process 7045 (asbru-cm) of user 1000 dumped core.
                                               
                                               Module linux-vdso.so.1 with build-id c4fab7a7ee86e62a6272cb22354ad5a06fbf1a5d
                                               Module MD5.so with build-id 3845c289950b360add245c175d67103841bcd049
                                               Module libdconfsettings.so with build-id 7a4ba7af122c4d11168004a9ea6def330f02089f
                                               Module libgthread-2.0.so.0 with build-id a4594cf4c07f4f6443d7bbdff34c0c1109e476e5
                                               Module libxfconf-0.so.3 with build-id 05a5980d778faaf25bba2d27249e359b41a796eb
                                               Module libxfconfgsettingsbackend.so with build-id 8ce01e731b1120543da65b897c044ac6073f4b2b
                                               Module libgioremote-volume-monitor.so with build-id b32824d1334e43af0033456180017669e3a7dd2b
                                               Module librsvg-2.so.2 with build-id 8c033bf594f51f48c7b2ee078fa4586ddb70513a
                                               Module libpixbufloader-svg.so with build-id b496e4f240c3dd862a5fe9ad31a464e65692cc08
                                               Module libibus-1.0.so.5 with build-id 9ee6cfbac64630c1ecf356c6f72d46f932e20be8
                                               Module im-ibus.so with build-id 14a8df0e1d67098299db587c198dd28c1efcc69e
                                               Module Blowfish.so with build-id 6af1c2ee344568da40674d3de80cac6a37c68e85
                                               Module libX11-xcb.so.1 with build-id f6beacd41cd16a23f53e5e56bb599e98f039d0d6
                                               Module libxcb-util.so.1 with build-id 4188ebc629b472b560849c5792a69c1803c3d1a4
                                               Module libXRes.so.1 with build-id 6ae98691f3ebed4aae1d0ac919078baa00d71fb6
                                               Module libstartup-notification-1.so.0 with build-id c31cad1791f13615a8f6c9ec025e1a3c3eef7736
                                               Module libwnck-3.so.0 with build-id 7561240bd4775322758f8608429f3a90b61c1e38
                                               Module ARP.so with build-id 6c8ed26e4c6f2a55e9949c7e4a8d3c2f1a8e69a2
                                               Module Hostname.so with build-id b28e68cb41fbc703d03de33a3e6ffa8abd17dbdd
                                               Module Socket6.so with build-id 587e45dfe2b40e307717fb2ab8b4625d9fd8ef11
                                               Module libgmp.so.10 with build-id e58d34ab389d1b649c24195c2d145e3ff2e58290
                                               Module libhogweed.so.6 with build-id 2d70cff7b1841b4d9ca4e8e7726cd4b944c07fdc
                                               Module libnettle.so.8 with build-id 9a878e513c02007598fcf1e2e286c2203f13536e
                                               Module libtasn1.so.6 with build-id ee3429ca5e94718aea4fe5249fc859e0cd88e4e9
                                               Module libunistring.so.2 with build-id 617dbf3d3d6f85d6556a7a036e23845e95490158
                                               Module libidn2.so.0 with build-id 1ce2b50ad9f9821c2c629b521cf5a3c99593d332
                                               Module libbrotlienc.so.1 with build-id 74adbc62e4fbb5da9d37b5aa458471f4130862ff
                                               Module libp11-kit.so.0 with build-id cc372ea3c28c4d3dfc633b4d2e933c8584d2af16
                                               Module libpcre2-8.so.0 with build-id a0306c1eb7393936ed0fb7328c8bb117726c2adc
                                               Module libgnutls.so.30 with build-id cab291a7adfcc0c6221df6ebc923cd18ac7dd190
                                               Module libvte-2.91.so.0 with build-id 360ab033f3d0130660da4752207cb7a6923c535f
                                               Module libgvfscommon.so with build-id 5c6df2952527d8d19cfb9ba14ceb290a15d186f8
                                               Module libgvfsdbus.so with build-id 2529d3764be816acfea14bd80db2c56c2cb7f024
                                               Module libdl.so.2 with build-id 94198b268228074fa9f405bbedbbae94112593ed
                                               Module libogg.so.0 with build-id ca0cae30a809f10db1f16e54a23b4e5ff7b2c54c
                                               Module libvorbis.so.0 with build-id f4e086347f6c1a66eb73cfe13974a29bd39aabca
                                               Module libltdl.so.7 with build-id c4ee3f1ba09fe34163d71ff336756fbecb6f409f
                                               Module libtdb.so.1 with build-id 6c9ccf6d9a22d117d984d1666842a49fd7669f09
                                               Module libvorbisfile.so.3 with build-id 45d2551167a616d448beb033ba49394831992887
                                               Module libcanberra.so.0 with build-id 8ddef69c9b84a86062c88a59510639cd908fc6d3
                                               Module libcanberra-gtk3.so.0 with build-id 2e99c78f79bea4bc67ccd9a9f8fed562f89599ee
                                               Module libcanberra-gtk-module.so with build-id cc626937222c6ce3f7bb45dbe6e862d0b1efba01
                                               Module libxkbfile.so.1 with build-id de5e415879c20263a8dd42f8cf2dd88107c2bfb2
                                               Module libxklavier.so.16 with build-id cefd678b3d270e389f50a9686ad2db83a8c67494
                                               Module libgnomekbd.so.8 with build-id 7a75c84337b94141ae6bdf56da86a5a6f72343bf
                                               Module libgnomekbdui.so.8 with build-id eeb3039b3aa71b38849fb1b3d2e97acb9edab6d4
                                               Module libxapp.so.1 with build-id 2d6867c3b087052ef8acd12a1a6c82b3c62b8f36
                                               Module libxapp-gtk3-module.so with build-id 12b94957cbe0eb705d8e900c9006d5333846d4db
                                               Module libgpg-error.so.0 with build-id f9aaa96d5ddf6f6872051ed7abcdfe6bdaff9b1c
                                               Module libgcrypt.so.20 with build-id 8bf3cb884124273640de797a3e77d86c98434ea4
                                               Module libcap.so.2 with build-id 21b00ab76bb16fde56fd741f07233c78069f0579
                                               Module liblz4.so.1 with build-id e63600ab23b2f6997f42fac2fa56e1f02ce159a1
                                               Module libgcc_s.so.1 with build-id 0e3de903950e35ae59a5de8c00b1817a4a71ca01
                                               Module libstdc++.so.6 with build-id b3eaebcb5369487562e52dd8d016c9cd77f80c54
                                               Module libicudata.so.71 with build-id 4fef196388e678deb881978139e125e20ee2d94d
                                               Module libsystemd.so.0 with build-id cdfc45d8f96e3af51b3d041c32f7899a93b86706
                                               Module liblzma.so.5 with build-id 28b40c7af8098a66af6ee093b6986b91cad7694d
                                               Module libzstd.so.1 with build-id 3bccb8fe08e48d5ea135b1d0f99de0d771dd752f
                                               Module libdatrie.so.1 with build-id 6fe3b6ece2c8e7d11869fa051375128d8f808f58
                                               Module libxml2.so.2 with build-id 8cdf00fa954d9a27f2f184c4d354cb14677446ac
                                               Module libjson-glib-1.0.so.0 with build-id 58decebd2c409d59b07f926ae4c513281918bc4d
                                               Module libsqlite3.so.0 with build-id 143cb4bde0356249e42c865273631c175d738ba1
                                               Module libicui18n.so.71 with build-id 6fd5c97fd2808ee29958bf809656d5885e7e8963
                                               Module libicuuc.so.71 with build-id 633fdc0c5385d916571f6140e7a978ad0630ef55
                                               Module libstemmer.so.0 with build-id 013b48e71279a5ec55e3021fc0bd8fb10a08bae5
                                               Module libatspi.so.0 with build-id 87bca381f073faea3b0ffd1ab06f5f8f204e24cf
                                               Module libdbus-1.so.3 with build-id 7f4b16b4b407cbae2d7118d6f99610e29a18a56a
                                               Module libtiff.so.5 with build-id 9e8868622f8b7144fd82dabfa8ac2fcaf6d45a34
                                               Module libjpeg.so.8 with build-id 324d9d66f01707241e31af5cc104db3c9122f4c4
                                               Module libthai.so.0 with build-id a7ac5010b4275c49308021200d23690533952702
                                               Module libXinerama.so.1 with build-id dbb6adece34ea2766d3efcd628af8f9757344dd6
                                               Module libXrandr.so.2 with build-id d4e869b5c72541e1de8f96b456248987ea52d51b
                                               Module libXcomposite.so.1 with build-id f1bb5ffb6203ab2907ac044a204ce3902a79f1c1
                                               Module libXdamage.so.1 with build-id a1d867e093c16944b2c0083be98050ef35c9e5c2
                                               Module libXcursor.so.1 with build-id f0525ae3715ac95f96a8cdb44795b03f831334b0
                                               Module libwayland-egl.so.1 with build-id ac45e227422559ff92c4d04851fffb8452874713
                                               Module libwayland-cursor.so.0 with build-id 647d92328111682fb15bff1c20a4c9368414857c
                                               Module libwayland-client.so.0 with build-id 95e7368b400dd57e3db2a5c385de71c7dca08879
                                               Module libxkbcommon.so.0 with build-id 3a9338b2085f0af41217bc0a90ffcc941938a16e
                                               Module libXfixes.so.3 with build-id 0a05c7e8714522bfbdd7c0027c3e2a94965664b0
                                               Module libtracker-sparql-3.0.so.0 with build-id d03c91051f78975ac3f1d4732d1fecf70b32e709
                                               Module libcloudproviders.so.0 with build-id ed1d9c9e60be4e858ad148484767249be1edf95f
                                               Module libatk-bridge-2.0.so.0 with build-id 1161ebbcc5aa791075dfa026671875e5417287bd
                                               Module libXi.so.6 with build-id 16603be937a02a7e61b0b0395d064be7efd86f49
                                               Module libepoxy.so.0 with build-id edc178a150c4255d124e1e1ecbdbecebd1a388cd
                                               Module libatk-1.0.so.0 with build-id c2de8b4fcbd9681cef225fe3956a9608a2a664bb
                                               Module libgdk_pixbuf-2.0.so.0 with build-id 5b8422ab971b1a8a8e1c43b88738d4ee217f609e
                                               Module libfribidi.so.0 with build-id fe9f35ac2a0074108c8306c517793f7279bd9b37
                                               Module libpangoft2-1.0.so.0 with build-id c2c09f789578900f61b7fca4a4311d8b94d9a750
                                               Module libpango-1.0.so.0 with build-id 7e27c1e46a1d958f6b16e1ba199f8bdb3f100566
                                               Module libpangocairo-1.0.so.0 with build-id b65f507d9e33adfbd19369acef5e5a0a2422c6d1
                                               Module libgdk-3.so.0 with build-id 4a9a6d5ddd18f22c56c05773208f8808cefacab6
                                               Module libgtk-3.so.0 with build-id 48baf44dfd4d51f8c2b81d852eb44de692c16b19
                                               Module libblkid.so.1 with build-id 140694a62d8d4d07c6c320a501f948dd1b389d73
                                               Module libmount.so.1 with build-id 4436aeea0cd8c01b5a77969e0531184f8b3513ce
                                               Module libgio-2.0.so.0 with build-id 8c411770513e0bc758a1bbe661af14c972e2a3c4
                                               Module libgmodule-2.0.so.0 with build-id c6df28882f153ee03d0fb33bb8aac2b219ebaacc
                                               Module libgirepository-1.0.so.1 with build-id e90459be4a81e316d337c7be79d5c32e53e7c9c8
                                               Module Introspection.so with build-id 30b0712b7e0003bf3167e4e04a80a5b0cb6e4c3a
                                               Module libcairo-gobject.so.2 with build-id 9927090dddfb180365695a8f37d1cac89463f109
                                               Module GObject.so with build-id 8296ca48e9ba6f49e684ec34cb7816fe3dcb1601
                                               Module libffi.so.8 with build-id f0a9586cf0f42d2b9971bd1065ca3a6b19f4a2c2
                                               Module libgobject-2.0.so.0 with build-id 4337ec84b2f33ec39a95863d47bfca0a28afd488
                                               Module Glib.so with build-id e8ffbf0334e91ca9e629dffbc95160622f8bf09d
                                               Module libpthread.so.0 with build-id 95ae4f30a6f12ccbff645d30f8e1a3ee23ec7d36
                                               Module libpcre.so.1 with build-id 845483dd0acba86de9f0313102bebbaf3ce52767
                                               Module libbrotlicommon.so.1 with build-id acfd597a977c8087bb6184383daae2e828a9ce42
                                               Module libglib-2.0.so.0 with build-id e268e80e668ce871312cf50e9969f88b086e33f2
                                               Module libgraphite2.so.3 with build-id 47761dc11e553f519cde97ed9ee985be12ccdae2
                                               Module libXdmcp.so.6 with build-id 8ca0792d23c8b8b4c0864297512349292bea5955
                                               Module libXau.so.6 with build-id 1c67764663e07bec24d8951e5fd93f4d165979ff
                                               Module libbrotlidec.so.1 with build-id 66c54e9301f7e102ecc1d88547e5f0e8a056fe22
                                               Module libharfbuzz.so.0 with build-id a11faa61f71b258fb92b717723757fc7dd141c01
                                               Module libbz2.so.1.0 with build-id 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                                               Module libexpat.so.1 with build-id 113bb5a3e9ad856801bfcfc029102c9bdc13d67e
                                               Module libpixman-1.so.0 with build-id 341f793dcada3a48a306a793d265a517e3f2e7d6
                                               Module libxcb-shm.so.0 with build-id 828fec4d856e2710e732ea8d92c3f250c807b1c2
                                               Module libxcb-render.so.0 with build-id b1ca498d665807ab0ccdafbe8070853efd058173
                                               Module libxcb.so.1 with build-id 13d677412a71468381b11092915d231f664d18d3
                                               Module libXrender.so.1 with build-id 97e0b9ab6ba96ebc86527cc2b3c3078aad8616b3
                                               Module libXext.so.6 with build-id d70f24beb4fad748d6becffdcc13e51be0a2ebfa
                                               Module libX11.so.6 with build-id d8e0be8e0323aa421366f19065ecd1c76405c130
                                               Module libfreetype.so.6 with build-id f89dd5502e75aca28fb5c3ccd0dbd26fe822bfef
                                               Module libfontconfig.so.1 with build-id 36be6951b8c1e42a7dd05684a37400fc8ef9147c
                                               Module libpng16.so.16 with build-id 2dc0bce07f199bf983c07a05fb95a6f4af83a9b3
                                               Module libz.so.1 with build-id fefe3219a96d682ec98fcfb78866b8594298b5a2
                                               Module libcairo.so.2 with build-id a222d042e56108d2786ece7bf291b56ba2069591
                                               Module Cairo.so with build-id d489257a2ba9c568821cfabe458bbb19b940f6a7
                                               Module Glob.so with build-id 0c36d092654b447a0dfc70683f42563486a2dff8
                                               Module libossp-uuid.so.16 with build-id 114a8d611f6fe4ce5f52c63ecbeebc81a642c8cc
                                               Module uuid.so with build-id 62790f88cd27c2f30bc4fea4e6376e798436872f
                                               Module IO.so with build-id 762c9d9a3a3daecc67f867f39702f9b8da6c7c92
                                               Module POSIX.so with build-id 0c40d83c4b458a44502b504624ca7bbb177aafc2
                                               Module Socket.so with build-id 9857b247197cedc504dd3fb77319a8b0c59c2b47
                                               Module Encode.so with build-id 9238b0c8e74e066e38a007d662d4348afc67aea8
                                               Module Storable.so with build-id 260bddde56eb5c8feeec7a88361a1648b4da4c4e
                                               Module Fcntl.so with build-id 58411f282d1d89679d1ef68a7c28525e5c064dd6
                                               Module Util.so with build-id 674d258be1093efe5bf38c78fa9dda9d79624f40
                                               Module HiRes.so with build-id 8526c50fcf8cf95d69cca878dd11dbf845f0070e
                                               Module Cwd.so with build-id 6147f2cd2a9ffc4c6032876d11bb914bc38baaff
                                               Module ld-linux-x86-64.so.2 with build-id fc93487393eea02b5bc6e76e48976fc325294c24
                                               Module libcrypt.so.2 with build-id a0a45f81771945f0559d04e93726d245159930da
                                               Module libm.so.6 with build-id 210ec9905e41825671210f8f7d0b24d6c371196a
                                               Module libc.so.6 with build-id 388993b6ef62f964bc7bf473c069fbfe957b9e44
                                               Module libperl.so with build-id 4fe2c77bdede5a3ced02abe5c53c78fd79e59770
                                               Module perl with build-id ec8995f5e7b76f88dbe513e378f5fa3450f23903
                                               Stack trace of thread 7045:
                                               #0  0x00007f4769c42054 n/a (libgobject-2.0.so.0 + 0x30054)
                                               #1  0x00007f4769c435c7 g_signal_emit_valist (libgobject-2.0.so.0 + 0x315c7)
                                               #2  0x00007f4769c43824 g_signal_emit (libgobject-2.0.so.0 + 0x31824)
                                               #3  0x00007f476931539e n/a (libgtk-3.so.0 + 0x33d39e)
                                               #4  0x00007f4769c33bb2 g_object_run_dispose (libgobject-2.0.so.0 + 0x21bb2)
                                               #5  0x00007f476936b2af n/a (libgtk-3.so.0 + 0x3932af)
                                               #6  0x00007f4769c33b35 g_object_unref (libgobject-2.0.so.0 + 0x21b35)
                                               #7  0x00007f4769c91de9 XS_Glib__Object_DESTROY (Glib.so + 0x20de9)
                                               #8  0x00007f476acf2480 Perl_pp_entersub (libperl.so + 0x102480)
                                               #9  0x00007f476ac62afa Perl_call_sv (libperl.so + 0x72afa)
                                               #10 0x00007f476acfabc7 S_curse.lto_priv.0 (libperl.so + 0x10abc7)
                                               #11 0x00007f476acfb328 Perl_sv_clear (libperl.so + 0x10b328)
                                               #12 0x00007f476acfa1d3 Perl_sv_free2 (libperl.so + 0x10a1d3)
                                               #13 0x00007f476acf4059 Perl_sv_clean_objs (libperl.so + 0x104059)
                                               #14 0x00007f476ac63f38 perl_destruct (libperl.so + 0x73f38)
                                               #15 0x000055fef3ee315d main (perl + 0x115d)
                                               #16 0x00007f476a9dd290 n/a (libc.so.6 + 0x29290)
                                               #17 0x00007f476a9dd34a __libc_start_main (libc.so.6 + 0x2934a)
                                               #18 0x000055fef3ee31c5 _start (perl + 0x11c5)
                                               
                                               Stack trace of thread 7047:
                                               #0  0x00007f476aab9faf __poll (libc.so.6 + 0x105faf)
                                               #1  0x00007f4769e18976 n/a (libglib-2.0.so.0 + 0xab976)
                                               #2  0x00007f4769dbf6c5 g_main_context_iteration (libglib-2.0.so.0 + 0x526c5)
                                               #3  0x00007f4769dbf712 n/a (libglib-2.0.so.0 + 0x52712)
                                               #4  0x00007f4769df1da5 n/a (libglib-2.0.so.0 + 0x84da5)
                                               #5  0x00007f476aa4054d n/a (libc.so.6 + 0x8c54d)
                                               #6  0x00007f476aac5b14 __clone (libc.so.6 + 0x111b14)
                                               
                                               Stack trace of thread 7124:
                                               #0  0x00007f476aab9faf __poll (libc.so.6 + 0x105faf)
                                               #1  0x00007f4769e18976 n/a (libglib-2.0.so.0 + 0xab976)
                                               #2  0x00007f4769dbf6c5 g_main_context_iteration (libglib-2.0.so.0 + 0x526c5)
                                               #3  0x00007f475cb4aebe n/a (libdconfsettings.so + 0x5ebe)
                                               #4  0x00007f4769df1da5 n/a (libglib-2.0.so.0 + 0x84da5)
                                               #5  0x00007f476aa4054d n/a (libc.so.6 + 0x8c54d)
                                               #6  0x00007f476aac5b14 __clone (libc.so.6 + 0x111b14)
                                               
                                               Stack trace of thread 7173:
                                               #0  0x00007f476aabf67d syscall (libc.so.6 + 0x10b67d)
                                               #1  0x00007f4769e1285f g_cond_wait_until (libglib-2.0.so.0 + 0xa585f)
                                               #2  0x00007f4769d90a83 n/a (libglib-2.0.so.0 + 0x23a83)
                                               #3  0x00007f4769df4f3b n/a (libglib-2.0.so.0 + 0x87f3b)
                                               #4  0x00007f4769df1da5 n/a (libglib-2.0.so.0 + 0x84da5)
                                               #5  0x00007f476aa4054d n/a (libc.so.6 + 0x8c54d)
                                               #6  0x00007f476aac5b14 __clone (libc.so.6 + 0x111b14)
                                               
                                               Stack trace of thread 7237:
                                               #0  0x00007f476aabf67d syscall (libc.so.6 + 0x10b67d)
                                               #1  0x00007f4769e1285f g_cond_wait_until (libglib-2.0.so.0 + 0xa585f)
                                               #2  0x00007f4769d90a83 n/a (libglib-2.0.so.0 + 0x23a83)
                                               #3  0x00007f4769df4f3b n/a (libglib-2.0.so.0 + 0x87f3b)
                                               #4  0x00007f4769df1da5 n/a (libglib-2.0.so.0 + 0x84da5)
                                               #5  0x00007f476aa4054d n/a (libc.so.6 + 0x8c54d)
                                               #6  0x00007f476aac5b14 __clone (libc.so.6 + 0x111b14)
                                               
                                               Stack trace of thread 7048:
                                               #0  0x00007f476aab9faf __poll (libc.so.6 + 0x105faf)
                                               #1  0x00007f4769e18976 n/a (libglib-2.0.so.0 + 0xab976)
                                               #2  0x00007f4769dc16a3 g_main_loop_run (libglib-2.0.so.0 + 0x546a3)
                                               #3  0x00007f4769aed6dc n/a (libgio-2.0.so.0 + 0x10a6dc)
                                               #4  0x00007f4769df1da5 n/a (libglib-2.0.so.0 + 0x84da5)
                                               #5  0x00007f476aa4054d n/a (libc.so.6 + 0x8c54d)
                                               #6  0x00007f476aac5b14 __clone (libc.so.6 + 0x111b14)
                                               
                                               Stack trace of thread 7236:
                                               #0  0x00007f476aabf67d syscall (libc.so.6 + 0x10b67d)
                                               #1  0x00007f4769e1285f g_cond_wait_until (libglib-2.0.so.0 + 0xa585f)
                                               #2  0x00007f4769d90a83 n/a (libglib-2.0.so.0 + 0x23a83)
                                               #3  0x00007f4769df4f3b n/a (libglib-2.0.so.0 + 0x87f3b)
                                               #4  0x00007f4769df1da5 n/a (libglib-2.0.so.0 + 0x84da5)
                                               #5  0x00007f476aa4054d n/a (libc.so.6 + 0x8c54d)
                                               #6  0x00007f476aac5b14 __clone (libc.so.6 + 0x111b14)
                                               ELF object binary architecture: AMD x86-64
`

**To Reproduce**
1. Exit with the windows `x` and reopen.

**Environment (please complete the following information):**
 - OS: Arch Linux 5.17.9-arch1-1
 - Ásbrú Version [asbru-cm 6.3.3]

**Comment by gfrenoy** [comment]
Thanks for the feedback.  Does this happen:
 - when you open the application ?
 - systematically ?
 - if you start from a fresh configuration file ?

**Comment by seteBR** [comment]
Thanks for the help @gfrenoy.
 
> Thanks for the feedback. Does this happen:
> 
> * when you open the application ?
The dumped core happen at the application exit and only when the window is closed by clicking at the `X` button. If the application is exited by `Quit` button at the bottom, it exits without the dumped core and the added /saved connections isn't lost.

> * systematically ?
Yes

> * if you start from a fresh configuration file ?
A start after the dumped core is like a start from a fresh configuration file.

Feel free to ask for more details if needed.
