### ISSUE TITLE
📡 Promote the latest release on tech medias

### ISSUE THREAD

**Issue by gfrenoy** [asbru-cm/asbru-cm#944]
The latest release (6.3.3) has been published today (May 21st) 🎉🥳, see release notes on https://github.com/asbru-cm/asbru-cm/releases/tag/6.3.3.

To help the Ásbrú Connection Manager project and increase the number of users and supporters, promoting this information on various medias specialized in technology would be very useful.

If you have any idea 😇 on how to push this information to these kind of medias or if you just have an account on social medias, please publish this information in your network and let us know here so we can understand and follow-up the impact on the community 💥.

Thanks for your help and continuous support 😊 !

**Comment by nikuzz** [comment]
I tweet it to the "sviluppatori italiani" (italian developers) community on Twitter.
https://twitter.com/Nico89com/status/1528422857063251974
