### ISSUE TITLE
Errors on PACUtils.pm and PACTerminal.pm

### ISSUE THREAD

**Issue by popxunga** [asbru-cm/asbru-cm#945]
**Describe the bug**
A friend of mine got in a situation where he was unable to click anything behind a system modal transparent rectangle.
After some diagnostics efforts, he found that the "phantom" rectangle was related with Asbru-cm process.
By killing the Asbru process the rectangle was gone and their system got back to normal.

**To Reproduce**
Happened once. Not reproducible at the moment.

**Expected behavior**
The system model rectangle shouldn't be displayed.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: RHEL 8.5
 - asbru-cm-6.4.0~1652732944-1.el8 (loki)

**Additional context**
The following error (first seen on May 6th) was found in the system log in the same time frame:
**Use of uninitialized value in concatenation (.) or string at /usr/share/asbru-cm/lib/PACUtils.pm line 1449**

While searching my system logs for comparison purposes, I found this one dated May 8th:
**Use of uninitialized value $val in concatenation (.) or string at /usr/share/asbru-cm/lib/PACTerminal.pm line 1634.**
I was probably using the latest loki build available on May 8th but I don't recall to be in a similar situation as my friend.

May you please have a look at the code and check is something can be done to avoid the errors  above ?

Thanks for your support.

**Comment by gfrenoy** [comment]
Strangely enough, there is no concatenation on line 1449 of PACUtils.pm on the loki branch, see --> https://github.com/asbru-cm/asbru-cm/blob/loki/lib/PACUtils.pm#L1449

Neither on https://github.com/asbru-cm/asbru-cm/blob/loki/lib/PACTerminal.pm#L1634

Not sure what I can do from here, ... sorry :(

**Comment by popxunga** [comment]
Hi @gfrenoy ...

On May 8th I was using asbru-cm-6.4.0~1650211130-1.el8.

For the PACTerminal error on line # 1634 this was the code:
**            $self->_sendData("WENTER|:|$val|:|$pos");**

For the PACUtils.pm error on line # 1449 I've to check with my colleague which asbru-cm version he was using on May 6th. 

Thanks.

**Comment by gfrenoy** [comment]
For PACTerminal error on line #1634, this is happening when a popup is shown so it would match the suspicion that a "hidden" modal popup is somewhere on another workspace.  So that the main interface is "blocked".

**Comment by popxunga** [comment]
For the PACTerminal error, whatever the reason is, I think that any variable must be initialized before usage.

Regarding the PACUtils.pm error my friend got it again (using asbru-cm-6.4.0~1652732944-1):

Use of uninitialized value in concatenation (.) or string at /usr/share/asbru-cm/lib/PACUtils.pm line 1449.
GLib-GObject-CRITICAL **: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed at /usr/share/perl5/vendor_perl/Gtk3.pm line 1392.
Use of uninitialized value in concatenation (.) or string at /usr/share/asbru-cm/lib/PACUtils.pm line 1449.

This error was occurred when he clicked the systray icon. The X interface got blocked with Asbru on focus but "invisible" (the mouse cursor shape changes matched Asbru and not was visible).

He got the message as well when right clicking an empty folder (without any connection defined).

I tried without any success to reproduce those errors myself using the same exact Asbru code version.
So I guess something strange might be happening caused by something not Asbru related.

**Comment by gfrenoy** [comment]
I'd propose to close this for now.  If you find more information about it later, let's reopen it.
