### ISSUE TITLE
"save and close" does not close the "Edit Connection" page

### ISSUE THREAD

**Issue by kenifanying** [asbru-cm/asbru-cm#949]
**Describe the bug**
"save and close" does not close the "Edit Connection" page

**To Reproduce**
1. Go to 'Connectios--Add a new connection in the selected node--type some settings'
2. Click on 'save and close'
3. "Edit Connection" page does not closed

**Expected behavior**
Click on 'save and close' should close the "Edit Connection" page

**Screenshots**

![image](https://user-images.githubusercontent.com/4479181/171043300-a991f89d-764c-438a-8fd9-b9b02021f915.png)

**Environment (please complete the following information):**
 - OS: [Xubuntu 22.04]
 - Ásbrú Version [6.3.3]

**Comment by kenifanying** [comment]
It seems that  'save and close' also not work in the 'preferences' page

**Comment by gfrenoy** [comment]
See #858 ; you will need to use the `loki` branch or wait for the next 6.4.0 release...
