### ISSUE TITLE
All saved connection lost after repeat some start and close.

### ISSUE THREAD

**Issue by kenifanying** [asbru-cm/asbru-cm#950]
**Describe the bug**
All saved connection lost after some start and close recycle. Less than 10 times.

**To Reproduce**
1. add and save some connection.
2. close the application and restart again.
3. repeat

**Expected behavior**
All saved connection should not lost.

**Environment (please complete the following information):**
 - OS: [Xubuntu 22.04]
 - Ásbrú Version [6.3.3]

**Comment by gfrenoy** [comment]
See #858 ; you will need to use the `loki` branch or wait for the next 6.4.0 release...
