### ISSUE TITLE
Use of '“' is deprecated as a string delimiter at /opt/asbru-cm/lib/asbru_conn line XXX

### ISSUE THREAD

**Issue by YahiaJr** [asbru-cm/asbru-cm#951]
**Describe the bug**
After the latest update to the app and the perl libraries this message appears on every new session.
Use of '“' is deprecated as a string delimiter at /opt/asbru-cm/lib/asbru_conn line XXX

**To Reproduce**
1. On Arch linux system do a regular update including asbru-cm-git and perl packages
2. Start Asbru or restart it if you already opened it before the upgrade.

**Expected behavior**
not to see any message except for the default one.

**Screenshots**
![image](https://user-images.githubusercontent.com/37158766/171445559-491272d3-0c98-454d-8289-6cf6f1348a0e.png)

**Environment (please complete the following information):**
 - OS: Arch [Garuda Linux]
 - Ásbrú Version 6.3.4

**Comment by beliys** [comment]
https://github.com/asbru-cm/asbru-cm/pull/952

**Comment by gfrenoy** [comment]
Thanks for reporting @YahiaJr, and the fix @beliys, very much appreciated :)  It has been applied to our "snapshots" and "loki" repositories.

**Comment by xi-ao** [comment]
Hi,
When is the [6.3.4](https://github.com/asbru-cm/asbru-cm/milestone/12) supposed to be released with this fix please?

**Comment by gfrenoy** [comment]
No defined plan for the release but you can use the "snapshot" repository...

**Comment by xi-ao** [comment]
@gfrenoy Right thanks.

:information_source: For Archers, it means switching to the `asbru-cm-loki-git` AUR package.

**Comment by sam5558** [comment]
The asbru-cm-loki-git version is older (6.3.2) in AUR package (year 2021).
It's better to wait for a stable 6.3.4 release.

**Comment by beliys** [comment]
Just install asbru-cm-git (https://aur.archlinux.org/packages/asbru-cm-git) which installs the git version of the code.
