### ISSUE TITLE
Can't save Connections on Ubuntu 22.04

### ISSUE THREAD

**Issue by Mukeko** [asbru-cm/asbru-cm#953]
**Describe the bug**
I'm installing Asbu on my Ubuntu 22.04, and it doesn't let me save the sessions I create. I don't know where the problem could be.

**To Reproduce**
1. Go to Quit, and not save Connections.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Ásbrú Version 6.3.3

**Additional context**
xxxxx@xxxxx:~$ asbru-cm 
INFO: Ásbrú Connection Manager 6.3.3 (asbru-cm) started with PID 58689
INFO: Language detected : es_ES.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : gnome-shell:ubuntu
INFO: Config directory is '/home/urko/.config/asbru'
WARN: No configuration file found in '/home/urko/.config/asbru', creating a new one...
INFO: Virtual terminal emulator (VTE) version is 0.68
GLib-GObject-WARNING **: invalid (NULL) pointer instance at /opt/asbru/lib/PACMain.pm line 4910.
GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed at /opt/asbru/lib/PACMain.pm line 4910.
INFO: Theme directory is '/opt/asbru/res/themes/default'
INFO: No tray available
WARN: Adding new keybinding [Ctrl+t] for [Connections Tree]/[Collaps tree completly]...
WARN: Adding new keybinding [Ctrl+I] for [Terminal]/[Show the Info tab]...
WARN: Adding new keybinding [Alt+F] for [Connections Tree]/[Remove connection from favourites]...
WARN: Adding new keybinding [Ctrl+0] for [Terminal]/[Zoom reset text]...
WARN: Adding new keybinding [Ctrl+d] for [Connections Tree]/[Clone connection]...
WARN: Adding new keybinding [Ctrl+minus] for [Terminal]/[Zoom out text]...
WARN: Adding new keybinding [F11] for [Terminal]/[Go full screen]...
WARN: Adding new keybinding [Alt+e] for [Clusters Tree]/[Edit selected node]...
WARN: Adding new keybinding [Ctrl+Page_Up] for [Tabs]/[Previous Tab]...
WARN: Adding new keybinding [Alt+n] for [Terminal]/[Show/Hide connections list]...
WARN: Adding new keybinding [Ctrl+Insert] for [Terminal]/[Copy selection to clipboard]...
WARN: Adding new keybinding [Ctrl+b] for [Terminal]/[Paste and regex delete]...
WARN: Adding new keybinding [Ctrl+Tab] for [Tabs]/[Last focused Tab]...
WARN: Adding new keybinding [Alt+r] for [Connections Tree]/[Toggle protection]...
WARN: Adding new keybinding [undef-infotab] for [Tabs]/[Got to Info Tab]...
WARN: Adding new keybinding [Alt+f] for [Connections Tree]/[Add connection to favourites]...
WARN: Adding new keybinding [Ctrl+T] for [Main Window]/[Open a local shell]...
WARN: Adding new keybinding [Alt+e] for [Connections Tree]/[Edit selected node]...
WARN: Adding new keybinding [Ctrl+r] for [Connections Tree]/[Expand tree completly]...
WARN: Adding new keybinding [Ctrl+Return] for [Terminal]/[Start Terminal]...
WARN: Adding new keybinding [Ctrl+x] for [Connections Tree]/[Cut node]...
WARN: Adding new keybinding [Ctrl+R] for [Terminal]/[Restart connection (close and start)]...
WARN: Adding new keybinding [Ctrl+q] for [Terminal]/[Exit Ásbrú]...
WARN: Adding new keybinding [Alt+e] for [Favourites Tree]/[Edit selected node]...
WARN: Adding new keybinding [Ctrl+F4] for [Tabs]/[Close current Tab]...
WARN: Adding new keybinding [Ctrl+q] for [Main Window]/[Exit Ásbrú]...
WARN: Adding new keybinding [Alt+c] for [Connections Tree]/[Connect selected node]...
WARN: Adding new keybinding [Ctrl+N] for [Terminal]/[Close disconnected sessions]...
WARN: Adding new keybinding [Ctrl+F3] for [Terminal]/[Find Terminal]...
WARN: Adding new keybinding [Ctrl+p] for [Terminal]/[Paste terminal password]...
WARN: Adding new keybinding [Ctrl+Page_Down] for [Tabs]/[Next Tab]...
WARN: Adding new keybinding [Ctrl+V] for [Terminal]/[Paste clipboard into terminal]...
WARN: Adding new keybinding [Ctrl+v] for [Connections Tree]/[Paste node]...
WARN: Adding new keybinding [Ctrl+D] for [Terminal]/[Duplicate connection]...
WARN: Adding new keybinding [Ctrl+f] for [Main Window]/[Find in connection tree]...
WARN: Adding new keybinding [Ctrl+f] for [Terminal]/[Find in connection tree]...
WARN: Adding new keybinding [Ctrl+f] for [Connections Tree]/[Find in connection tree]...
WARN: Adding new keybinding [Ctrl+g] for [Terminal]/[Guess hostname]...
WARN: Adding new keybinding [Shift+Insert] for [Terminal]/[Paste selection into terminal]...
WARN: Adding new keybinding [AltCtrl+x] for [Terminal]/[Reset Terminal]...
WARN: Adding new keybinding [Alt+F] for [Favourites Tree]/[Remove connection from favourites]...
WARN: Adding new keybinding [Alt+e] for [Terminal]/[Edit Connection]...
WARN: Adding new keybinding [Ctrl+plus] for [Terminal]/[Zoom in text]...
WARN: Adding new keybinding [Ctrl+w] for [Terminal]/[Close Terminal]...
WARN: Adding new keybinding [Alt+e] for [History Tree]/[Edit selected node]...
WARN: Adding new keybinding [AltCtrl+X] for [Terminal]/[Reset Terminal and Clear window]...
WARN: Adding new keybinding [CtrlShift+F4] for [Terminal]/[Close all tabs]...
WARN: Adding new keybinding [Ctrl+ampersand] for [Terminal]/[Send Cisco interrupt keypress]...
WARN: Adding new keybinding [Alt+n] for [Main Window]/[Show/Hide connections list]...
WARN: Adding new keybinding [Ctrl+W] for [Terminal]/[Disconnect Terminal]...
WARN: Adding new keybinding [F2] for [Connections Tree]/[Rename node]...
WARN: Adding new keybinding [Ctrl+c] for [Connections Tree]/[Copy node]...
WARN: Adding new keybinding [CtrlAlt+r] for [Terminal]/[Remove terminal from cluster]...
WARN: Adding new keybinding [AltCtrl+s] for [Terminal]/[Open SFTP session]...

(asbru-cm:58689): Gtk-CRITICAL **: 19:05:36.908: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
INFO: Finishing (asbru-cm) with pid 58689
WARNING: The key derivation method "opensslv1" is deprecated. Using -pbkdf=>'pbkdf2' would be better.
Pass -nodeprecate=>1 to inhibit this message.
 at /opt/asbru/lib/PACUtils.pm line 2718.
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /opt/asbru/lib/PACUtils.pm line 2718.
***  ignoring at /usr/share/perl5/Gtk3.pm line 572.
Violación de segmento (`core' generado)

**Comment by amg-web** [comment]
same to me.
It does not save anything manually or auto save is enabled.
also when edit connection "Save & Close" button does not work

**Comment by gfrenoy** [comment]
See #858.

**Comment by Mukeko** [comment]
I think it's not the same problem, it lets me close the program without any error, but when I open it again the connections I created disappear.

![1](https://user-images.githubusercontent.com/107427245/173530348-0a576745-091a-46a7-ba99-b489d0da5e07.png)
![2](https://user-images.githubusercontent.com/107427245/173530352-077bac1a-a162-4277-90c0-e9c0784b0725.png)
![3](https://user-images.githubusercontent.com/107427245/173530354-c4333e17-4cd3-4087-afcd-da3047526ae4.png)

**Comment by amg-web** [comment]
I'll add to my post
it does not save anything 
connections, settings, etc.

**Comment by gfrenoy** [comment]
> I think it's not the same problem

Yes, it is.

Please try the latest `loki` branch (see https://docs.asbru-cm.net/General/Installation/) or our AppImage (see https://www.appimagehub.com/p/1796061).  It is fixed there.

**Comment by vitormupe** [comment]
> > I think it's not the same problem
> 
> Yes, it is.
> 
> Please try the latest `loki` branch (see https://docs.asbru-cm.net/General/Installation/) or our AppImage (see https://www.appimagehub.com/p/1796061). It is fixed there.

Hi gfrenoy, I just found your post, but before it I installed the libcrypt-cbc-perl_2.33-1_all.deb on Ubuntu 22.04 and everything works fine, auto save and save nodes connections ;) . 
Thanks
