### ISSUE TITLE
Keep button bar hidden when returning to a tab

### ISSUE THREAD

**Issue by ddevz** [asbru-cm/asbru-cm#954]
**Is your feature request related to a problem? Please describe.**
When looking at a tab, you have the option to click "Show/Hide" button bar".  Clicking it hides the button bar as expected.  This is great.  
Now if you switch to another tab and then back, the button bar is back to being shown, and you have to click the hide button again every time you come back to the tab (actually you have to click it twice each time, the first time to reset the show/hide button)

This is particularly annoying as having the button bar there can sometimes screw up the "virtual screen size" when using screen (over ssh).

**Describe the solution you'd like**
I propose that when you hide the button bar for a tab that it should stay hidden when you come back from another tab.

**Describe alternatives you've considered**
A setting to default to hiding the button bar on all tabs would probably be even better

**Additional context**
version 6.3.3

**Comment by gfrenoy** [comment]
Confirmed !  Thanks for your feedback and the great description :)

**Comment by gfrenoy** [comment]
I reviewed the way this button is working ; the button bar now stays hidden (or visible) on all terminals when you toggle the option.

It is actually linked to the global option "Auto hide main button bar" in Preferences > Main Options > Look and Feel so you can set the default value there.

You can test this in our snapshot release and it will be included in the next 6.4.1 version.

**Comment by ddevz** [comment]
Thanks!
