### ISSUE TITLE
Ver. 6.3.3 doesn't save connections

### ISSUE THREAD

**Issue by Quin452** [asbru-cm/asbru-cm#955]
**Describe the bug**
I've installed Asbru, and when I create a new connection, it is lost when I close the app.  I've tried many different times, and reboots, and it's always the same.

**To Reproduce**
1. Create a new connection
2. Connect to it
3. Exit
4. Close the program
5. Restart the program
6. No connections found

**Expected behavior**
Expected for connections to be retained.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Ásbrú Version 6.3.3

**Comment by xattack** [comment]
Hi @Quin452 

  You could see #953 and #858 seems to be related 

   Also you could try installing the latest loki build and let the community  know if it fix the issue

**Comment by amg-web** [comment]
@xattack 
what is loki ?

**Comment by KlaasT** [comment]
Loki is basically our unstable build. While we try to keep it as stable as possible when developing new features it might not always be the case.

**Comment by gfrenoy** [comment]
See #858.

Please try the latest loki branch (see https://docs.asbru-cm.net/General/Installation/) or our AppImage (see https://www.appimagehub.com/p/1796061).  It has been fixed there.
