### ISSUE TITLE
Can't close popped out split tab

### ISSUE THREAD

**Issue by DKNorad** [asbru-cm/asbru-cm#956]
**Describe the bug**
After splitting two tabs, either vertically or horizontally, and then dragging the tab out you can't close the window. Trying to close it only disconnects one of the sessions. In order to close it you need to manually disconnect the second one.

**To Reproduce**
1. Open two connections.
2. Split them horizontally or vertically.
3. Pop out the tab from the main window.
4. Try to close it.

**Expected behavior**
To disconnect both sessions in order to close the window.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Ásbrú Version 6.3.3

**Comment by xattack** [comment]
Hi @DKNorad   

   You can close windows in asbru with CTRL+w  , that is how the keybindings are defined in asbru. You
can find this keybindings in Preferences --> Keybindings , and you can customize it according
with your needs. 

    If you want to disconnect boths sessions , or any other number of sessions, you can use the Power Cluster Controller 
PCC , in order to do that.

Cheers
