### ISSUE TITLE
Use selected auth method do not work as expected

### ISSUE THREAD

**Issue by zystem** [asbru-cm/asbru-cm#957]
**Describe the bug**
I want to return Asbru usage to the same scenario as in 5.x version. I do not use any Asbru auth functionality and rely on embedded ssh auth options. So I specify "Host:" in format user@ip and expect it will work the same as in 5.x, but Asbru just fully ignores the user name. I read the documentation and looks like "Use selected auth method" should do what I want, Asbru start to auth with a specified user name but ignores the ssh key if it is added to the destination and ask for a password ever.

**To Reproduce**
1. Copy the ssh key to the destination and check what plain ssh does not ask for a password.
2. Select "Use selected auth method"
3. See what Asbru ignore the key and ask for a password

**Expected behavior**
Asbru bypasses any embedded auth and uses plain OpenSSH functionality.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mint una
 - Ásbrú Version v6.3.3

**Comment by gfrenoy** [comment]
The latest version is still supposed to work as you described.  It must be a problem in the way you configured the client and server systems.
