### ISSUE TITLE
Unable to install on Linux Mint 19 (LTS Release)

### ISSUE THREAD

**Issue by derrickmehaffy** [asbru-cm/asbru-cm#96]
Linux Mint is based on the Ubuntu 18.04 LTS Release (Bionic)

Attempting to use the override `os=ubuntu dist=bionic` doesn't provide any packages to install.

Running the script without the overrides provides the follow:

```
Unable to download repo config from: https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/config_file.list?os=LinuxMint&dist=tara&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.
```

**Comment by gfrenoy** [comment]
At this time, the bionic package is only available in the "snapshots" repository, did you have a look at this:
  https://packagecloud.io/app/asbru-cm/snapshots/search?dist=ubuntu%2Fbionic

See also https://github.com/asbru-cm/asbru-cm/issues/66

**Comment by gfrenoy** [comment]
:record_button: For the records:
http://www.blindinganswers.com/blog/how-to-install-pac-manager-in-linux-mint-19/

**Comment by gfrenoy** [comment]
The latest release [(5.2)](https://github.com/asbru-cm/asbru-cm/releases/tag/5.2.0) can now be installed on Linux Mint 19 and 19.1 (Tara and Tessa), see [specific instructions](https://github.com/asbru-cm/asbru-cm/wiki/installation-on-mint).
