### ISSUE TITLE
Red Hat 9 support

### ISSUE THREAD

**Issue by wunix99** [asbru-cm/asbru-cm#961]
current version does not seem to be supported on RHEL9
No match for argument: asbru-cm
Error: Unable to find a match: asbru-cm

**Comment by wunix99** [comment]
i used the centos install method with /epel-release-latest-9.noarch.rpm

**Comment by gfrenoy** [comment]
The Ásbrú project will not be able to support all the distributions.  Especially if this is a commercial one, you may want to contact the distribution and ask them to support Ásbrú, we will be happy to help them.
