### ISSUE TITLE
The sorting of list of connections from right click->"goto tab" can make tabs hard to find

### ISSUE THREAD

**Issue by ddevz** [asbru-cm/asbru-cm#962]
**Is your feature request related to a problem? Please describe.**
I find it difficult to find tabs in the right click->"goto tab" list of connections when they are sorted list looks like:

...
18:   server78
19:   server823
1:     server23 
20:   server888
21:   server33
2:     server43
3:     server11
4:     server72
...

**Describe the solution you'd like**
Allow the sorting of the connections list obtained by "right click"->"goto tab" to be either by number value, or alphabetically by the name of the tab (instead of alphabetically by a string of the tab number)

**Describe alternatives you've considered**
If that would take effort, maybe change the string representing the tab to be {name of tab} ({tab number}) instead of {tab number}: name of tab

**Comment by gfrenoy** [comment]
Thanks for the feedback !  If you have more than 10 connections open, the ordering becomes very confusing.

What about removing the {tab number} completely ?  I don't believe it really helps, does it ?

**Comment by ddevz** [comment]
> What about removing the {tab number} completely ? I don't believe it really helps, does it ?

By "removing the {tab number}", that would make it sort by alphabetical order of the name?  something like this?:

server11
server23
server33
server43
server72
server78
server823
server888




If so that might work  Although we might want to have the tab number at the end of the string if we are doing that so we have a method of differentiating for when you have multiple tabs open to the same location (like 5 tabs to "Local").  So it would be something like:

server11 - 3:
server23 - 1: 
server33 - 21: 
server43 - 2: 
server72 - 4: 
server78 - 18: 
server823 - 19: 
server888 - 20: 

Alternatively, a "0" could be added before any tab number that's less then 10.   
(this pushes the problem off to people that have more then 99 tabs open :)

*I* would probably be happier with alphabetical sorting by name, but i don't know about other people.  Maybe some people mentally index the tabs by tab number (or location/approximate tab number)

**Comment by gfrenoy** [comment]
> By "removing the {tab number}", that would make it sort by alphabetical order of the name?

As far as I can [read the code](https://github.com/asbru-cm/asbru-cm/blob/master/lib/PACTerminal.pm#L2580-L2596), yes.

> so we have a method of differentiating for when you have multiple tabs open to the same location

Good point, indeed !  Thanks for the heads up.

> I would probably be happier with alphabetical sorting by name

Gave it a try and it definitely looks more intuitive like this.  The change will be added to the next version.

Thanks again for your feedback.

**Comment by ddevz** [comment]
Cool.  Thanks!

**Comment by gfrenoy** [comment]
The fix is available in our `loki` branch and will be available in the next release.  Let's close the issue for now.
