### ISSUE TITLE
Parrot OS install failure

### ISSUE THREAD

**Issue by git2212** [asbru-cm/asbru-cm#965]
Hello,

it appears that asbru cannot be installed currently on Parrot OS (a Debian derivative). I get the following message:

>>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=parrot  version=5.0  codename=ara  arch=x86_64  
 >>>>:
 >>>>: You can force this script to use a particular value by specifying distro,
 >>>>: version, or codename via environment variable. E.g., to specify a distro
 >>>>: such as Ubuntu/Xenial (16.04), use the following:
 >>>>:
 >>>>:   <curl command> | distro=ubuntu version=16.04 codename=xenial sudo -E bash

I could force the debian version for the install but don't know if that's safe, I don't want to break my install...

Any fix for this?

**Comment by gfrenoy** [comment]
The Ásbrú project does not have the resources to support all the distributions.  Especially if there are a derivative of the Debian distribution, it is indeed very safe to go for the suggested override.
