### ISSUE TITLE
reorder tabs

### ISSUE THREAD

**Issue by mc36** [asbru-cm/asbru-cm#966]
**Is your feature request related to a problem? Please describe.**
it helps me a lot to have tabs in a specific order...
when dealing with routers, i order tabs from left to right as they appear in the traceroute...

**Describe the solution you'd like**
ctrl+shift+pgup|pgdn should move the current tab left/right, much link in firefox

**Describe alternatives you've considered**
maybe make it configurable in key bindings

**Additional context**
moving tabs left/right with mouse also would be helpful...

**Comment by merikz** [comment]
Hi,
Moving tabs with mouse should work. It is not animated, but at least when I double click + drag the cursor changes and when dropping on top of another tab the dropped tab is moved to the left of the dropped-on tab.
Is this not happening for you?

**Comment by gfrenoy** [comment]
Thanks for your feedback!

Re-ordering tabs using the mouse is indeed working.

As there is a solution, I'll close this issue but please re-open and modify the title to be more specific if you believe having a dedicated key for this is important.
