### ISSUE TITLE
a startup option to chdir somewhere

### ISSUE THREAD

**Issue by mc36** [asbru-cm/asbru-cm#969]
**Is your feature request related to a problem? Please describe.**
running appimage means it's chdirs to some random place...
connecting sftp tabs starts in that random, readonly folder...

**Describe the solution you'd like**
an argv --chdir /home/xxx could do the trick

**Describe alternatives you've considered**
maybe a per-connection sftp directory option would be better...
tried with the pre-command, it asked my permission to do the command, but cd xxx did not worked out, lpwd in sftp still printed the jailed path

**Additional context**
n/a

**Comment by beliys** [comment]
Try adding a command to 'Edit Connections ->Expect->Send'

**Comment by gfrenoy** [comment]
Does the workaround suggested by beliys work for you ?

And is your question only related to SFTP ?

**Comment by mc36** [comment]
yess, thanks a lot, the workaround works fine!
and yess, i only found the sftp use-case yet....

**Comment by gfrenoy** [comment]
Thanks for the feedback.  Let me close that one for now.
