### ISSUE TITLE
Snap support

### ISSUE THREAD

**Issue by zendre4** [asbru-cm/asbru-cm#97]
Hello, 

I think it would be nice to add this app in snap store like this PAC Manager fork: 

https://snapcraft.io/pac-vs

Snap is multi distribution and it's full integrate natively in Ubuntu OS family...

**Comment by KlaasT** [comment]
Do you have any experience with snap? We are searching for contributors to assist us in keeping the project running and distributing the software to different platforms.

**Comment by zendre4** [comment]
no unfortunately not... In my job we use AppImage for deployment.

**Comment by gfrenoy** [comment]
Or maybe one should contact "vasilisc" to see if he would agree to help us ?

**Comment by KlaasT** [comment]
I like the concept of multi platform distribution however I don't think we can support all of them. I personally like AppImage. A downloadable file with is executable and would run on any linux distribution.

I'm using the AppImage from Flexoptics to configure our optical transceivers and it works good.

**Comment by zendre4** [comment]
We have some problem with AppImage. We we remark than when test an AppImage compile from Ubuntu 16.04 to an Ubuntu 18.04, the AppImage wasn't working because our app is develop with QT and QT use some  library of the host system (like libssl) and library version of 18.04 was not compatible with the AppImage compile in 16.04... 

With snap package, the app is confined and all lib are independent of the hosting system. The second advantage is than the snap package have no access to hosted system by default, and user can control that.

**Comment by zendre4** [comment]
it's also much simple to update

**Comment by rubensa** [comment]
> We have some problem with AppImage. We we remark than when test an AppImage compile from Ubuntu 16.04 to an Ubuntu 18.04, the AppImage wasn't working because our app is develop with QT and QT use some library of the host system (like libssl) and library version of 18.04 was not compatible with the AppImage compile in 16.04...
> 
> With snap package, the app is confined and all lib are independent of the hosting system. The second advantage is than the snap package have no access to hosted system by default, and user can control that.

Can't those libraries be included in the AppImage?

**Comment by gfrenoy** [comment]
> Can't those libraries be included in the AppImage?

Certainly but the good question is : who can do that job ?

When we set "help wanted" as label, it means we're looking for someone to help us implementing the feature so candidates are welcome !  We'll support them as much as we can, of course.

**Comment by zendre4** [comment]
> Can't those libraries be included in the AppImage?
Probably...

But after few month of problems we switch from AppImage to Flatpak. I made many search for determine if snap was the best solution for us, and we decide for some reason to make a Flatpak app instead. And I am fully satisfied with this choice!

So for me this ticket is no longer necessary if you prefer Flatpak (#83)

**Comment by gfrenoy** [comment]
Thanks for your feedback.

I would believe Snap will forever remain something very focused on Canonical so we may want to start with a more universal package system.

So let's close this for now.
