### ISSUE TITLE
Can´t select cluster from PCC

### ISSUE THREAD

**Issue by AlexGaliana79** [asbru-cm/asbru-cm#970]
**Describe the bug**
Is not possible to select cluster in PCC "send to cluster" option

**To Reproduce**
1. Go to PCC
2. Try to Click on 'send to cluster' to see the available clusters 
3. When Click, nothing happens. No cluster list appear

**Expected behavior**
Having some clusters configured, cluster list should appear in PCC. It seems to be disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/110658544/183024094-b3303080-259f-48c6-bf20-61ffcee6b265.png)

**Environment (please complete the following information):**
 - OS: Linux Mint 20.3-Una
 - Ásbrú Version 6.4.0

**Comment by gfrenoy** [comment]
Hi Alex.  You need to have a *running* clusters to send commands to it.

So, first, start your cluster.  Then, start PCC and you'll have the option to send command to the started cluster.

Does that make sense?
