### ISSUE TITLE
Please modify to install mint 21 vanessa

### ISSUE THREAD

**Issue by SvenPausH** [asbru-cm/asbru-cm#972]
**Describe the bug**
I can´t install Asbru on Linux Mint 21 Vanessa

**To Reproduce**
root@pc-sven:/home# curl -s https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh | sudo bash
Detected operating system as LinuxMint/vanessa.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/asbru-cm_asbru-cm.list...curl: (22) The requested URL returned error: 404

Unable to download repo config from: https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/config_file.list?os=LinuxMint&dist=vanessa&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

**Environment (please complete the following information):**
Linux Mint 21 Vanessa \n \l

**Comment by SamAdum** [comment]
What I did to get it working (only for mint 21 !)
Get the install script
`wget https://packagecloud.io/install/repositories/asbru-cm/asbru-cm/script.deb.sh`
edit the file and modify the lines (around lines 101-103) : 
```
# remove whitespace from OS and dist name
os="${os// /}"
dist="${dist// /}"
```
With
```
# remove whitespace from OS and dist name
os="ubuntu"
dist="jammy"
```
execute installation script

**Comment by SamAdum** [comment]
> Your script without changes show:
> Detected operating system as LinuxMint/vanessa.

Yes.The mint version is detected correctly by the script but the according file is missing on the cloudsmith.io server. So, after detection, I just forced to ubuntu/jammy. This is not clean but it works until the missing file is added on cloudsmith.io

**Comment by gfrenoy** [comment]
Mint 21 "Vanessa" build is now available in our `loki` branch.
