### ISSUE TITLE
AsbruCM breaks when moved to another display

### ISSUE THREAD

**Issue by SlavaSafronov** [asbru-cm/asbru-cm#973]
Hi all, 
new here, so please do not blame for being unprofessional.  
Have been working with asbru for quite a while on Ubuntu 18.04, then upgraded to 20.04 - all worked well. 
After an upgrade to 22.04 noticed that if the window of the asbru cm is moved to another display it gets broken. The screen of the connection manager is cut, only a left upper quarter is shown, and the connections are not clickable. 

Laptop Dell Latitude 7490, 2 monitors 24'' connected to the docking station.
```
$ asbru-cm --version
INFO: Ásbrú Connection Manager 6.3.3 (asbru-cm) started with PID 53033
INFO: Language detected : en_US.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : gnome-shell:ubuntu
INFO: Config directory is '/home/slavas/.config/asbru'
INFO: Used config file '/home/slavas/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.68
GLib-GObject-WARNING **: invalid (NULL) pointer instance at /opt/asbru/lib/PACMain.pm line 4910.
GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed at /opt/asbru/lib/PACMain.pm line 4910.
INFO: Theme directory is '/opt/asbru/res/themes/asbru-color'
INFO: No tray available

(asbru-cm:53033): Gtk-CRITICAL **: 14:20:43.740: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
```

It is reproducible sporadically, open cm on full screen, work for a while, then try to move to another screen and you sometimes get the bad outcome. The issue started happening after the upgrade to Ubuntu 22.04.  

See the screenshot below, the titles are blurred for security reasons (working with production) and not as the result of the bug.
If there are logs that I can collect and share please let me know where to get them. 

![asbru-broken](https://user-images.githubusercontent.com/31385582/187423084-a1edf063-85c2-43eb-bfab-54740b9647a1.jpg)

**Comment by scontin** [comment]
me too.

**Comment by SlavaSafronov** [comment]
I actually found out - probably it is the Wayland bug. If I switch to x11, asbru-cm starts working normally. Please check.

**Comment by scontin** [comment]
I have no wayland on Kde neon:

scontin@Urania:~$ echo $XDG_SESSION_TYPE
x11

**Comment by gfrenoy** [comment]
This issue could not be reproduced on our test environments and is quite old.  Let's close it for now.  Feel free to open a new one if you have more details about the environment where the problem happens.
