### ISSUE TITLE
Asburu frezze when config folder on network path

### ISSUE THREAD

**Issue by kyocooro** [asbru-cm/asbru-cm#976]
**To Reproduce**
1. run with --config-dir parameter ./asbru-cm --config-dir=//config
2. See error
INFO: Using Gnome tray icon
*** unhandled exception in callback:
***   ERROR:No such file or directory at ~/asbru-cm/lib/PACTerminal.pm line 222.
***  ignoring at /usr/share/perl5/Gtk3.pm line 572.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Parrot OS 5
 - Ásbrú Connection Manager 6.3.4

**Comment by popxunga** [comment]
Have a look into issue #909 and give a try with Asbru loki build.

**Comment by kyocooro** [comment]
> Have a look into issue #909 and give a try with Asbru loki build.

Thank you, its works
