### ISSUE TITLE
grey tab after a number of connections

### ISSUE THREAD

**Issue by dennisTGC** [asbru-cm/asbru-cm#978]
If I open too many connections (9 in this case), the connection won't complete and the tab becomes grey:
![image](https://user-images.githubusercontent.com/12065502/193235622-975a4b8d-2d36-4ba9-8566-ec13afb940ce.png)

The tabs aren't responsive after, but I can close asbru normally (it even comes with the warning to close the existing sessions). 

In the logs it says:
```
*** unhandled exception in callback:
***   ERROR:Address already in use at /opt/asbru/lib/PACTerminal.pm line 228.
***  ignoring at /usr/lib/x86_64-linux-gnu/perl5/5.34/Glib/Object/Introspection.pm line 67.
```

I'm on kubuntu 22.04.1 
GDK_BACKEND=x11 
asbru v6.3.3

The issue is reproducable, let me know if I can submit logs or give more info.

**Comment by gfrenoy** [comment]
Are you opening the 9 connections at the same time ?
Do you open several times the same connection ?

**Comment by dennisTGC** [comment]
I open them consecutively and i use different connections. Sometimes the same, but I tested with all different connections.

**Comment by gfrenoy** [comment]
Sorry but I cannot reproduce that one.  Let me ask a few more questions to understand.

The error says an address is already in use.  But Ásbrú is supposed to test if the socket is available before creating it.

Does this always happen after the 9th connection?
Do you have other instances running?
Do you mind trying with 6.4.0?  Do you encounter the same behavior?

**Comment by dennisTGC** [comment]
sorry, I forgotten about this thread. I tried v6.4.0, and yes I have other instances running and it happens randomly but mostly with multiple connections. 

I don't think I'm seeing it while I have a single instance. Is there a way to see the socket behaviour?

**Comment by gfrenoy** [comment]
Dennis, really sorry but I don't understand how I can reproduce this.  Here I can run dozens en dozens of connections without any problem.

I don't say it does not happen to you, I just say you need to provide more information so that we can fix it...

Maybe starting from a new configuration file ?  You can use a brand new configuration directory using `--config-dir=/tmp/asbru`, reproduce the issue and then send us the screencast or anything that can help...

Thanks for your help !

**Comment by dennisTGC** [comment]
Ok, I'm not sure what is happening here, but on Kubuntu 22.10 with asbru-cm I don't have the issue. I just started 90 connections and no grey tabs.. lets call this a fluke and close it. If I get more data on this issue, I will add it. Let me know if I can do anything more to troubleshoot this.

I already use `--config-dir` as I use them for seperating environments, #995.
