### ISSUE TITLE
Cluster explode: window sizes and placement are incorrect

### ISSUE THREAD

**Issue by gentunian** [asbru-cm/asbru-cm#98]
When exploding a cluster, windows sizes and windows placement are incorrect.

This is happening on fedora 27 with a custom openbox. This is a screenshot:

![selection_119](https://user-images.githubusercontent.com/1090113/42944749-ded37e5e-8b3c-11e8-9add-8d2c14e83d1d.png)

The upper left window is well placed, but its height overlaps with the window below (or viceversa). In yellow the area overlapped.
The upper right window overlaps with my desktop panel and its height overlaps with the window below.

### Versions:
Linux: 4.17.3-100.fc27.x86_64 #1 SMP Tue Jun 26 14:19:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Openbox: 3.6.1

**Comment by gentunian** [comment]
@gfrenoy thanks for replying and locating the code. My guess is that this is a GTK issue. For example, I've tested this code:

```perl
# Move it to its corresponding position, hardcoded 0 y-axis
$$terminal{_WINDOWTERMINAL} -> move( $defw * $col, 0 );
```

The first terminal, that is `(0, 0)` point is well placed below the panel. The second terminal, that is `(terminalWidth, 0)` is misplaced overlapping the panel. I don't think this has something to do with PAC/asbru code but instead with the window manager.

Did you test this with another window manager? I'm not quite familiar with GTK development and I'm not sure if GTK is the responsible of placing the window or the underlying window manager implemented in GTK.

**Comment by gfrenoy** [comment]
I'm using Ubuntu 16.04 (on Gnome) and terminals position are not perfect either.  The overlapping space seems to correspond to the upper top bar and left task bar.

The question is : what is the reliable way to get the available space so we can calculate the terminal size accordingly ?

**Comment by gentunian** [comment]
@gfrenoy not sure, I think it's still a GTK problem. You may have panels at top, bottom and both sides.

I did another test with this code:

```perl
# Move it to its corresponding position, hardcode 1 to X position
$$terminal{_WINDOWTERMINAL} -> move(1, $defh * $row);
```

and effectively, the window overlaps the panel. So, my guess again is that GTK treat only `(0, 0)` (or maybe corner cases) as special cases where to place a window considering panels. As soon as you move away from `(0, 0)` the placement is done in the absolute screen position.

GTK may treat panels as special windows that reduce your viewport or have methods that gives you the screen size/ placement of windows taking them into account.

**Comment by gentunian** [comment]
Making a little research it seems that GTK has this option but panels needs to adhere to them: https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm140130317566832

see _NET_WM_STRUT and _NET_WM_STRUT_PARTIAL

**Comment by gentunian** [comment]
I think there are 2 issues hidden. 

First, GTK (or the window manager) is not placing windows correctly. The second one, is that decorations are not taking into account of the window size. LXPANEL seems to be doing its job correctly of setting panel constraints (see gif). When you located a window not being at `(0, 0)`, then, GTK places the window absolutely.

![asbru](https://user-images.githubusercontent.com/1090113/43373608-173817c2-9381-11e8-8568-fe86d1df85fc.gif)

Not sure how to solve these issues.

**Comment by KlaasT** [comment]
This should be fixed now with the great help of @hanspr
