### ISSUE TITLE
Typo error on Manual installation docs

### ISSUE THREAD

**Issue by jrichardsz** [asbru-cm/asbru-cm#980]
**Describe the bug**
In https://github.com/asbru-cm/asbru-cm/wiki/Manual-installation#start-application after `cd asbru-cm` , the line `./absru` is wrong

**To Reproduce**
1. Go to  https://github.com/asbru-cm/asbru-cm/wiki/Manual-installation#start-application
2. See error

**Expected behavior**
It should be:

`
./asbru-cm
`

**Screenshots**

![image](https://user-images.githubusercontent.com/3322836/193697278-2ca76922-fa08-4040-993d-0f6a78afe9f4.png)

**Comment by gfrenoy** [comment]
Thanks a lot for the feedback !  It is fixed now.
