### ISSUE TITLE
Save and Close it's doesn't work

### ISSUE THREAD

**Issue by c0r3dump3d** [asbru-cm/asbru-cm#985]
**Describe the bug**
The button "Save and Close" it's doesn't work
![imagen](https://user-images.githubusercontent.com/5602401/201335457-b53147d6-a0d7-447a-aba0-afc4927cf489.png)

**To Reproduce**
1. Go to 'Edit connection'
2. Click on 'Save and Close'
3. It's doesn't save and close. I see this exception:
```
WARNING: The key derivation method "opensslv1" is deprecated. Using -pbkdf=>'pbkdf2' would be better.
Pass -nodeprecate=>1 to inhibit this message.
 at /opt/asbru-cm/lib/PACUtils.pm line 2718.
*** unhandled exception in callback:
***   Salt must be exactly 8 bytes long at /opt/asbru-cm/lib/PACUtils.pm line 2718.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 572.
```

**Expected behavior**
Close Edit connection window and save the connection

**Environment (please complete the following information):**
 - OS: Arch Linux Manjaro
 - Ásbrú Version: 6.3.4

**Additional context**
 -Install with: `yay -S asbru-cm-git`

**Comment by gfrenoy** [comment]
Try version 6.4.0 on the `loki` branch or wait for the next stable release.

See #858 and many other duplicates.
