### ISSUE TITLE
QUESTION: How to decrypt passwords in asbru.yml using openssl?

### ISSUE THREAD

**Issue by ingmaf** [asbru-cm/asbru-cm#986]
Hello,

I have an `asbru.yml` backup file and I need to access to saved passwords.

I searched on this GitHub and, as far as I understand, Asbru uses blowfish in CBC mode to encrypt passwords. Then, I put a sample password into a `password.txt` file and I tried to use OpenSSL using the following commands:
- `openssl enc -bf-cbc -d -in password.txt`
- `openssl enc -bf-cbc -d -pbkdf2 -in password.txt`
- `openssl enc -bf-cbc -d -a -in password.txt`
- `openssl enc -bf-cbc -d -pbkdf2 -a -in password.txt`

When asked, in all cases, I use `PAC Manager (David Torrejon Vaquerizas, david.tv@gmail.com)` as the decryption password. All my attempts failed with openssl reporting `bad magic number`.

Also, looking again at `asbru.yml` I noted that there a `passphrase` keyword for each connetion entry. Then, I put that passphrase into a `passphrase.txt` and repeat above commands. Again, without success at all :(.

Can you please tell me how to proceed in my case?

Thank you very much in advance for your answer.
Regards.

**Comment by gfrenoy** [comment]
First, let's highlight `asbru.yml` is not a safe place to store your passwords ... You should use KeyPassXC to store any sensitive information.

Then, the way I would do it is to write a small perl script that mimics the way Ásbrú is reading the configuration file.  [`_decipherCFG`](https://github.com/asbru-cm/asbru-cm/blob/master/lib/PACUtils.pm#L2750-L2803) is probably the place to start.

**Comment by ingmaf** [comment]
First of all, thanks for your expedite answer Gaetan!

I know saving passwords in .yml is a bad idea but my use case is for lab connections so it's fine by us to do it that way.

Anyway, I looked at code you pointed me but I don't understand it, such a pity. Could you please give me a tip about how Asbru stores password?

Thanks again.

**Comment by gfrenoy** [comment]
Probably better to take this elsewhere, this place is not a discussion forum but a place to report issues and suggest enhancements for Ásbrú.  See our contact page on the public website.
