### ISSUE TITLE
Main window not showing

### ISSUE THREAD

**Issue by gabe-fr** [asbru-cm/asbru-cm#988]
Hello,

On Debian 11 with XFCE, the Asbru-cm 6.4.0 has a blank window, with local terminal or saved SSH entries.

The terminal output is :
`INFO: Ásbrú Connection Manager 6.4.0 (asbru-cm) started with PID 64639
INFO: Language detected : fr_FR.UTF-8, forcing to en_US.UTF-8
INFO: Desktop environment detected : xfce
INFO: Config directory is '/home/gabe/.config/asbru'
INFO: Used config file '/home/gabe/.config/asbru/asbru.nfreeze'
INFO: Virtual terminal emulator (VTE) version is 0.62
INFO: Theme directory is '/opt/asbru/res/themes/default'
INFO: Trying to loading Unity specific tray icon package...
INFO: Using Unity tray icon
Use of uninitialized value in hash element at /opt/asbru/lib/PACMain.pm line 3561.
*** unhandled exception in callback:
***   Can't locate object method "set_status" via package "Gtk3::ToggleButton" at /opt/asbru/lib/PACTrayUnity.pm line 178.
***  ignoring at /usr/share/perl5/Gtk3.pm line 572.
`
But preferences menu is ok.
Also, the "_Quit_" bouton doesn't work, I need to _kill_ the process.

**Comment by gfrenoy** [comment]
Thanks for the feedback.  I'll need to setup a XFCE environment to test this but my guess is indeed that it should not try to use any "systray" with XFCE, even if "Inconified in 'systray'" is checked.  Here it is trying and merely fails :-/

**Comment by gfrenoy** [comment]
I tested Ásbrú on a fresh Debian 11.5 Bullseye XFCE live CD.  All is working as expected so there must be something special with your configuration.

Would you mind providing a screenshot of your environment ?  And some details about the exact version you have, including Gtk?

**Comment by gabe-fr** [comment]
What do you mean exactly about about "a screenshot of your environment" ?
I am using Debian 11.5 Stable, updated with last updates.
[gtk_packages.txt](https://github.com/asbru-cm/asbru-cm/files/10064788/gtk_packages.txt)

**Comment by gfrenoy** [comment]
> What do you mean exactly about about "a screenshot of your environment" ?

Just a screenshot of what you see on your screen... So I can compare this to what I see on mine.

> I am using Debian 11.5 Stable, updated with last updates.

Yes, same here but no issue.  Sorry, I cannot reproduce.  You may way to try with the latest version in the [snapshot](https://docs.asbru-cm.net/General/Installation/) release, it'll hopefully work for you as well.
