### ISSUE TITLE
Expect seems to be failing when identifying command prompt

### ISSUE THREAD

**Issue by payen-sprice** [asbru-cm/asbru-cm#989]
Hi

**Description of problem**
It seems that in the latest version (6.4.0) the expect behaviour isn't working for me and seems to be failing to identify the command prompt to continue.  I can see that in the status history it is showing:
EXPECT:WAITING:[#%\$>]|\:\/\s*$
then after a period of time
CLOSE:TIMEOUT:60 Seconds expecting pattern [#%\$>]|\:\/\s*$

**To Reproduce**
1. have something configured to run in the expect configuration
2. Prompt is showing as [username@server ~]$ 
3. when connecting and after logging is successfully it times out waiting for command prompt

**Expected behaviour**
Recognise prompt and continue to expect configured expect commands

**Environment (please complete the following information):**
 - OS: Fedora 35
 - Ásbrú Version [6.4.0]

Confirmed on a separate system that 6.3.3 is working as expected.

**Comment by payen-sprice** [comment]
Hi, yes, it all looked the same and double checked the command prompt option in main options -> advanced and they are the identicle.

**Comment by payen-sprice** [comment]
Just downgraded to 6.3.3 using the same config on the machine causing trouble and it is working as expected

**Comment by gfrenoy** [comment]
Would you have a dummy configuration file you can share with an example ?  You can create a dedicated configuration with the option `--config-dir=/tmp/asbru-test` ?  That would help reproducing the issue.

Did you check Hans' article --> https://docs.asbru-cm.net/Managing/Expect/ ?

**Comment by payen-sprice** [comment]
Thanks for the pointer.  Using the debug option I can see what its looking for and traced it back to the option of:

expect: '<command prompt>'.  

This option seems to have been around for a long time in my configuration, including pre-asbru days. I created a connection from scratch and noticed that this is not present by default:

expect: ''

Changing existing connections to expect: '' works so that seems to be the root of the problem.

**Comment by gfrenoy** [comment]
Good so can we consider this closed ?

**Comment by payen-sprice** [comment]
Hi,

Just realised what I types meant to put in the previous message didnt output as I wanted due to markup.  So what I had in my configuration was:

expect: '\<command prompt\>'

And this was causing the problem.  I am happy that my issue is now resolved as I can remove this, but just to highlight that this being present in the configuration worked in the previous version but did work in 6.4.0

Happy to close and let you decide what to do with that information.
