### ISSUE TITLE
Local shell (bash) instant disconnect

### ISSUE THREAD

**Issue by kioan** [asbru-cm/asbru-cm#992]
**Describe the bug**
After the latest Asbru update (v6.4.0), it is impossible to open new tabs with local shell.

**To Reproduce**
1. Go to main window
2. Click on 'Local shell' button
3. A new tab opens and instantly is shows "DISCONNECTED (PRESS <ENTER> TO RECONNECT)"

**Expected behavior**
The newly opened local shell tab should stay connected

**Screenshots**
![asbru](https://user-images.githubusercontent.com/798405/202204355-bbd5e966-f364-4a68-9bb7-fe80c9f868f6.png)
![asbru-shell](https://user-images.githubusercontent.com/798405/202205632-b18f8f91-d0fb-4a86-8569-56ca44f5d073.png)

**Environment (please complete the following information):**
 - OS: Kubuntu 22.04 with KDE Plasma 5.24.6
 - Ásbrú Version 6.4.0

**Additional context**

**Comment by gfrenoy** [comment]
Can you try with the explicit "Initial Directory" (eg /home/user) or when leaving that option empty ?

**Comment by kioan** [comment]
Thank you! I changed it so that it points to the full path of my home directory and now it works.

Before the last update it was working just with the `~`. Perhaps it needs to be checked if the latest Ásbrú version sets the tilde as the default value in this field.

**Comment by gfrenoy** [comment]
The given path is not now surrounded by quotes so that it can accept space into it.  But this will prevent the "tilde" from working, we can now win on all aspects :(  I'll update the documentation accordingly.

**Comment by gfrenoy** [comment]
See https://docs.asbru-cm.net/Manual/Preferences/ShellOptions/

![image](https://user-images.githubusercontent.com/981546/202929380-4c760d35-fd3b-4789-a2b6-cff366ddfd73.png)
