### ISSUE TITLE
Add wlfreerdp support

### ISSUE THREAD

**Issue by nerijus** [asbru-cm/asbru-cm#993]
freerdp added wlfreerdp (FreeRDP wayland client) along with xfreerdp recently.
```
rpm -qi freerdp
Name        : freerdp
Version     : 2.8.0
Release     : 1.fc36
...
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.freerdp.com/
Bug URL     : https://bugz.fedoraproject.org/freerdp
Summary     : Free implementation of the Remote Desktop Protocol (RDP)
Description :
The xfreerdp & wlfreerdp Remote Desktop Protocol (RDP) clients from the FreeRDP
project.

xfreerdp & wlfreerdp can connect to RDP servers such as Microsoft Windows
machines, xrdp and VirtualBox.
```
Could you please add support for it too? It supports most of the xfreerdp options.

**Comment by gfrenoy** [comment]
Thanks for your suggestion, it is already in our list, see #974 :)

If you look for a quick fix and if this an option for you, try to have a global alias `xfreerdp` and use the `xfreerdp` option.
