### ISSUE TITLE
Asbru in read-only mode when using multiple instances

### ISSUE THREAD

**Issue by dennisTGC** [asbru-cm/asbru-cm#995]
**Describe the bug**
I have this issue (reproducable) if I have multiple asbru-cm applications open. I start asbru with the following command:

asbru-cm --config-dir='/home/someurl/Asbru/Asbru-customers1'

and a different session goes to customers2. Only the setting of the first started asbru get saved. I also have the setting Automatically save every configuration change turned on. v6.4.1 (loki) on ubuntu 22.04.1 and v6.4.0 on ubuntu 22.10

**To Reproduce**
1.  Start asbru(1) with --config-dir parameter
2. Start another asbru(2) with --config-dir parameter
3. make a change in asbru(2), like clone connection
4. See the save button change to "read-only" and none of the changes are saved. 

**Expected behavior**
I expect there are no configuration items shared between the first asbru and the second as I'm using different config-dirs for them. So I expect the second asbru to be able to save changes like a new connection.

**Screenshots**
asbru-cm(2)
![image](https://user-images.githubusercontent.com/12065502/202291461-b9d68790-f628-4f4d-bc59-bbef323f7afc.png)
console output:
```
INFO: Ásbrú is already running.
INFO: Starting '/usr/bin/asbru-cm' in READ ONLY mode!
```

**Environment (please complete the following information):**
 - OS: reproducable on 2 systems (Dell XPS13)
 Ubuntu 22.04.1 (freshly installed) with v6.4.1-loki
Ubuntu 22.10 with v6.4.0

**Comment by gfrenoy** [comment]
Do you have the option `Allow more than one instance to run at the same time` checked ?
![image](https://user-images.githubusercontent.com/981546/202298356-3b9f6e5d-07d0-40bf-b694-f425dcabc8c4.png)

**Comment by dennisTGC** [comment]
Yes, else i can't run multiple instances.. ;-)

**Comment by gfrenoy** [comment]
Interesting ;)  Thanks for the feedback.

I read the code and I believe this behavior has been coded on purpose from the time when it was not possible to have different configuration directories !  See https://github.com/asbru-cm/asbru-cm/blob/6.4.0/lib/PACMain.pm#L285-L298.

So the idea was : you can run multiple instances but the second one is always "read only".

We need an enhancement to check if the other instance is running with the same configuration directory (or not).  And only if it's the same, to run the other ones in read-only mode.

**Comment by dennisTGC** [comment]
Im running v6.5.0 and it is fixed!

:tada: :birthday: 

I'm gonna look how to donate to you, havent done cryptocurrency transfer yet and I don't have paypal anymore.
