### ISSUE TITLE
Telnet connection not connected successfully.

### ISSUE THREAD

**Issue by manohar199** [asbru-cm/asbru-cm#996]
![IMG_20221117_104807](https://user-images.githubusercontent.com/77186340/202362687-04c4d612-c9f0-404b-a214-ffc890f7ddf9.jpg)
When I connected to The telnet connection connection . It cannot connected successfully.. it show  Tab colour Still red and  

1.Auto login Option creating problem. It diconnected after Timeout

 'Manual' login No issue

2.Status "Spawned"

 Also
3.Auto telnet login connection not complete. And Tab colour remains red colour and not turns green even  after connected  
So I cannot perform saved  remote Commands (Preferences)

Bug observed since  16.11.2022..

UBUNTU 18.04(Bionic)

**Comment by manohar199** [comment]
> ![IMG_20221117_104807](https://user-images.githubusercontent.com/77186340/202362687-04c4d612-c9f0-404b-a214-ffc890f7ddf9.jpg) When I connected to The telnet connection connection . It cannot connected successfully.. it show Tab colour Still red and
> 
> Auto login Option creating problem. It diconnected after Timeout
> 
> 'Manual' login No issue
> 
> "status Spwned".
> 
> Bug observed since 16.11.2022..
Ubuntu 18.04

**Comment by manohar199** [comment]
> > Bug observed since 16.11.2022
> 
> Do you mean it was working before that date ? Did you upgrade to 6.4.0 ? What version are you running ?

Yes I updated. 6.40

**Comment by gfrenoy** [comment]
Strange.  I made some tests on my side and all looks to work fine.  There muse be something special in your configuration.  It looks like it does not detect the command prompt correctly.

Here are a few suggestions:
  - Enable the `Expect DEBUG` option in `Terminal Options` > `Advanced` and al
  - Check if your `Command Prompt` regular expression (see `Main Options` > `Advanced`) is properly detecting your prompt

**Comment by manohar199** [comment]
> Strange. I made some tests on my side and all looks to work fine. There muse be something special in your configuration. It looks like it does not detect the command prompt correctly.
> 
> Here are a few suggestions:
> 
> * Enable the `Expect DEBUG` option in `Terminal Options` > `Advanced` and al
> * Check if your `Command Prompt` regular expression (see `Main Options` > `Advanced`) is properly detecting your prompt
> * Check if it has anything to do with [autologin on telnet sessions should send \r instead of \n #967](https://github.com/asbru-cm/asbru-cm/issues/967)

Command prompt regular expression Missmatching during "Password prompt"

**Comment by gfrenoy** [comment]
As far as can I see, the password is sent but there is no reaction from the telnet server.  Ásbrú is waiting for some output to analyse further...

Did you try hitting on "ENTER" while it is waiting?

Or can you try changing `\n` into `\r` in the following lines:

User:
https://github.com/asbru-cm/asbru-cm/blob/6.4.0/lib/asbru_conn#L1784

Password:
https://github.com/asbru-cm/asbru-cm/blob/6.4.0/lib/asbru_conn#L1809

**Comment by manohar199** [comment]
> As far as can I see, the password is sent but there is no reaction from the telnet server. Ásbrú is waiting for some output to analyse further...
> 
> Did you try hitting on "ENTER" while it is waiting?
> 
> Or can you try changing `\n` into `\r` in the following lines:
> 
> User: https://github.com/asbru-cm/asbru-cm/blob/6.4.0/lib/asbru_conn#L1784
> 
> Password: https://github.com/asbru-cm/asbru-cm/blob/6.4.0/lib/asbru_conn#L1809

Not working

**Comment by mdub121** [comment]
Hi, I have the same issue. Problem started with 6.4 release and is related to: https://github.com/asbru-cm/asbru-cm/issues/904
New default command prompt 
`(([#%:>~\$\] ])(?!\g{-1})){3,4}|(\w[@\/]\w|sftp).*?[#%>~\$\]]|([\w\-\.]+)[%>\$\]]( |\033)|^[#%\$>\:\]~] *$`
 does not work with i.e. network devices like cisco switches/routers with simple prompt like "router>" or "router#".
There is no problem if "Manual" authentication is used, but when "User/Password" is selected, then after sending Password it is looking for prompt, which it cannot find with this new 'extended' regex.
Would it be possible to add also support for these simple prompts as it works before?

**Comment by preussal** [comment]
Hi i have the similar same Issue, but with SSH.

if i use this export line in the .bashrc
`export PS1='\[\033[1;33m\]\u\[\033[1;37m\]@\[\033[1;32m\]$(hostname -f)\[\033[1;37m\]:\[\033[1;31m\]\w \[\033[1;36m\]\$ \[\033[0m\]'`
then the connection are created but hang. with Spawn ....
![grafik](https://user-images.githubusercontent.com/26431172/209641592-dddbd933-cac8-43dc-86f8-f62d395a0c21.png)

Normal SSH over Terminal working Fine.
then i change the export to
`export PS1='\u@\h:\w\$ '`
then is working
![grafik](https://user-images.githubusercontent.com/26431172/209641888-3404ee86-9536-4179-886a-ed8414d465db.png)

i try a downgrade to 6.3.3-1 
but make now no different
