### ISSUE TITLE
Left click on tray icon is not showing main window since update to 6.4.1

### ISSUE THREAD

**Issue by plazarch** [asbru-cm/asbru-cm#997]
Since updating to 6.4.1 a left click on the tray icon shows the dropdown menu the same as a right click.  In previous versions a left click on the tray menu would immediatly open the main window.  I looked through the options and can't see a way to change this behavior.  Am I missing the option or is there a way change change the left click behavior of the tray icon?

**To Reproduce**
Install version 6.4.1
left click on the tray icon

**Expected behavior**
The main window would open

**Screenshots**
![asbru-menu](https://user-images.githubusercontent.com/16919300/202918118-e7633983-5cdc-43bb-a958-9a4e7c6ad56e.png)

**Environment (please complete the following information):**
 - OS: Rocky Linux 8.7
 - Ásbrú Version 6.4.1

**Additional context**
XFCE v4.16

**Comment by gfrenoy** [comment]
This is likely because Ásbrú is detecting  `AppIndicator3` or `AyatanaAppIndicator3` and is using it instead of the legacy `Gtk3::StatusIcon` method.  See also #870, #872, #880, #883 & #884.

I'd think that we only need to use `AppIndicator3` if running in `Unity`.  I'll make the change.

**Comment by gfrenoy** [comment]
Would you have the opportunity to test our new releases on our `snapshot` or `loki` branches ([see instructions here](https://docs.asbru-cm.net/General/Installation/)) ?

Unless you are using Unity, the left click should show/hide the Ásbrú main window.

**Comment by plazarch** [comment]
> Would you have the opportunity to test our new releases on our `snapshot` or `loki` branches ([see instructions here](https://docs.asbru-cm.net/General/Installation/)) ?
> 
> Unless you are using Unity, the left click should show/hide the Ásbrú main window.

I installed the snapshot verison and the dropdown menu now has the expected results.  Left click opens the main window, and right click drops down the menu. You people are awesome with the quick response and fix.  Thank you so much.
