### ISSUE TITLE
Local shell doesn't open

### ISSUE THREAD

**Issue by l00v3** [asbru-cm/asbru-cm#999]
**Describe the bug**
When clicking on "Local shell" (or Ctrl + Shift + t), the shell doesn't open. Expect Debug outputs:

```
[asbru_conn(32153)][PACShell][Local]: !!_PAC_AUTH_[asbru_PID{27024}_n9]!!
[asbru_conn(32153)][PACShell][Local]: GET_TITLE:
[asbru_conn(32153)][PACShell][Local]: SPAWNING:/bin/bash -login
[asbru_conn(32153)][PACShell][Local]: SPAWNED:'/bin/bash -login' (PID:32153)
[asbru_conn(32153)][PACShell][Local]: CONNECTED
[asbru_conn(32153)][PACShell][Local]: DISCONNECTED
```

**To Reproduce**
1. Click on "Local shell" (or Ctrl + Shift + t)

**Expected behavior**
Opens a local shell.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 19.04, Fedora 31 or Arch]: Xubuntu 22.04.1
 - Ásbrú Version [e.g. 6.1.1 or 6.2.0 or loki]: 6.4.0

**Additional context**
It worked before version 6.4.0

I can provide more info if needed. 
Thank you very much for looking into this!

**Comment by gfrenoy** [comment]
Did you check #992 ?

**Comment by l00v3** [comment]
Missed that, thank you! I had a wrong path (because of importing from previous installation with different user), and now it works!
